const BERUFSSCHULE = [
    { key: "beruf_kfz", label: "🔧 KFZ-Mechatronik" },
    { key: "beruf_elektro", label: "⚡ Elektroniker/in" },
    { key: "beruf_tischler", label: "🪵 Tischler/in" },
    { key: "beruf_industriemechaniker", label: "⚙️ Industriemechaniker/in" },
    { key: "beruf_fachinformatiker", label: "💻 Fachinformatiker/in" },
    { key: "beruf_buero", label: "📇 Kaufmann/-frau für Büromanagement" },
    { key: "beruf_verkaeufer", label: "🛒 Verkäufer/in & Einzelhandel" },
    { key: "beruf_pflege", label: "🩺 Pflegefachkraft" },
    { key: "beruf_friseur", label: "✂️ Friseur/in" }
];

const BERUFSSCHULE = [
    { key: "beruf_kfz", label: "🔧 KFZ-Mechatronik" },
    { key: "beruf_elektro", label: "⚡ Elektroniker/in" },
    { key: "beruf_tischler", label: "🪵 Tischler/in" },
    { key: "beruf_industriemechaniker", label: "⚙️ Industriemechaniker/in" },
    { key: "beruf_fachinformatiker", label: "💻 Fachinformatiker/in" },
    { key: "beruf_buero", label: "📇 Kaufmann/-frau für Büromanagement" },
    { key: "beruf_verkaeufer", label: "🛒 Verkäufer/in & Einzelhandel" },
    { key: "beruf_pflege", label: "🩺 Pflegefachkraft" },
    { key: "beruf_friseur", label: "✂️ Friseur/in" }
];

const BERUFS_QUESTIONS = [
    // ============ KFZ-Mechatronik ============
    { id: "q0542", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wofür steht die Abkürzung ABS?", answers: ["Anti-Blockier-System", "Automatik-Brems-Sensor", "Achsen-Balance-Steuerung", "Automatische Bremskraft-Steigerung"], correct: 0, difficulty: "schwer", points: 15, explanation: "ABS verhindert das Blockieren der Räder beim Bremsen." },
    { id: "q0543", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Was ist die Aufgabe des Turboladers?", answers: ["Die angesaugte Luft verdichten", "Kraftstoff einspritzen", "Öl kühlen", "Die Abgase filtern"], correct: 0, difficulty: "schwer", points: 15, explanation: "Mehr Sauerstoff im Zylinder bedeutet mehr Leistung." },
    { id: "q0544", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wofür steht OBD?", answers: ["On-Board-Diagnose", "Öl-Behälter-Druck", "Ohm-Bemessungs-Daten", "Online-Betriebs-Datenbank"], correct: 0, difficulty: "schwer", points: 15, explanation: "Sie überwacht abgasrelevante Systeme und speichert Fehlercodes." },
    { id: "q0545", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wie viele Takte hat ein klassischer Ottomotor?", answers: ["2", "4", "6", "8"], correct: 1, difficulty: "schwer", points: 15, explanation: "Ansaugen, Verdichten, Arbeiten, Ausstoßen." },
    { id: "q0546", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Was bedeutet '205/55 R16' beim Reifen?", answers: ["Breite in mm, Höhe in %, Felge in Zoll", "Luftdruck, Gewicht und Baujahr", "Tragfähigkeit, Tempo und Profil", "Baujahr, Hersteller und Reifentyp"], correct: 0, difficulty: "schwer", points: 15, explanation: "205 mm breit, Verhältnis 55 %, 16 Zoll Felge." },
    { id: "q0547", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Was ist die Aufgabe der Lambdasonde?", answers: ["Restsauerstoff im Abgas messen", "Den Motor kühlen", "Den Zündfunken erzeugen", "Den Reifendruck überwachen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Damit wird das Kraftstoff-Luft-Gemisch geregelt." },
    { id: "q0548", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wofür steht ESP?", answers: ["Elektronisches Stabilitätsprogramm", "Extra Sicherheits-Paket", "Elektro-Servo-Pumpe", "Elektronische Spritzverstellung"], correct: 0, difficulty: "schwer", points: 15, explanation: "ESP bremst gezielt einzelne Räder ab." },
    { id: "q0549", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Aufgabe hat der Katalysator?", answers: ["Schadstoffe im Abgas umwandeln", "Kraftstoff vor dem Motor filtern", "Motoröl im Kreislauf reinigen", "Die Bremskraft verstärken"], correct: 0, difficulty: "schwer", points: 15, explanation: "Er wandelt CO, HC und NOx in weniger schädliche Stoffe um." },
    { id: "q0550", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wozu dient der Ölfilter?", answers: ["Er reinigt das Motoröl", "Er kühlt den Motor", "Er filtert die Ansaugluft", "Er filtert den Kraftstoff"], correct: 0, difficulty: "schwer", points: 15, explanation: "Er hält Abrieb und Schmutzpartikel zurück." },
    { id: "q0551", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Was bewirkt ein Stoßdämpfer?", answers: ["Er dämpft die Schwingungen der Feder", "Er trägt das Gewicht allein", "Er lenkt die Räder", "Er verstärkt den Federweg"], correct: 0, difficulty: "schwer", points: 15, explanation: "Ohne ihn würde das Auto dauerhaft nachwippen." },
    { id: "q0552", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wofür steht die Fahrzeug-Identifizierungsnummer (FIN) im Fahrzeugschein?", answers: ["Zur eindeutigen Identifikation des Fahrzeugs mit Hersteller- und Baureihencode", "Als Nachweis über die letzte durchgeführte Hauptuntersuchung mit Plakettierung", "Als Referenz für die vom Hersteller freigegebenen Motorölsorten und -viskositäten", "Als Beleg über die entrichtete Kfz-Steuer des laufenden Jahres"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die FIN (17-stellig) enthält Hersteller, Baureihe, Motorvariante und eine Seriennummer – sie ist weltweit eindeutig." },
    { id: "q0553", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Nach welcher Vorgabe wird der empfohlene Ölwechsel-Intervall bei modernen Fahrzeugen meist festgelegt?", answers: ["Nach festen Kilometerintervallen oder Zeitabständen gemäß Hersteller-Wartungsplan", "Ausschließlich nach dem prozentualen Ölverschleiß, den das Motorsteuergerät berechnet", "Nach der Anzahl der Motorstarts, da jeder Start den größten Verschleiß verursacht", "Ausschließlich nach der Farbe des Öls beim Sichtcheck durch den Fahrer"], correct: 0, difficulty: "schwer", points: 15, explanation: "Moderne Longlife-Öle erlauben bis zu 30.000 km, aber spätestens nach 2 Jahren oder laut Service-Intervall sollte gewechselt werden." },
    { id: "q0554", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Arbeiten sind in einem standardisierten Inspektionsumfang (Service) nach Fahrzeugwartungsplan enthalten?", answers: ["Prüfung sicherheitsrelevanter Bauteile, Kontrolle der Betriebsflüssigkeiten und Filterwechsel", "Ausschließlich der Austausch von Motoröl und Ölfilter sowie das Nachfüllen von Scheibenwasser", "Lediglich die Sichtkontrolle der Bremsbeläge und das Einstellen der Scheinwerfer", "Nur das Aufladen der Batterie und das Prüfen der Reifenprofiltiefe"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Inspektion umfasst viele Punkte: Motoröl, Bremsflüssigkeit, Kühlmittel, Luftfilter, Keilriemen, Reifen, Beleuchtung und eine Probefahrt." },
    { id: "q0555", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Unter welchen Bedingungen sollte der Reifenfülldruck gemessen und korrigiert werden, um genaue Werte zu erhalten?", answers: ["Bei abgekühlten Reifen mit Umgebungstemperatur, mindestens zwei Stunden nach der letzten Fahrt", "Sofort nach einer längeren Autobahnfahrt im warmen Zustand für realistische Betriebswerte", "Bei frostigen Temperaturen unter 5 °C, weil dann die Reifen besonders steif sind", "Direkt nach dem Aufpumpen an der heißen Tankstellensäule bei laufendem Motor"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei warmen Reifen ist der Druck höher und verfälscht den Messwert. Die Herstellerangabe gilt immer für Kaltreifen." },
    { id: "q0556", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Sicherheitsmaßnahmen sind beim Ausbau eines kompletten Motoraggregats aus dem Fahrzeug zwingend erforderlich?", answers: ["Unterstellböcke für die Achsen, Motorkran mit Tragfähigkeitsprüfung und Sicherung gegen Wegrollen", "Ein hydraulischer Wagenheber unter der Ölwanne reicht für den sicheren Ausbau völlig aus", "Der Motor kann bei eingebauter Antriebswelle einfach nach oben abgezogen werden", "Ein einfacher Rangierwagenheber unter dem Getriebe genügt für den kompletten Ausbau"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei Motorausbau verlagert sich der Schwerpunkt stark – Abstützung der Vorderachse und Sicherung gegen Wegrollen sind Pflicht." },
    { id: "q0557", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Worauf ist beim Einbau eines neuen Zahnriemens zu achten, um Motorschäden zu vermeiden?", answers: ["Auf exakte Übereinstimmung der Steuerzeitenmarkierungen an Kurbelwelle und Nockenwellen", "Der Zahnriemen muss immer mit leichtem Übermaß montiert werden, damit er später nicht reißt", "Die Einbaurichtung ist egal, solange die Zahnflanken sauber und ölfrei sind", "Der Riemen darf ruhig verdreht eingebaut werden, solange die Spannung stimmt"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei falscher Zahnriemenposition kollidieren die Ventile mit den Kolben – Motor-Schaden. Die Spannung muss nach Herstellervorgabe eingestellt werden." },
    { id: "q0558", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Mit welchem Messgerät und in welcher Einstellung wird die Ruhespannung einer Fahrzeugbatterie im 12-V-Bordnetz geprüft?", answers: ["Digital-Multimeter im Gleichspannungsbereich bis 20 V an den Batteriepolen", "Oszilloskop im Wechselspannungsmodus mit 50 Hz Netzfrequenz-Filter", "Strommesszange im Milliampere-Bereich um das Pluskabel herum", "Analoges Amperemeter im Wechselstrombereich in Reihe zum Anlasser"], correct: 0, difficulty: "schwer", points: 15, explanation: "Das Multimeter wird auf Gleichspannung (DC V) gestellt – Ruhespannung ca. 12,6 V, bei laufendem Motor ca. 14,4 V." },
    { id: "q0559", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wie wird eine Fahrzeugsicherung fachgerecht auf ihre Funktionsfähigkeit geprüft?", answers: ["Durch Durchgangsprüfung mit dem Multimeter oder visuelle Kontrolle des Schmelzleiters", "Durch Anschluss an eine 12-Volt-Prüflampe, die bei intakter Sicherung leuchten muss", "Durch Widerstandsmessung mit einem Ohmmeter, der Wert muss genau 0,5 Ohm betragen", "Durch Erhitzen der Sicherung, bis der Schmelzleiter sichtbar aufglüht"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Durchgangspiepser zeigt sofort, ob die Sicherung intakt ist. Eine optische Prüfung auf Schmelzstelle ist ebenfalls üblich." },
    { id: "q0560", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welches Bussystem wird bei modernen Fahrzeugen für die Kommunikation zwischen Motor-, Getriebe- und Bremssystem-Steuergeräten vorrangig eingesetzt?", answers: ["Der CAN-Bus (Controller Area Network) mit einer Übertragungsrate von üblich 500 kBit/s", "Der LIN-Bus als Hauptsystem, der CAN-Bus dient nur für die Komfortfunktionen", "Ein proprietäres Lichtwellenleiter-System namens MOST-Bus für alle Antriebsfunktionen", "Ein einfaches USB-Netzwerk verbindet alle Steuergeräte des Antriebs"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der CAN-Bus (meist 500 kBit/s) verbindet Motor-, ABS-, Airbag- und Komfortsteuergeräte. Es gibt auch Subsysteme wie LIN oder FlexRay." },
    { id: "q0561", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Auswirkung hat ein Masse-Kurzschluss an der CAN-Datenleitung typischerweise auf die Fahrzeugsysteme?", answers: ["Diverse Steuergeräte fallen aus, der Fehlerspeicher füllt sich mit Kommunikationsfehlern", "Die Motorleistung wird automatisch um 50 % gedrosselt, alle übrigen Systeme laufen normal weiter", "Die Zündspule bekommt einen Kurzschluss, der Motor geht sofort aus und lässt sich nicht starten", "Nur die Innenbeleuchtung fällt aus, alle Antriebssysteme arbeiten normal weiter"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei einem Bus-Kurzschluss bricht die Kommunikation zusammen – das Diagnosegerät kann dann ggf. keine Verbindung mehr zu den Steuergeräten aufbauen." },
    { id: "q0562", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Mit welchem Werkzeug wird die Zylinder-Kompression eines Ottomotors gemessen und wie wird der Prüfling angeschlossen?", answers: ["Mit einem Kompressionsprüfer, der anstelle der Zündkerze eingeschraubt wird", "Mit einem Stethoskop, das von außen auf den Ventildeckel aufgesetzt wird", "Mit einem Durchflussmesser, der in den Ansaugtrakt eingesetzt wird", "Mit einer Abgassonde, die in den Auspuffendtopf geschoben wird"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Kompressionsprüfer wird anstelle der Zündkerze eingeschraubt. Bei der Messung müssen alle Zündkerzen ausgebaut und die Drosselklappe geöffnet sein." },
    { id: "q0563", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Funktion übernimmt die Nockenwellen-Ventilsteuerung im Betrieb eines Viertakt-Ottomotors?", answers: ["Sie öffnet und schließt die Ventile passend zur Stellung der Kurbelwelle", "Sie regelt den Förderdruck der Ölpumpe passend zur Drehzahl des Motors", "Sie erzeugt die Zündspannung für die Kerzen über einen eigenen Hallgeber", "Sie mischt Kraftstoff und Luft im richtigen Verhältnis vor der Zündung"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Nockenwelle wird von der Kurbelwelle über Zahnriemen oder Steuerkette angetrieben und öffnet die Ventile exakt im richtigen Arbeitstakt." },
    { id: "q0564", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Messaufgabe hat die Lambdasonde im Abgasstrang eines Ottomotors und wie beeinflusst sie die Motorsteuerung?", answers: ["Sie misst den Sauerstoff im Abgas und ermöglicht die genaue Gemischregelung", "Sie misst die Abgastemperatur vor dem Turbolader und schützt ihn vor Hitze", "Sie erkennt Fehlzündungen am Druckverlauf und meldet sie an die Zündanlage", "Sie misst den Kraftstoffdruck in der Einspritzleiste und regelt die Pumpe"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Lambdasonde (meist vor dem Kat) liefert ein Signal an das Motorsteuergerät, um das Gemisch stöchiometrisch (λ=1) zu regeln." },
    { id: "q0565", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Durch welchen Prozess wird der gespeicherte Ruß im Diesel-Partikelfilter (DPF) bei der aktiven Regeneration unschädlich gemacht?", answers: ["Durch Erhitzen auf etwa 600 °C mittels Nacheinspritzung wird der Ruß verbrannt", "Durch Spülen mit einem Additiv, das den Ruß chemisch auflöst und ausschwemmt", "Durch kurzzeitiges Umkehren der Abgasströmung wird der Ruß herausgeblasen", "Durch Zufuhr von Frischluft kühlt der Filter ab und der Ruß bröckelt heraus"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei der aktiven Regeneration wird Diesel in den Oxidationskat eingespritzt, um die Abgastemperatur zu erhöhen und den Ruß zu verbrennen." },
    { id: "q0566", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Anhand welcher Kriterien wird der Wechselzeitpunkt der Bremsflüssigkeit im hydraulischen Bremssystem bestimmt?", answers: ["Durch Messung des Wassergehalts oder des Siedepunkts mit einem dafür vorgesehenen Prüfgerät", "Nach einer festgelegten Anzahl von Bremsungen, die vom Bremskraftverstärker gezählt werden", "Sobald sich die Farbe der Bremsflüssigkeit von hellgelb nach dunkelbraun verändert hat", "Nach jeweils genau 100.000 Kilometern unabhängig vom Zustand der Flüssigkeit"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bremsflüssigkeit ist hygroskopisch (zieht Wasser). Ein Wassergehalt > 3 % senkt den Siedepunkt drastisch – Wechsel ist Pflicht (oft alle 2 Jahre)." },
    { id: "q0567", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Was versteht man unter dem Sturzwinkel (Radsturz) an der Vorderachse und wie beeinflusst er das Fahrverhalten?", answers: ["Die Neigung der Radebene zur Senkrechten in Fahrtrichtung, beeinflusst die Kurvenstabilität", "Der Winkel zwischen Lenkspindel und Fahrbahn, entscheidend für den Geradeauslauf", "Die Neigung der Radaufhängung nach vorne, verantwortlich für die Lenkungsrückstellung", "Der seitliche Abstand der Räder zur Fahrzeugmitte, wichtig für die Spurweite"], correct: 0, difficulty: "schwer", points: 15, explanation: "Positiver Sturz (oben nach außen) verbessert die Kurvenstabilität; negativer Sturz wird oft bei Sportfahrwerken eingestellt." },
    { id: "q0568", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Wie verhindert das Antiblockiersystem (ABS) das Blockieren der Räder während einer starken Bremsung?", answers: ["Durch pulsierende Bremsdruckregelung an jedem Rad einzeln basierend auf den Raddrehzahlsignalen", "Durch automatische Reduzierung der Gesamtbremskraft auf maximal 50 % des Pedaldrucks", "Durch mechanische Entkopplung der Hinterachse von der Vorderachse beim Bremsen", "Durch vollständiges Öffnen aller Bremsen, sobald ein Rad zu blockieren beginnt"], correct: 0, difficulty: "schwer", points: 15, explanation: "ABS-Sensoren an den Rädern messen die Drehzahl. Bei Blockierneigung wird der Bremsdruck kurzzeitig reduziert und wieder aufgebaut – das spürbare Pumpen am Pedal." },
    { id: "q0569", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Sensordaten werden vom Elektronischen Stabilitätsprogramm (ESP) verarbeitet, um ein Ausbrechen des Fahrzeugs zu erkennen?", answers: ["Raddrehzahlen, Lenkwinkel und die Drehrate um die Hochachse (Gierrate)", "Nur die Raddrehzahlen der angetriebenen Räder im Vergleich zur Fahrzeuggeschwindigkeit", "Die Temperatur der Bremsbeläge und der hydraulische Druck in den Bremsleitungen", "Ausschließlich die Außentemperatur und der Füllstand des Kraftstofftanks"], correct: 0, difficulty: "schwer", points: 15, explanation: "Das ESP gleicht die Daten ab: Lenkwinkel zeigt an, wohin der Fahrer will, Gierrate und Querbeschleunigung zeigen, wohin das Auto tatsächlich fährt. Bei Abweichung wird gezielt gebremst." },
    { id: "q0570", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Auf welchem thermodynamischen Prinzip basiert der Kältekreislauf einer Fahrzeug-Klimaanlage mit Kältemittel?", answers: ["Auf der Wärmeaufnahme bei Verdampfung und Wärmeabgabe bei Kondensation des Kältemittels", "Auf der Temperaturdifferenz zwischen Motorraum und Fahrgastraum, die durch Ventilatoren verstärkt wird", "Auf der elektrischen Kühlung durch Peltier-Elemente, die die Luft aktiv abkühlen", "Auf der Reibung des Kompressorriemens, die kalte Luft in den Innenraum drückt"], correct: 0, difficulty: "schwer", points: 15, explanation: "Das flüssige Kältemittel verdampft im Verdampfer und entzieht dabei Wärme; im Kondensator wird es wieder verflüssigt und gibt die Wärme nach außen ab." },
    { id: "q0571", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Aus welchen Gründen wird eine regelmäßige Wartung der Klimaanlage (Klimaservice) von den Herstellern empfohlen?", answers: ["Für die Kühlleistung, den Erhalt der Dichtungen und gegen Bakterienbildung", "Weil die Anlage bei Nichtbenutzung einfriert und den Kompressor zerstört", "Damit der Kältemittelkreislauf entlüftet wird und keine Blasen entstehen", "Weil sich das Kältemittel sonst in Wasser verwandelt und den Verdampfer flutet"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei stehendem System wandern die Dichtungen aus und das Kältemittel entweicht (ca. 10–15 % pro Jahr). Ein Klimaservice erhält die Leistung und Hygiene." },
    { id: "q0572", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Ab welcher Spannungsebene wird bei Elektro- und Hybridfahrzeugen von Hochvolt (HV) nach geltender Norm gesprochen?", answers: ["Bei Gleichspannung über 60 V oder Wechselspannung über 30 V (Effektivwert)", "Bei Spannungen über der üblichen 400-Volt-Drehstrom-Hausnetzspannung", "Erst bei Spannungen von mehr als 1.000 V Gleich- oder Wechselspannung", "Erst ab genau 230 V Wechselspannung wie im normalen Haushaltsnetz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Nach E-Norm gilt alles über 60 V Gleichspannung (bzw. 30 V Wechselspannung) als Hochvolt – in der Praxis meist 300–800 V." },
    { id: "q0573", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche Arbeitsschritte sind vor dem Öffnen eines Hochvolt-Kabels an einem Elektrofahrzeug verbindlich einzuhalten?", answers: ["Trennen des HV-Service-Steckers und Messen der Spannungsfreiheit mit geeignetem Spannungsprüfer", "Ausklemmen der 12-Volt-Batterie, da das HV-System dadurch automatisch spannungsfrei wird", "Tragen von Nitrilhandschuhen und Schutzbrille, dann kann das Kabel bedenkenlos getrennt werden", "Ein kurzes Antippen des Kabels prüft gefahrlos, ob noch Spannung anliegt"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der HV-Interlock-Stecker trennt die Batterie intern. Danach muss mit einem geeigneten Spannungsprüfer (CAT III/IV) an den HV-Kontakten die Spannungsfreiheit nachgewiesen werden." },
    { id: "q0574", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Welche primäre Funktion erfüllt ein Fahrzeug-Diagnosetester (wie z. B. Bosch, VCDS oder Autel) in der modernen Werkstatt?", answers: ["Auslesen der Fehlerspeicher, Darstellen von Live-Daten und gezielte Ansteuerung von Aktoren", "Er dient ausschließlich dem Rücksetzen der Wartungsanzeige nach durchgeführtem Service", "Er misst die Abgaswerte und berechnet daraus die Abgas-Nachbehandlungs-Strategie", "Er lädt ausschließlich die Fahrzeugbatterie und startet den Motor bei Bedarf"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Tester liest die Fehlercodes (DTC) aus, zeigt Sensorwerte in Echtzeit an und kann Aktuatoren (z. B. Stellmotoren) ansteuern – das ist der Kern jeder modernen Fehlersuche." },
    { id: "q0575", category: "beruf_kfz", area: "beruf", subject: "kfz", question: "Für welche Diagnoseaufgabe wird ein Oszilloskop im KFZ-Bereich hauptsächlich eingesetzt und was stellt es dar?", answers: ["Zur Darstellung elektrischer Signalverläufe über die Zeit, etwa am CAN-Bus", "Zum digitalen Auslesen der Fehlercodes über den OBD-II-Stecker am Fahrzeug", "Zur Messung des Widerstands von Kabelbäumen und einzelnen Steckverbindern", "Zum Auffüllen von Betriebsflüssigkeiten nach vorgegebenen Sollwerten"], correct: 0, difficulty: "schwer", points: 15, explanation: "Mit dem Oszilloskop kann man z. B. die Signale von Hall-Gebern, Klopfsensoren oder CAN-Bus-Nachrichten grafisch beurteilen – Störungen sind so schnell sichtbar." },

    // ============ Elektroniker/in ============
    { id: "q0732", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Wie lauten die fünf Sicherheitsregeln der Elektrotechnik in der richtigen Reihenfolge?", answers: ["Freischalten, sichern, prüfen, erden, abdecken", "Erden, freischalten, messen, abdecken, sichern", "Messen, abdecken, freischalten, erden, sichern", "Sichern, prüfen, freischalten, abdecken, erden"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Reihenfolge ist verbindlich und schützt vor Stromunfällen." },
    { id: "q0733", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Welche Farbe hat der Schutzleiter (PE) nach Norm?", answers: ["Grün-gelb", "Blau", "Braun", "Schwarz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Grün-gelb ist ausschließlich dem Schutzleiter vorbehalten, blau ist der Neutralleiter." },
    { id: "q0734", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Wozu dient ein FI-Schutzschalter (RCD)?", answers: ["Er trennt bei Fehlerströmen und schützt Personen", "Er begrenzt die Spannung im gesamten Stromkreis", "Er misst den Stromverbrauch für die Abrechnung", "Er glättet Spannungsschwankungen im Netz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der RCD vergleicht Hin- und Rückstrom und löst bei einer Differenz (Fehlerstrom) aus." },
    { id: "q0735", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was passiert mit dem Gesamtwiderstand in einer Parallelschaltung?", answers: ["Er wird kleiner als der kleinste Einzelwiderstand", "Er ist die Summe aller beteiligten Widerstände", "Er bleibt unverändert wie bei einem Einzelteil", "Er verdoppelt sich gegenüber dem Einzelwert"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bei Parallelschaltung addieren sich die Leitwerte, der Gesamtwiderstand sinkt." },
    { id: "q0736", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was gibt der Nennstrom einer Sicherung an?", answers: ["Den Strom, den sie dauerhaft führen darf", "Die Spannung, die im Stromkreis anliegt", "Den Widerstand der angeschlossenen Leitung", "Die Länge der zulässigen Leitung"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Sicherung schützt vor allem die Leitung vor Überlastung und Brand." },
    { id: "q0737", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Warum wählt man bei langen Leitungen einen größeren Querschnitt?", answers: ["Um Spannungsfall und Erwärmung zu begrenzen", "Damit die Leitung mechanisch stabiler wird", "Um die Spannung am Ende zu erhöhen", "Um den Widerstand gezielt zu erhöhen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Ein größerer Querschnitt senkt den Leitungswiderstand und damit den Spannungsfall." },
    { id: "q0738", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was bedeutet die Schutzart IP44?", answers: ["Schutz gegen feste Fremdkörper über 1 mm und Spritzwasser", "Schutz gegen Berührung und vollständiges Untertauchen", "Kein besonderer Schutz", "Vollständiger Schutz gegen dauerhaftes Untertauchen in Wasser"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die erste Ziffer steht für Fremdkörper-, die zweite für Wasserschutz." },
    { id: "q0739", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was ist der Unterschied zwischen Gleichstrom und Wechselstrom?", answers: ["Gleichstrom fließt immer in eine Richtung", "Gleichstrom ist grundsätzlich der stärkere", "Beide unterscheiden sich nur im Namen", "Wechselstrom fließt immer nur in eine Richtung"], correct: 0, difficulty: "schwer", points: 15, explanation: "Im deutschen Netz beträgt die Frequenz des Wechselstroms 50 Hz." },

    // ============ Tischler/in ============
    { id: "q0740", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Welches Holz zählt zu den Nadelhölzern?", answers: ["Fichte", "Eiche", "Buche", "Ahorn"], correct: 0, difficulty: "schwer", points: 15, explanation: "Fichte, Kiefer und Tanne sind Nadelhölzer; Eiche und Buche sind Laubhölzer." },
    { id: "q0741", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Welche Holzfeuchte ist für Möbel in beheizten Räumen üblich?", answers: ["Etwa 8 bis 10 Prozent", "Etwa 30 Prozent", "Etwa 50 Prozent", "Etwa 20 Prozent"], correct: 0, difficulty: "schwer", points: 15, explanation: "Zu feuchtes Holz schwindet später und die Verbindungen reißen auf." },
    { id: "q0742", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Was ist eine Zinkenverbindung?", answers: ["Eine Eckverbindung aus ineinandergreifenden Zapfen", "Eine Verbindung mit aufgenageltem Zinkblech", "Eine stumpf verleimte Verbindung ohne Zapfen", "Eine Verbindung ausschließlich mit Holzdübeln"], correct: 0, difficulty: "schwer", points: 15, explanation: "Schwalbenschwanzzinken sind besonders zugfest und ein Qualitätsmerkmal im Möbelbau." },
    { id: "q0743", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Warum arbeitet Holz auch nach der Verarbeitung noch?", answers: ["Es nimmt Feuchtigkeit auf und gibt sie ab", "Es wächst auch nach dem Verbauen weiter", "Es verändert sich durch Lichteinstrahlung", "Es dehnt sich durch Erwärmung dauerhaft aus"], correct: 0, difficulty: "schwer", points: 15, explanation: "Holz quillt und schwindet quer zur Faser deutlich stärker als in Längsrichtung." },
    { id: "q0744", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Wofür wird ein Stechbeitel verwendet?", answers: ["Zum Ausstemmen von Vertiefungen und Zapfenlöchern", "Zum geraden Ablängen von breiten Brettern", "Zum Feinschleifen sichtbarer Oberflächen", "Zum Bohren runder Löcher in Hartholz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Stechbeitel wird mit dem Klüpfel oder von Hand geführt." },
    { id: "q0745", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Was ist Furnier?", answers: ["Ein dünnes Echtholzblatt zum Beschichten", "Eine schützende Lackschicht für Möbel", "Ein Spezialkleber für Holzverbindungen", "Eine Platte aus verpressten Holzspänen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Furniere sind meist 0,5 bis 0,9 mm dick und sparen wertvolles Vollholz." },
    { id: "q0746", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Welche Schutzeinrichtung ist an der Tischkreissäge vorgeschrieben?", answers: ["Spaltkeil und Schutzhaube", "Nur eine Brille", "Keine, wenn man vorsichtig ist", "Ein Warnschild an der Werkstatttür"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Spaltkeil verhindert das Klemmen des Werkstücks und damit gefährliche Rückschläge." },
    { id: "q0747", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Wozu dient eine Absauganlage in der Werkstatt?", answers: ["Sie entfernt gesundheitsschädlichen Holzstaub", "Sie kühlt die Motoren der Maschinen", "Sie erhöht die Drehzahl der Sägeblätter", "Sie beleuchtet den Arbeitsbereich gleichmäßig"], correct: 0, difficulty: "schwer", points: 15, explanation: "Holzstaub gilt als krebserzeugend, besonders Eichen- und Buchenstaub." },

    // ============ Industriemechaniker/in ============
    { id: "q0748", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Womit misst man Längen auf Hundertstelmillimeter genau?", answers: ["Mit der Bügelmessschraube (Mikrometer)", "Mit einem geeichten Gliedermaßstab", "Mit einem gespannten Stahlmaßband", "Mit einem geeichten Zollstock aus Holz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Messschieber schafft üblicherweise 0,05 mm, die Bügelmessschraube 0,01 mm." },
    { id: "q0749", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Was bedeutet die Bezeichnung M8 bei einer Schraube?", answers: ["Metrisches Gewinde mit 8 mm Durchmesser", "Materialgüte der Stufe 8 nach Norm", "Schlüsselweite von 8 mm am Kopf", "Länge von 8 Zentimetern über alles"], correct: 0, difficulty: "schwer", points: 15, explanation: "M steht für metrisches ISO-Gewinde, die Zahl gibt den Außendurchmesser in mm an." },
    { id: "q0750", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Was versteht man unter einer Passung?", answers: ["Das Zusammenspiel der Toleranzen von Welle und Bohrung", "Die Oberflächenfarbe des fertigen Werkstücks", "Die Gesamtlänge eines gefertigten Bauteils", "Das Gewicht des fertigen Bauteils in Gramm"], correct: 0, difficulty: "schwer", points: 15, explanation: "Man unterscheidet Spiel-, Übergangs- und Presspassung." },
    { id: "q0751", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Welches Fertigungsverfahren ist Drehen?", answers: ["Spanendes Verfahren mit rotierendem Werkstück", "Umformendes Verfahren ohne Materialabtrag", "Fügendes Verfahren zum Verbinden von Teilen", "Ein Verfahren zum Gießen flüssigen Metalls"], correct: 0, difficulty: "schwer", points: 15, explanation: "Beim Drehen rotiert das Werkstück, das Werkzeug führt die Vorschubbewegung aus." },
    { id: "q0752", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Wozu dient das Härten von Stahl?", answers: ["Zur Erhöhung von Härte und Verschleißfestigkeit", "Zum Weichmachen für die spätere Bearbeitung", "Zum dauerhaften Schutz vor Rostbildung", "Zur dauerhaften Verbesserung der Leitfähigkeit"], correct: 0, difficulty: "schwer", points: 15, explanation: "Beim Härten wird der Stahl erhitzt und schnell abgeschreckt; danach folgt meist das Anlassen." },
    { id: "q0753", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Was zeigt eine technische Zeichnung in der Vorderansicht?", answers: ["Die Hauptansicht nach Projektionsmethode 1", "Grundsätzlich die Rückseite des Bauteils", "Ausschließlich Maße ohne erkennbare Form", "Immer eine Schnittdarstellung im Inneren"], correct: 0, difficulty: "schwer", points: 15, explanation: "In Europa gilt die Projektionsmethode 1 (Erstwinkelprojektion)." },
    { id: "q0754", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Warum verwendet man beim Zerspanen Kühlschmierstoff?", answers: ["Zur Kühlung, Schmierung und zum Späneabtransport", "Ausschließlich zur Reinigung nach der Arbeit", "Zur farblichen Kennzeichnung des Werkstücks", "Ausschließlich zur Verschönerung der Oberfläche"], correct: 0, difficulty: "schwer", points: 15, explanation: "Kühlschmierstoff verlängert die Standzeit des Werkzeugs und verbessert die Oberfläche." },
    { id: "q0755", category: "beruf_industriemechaniker", area: "beruf", subject: "industriemechaniker", question: "Was ist eine Presspassung?", answers: ["Die Welle ist größer als die Bohrung", "Zwischen den Teilen bleibt immer Spiel", "Die Teile werden nur lose gesteckt", "Zwischen den Teilen bleibt reichlich Spiel"], correct: 0, difficulty: "schwer", points: 15, explanation: "Presspassungen übertragen Kräfte durch Reibschluss, oft mit Erwärmen gefügt." },

    // ============ Fachinformatiker/in ============
    { id: "q0756", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Wofür steht die Abkürzung IP bei einer IP-Adresse?", answers: ["Internet Protocol", "Internal Port", "Info Packet", "International Protocol"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die IP-Adresse identifiziert ein Gerät eindeutig im Netzwerk." },
    { id: "q0757", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Welche Aufgabe hat ein DNS-Server?", answers: ["Er übersetzt Domainnamen in IP-Adressen", "Er speichert eingehende E-Mails zwischen", "Er verschlüsselt Passwörter beim Anmelden", "Er verteilt den Strom im Serverraum gleichmäßig"], correct: 0, difficulty: "schwer", points: 15, explanation: "Ohne DNS müsste man IP-Adressen statt Namen wie beispiel.de eingeben." },
    { id: "q0758", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was bewirkt der SQL-Befehl SELECT?", answers: ["Er liest Daten aus einer Tabelle aus", "Er löscht eine Tabelle", "Er legt einen Benutzer an", "Er legt eine neue Datenbank vollständig an"], correct: 0, difficulty: "schwer", points: 15, explanation: "SELECT ist der Abfragebefehl; DELETE löscht und CREATE legt an." },
    { id: "q0759", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was beschreibt die 3-2-1-Regel bei Backups?", answers: ["3 Kopien, 2 Medien, 1 Kopie außer Haus", "3 Server, 2 Nutzer, 1 Passwort", "3 Tage, 2 Wochen, 1 Monat", "3 Passwörter, 2 Nutzer, 1 Administrator"], correct: 0, difficulty: "schwer", points: 15, explanation: "Sie schützt vor Datenverlust durch Defekt, Diebstahl oder Brand." },
    { id: "q0760", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was ist ein RAID 1?", answers: ["Spiegelung der Daten auf zwei Festplatten", "Aufteilung der Daten auf viele Platten ohne Sicherung", "Eine Datensicherung auf Band", "Verteilung der Daten auf vier Platten ohne Sicherung"], correct: 0, difficulty: "schwer", points: 15, explanation: "RAID 1 erhöht die Ausfallsicherheit, ersetzt aber kein Backup." },
    { id: "q0761", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Wozu dient eine Firewall?", answers: ["Sie filtert den Netzwerkverkehr nach Regeln", "Sie beschleunigt die Internetverbindung", "Sie sichert Daten automatisch auf Band", "Sie kühlt die Serverschränke im Rechenzentrum"], correct: 0, difficulty: "schwer", points: 15, explanation: "Firewalls erlauben oder blockieren Verbindungen anhand von Ports, Adressen und Protokollen." },
    { id: "q0762", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was ist der Unterschied zwischen Hardware und Software?", answers: ["Hardware ist die Technik, Software sind Programme", "Software ist grundsätzlich das Teurere von beidem", "Beide bezeichnen dasselbe mit anderem Namen", "Hardware sind Programme, Software ist die Technik"], correct: 0, difficulty: "schwer", points: 15, explanation: "Hardware ist der physische Teil, Software die Menge der Programme und Daten." },
    { id: "q0763", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was regelt die DSGVO für IT-Betriebe?", answers: ["Den Umgang mit personenbezogenen Daten", "Die Höhe der Ausbildungsvergütung", "Die Kabelfarben im Serverraum", "Die Mindestgröße von Serverräumen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Verstöße können empfindliche Bußgelder nach sich ziehen." },

    // ============ Büromanagement ============
    { id: "q0764", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was bedeutet 'Skonto' auf einer Rechnung?", answers: ["Ein Preisnachlass bei schneller Zahlung", "Ein Zuschlag bei verspäteter Zahlung", "Der auf den Betrag entfallende Steueranteil", "Der Anteil des Gewinns an einer Rechnung"], correct: 0, difficulty: "schwer", points: 15, explanation: "Beispiel: '2 % Skonto bei Zahlung innerhalb von 10 Tagen'." },
    { id: "q0765", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wie hoch ist der reguläre Umsatzsteuersatz in Deutschland?", answers: ["19 Prozent", "7 Prozent", "25 Prozent", "16 Prozent"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der ermäßigte Satz von 7 Prozent gilt etwa für Lebensmittel und Bücher." },
    { id: "q0766", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wodurch kommt ein Kaufvertrag zustande?", answers: ["Durch zwei übereinstimmende Willenserklärungen", "Erst durch die vollständige Bezahlung", "Erst durch die Lieferung der Ware", "Erst durch die schriftliche Bestätigung des Chefs"], correct: 0, difficulty: "schwer", points: 15, explanation: "Antrag und Annahme genügen; ein schriftlicher Vertrag ist meist nicht nötig." },
    { id: "q0767", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was regelt die DIN 5008?", answers: ["Die Gestaltung von Geschäftsbriefen", "Die Maße von Büromöbeln am Arbeitsplatz", "Die zulässigen Arbeitszeiten im Büro", "Die zulässige Helligkeit am Bildschirmarbeitsplatz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Sie legt Abstände, Anschriftfeld und Aufbau von Geschäftsbriefen fest." },
    { id: "q0768", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was ist eine Inventur?", answers: ["Die Erfassung aller Vermögenswerte", "Ein Werbeprospekt für Stammkunden", "Eine Befragung zur Kundenzufriedenheit", "Die jährliche Beurteilung der Mitarbeiter"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Inventur ist gesetzlich vorgeschrieben und Grundlage des Inventars." },
    { id: "q0769", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was ist ein Verzug beim Zahlungsziel?", answers: ["Die verspätete Zahlung nach Fälligkeit", "Ein Preisnachlass bei sofortiger Zahlung", "Eine Zahlung noch vor der Lieferung", "Eine vorzeitige Lieferung vor dem Termin"], correct: 0, difficulty: "schwer", points: 15, explanation: "Nach Verzugseintritt können Verzugszinsen und Mahnkosten verlangt werden." },
    { id: "q0770", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was gehört zu den Aufgaben der Ablageorganisation?", answers: ["Systematisches Ordnen und Aufbewahren von Dokumenten", "Das Bestellen von Waren beim Lieferanten", "Die Einsatzplanung des gesamten Personals", "Die Planung der Werbekampagnen des Betriebs"], correct: 0, difficulty: "schwer", points: 15, explanation: "Wichtig sind einheitliche Ordnungssysteme und die Beachtung von Aufbewahrungsfristen." },
    { id: "q0771", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wie lange müssen Rechnungen handelsrechtlich in der Regel aufbewahrt werden?", answers: ["10 Jahre", "1 Jahr", "3 Monate", "5 Jahre"], correct: 0, difficulty: "schwer", points: 15, explanation: "Buchungsbelege und Jahresabschlüsse unterliegen der zehnjährigen Aufbewahrungsfrist." },

    // ============ Verkäufer/in & Einzelhandel ============
    { id: "q0772", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was ist bei der Warenannahme zuerst zu prüfen?", answers: ["Menge, Art und Zustand laut Lieferschein", "Ausschließlich der ausgezeichnete Verkaufspreis", "Ausschließlich das aufgedruckte Haltbarkeitsdatum", "Ausschließlich die Werbewirkung der Verpackung"], correct: 0, difficulty: "schwer", points: 15, explanation: "Mängel müssen sofort dokumentiert und gemeldet werden." },
    { id: "q0773", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Wie lange beträgt die gesetzliche Gewährleistung auf neue Waren?", answers: ["2 Jahre", "6 Monate", "5 Jahre", "3 Jahre"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Gewährleistung ist gesetzlich, die Garantie dagegen eine freiwillige Zusage des Herstellers." },
    { id: "q0774", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Muss ein Geschäft einwandfreie Ware umtauschen, die dem Kunden nicht gefällt?", answers: ["Nein, ein Umtausch ist dabei freiwillig", "Ja, immer innerhalb von 14 Tagen", "Ja, zeitlich völlig unbegrenzt", "Ja, aber nur gegen einen Gutschein"], correct: 0, difficulty: "schwer", points: 15, explanation: "Im Ladengeschäft besteht kein gesetzliches Umtauschrecht bei Nichtgefallen – anders als im Onlinehandel." },
    { id: "q0775", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was versteht man unter Warenpräsentation?", answers: ["Die verkaufsfördernde Anordnung im Laden", "Die platzsparende Lagerung im Keller", "Die Buchführung über alle Verkäufe", "Die geheime Kalkulation der Einkaufspreise"], correct: 0, difficulty: "schwer", points: 15, explanation: "Sichtzone und Griffzone in Augen- und Handhöhe verkaufen am besten." },
    { id: "q0776", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was ist ein 'offenes Fragen' im Verkaufsgespräch?", answers: ["Eine Frage, die nicht mit Ja oder Nein geht", "Eine Frage, die den Kunden bewusst drängt", "Eine Frage ausschließlich nach dem Preis", "Eine Frage, die man selbst beantwortet"], correct: 0, difficulty: "schwer", points: 15, explanation: "W-Fragen wie 'Wofür möchten Sie es nutzen?' bringen den Kunden ins Erzählen." },
    { id: "q0777", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was bedeutet die Preisangabenverordnung für den Einzelhandel?", answers: ["Preise müssen inklusive Mehrwertsteuer erkennbar sein", "Preise dürfen bewusst unauffällig platziert werden", "Die Regel gilt ausschließlich für Onlineshops", "Preise dürfen ohne Steuer angegeben werden"], correct: 0, difficulty: "schwer", points: 15, explanation: "Verbraucher müssen den Endpreis auf einen Blick erkennen können." },
    { id: "q0778", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Wie reagiert man richtig auf eine Reklamation?", answers: ["Zuhören, Verständnis zeigen, Lösung anbieten", "Den Kunden freundlich, aber bestimmt abweisen", "Den Fehler bestreiten und auf Hersteller verweisen", "Den Kunden zunächst warten lassen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Eine gut gelöste Reklamation stärkt oft die Kundenbindung." },
    { id: "q0779", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was ist Warenschwund im Einzelhandel?", answers: ["Ungeplanter Verlust durch Diebstahl oder Verderb", "Der geplante Abverkauf über Rabattaktionen", "Der gesamte Umsatz eines Verkaufstages", "Der bewusst eingeplante Werbeaufwand"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Schwund wird über die Inventur ermittelt und mindert den Gewinn." },

    // ============ Pflegefachkraft ============
    { id: "q0780", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Welche Werte zählen zu den Vitalzeichen?", answers: ["Puls, Blutdruck, Atmung und Temperatur", "Ausschließlich der gemessene Blutdruck", "Körpergröße und aktuelles Körpergewicht", "Ausschließlich die Blutgruppe des Patienten"], correct: 0, difficulty: "schwer", points: 15, explanation: "Vitalzeichen geben Auskunft über die lebenswichtigen Körperfunktionen." },
    { id: "q0781", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Was ist die wichtigste Maßnahme zur Infektionsprävention?", answers: ["Die hygienische Händedesinfektion", "Das Tragen von Schmuck", "Das Lüften allein", "Das regelmäßige Auftragen von Parfüm"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Händedesinfektion nach den fünf Momenten der WHO ist die wirksamste Einzelmaßnahme." },
    { id: "q0782", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Was versteht man unter Dekubitusprophylaxe?", answers: ["Maßnahmen zur Vorbeugung von Druckgeschwüren", "Maßnahmen zur Vorbeugung von Stürzen", "Maßnahmen zur Vorbeugung von Erkältungen", "Maßnahmen zur Vorbeugung von Karies"], correct: 0, difficulty: "schwer", points: 15, explanation: "Regelmäßige Positionswechsel, Hautpflege und Druckentlastung sind zentral." },
    { id: "q0783", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Welche Schritte umfasst der Pflegeprozess?", answers: ["Sammeln, Planen, Durchführen, Auswerten", "Ausschließlich das Dokumentieren am Ende", "Ausschließlich die ärztliche Visite", "Ausschließlich das Verteilen der Mahlzeiten"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Pflegeprozess ist ein Regelkreis und wird laufend angepasst." },
    { id: "q0784", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Warum ist die Pflegedokumentation so wichtig?", answers: ["Sie sichert Qualität und rechtliche Absicherung", "Sie ist eine reine Formsache ohne Bedeutung", "Sie ersetzt die mündliche Übergabe komplett", "Sie dient allein der Beschäftigung des Personals"], correct: 0, difficulty: "schwer", points: 15, explanation: "Was nicht dokumentiert ist, gilt im Streitfall als nicht durchgeführt." },
    { id: "q0785", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Was gilt für die Schweigepflicht in der Pflege?", answers: ["Patientendaten dürfen nicht unbefugt weitergegeben werden", "Angehörige dürfen stets alle Details erfahren", "Sie betrifft ausschließlich ärztliches Personal", "Sie gilt nur bei minderjährigen Patienten"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Schweigepflicht ist strafbewehrt (§ 203 StGB) und gilt auch für Auszubildende." },
    { id: "q0786", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Wie lagert man eine bewusstlose Person mit normaler Atmung?", answers: ["In der stabilen Seitenlage", "Flach auf dem Rücken", "Sitzend an die Wand gelehnt", "Mit erhöhten Beinen auf dem Rücken"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die Seitenlage hält die Atemwege frei und verhindert das Einatmen von Erbrochenem." },
    { id: "q0787", category: "beruf_pflege", area: "beruf", subject: "pflege", question: "Was ist ein Ziel der Sturzprophylaxe?", answers: ["Risiken erkennen und Umgebung sicher gestalten", "Bewegung soweit wie möglich ganz vermeiden", "Betroffene dauerhaft im Bett liegen lassen", "Alle Hilfsmittel aus dem Zimmer entfernen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Bewegungsförderung, gutes Schuhwerk und freie Wege senken das Sturzrisiko." },

    // ============ Friseur/in ============
    { id: "q0788", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Aus welchen drei Schichten besteht das Haar von außen nach innen?", answers: ["Schuppenschicht, Faserschicht, Mark", "Mark, Haut, Wurzel", "Fettschicht, Hornschicht, Nervenschicht", "Wurzel, Talg, Nerv"], correct: 0, difficulty: "schwer", points: 15, explanation: "Cuticula (Schuppenschicht), Cortex (Faserschicht) und Medulla (Mark)." },
    { id: "q0789", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Welchen pH-Wert hat gesunde Kopfhaut ungefähr?", answers: ["Etwa 5,5 (leicht sauer)", "Etwa 7 (neutral)", "Etwa 9 (basisch)", "Etwa 3 (stark sauer)"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der leicht saure Schutzmantel hemmt das Wachstum von Keimen." },
    { id: "q0790", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Was bewirkt Wasserstoffperoxid beim Färben?", answers: ["Es öffnet die Schuppenschicht und entwickelt Farbe", "Es kühlt die Kopfhaut während der Einwirkzeit", "Es fixiert die fertige Frisur dauerhaft", "Es verschließt die Schuppenschicht dauerhaft"], correct: 0, difficulty: "schwer", points: 15, explanation: "H2O2 oxidiert die Farbstoffvorstufen und hellt gleichzeitig das Naturpigment auf." },
    { id: "q0791", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Welche zwei Schritte umfasst eine Dauerwelle?", answers: ["Reduktion (Umformen) und anschließende Fixierung", "Gründliches Waschen und anschließendes Föhnen", "Stufiges Schneiden und abschließendes Tönen", "Färben und anschließendes Aufhellen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Das Wellmittel öffnet die Schwefelbrücken, die Fixierung schließt sie in neuer Form." },
    { id: "q0792", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Warum wird vor einer Coloration eine Verträglichkeitsprobe empfohlen?", answers: ["Um allergische Reaktionen auszuschließen", "Um den genauen Preis vorab zu ermitteln", "Um die Haarlänge exakt zu bestimmen", "Um die passende Frisur auszuwählen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Besonders PPD in Oxidationsfarben kann Allergien auslösen." },
    { id: "q0793", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Was gehört zur Hygiene am Arbeitsplatz im Salon?", answers: ["Desinfektion von Scheren, Kämmen und Flächen", "Nur das Fegen der Haare", "Nur das Händewaschen am Feierabend", "Nur das Lüften am Ende des Tages"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Hygieneplan regelt Reinigung und Desinfektion aller Werkzeuge und Flächen." },
    { id: "q0794", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Was ist das Ziel einer Kundenberatung vor dem Schnitt?", answers: ["Wünsche, Haarstruktur und Gesichtsform abstimmen", "Möglichst viele teure Pflegeprodukte verkaufen", "Die Dauer des Termins deutlich verkürzen", "Den Termin möglichst lange auszudehnen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Eine gute Beratung verhindert Missverständnisse und Reklamationen." },
    { id: "q0795", category: "beruf_friseur", area: "beruf", subject: "friseur", question: "Was passiert beim Blondieren mit dem Haar?", answers: ["Die natürlichen Pigmente werden aufgehellt", "Zusätzliche Farbpigmente werden eingelagert", "Die Schuppenschicht wird dauerhaft verdichtet", "Die Haarstruktur wird dauerhaft verdichtet"], correct: 0, difficulty: "schwer", points: 15, explanation: "Blondieren belastet das Haar stark, deshalb sind Pflege und Abstände wichtig." }
];