const K10_RELIGION_ETHIK_QUESTIONS = [
  // ================================================================
  // 1. ETHIK, FREIHEIT & VERANTWORTUNG (40 Fragen)
  // ================================================================
  {
    id: "q10_re_001",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Ethik?",
    answers: ["Die feste Sammlung religiöser Gebote und überlieferter Rituale", "Die staatliche Festlegung von Gesetzen, Regeln und Strafmaßen", "Die systematische Reflexion über gutes und richtiges Handeln", "Die reine Lehre von gesellschaftlichen Bräuchen, Sitten und Moden"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ethik fragt nach Maßstäben für gutes Leben und Handeln."
  },
  {
    id: "q10_re_002",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Moral?",
    answers: ["Die persönliche Meinung eines einzelnen Menschen über richtig und falsch", "Die Gesamtheit der in einer Gesellschaft geltenden Normen und Werte", "Die wissenschaftliche Untersuchung von Naturgesetzen und mathematischen Formeln", "Die staatlich festgelegte Ordnung von Gesetzen, Verordnungen und Erlassen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Moral beschreibt faktische Verhaltensregeln."
  },
  {
    id: "q10_re_003",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Gewissen?",
    answers: ["Die äußere Kontrolle durch Polizei, Gerichte und Behörden", "Die religiöse Vorschrift, die jede einzelne Handlung genau regelt", "Die innere Instanz, die Handlungen als gut oder schlecht bewertet", "Die gesellschaftliche Mehrheitsmeinung über richtiges und falsches Verhalten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Gewissen spielt in ethischen und religiösen Kontexten eine zentrale Rolle."
  },
  {
    id: "q10_re_004",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Verantwortung?",
    answers: ["Die Freiheit, sich jeder Konsequenz seines Handelns zu entziehen", "Die religiöse Pflicht, täglich zu beten und zu fasten", "Die staatliche Pflicht, Steuern und Abgaben zu zahlen", "Die Pflicht, für die Folgen des eigenen Handelns einzustehen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Verantwortung bezieht sich auf sich selbst, andere und die Umwelt."
  },
  {
    id: "q10_re_005",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Freiheit?",
    answers: ["Die Pflicht, sich stets den Regeln der Gemeinschaft zu unterwerfen", "Die Möglichkeit, selbstbestimmt zu handeln und zu entscheiden", "Die staatlich garantierte Vollversorgung aller Bürger", "Die religiöse Vorschrift, jede Entscheidung zu unterlassen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Freiheit und Verantwortung gehören zusammen."
  },
  {
    id: "q10_re_006",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die Menschenwürde?",
    answers: ["Der gesetzlich verliehene Status besonders verdienter Bürger", "Der wirtschaftliche Wert eines Menschen für die Gesellschaft", "Der religiöse Rang eines Menschen innerhalb der Kirche", "Der unverlierbare Wert jedes Menschen als Person"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Menschenwürde ist Grundlage der Menschenrechte."
  },
  {
    id: "q10_re_007",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was sind Menschenrechte?",
    answers: ["Nationale Vorrechte, die nur eigenen Staatsbürgern zustehen", "Kirchliche Privilegien, die nur Gläubigen zustehen", "Unveräußerliche Rechte, die jedem Menschen zustehen", "Berufliche Ansprüche, die nur Erwachsenen zustehen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Menschenrechte gelten unabhängig von Herkunft, Religion oder Status."
  },
  {
    id: "q10_re_008",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der kategorische Imperativ (Kant)?",
    answers: ["Handle stets so, wie es dir persönlich den größten Vorteil und Nutzen verschafft", "Handle immer genau so, wie es die religiöse Tradition seit jeher vorschreibt und verlangt", "Handle nur nach derjenigen Maxime, durch die du wollen kannst, dass sie allgemeines Gesetz werde", "Handle so, wie es die Mehrheit der Gesellschaft in diesem Moment gerade für richtig und passend hält"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Kants Ethik betont die Verallgemeinerbarkeit von Handlungen."
  },
  {
    id: "q10_re_009",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Utilitarismus?",
    answers: ["Eine Ethik, die das größtmögliche Glück der größtmöglichen Zahl anstrebt", "Eine Ethik, die allein auf religiösen Geboten und strengen Verboten beruht", "Eine Ethik, die ausschließlich die persönliche Absicht des Handelnden bewertet", "Eine Ethik, die ausschließlich staatliche Gesetze als einzigen Maßstab nimmt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Utilitarismus bewertet Handlungen nach ihren Folgen."
  },
  {
    id: "q10_re_010",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Tugendethik?",
    answers: ["Eine Ethik, die auf der Ausbildung guter Charaktereigenschaften beruht", "Eine Ethik, die allein die Folgen einer einzelnen Handlung bewertet", "Eine Ethik, die sich nur auf staatliche Vorschriften und Gesetze stützt", "Eine Ethik, die ausschließlich religiöse Rituale und Bräuche vorschreibt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Aristoteles betonte die Tugenden für ein gelingendes Leben."
  },
  {
    id: "q10_re_011",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Pflichtethik?",
    answers: ["Eine Ethik, die Handlungen allein nach ihrem Nutzen für alle bewertet", "Eine Ethik, die Handlungen nach der überlieferten Tradition der Kirche bewertet", "Eine Ethik, die Handlungen nach ihrer Übereinstimmung mit Pflichten bewertet", "Eine Ethik, die Handlungen allein nach dem persönlichen Gefühl bewertet"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Kant ist ein zentraler Vertreter der Pflichtethik."
  },
  {
    id: "q10_re_012",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das goldene Regel?",
    answers: ["Behandle andere so, wie du von ihnen behandelt werden willst", "Behandle andere stets strenger, als du selbst behandelt werden willst", "Behandle nur die, die dir religiös oder sozial nahestehen", "Behandle andere nach den Vorschriften des jeweiligen Staates"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die goldene Regel findet sich in vielen Kulturen und Religionen."
  },
  {
    id: "q10_re_013",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Nächstenliebe?",
    answers: ["Die rechtliche Pflicht, Verwandten finanziell zu helfen", "Die ethische Haltung, dem Mitmenschen Gutes zu tun", "Die religiöse Vorschrift, nur der eigenen Familie zu dienen", "Die staatliche Aufgabe, Bedürftige finanziell zu versorgen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Nächstenliebe ist ein zentrales christliches und jüdisches Gebot."
  },
  {
    id: "q10_re_014",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Gerechtigkeit?",
    answers: ["Die Haltung, allen Menschen exakt dasselbe zu geben", "Die Ordnung, wonach der Stärkere über andere entscheidet", "Die Haltung und Ordnung, jedem das Seine zu geben", "Die Vorschrift, nach der Fehler stets bestraft werden"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Gerechtigkeit ist ein zentrales ethisches und soziales Prinzip."
  },
  {
    id: "q10_re_015",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Solidarität?",
    answers: ["Das füreinander Einstehen in einer Gemeinschaft", "Das Verfolgen der eigenen Interessen ohne Rücksicht", "Das Meiden jeglichen Kontakts zu anderen Menschen", "Das Konkurrieren um Ansehen innerhalb einer Gruppe"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Solidarität ist ein sozialethisches Prinzip."
  },
  {
    id: "q10_re_016",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Toleranz?",
    answers: ["Die Gleichgültigkeit gegenüber jeder Art von fremder Überzeugung", "Die Bereitschaft, andere Überzeugungen und Lebensweisen zu achten", "Die bedingungslose Zustimmung zu jeder beliebigen fremden Meinung", "Die Ablehnung aller Überzeugungen, die man selbst nicht teilt"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Toleranz ist Voraussetzung für friedliches Zusammenleben."
  },
  {
    id: "q10_re_017",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Gewissensfreiheit?",
    answers: ["Das Recht, sich frei über Politik und Medien zu äußern", "Das Recht, nach dem eigenen Gewissen zu urteilen und zu handeln", "Das Recht, frei über die eigene Religionszugehörigkeit zu bestimmen", "Das Recht, ungehindert Zeitungen und Bücher zu veröffentlichen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Gewissensfreiheit ist ein Grundrecht."
  },
  {
    id: "q10_re_018",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Religionsfreiheit?",
    answers: ["Die staatlich verordnete Pflichtzugehörigkeit zu einer bestimmten Kirche", "Die Pflicht, sich zu einer staatlich anerkannten Religion zu bekennen", "Die Aufgabe der Kirche, Andersgläubige zum eigenen Glauben zu bekehren", "Das Recht, eine Religion zu wählen, auszuüben oder keine zu haben"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Religionsfreiheit umfasst positive und negative Freiheit."
  },
  {
    id: "q10_re_019",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist ein Dilemma?",
    answers: ["Eine Entscheidungssituation mit zwei oder mehr schwer vereinbaren Optionen", "Eine Entscheidungssituation mit einer einzigen eindeutig richtigen Lösung dafür", "Eine Situation, in der überhaupt keine Entscheidung nötig ist", "Eine gesetzlich klar geregelte Wahl zwischen zwei festen Optionen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ethische Dilemmata erfordern Abwägung."
  },
  {
    id: "q10_re_020",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Ethik und Moral?",
    answers: ["Ethik: gelebte Normen, Moral: Reflexion", "Ethik: Reflexion, Moral: gelebte Normen", "Ethik: Gesetze, Moral: private Gefühle", "Ethik: Religion, Moral: alte Bräuche"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ethik reflektiert die Moral."
  },
  {
    id: "q10_re_021",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Pflicht und Neigung?",
    answers: ["Pflicht: moralische Verpflichtung, Neigung: persönliches Wollen", "Pflicht: persönliches Wollen, Neigung: moralische Verpflichtung", "Pflicht: freiwilliges Hobby, Neigung: Befehl eines Vorgesetzten", "Pflicht: Gefühl der Lust, Neigung: Gesetz des Staates"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei Kant zählt die Pflichtmotivierung."
  },
  {
    id: "q10_re_022",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Absicht und Folge?",
    answers: ["Absicht: Ergebnis der Handlung, Folge: Motive des Handelnden", "Absicht: Zufall beim Handeln, Folge: Reihenfolge der Schritte", "Absicht: Motive des Handelnden, Folge: Ergebnis der Handlung", "Absicht: Strafe für eine Tat, Folge: Grund für eine Tat"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Verschiedene Ethiken gewichten Absicht oder Folge unterschiedlich."
  },
  {
    id: "q10_re_023",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Individual- und Sozialethik?",
    answers: ["Individualethik: persönliches Handeln, Sozialethik: gesellschaftliche Strukturen", "Individualethik: gesellschaftliche Strukturen, Sozialethik: persönliches Handeln", "Individualethik: Ethik für Einzelkinder, Sozialethik: Ethik für Sozialarbeiter", "Individualethik: Moral ohne Regeln, Sozialethik: Regeln der Sozialversicherung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Ebenen gehören zusammen."
  },
  {
    id: "q10_re_024",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen relativer und absoluter Ethik?",
    answers: ["Relativ: allgemeingültig, absolut: situationsabhängig", "Relativ: unwichtig, absolut: wichtig für alle Menschen", "Relativ: situationsabhängig, absolut: allgemeingültig", "Relativ: religiös, absolut: staatlich festgelegt"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Debatte betrifft den Geltungsanspruch moralischer Normen."
  },
  {
    id: "q10_re_025",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Schuld und Verantwortung?",
    answers: ["Schuld: Pflicht zum Einstehen, Verantwortung: moralisches Versagen", "Schuld: moralisches Versagen, Verantwortung: Pflicht zum Einstehen", "Schuld: Strafe vom Staat, Verantwortung: Lob für gute Taten", "Schuld: bloßes Gefühl, Verantwortung: nur ein Amt im Beruf"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Verantwortung kann auch positiv und zukunftsbezogen sein."
  },
  {
    id: "q10_re_026",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Autonomie und Heteronomie?",
    answers: ["Autonomie: Fremdbestimmung, Heteronomie: Selbstgesetzgebung", "Autonomie: Gesetzlosigkeit, Heteronomie: Gleichberechtigung", "Autonomie: Alleinsein, Heteronomie: Leben in der Gruppe", "Autonomie: Selbstgesetzgebung, Heteronomie: Fremdbestimmung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Autonomie ist ein zentrales Konzept der Aufklärungsethik."
  },
  {
    id: "q10_re_027",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Wert und Norm?",
    answers: ["Wert: konkrete Handlungsregel, Norm: Leitvorstellung", "Wert: Preis einer Sache, Norm: Durchschnitt der Leute", "Wert: Gefühl, Norm: Gesetz mit festgelegter Strafe", "Wert: Leitvorstellung, Norm: konkrete Handlungsregel"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Normen leiten sich oft aus Werten ab."
  },
  {
    id: "q10_re_028",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Tugend und Laster?",
    answers: ["Tugend: schlechte Charaktereigenschaft, Laster: gute", "Tugend: angeborenes Talent, Laster: erlernte Fähigkeit", "Tugend: gute Charaktereigenschaft, Laster: schlechte", "Tugend: Regel der Kirche, Laster: Verbot des Staates"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Tugendethik zielt auf Charakterbildung."
  },
  {
    id: "q10_re_029",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Intention und Konsequenz?",
    answers: ["Intention: Folge, Konsequenz: Absicht", "Intention: Zufall, Konsequenz: Strafe", "Intention: Gefühl, Konsequenz: Regel", "Intention: Absicht, Konsequenz: Folge"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Verschiedene Ethiken betonen unterschiedliche Aspekte."
  },
  {
    id: "q10_re_030",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen deontologischer und teleologischer Ethik?",
    answers: ["Deontologisch: ziel- und folgenbezogen, teleologisch: pflichtbezogen", "Deontologisch: gottesbezogen, teleologisch: naturwissenschaftlich", "Deontologisch: pflichtbezogen, teleologisch: ziel- und folgenbezogen", "Deontologisch: gefühlsbezogen, teleologisch: gesetzesbezogen"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Kant ist deontologisch, Utilitarismus teleologisch."
  },
  {
    id: "q10_re_031",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen formaler und materialer Ethik?",
    answers: ["Formal: konkrete Inhalte, material: allgemeine Prinzipien", "Formal: höfliche Umgangsformen, material: Besitz und Geld", "Formal: Regeln für Formulare, material: Regeln für Werkstoffe", "Formal: allgemeine Prinzipien, material: konkrete Inhalte"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Beide Ebenen ergänzen sich in der ethischen Reflexion."
  },
  {
    id: "q10_re_032",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Prinzipienethik und Situationsethik?",
    answers: ["Prinzipienethik: Einzelfallentscheidung, Situationsethik: allgemeine Regeln", "Prinzipienethik: Entscheidung nach Gefühl, Situationsethik: feste Gebote", "Prinzipienethik: allgemeine Regeln, Situationsethik: Einzelfallentscheidung", "Prinzipienethik: Ethik der Fürsten, Situationsethik: Ethik im Notfall"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Ansätze haben Stärken und Grenzen."
  },
  {
    id: "q10_re_033",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen ethischer und rechtlicher Verantwortung?",
    answers: ["Ethisch: gesetzlich, rechtlich: moralisch", "Ethisch: moralisch, rechtlich: gesetzlich", "Ethisch: religiös, rechtlich: politisch", "Ethisch: freiwillig, rechtlich: unverbindlich"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Recht und Moral überschneiden sich, sind aber nicht identisch."
  },
  {
    id: "q10_re_034",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen positiver und negativer Freiheit?",
    answers: ["Positiv: Freiheit von Zwang, negativ: Freiheit zu etwas", "Positiv: gute Freiheit, negativ: schlechte Freiheit", "Positiv: Freiheit für Reiche, negativ: Freiheit für Arme", "Positiv: Freiheit zu etwas, negativ: Freiheit von Zwang"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Freiheitsbegriffe sind in der Diskussion."
  },
  {
    id: "q10_re_035",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Glück und Sinn?",
    answers: ["Glück: Bedeutung und Orientierung, Sinn: subjektives Wohlbefinden", "Glück: reiner Zufall, Sinn: Sinneswahrnehmung wie Sehen und Hören", "Glück: subjektives Wohlbefinden, Sinn: Bedeutung und Orientierung", "Glück: materieller Besitz, Sinn: Erfolg im Beruf und Ansehen"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Fragen prägen ethische und religiöse Reflexion."
  },
  {
    id: "q10_re_036",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Egoismus und Altruismus?",
    answers: ["Egoismus: Handeln zum Wohl anderer, Altruismus: Eigeninteresse", "Egoismus: Eigeninteresse, Altruismus: Handeln zum Wohl anderer", "Egoismus: Angst vor anderen, Altruismus: Liebe zu Tieren", "Egoismus: Einsamkeit, Altruismus: Leben in einer Gemeinschaft"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Motivationen spielen in der Ethik eine Rolle."
  },
  {
    id: "q10_re_037",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Gerechtigkeit und Barmherzigkeit?",
    answers: ["Gerechtigkeit: das Übermaß der Güte, Barmherzigkeit: das Geschuldete", "Gerechtigkeit: das Gesetzbuch, Barmherzigkeit: eine Spende an die Kirche", "Gerechtigkeit: das Geschuldete, Barmherzigkeit: das Übermaß der Güte", "Gerechtigkeit: Rache, Barmherzigkeit: Schwäche gegenüber Tätern"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Prinzipien ergänzen sich in vielen Traditionen."
  },
  {
    id: "q10_re_038",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Vergebung und Versöhnung?",
    answers: ["Vergebung: Wiederherstellung der Beziehung, Versöhnung: Loslassen der Schuld", "Vergebung: Vergessen der Tat, Versöhnung: Bestrafung des Täters", "Vergebung: Loslassen der Schuld, Versöhnung: Wiederherstellung der Beziehung", "Vergebung: Entschuldigung des Täters, Versöhnung: Urteil eines Gerichts"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Versöhnung geht oft über Vergebung hinaus."
  },
  {
    id: "q10_re_039",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Wahrheit und Wahrhaftigkeit?",
    answers: ["Wahrheit: Übereinstimmung mit der Wirklichkeit, Wahrhaftigkeit: aufrichtige Haltung", "Wahrheit: aufrichtige Haltung, Wahrhaftigkeit: Übereinstimmung mit der Wirklichkeit", "Wahrheit: Meinung der Mehrheit, Wahrhaftigkeit: eine besonders geschickte Ausrede", "Wahrheit: persönliches Gefühl, Wahrhaftigkeit: strenge Befolgung aller Gesetze"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wahrhaftigkeit betrifft die redliche Absicht."
  },
  {
    id: "q10_re_040",
    category: "k10_religion",
    topic: "ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die zentrale Aufgabe der Ethik?",
    answers: ["Orientierung für gutes und verantwortliches Handeln zu geben", "Ausschließlich religiöse Vorschriften verbindlich festzulegen", "Allein staatliche Gesetze zu begründen und durchzusetzen", "Nur wissenschaftliche Fakten über die Natur zu sammeln"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ethik hilft bei der Urteilsbildung."
  },

  // ================================================================
  // 2. RELIGION, GLAUBE & WELTERLIGIONEN (40 Fragen)
  // ================================================================
  {
    id: "q10_re_041",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Religion?",
    answers: ["Ein System von Überzeugungen, Praktiken und Gemeinschaften mit Bezug auf Transzendenz", "Ein System von staatlichen Gesetzen, das ausschließlich vom Staat allein erlassen wird", "Eine Sammlung wissenschaftlicher Theorien über die Entstehung der Natur", "Eine private Meinung ohne jede gemeinschaftliche oder soziale Bedeutung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Religionen prägen Weltbilder und Lebensformen."
  },
  {
    id: "q10_re_042",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Glaube?",
    answers: ["Gesichertes Wissen, das durch wiederholte Experimente eindeutig bewiesen wurde", "Eine reine Vermutung ohne jede persönliche oder gemeinschaftliche Bedeutung", "Vertrauen und Überzeugung in Bezug auf Gott oder letztgültige Wirklichkeit", "Eine staatlich vorgeschriebene Überzeugung, der alle Bürger folgen müssen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Glaube umfasst Vertrauen und Erkenntnis."
  },
  {
    id: "q10_re_043",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Monotheismus?",
    answers: ["Der Glaube an mehrere Götter", "Der Glaube an einen einzigen Gott", "Die Ablehnung jeder Gottesvorstellung", "Die Verehrung von Naturkräften"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Judentum, Christentum und Islam sind monotheistisch."
  },
  {
    id: "q10_re_044",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Polytheismus?",
    answers: ["Der Glaube an einen Gott", "Der Glaube an Naturkräfte", "Der Glaube an mehrere Götter", "Der Glaube an keine Gottheit"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Viele antike Religionen waren polytheistisch."
  },
  {
    id: "q10_re_045",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Atheismus?",
    answers: ["Die Überzeugung, dass es keinen Gott gibt", "Die Überzeugung, dass mehrere Götter existieren", "Die Unsicherheit, ob ein Gott existiert oder nicht", "Die Überzeugung, dass ein einziger Gott existiert"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Atheismus ist eine weltanschauliche Position."
  },
  {
    id: "q10_re_046",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Agnostizismus?",
    answers: ["Die Haltung, dass Gottes Existenz zweifelsfrei bewiesen worden ist", "Die Haltung, dass es mit völliger Sicherheit keinen Gott gibt", "Die Haltung, dass es mehrere gleichrangige Götter nebeneinander gibt", "Die Haltung, dass man die Existenz Gottes nicht wissen kann"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Agnostizismus betont die Grenzen des Wissens."
  },
  {
    id: "q10_re_047",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das Judentum?",
    answers: ["Die monotheistische Religion des jüdischen Volkes mit der Tora als Grundlage", "Die monotheistische Religion, die allein auf dem Koran als Grundlage beruht und aufbaut", "Die polytheistische Religion einer bestimmten indischen Volksgruppe", "Eine Philosophie ohne jeden Bezug zu Gott oder heiligen Schriften"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Judentum ist die älteste der abrahamitischen Religionen."
  },
  {
    id: "q10_re_048",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das Christentum?",
    answers: ["Die Religion, die Mohammed als letzten Propheten Gottes verehrt", "Die Religion, die Jesus Christus als den Sohn Gottes und Erlöser bekennt", "Die Religion, die ausschließlich das Alte Testament als Schrift nutzt", "Die Philosophie, die jede Vorstellung von Gott strikt und grundsätzlich ablehnt"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Christentum ist weltweit die größte Religion."
  },
  {
    id: "q10_re_049",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Islam?",
    answers: ["Die monotheistische Religion, die Jesus als den Sohn Gottes verehrt", "Die monotheistische Religion, die Mohammed als Propheten anerkennt", "Die polytheistische Religion des alten Griechenlands mit vielen Göttern", "Die Philosophie, die auf Buddha und dessen Lehren zurückgeht"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Islam basiert auf dem Koran."
  },
  {
    id: "q10_re_050",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Buddhismus?",
    answers: ["Eine Religion und Philosophie, die auf den Lehren Mohammeds beruht", "Eine Religion und Philosophie, die auf den Lehren Buddhas beruht", "Eine monotheistische Religion mit einem einzigen Schöpfergott", "Eine rein staatliche Ideologie ohne religiösen Ursprung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Buddhismus betont den Weg zur Erleuchtung."
  },
  {
    id: "q10_re_051",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Hinduismus?",
    answers: ["Eine ganz einheitliche Religion mit nur einem einzigen verbindlichen höchsten Gott", "Eine vielgestaltige Religion Indiens mit vielen Traditionen und Gottheiten", "Eine monotheistische Religion des Nahen Ostens mit nur einer Schrift", "Eine rein philosophische Lehre ganz ohne jeden Bezug zu Gott"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Hinduismus kennt keine einheitliche Gründerfigur."
  },
  {
    id: "q10_re_052",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die Bibel?",
    answers: ["Die heilige Schrift, die ausschließlich im Islam verwendet wird", "Ein rein historisches Buch ohne religiöse Bedeutung", "Die Heilige Schrift des Judentums und des Christentums", "Die Sammlung der Gesetze des modernen Staates Israel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Bibel besteht aus Altem und Neuem Testament."
  },
  {
    id: "q10_re_053",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Koran?",
    answers: ["Die heilige Schrift des Buddhismus", "Ein modernes Geschichtsbuch über Arabien", "Die zentrale Schrift des Hinduismus", "Die heilige Schrift des Islam"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Muslime betrachten den Koran als Offenbarung Gottes."
  },
  {
    id: "q10_re_054",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die Tora?",
    answers: ["Die vier Evangelien, zentrale Schrift des Christentums", "Die fünf Bücher Mose, zentrale Schrift des Judentums", "Die 114 Suren, zentrale Schrift des Islam", "Die Psalmen, zentrale Gebetstexte des Christentums"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Tora ist Teil der hebräischen Bibel."
  },
  {
    id: "q10_re_055",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist ein Prophet?",
    answers: ["Ein Mensch, der ein kirchliches Amt geerbt hat", "Ein Mensch, der über politische Ereignisse berichtet", "Ein Mensch, der im Auftrag Gottes spricht und mahnt", "Ein Mensch, der wissenschaftliche Theorien entwickelt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Propheten spielen in den abrahamitischen Religionen eine Rolle."
  },
  {
    id: "q10_re_056",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Offenbarung?",
    answers: ["Die philosophische Herleitung von Naturgesetzen", "Die staatliche Bekanntgabe neuer Gesetze", "Die Selbstmitteilung Gottes an den Menschen", "Die menschliche Erforschung des Weltalls"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Offenbarung ist ein zentrales theologisches Konzept."
  },
  {
    id: "q10_re_057",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Schöpfung?",
    answers: ["Die Vorstellung, dass Gott die Welt hervorgebracht hat", "Die Vorstellung, dass die Welt schon immer existierte", "Die wissenschaftliche Theorie über den Ursprung der Sprache", "Die Annahme, dass der Mensch die Welt selbst erschaffen hat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Schöpfungsglaube und Naturwissenschaft können unterschiedlich bezogen werden."
  },
  {
    id: "q10_re_058",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Auferstehung?",
    answers: ["Der Glaube an das Weiterleben nach dem Tod durch Gottes Kraft", "Der Glaube an die endgültige Vernichtung des Menschen nach dem Tod", "Der Glaube an eine erneute Geburt als Tier oder als Pflanze", "Die medizinische Wiederbelebung eines Menschen durch ärztliche Kunst"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Auferstehung Jesu ist zentral für das Christentum."
  },
  {
    id: "q10_re_059",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Erlösung?",
    answers: ["Die Befreiung von Schuld, Leid oder Unheil durch Gott", "Die Befreiung von Schulden durch staatliche Programme", "Die eigenständige Überwindung von Problemen ohne Hilfe", "Die schulische Vermittlung von Wissen und Fähigkeiten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Erlösung ist ein zentrales Thema vieler Religionen."
  },
  {
    id: "q10_re_060",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Gebet?",
    answers: ["Die musikalische Untermalung eines Gottesdienstes durch Chor und Orgel", "Die feste Abfolge kirchlicher Handlungen bei großen kirchlichen Festen", "Die stille Versenkung eines Menschen ganz ohne Bezug zu Gott", "Die Zuwendung des Menschen zu Gott in Worten oder Gedanken"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Gebet ist eine zentrale religiöse Praxis."
  },
  {
    id: "q10_re_061",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Gottesdienst?",
    answers: ["Die gemeinschaftliche Feier des Glaubens", "Die stille Versenkung ohne andere Menschen", "Das einsame Gebet zu Hause am Abend", "Der schulische Unterricht über Religion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gottesdienste prägen das religiöse Leben."
  },
  {
    id: "q10_re_062",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist interreligiöser Dialog?",
    answers: ["Der Streit zwischen Anhängern verschiedener Religionen", "Der Versuch, andere von der eigenen Religion zu überzeugen", "Die scharfe Kritik an fremden religiösen Praktiken", "Das Gespräch zwischen Angehörigen verschiedener Religionen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Dialog fördert Verständnis und Frieden."
  },
  {
    id: "q10_re_063",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Mission?",
    answers: ["Der gleichberechtigte Austausch zwischen Religionen", "Die scharfe Kritik an religiösen Überzeugungen", "Die Weitergabe des eigenen Glaubens an andere", "Der schulische Unterricht über Weltreligionen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Mission kann unterschiedlich verstanden und praktiziert werden."
  },
  {
    id: "q10_re_064",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Ökumene?",
    answers: ["Die Bemühung um eine Einheit zwischen sämtlichen Weltreligionen der Erde", "Der Versuch, Angehörige anderer Religionen zum Christentum zu bekehren", "Die Bemühung um Einheit und Zusammenarbeit der christlichen Kirchen", "Die wissenschaftliche Erforschung religiöser Texte an einer Universität"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ökumene zielt auf Versöhnung unter Christen."
  },
  {
    id: "q10_re_065",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Religion und Weltanschauung?",
    answers: ["Religion: umfassendes Wirklichkeitsverständnis, Weltanschauung: oft mit Transzendenzbezug", "Religion: oft mit Transzendenzbezug, Weltanschauung: umfassendes Wirklichkeitsverständnis", "Religion: staatliche Verordnung, Weltanschauung: naturwissenschaftliche Messmethode", "Religion: private Freizeitbeschäftigung, Weltanschauung: politisches Parteiprogramm"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide prägen Werte und Lebensführung."
  },
  {
    id: "q10_re_066",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Glaube und Wissen?",
    answers: ["Glaube: begründete Erkenntnis, Wissen: Vertrauen", "Glaube: bloße Vermutung, Wissen: Meinung der Mehrheit", "Glaube: Vertrauen, Wissen: begründete Erkenntnis", "Glaube: Aberglaube, Wissen: auswendig gelernte Fakten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide können sich ergänzen oder in Spannung stehen."
  },
  {
    id: "q10_re_067",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Mythos und Geschichte?",
    answers: ["Mythos: rekonstruiertes Geschehen, Geschichte: sinnstiftende Erzählung", "Mythos: absichtliche Lüge, Geschichte: frei erfundene Erzählung", "Mythos: wissenschaftlicher Bericht, Geschichte: religiöse Legende", "Mythos: sinnstiftende Erzählung, Geschichte: rekonstruiertes Geschehen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Religiöse Texte verbinden oft beide Ebenen."
  },
  {
    id: "q10_re_068",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Ritus und Ethik?",
    answers: ["Ritus: moralische Orientierung, Ethik: kultische Handlung", "Ritus: kultische Handlung, Ethik: moralische Orientierung", "Ritus: moralische Regel, Ethik: Gottesdienstordnung", "Ritus: staatliches Gesetz, Ethik: persönlicher Geschmack"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide gehören zum religiösen Leben."
  },
  {
    id: "q10_re_069",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Kirche und Religion?",
    answers: ["Kirche: umfassenderes Phänomen, Religion: organisierte Gemeinschaft", "Kirche: nur das Gebäude, Religion: nur die Gebete im Alltag", "Kirche: organisierte Gemeinschaft, Religion: umfassenderes Phänomen", "Kirche: Glaube ohne Gott, Religion: Gemeinschaft ohne Glaube"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Nicht jede Religion ist kirchlich organisiert."
  },
  {
    id: "q10_re_070",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Theismus und Deismus?",
    answers: ["Theismus: entfernter Schöpfergott, Deismus: persönlicher Gott", "Theismus: viele Götter, Deismus: gar kein Gott", "Theismus: persönlicher Gott, Deismus: entfernter Schöpfergott", "Theismus: Gott als Naturkraft, Deismus: Gott als Mensch"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Deismus war in der Aufklärung verbreitet."
  },
  {
    id: "q10_re_071",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Immanenz und Transzendenz?",
    answers: ["Immanenz: in der Welt, Transzendenz: über die Welt hinaus", "Immanenz: über die Welt hinaus, Transzendenz: in der Welt", "Immanenz: im Himmel, Transzendenz: unter der Erde", "Immanenz: Unsterblichkeit, Transzendenz: Wiedergeburt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Gottesvorstellungen verbinden oft beide Aspekte."
  },
  {
    id: "q10_re_072",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Sakral und Profan?",
    answers: ["Sakral: alltäglich, Profan: heilig", "Sakral: heilig, Profan: alltäglich", "Sakral: verboten, Profan: erlaubt", "Sakral: uralt, Profan: modern"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Unterscheidung prägt religiöse Lebenswelten."
  },
  {
    id: "q10_re_073",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Dogma und Glaubensüberzeugung?",
    answers: ["Dogma: persönliche Haltung, Glaubensüberzeugung: verbindliche Lehrentscheidung", "Dogma: verbindliche Lehrentscheidung, Glaubensüberzeugung: persönliche Haltung", "Dogma: persönliche Vermutung, Glaubensüberzeugung: staatliches Gesetz", "Dogma: Gebet vor dem Essen, Glaubensüberzeugung: Wahlprogramm einer Partei"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Dogmen strukturieren kirchliche Lehre."
  },
  {
    id: "q10_re_074",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Spiritualität und Religion?",
    answers: ["Spiritualität: oft institutionell geprägt, Religion: innere Erfahrung", "Spiritualität: Glaube an Gespenster, Religion: Wissenschaft von Gott", "Spiritualität: innere Erfahrung, Religion: oft institutionell geprägt", "Spiritualität: staatliche Feiertage, Religion: private Meditation"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide können sich überschneiden."
  },
  {
    id: "q10_re_075",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Fundamentalismus und Liberalismus in der Religion?",
    answers: ["Fundamentalismus: strenge Bindung an Grundlagen, Liberalismus: offenere Auslegung", "Fundamentalismus: offenere Auslegung, Liberalismus: strenge Bindung an Grundlagen", "Fundamentalismus: Ablehnung jeder Religion, Liberalismus: völlige Gleichgültigkeit", "Fundamentalismus: Forschung an Urtexten, Liberalismus: Abschaffung aller Regeln"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Strömungen gibt es in verschiedenen Religionen."
  },
  {
    id: "q10_re_076",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Mission und Dialog?",
    answers: ["Mission: gegenseitiges Lernen, Dialog: Weitergabe des eigenen Glaubens", "Mission: Hilfe nur für Kirchenmitglieder, Dialog: Streit um die Wahrheit", "Mission: Reise ins Ausland, Dialog: Gespräch unter Priestern", "Mission: Weitergabe des eigenen Glaubens, Dialog: gegenseitiges Lernen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide können unterschiedlich bewertet werden."
  },
  {
    id: "q10_re_077",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen monotheistisch und polytheistisch?",
    answers: ["Monotheistisch: ein Gott, polytheistisch: mehrere Götter", "Monotheistisch: mehrere Götter, polytheistisch: ein Gott", "Monotheistisch: kein Gott, polytheistisch: ein Gott", "Monotheistisch: ein Gott, polytheistisch: kein Gott"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Unterscheidung ist grundlegend."
  },
  {
    id: "q10_re_078",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen abrahamitischen und östlichen Religionen?",
    answers: ["Abrahamitisch und östlich bezeichnen dabei angeblich stets exakt dieselbe Religionsgruppe", "Östlich meint Judentum, Christentum und Islam; abrahamitisch meint Hinduismus", "Abrahamitisch bezieht sich nur auf Religionen ganz ohne heilige Schriften", "Abrahamitisch: Judentum, Christentum, Islam; östlich: z. B. Hinduismus, Buddhismus"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Einteilung ist eine grobe Orientierung."
  },
  {
    id: "q10_re_079",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen personalem und impersonalem Gottesbild?",
    answers: ["Personal: Gott als Kraft oder Prinzip, impersonal: Gott als Gegenüber", "Personal: Gott als Gegenüber, impersonal: Gott als Kraft oder Prinzip", "Personal: Gott als Mensch, impersonal: es gibt keinen Gott", "Personal: Gott der Priester, impersonal: Gott der Laien"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Verschiedene Traditionen betonen unterschiedliche Aspekte."
  },
  {
    id: "q10_re_080",
    category: "k10_religion",
    topic: "religion",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die zentrale Frage der Religionsphilosophie?",
    answers: ["Wie sich Glaube, Vernunft und Wirklichkeit zueinander verhalten", "Wie sich Kirche und Staat in rechtlicher Hinsicht zueinander verhalten", "Wie viele Mitglieder eine bestimmte Religionsgemeinschaft insgesamt hat", "Welche Rituale in welcher genauen Reihenfolge stattzufinden haben"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Religionsphilosophie reflektiert religiöse Ansprüche."
  },

  // ================================================================
  // 3. BIBLISCHE THEMEN, KIRCHE & GESELLSCHAFT (35 Fragen)
  // ================================================================
  {
    id: "q10_re_081",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das Alte Testament?",
    answers: ["Der zweite Teil der christlichen Bibel mit sämtlichen erhaltenen Briefen des Apostels Paulus", "Die vollständige Sammlung aller 114 Suren des heiligen Korans im Islam", "Eine moderne wissenschaftliche Nacherzählung alter biblischer Geschichten", "Der erste Teil der christlichen Bibel, weitgehend identisch mit der hebräischen Bibel"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Es enthält Tora, Propheten und Schriften."
  },
  {
    id: "q10_re_082",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das Neue Testament?",
    answers: ["Der zweite Teil der christlichen Bibel mit den Schriften über Jesus und die frühe Kirche", "Der erste Teil der christlichen Bibel mit den vielen Geschichten des Volkes Israel", "Die zentrale Schrift des Islam mit den Offenbarungen an den Propheten Mohammed", "Eine Sammlung jüdischer Gebete und Lieder aus vorchristlicher Zeit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es umfasst Evangelien, Apostelgeschichte, Briefe und Offenbarung."
  },
  {
    id: "q10_re_083",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was sind die Evangelien?",
    answers: ["Die Briefe des Apostels Paulus an die frühen Gemeinden", "Die Prophetenbücher des Alten Testaments über die Zukunft", "Die vier Berichte über das Leben und die Botschaft Jesu", "Die Psalmen als Gebets- und Lobgesänge Israels"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Matthäus, Markus, Lukas und Johannes."
  },
  {
    id: "q10_re_084",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die Bergpredigt?",
    answers: ["Ein zentrales Gleichnis Jesu im Lukasevangelium der Bibel", "Ein Brief des Apostels Paulus an die Gemeinde in Rom", "Eine zentrale Lehrrede Jesu im Matthäusevangelium", "Ein einzelner Psalm aus dem Alten Testament der Bibel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie enthält die Seligpreisungen und ethische Weisungen."
  },
  {
    id: "q10_re_085",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist ein Gleichnis?",
    answers: ["Eine wortwörtliche Beschreibung eines genau datierten historischen Ereignisses", "Eine feste juristische Vorschrift ganz ohne jede bildhafte Sprache", "Eine wissenschaftliche Erklärung eines bestimmten Naturphänomens", "Eine bildhafte Erzählung, die eine religiöse oder ethische Wahrheit vermittelt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Jesus lehrte oft in Gleichnissen."
  },
  {
    id: "q10_re_086",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das Doppelgebot der Liebe?",
    answers: ["Gott und den Nächsten lieben", "Nur den eigenen Staat lieben", "Nur die eigene Familie lieben", "Nur sich selbst über alles lieben"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es fasst die ethische Kernbotschaft zusammen."
  },
  {
    id: "q10_re_087",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die Kirche?",
    answers: ["Die Verwaltung eines Bundeslandes", "Die Versammlung aller Staatsbürger", "Die Gemeinschaft der Glaubenden", "Die Organisation der Vereinten Nationen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Kirche bezeichnet Gemeinschaft und Institution."
  },
  {
    id: "q10_re_088",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Reformation?",
    answers: ["Die Erneuerungsbewegung des 16. Jahrhunderts, die zur Entstehung der evangelischen Kirchen führte", "Die Erneuerungsbewegung des 20. Jahrhunderts, die zur vollständigen rechtlichen Trennung von Kirche und Staat führte", "Die politische Revolution des 18. Jahrhunderts gegen die Monarchie in Frankreich", "Die kirchliche Bildungsreform des Mittelalters zur Gründung erster Universitäten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Luther, Calvin und andere prägten die Reformation."
  },
  {
    id: "q10_re_089",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist das Konzil?",
    answers: ["Eine Versammlung von Priestern zur feierlichen Feier eines Gottesdienstes", "Eine Zusammenkunft von Politikern zur Klärung offener Steuerfragen", "Eine Versammlung von Bischöfen zur Klärung von Glaubens- und Kirchenfragen", "Ein regelmäßiges Treffen von Studierenden der Theologie an der Universität"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Zweite Vatikanische Konzil war für die katholische Kirche bedeutsam."
  },
  {
    id: "q10_re_090",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Diakonie?",
    answers: ["Die theologische Ausbildung angehender Pfarrer und Diakone", "Die musikalische Gestaltung von Gottesdiensten durch Chöre", "Der soziale Dienst der Kirche an Menschen in Not", "Die Verwaltung kirchlicher Finanzen und der Gebäude vor Ort"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Diakonie ist gelebte Nächstenliebe."
  },
  {
    id: "q10_re_091",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Caritas?",
    answers: ["Die soziale Arbeit der evangelischen Kirche", "Die staatliche Sozialversicherung in Deutschland", "Die soziale Arbeit der katholischen Kirche", "Die private Wohltätigkeit einzelner Unternehmer"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Caritas bedeutet Nächstenliebe."
  },
  {
    id: "q10_re_092",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Prophetenkritik?",
    answers: ["Die genaue Vorhersage zukünftiger politischer Ereignisse durch die Propheten selbst", "Die kritische Mahnung der Propheten gegen Unrecht und falschen Gottesdienst", "Die feierliche Lobpreisung Gottes durch die Propheten in Liedern", "Die schriftliche Festlegung religiöser Gesetze durch die Könige Israels"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Propheten traten für Gerechtigkeit ein."
  },
  {
    id: "q10_re_093",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die Theodizee-Frage?",
    answers: ["Die Frage, ob es überhaupt einen einzigen Gott gibt oder eben gar nicht", "Die Frage, wie Leid und Böses mit einem guten und allmächtigen Gott vereinbar sind", "Die Frage, welche persönliche Schuld der Mensch für seine Taten trägt", "Die Frage, welchen tieferen Sinn das gesamte menschliche Leben insgesamt haben könnte"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Theodizee ist eine zentrale theologische Herausforderung."
  },
  {
    id: "q10_re_094",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Säkularisierung?",
    answers: ["Der Prozess der Zunahme religiöser Bindung in der modernen Gesellschaft", "Die enge Verbindung von Staatsführung und kirchlicher Lehre im Mittelalter", "Der Prozess der Abnahme religiöser Bindung und der Trennung von Religion und Staat", "Die verstärkte Rückkehr großer Bevölkerungsteile zu traditionellen religiösen Werten"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Säkularisierung prägt moderne Gesellschaften."
  },
  {
    id: "q10_re_095",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Pluralismus?",
    answers: ["Die verbindliche Einheitlichkeit aller Überzeugungen innerhalb eines gesamten Staates", "Die vollständige Trennung aller Bevölkerungsgruppen voneinander", "Die Vorherrschaft einer einzigen Religion innerhalb der gesamten Gesellschaft", "Die Vielfalt von Überzeugungen, Religionen und Lebensformen in einer Gesellschaft"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Religiöser Pluralismus erfordert Dialog und Toleranz."
  },
  {
    id: "q10_re_096",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Kirche und Staat?",
    answers: ["Kirche: politische Ordnung, Staat: religiöse Gemeinschaft", "Kirche: religiöse Gemeinschaft, Staat: politische Ordnung", "Kirche: Teil der Regierung, Staat: Teil der Kirche", "Kirche: Wirtschaftsunternehmen, Staat: Glaubensgemeinschaft"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "In Deutschland gilt die Trennung von Kirche und Staat."
  },
  {
    id: "q10_re_097",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen katholisch und evangelisch?",
    answers: ["Katholisch und evangelisch sind zwei komplett getrennte eigenständige Weltreligionen", "Unterschiedliche Traditionen, Ämter und Schwerpunkte innerhalb des Christentums", "Nur äußerliche Unterschiede in der Kirchenarchitektur und liturgischen Kleidung", "Rein regionale Unterschiede ganz ohne jede tiefere theologische Bedeutung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide gehören zur christlichen Tradition."
  },
  {
    id: "q10_re_098",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Schrift und Tradition?",
    answers: ["Schrift: überlieferte Auslegung und Praxis, Tradition: biblische Texte", "Schrift: Handschrift der Pfarrer, Tradition: moderne Gottesdienstform", "Schrift: biblische Texte, Tradition: überlieferte Auslegung und Praxis", "Schrift: Gesetzbuch des Staates, Tradition: Brauchtum ohne Glaubensbezug"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide spielen in den Kirchen unterschiedliche Rollen."
  },
  {
    id: "q10_re_099",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Sakrament und Ritual?",
    answers: ["Sakrament: wiederkehrende Praxis, Ritual: heilige Handlung mit besonderer Bedeutung", "Sakrament: einmaliges Gebet ohne Bedeutung, Ritual: spontane Einzelhandlung", "Sakrament: weltliches Fest, Ritual: heilige Handlung nur für Priester", "Sakrament: heilige Handlung mit besonderer Bedeutung, Ritual: wiederkehrende Praxis"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Sakramente haben in den Kirchen besondere Bedeutung."
  },
  {
    id: "q10_re_100",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Amt und Charisma?",
    answers: ["Amt: geistliche Begabung, Charisma: institutionelle Rolle", "Amt: institutionelle Rolle, Charisma: geistliche Begabung", "Amt: Behörde des Staates, Charisma: gutes Aussehen", "Amt: Ehrentitel ohne Aufgabe, Charisma: erlernte Technik"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide prägen kirchliches Leben."
  },
  {
    id: "q10_re_101",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Gemeinde und Kirche?",
    answers: ["Gemeinde: lokale Gemeinschaft, Kirche: größere organisatorische Einheit", "Gemeinde: größere organisatorische Einheit, Kirche: lokale Gemeinschaft", "Gemeinde: nur das Rathaus, Kirche: nur das Gebäude mit Turm", "Gemeinde: weltweite Organisation, Kirche: einzelner Gottesdienst"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Begriffe überschneiden sich."
  },
  {
    id: "q10_re_102",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Laie und Kleriker?",
    answers: ["Laie: mit geistlichem Amt, Kleriker: nicht ordiniert", "Laie: ungläubiger Mensch, Kleriker: Lehrer an der Schule", "Laie: nicht ordiniert, Kleriker: mit geistlichem Amt", "Laie: Anfänger im Glauben, Kleriker: Mitglied im Kirchenchor"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Unterscheidung ist in den Kirchen unterschiedlich ausgeprägt."
  },
  {
    id: "q10_re_103",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Glauben und Aberglauben?",
    answers: ["Glaube: unreflektierte Furcht oder Magie, Aberglaube: vertrauende Überzeugung", "Glaube: sicheres Wissen aus Experimenten, Aberglaube: jede Form von Religion", "Glaube: vertrauende Überzeugung, Aberglaube: unreflektierte Furcht oder Magie", "Glaube: Angst vor Strafe, Aberglaube: begründete wissenschaftliche Erkenntnis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Abgrenzung ist historisch und theologisch wichtig."
  },
  {
    id: "q10_re_104",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Theologie und Religionswissenschaft?",
    answers: ["Theologie: distanziert beschreibend, Religionswissenschaft: aus dem Glauben heraus", "Theologie: Kritik an jeder Religion, Religionswissenschaft: Missionsarbeit", "Theologie: aus dem Glauben heraus, Religionswissenschaft: distanziert beschreibend", "Theologie: Geschichte der Staaten, Religionswissenschaft: Lehre der Bibel"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Disziplinen haben unterschiedliche Perspektiven."
  },
  {
    id: "q10_re_105",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Pastoral und Diakonie?",
    answers: ["Pastoral: soziale Hilfe, Diakonie: seelsorgliche Begleitung", "Pastoral: Landwirtschaft der Kirche, Diakonie: Kirchenmusik", "Pastoral: Predigt im Fernsehen, Diakonie: Verwaltung der Kirche", "Pastoral: seelsorgliche Begleitung, Diakonie: soziale Hilfe"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide dienen dem Menschen."
  },
  {
    id: "q10_re_106",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Bekenntnis und Dogma?",
    answers: ["Bekenntnis: verbindliche Lehrformulierung, Dogma: Ausdruck des Glaubens", "Bekenntnis: Geständnis vor Gericht, Dogma: persönliche Meinung", "Bekenntnis: Austritt aus der Kirche, Dogma: unverbindlicher Vorschlag", "Bekenntnis: Ausdruck des Glaubens, Dogma: verbindliche Lehrformulierung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide strukturieren den Glauben."
  },
  {
    id: "q10_re_107",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Spiritualität und Mystik?",
    answers: ["Spiritualität: intensive Gotteserfahrung, Mystik: gelebte Frömmigkeit", "Spiritualität: Glaube an Geister, Mystik: Zaubertricks auf der Bühne", "Spiritualität: strenge Kirchenregeln, Mystik: wissenschaftliche Theologie", "Spiritualität: gelebte Frömmigkeit, Mystik: intensive Gotteserfahrung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Mystik ist eine besondere Form der Spiritualität."
  },
  {
    id: "q10_re_108",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Kirche und Sekte?",
    answers: ["Kirche: etablierte Gemeinschaft, Sekte: oft abgespaltene, engere Gruppe", "Kirche: oft abgespaltene, engere Gruppe, Sekte: etablierte Gemeinschaft", "Kirche: staatliche Behörde, Sekte: Sektion eines Sportvereins", "Kirche: kleine Hausgemeinschaft, Sekte: weltweite Großreligion"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Begriff Sekte ist umstritten und wertend."
  },
  {
    id: "q10_re_109",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Tradition und Innovation in der Kirche?",
    answers: ["Tradition: Erneuerung, Innovation: Überliefertes", "Tradition: Erfindung, Innovation: Wiederholung", "Tradition: Überliefertes, Innovation: Erneuerung", "Tradition: Verbot, Innovation: Gebot"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Kirchen bewegen sich zwischen beiden Polen."
  },
  {
    id: "q10_re_110",
    category: "k10_religion",
    topic: "bibel_kirche",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die zentrale Botschaft der christlichen Ethik?",
    answers: ["Liebe zu Gott und zum Nächsten als Maßstab des Handelns", "Strenge Gesetzeserfüllung als einziger Maßstab des Handelns", "Wirtschaftlicher Erfolg als Ziel jedes christlichen Lebens", "Selbstverwirklichung ohne Rücksicht auf andere Menschen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Doppelgebot der Liebe fasst sie zusammen."
  },

  // ================================================================
  // 4. AKTUELLE ETHISCHE HERAUSFORDERUNGEN (35 Fragen)
  // ================================================================
  {
    id: "q10_re_111",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Bioethik?",
    answers: ["Die ethische Reflexion über den nachhaltigen Umgang mit der Natur", "Die ethische Reflexion über Leben, Medizin und Biotechnologie", "Die ethische Reflexion über gerechtes wirtschaftliches Handeln", "Die rechtliche Regelung medizinischer Berufe durch staatliche Behörden"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bioethik behandelt Fragen am Anfang und Ende des Lebens."
  },
  {
    id: "q10_re_112",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Umweltethik?",
    answers: ["Die ethische Reflexion über Leben und Medizin", "Die ethische Reflexion über wirtschaftliches Handeln", "Die ethische Reflexion über den Umgang mit der Natur", "Die naturwissenschaftliche Erforschung des Klimas"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Umweltethik fragt nach Verantwortung für die Schöpfung."
  },
  {
    id: "q10_re_113",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Medienethik?",
    answers: ["Die ethische Reflexion über gerechtes wirtschaftliches Handeln", "Die ethische Reflexion über den Umgang mit Medien und Informationen", "Die technische Herstellung von Filmen und Zeitungen in der Redaktion", "Die rechtliche Regelung des Urheberrechts durch staatliche Gesetze"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Medienethik betrifft Wahrheit, Privatsphäre und Verantwortung."
  },
  {
    id: "q10_re_114",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Wirtschaftsethik?",
    answers: ["Die ethische Reflexion über den Umgang mit der Natur", "Die ethische Reflexion über wirtschaftliches Handeln", "Die betriebswirtschaftliche Berechnung von Gewinnen", "Die staatliche Kontrolle der Steuereinnahmen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wirtschaftsethik fragt nach Gerechtigkeit und Verantwortung."
  },
  {
    id: "q10_re_115",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Friedensethik?",
    answers: ["Die ethische Reflexion über Medien und deren Informationen", "Die ethische Reflexion über Krieg, Frieden und Gewalt", "Die militärische Planung von Verteidigungsstrategien im Ernstfall", "Die diplomatische Verhandlung von internationalen Handelsabkommen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Friedensethik sucht nach gerechten und gewaltfreien Lösungen."
  },
  {
    id: "q10_re_116",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist digitale Ethik?",
    answers: ["Die technische Entwicklung neuer Computerprogramme durch Fachleute", "Die ethische Reflexion über Krieg und Frieden in der Weltgeschichte", "Die rechtliche Regelung des Datenschutzes durch staatliche Behörden", "Die ethische Reflexion über Digitalisierung, KI und Daten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Digitale Ethik betrifft Privatsphäre, Algorithmen und Verantwortung."
  },
  {
    id: "q10_re_117",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Nachhaltigkeit als ethisches Prinzip?",
    answers: ["Die Verantwortung für heutige und zukünftige Generationen", "Die Verantwortung ausschließlich für die heutige Generation", "Die alleinige Sorge um wirtschaftliches Wachstum", "Die alleinige Sorge um technischen Fortschritt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltigkeit verbindet ökologische, soziale und ökonomische Aspekte."
  },
  {
    id: "q10_re_118",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Generationengerechtigkeit?",
    answers: ["Die gleichmäßige Verteilung von Renten an alle Bürger eines Staates", "Die bevorzugte Förderung ausschließlich der jeweils jüngsten Generation", "Die gerechte Verteilung von Chancen und Lasten zwischen Generationen", "Die einseitige Bevorzugung älterer Generationen gegenüber jüngeren"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie betrifft Klima, Schulden und Ressourcen."
  },
  {
    id: "q10_re_119",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist globale Gerechtigkeit?",
    answers: ["Die Forderung nach fairen Bedingungen zwischen Ländern und Regionen", "Die Forderung nach gleichen Löhnen innerhalb eines einzelnen Landes", "Die Forderung nach der Gründung einer einzigen gemeinsamen Weltregierung", "Die Forderung nach vollständiger wirtschaftlicher Isolation einzelner Länder"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Globale Gerechtigkeit betrifft Armut, Handel und Klima."
  },
  {
    id: "q10_re_120",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist Menschenwürde in der modernen Ethik?",
    answers: ["Der gesetzlich verliehene Status besonders verdienter Personen im Staat", "Der unverlierbare Wert jedes Menschen als Grundlage von Rechten", "Der wirtschaftliche Nutzen eines Menschen für die gesamte Gesellschaft", "Der soziale Rang eines Menschen innerhalb seiner eigenen Gemeinschaft"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Menschenwürde steht im Zentrum ethischer und rechtlicher Debatten."
  },
  {
    id: "q10_re_121",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen ethischer und technischer Machbarkeit?",
    answers: ["Was technisch machbar ist, ist automatisch auch ethisch erlaubt", "Ethisch erlaubte Dinge sind niemals technisch umsetzbar", "Technik und Ethik betreffen völlig getrennte Lebensbereiche", "Technisch machbar heißt nicht ethisch erlaubt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bio- und Technikethik betonen diese Unterscheidung."
  },
  {
    id: "q10_re_122",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen individuellem und kollektivem Handeln?",
    answers: ["Individuell: Gruppen und Institutionen, kollektiv: einzelne Person", "Individuell: immer egoistisch, kollektiv: immer gerecht und gut", "Individuell: nur Kinder, kollektiv: nur Erwachsene im Beruf", "Individuell: einzelne Person, kollektiv: Gruppen und Institutionen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Ebenen sind ethisch relevant."
  },
  {
    id: "q10_re_123",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Prävention und Intervention?",
    answers: ["Prävention: eingreifen, Intervention: vorbeugen", "Prävention: bestrafen, Intervention: abwarten", "Prävention: verbieten, Intervention: belohnen", "Prävention: vorbeugen, Intervention: eingreifen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Strategien spielen in der Ethik eine Rolle."
  },
  {
    id: "q10_re_124",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Risiko und Gefahr?",
    answers: ["Risiko: abwägbare Möglichkeit, Gefahr: drohendes Unheil", "Risiko: drohendes Unheil, Gefahr: abwägbare Möglichkeit", "Risiko: sicherer Schaden, Gefahr: sicherer Gewinn", "Risiko: Glücksspiel, Gefahr: Versicherungsvertrag"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Risikoethik reflektiert den Umgang mit Unsicherheit."
  },
  {
    id: "q10_re_125",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Autonomie und Fürsorge?",
    answers: ["Autonomie: Unterstützung anderer, Fürsorge: Selbstbestimmung", "Autonomie: Abhängigkeit, Fürsorge: Bevormundung durch den Staat", "Autonomie: Einsamkeit, Fürsorge: Pflege nur durch Fachkräfte", "Autonomie: Selbstbestimmung, Fürsorge: Unterstützung anderer"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Prinzipien stehen in der Medizinethik in Spannung."
  },
  {
    id: "q10_re_126",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Gerechtigkeit und Fairness?",
    answers: ["Gerechtigkeit: situationsbezogene Angemessenheit, Fairness: allgemeines Prinzip", "Gerechtigkeit: persönliche Vorliebe, Fairness: nur Regeln im Sport", "Gerechtigkeit: Gleichbehandlung nur Reicher, Fairness: Gewinnen um jeden Preis", "Gerechtigkeit: allgemeines Prinzip, Fairness: situationsbezogene Angemessenheit"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Begriffe überschneiden sich."
  },
  {
    id: "q10_re_127",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen absoluter und relativer Armut?",
    answers: ["Absolut: im Vergleich zum Durchschnitt, relativ: existenzbedrohend", "Absolut: nur in Kriegsgebieten, relativ: nur bei Rentnern", "Absolut: existenzbedrohend, relativ: im Vergleich zum Durchschnitt", "Absolut: ohne Auto, relativ: ohne Urlaub im Ausland"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Formen sind ethisch relevant."
  },
  {
    id: "q10_re_128",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Flucht und Migration ethisch betrachtet?",
    answers: ["Flucht: oft ökonomisch oder sozial motiviert, Migration: Schutzsuche vor Gefahr", "Flucht: Urlaubsreise ins Ausland, Migration: Umzug innerhalb einer Stadt", "Flucht: immer freiwillig, Migration: immer erzwungen durch Krieg", "Flucht: Schutzsuche vor Gefahr, Migration: oft ökonomisch oder sozial motiviert"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide erfordern ethische und rechtliche Antworten."
  },
  {
    id: "q10_re_129",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Integration und Assimilation?",
    answers: ["Integration: Angleichung, Assimilation: Teilhabe bei Bewahrung von Identität", "Integration: völlige Trennung der Gruppen, Assimilation: Ausweisung", "Integration: Abschottung der Neuen, Assimilation: Pflicht zum Sprachkurs", "Integration: Teilhabe bei Bewahrung von Identität, Assimilation: Angleichung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Integration betont wechselseitige Anerkennung."
  },
  {
    id: "q10_re_130",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Toleranz und Akzeptanz?",
    answers: ["Toleranz: anerkennen, Akzeptanz: dulden", "Toleranz: ablehnen, Akzeptanz: verbieten", "Toleranz: bekämpfen, Akzeptanz: ignorieren", "Toleranz: dulden, Akzeptanz: anerkennen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind für das Zusammenleben wichtig."
  },
  {
    id: "q10_re_131",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Privatsphäre und Transparenz?",
    answers: ["Privatsphäre: Offenlegung, Transparenz: Schutz des Persönlichen", "Privatsphäre: Schutz des Persönlichen, Transparenz: Offenlegung", "Privatsphäre: eigenes Grundstück, Transparenz: Fenster aus Glas", "Privatsphäre: Geheimhaltung von Straftaten, Transparenz: Datenhandel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Werte stehen in digitalen Kontexten in Spannung."
  },
  {
    id: "q10_re_132",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Wahrheit und Meinung in der Medienethik?",
    answers: ["Wahrheit: subjektiv, Meinung: überprüfbar", "Wahrheit: was die Mehrheit glaubt, Meinung: Fakt", "Wahrheit: Nachricht, Meinung: Werbung", "Wahrheit: überprüfbar, Meinung: subjektiv"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Unterscheidung ist zentral gegen Desinformation."
  },
  {
    id: "q10_re_133",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Verantwortung und Haftung?",
    answers: ["Verantwortung: rechtlich, Haftung: ethisch-moralisch", "Verantwortung: nur im Beruf, Haftung: nur in der Familie", "Verantwortung: Strafe, Haftung: Gefängnis", "Verantwortung: ethisch-moralisch, Haftung: rechtlich"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide können sich überschneiden."
  },
  {
    id: "q10_re_134",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen nachhaltigem und konsumorientiertem Lebensstil?",
    answers: ["Nachhaltig: ressourcenschonend, konsumorientiert: verbrauchsbetont", "Nachhaltig: verbrauchsbetont, konsumorientiert: ressourcenschonend", "Nachhaltig: lange haltbar verpackt, konsumorientiert: sparsam", "Nachhaltig: teuer und modern, konsumorientiert: billig und alt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Lebensstile haben ethische Dimensionen."
  },
  {
    id: "q10_re_135",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen globaler und lokaler Verantwortung?",
    answers: ["Global: vor Ort, lokal: weltweite Zusammenhänge", "Global: nur Politiker, lokal: nur Privatpersonen", "Global: weltweite Zusammenhänge, lokal: vor Ort", "Global: nur Firmen, lokal: nur Kirchengemeinden"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Ebenen sind miteinander verbunden."
  },
  {
    id: "q10_re_136",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen ethischer Reflexion und moralischem Urteil?",
    answers: ["Reflexion: systematische Prüfung, Urteil: konkrete Entscheidung", "Reflexion: konkrete Entscheidung, Urteil: systematische Prüfung", "Reflexion: spontanes Gefühl, Urteil: Spruch eines Gerichts", "Reflexion: Spiegelbild, Urteil: Meinung der Mehrheit"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide gehören zum ethischen Prozess."
  },
  {
    id: "q10_re_137",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Prinzip und Kompromiss?",
    answers: ["Prinzip: Annäherung im Konflikt, Kompromiss: grundlegende Orientierung", "Prinzip: Laune des Augenblicks, Kompromiss: Sieg einer Seite", "Prinzip: Ausnahme von der Regel, Kompromiss: Abbruch des Gesprächs", "Prinzip: grundlegende Orientierung, Kompromiss: Annäherung im Konflikt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Demokratie und Ethik brauchen beides."
  },
  {
    id: "q10_re_138",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Hoffnung und Optimismus?",
    answers: ["Hoffnung: positive Erwartung, Optimismus: Vertrauen trotz Unsicherheit", "Hoffnung: sichere Gewissheit, Optimismus: Leugnen aller Probleme", "Hoffnung: Vertrauen trotz Unsicherheit, Optimismus: positive Erwartung", "Hoffnung: passives Abwarten, Optimismus: religiöser Glaube"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Hoffnung hat in religiösen Traditionen besondere Bedeutung."
  },
  {
    id: "q10_re_139",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Schuld und Scham?",
    answers: ["Schuld: Gefühl der Bloßstellung, Scham: Verletzung einer Norm", "Schuld: Gefühl der Freude, Scham: Strafe durch das Gericht", "Schuld: Geldschuld bei der Bank, Scham: Höflichkeit", "Schuld: Verletzung einer Norm, Scham: Gefühl der Bloßstellung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Emotionen spielen in der Ethik eine Rolle."
  },
  {
    id: "q10_re_140",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Vergebung und Vergessen?",
    answers: ["Vergebung: Nicht-mehr-erinnern, Vergessen: Loslassen der Schuld", "Vergebung: Bestrafung der Schuld, Vergessen: bewusstes Verzeihen", "Vergebung: Leugnen der Tat, Vergessen: Wiedergutmachung", "Vergebung: Loslassen der Schuld, Vergessen: Nicht-mehr-erinnern"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Vergebung setzt Erinnerung voraus."
  },
  {
    id: "q10_re_141",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Sinn und Glück?",
    answers: ["Sinn: subjektives Wohlbefinden, Glück: Bedeutung und Orientierung", "Sinn: Bedeutung und Orientierung, Glück: subjektives Wohlbefinden", "Sinn: körperliche Wahrnehmung, Glück: Gewinn im Lotto", "Sinn: Pflicht zur Arbeit, Glück: Abwesenheit von Regeln"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Fragen prägen ethische und religiöse Reflexion."
  },
  {
    id: "q10_re_142",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen ethischer Bildung und moralischer Erziehung?",
    answers: ["Ethische Bildung: Urteilsfähigkeit, moralische Erziehung: Habitualisierung von Normen", "Ethische Bildung: Habitualisierung von Normen, moralische Erziehung: Urteilsfähigkeit", "Ethische Bildung: Auswendiglernen von Geboten, moralische Erziehung: Strafen", "Ethische Bildung: Schulabschluss, moralische Erziehung: Benimmkurs für Erwachsene"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide ergänzen sich in der Schule."
  },
  {
    id: "q10_re_143",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen religiöser und säkularer Ethik?",
    answers: ["Religiös: unabhängig von Religion, säkular: begründet in Glauben", "Religiös: nur für Priester, säkular: nur für Politiker", "Religiös: streng, säkular: ohne jede Moral und Regeln", "Religiös: begründet in Glauben, säkular: unabhängig von Religion"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide können zu ähnlichen Normen gelangen."
  },
  {
    id: "q10_re_144",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Dialog und Debatte?",
    answers: ["Dialog: Gegeneinander von Positionen, Debatte: gemeinsames Suchen", "Dialog: Rede einer einzigen Person, Debatte: Gespräch ohne Thema", "Dialog: Streit mit Gewalt, Debatte: Schweigen aller Beteiligten", "Dialog: gemeinsames Suchen, Debatte: Gegeneinander von Positionen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Dialog zielt auf Verstehen, Debatte auf Überzeugen."
  },
  {
    id: "q10_re_145",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Überzeugung und Fanatismus?",
    answers: ["Überzeugung: intolerante Absolutheit, Fanatismus: begründete Haltung", "Überzeugung: blinder Gehorsam, Fanatismus: Begeisterung für Sport", "Überzeugung: Zweifel an allem, Fanatismus: offene Diskussion", "Überzeugung: begründete Haltung, Fanatismus: intolerante Absolutheit"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Fanatismus schließt Dialog aus."
  },
  {
    id: "q10_re_146",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen Hoffnung und Illusion?",
    answers: ["Hoffnung: trügerische Vorstellung, Illusion: begründetes Vertrauen", "Hoffnung: begründetes Vertrauen, Illusion: trügerische Vorstellung", "Hoffnung: sichere Tatsache, Illusion: wissenschaftliches Modell", "Hoffnung: Verzweiflung, Illusion: genaue Wahrnehmung"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Hoffnung bleibt an Realität gebunden."
  },
  {
    id: "q10_re_147",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen ethischer Kompetenz und moralischer Haltung?",
    answers: ["Kompetenz: gelebte Einstellung, Haltung: Fähigkeit zu urteilen", "Kompetenz: Zuständigkeit im Amt, Haltung: Körperhaltung beim Sitzen", "Kompetenz: Fähigkeit zu urteilen, Haltung: gelebte Einstellung", "Kompetenz: Meinung ohne Gründe, Haltung: auswendig gelernte Regel"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind Ziele ethischer Bildung."
  },
  {
    id: "q10_re_148",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen globaler und planetarer Verantwortung?",
    answers: ["Global: erdbezogen inklusive Natur, planetar: menschheitsbezogen", "Global: nur Europa, planetar: das ganze Sonnensystem", "Global: nur Wirtschaft, planetar: nur Weltraumforschung", "Global: menschheitsbezogen, planetar: erdbezogen inklusive Natur"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Planetare Verantwortung betont die Grenzen der Erde."
  },
  {
    id: "q10_re_149",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist der Unterschied zwischen ethischer Theorie und ethischer Praxis?",
    answers: ["Theorie: gelebtes Handeln, Praxis: systematische Reflexion", "Theorie: unbewiesene Vermutung, Praxis: Arztbesuch", "Theorie: Handeln ohne Nachdenken, Praxis: Lehrbuchwissen", "Theorie: systematische Reflexion, Praxis: gelebtes Handeln"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide gehören zusammen."
  },
  {
    id: "q10_re_150",
    category: "k10_religion",
    topic: "aktuelle_ethik",
    area: "schule",
    grade: 10,
    subject: "religion_ethik",
    question: "Was ist die zentrale Aufgabe von Religion und Ethik in der Schule?",
    answers: ["Ausschließlich religiöses Wissen auswendig lernen zu lassen", "Zur Urteilsfähigkeit, Verantwortungsübernahme und Dialogfähigkeit beizutragen", "Allein die strikte Einhaltung fester Regeln im Klassenzimmer zu kontrollieren", "Nur die persönliche Glaubensüberzeugung der Lehrkraft weiterzugeben"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Fächer fördern mündige Persönlichkeiten."
  }
];
