const K10_INFORMATIK_QUESTIONS = [
  // ================================================================
  // 1. INFORMATION, DATEN & CODIERUNG (35 Fragen)
  // ================================================================
  {
    id: "q10_i_001",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Daten und Information?",
    answers: ["Information ist in der Informatik nur eine andere Bezeichnung für dieselben Daten", "Daten und Information sind in der Informatik in jedem Fall völlig identisch", "Information besteht stets nur aus rohen, völlig unstrukturierten Zeichenfolgen", "Daten sind rohe Zeichenfolgen, Information ist interpretierte Bedeutung"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Information entsteht durch Interpretation von Daten."
  },
  {
    id: "q10_i_002",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Bit?",
    answers: ["Eine feste Gruppe von acht zusammengehörigen Binärwerten", "Ein einzelnes lesbares Zeichen wie ein Buchstabe oder eine Zahl", "Eine Speichereinheit von genau eintausend Byte", "Die kleinste Informationseinheit mit den Zuständen 0 oder 1"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bit steht für Binary Digit."
  },
  {
    id: "q10_i_003",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Wie viele Bits hat ein Byte?",
    answers: ["32 Bits", "16 Bits", "8 Bits", "4 Bits"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Byte = 8 Bit."
  },
  {
    id: "q10_i_004",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das Dualsystem?",
    answers: ["Ein Zahlensystem mit der Basis 10 (Ziffern 0 bis 9)", "Ein Zahlensystem mit der Basis 16 (Ziffern 0–9 und A–F)", "Ein Zahlensystem mit der Basis 8 (Ziffern 0 bis 7)", "Ein Zahlensystem mit der Basis 2 (Ziffern 0 und 1)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Computer arbeiten intern im Dualsystem."
  },
  {
    id: "q10_i_005",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das Hexadezimalsystem?",
    answers: ["Ein Zahlensystem mit der Basis 2, also den Ziffern 0 und 1", "Ein Zahlensystem mit der Basis 10, den Ziffern 0 bis 9", "Ein Zahlensystem mit der Basis 8, den Ziffern 0 bis 7", "Ein Zahlensystem mit der Basis 16 (0–9 und A–F)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Hexadezimal wird oft für Speicheradressen und Farben genutzt."
  },
  {
    id: "q10_i_006",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ASCII?",
    answers: ["Ein Zeichencode, der Zeichen durch Zahlen darstellt", "Eine Programmiersprache für eingebettete Kleinsysteme", "Ein Bildformat für verlustfrei komprimierte Grafiken", "Ein Dateiformat zur Archivierung mehrerer Dateien"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "ASCII codiert 128 Zeichen."
  },
  {
    id: "q10_i_007",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Unicode?",
    answers: ["Ein Zeichencode, der fast alle Schriftzeichen der Welt abbildet", "Ein Dateiformat, das ausschließlich einfache Textdokumente speichert", "Eine ältere, auf 128 Zeichen begrenzte Version von ASCII", "Ein Bildformat, das nur einfache Symbolgrafiken darstellt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "UTF-8 ist eine häufige Unicode-Kodierung."
  },
  {
    id: "q10_i_008",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Pixelgrafik?",
    answers: ["Ein Bild, das aus mathematischen Linien und Formen besteht", "Ein Bild, das aus einzelnen Bildpunkten (Pixeln) besteht", "Ein Text, der aus einzelnen Buchstaben und Zeichen besteht", "Ein Sound, der aus einzelnen digitalen Tonproben besteht"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Pixelgrafiken verlieren bei Vergrößerung an Qualität."
  },
  {
    id: "q10_i_009",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Vektorgrafik?",
    answers: ["Ein Sound, der aus digital abgetasteten Tonproben besteht", "Ein Bild, das aus mathematischen Formen und Linien besteht", "Ein Bild aus Pixeln, das aus einzelnen Bildpunkten besteht", "Ein Text, der ausschließlich aus formatierten Zeichen besteht"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Vektorgrafiken skalieren verlustfrei."
  },
  {
    id: "q10_i_010",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Kompression?",
    answers: ["Die Verkleinerung der Datenmenge bei möglichst geringem Qualitätsverlust", "Nur die dauerhafte Speicherung von Daten auf einem beliebigen Datenträger", "Nur die Übertragung von Daten über ein beliebiges Netzwerk hinweg", "Nur die Verschlüsselung von Daten mit einem geheimen, sicheren Schlüssel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verlustbehaftet und verlustfrei sind zwei Arten."
  },
  {
    id: "q10_i_011",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist verlustfreie Kompression?",
    answers: ["Kompression, bei der ein Teil der ursprünglichen Originaldaten dauerhaft verloren geht", "Eine Methode, die ausschließlich bei einfachen Bilddateien angewendet wird", "Kompression, bei der die Originaldaten vollständig wiederherstellbar sind", "Eine Methode, die ausschließlich bei einfachen Audiodateien angewendet wird"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "ZIP und PNG nutzen verlustfreie Verfahren."
  },
  {
    id: "q10_i_012",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist verlustbehaftete Kompression?",
    answers: ["Kompression, bei der Informationen dauerhaft weggelassen werden", "Kompression, die ausschließlich bei Textdateien eingesetzt wird", "Kompression ohne jeglichen Verlust an Bild- oder Tonqualität", "Eine reine Methode zur strukturierten Speicherung in Datenbanken"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "JPEG und MP3 sind verlustbehaftet."
  },
  {
    id: "q10_i_013",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Dateiformat?",
    answers: ["Ein Programm, das ausschließlich nur zum Anzeigen von Dateien genutzt wird", "Ein gewöhnlicher Ordner, in dem mehrere Dateien desselben Typs liegen", "Nur der Name einer Datei ohne jede festgelegte innere Struktur", "Eine festgelegte Struktur zur Speicherung von Daten einer bestimmten Art"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: .txt, .jpg, .mp3, .pdf."
  },
  {
    id: "q10_i_014",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Metadaten?",
    answers: ["Nur die eigentlichen Inhaltsdaten", "Nur komprimierte Daten", "Daten über andere Daten", "Nur verschlüsselte Daten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Metadaten beschreiben Eigenschaften von Dateien."
  },
  {
    id: "q10_i_015",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Algorithmus?",
    answers: ["Nur eine mathematische Formel zur Berechnung geometrischer Flächen", "Nur ein bereits fertig programmiertes und getestetes Computerprogramm", "Eine endliche Folge eindeutiger Schritte zur Lösung eines Problems", "Nur eine physische Hardwarekomponente im Inneren eines Computers"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Algorithmen sind Grundlage der Programmierung."
  },
  {
    id: "q10_i_016",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Variable in der Programmierung?",
    answers: ["Nur ein fester Wert, der niemals verändert werden kann", "Nur eine Funktion, die einen festen Wert berechnet", "Ein benannter Speicherplatz für veränderbare Werte", "Nur eine Schleife, die mehrfach ausgeführt wird"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Variablen speichern Daten während der Programmausführung."
  },
  {
    id: "q10_i_017",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Datentyp?",
    answers: ["Die Art der Daten, die eine Variable speichern kann", "Nur der Speicherort, an dem eine Variable abgelegt wird", "Nur die Programmiersprache, in der Code geschrieben wird", "Nur der Name, den eine Variable im Code trägt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Häufige Typen: Integer, String, Boolean."
  },
  {
    id: "q10_i_018",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Boolesche Variable?",
    answers: ["Eine Variable, die ausschließlich Bilder speichern kann", "Eine Variable, die nur wahr oder falsch speichern kann", "Eine Variable, die ausschließlich Texte speichern kann", "Eine Variable, die ausschließlich Zahlen speichern kann"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Boolean-Werte sind true/false bzw. 1/0."
  },
  {
    id: "q10_i_019",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Array / eine Liste?",
    answers: ["Nur eine einzelne Variable, die genau einen gespeicherten Wert enthält", "Nur eine Funktion, die stets einen einzigen Wert zurückgibt", "Nur eine Schleife, die eine feste Anzahl an Werten zählt", "Eine geordnete Sammlung von Elementen gleichen oder ähnlichen Typs"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Arrays speichern mehrere Werte unter einem Namen."
  },
  {
    id: "q10_i_020",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Datenbank?",
    answers: ["Nur eine einzelne Excel-Tabelle ohne jede weitere Verknüpfung zu anderen Daten", "Nur ein Ordner, in dem beliebige Dateien lose abgelegt sind", "Nur eine einzelne Textdatei ohne jede feste innere Struktur", "Ein organisiertes System zur Speicherung und Verwaltung großer Datenmengen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Datenbanken ermöglichen effiziente Abfragen."
  },
  {
    id: "q10_i_021",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist SQL?",
    answers: ["Nur ein Betriebssystem zur Verwaltung aller vorhandenen Hardwarekomponenten", "Nur ein Dateiformat zum Speichern einzelner Tabellenwerte", "Eine Sprache zur Abfrage und Bearbeitung von relationalen Datenbanken", "Nur eine Programmiersprache zur Entwicklung mobiler Apps"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "SQL steht für Structured Query Language."
  },
  {
    id: "q10_i_022",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein relationales Datenbankmodell?",
    answers: ["Daten werden in Tabellen mit Beziehungen (Relationen) gespeichert", "Daten werden ausschließlich als Graph mit verbundenen Knoten gespeichert", "Daten werden ausschließlich als reiner Fließtext gespeichert", "Daten werden ausschließlich als einzelne Bilddateien gespeichert"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Tabellen sind über Schlüssel verbunden."
  },
  {
    id: "q10_i_023",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Primärschlüssel?",
    answers: ["Ein eindeutiges Attribut, das jeden Datensatz in einer Tabelle identifiziert", "Nur ein Fremdschlüssel, der auf einen Datensatz einer anderen Tabelle verweist", "Nur ein Datentyp, der zulässige Werte einer Spalte beschreibt", "Nur ein Index, der die Suche in einer Tabelle beschleunigt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Primärschlüssel gewährleisten Eindeutigkeit."
  },
  {
    id: "q10_i_024",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Fremdschlüssel?",
    answers: ["Nur ein Primärschlüssel, der jeden Datensatz eindeutig identifizieren kann", "Nur ein Index, der die Suche in großen Tabellen beschleunigt", "Nur ein Datentyp, der Zahlen oder Texte einheitlich beschreibt", "Ein Attribut, das auf den Primärschlüssel einer anderen Tabelle verweist"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Fremdschlüssel erzeugen Beziehungen zwischen Tabellen."
  },
  {
    id: "q10_i_025",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Normalisierung in Datenbanken?",
    answers: ["Nur die Verschlüsselung von Daten mit einem geheimen, sicheren Schlüssel", "Nur die regelmäßige Sicherung der Datenbank auf einem Server", "Nur die Kompression von Daten zur allgemeinen Platzersparnis", "Die strukturierte Aufteilung von Daten zur Vermeidung von Redundanz"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Normalformen helfen bei sauberer Datenbankstruktur."
  },
  {
    id: "q10_i_026",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Big Data?",
    answers: ["Nur ganz einfache Textdateien mit wenigen Zeilen an Inhalt, Struktur und sehr einfachem Umfang", "Sehr große und komplexe Datenmengen, die mit klassischen Methoden schwer zu verarbeiten sind", "Nur digitale Bilder, die zentral auf einem einzelnen, festen Server gespeichert sind", "Nur kleine Datensätze, die problemlos von Hand ausgewertet werden können und passen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Big Data erfordert spezielle Technologien."
  },
  {
    id: "q10_i_027",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Hash-Wert?",
    answers: ["Nur eine zufällig vergebene Netzwerkadresse", "Ein aus Daten berechneter fester Fingerabdruck", "Nur ein geheimer Schlüssel zur Verschlüsselung", "Nur ein vom Nutzer selbst gewähltes Passwort"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Hash-Funktionen werden für Integrität und Passwörter genutzt."
  },
  {
    id: "q10_i_028",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Verschlüsselung?",
    answers: ["Nur die Kompression von Daten zur allgemeinen Platzersparnis", "Nur die dauerhafte Speicherung von Daten auf einer externen Festplatte", "Nur die Übertragung von Daten über ein beliebiges Netzwerk", "Die Umwandlung von Daten in eine unleserliche Form mit Schlüssel"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Verschlüsselung schützt Vertraulichkeit."
  },
  {
    id: "q10_i_029",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist symmetrische Verschlüsselung?",
    answers: ["Nur Kompression", "Ver- und Entschlüsselung mit unterschiedlichen Schlüsseln", "Nur Hashing", "Ver- und Entschlüsselung mit demselben Schlüssel"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "AES ist ein bekanntes symmetrisches Verfahren."
  },
  {
    id: "q10_i_030",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist asymmetrische Verschlüsselung?",
    answers: ["Ver- und Entschlüsselung mit einem Schlüsselpaar", "Nur Hashing", "Nur Kompression", "Ver- und Entschlüsselung mit demselben Schlüssel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "RSA ist ein bekanntes asymmetrisches Verfahren."
  },
  {
    id: "q10_i_031",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein digitaler Fingerabdruck / Hash?",
    answers: ["Nur ein geheimer Schlüssel zur Verschlüsselung von Daten", "Nur ein vom Nutzer selbst gewähltes Passwort", "Nur ein digitales Zertifikat einer vertrauenswürdigen Stelle", "Ein kurzer, eindeutiger Wert, der aus Daten berechnet wird"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Hashes prüfen Integrität von Dateien."
  },
  {
    id: "q10_i_032",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Base64?",
    answers: ["Nur eine Verschlüsselung von Daten mit einem Schlüssel", "Nur ein Dateiformat für komprimierte Bilddaten", "Nur eine Kompression zur Verringerung der Datenmenge", "Eine Kodierung von Binärdaten in lesbare ASCII-Zeichen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Base64 wird oft für E-Mail-Anhänge und Webdaten genutzt."
  },
  {
    id: "q10_i_033",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein QR-Code?",
    answers: ["Ein zweidimensionaler Code, der Informationen speichern kann", "Nur ein einfaches Foto ohne jede gespeicherte Information darin", "Nur ein einfacher Link, der direkt im Browser eingegeben wird", "Nur ein eindimensionaler Strichcode aus einfachen Balken"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "QR-Codes können Texte, URLs und mehr speichern."
  },
  {
    id: "q10_i_034",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Open Data?",
    answers: ["Frei zugängliche und nutzbare Daten ohne oder mit minimalen Einschränkungen", "Nur streng geheime Daten staatlicher und militärischer Behörden weltweit", "Nur kostenpflichtige Daten kommerzieller Anbieter und großer Konzerne", "Nur persönliche Daten einzelner, namentlich genannter Privatpersonen weltweit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Open Data fördert Transparenz und Innovation."
  },
  {
    id: "q10_i_035",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen analog und digital?",
    answers: ["Analog bedeutet immer eine digitale Signalverarbeitung", "Analog: stufenlos, digital: in diskreten Werten (0/1)", "Analog und digital beschreiben in der Technik dasselbe Prinzip", "Digital bedeutet immer eine stufenlose Signalübertragung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Digitale Systeme arbeiten mit diskreten Zuständen."
  },

  // ================================================================
  // 2. ALGORITHMEN & PROGRAMMIERUNG (40 Fragen)
  // ================================================================
  {
    id: "q10_i_036",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Sequenz in einem Algorithmus?",
    answers: ["Nur eine einzelne Funktion ohne weitere Anweisungen", "Die hintereinander ausgeführte Abfolge von Anweisungen", "Nur eine mehrfache Wiederholung derselben einzelnen Anweisung", "Nur eine Entscheidung zwischen zwei möglichen Wegen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sequenz ist die einfachste Kontrollstruktur."
  },
  {
    id: "q10_i_037",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Verzweigung (If-Then-Else)?",
    answers: ["Nur eine Wiederholung von Anweisungen ohne jede Bedingung", "Nur eine feste Abfolge von Anweisungen ganz ohne jede mögliche Auswahl davon", "Nur ein wiederverwendbarer, benannter Abschnitt aus Code", "Eine Entscheidung, die je nach Bedingung unterschiedliche Wege nimmt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Verzweigungen ermöglichen bedingte Ausführung."
  },
  {
    id: "q10_i_038",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Schleife?",
    answers: ["Nur eine einmalige Abfolge von Anweisungen ganz ohne Wiederholung", "Nur eine Entscheidung zwischen zwei möglichen Wegen", "Nur ein wiederverwendbarer, benannter Codeabschnitt", "Eine Wiederholung von Anweisungen, solange eine Bedingung gilt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Schleifen sparen Code und ermöglichen Iteration."
  },
  {
    id: "q10_i_039",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Zählschleife (For-Schleife)?",
    answers: ["Eine Schleife, die eine feste Anzahl von Wiederholungen ausführt", "Nur eine Entscheidung zwischen zwei möglichen Wegen", "Nur eine Schleife, die von einer Bedingung abhängt", "Nur eine Schleife, die niemals von selbst endet oder abbrechen kann"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "For-Schleifen kennen den Wiederholungsbereich."
  },
  {
    id: "q10_i_040",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine bedingte Schleife (While-Schleife)?",
    answers: ["Nur eine einmalige Abfolge von Anweisungen", "Nur ein wiederverwendbarer, benannter Codeabschnitt", "Eine Schleife, die läuft, solange eine Bedingung wahr ist", "Nur eine Schleife mit fest vorgegebener Anzahl an Durchläufen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "While-Schleifen prüfen die Bedingung vor jedem Durchlauf."
  },
  {
    id: "q10_i_041",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Funktion / Prozedur?",
    answers: ["Nur eine Wiederholung von Anweisungen im Programm", "Nur eine Entscheidung zwischen zwei möglichen Wegen", "Nur ein Speicherplatz für einen einzelnen Wert", "Ein benannter, wiederverwendbarer Codeabschnitt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Funktionen strukturieren und modularisieren Programme."
  },
  {
    id: "q10_i_042",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Parameter?",
    answers: ["Nur der Wert, den eine Funktion zurückgibt", "Nur eine Variable innerhalb einer Schleife", "Nur eine Variable im übergeordneten Hauptprogramm", "Ein Wert, der an eine Funktion übergeben wird"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Parameter machen Funktionen flexibel."
  },
  {
    id: "q10_i_043",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Rückgabewert?",
    answers: ["Nur eine gewöhnliche Variable im Hauptprogramm", "Nur ein Wert, der an eine Funktion übergeben wird", "Der Wert, den eine Funktion an den Aufrufer zurückgibt", "Nur eine Meldung, die bei einem Fehler ausgegeben wird"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Funktionen können Ergebnisse zurückliefern."
  },
  {
    id: "q10_i_044",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Rekursion?",
    answers: ["Eine Funktion, die sich selbst aufruft", "Nur eine Entscheidung zwischen zwei möglichen Wegen", "Nur eine feste Abfolge von Anweisungen", "Nur eine Wiederholung mit fester Anzahl an Durchläufen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Rekursion braucht eine Abbruchbedingung."
  },
  {
    id: "q10_i_045",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Sortieralgorithmus?",
    answers: ["Nur ein Algorithmus zur Verkleinerung von Datenmengen", "Nur ein Algorithmus zur Verschlüsselung von Daten", "Nur ein Algorithmus, der ein bestimmtes Element in einer Liste findet", "Ein Algorithmus, der Elemente einer Liste in eine Ordnung bringt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Bubble Sort, Selection Sort, Quicksort."
  },
  {
    id: "q10_i_046",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Bubble Sort?",
    answers: ["Ein Suchalgorithmus, der ein bestimmtes Element in einer Liste findet", "Ein einfacher Sortieralgorithmus, der benachbarte Elemente vertauscht", "Ein Algorithmus, der Daten platzsparend und verlustfrei komprimiert", "Ein sehr schneller, hochkomplexer Sortieralgorithmus"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Bubble Sort ist anschaulich, aber ineffizient für große Listen."
  },
  {
    id: "q10_i_047",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Suchalgorithmus?",
    answers: ["Nur ein Algorithmus zur Verschlüsselung von Nachrichten", "Ein Algorithmus, der ein Element in einer Datenstruktur findet", "Nur ein Algorithmus zur Verkleinerung von Datenmengen", "Nur ein Algorithmus, der Elemente in eine feste Ordnung bringt"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Lineare und binäre Suche sind grundlegend."
  },
  {
    id: "q10_i_048",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist binäre Suche?",
    answers: ["Nur eine einfache Methode zum Sortieren von Zahlen", "Nur eine einfache Methode zur Verschlüsselung von Daten", "Eine Suche, die immer stets nacheinander jedes einzelne Element prüft", "Eine effiziente Suche in einer sortierten Liste durch Halbierung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Binäre Suche benötigt eine sortierte Liste."
  },
  {
    id: "q10_i_049",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die Komplexität eines Algorithmus?",
    answers: ["Nur die reine Anzahl der insgesamt geschriebenen Codezeilen eines Programms", "Ein Maß dafür, wie der Ressourcenbedarf mit der Eingabegröße wächst", "Nur die verwendete Programmiersprache eines Softwareprojekts", "Nur die optische Länge des vom Entwickler geschriebenen Quellcodes"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Oft in O-Notation (Big O) angegeben."
  },
  {
    id: "q10_i_050",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was bedeutet O(n) bei der Komplexität?",
    answers: ["Der Aufwand bleibt bei jeder Eingabegröße konstant", "Der Aufwand wächst quadratisch mit der Eingabegröße", "Der Aufwand wächst logarithmisch mit der Eingabegröße", "Der Aufwand wächst linear mit der Eingabegröße"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Lineare Suche hat typischerweise O(n)."
  },
  {
    id: "q10_i_051",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Pseudocode?",
    answers: ["Nur echter, direkt vom Computer ausführbarer Programmcode", "Nur maschinennaher Code für den Prozessor eines Computers", "Nur reiner Assemblercode mit einem festen, unveränderlichen Befehlssatz", "Eine menschenlesbare Beschreibung eines Algorithmus ohne strikte Syntax"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Pseudocode hilft beim Entwurf vor dem Programmieren."
  },
  {
    id: "q10_i_052",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Struktogramm / Nassi-Shneiderman-Diagramm?",
    answers: ["Nur ein Diagramm zur Darstellung von Klassenbeziehungen", "Nur ein Diagramm mit Pfeilen und Entscheidungssymbolen", "Eine grafische Darstellung von Algorithmen mit Blöcken", "Nur ein Diagramm zur Darstellung von Datenbanktabellen"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Struktogramme visualisieren Kontrollstrukturen."
  },
  {
    id: "q10_i_053",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Flussdiagramm?",
    answers: ["Nur ein Diagramm zur ganz rein grafischen Darstellung von Klassen und ihren Beziehungen", "Nur ein Diagramm zur Darstellung von Netzwerkverbindungen und Geräten", "Eine grafische Darstellung von Abläufen mit Symbolen für Schritte und Entscheidungen", "Nur ein Diagramm mit rechteckigen Blöcken ohne Entscheidungssymbole"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Flussdiagramme sind weit verbreitet."
  },
  {
    id: "q10_i_054",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Debugging?",
    answers: ["Das systematische Finden und Beheben von Fehlern im Programm", "Nur das erstmalige Schreiben von neuem Programmcode", "Nur das einmalige Ausführen eines fertigen Programms", "Nur das einmalige Übersetzen von Quellcode in reinen Maschinencode"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Debugger helfen beim schrittweisen Testen."
  },
  {
    id: "q10_i_055",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Syntaxfehler?",
    answers: ["Ein Fehler in der gedanklichen Lösung des Problems", "Ein Fehler gegen die Regeln der Programmiersprache", "Ein Fehler, der durch defekte Hardware verursacht wird", "Ein Fehler, der erst während der Programmausführung auftritt"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Syntaxfehler werden oft schon beim Übersetzen erkannt."
  },
  {
    id: "q10_i_056",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein logischer Fehler?",
    answers: ["Ein Fehler, der ausschließlich durch dauerhaft defekte Hardware verursacht wird", "Ein Fehler, bei dem das Programm läuft, aber falsche Ergebnisse liefert", "Ein Fehler, der ausschließlich gegen die Sprachregeln verstößt", "Ein Fehler, den ausschließlich der Compiler beim Übersetzen meldet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Logische Fehler sind oft schwerer zu finden."
  },
  {
    id: "q10_i_057",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Compiler?",
    answers: ["Ein Programm, das Quellcode in ausführbaren Maschinencode übersetzt", "Ein Programm, das gezielt nach Fehlern im Quellcode sucht", "Ein Programm, mit dem man Quellcode bequem und komfortabel schreiben kann", "Ein Programm, das Quellcode Zeile für Zeile direkt ausführt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Compiler erzeugen eine ausführbare Datei."
  },
  {
    id: "q10_i_058",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Interpreter?",
    answers: ["Ein Programm, mit dem man Quellcode schreiben kann", "Ein Programm, das gezielt Fehler im Quellcode sucht", "Ein Programm, das Quellcode Zeile für Zeile ausführt", "Ein Programm, das Quellcode in Maschinencode übersetzt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Python wird typischerweise interpretiert."
  },
  {
    id: "q10_i_059",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist objektorientierte Programmierung (OOP)?",
    answers: ["Nur ein Paradigma ganz ohne jede Verwendung von Funktionen", "Ein Paradigma, das Daten und Methoden in Objekten und Klassen organisiert", "Nur eine sehr alte, rein maschinennahe Programmiersprache", "Nur ein Paradigma mit einem ausschließlich streng linearen Programmablauf"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Klassen, Objekte, Vererbung und Kapselung sind zentrale Konzepte."
  },
  {
    id: "q10_i_060",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Klasse?",
    answers: ["Nur ein einzelnes Objekt, das bereits vollständig instanziiert wurde", "Eine Vorlage (Bauplan) für Objekte mit Attributen und Methoden", "Nur ein wiederverwendbarer, benannter Codeabschnitt", "Nur ein einzelner Speicherplatz für genau einen Wert"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Aus Klassen werden Objekte erzeugt (Instanziierung)."
  },
  {
    id: "q10_i_061",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Objekt?",
    answers: ["Nur ein Speicherplatz für einen einzelnen Wert", "Eine konkrete Instanz einer Klasse mit eigenen Werten", "Nur ein wiederverwendbarer, benannter Codeabschnitt", "Nur die feste Vorlage, aus der alle Instanzen erzeugt werden"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Objekte haben Zustand (Attribute) und Verhalten (Methoden)."
  },
  {
    id: "q10_i_062",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Vererbung?",
    answers: ["Das Ableiten neuer Klassen von bestehenden Klassen unter Übernahme von Eigenschaften", "Nur das wörtliche Kopieren von bereits vorhandenem Programmcode ganz ohne jede Anpassung", "Nur das Überschreiben bereits vorhandener Dateien auf der Festplatte", "Nur das dauerhafte Speichern von Klassendaten in einer Datenbank"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Vererbung fördert Wiederverwendung und Hierarchien."
  },
  {
    id: "q10_i_063",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Kapselung?",
    answers: ["Nur das Verstecken von Dateien und Ordnern im Dateisystem des Rechners", "Nur das Komprimieren von Daten zur Verringerung des Speicherbedarfs", "Das Verbergen interner Details einer Klasse und kontrollierter Zugriff über Methoden", "Nur das Verschlüsseln sämtlicher sensibler Klassendaten mit einem geheimen Schlüssel"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Kapselung schützt Datenintegrität."
  },
  {
    id: "q10_i_064",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Polymorphie?",
    answers: ["Die Fähigkeit, dass gleiche Methodenaufrufe unterschiedliche Verhaltensweisen auslösen", "Nur die Kapselung interner Details einer Klasse vor jedem äußeren Zugriff", "Nur die Vererbung von Eigenschaften einer Klasse an abgeleitete Unterklassen", "Nur die reine Abstraktion unwichtiger Implementierungsdetails einer ganz einzelnen Klasse"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Polymorphie ermöglicht flexible und erweiterbare Systeme."
  },
  {
    id: "q10_i_065",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine API?",
    answers: ["Nur eine einzelne Datenbank zur Speicherung sehr großer Datenmengen", "Nur ein einzelnes, komplett in sich geschlossenes Programm", "Nur ein Betriebssystem zur Verwaltung sämtlicher Hardware", "Eine Schnittstelle, über die Programme miteinander kommunizieren"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "API steht für Application Programming Interface."
  },
  {
    id: "q10_i_066",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Versionskontrolle (z. B. Git)?",
    answers: ["Nur ein einfacher Editor zum Schreiben von Programmcode", "Nur ein einfacher Compiler zum Übersetzen von Quellcode in Maschinencode", "Ein System zur Nachverfolgung und Verwaltung von Änderungen am Code", "Nur ein einfacher Debugger zum Auffinden von Fehlern im Code"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Git ermöglicht Zusammenarbeit und Historie."
  },
  {
    id: "q10_i_067",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Repository?",
    answers: ["Nur ein einzelner Server ohne gespeicherte Historie", "Nur ein ganz gewöhnlicher Ordner ohne jede Versionsverwaltung", "Nur eine einzelne Datei ohne gespeicherte Historie", "Ein Speicherort für den Code und dessen Versionshistorie"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Git-Repositories können lokal oder remote sein."
  },
  {
    id: "q10_i_068",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Open Source?",
    answers: ["Software, deren Quellcode öffentlich zugänglich und veränderbar ist", "Nur Software, die ausschließlich über eine externe Cloud läuft", "Nur Software, die grundsätzlich immer kostenlos angeboten wird", "Nur Software, deren kompletter Quellcode stets geheim gehalten wird"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Open Source fördert Transparenz und Zusammenarbeit."
  },
  {
    id: "q10_i_069",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Bug?",
    answers: ["Nur eine harmlose Warnmeldung des Compilers", "Ein Fehler im Programmcode oder Verhalten", "Nur eine gewünschte Funktion des Programms", "Nur ein erklärender Kommentar im Quellcode"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bugs werden durch Debugging behoben."
  },
  {
    id: "q10_i_070",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Testen in der Softwareentwicklung?",
    answers: ["Nur das einmalige Übersetzen von Quellcode in ausführbaren Maschinencode", "Das systematische Prüfen, ob ein Programm die Anforderungen erfüllt", "Nur das Veröffentlichen einer bereits fertigen Software", "Nur das erstmalige Schreiben von neuem Programmcode"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Tests erhöhen die Softwarequalität."
  },
  {
    id: "q10_i_071",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Modul?",
    answers: ["Nur ein Speicherplatz für einen einzelnen Wert", "Nur eine einzelne Datei ohne jeden festen Inhalt", "Nur eine einfache Schleife, die mehrfach durchlaufen wird", "Ein eigenständiger, wiederverwendbarer Programmteil"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Module fördern Struktur und Wiederverwendung."
  },
  {
    id: "q10_i_072",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die IDE?",
    answers: ["Eine integrierte Entwicklungsumgebung mit Editor, Compiler und Debugger", "Nur ein einfacher Browser zum Anzeigen und Öffnen von Webseiten", "Nur ein komplettes Betriebssystem zur Verwaltung der gesamten Computerhardware", "Nur ein einfacher Texteditor ohne Compiler und Debugger"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: VS Code, PyCharm, Eclipse."
  },
  {
    id: "q10_i_073",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Scratch?",
    answers: ["Eine visuelle Programmiersprache für Einsteiger mit Bausteinen", "Nur eine textbasierte Programmiersprache für Profis", "Nur eine Datenbank zur Speicherung von Lernfortschritten", "Nur ein spezielles Betriebssystem für Schulcomputer im Unterricht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Scratch wird oft in der Schule eingesetzt."
  },
  {
    id: "q10_i_074",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Python?",
    answers: ["Nur ein Betriebssystem für Server und Desktops", "Nur ein Browser zum Anzeigen von Webseiten", "Nur eine Datenbank zur Speicherung großer Datenmengen", "Eine weit verbreitete, lesbare Programmiersprache"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Python eignet sich gut für Anfänger und Datenanalyse."
  },
  {
    id: "q10_i_075",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist JavaScript?",
    answers: ["Eine Programmiersprache, die vor allem im Web eingesetzt wird", "Nur eine Sprache zur ausschließlich reinen Abfrage von Datenbanken", "Nur ein einfaches Textformat zum Austausch von Daten", "Nur ein spezielles Betriebssystem für mobile Geräte"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "JavaScript läuft in Browsern und auf Servern (Node.js)."
  },

  // ================================================================
  // 3. INFORMATIKSYSTEME & HARDWARE (30 Fragen)
  // ================================================================
  {
    id: "q10_i_076",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die Von-Neumann-Architektur?",
    answers: ["Ein Rechnermodell mit gemeinsamer Speicher für Programm und Daten", "Nur ein Modell zur Beschreibung von Datenbankstrukturen", "Nur ein Modell zur Beschreibung von Netzwerktopologien", "Nur ein reines Paradigma zur klaren Strukturierung von Programmcode"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die meisten heutigen Computer folgen diesem Prinzip."
  },
  {
    id: "q10_i_077",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die CPU?",
    answers: ["Nur die Grafikkarte zur Darstellung von Bildern und Videos", "Die zentrale Verarbeitungseinheit, das „Gehirn“ des Computers", "Nur die interne Festplatte zur dauerhaften Datenspeicherung von Dateien", "Nur der Arbeitsspeicher für kurzfristig genutzte Daten"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "CPU steht für Central Processing Unit."
  },
  {
    id: "q10_i_078",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist RAM?",
    answers: ["Der flüchtige Arbeitsspeicher des Computers", "Nur der dauerhafte Festspeicher des Computers", "Nur der zentrale Prozessor des Computers", "Nur die Grafikkarte zur Bilddarstellung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "RAM verliert Daten beim Ausschalten."
  },
  {
    id: "q10_i_079",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Festspeicher (SSD/HDD)?",
    answers: ["Ein nicht-flüchtiger Speicher für dauerhafte Daten", "Nur der kleine, sehr schnelle Zwischenspeicher", "Nur der flüchtige Arbeitsspeicher des Computers", "Nur der zentrale Prozessor eines gewöhnlichen Computers"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "SSDs sind schneller als klassische Festplatten."
  },
  {
    id: "q10_i_080",
    category: "k10_informatik",
 topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Betriebssystem?",
    answers: ["Nur ein einzelner Treiber für ein bestimmtes Gerät", "Die Software, die Hardware verwaltet und Programme ausführt", "Nur ein ganz gewöhnliches, einzelnes Anwendungsprogramm dafür", "Nur ein Browser zum Anzeigen von Webseiten im Internet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Windows, macOS, Linux, Android."
  },
  {
    id: "q10_i_081",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Treiber?",
    answers: ["Software, die die Kommunikation zwischen Betriebssystem und Hardware ermöglicht", "Nur ein Browser, der Webseiten für den Nutzer anzeigt und darstellt", "Nur ein gewöhnliches Anwendungsprogramm ohne Zugriff auf Hardware", "Nur eine gefährliche Schadsoftware, die gezielt Systeme angreift und beschädigt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ohne Treiber funktioniert Hardware oft nicht korrekt."
  },
  {
    id: "q10_i_082",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Netzwerk?",
    answers: ["Eine Verbindung mehrerer Computer zum Datenaustausch", "Nur ein einzelner, nicht verbundener Computer", "Nur eine einzelne, lokal gespeicherte Datei", "Nur ein einzelnes, komplett isoliert laufendes Programm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Netzwerke können lokal (LAN) oder global (Internet) sein."
  },
  {
    id: "q10_i_083",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das Internet?",
    answers: ["Nur die Gesamtheit sozialer Medien im Web", "Ein weltweites Netzwerk von Netzwerken", "Nur das World Wide Web mit seinen Webseiten", "Nur der weltweite Dienst zum Versenden von E-Mails"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das WWW ist nur ein Dienst des Internets."
  },
  {
    id: "q10_i_084",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das World Wide Web (WWW)?",
    answers: ["Nur ein Dienst zum Versenden und Empfangen von E-Mails", "Ein System von miteinander verknüpften Hypertext-Dokumenten im Internet", "Nur ein einzelnes Programm zum Anzeigen von Webseiten", "Nur ein weiterer, ganz gebräuchlicher Name für das gesamte weltweite Internet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das WWW basiert auf HTTP und HTML."
  },
  {
    id: "q10_i_085",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Browser?",
    answers: ["Ein Programm zum Anzeigen und Navigieren von Webseiten", "Nur ein Editor zum Schreiben von Programmcode", "Nur ein Server, der Webseiten bereitstellt", "Nur ein eigenständiges Betriebssystem für Desktop-Computer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Chrome, Firefox, Safari, Edge."
  },
  {
    id: "q10_i_086",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist HTML?",
    answers: ["Eine Auszeichnungssprache zur Strukturierung von Webseiten", "Nur eine reine Programmiersprache für die Serverlogik", "Nur ein Format zur Speicherung von Datenbankinhalten", "Nur ein einfaches Stylesheet zur farblichen Gestaltung von Text"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "HTML steht für HyperText Markup Language."
  },
  {
    id: "q10_i_087",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist CSS?",
    answers: ["Eine Sprache zur Gestaltung und Formatierung von Webseiten", "Nur eine Programmiersprache für Serverlogik", "Nur eine Auszeichnungssprache zur Strukturierung von Inhalten", "Nur ein Format zur Speicherung von Datenbankinhalten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "CSS steht für Cascading Style Sheets."
  },
  {
    id: "q10_i_088",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Server?",
    answers: ["Ein Computer oder Programm, das Dienste für andere Computer bereitstellt", "Nur ein einfacher Browser, der Webseiten beim Nutzer anzeigt und darstellt", "Nur ein Router, der Datenpakete zwischen Netzwerken weiterleitet", "Nur ein Client, der Dienste von einem Server anfordert"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Webserver liefern Webseiten aus."
  },
  {
    id: "q10_i_089",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Client?",
    answers: ["Nur ein Server, der Dienste für andere Computer bereitstellt", "Ein Computer oder Programm, das Dienste von einem Server anfordert", "Nur ein einfacher Switch, der Daten innerhalb eines lokalen Netzes verteilt", "Nur ein Router, der Datenpakete zwischen Netzwerken weiterleitet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Browser sind typische Clients."
  },
  {
    id: "q10_i_090",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist IP-Adresse?",
    answers: ["Eine eindeutige Adresse eines Geräts im Netzwerk", "Nur ein für Menschen lesbarer Domainname", "Nur die Nummer eines geöffneten Verbindungsports", "Nur ein zum Geräteschutz vergebenes Passwort"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "IPv4 und IPv6 sind die gängigen Versionen."
  },
  {
    id: "q10_i_091",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist DNS?",
    answers: ["Ein System, das Domainnamen in IP-Adressen übersetzt", "Nur ein Protokoll zur reinen Datenübertragung", "Nur ein Browser zum Anzeigen von Webseiten", "Nur ein Server, der ausschließlich E-Mails versendet"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "DNS macht das Internet benutzerfreundlich."
  },
  {
    id: "q10_i_092",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist HTTP / HTTPS?",
    answers: ["Nur ein Dateiformat für gespeicherte Webseiten", "Nur eine Programmiersprache für Serverlogik", "Protokolle zur Übertragung von Webseiten", "Nur ein Browser zum Anzeigen von Webseiten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "HTTPS schützt die Verbindung durch Verschlüsselung."
  },
  {
    id: "q10_i_093",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Router?",
    answers: ["Nur ein Server, der Dienste für andere bereitstellt", "Nur ein Modem, das Signale in Daten umwandelt", "Nur ein einfacher Switch, der Daten im lokalen Netz verteilt", "Ein Gerät, das Datenpakete zwischen Netzwerken weiterleitet"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Router verbinden z. B. Heimnetz und Internet."
  },
  {
    id: "q10_i_094",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Switch?",
    answers: ["Nur ein Router, der Netzwerke miteinander verbindet", "Nur ein einfaches Modem, das Signale in Daten umwandelt", "Nur ein einfacher Server, der nur Dienste für andere bereitstellt", "Ein Gerät, das Daten innerhalb eines lokalen Netzwerks verteilt"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Switches arbeiten auf der Data-Link-Schicht."
  },
  {
    id: "q10_i_095",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Firewall?",
    answers: ["Nur ein einfacher Browser zum Anzeigen von Webseiten", "Ein Sicherheitssystem, das unerwünschten Netzwerkverkehr filtert", "Nur ein einfacher Antivirus, der Dateien nach Schadcode durchsucht", "Nur ein gewöhnlicher Router, der Datenpakete weiterleitet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Firewalls schützen vor unerlaubten Zugriffen."
  },
  {
    id: "q10_i_096",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Cloud Computing?",
    answers: ["Nur ein Betriebssystem für vernetzte Computer", "Nur ein Browser zum Zugriff auf Onlinedienste", "Die Nutzung von IT-Ressourcen über das Internet statt lokal", "Nur die Nutzung ausschließlich lokal installierter Software auf dem Gerät"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Google Drive, AWS, Microsoft Azure."
  },
  {
    id: "q10_i_097",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Algorithmus in Hardware-Kontext (z. B. CPU)?",
    answers: ["Nur die komplette Software, die aktuell auf dem Rechner installiert ist", "Die festgelegte Abfolge von Schritten, die der Prozessor ausführt", "Nur ein bereits fertig kompiliertes und getestetes Programm", "Nur ein spezielles Format zur Speicherung von Dateien"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Auch Hardware folgt algorithmischen Abläufen."
  },
  {
    id: "q10_i_098",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Bus im Computer?",
    answers: ["Nur der zentrale Prozessor des Computers", "Nur ein Netzwerk zwischen mehreren Computern", "Nur der Arbeitsspeicher zur kurzfristigen Datenhaltung", "Ein Kommunikationsweg für Daten zwischen Komponenten"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Es gibt Datenbus, Adressbus und Steuerbus."
  },
  {
    id: "q10_i_099",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Cache?",
    answers: ["Nur der gewöhnliche Arbeitsspeicher eines jeden Computers", "Nur die dauerhafte Festplatte des Computers", "Nur der zentrale Prozessor eines gewöhnlichen Computers", "Ein schneller Zwischenspeicher für häufig genutzte Daten"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Cache beschleunigt den Datenzugriff."
  },
  {
    id: "q10_i_100",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Peripheriegerät?",
    answers: ["Nur die Hauptplatine im Inneren des Computers", "Nur der zentrale Prozessor eines gewöhnlichen Computers", "Ein externes Gerät, das an den Computer angeschlossen wird", "Nur der interne Arbeitsspeicher im Inneren eines jeden Computers"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Tastatur, Maus, Drucker, Monitor."
  },
  {
    id: "q10_i_101",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Mainboard / Motherboard?",
    answers: ["Die Hauptplatine, auf der die zentralen Komponenten verbunden sind", "Nur der zentrale Prozessor eines ganz gewöhnlichen privaten Heimcomputers", "Nur die Grafikkarte zur Darstellung von Bildern und Videos", "Nur der Arbeitsspeicher eines gewöhnlichen Computers"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Mainboard verbindet alle Teile."
  },
  {
    id: "q10_i_102",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Betriebssystem-Kernel?",
    answers: ["Nur eine einzelne, vom Nutzer selbst installierte Anwendung auf dem eigenen Gerät", "Nur ein Browser zum Anzeigen von Webseiten im Internet und Intranet", "Nur ein einzelner Gerätetreiber für ein bestimmtes Peripheriegerät", "Der zentrale Kern des Betriebssystems, der Hardware und Prozesse verwaltet"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Kernel hat besondere Privilegien."
  },
  {
    id: "q10_i_103",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Virtualisierung?",
    answers: ["Nur die Speicherung von Daten in einer externen Cloud", "Nur die Verschlüsselung von Daten mit einem geheimen, sicheren Schlüssel", "Nur die Kompression von Daten zur Verringerung des Speicherbedarfs", "Das Ausführen mehrerer virtueller Systeme auf einer physischen Hardware"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Virtuelle Maschinen teilen sich die Hardware."
  },
  {
    id: "q10_i_104",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein IoT-Gerät?",
    answers: ["Nur ein Server in einem großen Rechenzentrum", "Nur ein gewöhnliches Smartphone mit Mobilfunk", "Ein mit dem Internet verbundenes Alltagsgerät", "Nur ein klassischer Desktop-Computer"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: smarte Lampen, Thermostate, Wearables."
  },
  {
    id: "q10_i_105",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Protokoll in Netzwerken?",
    answers: ["Nur eine eindeutige, feste Adresse eines Geräts im Netzwerk", "Ein Satz von Regeln für die Kommunikation zwischen Geräten", "Nur ein zum Geräteschutz fest vergebenes Passwort", "Nur die feste Nummer eines geöffneten Verbindungsports"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: TCP, IP, HTTP, SMTP."
  },

  // ================================================================
  // 4. KI, DATENSCHUTZ, GESELLSCHAFT (45 Fragen)
  // ================================================================
  {
    id: "q10_i_106",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist künstliche Intelligenz (KI)?",
    answers: ["Nur klassische Datenbanken zur reinen Speicherung großer Datenmengen", "Systeme, die Aufgaben lösen, die normalerweise menschliche Intelligenz erfordern", "Nur mechanische Roboter mit fest programmierten, starren Abläufen", "Nur ganz einfache Algorithmen ganz ohne jegliche Fähigkeit zum eigenständigen Lernen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "KI umfasst Lernen, Planen und Problemlösen."
  },
  {
    id: "q10_i_107",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist maschinelles Lernen?",
    answers: ["Nur klassische Programmierung mit ganz fest vorgegebenen Regeln, Mustern und Formeln", "Verfahren, bei denen Systeme aus Daten lernen, ohne explizit programmiert zu sein", "Nur der ganz rein technische Aufbau klassischer Computernetzwerke", "Nur die Verwaltung klassischer, relationaler Datenbanksysteme"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Maschinelles Lernen ist ein Teilgebiet der KI."
  },
  {
    id: "q10_i_108",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein neuronales Netz?",
    answers: ["Nur ein klassischer Algorithmus ganz ohne jede Fähigkeit zum eigenständigen Lernen", "Nur eine gewöhnliche Datenbank zur Speicherung von Werten", "Ein Modell, das von biologischen Neuronen inspiriert ist und Muster lernt", "Nur ein gewöhnliches Computernetzwerk aus Kabeln und Geräten"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Tiefe neuronale Netze ermöglichen Deep Learning."
  },
  {
    id: "q10_i_109",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Chatbot?",
    answers: ["Nur ein ganz einfacher Suchalgorithmus für Einträge in einer Datenbank", "Nur ein Browser zum Anzeigen von Webseiten im Internet", "Nur ein einfacher Compiler zum Übersetzen von Programmcode", "Ein Programm, das mit Menschen in natürlicher Sprache kommuniziert"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Chatbots nutzen oft KI-Techniken."
  },
  {
    id: "q10_i_110",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Bias in KI-Systemen?",
    answers: ["Systematische Verzerrungen in den Ergebnissen durch unausgewogene Trainingsdaten", "Nur eine sehr langsame Ausführung des Programms auf zu schwacher Hardware im Betrieb", "Nur ein rein technisches Problem der verwendeten Rechenhardware selbst", "Nur ein gewöhnlicher Fehler im geschriebenen Programmcode selbst"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bias kann Diskriminierung verstärken."
  },
  {
    id: "q10_i_111",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Datenschutz?",
    answers: ["Nur die Kompression von Daten zur Platzersparnis", "Der Schutz personenbezogener Daten vor Missbrauch", "Nur die dauerhafte Speicherung von Daten auf Servern", "Nur die Verschlüsselung von Daten mit einem Schlüssel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Datenschutz ist ein Grundrecht."
  },
  {
    id: "q10_i_112",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die DSGVO?",
    answers: ["Nur ein interner Verhaltenskodex einzelner Unternehmen", "Nur ein Gesetz der Vereinigten Staaten von Amerika", "Nur ein rein deutsches, nationales Gesetz", "Die Datenschutz-Grundverordnung der Europäischen Union"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die DSGVO regelt den Umgang mit personenbezogenen Daten."
  },
  {
    id: "q10_i_113",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was sind personenbezogene Daten?",
    answers: ["Daten, die sich auf eine identifizierte oder identifizierbare Person beziehen", "Nur Daten, die ausschließlich große Unternehmen und Organisationen weltweit betreffen", "Nur Daten, die vollständig und uneingeschränkt öffentlich zugänglich sind", "Nur Daten, aus denen keine einzelne Person mehr erkennbar ist"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Name, Adresse, IP-Adresse können personenbezogen sein."
  },
  {
    id: "q10_i_114",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Einwilligung im Datenschutz?",
    answers: ["Nur ein rechtlich fest bindender Vertrag zwischen zwei Vertragsparteien", "Nur ein staatliches Gesetz zum ganz generellen Schutz von Daten", "Nur eine gesetzlich fest vorgeschriebene Pflicht ganz ohne jede freie Wahlmöglichkeit", "Die freiwillige, informierte Zustimmung zur Verarbeitung personenbezogener Daten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Einwilligung muss widerrufbar sein."
  },
  {
    id: "q10_i_115",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Tracking?",
    answers: ["Nur das Verschlüsseln von Daten mit einem Schlüssel", "Das Verfolgen des Nutzerverhaltens im Internet", "Nur das Komprimieren von Daten zur Platzersparnis", "Nur das dauerhafte Speichern von Dateien auf einem Server"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Cookies und Fingerprinting ermöglichen Tracking."
  },
  {
    id: "q10_i_116",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Cookie?",
    answers: ["Nur ein vom Nutzer selbst frei gewähltes, geheimes Zugangspasswort für ein Online-Konto", "Eine kleine Datei, die Websites auf dem Gerät speichern, um Informationen zu behalten", "Nur eine Schadsoftware, die sich selbstständig im Netzwerk verbreitet", "Nur ein gewöhnliches, direkt ausführbares Programm auf der Festplatte"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Cookies können nützlich oder problematisch sein."
  },
  {
    id: "q10_i_117",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Phishing?",
    answers: ["Nur unerwünschte Werbe-E-Mails völlig ohne jede betrügerische Absicht dahinter", "Nur eine gewöhnliche Schadsoftware, die sich selbst verbreitet", "Der Versuch, durch gefälschte Nachrichten an sensible Daten zu gelangen", "Nur gewöhnliche, völlig legale Onlinewerbung ohne Täuschung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Phishing nutzt oft gefälschte E-Mails oder Webseiten."
  },
  {
    id: "q10_i_118",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Virus (Computervirus)?",
    answers: ["Nur eine kleine Datei, die Websites lokal speichern", "Schadsoftware, die sich selbst verbreitet und Schaden anrichtet", "Nur gewöhnliche, völlig legale Onlinewerbung ohne Täuschung", "Nur ein gewöhnlicher Fehler im selbst geschriebenen Programmcode"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Viren benötigen meist ein Wirtsprogramm."
  },
  {
    id: "q10_i_119",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Ransomware?",
    answers: ["Nur Spähsoftware, die heimlich Nutzerdaten ausliest", "Nur ein sich selbst schnell verbreitender Computervirus", "Schadsoftware, die Daten verschlüsselt und Lösegeld fordert", "Nur Werbesoftware, die ständig ungewollt Anzeigen einblendet"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Backups und Vorsicht sind der beste Schutz."
  },
  {
    id: "q10_i_120",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein starkes Passwort?",
    answers: ["Nur das eigene Geburtsdatum als Zahlenfolge", "Nur der eigene Vor- oder Nachname als einfaches Wort", "Nur ein kurzes, leicht zu merkendes Wort", "Ein langes, komplexes und einzigartiges Passwort"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Passwortmanager und Zwei-Faktor-Authentifizierung helfen."
  },
  {
    id: "q10_i_121",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Zwei-Faktor-Authentifizierung (2FA)?",
    answers: ["Nur ein ganz gewöhnliches, einzelnes Passwort ganz ohne weiteren Nachweis", "Nur ein biometrischer Fingerabdruck-Scan ohne weiteren Faktor", "Ein Sicherheitsverfahren mit zwei unabhängigen Nachweisen der Identität", "Nur eine kurze, vierstellige Geheimzahl ohne weiteren Faktor"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "2FA erhöht die Sicherheit erheblich."
  },
  {
    id: "q10_i_122",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Social Engineering?",
    answers: ["Nur das ganz gezielte Hacken rein technischer Systeme über bekannte Sicherheitslücken", "Nur der gezielte Versand gefälschter Phishing-Nachrichten per E-Mail", "Das Ausnutzen menschlicher Schwächen, um an Informationen oder Zugang zu gelangen", "Nur der gezielte Einsatz klassischer, automatisch verbreiteter Schadsoftware"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Menschen sind oft das schwächste Glied."
  },
  {
    id: "q10_i_123",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist digitale Souveränität?",
    answers: ["Die Fähigkeit, digitale Technologien selbstbestimmt und sicher zu nutzen", "Nur der gesetzliche Schutz aller personenbezogener Daten vor jedem Missbrauch", "Nur die Nutzung frei zugänglicher, quelloffener Software", "Nur die Nutzung von Diensten über eine externe, fremde Cloud"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Digitale Souveränität betrifft Individuen und Staaten."
  },
  {
    id: "q10_i_124",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der digitale Fußabdruck?",
    answers: ["Nur die auf dem eigenen Gerät gespeicherten Cookies", "Die Spuren, die man durch digitale Aktivitäten hinterlässt", "Nur die einem Gerät zugewiesenen IP-Adressen", "Nur die für sämtliche Onlinedienste verwendeten Passwörter"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Fußabdruck kann schwer löschbar sein."
  },
  {
    id: "q10_i_125",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Fake News?",
    answers: ["Nur stark übertriebene, klar als solche erkennbare satirische Beiträge ohne Täuschungsabsicht", "Absichtlich falsche oder irreführende Informationen, die als Nachrichten verbreitet werden", "Nur persönliche, subjektive Meinungsäußerungen ohne jeden Wahrheitsanspruch", "Nur gewöhnliche, klar als Werbung gekennzeichnete Anzeigen eines Unternehmens"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Medienkompetenz hilft gegen Fake News."
  },
  {
    id: "q10_i_126",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Deepfake?",
    answers: ["Nur ein normal mit einer echten Kamera gefilmtes Video", "Mit KI erzeugte oder manipulierte Medieninhalte, die real wirken", "Nur ein völlig unbearbeitetes, vollkommen echtes Foto", "Nur ein ganz gewöhnlicher, per Hand geschriebener Text ohne Bearbeitung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Deepfakes können Desinformation verstärken."
  },
  {
    id: "q10_i_127",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Algorithmus-Transparenz?",
    answers: ["Nur die schriftliche Dokumentation des selbst geschriebenen Quellcodes", "Nur die freie Veröffentlichung des Quellcodes im Internet", "Die Nachvollziehbarkeit, wie ein Algorithmus zu Entscheidungen kommt", "Nur die systematische Testung eines fertigen Programms"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Transparenz ist wichtig für Vertrauen und Fairness."
  },
  {
    id: "q10_i_128",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ethische KI?",
    answers: ["Nur KI-Systeme, die ausschließlich ganz rein kommerziell verkauft und stets vermarktet werden", "Nur KI-Systeme mit einem vollständig offen zugänglichen Quellcode für alle", "Nur besonders leistungsstarke, extrem schnell rechnende KI-Systeme", "KI-Systeme, die fair, transparent und menschenzentriert entwickelt und eingesetzt werden"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Ethik in der KI ist ein wachsendes Forschungsfeld."
  },
  {
    id: "q10_i_129",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen starker und schwacher KI?",
    answers: ["Starke KI ist lediglich eine viel schnellere, leistungsstärkere Version schwacher KI", "Starke und schwache KI unterscheiden sich in der Praxis lediglich im Namen", "Schwache KI besitzt schon heute bereits eine vollständige, allgemeine menschenähnliche Intelligenz", "Schwache KI: spezialisiert auf Aufgaben, starke KI: allgemeine Menschenähnliche Intelligenz"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Heutige Systeme sind schwache KI."
  },
  {
    id: "q10_i_130",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen überwachtem und unüberwachtem Lernen?",
    answers: ["Überwachtes Lernen nutzt niemals gelabelte Trainingsdaten", "Unüberwachtes Lernen benötigt immer gelabelte Trainingsdaten", "Beide Verfahren nutzen exakt dieselben Trainingsdaten", "Überwacht: mit gelabelten Daten, unüberwacht: ohne Labels"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind zentrale Lernparadigmen."
  },
  {
    id: "q10_i_131",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Datenschutz und Datensicherheit?",
    answers: ["Datenschutz: Schutz der Person, Datensicherheit: Schutz der Daten vor Verlust/Zugriff", "Datenschutz und Datensicherheit meinen in der praktischen Anwendung technisch genau dasselbe", "Datenschutz bedeutet in jedem Zusammenhang denselben Schutz wie Datensicherheit", "Datensicherheit bedeutet in jedem Zusammenhang denselben Schutz wie Datenschutz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide ergänzen sich."
  },
  {
    id: "q10_i_132",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Anonymisierung und Pseudonymisierung?",
    answers: ["Anonymisierung ist in der Praxis stets mit dem passenden Schlüssel wieder rückführbar", "Pseudonymisierung macht Daten für immer und dauerhaft nicht rückführbar", "Beide Verfahren führen in der Praxis zu exakt demselben Ergebnis", "Anonymisierung: nicht rückführbar, Pseudonymisierung: mit Schlüssel rückführbar"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind Datenschutzmaßnahmen."
  },
  {
    id: "q10_i_133",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Open Source und proprietärer Software?",
    answers: ["Open Source bedeutet in der Praxis stets denselben geschlossenen Quellcode", "Open Source: Quellcode offen, proprietär: geschlossen und lizenziert", "Beide Softwarearten haben denselben Quellcode-Zugang", "Proprietäre Software hat stets einen frei einsehbaren Quellcode"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Modelle haben Vor- und Nachteile."
  },
  {
    id: "q10_i_134",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Client und Server?",
    answers: ["Ein Client stellt stets Dienste für einen Server bereit", "Client fordert an, Server stellt bereit", "Ein Server fordert stets Dienste von einem Client an", "Client und Server erfüllen technisch dieselbe Aufgabe"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Client-Server-Modell ist grundlegend."
  },
  {
    id: "q10_i_135",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen LAN und WAN?",
    answers: ["Ein LAN verbindet stets Geräte über große Entfernungen", "LAN und WAN bezeichnen technisch dasselbe Netzwerk", "LAN: lokal, WAN: über große Entfernungen", "Ein WAN verbindet stets nur Geräte in einem einzigen Raum"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Internet ist ein WAN."
  },
  {
    id: "q10_i_136",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Hardware und Software?",
    answers: ["Hardware: physische Komponenten, Software: Programme und Daten", "Software besteht in der Praxis stets aus greifbaren, physischen Bauteilen", "Hardware besteht stets aus Programmen und gespeicherten Daten", "Hardware und Software bezeichnen im Kern dasselbe Konzept"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind notwendig für funktionierende Systeme."
  },
  {
    id: "q10_i_137",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Frontend und Backend?",
    answers: ["Frontend und Backend erledigen in der Praxis exakt dieselbe Aufgabe", "Frontend: Benutzeroberfläche, Backend: serverseitige Logik und Daten", "Ein Frontend übernimmt in Wirklichkeit stets die serverseitige Datenverarbeitung", "Ein Backend zeigt stets die sichtbare Benutzeroberfläche an"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Webanwendungen trennen oft beide Schichten."
  },
  {
    id: "q10_i_138",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen synchroner und asynchroner Kommunikation?",
    answers: ["Synchrone Kommunikation läuft stets zeitversetzt ab", "Synchron: gleichzeitig, asynchron: zeitversetzt", "Asynchrone Kommunikation läuft stets gleichzeitig ab", "Beide Kommunikationsarten laufen technisch identisch ab"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "E-Mail ist asynchron, Chat oft synchron."
  },
  {
    id: "q10_i_139",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen zentraler und dezentraler Architektur?",
    answers: ["Zentrale und dezentrale Architekturen sind technisch identisch", "Eine zentrale Architektur verteilt Verantwortung auf viele Stellen", "Zentral: eine zentrale Instanz, dezentral: verteilte Verantwortung", "Eine dezentrale Architektur nutzt stets eine einzige zentrale Instanz"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Blockchain ist ein Beispiel für dezentral."
  },
  {
    id: "q10_i_140",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Authentifizierung und Autorisierung?",
    answers: ["Authentifizierung bedeutet in der Praxis stets dasselbe wie Autorisierung", "Autorisierung bedeutet stets dasselbe wie Authentifizierung", "Beide Begriffe beschreiben exakt denselben Sicherheitsschritt", "Authentifizierung: Identität prüfen, Autorisierung: Rechte prüfen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind Sicherheitsmechanismen."
  },
  {
    id: "q10_i_141",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Verschlüsselung und Hashing?",
    answers: ["Verschlüsselung ist in der Praxis grundsätzlich niemals umkehrbar", "Verschlüsselung und Hashing sind technisch identisch", "Verschlüsselung: umkehrbar, Hashing: praktisch nicht umkehrbar", "Hashing lässt sich stets mit dem passenden Schlüssel umkehren"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Passwörter werden gehasht, nicht verschlüsselt gespeichert."
  },
  {
    id: "q10_i_142",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen privater und öffentlicher Cloud?",
    answers: ["Private und öffentliche Cloud nutzen in der Praxis stets dieselbe Infrastruktur", "Eine öffentliche Cloud nutzt stets nur eigene Infrastruktur", "Privat: eigene Infrastruktur, öffentlich: geteilte Dienste eines Anbieters", "Eine private Cloud nutzt stets geteilte Dienste eines Anbieters"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Hybride Modelle kombinieren beide."
  },
  {
    id: "q10_i_143",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Edge Computing und Cloud Computing?",
    answers: ["Cloud Computing verarbeitet Daten stets direkt am Gerät", "Edge: Verarbeitung nah am Gerät, Cloud: zentral in Rechenzentren", "Edge und Cloud Computing verarbeiten Daten am selben Ort", "Edge Computing verarbeitet Daten stets in zentralen Rechenzentren"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Edge reduziert Latenz und Bandbreitenbedarf."
  },
  {
    id: "q10_i_144",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Supervised und Reinforcement Learning?",
    answers: ["Reinforcement Learning benötigt in der Praxis stets gelabelte Trainingsdaten", "Beide Lernverfahren funktionieren stets nach demselben Prinzip", "Supervised: mit Labels, Reinforcement: Lernen durch Belohnung und Bestrafung", "Supervised Learning lernt stets durch Belohnung und Bestrafung"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Reinforcement Learning wird z. B. bei Spielen und Robotik genutzt."
  },
  {
    id: "q10_i_145",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Black-Box und erklärbarer KI?",
    answers: ["Black-Box: undurchsichtig, erklärbar: nachvollziehbare Entscheidungen", "Eine Black-Box liefert in der Praxis stets nachvollziehbare Entscheidungen", "Erklärbare KI liefert stets undurchsichtige Entscheidungen", "Beide Ansätze liefern gleich nachvollziehbare Entscheidungen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Erklärbarkeit ist wichtig für Vertrauen und Recht."
  },
  {
    id: "q10_i_146",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Datensparsamkeit und Datenmaximierung?",
    answers: ["Beide Prinzipien fordern in der praktischen Anwendung exakt dieselbe Datenmenge", "Datensparsamkeit fordert in jedem Fall möglichst viele Daten", "Datenmaximierung fordert in jedem Fall möglichst wenige Daten", "Datensparsamkeit: nur notwendige Daten, Maximierung: möglichst viele Daten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Datensparsamkeit ist ein DSGVO-Prinzip."
  },
  {
    id: "q10_i_147",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen IT-Sicherheit und Cybersicherheit?",
    answers: ["Cybersicherheit betont den Schutz vernetzter Systeme und des digitalen Raums", "Beide Begriffe bezeichnen in der Praxis exakt denselben Schutzbereich", "Cybersicherheit ist in der Praxis stets nur ein Teilbereich der IT-Sicherheit", "IT-Sicherheit betont stets ausschließlich vernetzte Systeme"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Begriffe überschneiden sich stark."
  },
  {
    id: "q10_i_148",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen digitaler Kompetenz und Medienkompetenz?",
    answers: ["Digitale Kompetenz bedeutet in jedem denkbaren Zusammenhang genau dasselbe wie Medienkompetenz", "Digitale Kompetenz: technische Fähigkeiten, Medienkompetenz: kritisches Nutzen von Medien", "Beide Kompetenzen beschreiben in der Praxis exakt dieselbe Fähigkeit", "Medienkompetenz bedeutet stets nur rein technisches Fachwissen ohne Bewertung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind eng verwandt und ergänzen sich."
  },
  {
    id: "q10_i_149",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen ethischer und rechtlicher Verantwortung in der Informatik?",
    answers: ["Rechtliche Verantwortung bedeutet in der Praxis stets dasselbe wie ethische", "Ethisch: moralische Prinzipien, rechtlich: gesetzliche Vorschriften", "Beide Verantwortungsarten beruhen auf denselben Regeln", "Ethische Verantwortung bedeutet stets dasselbe wie rechtliche"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Ebenen sind für Entwickler und Nutzer relevant."
  },
  {
    id: "q10_i_150",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die zentrale Aufgabe der Informatik in der Gesellschaft?",
    answers: ["Digitale Systeme verantwortungsvoll zu gestalten und kritisch zu hinterfragen", "Nur ausschließlich neue Hardwarekomponenten für Computer zu entwickeln und zu bauen", "Nur neue Computerprogramme möglichst schnell zu schreiben und zu verkaufen", "Nur möglichst viele Daten über Nutzer zu sammeln und auszuwerten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Informatikbildung fördert Mündigkeit in der digitalen Welt."
  },
  {"id":"k10in101","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Algorithmus = …","answers":["Zufall","Vorschrift","nur Code","Hardware"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Vorschrift."},
  {"id":"k10in102","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Bit = …","answers":["Byte","0/1","KB","Netz"],"correct":1,"difficulty":"mittel","points":10,"explanation":"0/1."},
  {"id":"k10in103","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Schleife wiederholt …","answers":["nie","Anweisungen","Daten","Hardware"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Code."},
  {"id":"k10in104","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"1010₂ = ?","answers":["8","10","12","5"],"correct":1,"difficulty":"mittel","points":10,"explanation":"10."},
  {"id":"k10in105","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"TCP/IP ist …","answers":["HTTP","Protokollfamilie","USB","BT"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Netz."},
  {"id":"k10in106","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Verschlüsselung schützt …","answers":["Öffentlichkeit","Vertraulichkeit","Speed","Staub"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Geheimnis."},
  {"id":"k10in107","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"SQL SELECT …","answers":["löscht","fragt ab","Hardware","verschlüsselt"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Abfrage."},
  {"id":"k10in108","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Klasse OOP = …","answers":["Instanz","Bauplan","Variable","Schleife"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Bauplan."},
  {"id":"k10in109","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Rekursion: ruft …","answers":["andere Sprache","sich selbst","Schleife","Hardware"],"correct":1,"difficulty":"mittel","points":10,"explanation":"sich."},
  {"id":"k10in110","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Bug = …","answers":["Feature","Fehler","Hardware","Protokoll"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Fehler."},
  {"id":"k10in111","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Usability = …","answers":["Server","Benutzerfreundlichkeit","Strom","Kabel"],"correct":1,"difficulty":"mittel","points":10,"explanation":"UX."},
  {"id":"k10in112","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"ML braucht …","answers":["keine Daten","Trainingsdaten","starre Regeln","Zufall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Daten."},
  {"id":"k10in113","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Privacy by Design = …","answers":["nachrüsten","von Anfang","ignorieren","AGB"],"correct":1,"difficulty":"mittel","points":10,"explanation":"eingebaut."},
  {"id":"k10in114","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Phishing will …","answers":["Hardware","Zugangsdaten","Werbung","Backup"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Betrug."},
  {"id":"k10in115","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Array Index oft ab …","answers":["1","0","−1","Zufall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"0."},
  {"id":"k10in116","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Boolean = …","answers":["Zahl","true/false","String","Bild"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Wahrheit."},
  {"id":"k10in117","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Latenz = …","answers":["Bandbreite","Verzögerung","Speicher","CPU"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Delay."},
  {"id":"k10in118","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Backup gegen …","answers":["Mode","Datenverlust","Kabel","CPU"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Schutz."},
  {"id":"k10in119","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"HTML strukturiert …","answers":["Logik","Webinhalt","Index","CPU"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Markup."},
  {"id":"k10in120","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"CSS gestaltet …","answers":["Logik","Darstellung","DB","TCP"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Style."},
  {"id":"k10in121","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"JS oft für …","answers":["CSS only","Interaktivität","SQL","Compiler"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Dynamik."},
  {"id":"k10in122","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"JPEG oft …","answers":["verlustfrei","verlustbehaftet","Text","ZIP"],"correct":1,"difficulty":"mittel","points":10,"explanation":"verlustbehaftet."},
  {"id":"k10in123","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"O(n) wächst …","answers":["konstant","linear","quadratisch","log"],"correct":1,"difficulty":"mittel","points":10,"explanation":"linear."},
  {"id":"k10in124","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Hash oft …","answers":["umkehrbar","Einweg","sinnlos","Bild"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Fingerprint."},
  {"id":"k10in125","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Open Source: Code …","answers":["geheim","einsehbar","unbenutzbar","Verkauf only"],"correct":1,"difficulty":"mittel","points":10,"explanation":"offen."},
  {"id":"k10in126","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Compiler → oft …","answers":["Bilder","Maschinencode","Pakete","SQL"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Übersetzung."},
  {"id":"k10in127","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Prozess hat …","answers":["Bit","Kontext","Kabel","CSS"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Prozess."},
  {"id":"k10in128","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"HTTP 404 = …","answers":["OK","nicht gefunden","500","Redirect"],"correct":1,"difficulty":"mittel","points":10,"explanation":"404."},
  {"id":"k10in129","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Variable speichert …","answers":["Konstante","Wert","Funktion","Hardware"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Wert."},
  {"id":"k10in130","category":"k10_informatik","area":"schule","grade":10,"subject":"informatik","topic":"erweiterung","question":"Ethik fragt nach …","answers":["Speed","Folgen","Syntax","Zufall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Verantwortung."}
];
