const K10_MATHEMATIK_QUESTIONS = [
  // ================================================================
  // 1. REELLE ZAHLEN, WURZELN & POTENZEN (15 Fragen)
  // ================================================================
  {
    id: "q10_m_001",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Menge enthält alle rationalen und irrationalen Zahlen?",
    answers: ["Die Menge der rationalen Zahlen", "Die Menge der natürlichen Zahlen", "Die Menge der reellen Zahlen", "Die Menge der ganzen Zahlen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die reellen Zahlen umfassen alle rationalen und irrationalen Zahlen."
  },
  {
    id: "q10_m_002",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Quadratwurzel aus 144?",
    answers: ["12", "16", "10", "14"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "12 multipliziert mit 12 ergibt 144."
  },
  {
    id: "q10_m_003",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Aussage gilt für die Quadratwurzel aus einer negativen Zahl?",
    answers: ["Sie ist stets eine negative reelle Zahl ohne Ausnahme", "Sie ist gleich dem doppelten Betrag der ursprünglichen Zahl", "Sie ist immer eine ganze positive Zahl, egal welcher Radikand", "Sie ist im Bereich der reellen Zahlen nicht definiert"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Im Reellen gibt es keine Quadratwurzel aus negativen Zahlen."
  },
  {
    id: "q10_m_004",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet das Wurzelgesetz für das Produkt unter der Wurzel?",
    answers: ["Wurzel aus a geteilt durch b ist immer 1", "Wurzel aus a minus b gleich Wurzel a minus Wurzel b", "Wurzel aus a mal b gleich Wurzel a mal Wurzel b", "Wurzel aus a plus b gleich Wurzel a plus Wurzel b"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "√(a·b) = √a · √b (für a, b ≥ 0)."
  },
  {
    id: "q10_m_005",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bedeutet a^(1/2)?",
    answers: ["Die Kubikwurzel aus a", "Die Quadratwurzel aus a", "Der doppelte Wert von a", "Die dritte Potenz von a"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Potenz a^(1/2) ist definiert als √a."
  },
  {
    id: "q10_m_006",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie vereinfacht man √(50)?",
    answers: ["25√2", "10√5", "2√25", "5√2"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "√50 = √(25·2) = 5√2."
  },
  {
    id: "q10_m_007",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was gilt für a^0 (a ungleich 0)?",
    answers: ["a^0 ist gleich 1", "a^0 ist nicht definiert", "a^0 ist gleich 0", "a^0 ist gleich a"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Jede von null verschiedene Zahl hoch null ergibt 1."
  },
  {
    id: "q10_m_008",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie rechnet man (a^m) · (a^n)?",
    answers: ["a^(m+n)", "a^(m/n)", "a^(m-n)", "a^(m·n)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei gleicher Basis werden die Exponenten addiert."
  },
  {
    id: "q10_m_009",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist 2^(-3)?",
    answers: ["1/8", "1/6", "-8", "8"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "2^(-3) = 1 / 2^3 = 1/8."
  },
  {
    id: "q10_m_010",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Zahl ist irrational?",
    answers: ["√9", "4/5", "0,75", "√2"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "√2 lässt sich nicht als Bruch ganzer Zahlen darstellen."
  },
  {
    id: "q10_m_011",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet die Zehnerpotenzschreibweise von 0,00034?",
    answers: ["3,4 · 10^(-4)", "0,34 · 10^(-3)", "3,4 · 10^4", "34 · 10^(-3)"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "0,00034 = 3,4 · 10^(-4)."
  },
  {
    id: "q10_m_012",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ergibt √(16/25)?",
    answers: ["16/25", "5/4", "8/5", "4/5"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "√(16/25) = √16 / √25 = 4/5."
  },
  {
    id: "q10_m_013",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie vereinfacht man (√a)^2 für a ≥ 0?",
    answers: ["2a", "√a", "a^2", "a"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Quadrieren hebt die Quadratwurzel auf."
  },
  {
    id: "q10_m_014",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist der Wert von 8^(2/3)?",
    answers: ["4", "2", "64", "16"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "8^(2/3) = (8^(1/3))^2 = 2^2 = 4."
  },
  {
    id: "q10_m_015",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Aussage ist richtig für reelle Zahlen a und b?",
    answers: ["√(a+b) = √a + √b gilt für alle a,b", "√(a-b) = √a - √b gilt für alle a,b", "√(a·b) = √a · √b (bei a, b ≥ 0)", "√a · √b = √(a+b) ist immer gültig"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Produktgesetz gilt unter der Wurzel, die Summe nicht."
  },

  // ================================================================
  // 2. QUADRATISCHE FUNKTIONEN (25 Fragen)
  // ================================================================
  {
    id: "q10_m_016",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet die Normalform einer quadratischen Funktion?",
    answers: ["f(x) = a(x-d)² + e", "f(x) = mx + n (linear)", "f(x) = a/x + b (gebrochen)", "f(x) = ax² + bx + c"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Normalform ist f(x) = ax² + bx + c mit a ≠ 0."
  },
  {
    id: "q10_m_017",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist der Scheitelpunkt der Parabel f(x) = (x-3)² + 2?",
    answers: ["(3|−2)", "(3|2)", "(2|3)", "(−3|2)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "In der Scheitelpunktform f(x) = a(x-d)² + e ist S(d|e)."
  },
  {
    id: "q10_m_018",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wann öffnet sich eine Parabel nach oben?",
    answers: ["Wenn der Leitkoeffizient a positiv ist", "Wenn der Parameter c negativ ist", "Wenn der Koeffizient b positiv ist", "Wenn der Leitkoeffizient a negativ ist"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei a > 0 öffnet die Parabel nach oben, bei a < 0 nach unten."
  },
  {
    id: "q10_m_019",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Nullstellen einer quadratischen Gleichung ax² + bx + c = 0?",
    answers: ["Nur mit der linearen Ausgleichsformel lösbar", "Nur durch systematisches Probieren der Werte", "Nur durch Division beider Seiten durch x", "Mit der p-q-Formel oder Mitternachtsformel"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Mitternachtsformel bzw. p-q-Formel liefert die Lösungen."
  },
  {
    id: "q10_m_020",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was gibt die Diskriminante D = b² − 4ac an?",
    answers: ["Die Steigung der Tangente im Scheitel", "Die Koordinaten des Scheitelpunkts", "Die Anzahl und Art der Nullstellen", "Den Wert des y-Achsenabschnitts"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "D > 0: zwei Nullstellen, D = 0: eine, D < 0: keine reellen."
  },
  {
    id: "q10_m_021",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet der y-Achsenabschnitt von f(x) = 2x² − 3x + 5?",
    answers: ["2", "5", "−3", "0"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der y-Achsenabschnitt ist f(0) = c = 5."
  },
  {
    id: "q10_m_022",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Form heißt Scheitelpunktform?",
    answers: ["f(x) = a(x − n)(x − m)", "f(x) = mx + t", "f(x) = a(x − d)² + e", "f(x) = ax² + bx + c"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Scheitelpunktform zeigt den Scheitel (d|e) direkt."
  },
  {
    id: "q10_m_023",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bewirkt eine positive Verschiebung von d in f(x) = a(x − d)² + e?",
    answers: ["Verschiebung der Parabel nach rechts", "Streckung der Parabel in y-Richtung", "Verschiebung der Parabel nach links", "Spiegelung der Parabel an der x-Achse"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "x − d verschiebt den Graphen um d Einheiten nach rechts."
  },
  {
    id: "q10_m_024",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet die faktorisierte Form einer quadratischen Funktion mit Nullstellen n und m?",
    answers: ["f(x) = ax² + bx + c + d", "f(x) = a(x − d)² + e + f", "f(x) = a/x + bx + c + d", "f(x) = a(x − n)(x − m)"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Aus den Nullstellen ergibt sich die faktorisierte Darstellung."
  },
  {
    id: "q10_m_025",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was passiert mit der Parabel, wenn |a| größer wird?",
    answers: ["Sie wird enger", "Sie verschiebt sich nach oben", "Sie wird breiter", "Sie verschwindet"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Größeres |a| macht die Parabel steiler und enger."
  },
  {
    id: "q10_m_026",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie findet man den Scheitel bei f(x) = ax² + bx + c?",
    answers: ["x_S = b/a, dann y_S = f(0)", "x_S = −b/(2a), dann y_S = f(x_S)", "y_S = c, unabhängig von a und b", "Nur durch systematisches Ausprobieren"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Scheitel-x-Koordinate ergibt sich aus −b/(2a)."
  },
  {
    id: "q10_m_027",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Gleichung hat die Lösungen x = 2 und x = −3?",
    answers: ["(x + 2)(x + 3) = 0", "(x − 2)(x − 3) = 0", "(x − 2)(x + 3) = 0", "(x + 2)(x − 3) = 0"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Nullstellen sind die Werte, die die Faktoren null machen."
  },
  {
    id: "q10_m_028",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist der Wertebereich von f(x) = x² + 1?",
    answers: ["Nur positive Zahlen", "Alle y ≥ 1", "Alle y ≤ 1", "Alle reellen Zahlen"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Parabel hat den Tiefpunkt bei y = 1 und öffnet nach oben."
  },
  {
    id: "q10_m_029",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie löst man x² − 5x + 6 = 0 mit der p-q-Formel?",
    answers: ["x = 0 und x = 5", "x = −2 und x = −3", "x = 2 und x = 3", "x = 1 und x = 6"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "p = −5, q = 6 → x = 2,5 ± √(6,25 − 6) = 2,5 ± 0,5."
  },
  {
    id: "q10_m_030",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bewirkt die Multiplikation mit −1 bei einer Parabel?",
    answers: ["Verschiebung nach rechts oben", "Spiegelung an der x-Achse", "Streckung entlang der y-Achse", "Verschiebung nach oben hin"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "f(x) → −f(x) spiegelt den Graphen an der x-Achse."
  },
  {
    id: "q10_m_031",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Parabel hat den Scheitel im Ursprung und öffnet nach unten?",
    answers: ["f(x) = x² + 1", "f(x) = x²", "f(x) = −x²", "f(x) = (x − 1)²"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "−x² hat Scheitel (0|0) und öffnet nach unten."
  },
  {
    id: "q10_m_032",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie viele Nullstellen kann eine quadratische Funktion maximal haben?",
    answers: ["Keine", "Drei", "Unendlich viele", "Zwei"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Parabel schneidet die x-Achse höchstens zweimal."
  },
  {
    id: "q10_m_033",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Achsensymmetrie der Normalparabel?",
    answers: ["Symmetrie zur y-Achse", "Symmetrie zur x-Achse", "Punktsymmetrie zum Ursprung", "Keine Symmetrie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "f(x) = x² ist achsensymmetrisch zur y-Achse."
  },
  {
    id: "q10_m_034",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie erhält man aus der Normalform die Scheitelpunktform?",
    answers: ["Durch Ableiten der Funktion", "Durch einfache Division", "Durch quadratische Ergänzung", "Durch Logarithmieren beider Seiten"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Quadratische Ergänzung überführt ax² + bx + c in a(x − d)² + e."
  },
  {
    id: "q10_m_035",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bedeutet es, wenn die Diskriminante null ist?",
    answers: ["Keine reelle Nullstelle vorhanden", "Genau eine (doppelte) Nullstelle", "Zwei verschiedene reelle Nullstellen", "Unendlich viele mögliche Nullstellen"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "D = 0 bedeutet, dass die Parabel die x-Achse in genau einem Punkt berührt."
  },
  {
    id: "q10_m_036",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Funktion beschreibt eine nach oben geöffnete Parabel mit Scheitel (1|−2)?",
    answers: ["f(x) = (x − 1)² + 2", "f(x) = −(x − 1)² − 2", "f(x) = (x + 1)² − 2", "f(x) = (x − 1)² − 2"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "a > 0 und Scheitel (1|−2) führen zu (x − 1)² − 2."
  },
  {
    id: "q10_m_037",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist der Definitionsbereich einer quadratischen Funktion?",
    answers: ["Nur negative Zahlen", "Nur positive Zahlen", "Nur natürliche Zahlen", "Alle reellen Zahlen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Quadratische Funktionen sind für alle reellen x definiert."
  },
  {
    id: "q10_m_038",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet die Mitternachtsformel?",
    answers: ["x = (−b ± √(b² − 4ac)) / (2a)", "x = (−b ± √(b² + 4ac)) / (2a)", "x = (b ± √(b² − 4ac)) / (2a)", "x = (−b ± √(b² − 4ac)) / a"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die bekannte Lösungsformel für ax² + bx + c = 0."
  },
  {
    id: "q10_m_039",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was beschreibt der Parameter e in der Scheitelpunktform?",
    answers: ["Die y-Koordinate des Scheitels", "Die Öffnungsweite", "Die x-Koordinate des Scheitels", "Den y-Achsenabschnitt immer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In a(x − d)² + e ist e die Höhe des Scheitels."
  },
  {
    id: "q10_m_040",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Transformation verschiebt die Parabel um 4 Einheiten nach oben?",
    answers: ["Subtraktion von 4 vom x-Wert", "Addition von 4 zum Funktionsterm", "Multiplikation des Terms mit 4", "Division des Funktionswerts durch 4"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "f(x) + 4 verschiebt den Graphen parallel nach oben."
  },

  // ================================================================
  // 3. TRIGONOMETRIE (25 Fragen)
  // ================================================================
  {
    id: "q10_m_041",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie ist der Sinus eines Winkels im rechtwinkligen Dreieck definiert?",
    answers: ["Gegenkathete geteilt durch Ankathete", "Hypotenuse geteilt durch Gegenkathete", "Gegenkathete geteilt durch Hypotenuse", "Ankathete geteilt durch Hypotenuse"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "sin(α) = Gegenkathete / Hypotenuse."
  },
  {
    id: "q10_m_042",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie ist der Kosinus eines Winkels im rechtwinkligen Dreieck definiert?",
    answers: ["Gegenkathete geteilt durch Ankathete", "Ankathete geteilt durch Hypotenuse", "Gegenkathete geteilt durch Hypotenuse", "Hypotenuse geteilt durch Ankathete"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "cos(α) = Ankathete / Hypotenuse."
  },
  {
    id: "q10_m_043",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie ist der Tangens eines Winkels im rechtwinkligen Dreieck definiert?",
    answers: ["Gegenkathete geteilt durch Ankathete", "Gegenkathete geteilt durch Hypotenuse", "Ankathete geteilt durch Gegenkathete", "Ankathete geteilt durch Hypotenuse"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "tan(α) = Gegenkathete / Ankathete."
  },
  {
    id: "q10_m_044",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welcher Satz gilt im rechtwinkligen Dreieck für die Seiten?",
    answers: ["Satz des Thales: a · b = c immer", "Kathetensatz: a² − b² = c² stets", "Satz des Pythagoras: a² + b² = c²", "Höhensatz: a + b = c für alle Dreiecke"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Satz des Pythagoras verbindet die Katheten mit der Hypotenuse."
  },
  {
    id: "q10_m_045",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was besagt der Sinussatz?",
    answers: ["a + sin(α) = b + sin(β) immer", "a/cos(α) = b/cos(β) = c/cos(γ)", "a/sin(α) = b/sin(β) = c/sin(γ)", "a · sin(α) = b · sin(β) = c"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Sinussatz setzt Seiten und gegenüberliegende Winkel in Beziehung."
  },
  {
    id: "q10_m_046",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was besagt der Kosinussatz?",
    answers: ["c² = a² + b² − 2ab·cos(γ)", "c = a + b − cos(γ)", "c² = a² + b² + 2ab·cos(γ)", "c² = a² − b² · cos(γ)"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Kosinussatz verallgemeinert den Pythagoras für beliebige Dreiecke."
  },
  {
    id: "q10_m_047",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welchen Wert hat sin(90°)?",
    answers: ["0,5", "0", "√2/2", "1"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Einheitskreis bzw. rechtwinkligen Dreieck ist sin(90°) = 1."
  },
  {
    id: "q10_m_048",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welchen Wert hat cos(0°)?",
    answers: ["0,5", "1", "0", "−1"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "cos(0°) = 1."
  },
  {
    id: "q10_m_049",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Periode der Sinusfunktion?",
    answers: ["180° bzw. π rad", "90° bzw. π/2", "720° bzw. 4π", "360° bzw. 2π"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Sinusfunktion wiederholt sich alle 360° bzw. 2π."
  },
  {
    id: "q10_m_050",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welchen Wertebereich hat die Sinusfunktion?",
    answers: ["Von 0 bis 1", "Von −1 bis 1", "Alle reellen Zahlen", "Von −∞ bis ∞"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "sin(x) liegt immer zwischen −1 und 1."
  },
  {
    id: "q10_m_051",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bewirkt der Parameter a in f(x) = a·sin(x)?",
    answers: ["Verschiebung in x-Richtung", "Änderung der Periode", "Änderung der Amplitude", "Verschiebung in y-Richtung"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "a streckt oder staucht die Funktion in y-Richtung (Amplitude)."
  },
  {
    id: "q10_m_052",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bewirkt der Parameter b in f(x) = sin(b·x)?",
    answers: ["Änderung der Periode", "Änderung der Amplitude", "Nur Verschiebung nach oben", "Keine Auswirkung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "b verändert die Periodenlänge: T = 2π / |b|."
  },
  {
    id: "q10_m_053",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie lautet die Beziehung zwischen Sinus und Kosinus?",
    answers: ["sin²(x) − cos²(x) = 0", "sin(x) · cos(x) = 1/2", "sin²(x) + cos²(x) = 1", "sin(x) + cos(x) = √2"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Die trigonometrische Pythagoras-Identität."
  },
  {
    id: "q10_m_054",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist sin(30°)?",
    answers: ["0,5", "0", "√3/2", "1"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "sin(30°) = 1/2."
  },
  {
    id: "q10_m_055",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist cos(60°)?",
    answers: ["0,5", "0", "√3/2", "1"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "cos(60°) = 1/2."
  },
  {
    id: "q10_m_056",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "In welchem Quadranten ist der Sinus positiv und der Kosinus negativ?",
    answers: ["Im vierten Quadranten", "Im dritten Quadranten", "Im ersten Quadranten", "Im zweiten Quadranten"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Im II. Quadranten ist y positiv (Sinus) und x negativ (Kosinus)."
  },
  {
    id: "q10_m_057",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Hypotenuse in einem rechtwinkligen Dreieck?",
    answers: ["Die kürzeste Seite im gesamten rechtwinkligen Dreieck", "Die längste Seite, dem rechten Winkel gegenüber", "Eine der beiden Katheten direkt am rechten Winkel", "Eine beliebige Seite des Dreiecks, egal welche Länge"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Hypotenuse liegt dem 90°-Winkel gegenüber."
  },
  {
    id: "q10_m_058",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wann verwendet man den Sinussatz?",
    answers: ["Wenn man Seiten und gegenüberliegende Winkel kennt", "Nur bei gleichseitigen und gleichschenkligen Dreiecken", "Nur bei reinen Flächenberechnungen im Dreieck", "Nur bei ausschließlich rechtwinkligen Dreiecken"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Sinussatz eignet sich bei gegebenen Winkeln und gegenüberliegenden Seiten."
  },
  {
    id: "q10_m_059",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist tan(45°)?",
    answers: ["0", "0,5", "√3", "1"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "tan(45°) = 1, weil Gegen- und Ankathete gleich lang sind."
  },
  {
    id: "q10_m_060",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie hängt der Tangens mit Sinus und Kosinus zusammen?",
    answers: ["tan(x) = cos(x) / sin(x)", "tan(x) = sin(x) · cos(x)", "tan(x) = sin(x) + cos(x)", "tan(x) = sin(x) / cos(x)"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Definition tan(x) = sin(x)/cos(x)."
  },
  {
    id: "q10_m_061",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bewirkt eine Phasenverschiebung bei der Sinusfunktion?",
    answers: ["Verschiebung des Graphen in x-Richtung", "Änderung der Periodenlänge der Sinusfunktion", "Spiegelung des gesamten Graphen an der y-Achse", "Änderung der Amplitude statt der Lage"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Term (x − c) oder (bx + c) verschiebt den Graphen horizontal."
  },
  {
    id: "q10_m_062",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welchen Wert hat sin(0°)?",
    answers: ["0", "−1", "0,5", "1"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "sin(0°) = 0."
  },
  {
    id: "q10_m_063",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Amplitude der Funktion f(x) = 3·sin(2x)?",
    answers: ["1", "2", "6", "3"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Faktor vor dem Sinus gibt die Amplitude an."
  },
  {
    id: "q10_m_064",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Periode von f(x) = sin(2x)?",
    answers: ["360° bzw. 2π", "180° bzw. π", "90°", "720°"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Periode T = 2π / |b| = 2π / 2 = π."
  },
  {
    id: "q10_m_065",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wann ist der Kosinussatz besonders nützlich?",
    answers: ["Nur bei gleichseitigen und rechtwinkligen Dreiecken überhaupt", "Nur zur reinen Flächenberechnung im beliebigen Dreieck", "Wenn zwei Seiten und der eingeschlossene Winkel gegeben sind", "Nur bei ausschließlich rechtwinkligen Dreiecken mit Winkel"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Kosinussatz eignet sich für SAS-Konstellationen."
  },

  // ================================================================
  // 4. GEOMETRIE: KREIS & KÖRPER (15 Fragen)
  // ================================================================
  {
    id: "q10_m_066",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man den Umfang eines Kreises?",
    answers: ["U = πr² bzw. r²π", "U = 2r bzw. r + r", "U = 2πr bzw. πd", "U = r² bzw. πr"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Kreisumfang ist 2πr oder π mal Durchmesser."
  },
  {
    id: "q10_m_067",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man den Flächeninhalt eines Kreises?",
    answers: ["A = πd", "A = πr²", "A = r²", "A = 2πr"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Kreisfläche ist π mal Radius zum Quadrat."
  },
  {
    id: "q10_m_068",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist ein Kreissektor?",
    answers: ["Ein 'Tortenstück' des Kreises", "Ein einbeschriebenes Rechteck", "Der komplette Kreis als Ganzes", "Nur die Länge des Kreisumfangs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Sektor wird von zwei Radien und dem Bogen begrenzt."
  },
  {
    id: "q10_m_069",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man das Volumen eines Zylinders?",
    answers: ["V = r²h", "V = 2πrh", "V = πr²h", "V = πr h"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Grundfläche mal Höhe: πr² · h."
  },
  {
    id: "q10_m_070",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Oberfläche eines Zylinders (geschlossen)?",
    answers: ["O = πr² + 2πrh + r", "O = 2πrh + πr² − r", "O = πr²h + r² − h", "O = 2πr² + 2πrh"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Zwei Grundflächen plus Mantelfläche."
  },
  {
    id: "q10_m_071",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist ein Prisma?",
    answers: ["Körper mit zwei parallelen kongruenten Grundflächen und Rechtecken als Seiten", "Körper mit einer kreisförmigen Grundfläche und einer einzigen Spitze ganz oben", "Körper mit zwei parallelen kreisförmigen Grundflächen und gebogenem Mantel", "Körper, dessen Oberfläche überall gleich weit vom Mittelpunkt entfernt ist"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Prismen haben parallele, deckungsgleiche Grundflächen."
  },
  {
    id: "q10_m_072",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man das Volumen eines Prismas?",
    answers: ["V = Diagonale mal Höhe", "V = Oberfläche mal Höhe", "V = Umfang mal Höhe", "V = Grundfläche · Höhe"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Volumen = Grundflächeninhalt mal Höhe."
  },
  {
    id: "q10_m_073",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist eine Tangente an einen Kreis?",
    answers: ["Eine Gerade, die den Kreis in genau zwei Punkten schneidet", "Eine Strecke durch den Mittelpunkt des gesamten Kreises", "Eine Strecke vom Mittelpunkt bis zum äußeren Kreisrand", "Eine Gerade, die den Kreis in genau einem Punkt berührt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Tangente steht senkrecht auf dem Radius im Berührpunkt."
  },
  {
    id: "q10_m_074",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Länge eines Kreisbogens?",
    answers: ["b = πr² · α / 360°", "b = (α/360°) · 2πr", "b = α · r / 360°", "b = 2πr / α · 360°"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Bogen ist der entsprechende Anteil des Umfangs."
  },
  {
    id: "q10_m_075",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist der Radius eines Kreises mit Durchmesser 10 cm?",
    answers: ["5 cm", "10 cm", "20 cm", "2,5 cm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Radius ist der halbe Durchmesser."
  },
  {
    id: "q10_m_076",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie groß ist der Flächeninhalt eines Kreises mit Radius 3 cm (π ≈ 3,14)?",
    answers: ["Etwa 9,42 cm²", "Etwa 6 cm²", "Etwa 18,84 cm²", "Etwa 28,26 cm²"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "A = π · 9 ≈ 3,14 · 9 = 28,26."
  },
  {
    id: "q10_m_077",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Mantelfläche eines Zylinders?",
    answers: ["Nur die kreisförmige Grundfläche ganz unten", "Die seitliche Fläche ohne Deckel und Boden", "Die gesamte Oberfläche inklusive Deckel und Boden", "Nur der obere Deckel des gesamten Zylinders"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Mantelfläche = Umfang der Grundfläche mal Höhe = 2πrh."
  },
  {
    id: "q10_m_078",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welcher Körper hat als Grundfläche ein Vieleck und parallele Seitenkanten?",
    answers: ["Pyramide", "Kugel", "Kegel", "Prisma"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Prismen haben parallele, kongruente Grundflächen und parallele Seitenkanten."
  },
  {
    id: "q10_m_079",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie hängt der Mittelpunktswinkel mit dem Kreisbogen zusammen?",
    answers: ["Der Bogen ist unabhängig vom Radius des Kreises", "Der Bogen ist umgekehrt proportional zum Winkel", "Es gibt keinen Zusammenhang zwischen Bogen und Winkel", "Der Bogen ist proportional zum Mittelpunktswinkel"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Je größer der Mittelpunktswinkel, desto länger der zugehörige Bogen."
  },
  {
    id: "q10_m_080",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist π näherungsweise?",
    answers: ["1,41421…", "3,14159…", "2,71828…", "1,61803…"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "π ist das Verhältnis von Umfang zu Durchmesser eines Kreises."
  },

  // ================================================================
  // 5. STOCHASTIK & WAHRSCHEINLICHKEIT (20 Fragen)
  // ================================================================
  {
    id: "q10_m_081",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die relative Häufigkeit eines Ereignisses?",
    answers: ["Anzahl der günstigen Fälle geteilt durch Gesamtzahl der Versuche", "Differenz der günstigen und ungünstigen Fälle im gesamten Versuch", "Nur die absolute Anzahl der günstigen Fälle im Versuch insgesamt", "Die theoretische Wahrscheinlichkeit direkt in Prozent umgerechnet"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Relative Häufigkeit = absolute Häufigkeit / Anzahl der Versuche."
  },
  {
    id: "q10_m_082",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was besagt das Gesetz der großen Zahlen?",
    answers: ["Die absolute Häufigkeit bleibt bei jedem einzelnen Versuch konstant", "Nur bei sehr wenigen Versuchen gilt dieses statistische Gesetz", "Die Wahrscheinlichkeiten ändern sich bei jedem einzelnen Versuch", "Die relative Häufigkeit nähert sich der Wahrscheinlichkeit"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei vielen Wiederholungen stabilisiert sich die relative Häufigkeit."
  },
  {
    id: "q10_m_083",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Wahrscheinlichkeit bei einem Laplace-Experiment?",
    answers: ["Differenz aus günstigen und allen möglichen Ergebnissen zusammengerechnet", "Anzahl günstiger Ergebnisse geteilt durch Anzahl möglicher Ergebnisse", "Nur die Anzahl der günstigen Ergebnisse ohne jede weitere Rechnung", "Produkt aus günstigen und möglichen Ergebnissen jeweils berechnet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "P(E) = |E| / |Ω| bei gleichwahrscheinlichen Ausgängen."
  },
  {
    id: "q10_m_084",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Wahrscheinlichkeit, mit einem fairen Würfel eine 6 zu würfeln?",
    answers: ["1/2", "1", "1/3", "1/6"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein günstiges von sechs möglichen Ergebnissen."
  },
  {
    id: "q10_m_085",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was sind komplementäre Ereignisse?",
    answers: ["Ereignisse, die vollständig und in jeder Hinsicht voneinander unabhängig sind", "Ereignisse, die sich gegenseitig ausschließen und zusammen alles abdecken", "Ereignisse mit exakt gleicher Wahrscheinlichkeit im gesamten Versuch", "Ereignisse, die immer gleichzeitig und ausschließlich gemeinsam eintreten"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "P(E) + P(nicht E) = 1."
  },
  {
    id: "q10_m_086",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Wahrscheinlichkeit des Gegenereignisses?",
    answers: ["1 minus die Wahrscheinlichkeit des Ereignisses", "Das Doppelte der Wahrscheinlichkeit des Ereignisses", "Die gleiche Wahrscheinlichkeit wie das Ereignis", "Die Hälfte der Wahrscheinlichkeit des Ereignisses"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "P(nicht E) = 1 − P(E)."
  },
  {
    id: "q10_m_087",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bedeutet 'stochastisch unabhängig'?",
    answers: ["Die Ereignisse schließen sich gegenseitig vollständig aus", "Das Eintreten des einen beeinflusst das andere nicht", "Die Ereignisse treten stets gemeinsam und gleichzeitig auf", "Die Ereignisse besitzen stets dieselbe Wahrscheinlichkeit"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei Unabhängigkeit gilt P(A und B) = P(A) · P(B)."
  },
  {
    id: "q10_m_088",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie groß ist die Wahrscheinlichkeit, bei zweimaligem Münzwurf zweimal Kopf zu erhalten?",
    answers: ["1", "1/2", "1/3", "1/4"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Unabhängige Ereignisse: (1/2) · (1/2) = 1/4."
  },
  {
    id: "q10_m_089",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist ein Baumdiagramm?",
    answers: ["Eine mathematische Funktionsvorschrift mit mehreren Variablen", "Nur eine tabellarische Übersicht sämtlicher Werte im Versuch", "Ein Kreisdiagramm zur reinen Häufigkeitsdarstellung von Daten", "Grafische Darstellung mehrstufiger Zufallsexperimente"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Baumdiagramme zeigen Wege und Wahrscheinlichkeiten mehrstufiger Versuche."
  },
  {
    id: "q10_m_090",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Wahrscheinlichkeit eines Pfades im Baumdiagramm?",
    answers: ["Addition der Wahrscheinlichkeiten aller Pfade im Diagramm zusammen", "Subtraktion der Wahrscheinlichkeiten entlang des gesamten Pfades", "Division der Wahrscheinlichkeiten entlang des gesamten Pfades", "Multiplikation der Wahrscheinlichkeiten entlang des Pfades"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Entlang eines Pfades werden die Einzelwahrscheinlichkeiten multipliziert."
  },
  {
    id: "q10_m_091",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Summe aller Wahrscheinlichkeiten der Elementarereignisse?",
    answers: ["0", "0,5", "Unendlich", "1"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Wahrscheinlichkeiten aller möglichen Ausgänge ergeben zusammen 1."
  },
  {
    id: "q10_m_092",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was versteht man unter 'Zufallsexperiment'?",
    answers: ["Versuch, der bei jeder Durchführung denselben Ausgang liefert", "Versuch, der ausschließlich mit einer einzigen Münze durchgeführt wird", "Versuch mit ungewissem Ausgang unter gleichen Bedingungen", "Versuch mit von vornherein vollständig bekanntem Ergebnis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Zufallsexperiment ist wiederholbar und hat mehrere mögliche Ergebnisse."
  },
  {
    id: "q10_m_093",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie groß ist die Wahrscheinlichkeit, mit einem fairen Würfel eine gerade Zahl zu würfeln?",
    answers: ["2/3", "1/6", "1/3", "1/2"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Drei gerade Zahlen (2,4,6) von sechs möglichen."
  },
  {
    id: "q10_m_094",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist ein Ereignis in der Stochastik?",
    answers: ["Immer die gesamte Ergebnismenge", "Nur ein einzelnes mögliches Ergebnis", "Eine Teilmenge der Ergebnismenge", "Ein grundsätzlich unmögliches Ereignis"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Ein Ereignis fasst ein oder mehrere Elementarereignisse zusammen."
  },
  {
    id: "q10_m_095",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie berechnet man die Wahrscheinlichkeit der Vereinigung zweier sich ausschließender Ereignisse?",
    answers: ["Addition der Einzelwahrscheinlichkeiten", "Division", "Subtraktion", "Multiplikation der Einzelwahrscheinlichkeiten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei disjunkten Ereignissen gilt P(A ∪ B) = P(A) + P(B)."
  },
  {
    id: "q10_m_096",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was bedeutet 'Laplace-Experiment'?",
    answers: ["Nur ein einziger Münzwurf", "Experiment mit gleichwahrscheinlichen Ausgängen", "Nur Würfeln mit einem gezinkten Spielwürfel", "Experiment mit deutlich ungleichen Wahrscheinlichkeiten"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei Laplace-Experimenten haben alle Elementarereignisse die gleiche Wahrscheinlichkeit."
  },
  {
    id: "q10_m_097",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie groß ist die Wahrscheinlichkeit, beim Ziehen einer Karte aus einem 32er-Blatt ein Ass zu ziehen?",
    answers: ["1/4", "8/32 = 1/4", "4/52 = 1/13", "4/32 = 1/8"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Es gibt 4 Asse in 32 Karten."
  },
  {
    id: "q10_m_098",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ist die Ergebnismenge beim einmaligen Würfeln?",
    answers: ["{2, 4, 6, 8, 10, 12}", "{1, 2, 3, 4, 5, 6}", "{Kopf, Zahl, Rand}", "{1, 2, 3, 4, 5}"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Ergebnismenge Ω enthält alle möglichen Augenzahlen."
  },
  {
    id: "q10_m_099",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wie nennt man die Wahrscheinlichkeit, die man vor dem Experiment theoretisch angibt?",
    answers: ["Absolute Häufigkeit direkt aus dem Experiment abgelesen", "Empirische Wahrscheinlichkeit nach vielen Versuchen", "Relative Häufigkeit nach sehr vielen einzelnen Versuchen", "Klassische oder theoretische Wahrscheinlichkeit"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die theoretische Wahrscheinlichkeit ergibt sich aus der Modellannahme."
  },
  {
    id: "q10_m_100",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was ergibt die Summe der Wahrscheinlichkeiten aller Pfade zu einem bestimmten Ereignis im Baumdiagramm?",
    answers: ["Immer den Wert null, unabhängig vom gewählten Pfad", "Immer den Wert eins, unabhängig vom gewählten Pfad", "Die Gesamtwahrscheinlichkeit des Ereignisses", "Nur die reine Anzahl aller möglichen Pfade im Diagramm"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Verschiedene Pfade zum selben Ereignis werden addiert (Pfadregeln)."
  },

  // ================================================================
  // ERWEITERUNG (zusätzliche 50 Fragen)
  // ================================================================
  {
    id: "q10_m_101",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Gleichung ist quadratisch?",
    answers: ["3x − 7 = 0 (linear)", "2x² − 5x + 3 = 0", "x³ + 2x = 0 (kubisch)", "5/x = 2 (gebrochen)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Höchste Potenz ist x²."
  },
  {
    id: "q10_m_102",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Lösungen von x² − 6x + 8 = 0 mit p-q-Formel?",
    answers: ["x = 2 und x = 4", "x = −2 und x = −4", "x = 3 und x = 3", "x = 1 und x = 8"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "p = −6, q = 8 → 3 ± 1."
  },
  {
    id: "q10_m_103",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Scheitelpunktform von f(x) = x² − 4x + 1?",
    answers: ["f(x) = (x − 2)² + 3", "f(x) = (x + 2)² − 3", "f(x) = (x − 4)² − 1", "f(x) = (x − 2)² − 3"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Quadratische Ergänzung ergibt (x − 2)² − 3."
  },
  {
    id: "q10_m_104",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Parabel hat keine reelle Nullstelle?",
    answers: ["f(x) = x² − 1", "f(x) = (x − 2)²", "f(x) = x² + 1", "f(x) = x² − 4"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "x² + 1 liegt immer über der x-Achse."
  },
  {
    id: "q10_m_105",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Scheitel von f(x) = −2(x + 1)² + 5?",
    answers: ["(−1|5)", "(1|−5)", "(1|5)", "(−1|−5)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "S(−1|5)."
  },
  {
    id: "q10_m_106",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Anzahl reeller Lösungen von x² + 4 = 0?",
    answers: ["Eine", "Keine", "Unendlich viele", "Zwei"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "x² = −4 ist reell nicht lösbar."
  },
  {
    id: "q10_m_107",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wirkung von a = −1 in f(x) = a(x − 2)² + 3?",
    answers: ["Parabel öffnet nach oben hin", "Nur eine Verschiebung nach rechts", "Keine sichtbare Änderung der Form", "Parabel öffnet nach unten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Negatives a öffnet nach unten."
  },
  {
    id: "q10_m_108",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Nullstellen von f(x) = (x − 5)(x + 2)?",
    answers: ["x = 5 und x = 2", "x = −5 und x = 2", "x = 5 und x = −2", "x = −5 und x = −2"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Faktoren null setzen."
  },
  {
    id: "q10_m_109",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Normalform von f(x) = 2(x − 1)² + 3?",
    answers: ["f(x) = 2x² − 4x + 5", "f(x) = x² − 4x + 5", "f(x) = 2x² − 4x − 5", "f(x) = 2x² + 4x + 5"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ausmultiplizieren ergibt 2x² − 4x + 5."
  },
  {
    id: "q10_m_110",
    category: "k10_mathe",
    topic: "quadratische_funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "y-Achsenabschnitt von f(x) = −x² + 6x − 8?",
    answers: ["8", "−8", "-2", "6"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "f(0) = −8."
  },
  {
    id: "q10_m_111",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wert von sin(150°)?",
    answers: ["−0,5", "−√3/2", "√3/2", "0,5"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "sin(180° − 30°) = sin(30°) = 0,5."
  },
  {
    id: "q10_m_112",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wert von cos(120°)?",
    answers: ["√3/2", "−0,5", "−√3/2", "0,5"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "cos(180° − 60°) = −0,5."
  },
  {
    id: "q10_m_113",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wo ist der Tangens nicht definiert?",
    answers: ["Bei allen geraden Vielfachen von 180°", "Bei 0° und allen Vielfachen von 360°", "Bei 45° und allen Vielfachen von 45°", "Bei ungeraden Vielfachen von 90°"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Polstellen bei 90°, 270° usw."
  },
  {
    id: "q10_m_114",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Periode von f(x) = cos(3x)?",
    answers: ["90° bzw. π/2", "180° bzw. π", "120° bzw. 2π/3", "270° bzw. 3π/2"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "T = 2π / 3."
  },
  {
    id: "q10_m_115",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Beziehung sin(x) und cos?",
    answers: ["sin(x) = cos(x)", "sin(x) = cos(x + 180°)", "sin(x) = −cos(x)", "sin(x) = cos(90° − x)"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Kofunktionen-Identität."
  },
  {
    id: "q10_m_116",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Amplitude von f(x) = −4 · sin(x) + 1?",
    answers: ["−4", "4", "5", "1"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Amplitude = |−4| = 4."
  },
  {
    id: "q10_m_117",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Winkel α mit sin(α) = 0 in (0°; 360°)?",
    answers: ["45°", "270°", "180°", "90°"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "sin(180°) = 0."
  },
  {
    id: "q10_m_118",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wert von cos(180°)?",
    answers: ["1", "0", "−1", "0,5"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "cos(180°) = −1."
  },
  {
    id: "q10_m_119",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Funktion mit gleicher Periode wie sin(x)?",
    answers: ["sin(2x)", "cos(x)", "sin(x/2)", "tan(x)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide haben Periode 2π."
  },
  {
    id: "q10_m_120",
    category: "k10_mathe",
    topic: "trigonometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "sin(30°) und cos(60°) sind?",
    answers: ["Beide 0,5", "Beide 1", "Beide √3/2", "sin 0,5 und cos √3/2"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide ergeben 1/2."
  },
  {
    id: "q10_m_121",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Fläche eines Kreissektors mit Winkel α?",
    answers: ["α · πr²", "(α/180°) · πr²", "(α/360°) · πr²", "2πr · α"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Anteil der Kreisfläche."
  },
  {
    id: "q10_m_122",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Volumen Zylinder r = 3, h = 5 (π ≈ 3,14)?",
    answers: ["Etwa 94,25", "Etwa 15,7", "Etwa 47,12", "Etwa 141,3"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "π · 9 · 5 ≈ 141,3."
  },
  {
    id: "q10_m_123",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Mantelfläche Zylinder r = 4, h = 10?",
    answers: ["80π", "40π", "16π", "100π"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "2πrh = 80π."
  },
  {
    id: "q10_m_124",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Unterschied Prisma und Zylinder?",
    answers: ["Zylinder hat eckige Grundflächen", "Es gibt überhaupt keinen Unterschied", "Prisma polygonal, Zylinder kreisförmig", "Prisma hat immer eine kreisförmige Grundfläche"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Grundflächenform unterscheidet sie."
  },
  {
    id: "q10_m_125",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Oberfläche geschlossener Zylinder?",
    answers: ["πr²h + πr", "2πrh + r²", "2πr² + 2πrh", "πr² + πrh + r"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Zwei Kreise plus Mantel."
  },
  {
    id: "q10_m_126",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Fläche Kreis mit Durchmesser 8 cm?",
    answers: ["4π cm²", "8π cm²", "64π cm²", "16π cm²"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "r = 4 → 16π."
  },
  {
    id: "q10_m_127",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Bogenlänge r = 6, α = 60°?",
    answers: ["6π", "π", "3π", "2π"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "(60/360)·2π·6 = 2π."
  },
  {
    id: "q10_m_128",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Radius und Tangente im Berührpunkt?",
    answers: ["Sind gleich lang", "Stehen senkrecht", "Bilden 45°", "Sind parallel"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Radius ⊥ Tangente."
  },
  {
    id: "q10_m_129",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Volumen eines Quaders?",
    answers: ["Länge · Breite · Höhe", "2 · (a + b + c) · h", "a² · b² · c² zusammen", "a + b + c, alles addiert"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Produkt der Kanten."
  },
  {
    id: "q10_m_130",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Oberfläche Würfel Kantenlänge a?",
    answers: ["6a²", "a³", "4a²", "2a³"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sechs Quadrate."
  },
  {
    id: "q10_m_131",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "P(Summe 7) bei zwei fairen Würfeln?",
    answers: ["6/36 = 1/6", "8/36 = 2/9", "12/36 = 1/3", "3/36 = 1/12"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Sechs günstige Paare."
  },
  {
    id: "q10_m_132",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "P(erst rot, dann blau) aus 5 roten, 3 blauen ohne Zurücklegen?",
    answers: ["5/8 · 5/7 = 25/56", "5/8 · 3/8 = 15/64", "5/8 · 3/7 = 15/56", "3/8 · 3/7 = 9/56"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Nach dem ersten Zug ändern sich die Anzahlen."
  },
  {
    id: "q10_m_133",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Bedeutung 'mit Zurücklegen'?",
    answers: ["Reihenfolge der Ziehung spielt dabei keine Rolle", "Es wird insgesamt nur ein einziges Mal gezogen", "Kugel bleibt draußen, Wahrscheinlichkeiten ändern sich", "Kugel zurück, Wahrscheinlichkeiten bleiben gleich"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Unabhängige Ziehungen."
  },
  {
    id: "q10_m_134",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "P(mindestens einmal Kopf) bei dreimal Münzwurf?",
    answers: ["1/8", "7/8", "3/8", "1/2"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "1 − P(kein Kopf) = 1 − 1/8 = 7/8."
  },
  {
    id: "q10_m_135",
    category: "k10_mathe",
    topic: "stochastik",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Erwartungswert fairer Würfel?",
    answers: ["6,0", "4,5", "3,5", "5,0"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "(1+…+6)/6 = 3,5."
  },
  {
    id: "q10_m_136",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "√(9/16) = ?",
    answers: ["3/8", "3/4", "9/4", "9/16"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "√9 / √16 = 3/4."
  },
  {
    id: "q10_m_137",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Vereinfache √72",
    answers: ["12√2", "8√2", "9√2", "6√2"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "√(36·2) = 6√2."
  },
  {
    id: "q10_m_138",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "16^(3/4) = ?",
    answers: ["12", "64", "4", "8"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "(16^(1/4))^3 = 2^3 = 8."
  },
  {
    id: "q10_m_139",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "0,000056 in wissenschaftlicher Schreibweise?",
    answers: ["5,6 · 10^(−5)", "0,56 · 10^(−4)", "5,6 · 10^5", "56 · 10^(−6)"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "5,6 · 10^(−5)."
  },
  {
    id: "q10_m_140",
    category: "k10_mathe",
    topic: "reelle_zahlen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "(3²)³ = ?",
    answers: ["27", "729", "243", "81"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3^6 = 729."
  },
  {
    id: "q10_m_141",
    category: "k10_mathe",
    topic: "gleichungssysteme",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Verfahren für lineare Systeme mit zwei Variablen?",
    answers: ["Nur die quadratische Ergänzungsmethode für alle Systeme", "Nur die p-q-Formel für quadratische Gleichungen anwendbar", "Nur die Mitternachtsformel zur Bestimmung von Nullstellen", "Einsetzungs-, Additions- oder Gleichsetzungsverfahren"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die drei klassischen Verfahren."
  },
  {
    id: "q10_m_142",
    category: "k10_mathe",
    topic: "gleichungssysteme",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Parallele verschiedene Geraden bedeuten?",
    answers: ["Genau eine Lösung", "Unendlich viele Lösungen", "Die Geraden schneiden sich", "Keine Lösung des Systems"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Kein Schnittpunkt."
  },
  {
    id: "q10_m_143",
    category: "k10_mathe",
    topic: "prozent",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "15 % von 80?",
    answers: ["8", "15", "20", "12"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "0,15 · 80 = 12."
  },
  {
    id: "q10_m_144",
    category: "k10_mathe",
    topic: "prozent",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "50 € steigen um 20 %. Neuer Preis?",
    answers: ["60 €", "70 €", "55 €", "40 €"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "50 · 1,2 = 60."
  },
  {
    id: "q10_m_145",
    category: "k10_mathe",
    topic: "prozent",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Nach 10 % Rabatt 45 €. Originalpreis?",
    answers: ["50 €", "40,5 €", "55 €", "49,5 €"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "45 / 0,9 = 50."
  },
  {
    id: "q10_m_146",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Was besagt der Strahlensatz?",
    answers: ["Nur Flächenverhältnisse werden dabei grundsätzlich betrachtet", "Nur Winkelgrößen bleiben dabei stets vollständig erhalten", "Nur der Satz des Pythagoras ist dabei ausschließlich gültig", "Verhältnisse von Abschnitten an Strahlen sind gleich"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Proportionale Abschnitte."
  },
  {
    id: "q10_m_147",
    category: "k10_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Wann sind Dreiecke ähnlich?",
    answers: ["Nur wenn sie vollständig deckungsgleich sind", "Nur wenn alle Seiten gleich lang sind", "Wenn sie in den Winkeln übereinstimmen", "Nur wenn sie exakt die gleiche Fläche haben"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Gleiche Winkel ⇒ ähnlich."
  },
  {
    id: "q10_m_148",
    category: "k10_mathe",
    topic: "funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Definitionsbereich von f(x) = 1/(x − 2)?",
    answers: ["Nur x größer als 2", "Alle reellen Zahlen ohne Einschränkung", "Alle reellen Zahlen außer 2", "Nur x kleiner als 2"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Nenner darf nicht null sein."
  },
  {
    id: "q10_m_149",
    category: "k10_mathe",
    topic: "funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "Welche Funktion wächst exponentiell?",
    answers: ["f(x) = x² + 2", "f(x) = 2x + 1", "f(x) = 2^x", "f(x) = √(x+2)"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Variable im Exponenten."
  },
  {
    id: "q10_m_150",
    category: "k10_mathe",
    topic: "funktionen",
    area: "schule",
    grade: 10,
    subject: "mathematik",
    question: "y-Achsenabschnitt von f(x) = 3^x?",
    answers: ["1", "0", "3", "Unendlich"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "3^0 = 1."
  },
  {"id":"k10ma101","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Was ist √169?","answers":["12","13","14","15"],"correct":1,"difficulty":"mittel","points":10,"explanation":"13×13=169."},
  {"id":"k10ma102","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Löse: 5x=35","answers":["5","6","7","8"],"correct":2,"difficulty":"mittel","points":10,"explanation":"x=7."},
  {"id":"k10ma103","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"2³·2²=?","answers":["2⁵","2⁶","4⁵","2"],"correct":0,"difficulty":"mittel","points":10,"explanation":"2⁵."},
  {"id":"k10ma104","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"15% von 200?","answers":["20","25","30","35"],"correct":2,"difficulty":"mittel","points":10,"explanation":"30."},
  {"id":"k10ma105","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Steigung (0,0)→(4,8)?","answers":["1","2","3","4"],"correct":1,"difficulty":"mittel","points":10,"explanation":"2."},
  {"id":"k10ma106","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Fläche Rechteck 9×4?","answers":["13","36","26","18"],"correct":1,"difficulty":"mittel","points":10,"explanation":"36."},
  {"id":"k10ma107","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"sin(0°)=?","answers":["0","1","0,5","−1"],"correct":0,"difficulty":"mittel","points":10,"explanation":"0."},
  {"id":"k10ma108","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"log₁₀(100)=?","answers":["1","2","10","100"],"correct":1,"difficulty":"mittel","points":10,"explanation":"2."},
  {"id":"k10ma109","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"x²=36 → x=?","answers":["6","±6","36","−6"],"correct":1,"difficulty":"mittel","points":10,"explanation":"±6."},
  {"id":"k10ma110","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"3-4-5 Dreieck: c=?","answers":["5","6","7","8"],"correct":0,"difficulty":"mittel","points":10,"explanation":"5."},
  {"id":"k10ma111","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"P(Kopf) fair coin?","answers":["0","1/2","1/3","1"],"correct":1,"difficulty":"mittel","points":10,"explanation":"1/2."},
  {"id":"k10ma112","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Mittel 10,20,30?","answers":["15","20","25","60"],"correct":1,"difficulty":"mittel","points":10,"explanation":"20."},
  {"id":"k10ma113","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"1 h = ? s","answers":["60","3600","600","1000"],"correct":1,"difficulty":"mittel","points":10,"explanation":"3600."},
  {"id":"k10ma114","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"2/3 + 1/6=?","answers":["1/2","5/6","1","3/6"],"correct":1,"difficulty":"mittel","points":10,"explanation":"5/6."},
  {"id":"k10ma115","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"a⁴/a²=?","answers":["a²","a⁶","a","2a"],"correct":0,"difficulty":"mittel","points":10,"explanation":"a²."},
  {"id":"k10ma116","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Nullstelle y=x+5?","answers":["0","−5","5","1"],"correct":1,"difficulty":"mittel","points":10,"explanation":"−5."},
  {"id":"k10ma117","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Würfel Volumen a=5?","answers":["25","125","15","100"],"correct":1,"difficulty":"mittel","points":10,"explanation":"125."},
  {"id":"k10ma118","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Median 1,3,100?","answers":["1","3","100","34"],"correct":1,"difficulty":"mittel","points":10,"explanation":"3."},
  {"id":"k10ma119","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"0,5 als Bruch?","answers":["1/5","1/2","2/5","1/4"],"correct":1,"difficulty":"mittel","points":10,"explanation":"1/2."},
  {"id":"k10ma120","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"3a+2a=?","answers":["5a","6a","a⁵","5"],"correct":0,"difficulty":"mittel","points":10,"explanation":"5a."},
  {"id":"k10ma121","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Primzahl?","answers":["27","29","33","35"],"correct":1,"difficulty":"mittel","points":10,"explanation":"29."},
  {"id":"k10ma122","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Runde 2,35 auf Zehntel?","answers":["2,3","2,4","2,35","2"],"correct":1,"difficulty":"mittel","points":10,"explanation":"2,4."},
  {"id":"k10ma123","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"f(x)=x+1, f(10)=?","answers":["9","11","10","12"],"correct":1,"difficulty":"mittel","points":10,"explanation":"11."},
  {"id":"k10ma124","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"x−3>2 →","answers":["x>5","x<5","x>2","x=5"],"correct":0,"difficulty":"mittel","points":10,"explanation":"x>5."},
  {"id":"k10ma125","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Dreisatz 2→6, 5→?","answers":["10","15","12","30"],"correct":1,"difficulty":"mittel","points":10,"explanation":"15."},
  {"id":"k10ma126","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"U Kreis d=10 π≈3?","answers":["30","15","60","10"],"correct":0,"difficulty":"mittel","points":10,"explanation":"≈30."},
  {"id":"k10ma127","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"(−2)×3=?","answers":["−6","6","−5","5"],"correct":0,"difficulty":"mittel","points":10,"explanation":"−6."},
  {"id":"k10ma128","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"Quadrant III: x und y …","answers":["beide +","beide −","x+ y−","x− y+"],"correct":1,"difficulty":"mittel","points":10,"explanation":"beide negativ."},
  {"id":"k10ma129","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"4²=?","answers":["8","16","32","2"],"correct":1,"difficulty":"mittel","points":10,"explanation":"16."},
  {"id":"k10ma130","category":"k10_mathe","area":"schule","grade":10,"subject":"mathe","topic":"erweiterung","question":"5! =?","answers":["25","120","60","20"],"correct":1,"difficulty":"mittel","points":10,"explanation":"120."}
];
