const K10_FRANZOESISCH_QUESTIONS = [
  {
    id: "q10_f_001",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Welches Tempus beschreibt abgeschlossene Handlungen in der Vergangenheit?",
    answers: ["Plus-que-parfait", "Conditionnel présent", "Futur antérieur", "Passé composé"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Passé composé steht für abgeschlossene Handlungen."
  },
  {
    id: "q10_f_002",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Welches Tempus beschreibt andauernde oder wiederholte Handlungen in der Vergangenheit?",
    answers: ["Futur simple", "Imparfait", "Passé composé", "Présent"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Imparfait beschreibt Zustände und Gewohnheiten."
  },
  {
    id: "q10_f_003",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wie bildet man das Passé composé mit „avoir“?",
    answers: ["être im Imparfait + Participe passé", "avoir im Futur + Participe passé", "avoir im Présent + Participe passé", "avoir im Passé composé + Infinitif"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die meisten Verben bilden das Passé composé mit avoir."
  },
  {
    id: "q10_f_004",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Welche Verben bilden das Passé composé mit „être“?",
    answers: ["Verben der Bewegung und reflexive Verben", "Nur unregelmäßige und reflexive Verben", "Nur Verben, die ein direktes Objekt haben", "Alle Verben im Passé composé ohne Ausnahme"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Dr.-Mrs.-Vandertramp-Verben und Reflexiva nehmen être."
  },
  {
    id: "q10_f_005",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist das Participe passé von „faire“?",
    answers: ["fait", "fais", "fai", "faité"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "faire – fait ist unregelmäßig."
  },
  {
    id: "q10_f_006",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist das Participe passé von „prendre“?",
    answers: ["prenu", "prend", "pris", "prendu"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "prendre – pris ist unregelmäßig."
  },
  {
    id: "q10_f_007",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wie lautet die 1. Person Singular von „aller“ im Futur simple?",
    answers: ["j’irai", "je vais", "j’allais", "je suis allé"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "aller hat im Futur den Stamm ir-."
  },
  {
    id: "q10_f_008",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wie lautet die 3. Person Plural von „être“ im Présent?",
    answers: ["ils/elles est", "ils/elles sont", "ils/elles êtes", "ils/elles sommes"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "être: je suis, tu es, il est, nous sommes, vous êtes, ils sont."
  },
  {
    id: "q10_f_009",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Objektpronomen?",
    answers: ["Ein Pronomen, das das Objekt eines Verbs ersetzt", "Ein Pronomen, das das Subjekt eines Satzes ersetzt", "Ein Pronomen, das Besitzverhältnisse ausdrückt", "Ein Pronomen, das auf eine bestimmte Sache hinweist"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Objektpronomen stehen vor dem Verb."
  },
  {
    id: "q10_f_010",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wo steht das Objektpronomen im Passé composé?",
    answers: ["Vor dem Subjekt", "Vor dem Hilfsverb", "Am Satzende", "Nach dem Participe passé"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Je l’ai vu. – Das Pronomen steht vor avoir/être."
  },
  {
    id: "q10_f_011",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein relativer Satz?",
    answers: ["Ein Nebensatz, der durch qui, que, où, dont eingeleitet wird", "Ein Hauptsatz, der durch Konjunktionen wie et, mais verbunden wird", "Ein Nebensatz, der durch quand oder si eingeleitet wird", "Ein Satz, der nur aus Subjekt und Verb ohne Ergänzung besteht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Relativsätze bestimmen Nomen näher."
  },
  {
    id: "q10_f_012",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wann verwendet man „qui“ als Relativpronomen?",
    answers: ["Wenn das Bezugswort ein Ort oder eine Zeitangabe ist", "Wenn das Bezugswort Objekt des Relativsatzes ist", "Nur bei Besitzverhältnissen mit dont", "Wenn das Bezugswort Subjekt des Relativsatzes ist"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "qui = der/die/das (Subjekt)."
  },
  {
    id: "q10_f_013",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wann verwendet man „que“ als Relativpronomen?",
    answers: ["Wenn das Bezugswort Objekt des Relativsatzes ist", "Nur bei Besitzverhältnissen mit dont", "Nur bei Orts- und Zeitangaben mit où", "Wenn das Bezugswort Subjekt des Relativsatzes ist"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "que = den/die/das (Objekt)."
  },
  {
    id: "q10_f_014",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „dont“?",
    answers: ["welcher/welche (als Subjekt)", "welchen/welche (als Objekt)", "wo (für Ort und Zeit)", "von dem/der, dessen/deren"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "dont ersetzt de + Nomen."
  },
  {
    id: "q10_f_015",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Conditionnel présent?",
    answers: ["Eine Form für höfliche Bitten, Wünsche oder irreale Bedingungen", "Eine Form für bereits abgeschlossene Handlungen in der Vergangenheit", "Eine Form für Gewohnheiten und Zustände in der Vergangenheit", "Eine Form für sichere zukünftige Ereignisse und Pläne"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Je voudrais … – Ich hätte gern …"
  },
  {
    id: "q10_f_016",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wie bildet man den Conditionnel présent?",
    answers: ["Infinitiv + Passé-Endungen", "Présentstamm + Futur-Endungen", "Imparfaitstamm + Futur-Endungen", "Futurstamm + Imparfait-Endungen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Je parlerais, tu finirais, il vendrait …"
  },
  {
    id: "q10_f_017",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Subjonctif?",
    answers: ["Ein Modus für Befehle und direkte Aufforderungen", "Ein Tempus für abgeschlossene Handlungen in der Vergangenheit", "Ein Modus für objektive Tatsachen und sichere Fakten", "Ein Modus für Unsicherheit, Wunsch, Notwendigkeit und Emotion"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Nach bestimmten Verben und Ausdrücken steht der Subjonctif."
  },
  {
    id: "q10_f_018",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Nach welchem Ausdruck steht oft der Subjonctif?",
    answers: ["Il faut que …", "Il est certain que …", "Je sais que …", "Il est clair que …"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Il faut que tu viennes – Notwendigkeit."
  },
  {
    id: "q10_f_019",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Adverb?",
    answers: ["Ein Wort, das ein Nomen oder Pronomen ersetzt oder begleitet", "Ein Wort, das Personen, Sachen oder abstrakte Begriffe und Ideen benennt", "Ein Wort, das ein Verb, Adjektiv oder anderes Adverb näher bestimmt", "Ein Wort, das ein Nomen näher beschreibt oder qualifiziert"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Viele Adverbien enden auf -ment."
  },
  {
    id: "q10_f_020",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wie bildet man die meisten Adverbien aus Adjektiven?",
    answers: ["Feminine Form des Adjektivs + -ment", "Maskuline Form des Adjektivs + -ment", "Infinitiv des Verbs + -ment als Endung", "Participe passé des Verbs + -ment"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "rapide → rapidement, heureux → heureusement."
  },
  {
    id: "q10_f_021",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Komparativ von „bon“?",
    answers: ["mieux", "bonner", "meilleur", "plus bon"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "bon – meilleur – le meilleur (unregelmäßig)."
  },
  {
    id: "q10_f_022",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Komparativ von „bien“?",
    answers: ["mieux", "bienner", "plus bien", "meilleur"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "bien – mieux – le mieux."
  },
  {
    id: "q10_f_023",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Demonstrativpronomen?",
    answers: ["Ein Pronomen, das einen Nebensatz einleitet", "Ein Pronomen, das Besitz anzeigt", "Ein Pronomen, das eine Person ersetzt", "Ein Pronomen, das auf etwas hinweist"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "celui-ci = dieser hier."
  },
  {
    id: "q10_f_024",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Possessivpronomen?",
    answers: ["Ein Pronomen, das Besitz anzeigt", "Ein Pronomen, das eine Person ersetzt", "Ein Pronomen, das einen Nebensatz einleitet", "Ein Pronomen, das auf etwas hinweist"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "C’est le mien – Das ist meiner."
  },
  {
    id: "q10_f_025",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Verneinung mit „ne … pas“?",
    answers: ["Eine besonders höfliche Frageform", "Eine Form der Bestätigung einer Aussage", "Eine Form der besonderen Betonung", "Die Standardverneinung im Französischen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Je ne parle pas – Ich spreche nicht."
  },
  {
    id: "q10_f_026",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „ne … jamais“?",
    answers: ["nicht mehr", "niemals", "niemand", "nichts"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Je ne vais jamais au cinéma."
  },
  {
    id: "q10_f_027",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „ne … plus“?",
    answers: ["gar nichts", "nie wieder", "kein einziges Mal", "nicht mehr"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Je n’habite plus ici."
  },
  {
    id: "q10_f_028",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „ne … rien“?",
    answers: ["niemals", "nicht mehr", "niemand", "nichts"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Je ne vois rien."
  },
  {
    id: "q10_f_029",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „ne … personne“?",
    answers: ["niemand", "niemals", "nichts", "nicht mehr"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Je ne connais personne ici."
  },
  {
    id: "q10_f_030",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Imperativ?",
    answers: ["Die Form für zukünftige Handlungen", "Die Form für Wünsche und Unsicherheiten", "Die Befehls- oder Aufforderungsform", "Die Form für höfliche Bitten und Wünsche"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Parle ! Parlez ! – Sprich! Sprecht!"
  },
  {
    id: "q10_f_031",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Wie lautet der Imperativ von „aller“ (du-Form)?",
    answers: ["allons", "allez", "vas", "va"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "va à la maison !"
  },
  {
    id: "q10_f_032",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein indirekter Fragesatz?",
    answers: ["Eine Frage, die direkt und ohne Einleitung gestellt wird", "Eine Frage, die in einen Hauptsatz eingebettet ist", "Ein Satz, der eine Bedingung ausdrückt", "Ein Nebensatz, der ein Nomen näher beschreibt"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Je me demande où il habite."
  },
  {
    id: "q10_f_033",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Übereinstimmung des Participe passé mit avoir?",
    answers: ["Es ändert sich grundsätzlich nur bei bestimmten reflexiven Verben", "Es richtet sich nach dem vorangestellten direkten Objekt", "Es richtet sich immer nach dem Subjekt des Satzes", "Es richtet sich nach dem nachgestellten direkten Objekt"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Les lettres que j’ai écrites – Übereinstimmung mit „les lettres“."
  },
  {
    id: "q10_f_034",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Übereinstimmung des Participe passé mit être?",
    answers: ["Es richtet sich nach dem Subjekt", "Es richtet sich nach dem Objekt", "Es ändert sich nie", "Es richtet sich nach dem Hilfsverb"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Elle est allée – Übereinstimmung mit „elle“."
  },
  {
    id: "q10_f_035",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Gerundium (gérondif)?",
    answers: ["en + Participe présent", "Nur der Subjonctif", "Nur das Participe passé", "Nur der Infinitiv"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "en marchant – während des Gehens."
  },
  {
    id: "q10_f_036",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Infinitif présent?",
    answers: ["Nur das Présent", "Nur das Participe passé", "Nur das Futur", "Die Grundform des Verbs"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Infinitiv ist die Nennform."
  },
  {
    id: "q10_f_037",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Infinitif passé?",
    answers: ["Nur das Passé composé im Indikativ", "avoir/être + Participe passé", "Nur das Plus-que-parfait der Vergangenheit", "Nur der Infinitif présent ohne Hilfsverb"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "après avoir mangé – nachdem ich gegessen hatte."
  },
  {
    id: "q10_f_038",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Bedingungssatz (si-Satz) Typ 1?",
    answers: ["si + Subjonctif, Imperativ (Wunschsatz)", "si + Imparfait, Conditionnel présent (irreale Bedingung)", "si + Présent, Futur/Présent (reale Bedingung)", "si + Plus-que-parfait, Conditionnel passé (Vergangenheit)"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Si tu viens, je serai content."
  },
  {
    id: "q10_f_039",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein Bedingungssatz (si-Satz) Typ 2?",
    answers: ["Nur Imperativ", "si + Présent, Futur", "si + Plus-que-parfait, Conditionnel passé", "si + Imparfait, Conditionnel présent"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Si j’avais de l’argent, j’achèterais une voiture."
  },
  {
    id: "q10_f_040",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Plus-que-parfait?",
    answers: ["Ein Tempus für Gewohnheiten in der Vergangenheit", "Ein Tempus für Vorzeitigkeit in der nahen Zukunft", "Ein Tempus für abgeschlossene Handlungen der Gegenwart", "Ein Tempus für Vorzeitigkeit in der Vergangenheit"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "J’avais déjà mangé quand il est arrivé."
  },
  {
    id: "q10_f_041",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Futur antérieur?",
    answers: ["Ein Tempus für sichere zukünftige Handlungen", "Ein Tempus für höfliche Bitten und Wünsche", "Ein Tempus für Vorzeitigkeit in der Zukunft", "Ein Tempus für abgeschlossene Vergangenheit"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Quand j’aurai fini, je sortirai."
  },
  {
    id: "q10_f_042",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein indirektes Objektpronomen?",
    answers: ["le, la, les (direktes Objekt)", "me, te, se (reflexiv)", "lui, leur (für Personen)", "y, en (Orts-/Mengenangabe)"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Je lui parle – Ich spreche mit ihm/ihr."
  },
  {
    id: "q10_f_043",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet das Pronomen „y“?",
    answers: ["ihm/ihr", "ihn/sie/es", "davon / davon", "dort / daran"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "J’y vais – Ich gehe dorthin."
  },
  {
    id: "q10_f_044",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet das Pronomen „en“?",
    answers: ["dort / an diesem Ort", "davon / davon", "ihm / ihr (indirektes Objekt)", "ihn / sie / es (direktes Objekt)"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "J’en ai trois – Ich habe drei davon."
  },
  {
    id: "q10_f_045",
    category: "k10_franzoesisch",
    topic: "grammatik",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Stellung mehrerer Objektpronomen?",
    answers: ["y – en – lui/leur – le/la/les – me/te/se/nous/vous", "le/la/les – me/te/se – lui/leur – y – en", "me/te/se/nous/vous – le/la/les – lui/leur – y – en", "en – y – lui/leur – le/la/les – me/te/se – nous"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Die Reihenfolge der Pronomen ist festgelegt."
  },
  {
    id: "q10_f_046",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „métier“?",
    answers: ["Nur Hobby", "Beruf / Handwerk", "Nur Studium", "Nur Arbeit im Allgemeinen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Quel est ton métier ? – Was ist dein Beruf?"
  },
  {
    id: "q10_f_047",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „projet de vie“?",
    answers: ["Lebensprojekt / Lebensplan", "Berufsprojekt / Karriereplan", "Urlaubsprojekt / Reiseplan", "Familienprojekt / Wohnplan"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Häufiges Thema in Klasse 10."
  },
  {
    id: "q10_f_048",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „s’engager“?",
    answers: ["sich ausruhen / sich richtig entspannen", "sich engagieren / sich verpflichten", "sich bewerben / sich vorstellen", "sich verabschieden / sich trennen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "s’engager pour une cause – sich für eine Sache einsetzen."
  },
  {
    id: "q10_f_049",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „environnement“?",
    answers: ["Landschaft / Gegend", "Umwelt / Umgebung", "Wetter / Jahreszeit", "Wildnis / Wüste"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "protéger l’environnement – die Umwelt schützen."
  },
  {
    id: "q10_f_050",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „développement durable“?",
    answers: ["Nur Umweltschutz", "Nur Sozialpolitik", "Nur Wirtschaftswachstum", "nachhaltige Entwicklung"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein zentrales Thema der Gegenwart."
  },
  {
    id: "q10_f_051",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „égalité“?",
    answers: ["Freiheit / persönliche Unabhängigkeit", "Gleichheit / Gleichberechtigung", "Brüderlichkeit / Solidarität", "Gerechtigkeit / soziale Fairness"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Liberté, égalité, fraternité – Motto Frankreichs."
  },
  {
    id: "q10_f_052",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „liberté“?",
    answers: ["Nur Brüderlichkeit", "Freiheit", "Nur Demokratie", "Nur Gleichheit"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein zentraler Wert der französischen Republik."
  },
  {
    id: "q10_f_053",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „fraternité“?",
    answers: ["Freundschaft / Kameradschaft", "Freiheit / Unabhängigkeit", "Brüderlichkeit / Solidarität", "Gleichheit / Gerechtigkeit"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Teil des französischen Mottos."
  },
  {
    id: "q10_f_054",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „citoyenneté“?",
    answers: ["Staatsbürgerschaft / Bürgerschaft", "Aufenthaltstitel / fester Wohnsitz", "Reisepass / amtliches Ausweisdokument", "Nationalität / Herkunftsland"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "éducation à la citoyenneté – politische Bildung."
  },
  {
    id: "q10_f_055",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „solidarité“?",
    answers: ["Nur Gemeinschaft", "Solidarität", "Nur Hilfe", "Nur Freundschaft"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein wichtiger gesellschaftlicher Wert."
  },
  {
    id: "q10_f_056",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „identité“?",
    answers: ["Nur Nationalität", "Nur Persönlichkeit", "Nur Kultur", "Identität"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "identité culturelle – kulturelle Identität."
  },
  {
    id: "q10_f_057",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „diversité“?",
    answers: ["Nur Multikulturalismus", "Vielfalt", "Nur Einheit", "Nur Unterschied"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "diversité culturelle – kulturelle Vielfalt."
  },
  {
    id: "q10_f_058",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „intégration“?",
    answers: ["Integration", "Nur Einwanderung", "Nur Assimilation", "Nur Anpassung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein gesellschaftlich relevantes Thema."
  },
  {
    id: "q10_f_059",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „immigration“?",
    answers: ["Nur Tourismus", "Nur Auswanderung", "Einwanderung", "Nur Reise"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein wichtiges Thema in Frankreich und Europa."
  },
  {
    id: "q10_f_060",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „chômage“?",
    answers: ["Altersrente", "Berufsausbildung", "Vollzeitarbeit", "Arbeitslosigkeit"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "le taux de chômage – die Arbeitslosenquote."
  },
  {
    id: "q10_f_061",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „formation“?",
    answers: ["Grundschule / Kindheit", "Ausbildung / Bildung", "Berufsleben / Karriere", "Hochschule / Fachschule"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "formation professionnelle – berufliche Ausbildung."
  },
  {
    id: "q10_f_062",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „études“?",
    answers: ["Abschlussprüfung", "Grundschule / Kindergarten", "Studium / Studien", "Berufsausbildung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "faire des études – studieren."
  },
  {
    id: "q10_f_063",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „avenir“?",
    answers: ["Nur Gegenwart", "Nur Vergangenheit", "Nur Plan", "Zukunft"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "penser à l’avenir – an die Zukunft denken."
  },
  {
    id: "q10_f_064",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „rêve“?",
    answers: ["Nur Ziel", "Traum", "Nur Wunsch", "Nur Plan"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "réaliser ses rêves – seine Träume verwirklichen."
  },
  {
    id: "q10_f_065",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „défi“?",
    answers: ["klare Zielsetzung", "große Schwierigkeit", "Herausforderung", "erster Lösungsansatz"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "relever un défi – eine Herausforderung annehmen."
  },
  {
    id: "q10_f_066",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „réussir“?",
    answers: ["Fleißig lernen / üben", "Etwas versuchen / probieren", "Erfolg haben / gelingen", "Scheitern / durchfallen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "réussir ses examens – die Prüfungen bestehen."
  },
  {
    id: "q10_f_067",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „échouer“?",
    answers: ["scheitern / durchfallen", "Erfolg haben / gelingen", "Fleißig lernen / üben", "Etwas versuchen / probieren"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "échouer à un examen – bei einer Prüfung durchfallen."
  },
  {
    id: "q10_f_068",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „expérience“?",
    answers: ["Ausprobieren / Test", "Erfahrung / Erlebnis", "Laborversuch / Studie", "Allgemeinwissen / Bildung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "expérience professionnelle – Berufserfahrung."
  },
  {
    id: "q10_f_069",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „compétence“?",
    answers: ["Abschlussnote / Zensur", "Kompetenz / Fähigkeit", "Fachwissen / Kenntnisse", "Abschlusszeugnis / Diplom"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "compétences linguistiques – Sprachkompetenzen."
  },
  {
    id: "q10_f_070",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „candidature“?",
    answers: ["Nur Anschreiben", "Nur Lebenslauf", "Nur Vorstellungsgespräch", "Bewerbung"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "envoyer sa candidature – seine Bewerbung schicken."
  },
  {
    id: "q10_f_071",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „curriculum vitae“ (CV)?",
    answers: ["Nur Anschreiben", "Nur Zeugnis", "Lebenslauf", "Nur Bewerbung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der CV ist zentral in der Bewerbung."
  },
  {
    id: "q10_f_072",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „lettre de motivation“?",
    answers: ["Motivationsschreiben / Anschreiben", "Arbeitsvertrag / Anstellung", "Abschlusszeugnis / Note", "Lebenslauf / tabellarische Übersicht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Teil einer vollständigen Bewerbung."
  },
  {
    id: "q10_f_073",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „entretien d’embauche“?",
    answers: ["Vorstellungsgespräch", "kurzer Probearbeitstag", "unterschriebener Vertrag", "Bewerbungsschreiben"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Gespräch mit dem Arbeitgeber."
  },
  {
    id: "q10_f_074",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „salaire“?",
    answers: ["Rente / Pension", "Gehalt / Lohn", "Steuer / Abgabe", "Bonus / Prämie"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "le salaire net – das Nettogehalt."
  },
  {
    id: "q10_f_075",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „contrat de travail“?",
    answers: ["Bewerbungsschreiben", "Abschlusszeugnis", "Arbeitsvertrag", "Kündigungsschreiben"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Vertrag zwischen Arbeitgeber und Arbeitnehmer."
  },
  {
    id: "q10_f_076",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „stage“?",
    answers: ["Nur Studium", "Nur Ausbildung", "Nur Job", "Praktikum"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "faire un stage – ein Praktikum machen."
  },
  {
    id: "q10_f_077",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „bénévole“?",
    answers: ["professionell / hauptberuflich", "bezahlt / entlohnt", "ehrenamtlich / Freiwilliger", "studentisch / akademisch"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "travailler comme bénévole – ehrenamtlich arbeiten."
  },
  {
    id: "q10_f_078",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „association“?",
    answers: ["Schule / Bildungseinrichtung", "Firma / Unternehmen", "Verein / Organisation", "Partei / politische Gruppe"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "une association caritative – ein wohltätiger Verein."
  },
  {
    id: "q10_f_079",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „mobilité“?",
    answers: ["Mobilität", "Nur Transport", "Nur Auto", "Nur Reisen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "mobilité internationale – internationale Mobilität."
  },
  {
    id: "q10_f_080",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „échange“?",
    answers: ["Nur Handel", "Nur Tausch", "Austausch", "Nur Gespräch"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "un échange scolaire – ein Schüleraustausch."
  },
  {
    id: "q10_f_081",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „séjour“?",
    answers: ["Nur Reise", "Nur Urlaub", "Nur Besuch", "Aufenthalt"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "un séjour linguistique – ein Sprachaufenthalt."
  },
  {
    id: "q10_f_082",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „hébergement“?",
    answers: ["Nur Gastfamilie", "Unterkunft", "Nur Hotel", "Nur Wohnung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "l’hébergement en famille – Unterkunft in der Familie."
  },
  {
    id: "q10_f_083",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „quotidien“?",
    answers: ["Woche / wöchentlich", "Jahr / jährlich", "Monat / monatlich", "Alltag / täglich"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "la vie quotidienne – das Alltagsleben."
  },
  {
    id: "q10_f_084",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „habitude“?",
    answers: ["Nur Ritual", "Nur Tradition", "Gewohnheit", "Nur Regel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "avoir l’habitude de … – die Gewohnheit haben zu …"
  },
  {
    id: "q10_f_085",
    category: "k10_franzoesisch",
    topic: "wortschatz",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet „coutume“?",
    answers: ["Nur Gesetz", "Nur Tradition im engen Sinn", "Brauch / Sitte", "Nur Regel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "les coutumes locales – die lokalen Bräuche."
  },
  {
    id: "q10_f_086",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Hauptstadt Frankreichs?",
    answers: ["Marseille", "Paris", "Lyon", "Toulouse"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Paris ist die Hauptstadt und größte Stadt."
  },
  {
    id: "q10_f_087",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist das Motto der Französischen Republik?",
    answers: ["Liberté, égalité, fraternité", "Fraternité, unité, force", "Égalité, justice, paix", "Liberté, sécurité, prospérité"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Freiheit, Gleichheit, Brüderlichkeit."
  },
  {
    id: "q10_f_088",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der 14. Juli in Frankreich?",
    answers: ["Der Tag der Arbeit zu Ehren der Gewerkschaften", "Ein religiöser Feiertag ohne staatlichen Bezug", "Der Gedenktag an das Ende des Ersten Weltkriegs", "Der Nationalfeiertag (Sturm auf die Bastille)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "La fête nationale erinnert an 1789."
  },
  {
    id: "q10_f_089",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Marseillaise?",
    answers: ["Nur ein Volkslied", "Nur ein Lied aus Marseille", "Nur ein Revolutionslied ohne offiziellen Status", "Die französische Nationalhymne"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "La Marseillaise ist die Nationalhymne."
  },
  {
    id: "q10_f_090",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Québec?",
    answers: ["Eine kleine Stadt im Süden Frankreichs", "Eine Insel im Indischen Ozean", "Eine französischsprachige Region in Belgien", "Eine frankophone Provinz in Kanada"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Québec ist ein wichtiges frankophones Gebiet."
  },
  {
    id: "q10_f_091",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Francophonie?",
    answers: ["Die Gesamtheit aller Amtssprachen der Europäischen Union", "Die Organisation der ehemaligen belgischen Kolonialgebiete", "Die Verwaltung sämtlicher kanadischer Provinzen und Territorien", "Die Gemeinschaft der französischsprachigen Länder und Regionen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die OIF fördert die französische Sprache weltweit."
  },
  {
    id: "q10_f_092",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Eiffelturm?",
    answers: ["Ein Denkmal zur Erinnerung an die Revolution von 1789", "Ein Fernsehturm zur Übertragung von Radiosignalen", "Ein Wahrzeichen von Paris, erbaut für die Weltausstellung 1889", "Ein sehr modernes Bauwerk aus dem ganz beginnenden 21. Jahrhundert"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Tour Eiffel ist weltweit bekannt."
  },
  {
    id: "q10_f_093",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Louvre?",
    answers: ["Eine der ältesten Kirchen im historischen Zentrum von Paris", "Eines der größten und bekanntesten Museen der Welt in Paris", "Ein prunkvolles Schloss weit außerhalb der Stadt", "Ein bekanntes Theater für klassische Opernabende"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Louvre beherbergt die Mona Lisa."
  },
  {
    id: "q10_f_094",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Versailles?",
    answers: ["Ein bekanntes Museum für moderne Kunst im Zentrum von Paris", "Ein berühmtes Schloss und ehemalige Residenz der französischen Könige", "Ein weitläufiger Park am östlichen Stadtrand von Paris", "Eine kleine unbedeutende Stadt ohne jede besondere touristische Bedeutung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Versailles symbolisiert den Absolutismus."
  },
  {
    id: "q10_f_095",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Académie française?",
    answers: ["Eine private Schule für besonders begabte Schüler", "Ein renommierter Literaturpreis für zeitgenössische Romane", "Eine staatliche Universität im Zentrum von Paris", "Eine Institution, die die französische Sprache pflegt"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Sie gibt das offizielle Wörterbuch heraus."
  },
  {
    id: "q10_f_096",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der baccalauréat (bac)?",
    answers: ["Das französische Abitur", "Nur eine Zwischenprüfung", "Nur ein Studium", "Nur eine Berufsausbildung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das bac ist der Abschluss der Sekundarstufe II."
  },
  {
    id: "q10_f_097",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist das collège in Frankreich?",
    answers: ["Die weiterführende Schule etwa der Klassen 6–9", "Die gymnasiale Oberstufe der Klassen 10–12", "Die einfache Grundschule der Klassen 1–5 in Frankreich", "Die staatliche Universität nach dem Abitur"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Danach folgt das lycée."
  },
  {
    id: "q10_f_098",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist das lycée?",
    answers: ["Die Grundschule in Frankreich", "Die Oberstufe in Frankreich", "Die Mittelstufe in Frankreich", "Die Universität in Frankreich"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Am Ende steht das baccalauréat."
  },
  {
    id: "q10_f_099",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die Grande École?",
    answers: ["Eine praxisorientierte Berufsschule in Frankreich", "Eine gewöhnliche staatliche Universität ohne Auswahl", "Eine elitär ausgerichtete Hochschule in Frankreich", "Ein allgemeinbildendes Gymnasium in Frankreich"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Zugang oft über concours (Auswahlprüfungen)."
  },
  {
    id: "q10_f_100",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Élysée-Vertrag?",
    answers: ["Ein Handelsabkommen zwischen Frankreich und Deutschland", "Ein Militärpakt aus der Zeit des Kalten Krieges", "Der deutsch-französische Freundschaftsvertrag von 1963", "Ein Kulturabkommen zur Förderung des Filmaustauschs"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Er legte die Grundlage für die enge Zusammenarbeit."
  },
  {
    id: "q10_f_101",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die deutsch-französische Freundschaft?",
    answers: ["Eine rein historische Erinnerung ohne jede aktuelle politische Bedeutung", "Ein einmaliges Schüleraustauschprogramm aus den 1960er Jahren ohne Fortsetzung", "Ein begrenztes Handelsabkommen ausschließlich im Bereich der Landwirtschaft", "Die enge politische und kulturelle Zusammenarbeit seit dem Zweiten Weltkrieg"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie ist ein Pfeiler der europäischen Integration."
  },
  {
    id: "q10_f_102",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die EU?",
    answers: ["Die Europäische Union, an der Frankreich Gründungsmitglied ist", "Eine reine Währungsunion ganz ohne jede politische Zusammenarbeit", "Eine einfache Freihandelszone ohne gemeinsame Institutionen", "Ein reines Militärbündnis unter alleiniger Führung der USA"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Frankreich spielt eine zentrale Rolle in der EU."
  },
  {
    id: "q10_f_103",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Euro?",
    answers: ["Die traditionelle Währung Großbritanniens vor dem Brexit", "Die offizielle Währung der Vereinigten Staaten von Amerika", "Eine alte, heute nicht mehr gültige Landeswährung", "Die gemeinsame Währung vieler EU-Staaten, auch Frankreichs"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Frankreich gehört zur Eurozone."
  },
  {
    id: "q10_f_104",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die laïcité?",
    answers: ["Die ausdrückliche und vollständige Ablehnung jeder Religion durch den Staat", "Das Prinzip der Trennung von Staat und Religion in Frankreich", "Die allgemeine gesellschaftliche Duldung unterschiedlicher Meinungen", "Das verfassungsmäßige Recht, seine Religion frei zu wählen und auszuüben"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Laïcité ist ein zentrales Prinzip der Republik."
  },
  {
    id: "q10_f_105",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen Frankreich und der Frankophonie?",
    answers: ["Die Frankophonie besteht ausschließlich aus ehemaligen Kolonien Frankreichs", "Beide Begriffe bezeichnen exakt dasselbe geografische Gebiet in Europa", "Frankreich ist ein Land, die Frankophonie umfasst alle französischsprachigen Räume", "Frankreich ist nur ein kleiner unbedeutender Teil der Europäischen Union insgesamt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Frankophonie geht weit über Frankreich hinaus."
  },
  {
    id: "q10_f_106",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen Paris und der Province?",
    answers: ["Province bezeichnet ausschließlich die engere ländliche Region um Paris", "Paris ist die Hauptstadt, Province bezeichnet das übrige Frankreich", "Beide Begriffe meinen exakt dasselbe Verwaltungsgebiet", "Paris gehört verwaltungstechnisch nicht zu Frankreich"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Unterscheidung ist kulturell und sprachlich relevant."
  },
  {
    id: "q10_f_107",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen français standard und régionalismes?",
    answers: ["Standardfranzösisch ist die Norm, Regionalismen sind örtliche Varianten", "Regionalismen gelten offiziell als die einzig richtige sprachliche Norm", "Beide Begriffe bezeichnen exakt dieselbe sprachliche Ebene", "Standardfranzösisch wird ausschließlich in Québec gesprochen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Es gibt viele regionale Besonderheiten."
  },
  {
    id: "q10_f_108",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen Québec und Frankreich sprachlich?",
    answers: ["Québec spricht ausschließlich reines europäisches Standardfranzösisch", "Québec hat eigene Ausdrücke, Aussprache und einige grammatische Besonderheiten", "Frankreich übernimmt ganz und gar vollständig alle sprachlichen Besonderheiten von Québec", "Beide Varianten unterscheiden sich in überhaupt keiner Hinsicht"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Québécois hat eigene Merkmale."
  },
  {
    id: "q10_f_109",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen formell und informell im Französischen?",
    answers: ["Formell: vous und gehobene Sprache, informell: tu und umgangssprachlich", "Formell wird ausschließlich in der geschriebenen Schriftsprache verwendet", "Informell wird ausschließlich unter engen Freunden akzeptiert", "Beide Register unterscheiden sich in Frankreich überhaupt nicht voneinander"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Anrede (tu/vous) ist zentral."
  },
  {
    id: "q10_f_110",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „tu“ und „vous“?",
    answers: ["tu wird ausschließlich in offiziellen Briefen verwendet", "vous wird ausschließlich unter ganz kleinen Kindern verwendet", "tu: vertraut/informell, vous: höflich/formell oder Plural", "Beide Formen sind in jeder Situation frei austauschbar"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Wahl hängt von Beziehung und Kontext ab."
  },
  {
    id: "q10_f_111",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „bonjour“ und „salut“?",
    answers: ["bonjour wird nur nach 18 Uhr verwendet", "bonjour: formell/neutral, salut: informell", "salut wird nur bei offiziellen Anlässen benutzt", "Beide Grußformen bedeuten exakt dasselbe"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "salut verwendet man unter Freunden."
  },
  {
    id: "q10_f_112",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „merci“ und „je vous remercie“?",
    answers: ["merci: neutral, je vous remercie: formeller", "Beide Ausdrücke sind gleich höflich", "merci wird nur schriftlich verwendet", "je vous remercie wird nur unter Freunden benutzt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide drücken Dank aus, unterschiedlich formell."
  },
  {
    id: "q10_f_113",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „s’il vous plaît“ und „s’il te plaît“?",
    answers: ["Beide Ausdrücke werden ausschließlich schriftlich verwendet", "s’il vous plaît wird nur bei kleinen Kindern benutzt", "s’il vous plaît: formell, s’il te plaît: informell", "s’il te plaît wird nur beim Einkaufen verwendet"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Höflichkeitsform richtet sich nach tu/vous."
  },
  {
    id: "q10_f_114",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „au revoir“ und „à bientôt“?",
    answers: ["à bientôt wird nur bei sehr offiziellen Anlässen benutzt", "Beide Ausdrücke bedeuten ausschließlich ein endgültiges für immer", "au revoir: allgemeiner Abschied, à bientôt: bis bald", "au revoir wird ausschließlich am Telefon verwendet"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind gängige Abschiedsformeln."
  },
  {
    id: "q10_f_115",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „excusez-moi“ und „pardon“?",
    answers: ["Beide werden ausschließlich schriftlich verwendet", "excusez-moi wird nur unter Freunden benutzt", "Beide entschuldigen, excusez-moi ist formeller", "pardon wird nur bei schweren Fehlern gesagt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind höflich und gebräuchlich."
  },
  {
    id: "q10_f_116",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „je voudrais“ und „je veux“?",
    answers: ["je voudrais: höflich, je veux: direkter/fordernder", "Beide Formen wirken gleich höflich und zurückhaltend", "je veux wird nur in der Schriftsprache benutzt", "je voudrais wird nur bei Fremden verwendet"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "je voudrais ist die höflichere Bitte."
  },
  {
    id: "q10_f_117",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „on“ und „nous“?",
    answers: ["Beide Formen werden ausschließlich in offiziellen Texten schriftlich verwendet", "nous wird ausschließlich in der gesprochenen Umgangssprache benutzt", "on wird ausschließlich in offiziellen Verwaltungsdokumenten verwendet", "on: umgangssprachlich für „wir“ oder „man“, nous: formeller/klassisch"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Im gesprochenen Französisch dominiert oft „on“."
  },
  {
    id: "q10_f_118",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „c’est“ und „il est“?",
    answers: ["c’est wird ausschließlich in kurzen Fragesätzen verwendet", "c’est: für Nomen und Betonung, il est: für Adjektive und Uhrzeit", "Beide Ausdrücke werden stets in völlig identischen Kontexten benutzt", "il est wird ausschließlich bei Personennamen verwendet"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "C’est un livre. Il est intéressant."
  },
  {
    id: "q10_f_119",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „savoir“ und „connaître“?",
    answers: ["connaître bezeichnet nur das Auswendiglernen", "savoir wird nur für Personen verwendet", "savoir: Wissen/Können, connaître: kennen", "Beide Verben sind in jedem Kontext austauschbar"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Je sais nager. Je connais Paris."
  },
  {
    id: "q10_f_120",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „regarder“ und „voir“?",
    answers: ["regarder: bewusst hinschauen, voir: sehen/wahrnehmen", "voir wird ausschließlich für unbewusstes Hören verwendet", "Beide Verben beschreiben ausschließlich den Sinn des Hörens", "regarder wird nur bei laufenden Fernsehsendungen benutzt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Je regarde la télé. Je vois un oiseau."
  },
  {
    id: "q10_f_121",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „écouter“ und „entendre“?",
    answers: ["écouter: bewusst zuhören, entendre: hören/wahrnehmen", "entendre wird nur für bewusstes Betrachten verwendet", "écouter bezeichnet ausschließlich lautes Sprechen", "Beide Verben beschreiben ausschließlich das Sehen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "J’écoute de la musique. J’entends un bruit."
  },
  {
    id: "q10_f_122",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „parler“ und „dire“?",
    answers: ["parler wird nur für schriftliche Mitteilungen benutzt", "dire bezeichnet ausschließlich lautes Rufen", "parler: sprechen (allgemein), dire: sagen", "Beide Verben sind in jeder Situation austauschbar"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Je parle français. Je dis la vérité."
  },
  {
    id: "q10_f_123",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „habiter“ und „vivre“?",
    answers: ["Beide Verben beschreiben nur das Reisen", "vivre wird ausschließlich für Tiere verwendet", "habiter: wohnen (Ort), vivre: leben", "habiter bezeichnet nur einen kurzen Aufenthalt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "J’habite à Paris. Je vis heureux."
  },
  {
    id: "q10_f_124",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen „travailler“ und „fonctionner“?",
    answers: ["travailler: arbeiten (Person), fonctionner: funktionieren", "fonctionner wird ausschließlich für Menschen verwendet", "travailler bezeichnet nur das Funktionieren von Maschinen", "Beide Verben sind in jedem Zusammenhang austauschbar"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Je travaille. L’ordinateur fonctionne."
  },
  {
    id: "q10_f_125",
    category: "k10_franzoesisch",
    topic: "landeskunde",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist interkulturelle Kompetenz?",
    answers: ["Ausschließlich grammatikalisch vollkommen korrekte Sprachkenntnisse ganz ohne jeden Kulturbezug", "Die Fähigkeit, mit Menschen anderer Kulturen angemessen zu kommunizieren und zu handeln", "Das bloße Bereisen fremder Länder ohne jeden weiteren Kontakt zu Menschen", "Reines Faktenwissen über die Geografie und Geschichte eines fremden Landes"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie ist ein zentrales Ziel des Französischunterrichts."
  },
  {
    id: "q10_f_126",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Sprachmittlung?",
    answers: ["Die wörtliche Übertragung eines rein schriftlichen Textes", "Die mündliche Übertragung eines frei gesprochenen Textes", "Das Kürzen eines langen Textes auf die wichtigsten Kernaussagen", "Das Übertragen von Inhalten von einer Sprache in die andere"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Sprachmittlung ist eine wichtige Kompetenz."
  },
  {
    id: "q10_f_127",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Hörverstehen?",
    answers: ["Die Fähigkeit, gesprochene Sprache zu verstehen", "Die Fähigkeit, eigene Texte zu verfassen", "Die Fähigkeit, geschriebene Texte zu verstehen", "Die Fähigkeit, frei zusammenhängend zu sprechen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hörverstehen ist eine rezeptive Kompetenz."
  },
  {
    id: "q10_f_128",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Leseverstehen?",
    answers: ["Die Fähigkeit, gesprochene Sprache zu verstehen", "Die Fähigkeit, geschriebene Texte zu verstehen", "Die Fähigkeit, frei zusammenhängend zu sprechen", "Die Fähigkeit, eigene Texte zu verfassen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Leseverstehen ist eine rezeptive Kompetenz."
  },
  {
    id: "q10_f_129",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist zusammenhängendes Sprechen?",
    answers: ["Der spontane Austausch in einem Dialog", "Das schriftliche Verfassen von Texten", "Das monologische Präsentieren von Inhalten", "Das passive Verstehen gesprochener Sprache"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Teil der produktiven mündlichen Kompetenz."
  },
  {
    id: "q10_f_130",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist an Gesprächen teilnehmen?",
    answers: ["Die Fähigkeit, in Dialogen und Diskussionen zu interagieren", "Die Fähigkeit, ganz allein zusammenhängend frei zu sprechen", "Die Fähigkeit, längere Texte fehlerfrei schriftlich zu verfassen", "Die Fähigkeit, gesprochene Sprache nur passiv zu verstehen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Interaktive mündliche Kompetenz."
  },
  {
    id: "q10_f_131",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Schreiben als Kompetenz?",
    answers: ["Das bloße Abschreiben fertiger Vorlagen ganz ohne jede eigene Formulierung", "Die Fähigkeit, Texte zielgerichtet und sprachlich angemessen zu verfassen", "Die wörtliche Übersetzung eines Textes in eine ganz andere Sprache", "Das stichwortartige Festhalten kurzer eigener Notizen im Heft"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Schreiben ist eine produktive Kompetenz."
  },
  {
    id: "q10_f_132",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Text- und Medienkompetenz?",
    answers: ["Das reine Verfassen eigener Texte ganz ohne jede weitere Analyse oder Reflexion überhaupt", "Die Fähigkeit, Texte und Medien zu verstehen, zu analysieren und zu produzieren", "Das bloße Anhören gesprochener Texte ohne inhaltliche Auseinandersetzung", "Das einfache Lesen von Texten ganz ohne weitere sprachliche Verarbeitung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie umfasst analoge und digitale Medien."
  },
  {
    id: "q10_f_133",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Sprachlernkompetenz?",
    answers: ["Ausschließlich das vollkommen fehlerfreie Beherrschen aller grammatischen Regeln", "Das reine Auswendiglernen von Vokabellisten ganz ohne eigenes System", "Die Fähigkeit, das eigene Sprachenlernen zu organisieren und zu reflektieren", "Das wiederholte mechanische Üben von Aufgaben ganz ohne jede Reflexion"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie fördert autonomes Lernen."
  },
  {
    id: "q10_f_134",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Sprachbewusstheit?",
    answers: ["Die korrekte Betonung und Aussprache einzelner besonders fremder Wörter", "Das reine Wissen über die grammatischen Regeln einer Sprache", "Das Bewusstsein für sprachliche Strukturen, Register und Varietäten", "Der aktive und passive Wortschatz einer gelernten Fremdsprache"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Sprachbewusstheit hilft beim bewussten Sprachgebrauch."
  },
  {
    id: "q10_f_135",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Gemeinsame europäische Referenzrahmen (GeR)?",
    answers: ["Ein Rahmen zur Beschreibung von Sprachkompetenzen (A1–C2)", "Ein verbindlicher Lehrplan für alle Fächer einer Schule", "Eine standardisierte Prüfung am Ende der gesamten Schulzeit", "Ein alphabetisches Nachschlagewerk für fremdsprachige Wörter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Am Ende der SI wird etwa B1 angestrebt."
  },
  {
    id: "q10_f_136",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was bedeutet Niveau B1 im GeR?",
    answers: ["Elementare Sprachverwendung in ganz einfachsten Situationen", "Kompetente Sprachverwendung in besonders komplexen Situationen", "Nahezu muttersprachliche Beherrschung der gesamten Sprache", "Selbstständige Sprachverwendung in vertrauten Situationen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "B1 ist das Ziel am Ende der Sekundarstufe I."
  },
  {
    id: "q10_f_137",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist eine Lernstrategie?",
    answers: ["Ein planvolles Vorgehen zum effektiven Sprachenlernen", "Ein rein mechanisches Auswendiglernen fester grammatischer Regeln", "Ein ständiges Üben ganz ohne erkennbares System", "Ein einfaches Wiederholen bereits gut Gelernten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Strategien unterstützen nachhaltiges Lernen."
  },
  {
    id: "q10_f_138",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Wortschatzarbeit?",
    answers: ["Das wörtliche Übertragen einzelner Wörter in eine ganz andere Fremdsprache", "Das systematische Erschließen, Üben und Anwenden von Wörtern und Wendungen", "Das reine Auswendiglernen von Vokabellisten ganz ohne Anwendung", "Das gelegentliche Nachschlagen einzelner unbekannter Wörter"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wortschatz ist Grundlage der Kommunikation."
  },
  {
    id: "q10_f_139",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Aussprache und Intonation?",
    answers: ["Der aktive und passive Wortschatz eines Lernenden insgesamt", "Die korrekten grammatischen Regeln einer gelernten Sprache", "Die richtige Schreibweise einzelner schwieriger Wörter", "Die korrekte Lautbildung und die Melodie der Sprache"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie sind Teil der funktionalen kommunikativen Kompetenz."
  },
  {
    id: "q10_f_140",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Orthografie?",
    answers: ["Die grammatischen Regelwerke", "Die richtige Aussprache", "Die korrekte Schreibweise", "Der passive Wortschatz"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Orthografie gehört zu den sprachlichen Mitteln."
  },
  {
    id: "q10_f_141",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein authentischer Text?",
    answers: ["Ein Text, der speziell und ausschließlich für den Sprachunterricht geschrieben wurde", "Ein Text, der wörtlich aus einer anderen Sprache übersetzt und übertragen wurde", "Ein Text, der ursprünglich für Muttersprachler und nicht für Lernende verfasst wurde", "Ein kurzes fiktives Gespräch zwischen zwei erfundenen literarischen Personen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Authentische Texte fördern reale Sprachbegegnung."
  },
  {
    id: "q10_f_142",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist ein didaktisierter Text?",
    answers: ["Ein anspruchsvoller literarischer Text ganz ohne Anpassung", "Ein aktueller Zeitungsartikel ganz ohne jede Bearbeitung", "Ein Text, der ausschließlich für Muttersprachler verfasst wurde", "Ein für Lernende vereinfachter oder aufbereiteter Text"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Didaktisierte Texte erleichtern den Einstieg."
  },
  {
    id: "q10_f_143",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Feedback im Sprachunterricht?",
    answers: ["Eine ausschließliche Korrektur von Fehlern ohne Erklärung", "Eine reine Notenvergabe ohne weitere Erläuterung", "Ein allgemeines Lob ohne konkrete Hinweise", "Rückmeldung zur sprachlichen Leistung und zum Lernprozess"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Konstruktives Feedback fördert das Lernen."
  },
  {
    id: "q10_f_144",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist Selbstevaluation?",
    answers: ["Die Bewertung ausschließlich durch die Lehrkraft allein", "Die eigene Einschätzung des Lernstands und der Fortschritte", "Eine regelmäßige schriftliche Leistungskontrolle im Unterricht", "Die offizielle Zeugnisnote am Ende des Schuljahres"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Selbstevaluation stärkt die Lernkompetenz."
  },
  {
    id: "q10_f_145",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist kooperatives Lernen?",
    answers: ["Lernen vollständig allein und ganz ohne jeglichen Austausch mit anderen", "Unterricht, bei dem ausschließlich die Lehrkraft frontal vorträgt", "Lernen in Partner- oder Gruppenarbeit mit gemeinsamer Verantwortung", "Aufgaben, die ausschließlich zu Hause allein bearbeitet werden"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Kooperation fördert Kommunikation und Sozialkompetenz."
  },
  {
    id: "q10_f_146",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen rezeptiven und produktiven Kompetenzen?",
    answers: ["Produktiv bezeichnet ausschließlich das Hörverstehen", "Rezeptiv: verstehen , produktiv: erzeugen", "Rezeptiv bezeichnet ausschließlich das freie Sprechen", "Beide Begriffe meinen exakt denselben Vorgang"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Bereiche ergänzen sich."
  },
  {
    id: "q10_f_147",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen formeller und informeller Sprache?",
    answers: ["Informell wird ausschließlich in ganz offiziellen amtlichen Prüfungssituationen verwendet", "Formell: situationsangemessen höflich, informell: vertraut und umgangssprachlich", "Formell wird ausschließlich im Gespräch unter engen Freunden benutzt", "Beide Sprachregister sind in jeder denkbaren Situation völlig gleichwertig"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Registerbewusstsein ist Teil der Sprachkompetenz."
  },
  {
    id: "q10_f_148",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen Monolog und Dialog?",
    answers: ["Dialog bezeichnet ausschließlich das Zuhören", "Monolog bezeichnet ausschließlich den Austausch zu zweit", "Beide Begriffe meinen dieselbe Sprechform", "Monolog: allein sprechen, Dialog: Wechselrede"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Formen werden im Unterricht geübt."
  },
  {
    id: "q10_f_149",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist der Unterschied zwischen globalem und detailliertem Verstehen?",
    answers: ["Beide Begriffe bezeichnen exakt dieselbe Lesetechnik im Unterricht", "Global: Gesamtverständnis, detailliert: genaue Informationen", "Detailliertes Verstehen erfasst nur den groben Gesamtinhalt", "Globales Verstehen erfasst jede einzelne kleine Information"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Strategien sind beim Hören und Lesen wichtig."
  },
  {
    id: "q10_f_150",
    category: "k10_franzoesisch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "franzoesisch",
    question: "Was ist die zentrale Aufgabe des Französischunterrichts?",
    answers: ["Ausschließlich sämtliche grammatische Regeln vollständig fehlerfrei anzuwenden und stets perfekt zu beherrschen", "Ausschließlich schriftliche Texte möglichst wortgetreu zu übersetzen und wiederzugeben", "Zur interkulturellen kommunikativen Handlungsfähigkeit in der französischen Sprache zu befähigen", "Ausschließlich einen möglichst großen Wortschatz auswendig zu lernen und stets abzufragen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Ziel ist handlungsorientierte Sprachkompetenz."
  }
];
