const K10_ERDKUNDE_QUESTIONS = [
  // ================================================================
  // 1. PHYSISCHE GEOGRAPHIE & NATURRISIKEN (40 Fragen)
  // ================================================================
  {
    id: "q10_e_001",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Plattentektonik?",
    answers: ["Die Lehre von der Verschiebung der Ozeanböden", "Die Theorie zur Entstehung der Erdatmosphäre", "Die Beschreibung der Gesteinsschichten im Erdmantel", "Die Theorie der Bewegung der Lithosphärenplatten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Plattenbewegungen erklären viele geologische Prozesse."
  },
  {
    id: "q10_e_002",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine Subduktionszone?",
    answers: ["Ein Bereich, in dem zwei Platten aneinander vorbeigleiten", "Ein Bereich, in dem eine Platte unter eine andere abtaucht", "Ein Bereich, in dem sich der Meeresboden absenkt und einbricht", "Ein Bereich, in dem neue ozeanische Kruste entsteht"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Subduktion führt oft zu Vulkanismus und Erdbeben."
  },
  {
    id: "q10_e_003",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Erdbeben?",
    answers: ["Eine plötzliche Verschiebung von Gesteinsschichten entlang einer Bruchzone", "Eine langsame Verformung von Gestein durch anhaltenden Druck im Untergrund", "Eine kurzzeitige Absenkung des Erdbodens nach starken Regenfällen im Gebirge", "Eine plötzliche Erschütterung der Erdkruste durch Spannungsabbau"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Erdbeben entstehen oft an Plattengrenzen."
  },
  {
    id: "q10_e_004",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist das Epizentrum?",
    answers: ["Der Ort im Erdinneren, an dem die Bebenwellen ihren Ursprung nehmen", "Der Punkt an der Erdoberfläche senkrecht über dem Erdbebenherd", "Die Zone entlang einer Plattengrenze mit besonders hoher Bebenhäufigkeit", "Der Bereich an der Oberfläche mit den stärksten Zerstörungen nach einem Beben"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Epizentrum ist der Ort stärkster Auswirkungen."
  },
  {
    id: "q10_e_005",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die Richterskala?",
    answers: ["Eine Skala zur Einteilung der Stärke eines einzelnen Bebens", "Eine Skala zur Beschreibung des Ausflusses von Lava am Hang", "Eine Skala zur Einordnung der Stärke tropischer Stürme", "Eine Skala zur Messung der Magnitude von Erdbeben"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Magnitude beschreibt die freigesetzte Energie."
  },
  {
    id: "q10_e_006",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Tsunami?",
    answers: ["Eine große Meereswelle, oft durch Seebeben ausgelöst", "Eine ungewöhnlich hohe Flut durch starken Sturm", "Eine Welle, die durch Wind an der Küste entsteht", "Ein regelmäßiger Anstieg des Wassers durch Ebbe und Flut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Tsunamis können verheerende Folgen an Küsten haben."
  },
  {
    id: "q10_e_007",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Vulkan?",
    answers: ["Eine trichterförmige Vertiefung an der Bergspitze", "Eine Erhebung des Landes über die Umgebung", "Eine Öffnung der Erdkruste, aus der Magma austritt", "Eine erstarrte Gesteinsschicht aus früherem Ausbruch"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Vulkane entstehen oft an Plattengrenzen oder Hotspots."
  },
  {
    id: "q10_e_008",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Magma?",
    answers: ["Heiße Dämpfe, die aus dem Vulkan entweichen", "Geschmolzenes Gestein unter der Erdoberfläche", "Geschmolzenes Gestein an der Erdoberfläche", "Feine Partikel, die beim Ausbruch ausgestoßen werden"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "An der Oberfläche wird Magma zu Lava."
  },
  {
    id: "q10_e_009",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Lava?",
    answers: ["Heiße Dämpfe, die aus dem Krater entweichen", "Feine Partikel, die bei einem Ausbruch entstehen", "Geschmolzenes Gestein unter der Erdoberfläche", "Geschmolzenes Gestein an der Erdoberfläche"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Lava entsteht beim Austritt von Magma."
  },
  {
    id: "q10_e_010",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Schichtvulkan?",
    answers: ["Ein steiler Vulkan aus abwechselnden Lava- und Ascheschichten", "Ein sehr flacher Vulkan aus dünnflüssiger, weit fließender Lava", "Ein eingesunkener Krater, entstanden nach großem Ausbruch", "Ein kleiner Vulkankegel, der nur ein einziges Mal ausbricht"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Schichtvulkane sind oft explosiv."
  },
  {
    id: "q10_e_011",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Schildvulkan?",
    answers: ["Ein steiler Vulkan aus Lava- und Ascheschichten", "Ein spitzer Vulkan mit einem einzigen Krater", "Ein eingesunkener Krater nach einer Eruption", "Ein flacher Vulkan aus dünnflüssiger Lava"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Schildvulkane entstehen oft an Hotspots."
  },
  {
    id: "q10_e_012",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Ring of Fire?",
    answers: ["Ein Gürtel intensiver vulkanischer und seismischer Aktivität um den Pazifik", "Ein Gürtel besonders häufiger Erdbeben rund um das Mittelmeer und Teile Europas", "Ein einziger, sehr aktiver Vulkan im gesamten Inselraum Südostasiens", "Ein Gürtel intensiver Erdbebenaktivität entlang der gesamten Alpenkette"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Dort treffen viele Platten aufeinander."
  },
  {
    id: "q10_e_013",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein tropischer Wirbelsturm?",
    answers: ["Ein saisonaler Wind, der starken Regen weit ins Landesinnere hineinträgt", "Ein kurzes, aber sehr heftiges Unwetter mit Blitz, Donner und Hagel", "Ein starker Sturm über warmen Meeresgebieten mit niedrigem Druckzentrum", "Ein kleinräumiger, jedoch extrem starker Luftwirbel über festem Land"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Je nach Region Hurricane, Taifun oder Zyklon genannt."
  },
  {
    id: "q10_e_014",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Tornado?",
    answers: ["Ein kleinräumiger, sehr starker Wirbelsturm über Land", "Ein kurzes, heftiges Unwetter mit Blitz und Donner", "Ein sehr großer tropischer Sturm über dem Ozean", "Ein saisonaler Wind, der Regen ins Landesinnere bringt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Tornados entstehen oft bei starken Gewittern."
  },
  {
    id: "q10_e_015",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Hochwasser?",
    answers: ["Ein Übertritt von Flüssen oder Meeren über ihre Ufer", "Ein sehr starker Wind mit ungewöhnlich hohen Wellen an der Küste", "Ein ungewöhnlich niedriger Wasserstand in einem Fluss im Sommer", "Eine lang anhaltende Trockenperiode ohne ausreichenden Regen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hochwasser kann natürliche oder anthropogene Ursachen haben."
  },
  {
    id: "q10_e_016",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Erosion?",
    answers: ["Die Ablagerung von abgetragenem Material an einem völlig neuen Ort", "Die Zerkleinerung von Gestein direkt an Ort und Stelle ohne Transport", "Die Ablagerung feiner Sedimente am Grund eines Meeres oder Sees", "Der Abtrag von Gestein und Boden durch Wind, Wasser oder Eis"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Erosion formt Landschaften."
  },
  {
    id: "q10_e_017",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Verwitterung?",
    answers: ["Die Bewegung großer Erdplatten im zähflüssigen Erdmantel über Jahrmillionen", "Die Zerkleinerung und Veränderung von Gestein an der Erdoberfläche", "Die Ablagerung von abgetragenem Material an einem völlig neuen Ort", "Der Abtrag von Gestein und Boden durch fließendes Wasser, Wind oder Eis"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Verwitterung bereitet Material für Erosion vor."
  },
  {
    id: "q10_e_018",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Wasserkreislauf?",
    answers: ["Der Übergang von flüssigem Wasser in einen gasförmigen Aggregatzustand", "Der ständige Kreislauf des Wassers zwischen Atmosphäre, Land und Meer", "Der Niederschlag von Wasser aus Wolken hinunter zur festen Erdoberfläche", "Der Abfluss von Regen- und Schmelzwasser über Flüsse direkt ins Meer"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Verdunstung, Niederschlag und Abfluss sind zentrale Prozesse."
  },
  {
    id: "q10_e_019",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Klima?",
    answers: ["Die durchschnittliche Wärme der Luft an einem einzelnen bestimmten Tag", "Die Gesamtmenge des Regens, die im Jahresverlauf an einem Ort fällt", "Der langfristige mittlere Zustand der Atmosphäre an einem Ort", "Der kurzfristige, sich täglich ändernde Zustand der Atmosphäre vor Ort"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Klima wird über längere Zeiträume betrachtet."
  },
  {
    id: "q10_e_020",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Wetter?",
    answers: ["Die durchschnittliche Wärme der Luft im Jahresverlauf", "Die langfristige Menge des Niederschlags an einem Ort", "Der aktuelle Zustand der Atmosphäre an einem Ort", "Der langfristige mittlere Zustand der Atmosphäre"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Wetter ändert sich kurzfristig."
  },
  {
    id: "q10_e_021",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Treibhauseffekt?",
    answers: ["Die Entstehung von Wolken durch aufsteigende Luft", "Die schützende Schicht aus Ozon in der Stratosphäre", "Die Abkühlung der Erde durch Vulkanasche", "Die Erwärmung der Atmosphäre durch Spurengase"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Natürlicher und anthropogener Treibhauseffekt unterscheiden sich."
  },
  {
    id: "q10_e_022",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Klimawandel?",
    answers: ["Der regelmäßige jahreszeitliche Wechsel zwischen Sommer- und Winterwetter", "Die langfristige Veränderung des Klimas, derzeit vor allem anthropogen", "Der tägliche Wechsel zwischen warmem und kaltem Wetter innerhalb eines Tages", "Natürliche Schwankungen des Klimas, die sich über Jahrmillionen vollziehen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Menschliche Aktivitäten verstärken den Treibhauseffekt."
  },
  {
    id: "q10_e_023",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was sind Treibhausgase?",
    answers: ["Gase, die in der Luft keine chemische Wirkung haben", "Ein Gas, das den Großteil der Luft ausmacht", "Gase, die den Treibhauseffekt verstärken", "Ein Gas, das für die Atmung notwendig ist"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "CO₂ entsteht vor allem durch Verbrennung fossiler Energieträger."
  },
  {
    id: "q10_e_024",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Meeresspiegelanstieg?",
    answers: ["Das Ansteigen des mittleren Meeresspiegels durch Erwärmung und Eisschmelze", "Das kurzfristige, sehr starke Ansteigen des Wasserstands durch eine Sturmflut", "Die regelmäßige, tägliche Bewegung des Meerwassers durch Ebbe und Flut", "Die großräumige, dauerhafte Bewegung von Wassermassen im offenen Ozean"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Er bedroht Küstenregionen weltweit."
  },
  {
    id: "q10_e_025",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die Ozonschicht?",
    answers: ["Eine elektrisch geladene Schicht hoch über der Erde, wichtig für Funk", "Eine Schicht in der Stratosphäre, die UV-Strahlung absorbiert", "Die unterste Luftschicht der Atmosphäre, in der das Wetter entsteht", "Die äußerste, sehr dünne Schicht der Erdatmosphäre nahe dem Weltraum"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Ozonloch ist ein bekanntes Umweltproblem."
  },
  {
    id: "q10_e_026",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Biom?",
    answers: ["Ein kleinräumiger Lebensraum, der nur von einer einzelnen Art bewohnt wird", "Die Gesamtheit aller Lebewesen und ihrer Umwelt an einem bestimmten Ort", "Ein großräumiger Lebensraum mit charakteristischer Vegetation und Klima", "Eine einzelne Pflanzen- oder Tierart, die typisch für eine Region ist"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beispiele: Regenwald, Savanne, Tundra."
  },
  {
    id: "q10_e_027",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der tropische Regenwald?",
    answers: ["Ein Waldökosystem der gemäßigten Zone mit überwiegend sommergrünen Laubbäumen", "Ein Waldökosystem der kalten Zone mit überwiegend immergrünen Nadelbäumen", "Ein immergrünes Waldökosystem in den Tropen mit hoher Artenvielfalt", "Eine grasbewachsene Landschaft mit vereinzelten Bäumen in tropischer Lage"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Regenwälder sind wichtige Kohlenstoffspeicher."
  },
  {
    id: "q10_e_028",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Desertifikation?",
    answers: ["Die Ausbreitung von Wüsten und die Verödung von Land", "Das Wachstum von Städten auf Kosten von Ackerland", "Die künstliche Bewässerung von trockenem Ackerland", "Das gezielte Anpflanzen von Wäldern auf freien Flächen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ursachen sind Klima und menschliche Nutzung."
  },
  {
    id: "q10_e_029",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Klima und Wetter?",
    answers: ["Klima beschreibt nur die Temperatur eines einzelnen Tages", "Wetter: langfristig, Klima: kurzfristig", "Klima: langfristig, Wetter: kurzfristig", "Beide Begriffe bezeichnen genau denselben Sachverhalt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Klima beschreibt Mittelwerte über Jahrzehnte."
  },
  {
    id: "q10_e_030",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Magnitude und Intensität bei Erdbeben?",
    answers: ["Magnitude: freigesetzte Energie, Intensität: Auswirkungen vor Ort", "Magnitude: Auswirkungen vor Ort, Intensität: freigesetzte Energie", "Magnitude und Intensität bezeichnen in der Seismologie denselben Wert", "Magnitude misst nur die Tiefe des Bebenherds unter der Erde"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Richterskala misst Magnitude."
  },
  {
    id: "q10_e_031",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen kontinentaler und ozeanischer Kruste?",
    answers: ["Ozeanische Kruste ist dicker und leichter, kontinentale dünner und schwerer", "Kontinentale Kruste ist dicker und leichter, ozeanische dünner und schwerer", "Kontinentale und ozeanische Kruste bestehen aus identischem Gestein", "Beide Krustentypen haben exakt die gleiche Dicke und Dichte"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das beeinflusst Subduktionsprozesse."
  },
  {
    id: "q10_e_032",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen natürlichem und anthropogenem Treibhauseffekt?",
    answers: ["Natürlich ist immer schädlich", "Natürlich: lebenswichtig, anthropogen: durch Menschen verstärkt", "Natürlicher und anthropogener Treibhauseffekt sind wissenschaftlich identisch", "Nur der anthropogene Treibhauseffekt existiert tatsächlich in der Atmosphäre"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der anthropogene Effekt treibt den aktuellen Klimawandel."
  },
  {
    id: "q10_e_033",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Adaptation und Mitigation beim Klimawandel?",
    answers: ["Adaptation: Vermeidung/Verminderung, Mitigation: Anpassung", "Adaptation und Mitigation bezeichnen denselben Klimaschutzansatz", "Adaptation: Anpassung, Mitigation: Vermeidung/Verminderung", "Adaptation bedeutet ausschließlich technische Emissionsminderung"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Strategien sind notwendig."
  },
  {
    id: "q10_e_034",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen erneuerbaren und fossilen Energieträgern?",
    answers: ["Erneuerbar: endlich und CO₂-intensiv, fossil: regenerieren sich", "Erneuerbare und fossile Energieträger sind gleichermaßen unbegrenzt verfügbar", "Fossile Energieträger erneuern sich innerhalb weniger Jahrzehnte von selbst", "Erneuerbar: regenerieren sich, fossil: endlich und CO₂-intensiv"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Sonne, Wind und Wasser sind erneuerbar."
  },
  {
    id: "q10_e_035",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Biodiversität und Artenvielfalt?",
    answers: ["Biodiversität umfasst Arten, Gene und Ökosysteme, Artenvielfalt nur Arten", "Artenvielfalt umfasst Arten, Gene und Ökosysteme, Biodiversität nur Arten", "Biodiversität und Artenvielfalt bezeichnen exakt denselben engen Begriff", "Biodiversität beschreibt allein die genetische Vielfalt einzelner Populationen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Biodiversität ist der umfassendere Begriff."
  },
  {
    id: "q10_e_036",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Endmoräne und Grundmoräne?",
    answers: ["Endmoräne: unter dem Gletscher, Grundmoräne: am Gletscherrand", "Endmoräne: am Gletscherrand, Grundmoräne: unter dem Gletscher", "Endmoräne und Grundmoräne bezeichnen dieselbe Ablagerungsform", "Beide Moränentypen entstehen ausschließlich durch fließendes Flusswasser"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Beide sind glaziale Ablagerungen."
  },
  {
    id: "q10_e_037",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen chemischer und physikalischer Verwitterung?",
    answers: ["Physikalisch ist immer chemisch", "Chemisch ist immer physikalisch", "Chemisch: Stoffumwandlung, physikalisch: mechanische Zerkleinerung", "Chemische Verwitterung entsteht ausschließlich durch Frost und Eis"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Prozesse wirken oft zusammen."
  },
  {
    id: "q10_e_038",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Klima- und Wettervorhersage?",
    answers: ["Klimavorhersage ist immer Wetter", "Klimavorhersage: langfristig, Wettervorhersage: kurzfristig", "Klimavorhersage und Wettervorhersage nutzen identische Zeiträume", "Wettervorhersage betrachtet nur die Entwicklung über Jahrzehnte"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Unterschiedliche Zeithorizonte und Methoden."
  },
  {
    id: "q10_e_039",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen absinkendem und aufsteigendem Luftstrom?",
    answers: ["Absinkend: Hochdruck, aufsteigend: Tiefdruck", "Absinkend: Tiefdruck, aufsteigend: Hochdruck", "Aufsteigende Luft entsteht nur über sehr kalten Regionen", "Absinkende und aufsteigende Luftströme erzeugen denselben Druck"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Aufsteigende Luft führt oft zu Niederschlag."
  },
  {
    id: "q10_e_040",
    category: "k10_erdkunde",
    topic: "physische_geographie",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen geographischer und astronomischer Breite?",
    answers: ["Geographisch: Position auf der Erde, astronomisch: bezogen auf Himmelskörper", "Geographisch: bezogen auf Himmelskörper, astronomisch: Position auf der Erde", "Geographische und astronomische Breite bezeichnen exakt denselben Wert", "Astronomische Breite beschreibt allein die Entfernung zum Nullmeridian"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Geographische Breite bestimmt Klima und Tageslänge."
  },

  // ================================================================
  // 2. BEVÖLKERUNG, SIEDLUNG & WIRTSCHAFT (40 Fragen)
  // ================================================================
  {
    id: "q10_e_041",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die Weltbevölkerung?",
    answers: ["Die Anzahl der Menschen, die in Städten leben", "Die Gesamtzahl der Menschen auf der Erde", "Die Zahl der Einwohner eines einzelnen Kontinents", "Die Anzahl der Menschen ohne festen Wohnsitz"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie beträgt derzeit über 8 Milliarden."
  },
  {
    id: "q10_e_042",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die Bevölkerungsdichte?",
    answers: ["Die Gesamtzahl aller Einwohner eines Staates", "Der Anteil der Menschen, die jährlich sterben", "Die Anzahl der Einwohner pro Flächeneinheit", "Der Anteil der Menschen, die jährlich geboren werden"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie wird meist in Einwohnern pro km² angegeben."
  },
  {
    id: "q10_e_043",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die Geburtenrate?",
    answers: ["Die Anzahl der Menschen, die ins Ausland abwandern", "Die Anzahl der Todesfälle pro 1000 Einwohner und Jahr", "Die Anzahl der Geburten pro 1000 Einwohner und Jahr", "Die Anzahl der Menschen, die neu zuwandern"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie beeinflusst das Bevölkerungswachstum."
  },
  {
    id: "q10_e_044",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die Sterberate?",
    answers: ["Die Anzahl der Menschen, die neu ins Land einwandern", "Die Anzahl der Geburten je 1000 Einwohner im Jahr", "Die Anzahl der Menschen, die das Land dauerhaft verlassen", "Die Anzahl der Todesfälle pro 1000 Einwohner und Jahr"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie sinkt mit besserer Gesundheitsversorgung."
  },
  {
    id: "q10_e_045",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist das natürliche Bevölkerungswachstum?",
    answers: ["Die Differenz zwischen Geburten- und Sterberate", "Die Summe aus Zu- und Abwanderung eines Landes", "Der Anteil älterer Menschen an der Gesamtbevölkerung", "Die Bewegung von Menschen zwischen Stadt und Land"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Migration beeinflusst das Gesamtwachstum zusätzlich."
  },
  {
    id: "q10_e_046",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der demografische Übergang?",
    answers: ["Die Wanderung großer Bevölkerungsgruppen über Grenzen", "Die Zunahme des Anteils älterer Menschen an der Bevölkerung", "Der Wandel von hohen zu niedrigen Geburten- und Sterberaten", "Die stetige Zunahme der Weltbevölkerung ohne Ende"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Er beschreibt typische Phasen der Bevölkerungsentwicklung."
  },
  {
    id: "q10_e_047",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine Alterspyramide?",
    answers: ["Eine Grafik der jährlichen Geburten- und Sterbezahlen eines Staates", "Eine grafische Darstellung der Alters- und Geschlechtsstruktur", "Eine tabellarische Übersicht wichtiger wirtschaftlicher Kennzahlen", "Eine kartenähnliche Darstellung der Bevölkerungsdichte im Land"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sie zeigt, ob eine Bevölkerung jung oder alt ist."
  },
  {
    id: "q10_e_048",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Urbanisierung?",
    answers: ["Die Zunahme des Anteils der Stadtbevölkerung", "Die Entstehung besonders großer Metropolregionen", "Die Abwanderung aus der Stadt in das Umland", "Die Neugründung von Städten in ländlichen Gebieten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Urbanisierung ist ein globales Phänomen."
  },
  {
    id: "q10_e_049",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine Megacity?",
    answers: ["Eine Stadt mit mehr als 1 Million Einwohnern", "Eine Stadt mit mehr als 10 Millionen Einwohnern", "Eine Stadt, die als Hauptstadt eines Landes dient", "Eine Stadt mit besonders hoher Industriedichte"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Tokio, Delhi, Shanghai."
  },
  {
    id: "q10_e_050",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Suburbanisierung?",
    answers: ["Die Abwanderung der Bevölkerung vom Land in die Stadt", "Die Entstehung besonders großer Metropolregionen", "Die Abwanderung aus der Kernstadt in das Umland", "Die Zunahme des Anteils der Stadtbevölkerung"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Suburbanisierung prägt viele Industrieländer."
  },
  {
    id: "q10_e_051",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Migration?",
    answers: ["Die dauerhafte Ansiedlung von Menschen in einem einzigen fremden Land", "Die Wanderung von Menschen über Grenzen oder innerhalb von Staaten", "Das zeitlich begrenzte Reisen in ferne Länder zur Erholung", "Die einmalige Übersiedlung aus dem eigenen Heimatland"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Migration kann freiwillig oder erzwungen sein."
  },
  {
    id: "q10_e_052",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Push-Faktor?",
    answers: ["Ein Grund, der Menschen an einen Ort besonders bindet", "Ein Grund, der Menschen zum Verlassen eines Ortes bewegt", "Ein Vorteil, der aus gemeinsamer Sprache und Kultur entsteht", "Ein finanzieller Anreiz, an einem neuen Ort zu bleiben"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Krieg, Armut, Naturkatastrophen."
  },
  {
    id: "q10_e_053",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Pull-Faktor?",
    answers: ["Ein Grund, der Menschen zum Wegzug zwingt", "Ein Grund, der Menschen an einen Ort anzieht", "Ein plötzliches Ereignis wie Erdbeben oder Flut", "Ein staatlicher Zwang, das Land zu verlassen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Arbeit, Sicherheit, Bildung."
  },
  {
    id: "q10_e_054",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der primäre Sektor?",
    answers: ["Fertigung von Waren in Fabriken und Werken", "Verkauf und Vertrieb von Waren an Kunden", "Landwirtschaft, Forstwirtschaft und Fischerei", "Bildung, Gesundheit und andere Dienstleistungen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der primäre Sektor gewinnt Rohstoffe."
  },
  {
    id: "q10_e_055",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der sekundäre Sektor?",
    answers: ["Industrie und verarbeitendes Gewerbe", "Handel und Transport von Waren", "Anbau von Pflanzen und Haltung von Tieren", "Beratung, Bildung und Gesundheitswesen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der sekundäre Sektor verarbeitet Rohstoffe."
  },
  {
    id: "q10_e_056",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der tertiäre Sektor?",
    answers: ["Dienstleistungen", "Nur Landwirtschaft", "Nur Rohstoffgewinnung", "Nur Industrie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In Industrieländern dominiert der tertiäre Sektor."
  },
  {
    id: "q10_e_057",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Standortfaktor?",
    answers: ["Ein Merkmal, das ausschließlich den Kaufpreis eines einzelnen Grundstücks festlegt", "Die exakte Entfernung in Kilometern zwischen zwei benachbarten Großstädten im Land", "Das durchschnittliche Klima einer bestimmten Region, betrachtet über das gesamte Jahr", "Ein Merkmal, das die Eignung eines Ortes für wirtschaftliche Aktivitäten beeinflusst"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Arbeitskräfte, Verkehr, Rohstoffe."
  },
  {
    id: "q10_e_058",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Globalisierung?",
    answers: ["Die zunehmende weltweite Verflechtung von Wirtschaft, Kultur und Politik", "Der grenzüberschreitende Austausch von Waren, Dienstleistungen und Kapital", "Die weltweite Wanderung von Menschen aus vorwiegend wirtschaftlichen Gründen", "Die zunehmende Nutzung digitaler Technik im Alltag von Menschen weltweit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Globalisierung hat räumliche Auswirkungen."
  },
  {
    id: "q10_e_059",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Entwicklungsunterschied?",
    answers: ["Unterschiede im wirtschaftlichen und sozialen Entwicklungsstand von Regionen", "Unterschiede im Zugang zu Schulen und beruflichen Ausbildungsmöglichkeiten", "Unterschiede in der medizinischen Versorgung und der Lebenserwartung der Menschen", "Unterschiede im durchschnittlichen Einkommen einzelner Haushalte einer Region"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Entwicklungsunterschiede bestehen global und national."
  },
  {
    id: "q10_e_060",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Human Development Index (HDI)?",
    answers: ["Ein Wert für die Anzahl der Schuljahre einer Bevölkerung", "Ein Wert für die durchschnittliche Lebenserwartung", "Ein Wert für das Bruttoinlandsprodukt eines Landes", "Ein Index zur Messung der menschlichen Entwicklung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "HDI berücksichtigt Gesundheit, Bildung und Einkommen."
  },
  {
    id: "q10_e_061",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist absolute Armut?",
    answers: ["Ein Zustand, in dem grundlegende Bedürfnisse nicht gedeckt werden können", "Ein Zustand, in dem der Zugang zu Bildung dauerhaft fehlt", "Ein Zustand, in dem das Einkommen unter dem Landesdurchschnitt liegt", "Ein Zustand, der im Vergleich zum gesellschaftlichen Durchschnitt entsteht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Absolute Armut wird oft an der 2,15-Dollar-Grenze gemessen."
  },
  {
    id: "q10_e_062",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist relative Armut?",
    answers: ["Ein Zustand, in dem lebenswichtige Bedürfnisse fehlen", "Ein Zustand im Vergleich zum gesellschaftlichen Durchschnitt", "Ein Zustand, in dem grundlegende Bedürfnisse nicht gedeckt werden können", "Ein Zustand, in dem der Zugang zu Bildung dauerhaft fehlt"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Relative Armut bezieht sich auf den Lebensstandard der Umgebung."
  },
  {
    id: "q10_e_063",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Nachhaltigkeit?",
    answers: ["Eine Entwicklung, die vor allem auf schnelles Wirtschaftswachstum ausgerichtet ist", "Entwicklung, die Bedürfnisse der Gegenwart erfüllt, ohne zukünftige Generationen zu gefährden", "Eine Entwicklung, die ausschließlich den Schutz der natürlichen Umwelt in den Blick nimmt", "Eine Entwicklung, die sich allein auf soziale Gerechtigkeit innerhalb einer Gesellschaft richtet"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltigkeit hat ökologische, soziale und ökonomische Dimensionen."
  },
  {
    id: "q10_e_064",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was sind die SDGs?",
    answers: ["Die 17 Ziele für nachhaltige Entwicklung der Vereinten Nationen", "Die international vereinbarten Ziele zum Schutz des Klimas", "Die weltweiten Vereinbarungen zur Bekämpfung von Armut", "Die zentralen Bildungsziele der Vereinten Nationen für alle Staaten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Agenda 2030 umfasst die SDGs."
  },
  {
    id: "q10_e_065",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der ökologische Fußabdruck?",
    answers: ["Ein Maß für die insgesamt freigesetzte Menge an Kohlenstoffdioxid", "Ein Maß für den Ressourcenverbrauch und die Umweltbelastung", "Ein Maß für den durchschnittlichen Wasserverbrauch eines Haushalts", "Ein Maß für den jährlichen Stromverbrauch eines einzelnen Menschen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Er zeigt, wie viel Fläche für den Lebensstil benötigt wird."
  },
  {
    id: "q10_e_066",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Stadt und Land?",
    answers: ["Stadt: hohe Dichte und Funktionen, Land: geringere Dichte und landwirtschaftliche Prägung", "Stadt: geringere Dichte und landwirtschaftliche Prägung, Land: hohe Dichte und Funktionen", "Stadt und Land unterscheiden sich in der Geographie nicht voneinander", "Land bezeichnet ausschließlich Gebiete ohne jede menschliche Besiedlung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Grenzen sind fließend."
  },
  {
    id: "q10_e_067",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Zentrum und Peripherie?",
    answers: ["Zentrum: abhängig, Peripherie: wirtschaftlich und politisch dominant", "Zentrum und Peripherie besitzen stets denselben wirtschaftlichen Einfluss", "Zentrum: wirtschaftlich und politisch dominant, Peripherie: abhängig", "Peripherie bezeichnet nur Gebiete ohne jede Bevölkerung"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Zentrum-Peripherie-Modelle erklären räumliche Ungleichheit."
  },
  {
    id: "q10_e_068",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Industrieland und Entwicklungsland?",
    answers: ["Industrieland: niedrigerer Entwicklungsstand, Entwicklungsland: hoher Stand", "Industrieland und Entwicklungsland weisen denselben Entwicklungsstand auf", "Industrieland: hoher Entwicklungsstand, Entwicklungsland: niedrigerer Stand", "Entwicklungsland bezeichnet ausschließlich Staaten ohne Industrie"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Begriffe werden kritisch diskutiert."
  },
  {
    id: "q10_e_069",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen formalem und informellem Sektor?",
    answers: ["Formal: außerhalb der offiziellen Wirtschaft, informell: gesetzlich geregelt", "Formaler und informeller Sektor unterliegen denselben gesetzlichen Regeln", "Informeller Sektor bezeichnet nur staatlich geförderte Großunternehmen", "Formal: gesetzlich geregelt, informell: außerhalb der offiziellen Wirtschaft"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Der informelle Sektor ist in vielen Ländern bedeutsam."
  },
  {
    id: "q10_e_070",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen absoluter und relativer Lage?",
    answers: ["Absolut: geografische Position, relativ: Lage zu anderen Orten", "Absolut: Lage zu anderen Orten, relativ: geografische Position", "Absolute und relative Lage beschreiben stets denselben Ortswert", "Relative Lage bezeichnet ausschließlich die Höhe über dem Meeresspiegel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind für Standortbewertungen wichtig."
  },
  {
    id: "q10_e_071",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Verdichtung und Ausdünnung?",
    answers: ["Verdichtung: Abnahme der Dichte, Ausdünnung: Zunahme", "Verdichtung und Ausdünnung beschreiben denselben Bevölkerungsprozess", "Verdichtung: Zunahme der Dichte, Ausdünnung: Abnahme", "Ausdünnung bezeichnet allein den Bau neuer Wohngebäude"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Prozesse prägen Raumstrukturen."
  },
  {
    id: "q10_e_072",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Binnen- und Außenmigration?",
    answers: ["Binnen: innerhalb eines Staates, Außen: über Staatsgrenzen", "Binnen: über Staatsgrenzen, Außen: innerhalb eines Staates", "Binnen- und Außenmigration bezeichnen genau denselben Wanderungstyp", "Außenmigration bezeichnet nur den Umzug innerhalb derselben Stadt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Formen haben unterschiedliche Ursachen und Folgen."
  },
  {
    id: "q10_e_073",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Flucht und Arbeitsmigration?",
    answers: ["Flucht und Arbeitsmigration haben stets dieselben Beweggründe", "Arbeitsmigration erfolgt ausschließlich durch staatlichen Zwang", "Flucht: erzwungen, Arbeitsmigration: oft ökonomisch motiviert", "Flucht: ökonomisch motiviert, Arbeitsmigration: erzwungen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Unterscheidung ist rechtlich relevant."
  },
  {
    id: "q10_e_074",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Metropole und Megacity?",
    answers: ["Metropole und Megacity bezeichnen exakt denselben Stadttyp", "Metropole: funktional bedeutend, Megacity: Größenkriterium", "Metropole: Größenkriterium, Megacity: funktional bedeutend", "Megacity bezeichnet nur Städte mit besonderer politischer Funktion"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Nicht jede Megacity ist eine globale Metropole."
  },
  {
    id: "q10_e_075",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Nachhaltigkeit und Wachstum?",
    answers: ["Wachstum bezeichnet ausschließlich den Rückgang wirtschaftlicher Leistung", "Nachhaltigkeit und Wachstum bedeuten in der Wirtschaft dasselbe", "Nachhaltigkeit: quantitative Zunahme, Wachstum: langfristig tragfähig", "Nachhaltigkeit: langfristig tragfähig, Wachstum: quantitative Zunahme"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltiges Wachstum ist ein politisches Ziel."
  },
  {
    id: "q10_e_076",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen lokal und global?",
    answers: ["Global bezeichnet nur Vorgänge innerhalb eines einzelnen Kontinents", "Lokal und global beschreiben denselben räumlichen Maßstab", "Lokal: weltweit, global: örtlich begrenzt", "Lokal: örtlich begrenzt, global: weltweit"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Viele Probleme haben lokale und globale Dimensionen."
  },
  {
    id: "q10_e_077",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Ressourcen und Reserven?",
    answers: ["Ressourcen und Reserven bezeichnen exakt dieselbe Rohstoffmenge", "Ressourcen: wirtschaftlich nutzbar, Reserven: vorhanden", "Ressourcen: vorhanden, Reserven: wirtschaftlich nutzbar", "Reserven bezeichnen ausschließlich bereits verbrauchte Rohstoffe"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Reserven sind ein Teil der Ressourcen."
  },
  {
    id: "q10_e_078",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen regenerativen und nicht-regenerativen Ressourcen?",
    answers: ["Regenerativ: erneuern sich, nicht-regenerativ: endlich", "Regenerativ: endlich, nicht-regenerativ: erneuern sich", "Nicht-regenerative Ressourcen erneuern sich innerhalb weniger Jahre", "Regenerative und nicht-regenerative Ressourcen sind gleichermaßen unbegrenzt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossile Energieträger sind nicht-regenerativ."
  },
  {
    id: "q10_e_079",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Intensiv- und Extensivlandwirtschaft?",
    answers: ["Intensiv: geringer Input pro Fläche, Extensiv: hoher Input", "Extensivlandwirtschaft bezeichnet ausschließlich den Anbau in Gewächshäusern", "Intensiv: hoher Input pro Fläche, Extensiv: geringer Input", "Intensive und extensive Landwirtschaft nutzen stets denselben Input"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Formen haben unterschiedliche Umweltwirkungen."
  },
  {
    id: "q10_e_080",
    category: "k10_erdkunde",
    topic: "bevoelkerung",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Monokultur und Mischkultur?",
    answers: ["Mischkultur ist immer Monokultur", "Monokultur und Mischkultur bezeichnen dieselbe Anbauform", "Mischkultur bezeichnet ausschließlich den Anbau ohne jede Pflanze", "Monokultur: eine Art, Mischkultur: mehrere Arten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Monokulturen können anfälliger für Schädlinge sein."
  },

  // ================================================================
  // 3. RÄUMLICHE STRUKTUREN, KARTEN & METHODEN (30 Fragen)
  // ================================================================
  {
    id: "q10_e_081",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Atlas?",
    answers: ["Ein digitales Bild der Erde, aufgenommen aus dem Weltall", "Ein Buch mit Karten und geographischen Informationen", "Eine einzelne Karte ohne weitere Zusatzinformationen", "Ein maßstabsgetreues Modell der Erde in Kugelform"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Atlanten sind wichtige Arbeitsmittel."
  },
  {
    id: "q10_e_082",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Maßstab einer Karte?",
    answers: ["Das Verhältnis zwischen Kartenstrecke und realer Strecke", "Die tatsächliche Größe des Papierblatts, auf dem die Karte gedruckt", "Die Auswahl der auf einer Karte verwendeten Farben und Muster", "Die Übersicht der Kartensymbole und ihrer jeweiligen Bedeutung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Maßstab ermöglicht Entfernungsberechnungen."
  },
  {
    id: "q10_e_083",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine Legende?",
    answers: ["Der Pfeil, der die Nordrichtung auf der Karte zeigt", "Die Überschrift, die das Thema der Karte benennt", "Die Angabe des Verhältnisses zwischen Karte und Wirklichkeit", "Die Erklärung der Zeichen und Farben auf einer Karte"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ohne Legende ist eine Karte schwer lesbar."
  },
  {
    id: "q10_e_084",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine topographische Karte?",
    answers: ["Eine Karte, die ausschließlich Temperatur und Niederschlag zeigt", "Eine Karte, die nur ein einzelnes Thema wie Bevölkerung zeigt", "Eine Karte, die Gelände und Infrastruktur detailliert darstellt", "Eine Karte, die wirtschaftliche Strukturen einer Region zeigt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Topographische Karten dienen der Orientierung."
  },
  {
    id: "q10_e_085",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine thematische Karte?",
    answers: ["Eine Sammlung mehrerer Karten in einem Buch", "Eine Karte, die ein bestimmtes Thema darstellt", "Ein detaillierter Plan einer einzelnen Stadt", "Eine Karte mit genauer Darstellung von Gelände"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Klimakarten, Bevölkerungskarten."
  },
  {
    id: "q10_e_086",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist GIS?",
    answers: ["Geographisches Informationssystem zur Analyse räumlicher Daten", "Ein Flugkörper zur Beobachtung der Erdoberfläche aus dem Weltraum heraus", "Eine einzelne gedruckte Karte eines geografisch klar begrenzten Gebiets", "Eine gebundene Sammlung mehrerer Karten und statistischer Tabellen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "GIS verbindet Daten mit räumlichen Positionen."
  },
  {
    id: "q10_e_087",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Fernerkundung?",
    answers: ["Die zeichnerische Darstellung von Gelände und Höhenlinien auf Papier", "Die Gewinnung von Informationen aus der Ferne, z. B. per Satellit", "Die direkte Untersuchung eines Gebiets durch persönliche Begehung vor Ort", "Die mündliche Erhebung von Daten mithilfe von Interviews direkt vor Ort"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Satellitendaten sind zentral für Umweltbeobachtung."
  },
  {
    id: "q10_e_088",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Profil?",
    answers: ["Ein Schnitt durch das Gelände zur Darstellung von Höhen und Strukturen", "Eine tabellarische Übersicht verschiedener statistischer Messwerte eines Gebiets", "Eine flächenhafte Darstellung eines gesamten Gebiets aus der Vogelperspektive", "Eine grafische Darstellung von Zahlen in Form eines einfachen Balkendiagramms"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Profile verdeutlichen Relief und Nutzung."
  },
  {
    id: "q10_e_089",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine Klimazone?",
    answers: ["Ein Gebiet mit gleicher Vegetation", "Ein Bereich mit einheitlicher Uhrzeit", "Ein Gebiet mit ähnlicher Wirtschaft", "Ein Gebiet mit ähnlichem Klima"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Klimazonen folgen grob den Breitengraden."
  },
  {
    id: "q10_e_090",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist eine Vegetationszone?",
    answers: ["Ein Bereich mit einer einheitlichen Uhrzeit auf der ganzen Erde", "Ein Gebiet mit ähnlichem Klima während des gesamten Jahres", "Ein Gebiet mit charakteristischer natürlicher Vegetation", "Ein Gebiet mit vergleichbarer wirtschaftlicher Nutzung des Bodens"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Vegetationszonen hängen eng mit dem Klima zusammen."
  },
  {
    id: "q10_e_091",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Längengrad?",
    answers: ["Die Angabe der Höhe eines Ortes über dem Meeresspiegel", "Die Angabe der Position ost-westlich vom Nullmeridian", "Die Angabe der Position nord-südlich vom Äquator", "Die Angabe der Entfernung zwischen zwei Städten"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Längengrade laufen von Pol zu Pol."
  },
  {
    id: "q10_e_092",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Breitengrad?",
    answers: ["Die Angabe der Position ost-westlich vom Nullmeridian", "Die Angabe der Höhe eines Ortes über dem Meeresspiegel", "Die Angabe der Position nord-südlich vom Äquator", "Die Angabe der Entfernung zwischen zwei Orten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Breitengrade verlaufen parallel zum Äquator."
  },
  {
    id: "q10_e_093",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Äquator?",
    answers: ["Der Längenkreis, von dem aus die Zeitzonen gezählt werden", "Der Breitenkreis, an dem die Sonne im Sommer im Zenit steht", "Der größte Breitenkreis, der die Erde in Nord und Süd teilt", "Der Breitenkreis, jenseits dessen die Polarnacht auftritt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Äquator liegt bei 0° Breite."
  },
  {
    id: "q10_e_094",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Nullmeridian?",
    answers: ["Der Breitenkreis, jenseits dessen im Winter die Polarnacht eintritt", "Der Breitenkreis, an dem im Sommer die Sonne senkrecht im Zenit steht", "Der Längenkreis durch Greenwich, von dem aus Länge gemessen wird", "Der größte Breitenkreis, der die Erde in zwei gleiche Hälften teilt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Er definiert 0° Länge."
  },
  {
    id: "q10_e_095",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Wendekreis?",
    answers: ["Der Längenkreis, von dem aus die Zeitzonen der Erde gezählt werden", "Der größte Breitenkreis, der die Erde in eine Nord- und Südhälfte teilt", "Der Breitenkreis, jenseits dessen im Winter die Polarnacht eintritt", "Der Breitenkreis, an dem die Sonne zur Sonnenwende im Zenit steht"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Nördlicher und südlicher Wendekreis begrenzen die Tropen."
  },
  {
    id: "q10_e_096",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist ein Polarkreis?",
    answers: ["Der Breitenkreis, jenseits dessen Polarnacht und Polartag auftreten", "Der Längenkreis, von dem aus die weltweiten Zeitzonen gezählt werden", "Der größte Breitenkreis, der die Erde in eine Nord- und Südhälfte teilt", "Der Breitenkreis, an dem zur Sonnenwende die Sonne senkrecht im Zenit steht"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Nördlicher und südlicher Polarkreis begrenzen die Polarzonen."
  },
  {
    id: "q10_e_097",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Karte und Globus?",
    answers: ["Karte: dreidimensional und verzerrungsfrei, Globus: flache Darstellung mit Verzerrungen", "Karte und Globus stellen die Erde stets völlig verzerrungsfrei dar", "Karte: flache Darstellung mit Verzerrungen, Globus: dreidimensional und verzerrungsfrei", "Ein Globus zeigt die Erde nur als zweidimensionales, flaches Abbild"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Kartenprojektionen verzerren Flächen, Winkel oder Entfernungen."
  },
  {
    id: "q10_e_098",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen absolute und relative Höhe?",
    answers: ["Absolut: über der Umgebung, relativ: über dem Meeresspiegel", "Absolute und relative Höhe beziehen sich stets auf denselben Bezugspunkt", "Relative Höhe bezeichnet ausschließlich die Entfernung zum Äquator", "Absolut: über dem Meeresspiegel, relativ: über der Umgebung"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Angaben sind für Reliefbeschreibungen wichtig."
  },
  {
    id: "q10_e_099",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen qualitativer und quantitativer Karte?",
    answers: ["Qualitativ: Arten von Erscheinungen, quantitativ: Mengen und Werte", "Qualitativ: Mengen und Werte, quantitativ: Arten von Erscheinungen", "Qualitative und quantitative Karten zeigen stets dieselben Informationen", "Quantitative Karten stellen ausschließlich politische Grenzen dar"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Kartentypen dienen unterschiedlichen Zwecken."
  },
  {
    id: "q10_e_100",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Isolinie und Isolinie-freier Darstellung?",
    answers: ["Isolinien nutzen Flächen oder Punkte, andere Darstellungen verbinden gleiche Werte", "Isolinien und flächenhafte Darstellungen zeigen grundsätzlich dieselben Werte", "Isolinien verbinden ausschließlich Orte mit identischer Bevölkerungszahl", "Isolinien verbinden gleiche Werte, andere Darstellungen nutzen Flächen oder Punkte"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Isothermen und Isohyeten sind Beispiele für Isolinien."
  },
  {
    id: "q10_e_101",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen physischer und politischer Karte?",
    answers: ["Physisch: Grenzen und Staaten, politisch: Naturraum", "Physisch: Naturraum, politisch: Grenzen und Staaten", "Physische und politische Karten zeigen stets denselben Inhalt", "Politische Karten stellen ausschließlich Gebirge und Flüsse dar"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Kartentypen ergänzen sich."
  },
  {
    id: "q10_e_102",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Groß- und Kleinmaßstab?",
    answers: ["Großmaßstab: detailliert, Kleinmaßstab: Überblick", "Großmaßstab: Überblick, Kleinmaßstab: detailliert", "Kleinmaßstab bezeichnet ausschließlich sehr große Papierformate", "Groß- und Kleinmaßstab zeigen stets dieselbe Detailgenauigkeit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1:25.000 ist großmaßstäbig, 1:1.000.000 kleinmaßstäbig."
  },
  {
    id: "q10_e_103",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Generalisierung und Detailtreue?",
    answers: ["Detailtreue ist immer generalisiert", "Generalisierung: Vereinfachung, Detailtreue: genaue Wiedergabe", "Generalisierung und Detailtreue bedeuten in der Kartografie dasselbe", "Detailtreue bezeichnet ausschließlich die Farbwahl einer Karte"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Karten generalisieren zwangsläufig."
  },
  {
    id: "q10_e_104",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Projektion und Abbildung?",
    answers: ["Projektion und Abbildung bezeichnen exakt denselben kartografischen Vorgang", "Eine Projektion beschreibt nur die farbliche Gestaltung einer Karte", "Projektion: mathematische Übertragung auf die Ebene, Abbildung: Darstellung", "Projektion: Darstellung, Abbildung: mathematische Übertragung auf die Ebene"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Kartenprojektionen verzerren unvermeidlich."
  },
  {
    id: "q10_e_105",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Raum und Region?",
    answers: ["Raum: allgemeiner Begriff, Region: abgegrenzter Teilraum", "Region ist immer Raum", "Raum: abgegrenzter Teilraum, Region: allgemeiner Begriff", "Region bezeichnet ausschließlich einen gesamten Kontinent"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Regionen werden nach Kriterien abgegrenzt."
  },
  {
    id: "q10_e_106",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Struktur und Prozess?",
    answers: ["Struktur: Veränderung, Prozess: Zustand", "Struktur und Prozess beschreiben stets denselben Sachverhalt", "Ein Prozess bezeichnet ausschließlich einen dauerhaft festen Zustand", "Struktur: Zustand, Prozess: Veränderung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Geographie untersucht beide."
  },
  {
    id: "q10_e_107",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Analyse und Bewertung?",
    answers: ["Analyse und Bewertung bezeichnen in der Geographie denselben Arbeitsschritt", "Analyse: Zerlegung und Beschreibung, Bewertung: Urteil nach Kriterien", "Eine Bewertung erfolgt ausschließlich ohne jegliche Kriterien", "Analyse: Urteil nach Kriterien, Bewertung: Zerlegung und Beschreibung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Kompetenzen sind im Lehrplan verankert."
  },
  {
    id: "q10_e_108",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Beschreibung und Erklärung?",
    answers: ["Beschreibung: Was?, Erklärung: Warum?", "Beschreibung und Erklärung stellen stets dieselbe Frage", "Beschreibung: Warum?, Erklärung: Was?", "Eine Erklärung fragt ausschließlich nach dem Ort eines Ereignisses"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Erklärung erfordert Kausalzusammenhänge."
  },
  {
    id: "q10_e_109",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen lokal und regional?",
    answers: ["Lokal und global beziehen sich stets auf denselben Maßstab", "Lokal: kleinräumig, regional: größerer Maßstab", "Lokal: größerer Maßstab, regional: kleinräumig", "Regional bezeichnet ausschließlich ein einzelnes Grundstück"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Maßstabsebenen sind zentral in der Geographie."
  },
  {
    id: "q10_e_110",
    category: "k10_erdkunde",
    topic: "methoden",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Naturraum und Kulturraum?",
    answers: ["Naturraum: natürliche Ausstattung, Kulturraum: durch Menschen geprägt", "Naturraum: durch Menschen geprägt, Kulturraum: natürliche Ausstattung", "Naturraum und Kulturraum bezeichnen stets denselben unberührten Bereich", "Kulturraum bezeichnet ausschließlich Gebiete ohne jede Besiedlung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind eng miteinander verbunden."
  },

  // ================================================================
  // 4. GLOBALE HERAUSFORDERUNGEN & NACHHALTIGKEIT (40 Fragen)
  // ================================================================
  {
    id: "q10_e_111",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Klimawandel?",
    answers: ["Die langfristige Veränderung des globalen Klimas", "Der tägliche Wechsel zwischen warmem und kaltem Wetter", "Die kurzfristige Schwankung der Temperatur an einem Ort", "Der regelmäßige Wechsel der vier Jahreszeiten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Aktuell vor allem durch Treibhausgase verursacht."
  },
  {
    id: "q10_e_112",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist CO₂?",
    answers: ["Methan, ein Gas aus der Viehhaltung und Landwirtschaft", "Stickstoff, der größte Bestandteil der Luft", "Sauerstoff, ein für die Atmung notwendiges Gas", "Kohlenstoffdioxid, ein wichtiges Treibhausgas"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "CO₂ entsteht bei Verbrennung und Atmung."
  },
  {
    id: "q10_e_113",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Treibhauseffekt?",
    answers: ["Die schützende Schicht aus Ozon in der Stratosphäre", "Die Erwärmung der Atmosphäre durch Spurengase", "Die Abkühlung der Erde durch aufsteigende Wolken", "Die Bildung von Wolken durch feuchte, warme Luft"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ohne natürlichen Treibhauseffekt wäre die Erde zu kalt."
  },
  {
    id: "q10_e_114",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Meeresspiegelanstieg?",
    answers: ["Das Ansteigen des Meeresspiegels durch Erwärmung und Eisschmelze", "Die großräumige, dauerhafte Bewegung von Wassermassen im offenen Ozean", "Die regelmäßige Auf- und Abbewegung des Wassers unmittelbar an der Küste", "Der tägliche Wechsel zwischen Ebbe und Flut entlang einer flachen Küste"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Er bedroht Küsten und Inselstaaten."
  },
  {
    id: "q10_e_115",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Biodiversitätsverlust?",
    answers: ["Der Rückgang der Artenvielfalt und der Vielfalt von Ökosystemen", "Das vollständige Aussterben einer einzelnen, stark bedrohten Tierart", "Die zunehmende Belastung natürlicher Ökosysteme durch Schadstoffe im Boden", "Die großflächige Rodung von Wäldern zur Gewinnung von neuem Ackerland"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ursachen sind Habitatverlust, Klimawandel und Übernutzung."
  },
  {
    id: "q10_e_116",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Abholzung?",
    answers: ["Nur die nachhaltige Forstwirtschaft", "Nur die Aufforstung", "Die großflächige Rodung von Wäldern", "Nur die Naturschutz"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Abholzung trägt zum Klimawandel und Artenverlust bei."
  },
  {
    id: "q10_e_117",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Desertifikation?",
    answers: ["Die Zunahme des Anteils der Bevölkerung in Städten", "Die künstliche Bewässerung von trockenem Ackerland", "Die Ausbreitung von Wüsten und die Verödung von Land", "Das gezielte Anpflanzen von Wäldern auf freien Flächen"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Ursachen sind Klima und Übernutzung."
  },
  {
    id: "q10_e_118",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Wasserknappheit?",
    answers: ["Ein Zustand, in dem an einem Ort deutlich zu viel Wasser vorhanden ist", "Ein Zustand, in dem nicht genügend Wasser für Bedürfnisse verfügbar ist", "Ein Zustand, in dem Wasser unnötig und in großen Mengen verschwendet wird", "Ein Zustand, in dem verfügbares Wasser stark durch Schadstoffe belastet ist"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wasserknappheit betrifft viele Regionen."
  },
  {
    id: "q10_e_119",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Ernährungssicherheit?",
    answers: ["Die gerechte Verteilung von Nahrungsmitteln zwischen Regionen", "Die ausreichende Produktion von Nahrungsmitteln in einem Land", "Der internationale Handel mit landwirtschaftlichen Produkten", "Der Zugang aller Menschen zu ausreichend und sicherer Nahrung"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ernährungssicherheit ist ein globales Ziel."
  },
  {
    id: "q10_e_120",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der ökologische Fußabdruck?",
    answers: ["Ein Maß für den durchschnittlichen Wasserverbrauch eines Haushalts", "Ein Maß für die insgesamt freigesetzte Menge an Kohlenstoffdioxid", "Ein Maß für den Ressourcenverbrauch und die Umweltbelastung", "Ein Maß für den jährlichen Stromverbrauch eines einzelnen Menschen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Er zeigt die Belastung der Erde."
  },
  {
    id: "q10_e_121",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der CO₂-Fußabdruck?",
    answers: ["Ein Maß für die Treibhausgasemissionen einer Person oder Tätigkeit", "Ein Maß für den gesamten Ressourcenverbrauch eines Landes über ein Jahr", "Ein Maß für den täglichen Wasserverbrauch eines durchschnittlichen Haushalts", "Ein Maß für den jährlichen Stromverbrauch eines einzelnen Industriebetriebs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Er hilft, Emissionen zu vergleichen."
  },
  {
    id: "q10_e_122",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Kreislaufwirtschaft?",
    answers: ["Ein Wirtschaftssystem, das Rohstoffe nur einmalig nutzt und danach entsorgt", "Ein Wirtschaftssystem, das vor allem auf ständigem Neukauf von Produkten beruht", "Ein Wirtschaftssystem, das Ressourcen möglichst lange nutzt und Abfälle minimiert", "Ein Wirtschaftssystem, das sich ausschließlich auf klassische Industriegüter stützt"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Kreislaufwirtschaft ist ein Nachhaltigkeitskonzept."
  },
  {
    id: "q10_e_123",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Energiewende?",
    answers: ["Der weitere Ausbau bestehender Kohle- und Erdgaskraftwerke im Land", "Der Umbau der Energieversorgung hin zu erneuerbaren Energien", "Die schrittweise Reduzierung des gesamten Stromverbrauchs im Land", "Der Bau neuer Kraftwerke zur Nutzung von klassischer Kernenergie"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Energiewende ist ein zentrales Klimaschutzinstrument."
  },
  {
    id: "q10_e_124",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Klimaschutz?",
    answers: ["Maßnahmen zur Beobachtung des Wetters", "Maßnahmen zur Anpassung an Klimafolgen", "Maßnahmen zur Erforschung vergangener Klimadaten", "Maßnahmen zur Begrenzung des Klimawandels"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Klimaschutz umfasst Vermeidung von Emissionen."
  },
  {
    id: "q10_e_125",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist Klimaanpassung?",
    answers: ["Maßnahmen zur wissenschaftlichen Erforschung des Klimawandels", "Maßnahmen zur direkten Begrenzung des Klimawandels", "Maßnahmen zur Anpassung an bereits eintretende Klimafolgen", "Maßnahmen zur vollständigen Vermeidung von Emissionen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Anpassung und Vermeidung ergänzen sich."
  },
  {
    id: "q10_e_126",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Mitigation und Adaptation?",
    answers: ["Beide sind identisch", "Mitigation: Vermeidung, Adaptation: Anpassung", "Adaptation ist immer Mitigation", "Mitigation bedeutet ausschließlich technische Wetterbeobachtung"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Strategien sind nötig."
  },
  {
    id: "q10_e_127",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen erneuerbaren und fossilen Energien?",
    answers: ["Beide sind identisch", "Erneuerbar ist immer fossil", "Fossile Energien erneuern sich innerhalb weniger Jahrzehnte von selbst", "Erneuerbar: regenerieren sich, fossil: endlich und emissionsintensiv"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Sonne, Wind und Wasser sind erneuerbar."
  },
  {
    id: "q10_e_128",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen lokal und global beim Klimawandel?",
    answers: ["Global ist immer eine bloße Summe vieler unabhängiger lokaler Ereignisse", "Lokal: regionale Auswirkungen, global: weltweite Ursachen und Folgen", "Lokale und globale Wirkungen des Klimawandels sind grundsätzlich stets identisch", "Globale Auswirkungen betreffen ausschließlich einzelne, klar begrenzte Küstenorte"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Klimawandel verbindet lokale und globale Ebenen."
  },
  {
    id: "q10_e_129",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Verursacher und Betroffenem beim Klimawandel?",
    answers: ["Verursacher: emittiert stark, Betroffener: leidet unter Folgen", "Verursacher: leidet unter Folgen, Betroffener: emittiert stark", "Verursacher und Betroffener tragen stets dieselbe Verantwortung", "Ein Betroffener bezeichnet ausschließlich staatliche Institutionen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gerechtigkeit ist ein zentrales Thema."
  },
  {
    id: "q10_e_130",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen präventivem und reaktivem Katastrophenschutz?",
    answers: ["Präventiver und reaktiver Katastrophenschutz erfolgen stets gleichzeitig", "Reaktiver Katastrophenschutz bezeichnet ausschließlich vorbeugende Bauvorschriften", "Präventiv: Reaktion nach dem Ereignis, reaktiv: Vorsorge", "Präventiv: Vorsorge, reaktiv: Reaktion nach dem Ereignis"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Vorsorge mindert Schäden."
  },
  {
    id: "q10_e_131",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Naturereignis und Naturkatastrophe?",
    answers: ["Ereignis: natürlicher Prozess, Katastrophe: mit schweren Schäden für Menschen", "Ereignis: mit schweren Schäden für Menschen, Katastrophe: natürlicher Prozess", "Naturereignis und Naturkatastrophe bezeichnen stets denselben Vorgang", "Eine Naturkatastrophe entsteht ausschließlich durch menschliches Handeln"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verletzlichkeit entscheidet über das Ausmaß."
  },
  {
    id: "q10_e_132",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Vulnerabilität und Resilienz?",
    answers: ["Vulnerabilität: Widerstandsfähigkeit, Resilienz: Verwundbarkeit", "Resilienz beschreibt ausschließlich die Stärke eines Erdbebens", "Vulnerabilität und Resilienz bezeichnen dieselbe Eigenschaft eines Systems", "Vulnerabilität: Verwundbarkeit, Resilienz: Widerstandsfähigkeit"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Konzepte sind zentral für Risikomanagement."
  },
  {
    id: "q10_e_133",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Exposition und Empfindlichkeit?",
    answers: ["Exposition: Anfälligkeit, Empfindlichkeit: Ausgesetztsein", "Exposition und Empfindlichkeit bezeichnen dasselbe Risikomerkmal", "Exposition: Ausgesetztsein, Empfindlichkeit: Anfälligkeit", "Empfindlichkeit beschreibt ausschließlich die Lage eines Ortes zum Meer"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Beide bestimmen die Vulnerabilität."
  },
  {
    id: "q10_e_134",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen nachhaltiger und konventioneller Landwirtschaft?",
    answers: ["Beide sind identisch", "Nachhaltig: ressourcenschonend, konventionell: oft intensiver und chemiebasierter", "Konventionelle Landwirtschaft verzichtet grundsätzlich auf jeden Chemieeinsatz", "Nachhaltig: oft intensiver und chemiebasierter, konventionell: ressourcenschonend"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltige Landwirtschaft schont Böden und Biodiversität."
  },
  {
    id: "q10_e_135",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen fairer und unfairer Handelsbeziehung?",
    answers: ["Beide sind identisch", "Fair: gerechte Preise und Bedingungen, unfair: Ausbeutung", "Unfairer Handel bezeichnet ausschließlich den Handel innerhalb der EU", "Fair: Ausbeutung, unfair: gerechte Preise und Bedingungen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Fairer Handel ist ein Nachhaltigkeitsansatz."
  },
  {
    id: "q10_e_136",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen lokalem und globalem Handeln?",
    answers: ["Beide sind identisch", "Lokal ist immer global", "Globales Handeln bezeichnet ausschließlich Entscheidungen einzelner Familien", "Lokal: vor Ort, global: weltweit"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Ebenen sind für Nachhaltigkeit wichtig."
  },
  {
    id: "q10_e_137",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen individueller und struktureller Verantwortung?",
    answers: ["Individuell: persönliches Handeln, strukturell: gesellschaftliche Rahmenbedingungen", "Beide sind identisch", "Individuell: gesellschaftliche Rahmenbedingungen, strukturell: persönliches Handeln", "Strukturelle Verantwortung betrifft ausschließlich einzelne Privatpersonen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Ebenen sind für Veränderungen nötig."
  },
  {
    id: "q10_e_138",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Effizienz und Suffizienz?",
    answers: ["Effizienz: mehr mit weniger, Suffizienz: maßvoller Konsum", "Suffizienz bedeutet ausschließlich die Steigerung der Produktion", "Beide sind identisch", "Effizienz: maßvoller Konsum, Suffizienz: mehr mit weniger"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Strategien ergänzen sich."
  },
  {
    id: "q10_e_139",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen technischer und sozialer Innovation?",
    answers: ["Soziale Innovation bezeichnet ausschließlich neue technische Geräte", "Technisch: neue Technologien, sozial: neue Verhaltens- und Organisationsformen", "Technische und soziale Innovation bezeichnen stets denselben Wandel", "Technisch: neue Verhaltens- und Organisationsformen, sozial: neue Technologien"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind für Nachhaltigkeit relevant."
  },
  {
    id: "q10_e_140",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Planetaren Grenzen und Nachhaltigkeitszielen?",
    answers: ["Planetare Grenzen und SDGs bezeichnen stets dasselbe Rahmenwerk", "SDGs beschreiben ausschließlich naturwissenschaftliche Belastungsgrenzen", "Planetare Grenzen: gesellschaftliche Ziele, SDGs: ökologische Limits", "Planetare Grenzen: ökologische Limits, SDGs: gesellschaftliche Ziele"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Beide Konzepte rahmen nachhaltige Entwicklung."
  },
  {
    id: "q10_e_141",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Umweltverschmutzung und Ressourcenverbrauch?",
    answers: ["Umweltverschmutzung und Ressourcenverbrauch bezeichnen denselben Vorgang", "Ressourcenverbrauch bezeichnet ausschließlich die Verschmutzung von Gewässern", "Verschmutzung: Nutzung von Ressourcen, Verbrauch: Belastung", "Verschmutzung: Belastung, Verbrauch: Nutzung von Ressourcen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide belasten die Umwelt."
  },
  {
    id: "q10_e_142",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen linearer und zirkulärer Wirtschaft?",
    answers: ["Beide sind identisch", "Linear: nehmen–herstellen–wegwerfen, zirkulär: wiederverwenden und recyceln", "Zirkuläre Wirtschaft bezeichnet ausschließlich den einmaligen Rohstoffabbau", "Linear: wiederverwenden und recyceln, zirkulär: nehmen–herstellen–wegwerfen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Kreislaufwirtschaft ist nachhaltiger."
  },
  {
    id: "q10_e_143",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen anthropogen und natürlich?",
    answers: ["Natürlich ist immer anthropogen", "Beide sind identisch", "Anthropogen: ohne menschlichen Einfluss, natürlich: durch Menschen verursacht", "Anthropogen: durch Menschen verursacht, natürlich: ohne menschlichen Einfluss"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Der aktuelle Klimawandel ist weitgehend anthropogen."
  },
  {
    id: "q10_e_144",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen kurzfristig und langfristig in der Nachhaltigkeit?",
    answers: ["Beide sind identisch", "Kurzfristige und langfristige Nachhaltigkeit betrachten denselben Zeitraum", "Langfristige Nachhaltigkeit betrachtet ausschließlich das laufende Jahr", "Kurzfristig: unmittelbare Wirkungen, langfristig: Generationenperspektive"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltigkeit denkt langfristig."
  },
  {
    id: "q10_e_145",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen globalem Norden und globalem Süden?",
    answers: ["Norden: oft wohlhabender, Süden: oft weniger entwickelt", "Norden: oft weniger entwickelt, Süden: oft wohlhabender", "Globaler Norden und Süden weisen stets denselben Entwicklungsstand auf", "Globaler Süden bezeichnet ausschließlich Staaten der südlichen Hemisphäre"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Begriffe sind umstritten und vereinfachend."
  },
  {
    id: "q10_e_146",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Umweltgerechtigkeit und Klimagerechtigkeit?",
    answers: ["Umweltgerechtigkeit und Klimagerechtigkeit bezeichnen exakt dasselbe rechtliche Prinzip", "Umweltgerechtigkeit: faire Verteilung von Klimalasten, Klimagerechtigkeit: fairer Zugang zu Umweltgütern", "Klimagerechtigkeit bezeichnet ausschließlich technische Maßnahmen des Küstenschutzes", "Umweltgerechtigkeit: fairer Zugang zu Umweltgütern, Klimagerechtigkeit: faire Verteilung von Klimalasten"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Beide fordern gerechte Lösungen."
  },
  {
    id: "q10_e_147",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Planetary Boundaries und SDGs?",
    answers: ["Planetary Boundaries: umfassende Entwicklungsziele, SDGs: ökologische Grenzen", "Planetary Boundaries: ökologische Grenzen, SDGs: umfassende Entwicklungsziele", "Planetary Boundaries und SDGs bezeichnen dasselbe internationale Abkommen", "SDGs beschreiben ausschließlich naturwissenschaftliche Belastungsgrenzen der Erde"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Beide Konzepte ergänzen sich."
  },
  {
    id: "q10_e_148",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen Vorsorgeprinzip und Nachsorgeprinzip?",
    answers: ["Vorsorge: nach Schäden reagieren, Nachsorge: vorausschauend handeln", "Vorsorge- und Nachsorgeprinzip beschreiben stets denselben Handlungszeitpunkt", "Das Nachsorgeprinzip bezeichnet ausschließlich vorbeugende Gesetzgebung", "Vorsorge: vorausschauend handeln, Nachsorge: nach Schäden reagieren"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Vorsorge ist zentral für Nachhaltigkeit."
  },
  {
    id: "q10_e_149",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist der Unterschied zwischen starker und schwacher Nachhaltigkeit?",
    answers: ["Stark: Naturkapital unersetzbar, schwach: Naturkapital durch anderes ersetzbar", "Starke und schwache Nachhaltigkeit behandeln Naturkapital stets völlig identisch", "Schwache Nachhaltigkeit lehnt jeden Ersatz von Naturkapital grundsätzlich ab", "Stark bedeutet, dass Naturkapital jederzeit beliebig ersetzbar sein muss"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Die Debatte prägt Nachhaltigkeitsstrategien."
  },
  {
    id: "q10_e_150",
    category: "k10_erdkunde",
    topic: "nachhaltigkeit",
    area: "schule",
    grade: 10,
    subject: "erdkunde",
    question: "Was ist die zentrale Aufgabe der Geographie im 21. Jahrhundert?",
    answers: ["Historische Jahreszahlen und wichtige Ereignisse zuverlässig auswendig lernen", "Räumliche Zusammenhänge verstehen und nachhaltige Lösungen mitgestalten", "Politische Grenzen und Hauptstädte aller Staaten der Erde korrekt benennen", "Naturphänomene ausschließlich sachlich und vollkommen wertfrei beschreiben"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Geographie verbindet Natur und Gesellschaft."
  },
  {"id":"k10ek101","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Deutschland Kontinent?","answers":["Afrika","Europa","Asien","Australien"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Europa."},
  {"id":"k10ek102","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Hauptstadt FR?","answers":["Lyon","Paris","Marseille","Nizza"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Paris."},
  {"id":"k10ek103","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Äquator Breite?","answers":["90°","0°","180°","45°"],"correct":1,"difficulty":"mittel","points":10,"explanation":"0°."},
  {"id":"k10ek104","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Nachhaltigkeit: …","answers":["verbrauchen","schonend nutzen","nur Export","kein Wasser"],"correct":1,"difficulty":"mittel","points":10,"explanation":"schonen."},
  {"id":"k10ek105","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Urbanisierung = …","answers":["Landwirtschaft","Verstädterung","Wald","Eiszeit"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Stadt."},
  {"id":"k10ek106","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Plattentektonik erklärt …","answers":["Wetter","Erdbeben/Vulkane","Mode","Sprache"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Platten."},
  {"id":"k10ek107","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Migration pull?","answers":["Krieg","Jobs Ziel","Katastrophe","Verfolgung"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Anziehung."},
  {"id":"k10ek108","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Treibhausgas u. a. …","answers":["O₂","CO₂","N₂","He"],"correct":1,"difficulty":"mittel","points":10,"explanation":"CO₂."},
  {"id":"k10ek109","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"1:100000 → 1 cm = …","answers":["1 m","1 km","100 km","10 m"],"correct":1,"difficulty":"mittel","points":10,"explanation":"1 km."},
  {"id":"k10ek110","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Rhein → …","answers":["Ostsee","Nordsee","Adria","Donau"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Nordsee."},
  {"id":"k10ek111","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Wüste: wenig …","answers":["Sand","Niederschlag","Sonne","Wind"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Regen."},
  {"id":"k10ek112","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Globalisierung = …","answers":["Isolation","Verflechtung","Lokal","Autarkie"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Netz."},
  {"id":"k10ek113","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"HDI u. a. …","answers":["Militär","Bildung/Gesundheit/Einkommen","CO₂","nur BIP"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Entwicklung."},
  {"id":"k10ek114","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Desertifikation = …","answers":["Aufforstung","Wüstenbildung","Gletscher","Stadt"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Degradation."},
  {"id":"k10ek115","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Alpen = …","answers":["Tiefland","Hochgebirge","Inseln","Wüste"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Gebirge."},
  {"id":"k10ek116","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"EU Binnenmarkt: freier …","answers":["Krieg","Warenverkehr","Zoll","Grenze überall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Waren."},
  {"id":"k10ek117","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Legende erklärt …","answers":["Politik","Signaturen","Zeit","Zufall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Zeichen."},
  {"id":"k10ek118","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Süßwasser u. a. in …","answers":["Meer","Gletscher/Grundwasser","Asphalt","Hochhaus"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Süßwasser."},
  {"id":"k10ek119","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Strukturwandel → …","answers":["Kohle","Dienstleistungen","Wüste","Landwirtschaft"],"correct":1,"difficulty":"mittel","points":10,"explanation":"tertiär."},
  {"id":"k10ek120","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Geopolitik: Macht und …","answers":["Sport","Raum","Mode","Zufall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Raum."},
  {"id":"k10ek121","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Tropen nah am …","answers":["Pol","Äquator","Mond","Mars"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Äquator."},
  {"id":"k10ek122","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Bodenschatz?","answers":["Luft","Erz/Kohle","Wolke","Wind"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Rohstoff."},
  {"id":"k10ek123","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Versiegelung + Starkregen → …","answers":["weniger Risiko","mehr Hochwasser","kein Effekt","Schnee"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Risiko."},
  {"id":"k10ek124","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Fair Trade → …","answers":["Dumping","faire Preise","Zwischenhandel max","Schwarzmarkt"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Fairness."},
  {"id":"k10ek125","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Kompass → …","answers":["Osten","Norden","Süden","Westen"],"correct":1,"difficulty":"mittel","points":10,"explanation":"N."},
  {"id":"k10ek126","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Primärer Sektor = …","answers":["Industrie","Rohstoffe/Landwirtschaft","Dienstleistung","IT"],"correct":1,"difficulty":"mittel","points":10,"explanation":"primär."},
  {"id":"k10ek127","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Bevölkerungsdichte = …","answers":["Zahl","Einwohner/Fläche","Geburten","Migration"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Dichte."},
  {"id":"k10ek128","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Klimaschutz: mehr …","answers":["Kohle","Erneuerbare","Abholzung","Flüge"],"correct":1,"difficulty":"mittel","points":10,"explanation":"EE."},
  {"id":"k10ek129","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"Metropolregion = …","answers":["Dorf","Stadtregion","Wüste","Insel"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Agglomeration."},
  {"id":"k10ek130","category":"k10_erdkunde","area":"schule","grade":10,"subject":"erdkunde","topic":"erweiterung","question":"SDGs sind …","answers":["Krieg","UN-Nachhaltigkeitsziele","nur DE","Sport"],"correct":1,"difficulty":"mittel","points":10,"explanation":"UN."}
];
