const K10_BIOLOGIE_QUESTIONS = [
  // ================================================================
  // 1. ZELLE & ZELLBIOLOGIE (20 Fragen)
  // ================================================================
  {
    id: "q10_b_001",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die kleinste selbstständig lebensfähige Einheit eines Organismus?",
    answers: ["Das Gewebe", "Die Zelle", "Der Organismus", "Das Organ"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zelle ist die Grundeinheit des Lebens."
  },
  {
    id: "q10_b_002",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welches Zellorganell enthält die Erbinformation?",
    answers: ["Zellwand (Barriere)", "Lysosom (Verdauung)", "Zellkern (Nucleus)", "Vakuole (Speicher)"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Zellkern liegt die DNA in Form von Chromosomen vor."
  },
  {
    id: "q10_b_003",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Aufgabe haben die Mitochondrien?",
    answers: ["Speicherung von Erbinformation", "Energiegewinnung (Zellatmung)", "Photosynthese in Chloroplasten", "Eiweißsynthese an Ribosomen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Mitochondrien produzieren ATP durch Zellatmung."
  },
  {
    id: "q10_b_004",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen tierischen und pflanzlichen Zellen?",
    answers: ["Tierzellen besitzen Zellwand und Chloroplasten", "Pflanzenzellen haben niemals ein Zellplasma", "Tierzellen besitzen immer eine Zellwand aus Cellulose", "Pflanzenzellen besitzen Zellwand und Chloroplasten"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Zellwand und Chloroplasten sind typisch für Pflanzenzellen."
  },
  {
    id: "q10_b_005",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Aufgabe hat die Zellmembran?",
    answers: ["Stoffaustausch und Abgrenzung der Zelle","Bereitstellung von Energie durch die Zellatmung","Aufbau von Traubenzucker durch Photosynthese","Dauerhafte Speicherung der Erbinformation im Kern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Membran reguliert den Stoffdurchtritt."
  },
  {
    id: "q10_b_006",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Wo findet die Photosynthese in der Pflanzenzelle statt?",
    answers: ["In den Chloroplasten", "In den Ribosomen", "Im Zellkern", "In den Mitochondrien"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Chloroplasten enthalten Chlorophyll und betreiben Photosynthese."
  },
  {
    id: "q10_b_007",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Ribosomen?",
    answers: ["Stofftransport", "Energiegewinnung", "Eiweißsynthese", "Photosynthese"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Ribosomen übersetzen mRNA in Proteine."
  },
  {
    id: "q10_b_008",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was versteht man unter Diffusion?",
    answers: ["Aktiver Transport von Stoffen unter Verbrauch von ATP-Energie","Osmotischer Wassertransport durch die halbdurchlässige Zellmembran","Gezielter Gasaustausch, der ausschließlich in der Lunge stattfindet","Ausgleich von Konzentrationsunterschieden ohne Energieaufwand"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Diffusion ist passiver Stofftransport."
  },
  {
    id: "q10_b_009",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Osmose?",
    answers: ["Diffusion von Wasser durch eine semipermeable Membran","Aufbau von Traubenzucker in den Chloroplasten der Zelle","Aktiver Transport von Ionen durch spezielle Kanäle","Teilung der Zelle durch Mitose und anschließende Cytokinese"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Osmose ist die Wasserbewegung entlang des Konzentrationsgefälles."
  },
  {
    id: "q10_b_010",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Zellen besitzen keinen echten Zellkern?",
    answers: ["Hautzellen","Nervenzellen","Wurzelhaarzellen","Bakterienzellen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Prokaryoten haben kein abgetrenntes Kernkompartiment."
  },
  {
    id: "q10_b_011",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Zellplasmas (Cytoplasma)?",
    answers: ["Ausschließlich Photosynthese in den Chloroplasten","Ausschließlich Speicherung der genetischen Information","Ausschließlich Energiegewinnung durch die Zellatmung","Ort vieler Stoffwechselvorgänge und Transportmedium"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Cytoplasma laufen zahlreiche Reaktionen ab."
  },
  {
    id: "q10_b_012",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind Chromosomen?",
    answers: ["Strukturen aus DNA und Proteinen, die die Erbinformation tragen","Bestandteile der Zellmembran, die den Stoffaustausch regulieren","Enzyme, die chemische Reaktionen in der Zelle beschleunigen","Zellorganellen, die ausschließlich der Energiegewinnung dienen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Chromosomen enthalten die Gene."
  },
  {
    id: "q10_b_013",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Phase der Mitose folgt auf die Prophase?",
    answers: ["Telophase", "Interphase", "Anaphase", "Metaphase"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Reihenfolge: Prophase – Metaphase – Anaphase – Telophase."
  },
  {
    id: "q10_b_014",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was geschieht in der Anaphase der Mitose?",
    answers: ["Der Zellkern löst sich vollständig auf", "Die Schwesterchromatiden werden zu den Polen gezogen", "Die Zellmembran schnürt sich in der Mitte durch", "Die Chromosomen ordnen sich mittig in der Äquatorialebene"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Anaphase = Trennung der Chromatiden."
  },
  {
    id: "q10_b_015",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Mitose und Meiose?",
    answers: ["Mitose und Meiose laufen in exakt identischer Weise ab","Mitose erzeugt diploide Körperzellen, Meiose haploide Keimzellen","Beide Prozesse erzeugen ausschließlich diploide Körperzellen im Gewebe","Beide Prozesse erzeugen ausschließlich haploide Keimzellen im Körper"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Meiose halbiert den Chromosomensatz."
  },
  {
    id: "q10_b_016",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ATP?",
    answers: ["Ein Botenstoff des Hormonsystems", "Der universelle Energieträger der Zelle", "Ein essenzielles Vitamin für den Stoffwechsel", "Ein struktureller Baustein der Zellmembran"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "ATP speichert und überträgt Energie."
  },
  {
    id: "q10_b_017",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Reaktion beschreibt die Photosynthese vereinfacht?",
    answers: ["Zucker + O₂ → CO₂ + H₂O + Energie", "CO₂ + H₂O + Licht → Zucker + O₂", "Nur Wasser → Sauerstoff", "Nur CO₂ → O₂"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Pflanzen bauen mit Licht aus CO₂ und Wasser Zucker auf und setzen O₂ frei."
  },
  {
    id: "q10_b_018",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Reaktion beschreibt die Zellatmung vereinfacht?",
    answers: ["Zucker + O₂ → CO₂ + H₂O + Energie (ATP)","Fett + Sauerstoff → Kohlendioxid + Wasser + Wärme","Zucker + Wasser → Kohlendioxid + Energie (ATP)","Wasser + CO₂ + Licht → Zucker + Sauerstoff frei"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zellatmung setzt die in Zucker gespeicherte Energie frei."
  },
  {
    id: "q10_b_019",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Enzym?",
    answers: ["Ein Hormon, das den Stoffwechsel im Körper reguliert","Ein struktureller Baustein der pflanzlichen Zellwand","Ein Energieträger für die mitochondriale Zellatmung","Ein Biokatalysator, der Reaktionen beschleunigt"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Enzyme senken die Aktivierungsenergie."
  },
  {
    id: "q10_b_020",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet 'semipermeabel'?",
    answers: ["Vollständig undurchlässig für alle Stoffe", "Teildurchlässig für bestimmte Stoffe", "Uneingeschränkt durchlässig für alle Stoffe", "Ausschließlich für Gase durchlässig"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zellmembran ist selektiv permeabel."
  },

  // ================================================================
  // 2. GENETIK (30 Fragen)
  // ================================================================
  {
    id: "q10_b_021",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Gen?",
    answers: ["Ein Zellorganell zur Gewinnung von Energie","Ein ganzes Chromosom mit sehr vielen einzelnen Genen","Ein Hormon, das das Wachstum des ganzen Körpers steuert","Ein Abschnitt der DNA, der für ein Merkmal codiert"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Gene sind die Erbeinheiten."
  },
  {
    id: "q10_b_022",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet diploid?",
    answers: ["Doppelter Chromosomensatz (2n)", "Einfacher Chromosomensatz (n)", "Dreifacher Chromosomensatz (3n)", "Vollständig fehlender Chromosomensatz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Körperzellen sind diploid."
  },
  {
    id: "q10_b_023",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet haploid?",
    answers: ["Vierfacher Chromosomensatz", "Doppelter Chromosomensatz", "Einfacher Chromosomensatz (n)", "Vollständig fehlender Chromosomensatz"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Keimzellen sind haploid."
  },
  {
    id: "q10_b_024",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Allel?",
    answers: ["Ein Enzym im Zellstoffwechsel", "Eine Variante eines Gens", "Ein Protein in der Zellmembran", "Ein ganzes Chromosom"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Allele sind unterschiedliche Ausprägungen desselben Gens."
  },
  {
    id: "q10_b_025",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet dominant?",
    answers: ["Das Allel wird nie ausgeprägt", "Das Allel setzt sich im Phänotyp durch", "Das Allel ist immer rezessiv", "Das Allel liegt nur auf dem Y-Chromosom"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Dominante Allele überdecken rezessive."
  },
  {
    id: "q10_b_026",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet rezessiv?",
    answers: ["Das Allel liegt ausschließlich auf dem Y-Chromosom des Mannes","Das Allel ist unabhängig vom Partnerallel immer vollständig dominant","Das Allel setzt sich in jedem Fall gegen andere Allele durch","Das Allel wird nur ausgeprägt, wenn kein dominantes vorhanden ist"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Rezessive Merkmale erscheinen nur im homozygoten Zustand."
  },
  {
    id: "q10_b_027",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Genotyp?",
    answers: ["Die genetische Ausstattung eines Individuums","Nur die Anzahl der vorhandenen Chromosomen im Kern","Nur die äußeren Umweltfaktoren eines Lebewesens","Ausschließlich das äußere Erscheinungsbild"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Genotyp = Allelkombination."
  },
  {
    id: "q10_b_028",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Phänotyp?",
    answers: ["Nur die Chromosomenzahl", "Nur die Umweltbedingungen", "Das äußere Erscheinungsbild", "Nur die vorhandene DNA-Sequenz"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Phänotyp = sichtbare Merkmale."
  },
  {
    id: "q10_b_029",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was besagt die 1. Mendel-Regel (Uniformitätsregel)?",
    answers: ["Alle Merkmale werden stets unabhängig voneinander vererbt","Nur dominante Merkmale werden an die Nachkommen weitergegeben","Die Merkmale spalten bereits in der ersten Generation auf","Kreuzung reinerbiger Eltern ergibt einheitliche Nachkommen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "F1-Generation ist uniform."
  },
  {
    id: "q10_b_030",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was besagt die 2. Mendel-Regel (Spaltungsregel)?",
    answers: ["Alle Nachkommen der F2-Generation sind in jeder Hinsicht völlig gleich","In der F2-Generation spalten die Merkmale im Verhältnis 3:1 auf","In der F2-Generation erscheinen ausschließlich die rezessiven Merkmale","In der F2-Generation gibt es unter keinen Umständen eine Aufspaltung"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei monohybridem Erbgang: 3 dominant : 1 rezessiv."
  },
  {
    id: "q10_b_031",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist DNA?",
    answers: ["Ein Protein, das aus vielen Aminosäureketten besteht","Ein Hormon der Hirnanhangdrüse im Gehirn","Ein Zucker, der als Energiespeicher dient","Desoxyribonukleinsäure – Träger der Erbinformation"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "DNA speichert die genetische Information."
  },
  {
    id: "q10_b_032",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Basen paaren in der DNA?",
    answers: ["Alle Basen paarweise beliebig", "Adenin mit Thymin, Guanin mit Cytosin", "Adenin mit Guanin, Thymin mit Cytosin", "Adenin mit Cytosin, Guanin mit Thymin"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Komplementäre Basenpaarung: A-T, G-C."
  },
  {
    id: "q10_b_033",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Mutation?",
    answers: ["Nur eine kurzfristige Anpassung an die Umweltbedingungen","Nur eine gewöhnliche Zellteilung ohne bleibende Folgen","Nur eine vorübergehende, reversible Veränderung der Zelle","Eine bleibende Veränderung der genetischen Information"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Mutationen verändern die DNA dauerhaft."
  },
  {
    id: "q10_b_034",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein homozygoter Genotyp?",
    answers: ["Beide Allele sind unterschiedlich", "Nur ein einziges Allel ist vorhanden", "Beide Allele fehlen völlig im Genom", "Beide Allele eines Gens sind gleich"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Homozygot = reinerbig (AA oder aa)."
  },
  {
    id: "q10_b_035",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein heterozygoter Genotyp?",
    answers: ["Beide Allele eines Gens sind unterschiedlich", "Nur ein einziges Allel ist im Genom vorhanden", "Beide Allele des Gens sind völlig identisch", "Es sind überhaupt keine Allele vorhanden"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Heterozygot = mischerbig (Aa)."
  },
  {
    id: "q10_b_036",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Wie viele Chromosomen hat der Mensch in einer Körperzelle?",
    answers: ["92 (46 Paare)", "46 (23 Paare)", "23 (unpaarig)", "44 (22 Paare)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "46 Chromosomen = 23 homologe Paare."
  },
  {
    id: "q10_b_037",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der mRNA?",
    answers: ["Photosynthese in den Chloroplasten der grünen Pflanzenzelle","Übertragung der genetischen Information vom Kern zu den Ribosomen","Dauerhafte Speicherung der gesamten Erbinformation im Zellkern","Energiegewinnung durch die Zellatmung in den Mitochondrien der Zelle"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "mRNA ist die Boten-RNA."
  },
  {
    id: "q10_b_038",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Karyogramm?",
    answers: ["Eine Nahrungskette innerhalb eines gesamten Ökosystems","Ein Stammbaum eng verwandter Lebewesen einer bestimmten Art","Die geordnete Darstellung aller Chromosomen einer Zelle","Ein Schema der wichtigsten Enzyme innerhalb einer Zelle"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Im Karyogramm werden Chromosomen nach Größe und Form sortiert."
  },
  {
    id: "q10_b_039",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was besagt die 3. Mendel-Regel (Unabhängigkeitsregel)?",
    answers: ["Alle Gene sind fest und dauerhaft aneinander gekoppelt","Rezessive Gene verschwinden bereits nach einer Generation","Nur dominante Gene werden an die Nachkommen vererbt","Verschiedene Gene werden unabhängig voneinander vererbt"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei dihybridem Erbgang spalten die Merkmale unabhängig auf."
  },
  {
    id: "q10_b_040",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Doppelhelix?",
    answers: ["Ein Protein mit Enzymfunktion", "Ein Enzym zur DNA-Reparatur", "Ein vollständiger Chromosomensatz", "Die räumliche Struktur der DNA"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "DNA besteht aus zwei komplementären Strängen in Schraubenform."
  },
  {
    id: "q10_b_041",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein X-chromosomaler Erbgang?",
    answers: ["Das Gen liegt auf dem X-Chromosom", "Das Gen liegt auf dem Y-Chromosom", "Das Gen liegt auf einem Autosom", "Das Gen liegt nicht auf einem Chromosom"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Geschlechtsgebundene Vererbung über das X-Chromosom."
  },
  {
    id: "q10_b_042",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der tRNA?",
    answers: ["Dauerhafte Speicherung der DNA im Zellkern","Energiegewinnung in den Mitochondrien der Zelle","Photosynthese in den Chloroplasten der Pflanze","Transport von Aminosäuren zu den Ribosomen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "tRNA bringt die passenden Aminosäuren."
  },
  {
    id: "q10_b_043",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Codon?",
    answers: ["Ein Protein aus mehreren verschiedenen Aminosäureketten","Ein Triplett von Basen, das eine Aminosäure codiert","Ein ganzes Gen mit sehr vielen einzelnen Basenpaaren","Ein Chromosom mit hunderten einzelnen Genen darauf"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Drei Basen bilden ein Codon."
  },
  {
    id: "q10_b_044",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was geschieht bei der Replikation der DNA?",
    answers: ["Die DNA wird in RNA umgeschrieben", "Die DNA wird abgebaut", "Die DNA wird verdoppelt", "Die DNA wird in Protein übersetzt"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Replikation sichert die Weitergabe der Erbinformation."
  },
  {
    id: "q10_b_045",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Transcription?",
    answers: ["Verdopplung der gesamten DNA vor der Zellteilung", "Kontrollierter Abbau überschüssiger RNA", "Umschreibung der DNA-Information in mRNA", "Übersetzung der mRNA-Sequenz in Protein"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Transcription = DNA → mRNA."
  },
  {
    id: "q10_b_046",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Translation?",
    answers: ["Übersetzung der mRNA-Sequenz in eine Aminosäurekette","Verdopplung der gesamten DNA kurz vor der Zellteilung","Zellteilung mit vollständiger Verdopplung des Chromosomensatzes","Umschreibung der DNA-Information in die passende mRNA"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Translation = Proteinbiosynthese an den Ribosomen."
  },
  {
    id: "q10_b_047",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Autosom?",
    answers: ["Ein Chromosom, das die Geschlechtsbestimmung eines Menschen festlegt","Ein Protein, das dauerhaft fest an Chromosomen gebunden bleibt","Ein Chromosom, das nicht an der Geschlechtsbestimmung beteiligt ist","Ein Gen, das ausschließlich auf einem Geschlechtschromosom liegt"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Mensch hat 22 Autosomenpaare und ein Geschlechtschromosomenpaar."
  },
  {
    id: "q10_b_048",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Gen und Allel?",
    answers: ["Zwischen beiden Begriffen besteht überhaupt kein Unterschied","Ein Gen ist der Ort, Allele sind die Varianten dieses Gens","Gene sind grundsätzlich immer rezessiv veranlagt","Allele sind grundsätzlich immer dominant veranlagt"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Gen = Locus, Allele = alternative Formen."
  },
  {
    id: "q10_b_049",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Punnett-Quadrat?",
    answers: ["Ein Modell zur Darstellung von Enzymreaktionen in der Zelle","Ein Bild der Chromosomen im erstellten Karyogramm","Ein Stammbaum zur Erfassung erblicher Krankheiten","Ein Schema zur Vorhersage von Genotypen bei Kreuzungen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Mit dem Punnett-Quadrat lassen sich Mendel-Kreuzungen darstellen."
  },
  {
    id: "q10_b_050",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet intermedärer Erbgang?",
    answers: ["Nur das rezessive Allel bestimmt allein den gesamten Phänotyp","Beide Allele beeinflussen den Phänotyp gemeinsam (Mischform)","Es findet in diesem Fall grundsätzlich überhaupt keine Vererbung statt","Nur das dominante Allel bestimmt allein den gesamten Phänotyp"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Beispiel: rote und weiße Blüten → rosa Nachkommen."
  },

  // ================================================================
  // 3. EVOLUTION (20 Fragen)
  // ================================================================
  {
    id: "q10_b_051",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Evolution?",
    answers: ["Nur die Zellteilung innerhalb eines einzelnen Organismus","Nur die Entwicklung eines einzelnen Individuums im Leben","Nur die Anpassung eines Lebewesens innerhalb einer Generation","Die Veränderung von Lebewesen über Generationen hinweg"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Evolution beschreibt die stammesgeschichtliche Entwicklung."
  },
  {
    id: "q10_b_052",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Wer formulierte die Evolutionstheorie durch natürliche Selektion?",
    answers: ["Alexander Fleming","Gregor Mendel","Charles Darwin","Robert Koch"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Darwin veröffentlichte 1859 'On the Origin of Species'."
  },
  {
    id: "q10_b_053",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist natürliche Selektion?",
    answers: ["Nur zufällige Mutation gänzlich ohne jede Selektionswirkung","Bevorzugte Fortpflanzung der besser angepassten Individuen","Nur künstliche Züchtung von Nutztieren durch den Menschen","Zufällige Veränderung der DNA-Sequenz innerhalb einer Zelle"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Selektion wirkt auf vorhandene Variation."
  },
  {
    id: "q10_b_054",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Anpassung (Adaptation)?",
    answers: ["Nur eine zufällige Mutation im Erbgut eines einzelnen Lebewesens","Nur eine kurzfristige Veränderung der äußeren Umweltbedingungen","Nur ein erlerntes Verhalten eines einzelnen, erwachsenen Individuums","Ein Merkmal, das die Überlebens- und Fortpflanzungschancen erhöht"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Anpassungen entstehen durch Selektion."
  },
  {
    id: "q10_b_055",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind homologe Organe?",
    answers: ["Organe mit gleicher Herkunft, aber möglicherweise unterschiedlicher Funktion","Organe mit gleicher Funktion, aber unterschiedlicher stammesgeschichtlicher Herkunft","Organe, die im Körper keinerlei erkennbare Funktion mehr besitzen","Organe mit ausschließlich gleicher äußerer Form und Farbe"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Homologie deutet auf gemeinsame Abstammung hin."
  },
  {
    id: "q10_b_056",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind analoge Organe?",
    answers: ["Organe mit ausschließlich gleicher innerer anatomischer Struktur","Organe mit gemeinsamer stammesgeschichtlicher Herkunft und Bauplan","Nur zurückgebildete, funktionslose rudimentäre Organe","Organe mit ähnlicher Funktion, aber unterschiedlicher Herkunft"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Analogie entsteht durch konvergente Evolution."
  },
  {
    id: "q10_b_057",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind rudimentäre Organe?",
    answers: ["Nur besonders spezialisierte Sinnesorgane des menschlichen Körpers","Neu entstandene Organe mit vollständiger, voll funktionierender Funktion","Zurückgebildete Organe, die ihre ursprüngliche Funktion verloren haben","Besonders wichtige, absolut lebensnotwendige Organe des ganzen Körpers"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beispiel: Weisheitszähne oder Steißbein beim Menschen."
  },
  {
    id: "q10_b_058",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Artbildung (Speziation)?",
    answers: ["Die Entstehung neuer Arten aus bestehenden Populationen","Nur die geringfügige Veränderung innerhalb einer einzigen Art","Nur eine einzelne zufällige Mutation im Erbgut","Nur die natürliche Selektion einer Population allein"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Artbildung kann z. B. durch geografische Isolation erfolgen."
  },
  {
    id: "q10_b_059",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Genpool?",
    answers: ["Nur die Anzahl der dominanten Allele einer Population","Nur die Chromosomen eines einzelnen Individuums","Die Gesamtheit aller Allele in einer Population","Nur die DNA-Menge in einer einzelnen Zelle"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Genpool ist die genetische Vielfalt einer Population."
  },
  {
    id: "q10_b_060",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Fitness in der Evolutionsbiologie?",
    answers: ["Nur die Intelligenz eines einzelnen Lebewesens","Nur die Körpergröße eines einzelnen Individuums","Der Fortpflanzungserfolg eines Individuums","Nur die körperliche Leistungsfähigkeit im Alltag"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Fitness misst den Beitrag zum Genpool der nächsten Generation."
  },
  {
    id: "q10_b_061",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist konvergente Evolution?",
    answers: ["Nur zufällige Selektion ganz ohne jegliche gemeinsame Merkmale","Unabhängige Entwicklung ähnlicher Merkmale bei nicht verwandten Arten","Gemeinsame Entwicklung aus einem einzigen gemeinsamen Vorfahren heraus","Nur zufällige Mutation ganz ohne erkennbaren Anpassungswert"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Beispiel: Flügel von Insekten und Vögeln."
  },
  {
    id: "q10_b_062",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Fossil?",
    answers: ["Ein Enzym zur Beschleunigung chemischer Reaktionen im Stoffwechsel","Ein erhaltener Rest oder Abdruck eines Lebewesens aus früherer Zeit","Ein Mineral, das aus vulkanischem Gestein tief in der Erde entsteht","Ein heute noch lebendes, völlig unverändertes Tier der Gegenwart"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossilien belegen die Evolution."
  },
  {
    id: "q10_b_063",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Stammbaum der Lebewesen?",
    answers: ["Nur die Anzahl der vorhandenen Chromosomensätze einer Art","Eine Darstellung der verwandtschaftlichen Beziehungen","Nur eine einfache Liste bereits bekannter Arten","Nur eine geordnete Darstellung der Chromosomen einer Zelle"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Stammbäume zeigen gemeinsame Vorfahren."
  },
  {
    id: "q10_b_064",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Selektionsdruck?",
    answers: ["Nur die Anzahl der vorhandenen Chromosomen einer Zelle","Der Einfluss der Umweltfaktoren auf die Überlebenschancen","Nur die durchschnittliche Umgebungstemperatur eines Gebiets","Nur die Häufigkeit zufälliger Mutationen im Erbgut"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Selektionsdruck führt zu Anpassung."
  },
  {
    id: "q10_b_065",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Isolation in der Evolution?",
    answers: ["Nur die geografische Entfernung zwischen zwei verschiedenen Gebieten","Trennung von Populationen, die den Genaustausch verhindert","Nur die natürliche Selektion innerhalb einer einzigen Population","Nur eine einzelne zufällige genetische Mutation im Erbgut"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Isolation ist Voraussetzung für Artbildung."
  },
  {
    id: "q10_b_066",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Mikro- und Makroevolution?",
    answers: ["Mikroevolution = Veränderungen innerhalb einer Art, Makroevolution = Entstehung neuer Arten und höherer Taxa","Zwischen Mikroevolution und Makroevolution besteht laut dieser Aussage ganz und gar überhaupt kein Unterschied","Makroevolution betrifft ausschließlich einzellige Bakterien und andere winzige Mikroorganismen der Erde","Mikroevolution verläuft grundsätzlich in jedem einzelnen Fall deutlich schneller ab als die Makroevolution"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Die Begriffe beschreiben unterschiedliche Zeitskalen und Ebenen."
  },
  {
    id: "q10_b_067",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein lebendes Fossil?",
    answers: ["Ein versteinertes Fossil, das angeblich immer noch atmet","Ein vollständig ausgestorbenes, völlig unbekanntes Tier der Vorzeit","Ein durch Mutation ganz neu entstandenes, unbekanntes Tier","Eine Art, die sich über sehr lange Zeit kaum verändert hat"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beispiel: Quastenflosser oder Ginkgo."
  },
  {
    id: "q10_b_068",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der genetische Drift?",
    answers: ["Nur gezielte natürliche Selektion in sehr großen Populationen","Nur eine einzelne zufällige Mutation der DNA-Sequenz einer einzigen Zelle","Nur eine sehr langsame Anpassung an ganz neue Umweltbedingungen der Erde","Zufällige Veränderung der Allelfrequenzen in kleinen Populationen"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Genetische Drift ist besonders in kleinen Populationen wirksam."
  },
  {
    id: "q10_b_069",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der gemeinsame Vorfahre?",
    answers: ["Eine Art, aus der sich mehrere heutige Arten entwickelt haben","Nur eine einzelne zufällige Mutation im Erbgut eines einzelnen Tieres","Nur ein einzelnes lebendes Individuum einer ganz bestimmten Art","Nur das älteste bekannte gefundene Fossil auf der ganzen Erde"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gemeinsame Vorfahren begründen Verwandtschaft."
  },
  {
    id: "q10_b_070",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Beweiswert von Fossilien für die Evolution?",
    answers: ["Sie beweisen ausschließlich die frühere Existenz bestimmter Tiere","Sie zeigen ausschließlich die damaligen klimatischen Bedingungen der Erde","Sie haben für die Evolutionstheorie nach dieser Aussage keinen Beweiswert","Sie zeigen die Veränderung von Lebensformen über geologische Zeiträume"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossilreihen belegen Übergangsformen."
  },

  // ================================================================
  // 4. ÖKOLOGIE (30 Fragen)
  // ================================================================
  {
    id: "q10_b_071",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Ökosystem?",
    answers: ["Nur die Tierwelt eines bestimmten geografischen Gebiets","Nur die Pflanzenwelt eines bestimmten geografischen Gebiets","Nur die Bodenbeschaffenheit eines bestimmten Gebiets","Die Gesamtheit aus Lebensgemeinschaft und Lebensraum"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ökosystem = Biozönose + Biotop."
  },
  {
    id: "q10_b_072",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Produzent?",
    answers: ["Ein Lebewesen, das tote organische Substanz vollständig zersetzt","Ein Lebewesen, das organische Stoffe aus anorganischen aufbaut","Ein Lebewesen, das sowohl Pflanzen als auch andere Tiere frisst","Ein Lebewesen, das sich ausschließlich von tierischem Fleisch ernährt"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Produzenten betreiben Photosynthese."
  },
  {
    id: "q10_b_073",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Konsument?",
    answers: ["Nur Bakterien, die organische Stoffe zersetzen", "Ein Lebewesen, das organische Stoffe aufnimmt (Tiere)", "Ein Lebewesen, das organische Stoffe selbst herstellt", "Nur Pflanzen, die Photosynthese betreiben"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Konsumenten ernähren sich von anderen Organismen."
  },
  {
    id: "q10_b_074",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Destruent (Zersetzer)?",
    answers: ["Ein Lebewesen, das organische Stoffe selbst aufbaut", "Ein Lebewesen am Ende der Nahrungskette", "Ein Lebewesen, das sich direkt von Pflanzen ernährt", "Ein Lebewesen, das tote organische Substanz abbaut"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bakterien und Pilze sind wichtige Destruenten."
  },
  {
    id: "q10_b_075",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Nahrungskette?",
    answers: ["Nur die Tiere eines Ökosystems", "Nur die Pflanzen eines Ökosystems", "Nur der Stoffkreislauf", "Eine Abfolge von Fressbeziehungen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Nahrungsketten zeigen den Energiefluss."
  },
  {
    id: "q10_b_076",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Nahrungsnetz?",
    answers: ["Die vernetzten Nahrungsbeziehungen in einem Ökosystem","Nur die Produzenten eines einzelnen Ökosystems","Nur eine einzelne, lineare Nahrungskette in der Natur","Nur die Zersetzer innerhalb eines Ökosystems"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nahrungsnetze sind komplexer als einzelne Ketten."
  },
  {
    id: "q10_b_077",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die ökologische Nische?",
    answers: ["Nur die Temperatur im Lebensraum einer einzelnen Art","Die Gesamtheit der Umweltbeziehungen einer Art","Nur der geografische Lebensraum einer einzelnen Art","Nur die verfügbare Nahrung einer einzelnen Art"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Nische beschreibt die Rolle einer Art im Ökosystem."
  },
  {
    id: "q10_b_078",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Konkurrenz?",
    answers: ["Eine für beide Seiten vorteilhafte Symbiose", "Wettbewerb um begrenzte Ressourcen", "Eine dauerhafte Zusammenarbeit zweier Arten", "Nur Räuber-Beute-Beziehung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Konkurrenz kann inner- oder zwischenartlich sein."
  },
  {
    id: "q10_b_079",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Symbiose?",
    answers: ["Eine Beziehung, von der beide Partner profitieren","Eine reine Räuber-Beute-Beziehung zwischen zwei Arten","Eine Beziehung, die beiden beteiligten Partnern schadet","Eine Beziehung, die nur einem der beiden Partner nützt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiel: Flechten (Pilz + Alge)."
  },
  {
    id: "q10_b_080",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Parasitismus?",
    answers: ["Eine Beziehung, bei der die Beute sofort und vollständig getötet wird","Eine Beziehung, bei der ein Partner schadet und der andere profitiert","Ein Wettbewerb um dieselben begrenzten Ressourcen in einem Gebiet","Eine für beide beteiligten Partner gleichermaßen vorteilhafte Beziehung"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Parasiten leben auf oder in einem Wirt."
  },
  {
    id: "q10_b_081",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Tragfähigkeit eines Ökosystems?",
    answers: ["Nur die durchschnittliche Jahrestemperatur eines bestimmten Gebiets","Nur die jährliche Niederschlagsmenge eines bestimmten Gebiets","Nur die Anzahl der vorhandenen Produzenten in einem Gebiet","Die maximale Populationsgröße, die dauerhaft erhalten werden kann"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Überschreitung der Tragfähigkeit führt zu Zusammenbrüchen."
  },
  {
    id: "q10_b_082",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Biodiversität?",
    answers: ["Nur die Anzahl der Tierarten in einem Gebiet", "Nur die Anzahl der Pflanzenarten in einem Gebiet", "Nur die genetische Vielfalt einer Art", "Die Vielfalt der Arten, Gene und Ökosysteme"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Biodiversität umfasst mehrere Ebenen."
  },
  {
    id: "q10_b_083",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Treibhauseffekt?",
    answers: ["Nur der Abbau der schützenden Ozonschicht", "Erwärmung der Atmosphäre durch bestimmte Gase", "Nur die natürliche Abkühlung der Erdatmosphäre", "Nur die Photosynthese der grünen Pflanzen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Natürlicher und anthropogener Treibhauseffekt."
  },
  {
    id: "q10_b_084",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Gase tragen besonders zum Treibhauseffekt bei?",
    answers: ["Stickstoff und Sauerstoff", "Nur reine Edelgase", "CO₂, Methan, Wasserdampf", "Nur reiner Sauerstoff"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Treibhausgase halten Wärmestrahlung zurück."
  },
  {
    id: "q10_b_085",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Biozönose und Biotop?",
    answers: ["Biozönose = Lebensgemeinschaft, Biotop = Lebensraum", "Beide bedeuten dasselbe", "Biozönose = Lebensraum, Biotop = Lebensgemeinschaft", "Beide betreffen nur Pflanzen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Zusammen bilden sie das Ökosystem."
  },
  {
    id: "q10_b_086",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein abiotischer Umweltfaktor?",
    answers: ["Ein belebter Faktor (Räuber, Konkurrenten)", "Nur die Artgenossen", "Ein unbelebter Faktor", "Nur die Nahrung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Abiotisch = nicht lebend."
  },
  {
    id: "q10_b_087",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein biotischer Umweltfaktor?",
    answers: ["Nur Temperatur", "Nur Licht", "Nur Bodenbeschaffenheit", "Ein belebter Faktor"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Biotisch = durch andere Lebewesen bedingt."
  },
  {
    id: "q10_b_088",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Energiefluss in einem Ökosystem?",
    answers: ["Nur der Kreislauf der Nährstoffe innerhalb des Ökosystems","Nur die Zellatmung einzelner Lebewesen im Ökosystem","Die Weitergabe von Energie von Produzenten zu Konsumenten","Nur die Photosynthese der Produzenten im Ökosystem"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Energie geht auf jeder Stufe teilweise verloren."
  },
  {
    id: "q10_b_089",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Stoffkreislauf?",
    answers: ["Nur die Zellatmung innerhalb der Konsumenten eines Gebiets","Nur die Photosynthese in den Produzenten eines Gebiets","Der wiederholte Weg von Nährstoffen durch das Ökosystem","Nur der einseitige Energiefluss innerhalb des Ökosystems"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Stoffe werden im Gegensatz zur Energie recycelt."
  },
  {
    id: "q10_b_090",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Artenschutz?",
    answers: ["Nur die kontrollierte Jagd auf bereits stark bedrohte Arten","Nur die wissenschaftliche Forschung an bereits bedrohten Arten","Maßnahmen zum Erhalt bedrohter Arten und ihrer Lebensräume","Nur die gezielte Züchtung besonders seltener Tierarten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Artenschutz ist Teil des Naturschutzes."
  },
  {
    id: "q10_b_091",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Indikatororganismus?",
    answers: ["Nur ein Destruent innerhalb eines komplexen Nahrungsnetzes","Nur ein Räuber an der Spitze einer langen Nahrungskette","Nur ein Produzent innerhalb eines bestimmten Ökosystems","Eine Art, die auf bestimmte Umweltbedingungen hinweist"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Flechten zeigen z. B. Luftqualität an."
  },
  {
    id: "q10_b_092",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Population und Art?",
    answers: ["Eine Art existiert dieser Aussage zufolge grundsätzlich immer nur in einem einzigen, ganz festen Gebiet","Eine Population ist dieser Aussage zufolge grundsätzlich immer viel größer als die gesamte Art insgesamt","Population = Gruppe einer Art in einem Gebiet, Art = Gesamtheit aller fortpflanzungsfähigen Individuen","Population und Art bedeuten in der Biologie nach dieser Aussage exakt dasselbe wie im Alltag"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Populationen sind räumlich begrenzt."
  },
  {
    id: "q10_b_093",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Sukzession?",
    answers: ["Nur die Konkurrenz zwischen zwei verschiedenen Arten am Standort","Die zeitliche Abfolge von Lebensgemeinschaften an einem Standort","Nur die Nahrungskette eines einzelnen, bestimmten Standorts","Nur die Wanderung von Tieren zwischen zwei verschiedenen Gebieten"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Sukzession führt oft zu einer Klimaxgesellschaft."
  },
  {
    id: "q10_b_094",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Ozonabbau?",
    answers: ["Die Zerstörung der Ozonschicht durch bestimmte Chemikalien","Nur die Zellatmung in den tierischen Zellen des ganzen Körpers","Nur die Photosynthese in den grünen Pflanzenzellen der Blätter","Nur der Treibhauseffekt durch das Gas Kohlendioxid (CO₂)"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "FCKW und ähnliche Stoffe schädigen die Ozonschicht."
  },
  {
    id: "q10_b_095",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen erneuerbaren und nicht erneuerbaren Ressourcen?",
    answers: ["Zwischen beiden Ressourcenarten besteht überhaupt kein Unterschied","Beide Ressourcenarten sind vollkommen unerschöpflich verfügbar","Erneuerbare können sich regenerieren, nicht erneuerbare nicht","Beide Ressourcenarten sind gleichermaßen endlich und begrenzt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossile Brennstoffe sind nicht erneuerbar."
  },
  {
    id: "q10_b_096",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Schlüsselart (Keystone Species)?",
    answers: ["Eine Art, die überproportional großen Einfluss auf das Ökosystem hat","Nur die körperlich größte Art innerhalb des gesamten Ökosystems","Nur ein ganz gewöhnlicher Produzent innerhalb des gesamten Nahrungsnetzes","Nur die zahlenmäßig häufigste Art in dem betrachteten Gebiet"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Der Verlust einer Schlüsselart kann das System stark verändern."
  },
  {
    id: "q10_b_097",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Räuber und Parasit?",
    answers: ["Räuber sind grundsätzlich immer deutlich kleiner als ihre Beute","Parasiten sind grundsätzlich immer deutlich größer als ihr Wirt","Räuber tötet die Beute, Parasit lebt länger auf/in dem Wirt","Räuber und Parasiten verhalten sich in jeder Hinsicht identisch"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Unterschiedliche Strategien der Ausbeutung."
  },
  {
    id: "q10_b_098",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der anthropogene Einfluss auf Ökosysteme?",
    answers: ["Nur der Einfluss von Pflanzen", "Nur der Einfluss des Klimas", "Nur der Einfluss von Tieren", "Der Einfluss des Menschen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Menschliche Aktivitäten verändern viele Ökosysteme stark."
  },
  {
    id: "q10_b_099",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Habitat und Nische?",
    answers: ["Habitat = Lebensraum, Nische = ökologische Rolle", "Habitat und Nische bedeuten in der Ökologie dasselbe", "Habitat ist die Rolle, Nische der Raum", "Beide Begriffe betreffen ausschließlich Tierarten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Nische ist multidimensional."
  },
  {
    id: "q10_b_100",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist nachhaltige Nutzung?",
    answers: ["Nutzung, die die Regenerationsfähigkeit des Systems erhält","Maximale Ausbeutung ohne jegliche Rücksicht auf Regeneration","Ausschließlich Schutz eines Gebiets ohne jegliche Nutzung","Nur kurzfristige Nutzung ohne jede langfristige Planung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltigkeit sichert Ressourcen für die Zukunft."
  },

  // ================================================================
  // 5. MENSCH & GESUNDHEIT / NERVENSYSTEM / IMMUN (50 Fragen – Erweiterung)
  // ================================================================
  {
    id: "q10_b_101",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Nervensystems?",
    answers: ["Aufnahme, Weiterleitung und Verarbeitung von Informationen","Nur die Verdauung und Aufnahme von Nährstoffen im Darm","Nur die Abwehr von Krankheitserregern im gesamten Blutkreislauf","Nur der Transport von Sauerstoff im Blut des menschlichen Körpers"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Nervensystem steuert und koordiniert."
  },
  {
    id: "q10_b_102",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Neuron?",
    answers: ["Ein Muskel", "Ein Blutkörperchen", "Eine Nervenzelle", "Ein Hormon"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Neurone leiten elektrische Signale."
  },
  {
    id: "q10_b_103",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Synapse?",
    answers: ["Ein Mitochondrium innerhalb einer einzelnen Nervenzelle","Ein Zellkern innerhalb eines einzelnen Neurons","Ein Muskel, der direkt von Nerven gesteuert wird","Die Verbindungsstelle zwischen zwei Nervenzellen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "An Synapsen wird das Signal chemisch übertragen."
  },
  {
    id: "q10_b_104",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist das zentrale Nervensystem?",
    answers: ["Gehirn und Rückenmark", "Nur die Sinnesorgane", "Nur die Nerven in den Armen", "Nur das vegetative System"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "ZNS = Gehirn + Rückenmark."
  },
  {
    id: "q10_b_105",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist das periphere Nervensystem?",
    answers: ["Nur das Rückenmark innerhalb der Wirbelsäule","Nur die Hormone des endokrinen Systems im Körper","Nur das Gehirn innerhalb des knöchernen Schädels","Die Nerven außerhalb von Gehirn und Rückenmark"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "PNS verbindet ZNS mit dem Körper."
  },
  {
    id: "q10_b_106",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Reflex?",
    answers: ["Eine unwillkürliche, schnelle Reaktion auf einen Reiz","Nur ein bewusster Gedanke ganz ohne körperliche Reaktion","Nur eine willkürlich gesteuerte Bewegung des Körpers","Eine bewusste, eher langsame Entscheidung des Gehirns"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Reflexe laufen über das Rückenmark ab."
  },
  {
    id: "q10_b_107",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Immunsystems?",
    answers: ["Nur die Verdauung von Nahrungsbestandteilen im Magen","Abwehr von Krankheitserregern und fremden Stoffen","Nur die Bewegung des Skeletts und der Muskulatur","Nur der Transport von Sauerstoff im Blut des Körpers"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Immunsystem schützt den Körper."
  },
  {
    id: "q10_b_108",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind Antikörper?",
    answers: ["Hormone, die den Blutzuckerspiegel regulieren", "Proteine, die gezielt gegen Erreger gerichtet sind", "Nur weiße Blutkörperchen ohne spezifische Wirkung", "Nur rote Blutkörperchen für den Sauerstofftransport"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Antikörper markieren oder neutralisieren Erreger."
  },
  {
    id: "q10_b_109",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Impfung?",
    answers: ["Nur eine Bluttransfusion zur Auffrischung des Blutes","Nur die Gabe von Antibiotika gegen bestimmte Bakterien","Nur die nachträgliche Behandlung einer bereits bestehenden Krankheit","Die gezielte Aktivierung des Immunsystems gegen einen Erreger"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Impfungen erzeugen immunologisches Gedächtnis."
  },
  {
    id: "q10_b_110",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen aktiver und passiver Immunisierung?",
    answers: ["Passiv erzeugt in jedem Fall grundsätzlich ein lebenslanges Immungedächtnis im Körper","Aktive und passive Immunisierung sind in jeder Hinsicht völlig identisch","Aktive Immunisierung ist grundsätzlich in jedem Fall deutlich gefährlicher","Aktiv: Körper bildet selbst Antikörper; Passiv: fertige Antikörper werden gegeben"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Aktive Immunisierung führt zu langfristigem Schutz."
  },
  {
    id: "q10_b_111",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der roten Blutkörperchen?",
    answers: ["Blutgerinnung", "Nur Nährstofftransport", "Sauerstofftransport", "Abwehr von Erregern"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Erythrozyten enthalten Hämoglobin."
  },
  {
    id: "q10_b_112",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der weißen Blutkörperchen?",
    answers: ["Transport von Nährstoffen im Blut", "Transport von Sauerstoff im Blut", "Abwehr von Krankheitserregern", "Beteiligung an der Blutgerinnung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Leukozyten sind Teil des Immunsystems."
  },
  {
    id: "q10_b_113",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Blutplättchen?",
    answers: ["Blutgerinnung", "Nur Nährstofftransport", "Abwehr von Erregern", "Sauerstofftransport"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Thrombozyten helfen bei der Wundheilung."
  },
  {
    id: "q10_b_114",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der große Blutkreislauf?",
    answers: ["Nur der Blutweg in die Beine und ganz allein wieder zurück zum Herzen","Der Weg vom linken Herzen zum Körper und zurück zum rechten Herzen","Nur der Blutweg zum Gehirn und wieder ganz zurück zum Herzen","Nur der kleine Kreislauf zur Lunge und wieder zurück zum Herzen"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Körperkreislauf versorgt die Organe."
  },
  {
    id: "q10_b_115",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der kleine Blutkreislauf?",
    answers: ["Nur der Blutweg in die Arme und wieder zurück zum Herzen","Nur der große Körperkreislauf zu den einzelnen Organen des Körpers","Nur der Blutweg zum Gehirn und wieder zurück zum Herzen","Der Weg vom rechten Herzen zur Lunge und zurück zum linken Herzen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Lungenkreislauf dient dem Gasaustausch."
  },
  {
    id: "q10_b_116",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Lunge?",
    answers: ["Nur die Blutbildung", "Nur die Verdauung", "Gasaustausch", "Nur die Abwehr"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "In den Alveolen findet der Gasaustausch statt."
  },
  {
    id: "q10_b_117",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Herzens?",
    answers: ["Filter für harnpflichtige Stoffe", "Pumpe für den Blutkreislauf", "Speicher für Verdauungsenzyme", "Bildungsort roter Blutkörperchen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Herz treibt das Blut an."
  },
  {
    id: "q10_b_118",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Nieren?",
    answers: ["Nur die Bildung roter Blutkörperchen im Knochenmark des ganzen Körpers","Nur die Atmung und der Gasaustausch in der menschlichen Lunge und Bronchien","Nur die Verdauung von Nahrung im Magen des menschlichen Körpers","Ausscheidung von Abbauprodukten und Regulation des Wasserhaushalts"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Nieren filtern das Blut."
  },
  {
    id: "q10_b_119",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Leber?",
    answers: ["Nur die Atmung über die feinen Lungenbläschen","Nur die Bewegung der gesamten Skelettmuskulatur","Stoffwechselzentrum, Entgiftung und Speicherung","Nur die Bildung von Blutzellen im Knochenmark"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Leber hat viele zentrale Funktionen."
  },
  {
    id: "q10_b_120",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Hormon?",
    answers: ["Ein Botenstoff, der über das Blut wirkt", "Ein elektrisches Nervensignal im Gehirn", "Ein Antikörper des Immunsystems", "Ein Enzym zur Verdauung der Nahrung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hormone steuern viele Körperfunktionen."
  },
  {
    id: "q10_b_121",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen sensiblen und motorischen Nerven?",
    answers: ["Sensibel = zum ZNS, motorisch = vom ZNS zu den Muskeln","Sensible und motorische Nerven sind völlig identisch aufgebaut","Sensibel steuert Muskeln, motorisch leitet Sinneseindrücke","Beide Nervenarten leiten ausschließlich zum Gehirn"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Richtung der Erregungsleitung unterscheidet sie."
  },
  {
    id: "q10_b_122",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Ruhezustand einer Nervenzelle?",
    answers: ["Ein Aktionspotenzial", "Nur die Erregungsleitung", "Nur die Synapse", "Das Ruhepotenzial"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Im Ruhezustand besteht ein Membranpotenzial."
  },
  {
    id: "q10_b_123",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Aktionspotenzial?",
    answers: ["Der dauerhafte Ruhezustand der ganzen Nervenzelle","Nur ein im Blut wirkendes körpereigenes Hormon","Nur die Verbindungsstelle zweier benachbarter Nervenzellen","Eine kurze Umkehrung des Membranpotenzials bei Erregung"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Aktionspotenziale leiten Informationen weiter."
  },
  {
    id: "q10_b_124",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Blut-Hirn-Schranke?",
    answers: ["Nur eine einzelne Nervenzelle im Rückenmark","Eine Schutzbarriere zwischen Blut und Gehirn","Nur ein Muskel im Bereich des menschlichen Kopfes","Nur ein im Gehirn wirkendes körpereigenes Hormon"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Sie schützt das Gehirn vor vielen Stoffen."
  },
  {
    id: "q10_b_125",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen angeborener und erworbener Immunität?",
    answers: ["Angeboren ist grundsätzlich in jedem Fall hochspezifisch und eher recht langsam","Erworben ist grundsätzlich in jedem Fall völlig unspezifisch und schnell","Angeborene und erworbene Immunität sind in jeder Hinsicht völlig identisch","Angeboren = unspezifisch und sofort, erworben = spezifisch und mit Gedächtnis"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Systeme arbeiten zusammen."
  },
  {
    id: "q10_b_126",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Antigen?",
    answers: ["Ein Antikörper gegen bestimmte Krankheitserreger","Ein Stoff, der eine Immunreaktion auslöst","Ein Hormon aus der körpereigenen Bauchspeicheldrüse","Ein Enzym der körpereigenen Verdauungsdrüsen"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Antigene werden vom Immunsystem erkannt."
  },
  {
    id: "q10_b_127",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Dickdarms?",
    answers: ["Wasserentzug und Formung des Kots", "Produktion von Verdauungsenzymen", "Aufnahme von Nährstoffen ins Blut", "Enzymatische Verdauung von Proteinen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Dickdarm wird dem Nahrungsbrei Wasser entzogen."
  },
  {
    id: "q10_b_128",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Dünndarms?",
    answers: ["Nur die Speicherung von Nahrung", "Hauptort der Wasseraufnahme", "Hauptort der Nährstoffaufnahme", "Hauptort der Kotbildung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Dünndarm werden die meisten Nährstoffe resorbiert."
  },
  {
    id: "q10_b_129",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Arterien und Venen?",
    answers: ["Arterien und Venen sind in ihrer Funktion völlig identisch","Arterien führen Blut vom Herzen weg, Venen zum Herzen hin","Arterien führen grundsätzlich immer sauerstoffarmes Blut","Venen führen grundsätzlich immer sauerstoffreiches Blut"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Richtung relativ zum Herzen definiert sie."
  },
  {
    id: "q10_b_130",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Kapillaren?",
    answers: ["Nur große Venen mit dunklem, sauerstoffarmem Blut","Nur große Arterien mit einem sehr hohen Blutdruck im Gefäß","Nur Lymphgefäße für den Rücktransport von Gewebeflüssigkeit","Feinste Blutgefäße, in denen der Stoffaustausch stattfindet"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Kapillaren ermöglichen den Austausch mit den Geweben."
  },
  {
    id: "q10_b_131",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Puls?",
    answers: ["Nur die Frequenz der Atmung pro Minute im Ruhezustand","Die druckbedingte Ausdehnung der Arterienwände","Nur die gemessene Herzfrequenz im Ruhezustand","Nur der gemessene Blutdruck innerhalb der Arterien"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Puls spiegelt die Herzschläge wider."
  },
  {
    id: "q10_b_132",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Blutdruck?",
    answers: ["Nur der tastbare Puls einer Arterie","Der Druck des Blutes auf die Gefäßwände","Nur die Frequenz der Atmung pro Minute","Nur die Frequenz des Herzschlags pro Minute"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Blutdruck wird in mmHg gemessen."
  },
  {
    id: "q10_b_133",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Bauchspeicheldrüse (Pankreas)?",
    answers: ["Nur die Atmung über die Lunge und die Bronchien des Körpers","Nur die Speicherung von Galleflüssigkeit im menschlichen Körper","Produktion von Verdauungsenzymen und Hormonen (Insulin)","Nur die Bildung roter Blutkörperchen im Knochenmark"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Pankreas hat exokrine und endokrine Funktionen."
  },
  {
    id: "q10_b_134",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Insulin?",
    answers: ["Ein Antikörper gegen bestimmte Bakterien","Ein Nervensignal innerhalb des Rückenmarks","Ein Verdauungsenzym im Dünndarm des Körpers","Ein Hormon, das den Blutzuckerspiegel senkt"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Insulin fördert die Aufnahme von Glucose in die Zellen."
  },
  {
    id: "q10_b_135",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Schilddrüse?",
    answers: ["Nur die Bildung von Blutzellen im Knochenmark des Körpers","Nur die Abwehr von Krankheitserregern im Blut","Produktion von Hormonen, die den Stoffwechsel regulieren","Nur die Verdauung von Nahrungsbestandteilen im Darm"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Schilddrüsenhormone beeinflussen den Energieumsatz."
  },
  {
    id: "q10_b_136",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen somatischem und vegetativem Nervensystem?",
    answers: ["Somatisch steuert ausschließlich innere Organe", "Somatisches und vegetatives System sind identisch", "Somatisch = willkürlich, vegetativ = unwillkürlich", "Vegetativ steuert ausschließlich die Skelettmuskeln"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Vegetatives System reguliert innere Organe."
  },
  {
    id: "q10_b_137",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Sympathikus?",
    answers: ["Nur ein Teil des zentralen Gehirns im menschlichen Schädel","Teil des vegetativen Systems, der den Körper leistungsbereit macht","Teil des vegetativen Systems, der den Körper in Ruhe versetzt","Nur das willkürlich steuerbare somatische Nervensystem des Körpers"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Sympathikus = 'Kampf-oder-Flucht'-Reaktion."
  },
  {
    id: "q10_b_138",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Parasympathikus?",
    answers: ["Teil des vegetativen Systems, der den Körper in Ruhe versetzt","Teil des vegetativen Systems, der den Körper leistungsbereit macht","Nur das Rückenmark innerhalb des knöchernen Wirbelkanals","Nur das willkürlich gesteuerte somatische Nervensystem"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Parasympathikus = 'Rest-and-Digest'."
  },
  {
    id: "q10_b_139",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Haut?",
    answers: ["Schutz, Temperaturregulation und Sinnesorgan","Nur die Bildung von Blutkörperchen im Knochenmark","Nur die Verdauung der Nahrung im Magen-Darm-Trakt","Nur der Gasaustausch beim Atmen in der Lunge"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Haut hat multiple Funktionen."
  },
  {
    id: "q10_b_140",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen angeborener und erlernter Immunität?",
    answers: ["Angeborene und erlernte Immunität sind in jeder Hinsicht völlig identisch","Angeboren ist unspezifisch, erlernt ist spezifisch und hat Gedächtnis","Angeboren ist grundsätzlich in jedem Fall hochspezifisch und langsam","Erlernt ist grundsätzlich in jedem Fall völlig unspezifisch und schnell"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das erworbene System lernt aus Kontakten mit Erregern."
  },
  {
    id: "q10_b_141",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Allergie?",
    answers: ["Nur eine Vergiftung durch bestimmte giftige Stoffe im Körper","Nur eine Infektion durch bestimmte Arten von Bakterien","Nur eine Mangelerscheinung bei starkem Vitamin- und Mineralmangel","Eine übersteigerte Immunreaktion gegen harmlose Stoffe"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Allergien sind Fehlregulationen des Immunsystems."
  },
  {
    id: "q10_b_142",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Virus und Bakterium?",
    answers: ["Viren sind grundsätzlich in jedem einzelnen Fall deutlich größer als alle Bakterien","Viren und Bakterien sind biologisch in jeder erdenklichen Hinsicht völlig identisch aufgebaut","Bakterien benötigen zwingend in jedem Fall eine fremde Wirtszelle zum Überleben","Viren sind keine Zellen und brauchen Wirtszellen, Bakterien sind eigenständige Zellen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Unterschiedliche Organisation und Vermehrung."
  },
  {
    id: "q10_b_143",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Antibiotika?",
    answers: ["Wirkstoffe gegen Viren", "Wirkstoffe gegen alle Erreger", "Nur Impfstoffe", "Wirkstoffe gegen Bakterien"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Antibiotika wirken nicht gegen Viren."
  },
  {
    id: "q10_b_144",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Resilienz im gesundheitlichen Kontext?",
    answers: ["Nur die allgemeine Stärke des körpereigenen Immunsystems im Körper","Nur die allgemeine körperliche Fitness eines gesunden Menschen","Nur die ausgewogene tägliche Ernährung eines erwachsenen Menschen","Die Fähigkeit, Belastungen zu bewältigen und sich zu erholen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Resilienz umfasst körperliche und psychische Aspekte."
  },
  {
    id: "q10_b_145",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen akuter und chronischer Erkrankung?",
    answers: ["Akute Erkrankungen sind grundsätzlich immer unheilbar", "Chronische Erkrankungen sind grundsätzlich immer harmlos", "Akut = plötzlich und kurz, chronisch = lang andauernd", "Akute und chronische Erkrankungen sind völlig identisch"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Zeitverlauf unterscheidet sie."
  },
  {
    id: "q10_b_146",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Lymphknoten?",
    answers: ["Filterung der Lymphe und Aktivierung von Immunzellen","Nur die Atmung über die feinen Lungenbläschen des Körpers","Nur die Bildung roter Blutkörperchen im Knochenmark","Nur die Verdauung von Nahrungsbestandteilen im Darm"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Lymphknoten sind wichtige Stationen der Immunabwehr."
  },
  {
    id: "q10_b_147",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen äußerer und innerer Atmung?",
    answers: ["Äußere = Gasaustausch in der Lunge, innere = Zellatmung","Äußere Atmung ist nur die Zellatmung im Gewebe des Körpers","Innere Atmung ist nur der Gasaustausch in der Lunge","Äußere und innere Atmung sind völlig identisch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Prozesse sind für die Energieversorgung nötig."
  },
  {
    id: "q10_b_148",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der pH-Wert des Magensaftes?",
    answers: ["Stark basisch (12–14)", "Stark sauer (ca. 1–2)", "Schwach sauer (5–6)", "Neutral (7)"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Salzsäure im Magen tötet viele Keime und aktiviert Enzyme."
  },
  {
    id: "q10_b_149",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Galle?",
    answers: ["Nur die Abwehr von Krankheitserregern", "Ausschließlich die Verdauung von Eiweißen", "Ausschließlich die Verdauung von Kohlenhydraten", "Emulgierung von Fetten zur besseren Verdauung"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Galle zerlegt Fette in kleinere Tröpfchen."
  },
  {
    id: "q10_b_150",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Nährstoffen und Ballaststoffen?",
    answers: ["Nährstoffe liefern Energie oder Bausteine, Ballaststoffe werden nicht verdaut","Nährstoffe werden in diesem Modell grundsätzlich niemals im Körper verdaut","Nährstoffe und Ballaststoffe sind in jeder Hinsicht völlig identisch aufgebaut","Ballaststoffe liefern in diesem Modell grundsätzlich immer sehr viel Energie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ballaststoffe fördern die Verdauung, liefern aber kaum Energie."
  },
  {"id":"k10bi101","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Photosynthese in …","answers":["Mitochondrien","Chloroplasten","Zellkern","Ribosomen"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Chloroplasten."},
  {"id":"k10bi102","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"DNA-Base A paart mit …","answers":["G","T","C","U"],"correct":1,"difficulty":"mittel","points":10,"explanation":"T."},
  {"id":"k10bi103","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Mitose erzeugt …","answers":["Gameten","Körperzellen diploid","Mutationen","Viren"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Körperzellen."},
  {"id":"k10bi104","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Enzyme sind meist …","answers":["Lipide","Proteine","DNA","Zucker"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Proteine."},
  {"id":"k10bi105","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Ökosystem = …","answers":["nur Tiere","Lebewesen + Umwelt","nur Klima","nur Boden"],"correct":1,"difficulty":"mittel","points":10,"explanation":"System."},
  {"id":"k10bi106","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Antibiotika gegen …","answers":["Viren","Bakterien","Knochen","Allergie"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Bakterien."},
  {"id":"k10bi107","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Selektion wirkt auf …","answers":["Genotyp immer sichtbar","Fitness","Mode","Zufall"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Fitness."},
  {"id":"k10bi108","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Blut transportiert …","answers":["nur Wasser","O₂/Nährstoffe","Knochen","Licht"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Stoffe."},
  {"id":"k10bi109","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Nerven leiten …","answers":["Blut","Impulse","Luft","Knochen"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Erregung."},
  {"id":"k10bi110","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Biodiversität = …","answers":["eine Art","Vielfalt","Klima","Städte"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Vielfalt."},
  {"id":"k10bi111","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Impfung aktiviert …","answers":["Verdauung","Immunsystem","Muskeln","Gehör"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Immun."},
  {"id":"k10bi112","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Zellatmung in …","answers":["Chloroplast","Mitochondrien","Zellwand","Vakuole"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Mitochondrien."},
  {"id":"k10bi113","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Art = …","answers":["beliebige Tiere","fortpflanzungsfähige Gruppe","Farbe","Größe"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Art."},
  {"id":"k10bi114","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Parasit … dem Wirt.","answers":["nützt","schadet","neutral","ersetzt"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Schaden."},
  {"id":"k10bi115","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Gene auf …","answers":["Blut","Chromosomen","Zähnen","Haaren"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Chromosomen."},
  {"id":"k10bi116","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Nachhaltigkeit: …","answers":["erschöpfen","Tragfähigkeit achten","nur Konsum","nur Wachstum"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Grenzen."},
  {"id":"k10bi117","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Haut schützt vor …","answers":["nur Kälte","Keimen u. a.","Schall","Magneten"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Schutz."},
  {"id":"k10bi118","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Bestäubung = …","answers":["Kernverschmelzung","Pollenübertragung","Keimung","Photosynthese"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Pollen."},
  {"id":"k10bi119","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Population = …","answers":["alle Arten","Art im Gebiet","Pflanzen","Klima"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Population."},
  {"id":"k10bi120","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Viren sind …","answers":["Zellen","keine vollständigen Zellen","Pflanzen","Bakterien"],"correct":1,"difficulty":"mittel","points":10,"explanation":"akaryotisch."},
  {"id":"k10bi121","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Nahrungskette start: …","answers":["Fleischfresser","Produzenten","Menschen","Pilze"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Pflanzen."},
  {"id":"k10bi122","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Insulin beeinflusst …","answers":["Hören","Blutzucker","Knochenfarbe","Haare"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Glucose."},
  {"id":"k10bi123","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Mutation = …","answers":["immer tödlich","DNA-Änderung","nur Phänotyp","Sport"],"correct":1,"difficulty":"mittel","points":10,"explanation":"DNA."},
  {"id":"k10bi124","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Symbiose: beide …","answers":["schaden","profitieren","neutral","parasitär"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Nutzen."},
  {"id":"k10bi125","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Lunge nimmt … auf.","answers":["CO₂","O₂","N₂","He"],"correct":1,"difficulty":"mittel","points":10,"explanation":"O₂."},
  {"id":"k10bi126","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Zellmembran ist …","answers":["starr","selektiv permeabel","dicht total","DNA"],"correct":1,"difficulty":"mittel","points":10,"explanation":"selektiv."},
  {"id":"k10bi127","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Insektenbeine: …","answers":["4","6","8","10"],"correct":1,"difficulty":"mittel","points":10,"explanation":"6."},
  {"id":"k10bi128","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Winterschlaf spart …","answers":["Licht","Energie","Wasser","Luft"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Energie."},
  {"id":"k10bi129","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Gentechnik greift in … ein.","answers":["Verhalten","Erbgut","Wetter","Sport"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Genom."},
  {"id":"k10bi130","category":"k10_biologie","area":"schule","grade":10,"subject":"biologie","topic":"erweiterung","question":"Artenschutz in situ = …","answers":["Zoo","im Lebensraum","Labor","Museum"],"correct":1,"difficulty":"mittel","points":10,"explanation":"vor Ort."}
];
