const questions_k8_physik = [
  {
    "id": "k8_phy_001",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "In welcher Basiseinheit des SI-Systems wird die elektrische Stromstärke gemessen?",
    "answers": [
      "In der Einheit Kilowatt (kW).",
      "In der Einheit Kiloohm (kΩ).",
      "In der Einheit Millivolt (mV).",
      "In der Einheit Ampere (A)."
    ],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die elektrische Stromstärke gibt an, wie viel Ladung pro Zeit durch einen Leiterquerschnitt fließt, und wird in Ampere (A) gemessen."
  },
  {
    "id": "k8_phy_002",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die Formel zur Berechnung der Geschwindigkeit v bei einer gleichförmigen Bewegung?",
    "answers": ["Die Formel lautet v = a · t².", "Die Formel lautet v = t/s.", "Die Formel lautet v = s/t.", "Die Formel lautet v = s · t."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Geschwindigkeit ist Strecke pro Zeit (v = s/t)."
  },
  {
    "id": "k8_phy_003",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie rechnet man eine Geschwindigkeit von m/s in km/h um?",
    "answers": ["Man dividiert den Wert in m/s einfach durch den Faktor 10.", "Man addiert zum Wert in m/s immer die feste Zahl 3,6 hinzu.", "Man zieht aus dem Wert in m/s die Quadratwurzel und multipliziert mit 2.", "Man multipliziert den Wert in m/s mit dem Faktor 3,6."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Da 1 km = 1000 m und 1 h = 3600 s sind, entspricht 1 m/s = 3,6 km/h."
  },
  {
    "id": "k8_phy_004",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt das Trägheitsgesetz (1. Newtonsches Axiom)?",
    "answers": [
      "Ein Körper verharrt in Ruhe oder gleichförmiger Bewegung, wenn keine Gesamtkraft wirkt.",
      "Ein Körper bewegt sich nur dann geradlinig weiter, wenn ständig eine Kraft auf ihn einwirkt.",
      "Jeder ruhende Körper beginnt sich von selbst zu beschleunigen, sobald keine Reibung mehr wirkt.",
      "Ein bewegter Körper kommt automatisch zur Ruhe, sobald genug Zeit vergangen ist."
    ],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ohne äußere Kraftkräfte behaart ein Körper in seinem Bewegungszustand (Ruhe oder geradlinig-gleichförmige Bewegung)."
  },
  {
    "id": "k8_phy_005",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet das Fundamentalgesetz der Mechanik (2. Newtonsches Axiom)?",
    "answers": ["Die Formel lautet F = m · v.", "Die Formel lautet F = m · a.", "Die Formel lautet F = m/a.", "Die Formel lautet F = 1/2 m v²."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Kraft ist das Produkt aus Masse und Beschleunigung (F = m · a). Die Einheit ist Newton (N)."
  },
  {
    "id": "k8_phy_006",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die Formel zur Berechnung der Gewichtskraft Fg auf der Erde?",
    "answers": ["Die Formel lautet Fg = g/m.", "Die Formel lautet Fg = m · g.", "Die Formel lautet Fg = m + g.", "Die Formel lautet Fg = m/g."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Gewichtskraft berechnet sich aus der Masse m multipliziert mit dem Ortsfaktor g (auf der Erde g ≈ 9,81 N/kg)."
  },
  {
    "id": "k8_phy_007",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie groß ist der durchschnittliche Ortsfaktor g auf der Erdoberfläche?",
    "answers": ["Er beträgt ungefähr 24,79 N/kg (oder m/s²).", "Er beträgt ungefähr 3,71 N/kg (oder m/s²).", "Er beträgt ungefähr 9,81 N/kg (oder m/s²).", "Er beträgt ungefähr 1,62 N/kg (oder m/s²)."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Auf der Erde gilt g ≈ 9,81 N/kg. Auf dem Mond beträgt er z. B. nur ca. 1,62 N/kg."
  },
  {
    "id": "k8_phy_008",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt das Wechselwirkungsgesetz (3. Newtonsches Axiom)?",
    "answers": [
      "Ein Körper bleibt so lange in Ruhe, bis eine deutlich spürbare äußere Kraft auf ihn einwirkt und ihn stört.",
      "Übt Körper A eine Kraft auf Körper B aus, so wirkt eine gleich große, entgegengesetzte Kraft von B auf A.",
      "Die Beschleunigung eines Körpers ist stets direkt proportional zur wirkenden Gesamtkraft, die auf ihn einwirkt.",
      "Zwei Körper üben nur dann Kräfte aufeinander aus, wenn sie sich unmittelbar berühren und aneinanderstoßen."
    ],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Das Wechselwirkungsprinzip heißt kurz: Actio = Reactio (Kräfte treten immer paarweise auf)."
  },
  {
    "id": "k8_phy_009",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie ist der physikalische Druck p definiert?",
    "answers": ["Als senkrecht auf eine Fläche wirkende Kraft pro Flächeninhalt (p = F/A).", "Als die Masse eines Körpers geteilt durch die Zeit seines freien Falls (p = m/t).", "Als eine Kraft, die parallel zu einer Fläche entlanggleitet (p = F · A).", "Als die Energiemenge, die pro Sekunde auf eine Fläche trifft (p = E/t)."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Druck ist Kraft pro Fläche (p = F/A). Seine SI-Einheit ist Pascal (Pa) bzw. N/m²."
  },
  {
    "id": "k8_phy_010",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "In welcher SI-Einheit wird der Druck p angegeben?",
    "answers": ["In Joule (J) beziehungsweise N · m.", "In Newton (N) beziehungsweise kg · m/s.", "In Watt (W) beziehungsweise J/s.", "In Pascal (Pa) beziehungsweise N/m²."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "1 Pascal (Pa) = 1 N/m². Häufig genutzte Einheiten sind auch Bar (1 bar = 100.000 Pa)."
  },
  {
    "id": "k8_phy_011",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wovon hängt der Schweredruck (hydrostatische Druck) in einer Flüssigkeit ab?",
    "answers": ["Von der Dichte der Flüssigkeit, der Fallbeschleunigung und der Tiefe.", "Ausschließlich von der Grundfläche und der Gesamtform des Gefäßes.", "Vom Gesamtvolumen der Flüssigkeit unabhängig von der Eintauchtiefe.", "Nur von der Außentemperatur und der Oberflächenspannung der Flüssigkeit."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Der Schweredruck berechnet sich nach der Formel p = ρ · g · h (Dichte ρ, Ortsfaktor g, Tiefe h)."
  },
  {
    "id": "k8_phy_012",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt das Gesetz von Archimedes über die Auftriebskraft FA?",
    "answers": ["Die Auftriebskraft entspricht immer genau der halben Gewichtskraft des eingetauchten Körpers.", "Die Auftriebskraft hängt allein von der Farbe der eingetauchten Körperoberfläche ab.", "Die Auftriebskraft entspricht der Gewichtskraft der verdrängten Flüssigkeitsmenge.", "Die Auftriebskraft wächst mit zunehmender Eintauchtiefe bis ins Unendliche an."],
    "correct": 2,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Archimedisches Prinzip: FA = mVerdrängt · g = ρMedium · VKörper · g."
  },
  {
    "id": "k8_phy_013",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wann schwimmt ein Körper in einer Flüssigkeit?",
    "answers": ["Wenn seine Gewichtskraft größer als die maximale Auftriebskraft ist.", "Wenn seine mittlere Dichte kleiner als die Dichte der Flüssigkeit ist.", "Wenn der Körper keinerlei Flüssigkeit verdrängen kann.", "Wenn die Dichte des Körpers exakt doppelt so groß wie die der Flüssigkeit ist."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ist ρKörper < ρFlüssigkeit, steigt der Körper auf und schwimmt an der Oberfläche (Gewichtskraft = Auftriebskraft im Teilvolumen)."
  },
  {
    "id": "k8_phy_014",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet das Ohmsche Gesetz zur Beschreibung von Stromkreisen?",
    "answers": ["Die Stromstärke ist proportional zum Quadrat des Widerstands (I = R²).", "Die Leistung ist der Quotient aus Widerstand und Spannung (P = R/U).", "Die Spannung berechnet sich aus Stromstärke mal Widerstand (U = R · I).", "Der Widerstand berechnet sich aus Spannung mal Stromstärke (R = U · I)."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Das Ohmsche Gesetz lautet U = R · I bzw. R = U/I."
  },
  {
    "id": "k8_phy_015",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "In welcher SI-Einheit wird der elektrische Widerstand R angegeben?",
    "answers": ["In Farad (F).", "In Ampere (A).", "In Ohm (Ω).", "In Coulomb (C)."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Der elektrische Widerstand hemmt den Stromfluss. Die Einheit ist Ohm (Ω = V/A)."
  },
  {
    "id": "k8_phy_016",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verhält sich die Gesamtstromstärke Iges in einer Reihenschaltung (Serienschaltung)?",
    "answers": ["Die Stromstärke halbiert sich mit jedem zusätzlich eingebauten Widerstand.", "Die Stromstärke ist an jeder Stelle der Reihenschaltung gleich groß.", "Die Stromstärke ist am Pluspol doppelt so hoch wie am Minuspol.", "Die Gesamtstromstärke ist die Summe der Einzelstromstärken durch alle Bauteile."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "In unverzweigten Stromkreisen (Reihenschaltung) fließt überall derselbe Strom: Iges = I₁ = I₂ = …."
  },
  {
    "id": "k8_phy_017",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verhalten sich die Teilspannungen U₁, U₂ in einer Parallelschaltung?",
    "answers": ["An allen parallelen Zweigen addieren sich die Teilspannungen stets zur vollen Gesamtspannung auf.", "Die Spannung ist an dem Zweig mit dem größten Widerstand stets am kleinsten.", "An allen parallelen Zweigen liegt dieselbe Spannung an (Uges = U₁ = U₂).", "Die Teilspannungen verhalten sich stets umgekehrt proportional zu den Widerständen."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "In einer Parallelschaltung liegt an jedem Bauteil die volle Quellspannung an (Uges = U₁ = U₂)."
  },
  {
    "id": "k8_phy_018",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie berechnet sich der Gesamtwiderstand Rges zweier in Reihe geschalteter Widerstände R₁ und R₂?",
    "answers": ["Durch Subtraktion des kleineren vom größeren Widerstand.", "Durch Produktbildung der Einzelwiderstände (Rges = R₁ · R₂).", "Durch einfache Addition der Einzelwiderstände (Rges = R₁ + R₂).", "Durch Kehrwertbildung (Rges = 1/R₁ + 1/R₂)."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Bei der Reihenschaltung addieren sich die Widerstände: Rges = R₁ + R₂ + …."
  },
  {
    "id": "k8_phy_019",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was passiert mit dem Gesamtwiderstand einer Parallelschaltung, wenn man einen weiteren Widerstand parallel hinzufügt?",
    "answers": ["Der Gesamtwiderstand steigt an und wird größer als der größte Einzelwiderstand.", "Der Gesamtwiderstand sinkt und ist kleiner als der kleinste Einzelwiderstand.", "Der Gesamtwiderstand bleibt gleich dem Durchschnittswert aller Einzelwiderstände.", "Der Gesamtwiderstand entspricht genau der Summe aller einzelnen Widerstände."],
    "correct": 1,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Ein zusätzlicher paralleler Pfad öffnet eine neue 'Leitungsschneise'. Der Gesamtwiderstand sinkt dadurch (Kehrwertzusammenhang: 1/Rges = 1/R₁ + 1/R₂). "
  },
  {
    "id": "k8_phy_020",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie berechnet sich die elektrische Leistung P eines elektrischen Verbrauchers?",
    "answers": ["Aus Stromstärke mal Zeit (P = I · t).", "Aus Spannung mal Widerstand (P = U · R).", "Aus Spannung durch Widerstand (P = U/R).", "Aus Spannung mal Stromstärke (P = U · I)."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die elektrische Leistung berechnet sich nach P = U · I. Die Einheit ist Watt (W)."
  },
  {
    "id": "k8_phy_021",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die Einheit für die elektrische Energie im Alltag (z. B. auf Stromrechnungen)?",
    "answers": ["Kilowattstunde (kWh).", "Kilowatt pro Stunde (kW/h).", "Ampere pro Volt (A/V).", "Newtonmeter pro Sekunde (Nm/s)."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Elektrische Energie E = P · t wird im Alltag in Kilowattstunden (1 kWh = 3,6 · 10⁶ J) gemessen."
  },
  {
    "id": "k8_phy_022",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was beschreibt die spezifische Wärmekapazität c eines Stoffes?",
    "answers": ["Die Energie, die nötig ist, um 1 kg eines Stoffes um 1 K (oder 1°C) zu erwärmen.", "Die Zeitspanne, die 1 kg eines Stoffes braucht, um vollständig zu schmelzen und ganz flüssig zu werden.", "Die Kraft, die nötig ist, um 1 kg eines Stoffes anzuheben und dabei um 1 K zu drehen.", "Die Masse, die ein Stoff bei einer Temperaturänderung von 1 K durch Verdampfung verliert."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Die spezifische Wärmekapazität c gibt an, wie viel Wärme Q zugeführt werden muss: Q = c · m · ΔT."
  },
  {
    "id": "k8_phy_023",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die Grundgleichung der Wärmelehre zur Berechnung der aufgenommenen Wärme Q?",
    "answers": ["Die Formel lautet Q = m · g · h.", "Die Formel lautet Q = c · m · ΔT.", "Die Formel lautet Q = 1/2 c · m².", "Die Formel lautet Q = (c · m)/(ΔT)."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Wärmemenge Q hängt ab von Stoffkonstante c, Masse m und Temperaturdifferenz ΔT."
  },
  {
    "id": "k8_phy_024",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche der folgenden Stoffe besitzt eine außergewöhnlich hohe spezifische Wärmekapazität?",
    "answers": ["Festes Kupfer (c ≈ 0,38 kJ/(kg·K)).", "Reines Eisenmetall (c ≈ 0,45 kJ/(kg·K)).", "Flüssiges Wasser (c ≈ 4,18 kJ/(kg·K)).", "Flüssiges Quecksilber (c ≈ 0,14 kJ/(kg·K))."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Wasser speichert Wärme hervorragend (c ≈ 4180 J/(kg·K)), weshalb es als Kühlmittel und Wärmespeicher dient."
  },
  {
    "id": "k8_phy_025",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie unterscheiden sich Wärmeübertragung durch Wärmeleitung und Wärmeströmung (Konvektion)?",
    "answers": [
      "Bei der Wärmeleitung wandert Materie mit, bei der Konvektion bleiben die Teilchen an festen Plätzen.",
      "Beide Übertragungsarten funktionieren ausschließlich im nahezu luftleeren Raum ohne jede Materie.",
      "Wärmeleitung findet nur in Flüssigkeiten statt, Konvektion dagegen nur in massiven Metallen.",
      "Bei Konvektion wandert Materie mit, bei Wärmeleitung verharren die Teilchen um feste Plätze."
    ],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Wärmeleitung erfolgt in Festkörpern ohne Stofftransport. Konvektion erfolgt in Flüssigkeiten/Gasen durch Mitführen erwärmter Materie."
  },
  {
    "id": "k8_phy_026",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Auf welchem Mechanismus beruht der Energietransport der Sonne zur Erde durch das Weltall?",
    "answers": ["Auf Wärmeleitung durch die dünnen Gasteilchen zwischen Sonne und Erde.", "Ausschließlich auf Wärmestrahlung.", "Auf Konvektionsströmungen im nahezu luftleeren Raum zwischen den Planeten.", "Auf Schallwellen, die sich durch das Vakuum des Weltalls ausbreiten."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Da das Weltall ein Vakuum ist, kann Wärme nur über Wärmestrahlung (Infrarot- und Lichtwellen) übertragen werden."
  },
  {
    "id": "k8_phy_027",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet der 1. Hauptsatz der Thermodynamik?",
    "answers": ["Energie kann weder erzeugt noch vernichtet, sondern nur umgewandelt werden.", "Wärme fließt von selbst stets nur vom kälteren hin zum wärmeren Körper über und niemals zurück.", "Die Entropie eines geschlossenen physikalischen Systems nimmt mit der Zeit immer weiter ab.", "Der absolute Nullpunkt der Temperaturskala liegt genau bei 0°C Celsius."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Der 1. Hauptsatz ist der Energieerhaltungssatz: Die Änderung der inneren Energie entspricht der zugeführten Wärme plus verrichteter Arbeit (ΔU = Q + W)."
  },
  {
    "id": "k8_phy_028",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Temperatur entspricht dem absoluten Nullpunkt der Kelvin-Skala in Celsius?",
    "answers": ["Exakt 0,00°C.", "Exakt -273,15°C.", "Exakt -100,00°C.", "Exakt -459,67°C."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "0 K = -273,15°C. Bei dieser Temperatur steht jegliche Molekularbewegung theoretisch still."
  },
  {
    "id": "k8_phy_029",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was beschreibt die Schmelzwärme qs eines festen Stoffes?",
    "answers": ["Die Temperatur, bei der ein fester Stoff spontan seine Farbe vollständig ändert und dabei schmilzt.", "Die Wärmemenge, die beim Gefrieren einer Flüssigkeit pro Sekunde wieder abgegeben wird.", "Der Druckanstieg, der beim Erhitzen eines Metallblocks bis zum Siedepunkt entsteht.", "Die Energie, die benötigt wird, um 1 kg eines Stoffes am Schmelzpunkt zu verflüssigen."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Die spezifische Schmelzwärme qs beschreibt die Energie für den Phasenübergang fest → flüssig ohne Temperaturerhöhung (Q = m · qs)."
  },
  {
    "id": "k8_phy_030",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was geschieht mit der Temperatur eines Stoffes während des reinen Phasenübergangs (z. B. beim Sieden von Wasser)?",
    "answers": ["Die Temperatur schwankt unregelmäßig zwischen 0°C und 100°C.", "Die Temperatur fällt schlagartig auf den gefrierpunkt ab.", "Die Temperatur bleibt konstant, bis der Phasenübergang abgeschlossen ist.", "Die Temperatur steigt doppelt so schnell wie vor dem Übergang an."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Während des Übergangs (Schmelzen oder Sieden) wird die zugeführte Energie für das Aufbrechen der Bindungen genutzt, nicht für eine Temperaturerhöhung."
  },
  {
    "id": "k8_phy_031",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verändert sich die Dichte der meisten festen und flüssigen Stoffe bei Erwärmung?",
    "answers": ["Die Dichte verdoppelt sich pro 10°C Erwärmung.", "Die Dichte bleibt bei allen Temperaturen exakt unverändert.", "Die Dichte nimmt ab, da sich der Stoff ausdehnt.", "Die Dichte nimmt stark zu, da die Teilchen schwerer werden."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Erwärmung führt zu größerem Raumbedarf der Teilchen (Volumenzunahme). Da die Masse konstant bleibt, sinkt die Dichte (ρ = m/V)."
  },
  {
    "id": "k8_phy_032",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was versteht man unter der sogenannten 'Dichteanomalie des Wassers'?",
    "answers": ["Wasser zieht sich beim Sieden schlagartig zusammen.", "Wasser erreicht seine höchste Dichte im gefrorenen Zustand bei -20°C.", "Wasser besitzt seine höchste Dichte bei etwa +4°C.", "Wasser dehnt sich beim Erwärmen von 0°C auf 4°C stärker aus als alle Metalle."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Flüssiges Wasser hat bei +4°C seine größte Dichte (1 g/cm³). Eis hat eine geringere Dichte und schwimmt deshalb oben."
  },
  {
    "id": "k8_phy_033",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welcher physikalische Effekt ermöglicht das Funktionieren eines Bimetallstreifens?",
    "answers": [
      "Unterschiedliche elektrische Leitfähigkeit der beiden fest verbundenen Metallschichten.",
      "Unterschiedliche Farbtönung der beiden Metalle bei intensiver Sonneneinstrahlung.",
      "Unterschiedliche Magnetisierbarkeit der beiden Metalle bei normaler Zimmertemperatur.",
      "Unterschiedliche Längenausdehnung zweier fest verbundener Metalle bei Erwärmung."
    ],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Zwei Metalle mit verschiedenen Ausdehnungskoeffizienten verbiegen den Streifen bei Temperaturänderung (Anwendung: Thermostate)."
  },
  {
    "id": "k8_phy_034",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was versteht man unter der mechanischen Arbeit W in der Physik?",
    "answers": ["Das Produkt aus Masse und verrichteter Geschwindigkeit (W = m · v).", "Das Produkt aus Kraft und Weg in Kraftrichtung (W = F · s).", "Die Summe aus potenzieller und kinetischer Leistung.", "Den Quotienten aus Kraft und verstrichener Zeit (W = F/t)."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Arbeit ist Kraft mal Weg (W = F · s). Die SI-Einheit ist Joule (J) bzw. Newtonmeter (Nm)."
  },
  {
    "id": "k8_phy_035",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die Goldene Regel der Mechanik für einfache Maschinen (z. B. Hebel, Flaschenzug)?",
    "answers": ["Die verrichtete Arbeit halbiert sich bei jeder Rolle.", "Die Eingangsleistung ist immer größer als die zugeführte Kraft.", "Was man an Kraft spart, muss man an Weg zusetzen.", "Kräfte können vervielfacht werden, ohne dass sich der Weg verlängert."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Goldene Regel der Mechanik besagt: W = F₁ · s₁ = F₂ · s₂. Man kann zwar Kraft sparen, nicht aber physikalische Arbeit."
  },


  {
    "id": "k8_ph_036",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was beschreibt die 'Lichtbrechung' beim Übergang eines Lichtstrahls von Luft in Glas?",
    "answers": [
      "Die Richtungsänderung des Lichtstrahls aufgrund unterschiedlicher Ausbreitungsgeschwindigkeiten.",
      "Die vollständige Absorption des einfallenden Lichtstrahls beim Eintritt in dickes Glas ganz ohne Rest.",
      "Die sofortige Aufspaltung des Lichtstrahls in mehrere getrennte, farbige Einzelstrahlen.",
      "Die Verdopplung der Lichtgeschwindigkeit beim Übergang in ein dichteres Medium wie Glas."
    ],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Beim Übergang in ein optisch dichteres Medium (wie Glas oder Wasser) verlangsamt sich das Licht und wird zum Einfallslot hin gebrochen."
  },
  {
    "id": "k8_ph_037",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie wird ein Lichtstrahl gebrochen, wenn er aus einem optisch dichteren Medium (z. B. Glas) in ein optisch dünneres Medium (z. B. Luft) übertritt?",
    "answers": [
      "Er läuft ohne jegliche Richtungsänderung exakt geradeaus weiter.",
      "Er wird vom Einfallslot weg gebrochen.",
      "Er wird zum Einfallslot hin gebrochen.",
      "Er wird im rechten Winkel nach hinten reflektiert."
    ],
    "correct": 1,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Beim Übergang von optisch dicht zu optisch dünn erhöht sich die Ausbreitungsgeschwindigkeit des Lichts, weshalb die Brechung vom Lot weg erfolgt."
  },
  {
    "id": "k8_ph_038",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was versteht man in der Optik unter der 'Totalreflexion'?",
    "answers": [
      "Das gleichmäßige Brechen aller Spektralfarben des Lichts im exakt selben Winkel an jedem beliebigen Prisma auf der Welt.",
      "Die vollständige Umwandlung von Lichtenergie in Wärmeenergie beim Durchgang durch dickes Glas.",
      "Die spiegelglatte Reflexion von Licht an einer absolut ebenen, frisch polierten Metallplatte im Freien.",
      "Das Phänomen, dass Licht beim Übergang ins dünnere Medium ab einem bestimmten Winkel vollständig reflektiert wird."
    ],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Übersteigt der Einfallswinkel beim Übergang von einem optisch dichteren in ein dünneres Medium den Grenzwinkel, tritt kein Licht mehr aus – es wird vollständig reflektiert (Anwendung: Glasfaserkabel)."
  },
  {
    "id": "k8_ph_039",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Form besitzt eine 'Sammellinse' (Konvexlinse)?",
    "answers": [
      "Sie ist am Rand dicker als in der Mitte.",
      "Sie ist auf beiden Seiten vollkommen plan und flach.",
      "Sie besitzt eine quadratische Grundfläche mit Löchern.",
      "Sie ist in der Mitte dicker als am Rand."
    ],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Eine Sammellinse (Konvexlinse) ist in der Mitte wölbt/dicker als am äußeren Rand und bündelt parallel einfallende Lichtstrahlen im Brennpunkt."
  },
  {
    "id": "k8_ph_040",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie heißen die Linsen, die in der Mitte dünner sind als am Rand und parallel einfallendes Licht streuen?",
    "answers": ["Sammellinsen, auch Konvexlinsen genannt.", "Zerstreuungslinsen.", "Bikonvexe Streulinsen mit Rand.", "Planlinsen ohne jede Wölbung."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Zerstreuungslinsen (Konkavlinsen) sind innen dünner als außen. Sie lassen parallel einfallende Lichtstrahlen auseinanderlaufen (streuen)."
  },
  {
    "id": "k8_ph_041",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was versteht man unter dem 'Brennpunkt' (Fokus) einer Sammellinse?",
    "answers": ["Der Punkt, in dem sich parallel zur optischen Achse einfallende Lichtstrahlen nach der Brechung schneiden.", "Der Ort, an dem sich zwei benachbarte Sammellinsen exakt berühren und dabei Wärme freisetzen.", "Der Mittelpunkt der Linse, in dem sich angeblich alle Farben des einfallenden Sonnenlichts vollständig vermischen.", "Der äußere Rand der Linse, an dem einfallendes Licht stets vollständig reflektiert wird."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Parallel einfallende Lichtstrahlen werden von einer Sammellinse so gebrochen, dass sie sich hinter der Linse im Brennpunkt F vereinigen."
  },
  {
    "id": "k8_ph_042",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "In welcher Einheit wird die Brechwert (Dioptrie) einer Linse gemessen und wie hängt er mit der Brennweite f zusammen?",
    "answers": ["In Volt (V); der Brechwert gibt die Spannung der Lichtteilchen an.", "In Dioptrien (dpt = 1/m); der Brechwert ist der Kehrwert der Brennweite.", "In Newton (N); der Brechwert beschreibt die Masse der Linse pro Meter.", "In Watt (W); der Brechwert entsteht durch Multiplikation von Brennweite und Linsendurchmesser."],
    "correct": 1,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Der Brechwert D berechnet sich als Kehrwert der Brennweite in Metern: D = 1/f. Je kürzer die Brennweite, desto höher der Brechwert in Dioptrien (1/m)."
  },
  {
    "id": "k8_ph_043",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Augenfehlzsichtigkeit liegt vor, wenn das Bild weit entfernter Gegenstände vor der Netzhaut entsteht?",
    "answers": [
      "Kurzsichtigkeit (Myopie).",
      "Farbenblindheit.",
      "Grauer Star.",
      "Weitsichtigkeit (Hyperopie)."
    ],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Bei Kurzsichtigkeit ist der Augapfel meist zu lang, sodass der Brennpunkt paralleler Strahlen vor der Netzhaut liegt. Man benötigt Zerstreuungslinsen zur Korrektur."
  },
  {
    "id": "k8_ph_044",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was beschreibt der Begriff 'Spektrum' des weißen Lichts beim Durchgang durch ein Glasprisma?",
    "answers": ["Die Aufspaltung des weißen Lichts in seine Spektralfarben.", "Die vollständige Auslöschung des weißen Lichts beim Durchgang durch das Prisma.", "Die Umwandlung des weißen Lichts in unsichtbare Infrarotstrahlung im Prisma.", "Die Verdopplung der Helligkeit des Lichts beim Durchgang durch das Glasprisma."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Unterschiedliche Farben (Wellenlängen) werden im Glas unterschiedlich stark gebrochen. Weißes Licht wird dadurch in Rot, Orange, Gelb, Grün, Blau und Violett zerlegt."
  },
  {
    "id": "k8_ph_045",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche physikalische Größe gibt an, wie viele Ladungen pro Sekunde durch den Querschnitt eines Leiters fließen?",
    "answers": ["Der elektrische Widerstand R im Draht.", "Die elektrische Stromstärke I.", "Die elektrische Leistung P im Kabel.", "Die elektrische Spannung U am Pol."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Stromstärke I beschreibt die Ladungsmenge Q, die pro Zeitspanne t durch eine Leitung fließt (I = Q/t). Einheiten: Ampere (A)."
  },
  {
    "id": "k8_ph_046",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welches Messgerät verwendet man zur Messung der elektrischen Stromstärke und wie wird es in den Stromkreis geschaltet?",
    "answers": ["Ein Voltmeter, geschaltet parallel zum Verbraucher.", "Ein Ohmmeter, geschaltet direkt an die Spannungsquelle.", "Ein Amperemeter, geschaltet in Reihe.", "Ein Barometer, frei im Raum aufgestellt."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Das Amperemeter misst den fließenden Strom und muss daher in Reihe (in Serie) in den Stromkreis eingebaut werden, damit der gesamte Strom durch das Gerät fließt."
  },
  {
    "id": "k8_ph_047",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was gibt die elektrische Spannung U an?",
    "answers": ["Die Anzahl der Elektronen, die insgesamt im gesamten Kabel vorhanden sind.", "Die Wärme, die ein Kabel jede Minute an die umgebende Luft abgibt.", "Die Kraft, mit der Protonen im Leiter gegeneinander stoßen und reiben.", "Der 'Druck' bzw. Antrieb des elektrischen Stroms zwischen zwei Punkten."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Spannung U (Einheit Volt, V) gibt das Potenzialgefälle an und beschreibt, wie stark die Elektronen im Stromkreis angetrieben werden."
  },
  {
    "id": "k8_ph_048",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie wird ein Spannungsmessgerät (Voltmeter) im Schaltplan korrekt angeschlossen?",
    "answers": [
      "In Reihe direkt zwischen der Batterie und dem zu messenden Bauteil.",
      "Parallel zum Bauteil, dessen Spannung gemessen werden soll.",
      "Immer außerhalb des vollständig geschlossenen Stromkreises am Kabelende.",
      "Parallel zur Batterie, aber niemals zum eigentlichen Bauteil selbst."
    ],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Das Voltmeter misst die Potenzialdifferenz (Spannungsabfall) zwischen zwei Punkten und wird daher parallel zum Verbraucher angeschlossen."
  },
  {
    "id": "k8_ph_049",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet das Ohmsche Gesetz in Formelform?",
    "answers": ["U = I/R", "U = R · I", "I = U · R", "R = U · I"],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Das Ohmsche Gesetz besagt, dass die Spannung U proportional zur Stromstärke I ist: U = R · I bzw. R = U/I."
  },
  {
    "id": "k8_ph_050",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Durch einen Widerstand von 20 Ω fließt ein Strom von 0,5 A. Wie groß ist die anliegende Spannung?",
    "answers": ["2,5 Volt.", "100 Volt.", "10 Volt.", "40 Volt."],
    "correct": 2,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Nach dem Ohmschen Gesetz rechnet man: U = R · I = 20 Ω · 0,5 A = 10 V."
  },
  {
    "id": "k8_ph_051",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verhält sich die Gesamtspannung Ugesamt in einer Reihenschaltung von zwei Verbrauchern?",
    "answers": ["Die Gesamtspannung ist an allen Bauteilen identisch groß: Ugesamt = U₁ = U₂.", "Die Gesamtspannung berechnet sich über das Produkt der Widerstände.", "Die Gesamtspannung halbiert sich mit jedem zusätzlichen Kabel.", "Die Gesamtspannung ist die Summe der Teilspannungen: Ugesamt = U₁ + U₂."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "In einer Reihenschaltung teilt sich die Quellspannung auf die einzelnen Verbraucher auf: Ugesamt = U₁ + U₂ + ...."
  },
  {
    "id": "k8_ph_052",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verhält sich die Stromstärke I in allen Bauteilen einer Reihenschaltung?",
    "answers": ["Die Stromstärke nimmt vom Pluspol zum Minuspol hin stetig immer weiter ab.", "Die Stromstärke ist am Widerstand mit dem größten Wert stets am kleinsten.", "Die Stromstärke teilt sich an jedem einzelnen Bauteil stets zu gleichen Teilen genau auf.", "Die Stromstärke ist an jeder Stelle im unverzweigten Stromkreis exakt gleich groß."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Da in einem unverzweigten Stromkreis (Reihenschaltung) keine Ladungen verloren gehen, ist die Stromstärke I überall gleich: I₁ = I₂ = Igesamt."
  },
  {
    "id": "k8_ph_053",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Aussage gilt für die elektrische Spannung U an parallel geschalteten Verbrauchern?",
    "answers": ["An allen parallelen Zweigen liegt dieselbe Spannung an: Ugesamt = U₁ = U₂.", "Die Spannung teilt sich an jedem Zweig proportional zum jeweiligen Widerstand genau auf.", "Die Spannung sinkt in dem Zweig mit dem dünnsten Draht sofort auf null Volt.", "Die Spannung verdoppelt sich bei jedem zusätzlich hinzugefügten parallelen Zweig."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "In einer Parallelschaltung sind alle Zweige direkt mit den gleichen zwei Potenzialknoten verbunden, weshalb an jedem Zweig die volle Quellspannung anliegt."
  },
  {
    "id": "k8_ph_054",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt die 1. Kirchhoffsche Regel (Knotenpunktregel) für elektrische Stromkreise?",
    "answers": ["An jedem Knotenpunkt im Stromkreis geht genau die Hälfte des Stroms als Wärme dauerhaft verloren.", "Die Spannung an einem Knotenpunkt verdoppelt sich mit jedem zusätzlichen Zweig sofort.", "Der elektrische Widerstand sinkt an jedem Knotenpunkt automatisch schlagartig auf null.", "Die Summe aller zufließenden Stromstärken ist gleich der Summe aller abfließenden Stromstärken."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Ladungen können sich nicht anstauen oder auflösen: Am Verzweigungsknoten gilt Σ Izu = Σ Iab."
  },
  {
    "id": "k8_ph_055",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verändert sich der Gesamtwiderstand Rgesamt, wenn man zu einem Verbraucher einen weiteren Widerstand in Reihe schaltet?",
    "answers": ["Der Gesamtwiderstand bleibt trotz der Erweiterung völlig unverändert und gleich.", "Der Gesamtwiderstand fällt durch die zusätzliche Reihenschaltung auf null Ohm.", "Der Gesamtwiderstand vergrößert sich (Rgesamt = R₁ + R₂).", "Der Gesamtwiderstand verringert sich um den Wert des neuen Widerstands."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Bei der Reihenschaltung addieren sich die Widerstände der einzelnen Bauteile: Der Gesamtwiderstand steigt."
  },
  {
    "id": "k8_ph_056",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verändert sich der Gesamtwiderstand einer Schaltung, wenn man weitere Verbraucher parallel hinzufügt?",
    "answers": ["Der Gesamtwiderstand steigt mit jedem zusätzlich hinzugeschalteten parallelen Zweig an.", "Der Gesamtwiderstand verdoppelt sich automatisch bei jedem neu hinzugefügten Verbraucher.", "Der Gesamtwiderstand hängt ausschließlich von der Farbe der Kabelisolierung ab.", "Der Gesamtwiderstand sinkt."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Durch zusätzliche parallele Zweige entstehen weitere Strömungswege für Elektronen (mehr 'Leitungsquerschnitt'). Dadurch sinkt der Gesamtwiderstand der Schaltung."
  },
  {
    "id": "k8_ph_057",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Von welchen Materialeigenschaften hängt der elektrische Widerstand R eines metallischen Drahtes ab?",
    "answers": ["Vom Werkstoff (spezifischer Widerstand), der Drahtlänge und der Querschnittsfläche.", "Nur vom Hersteller des Drahtes und der Farbe seiner äußeren Verpackung im Baumarktladen.", "Ausschließlich von der genauen Uhrzeit, zu der der Draht gerade verwendet wird.", "Nur von der Entfernung des Drahtes zum nächsten Fenster im selben Raum."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Es gilt R = ρ · l/A. Der Widerstand wächst mit der Länge l und sinkt mit größerer Querschnittsfläche A."
  },
  {
    "id": "k8_ph_058",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie berechnet man die elektrische Leistung P eines elektrischen Geräts aus Spannung U und Stromstärke I?",
    "answers": ["P = U + I", "P = I/(U²)", "P = U · I", "P = U/I"],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die elektrische Leistung P ist das Produkt aus Spannung U und Stromstärke I (P = U · I). Einheit: Watt (W)."
  },
  {
    "id": "k8_ph_059",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Ein Wasserkocher wird an das Haushaltsnetz (230 V) angeschlossen. Es fließt ein Strom von 10 A. Welche elektrische Leistung erbringt das Gerät?",
    "answers": ["2300 Watt", "230 Watt", "4600 Watt", "100 Watt"],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Über P = U · I rechnet man: P = 230 V · 10 A = 2300 W = 2,3 kW."
  },
  {
    "id": "k8_ph_060",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "In welcher Maßeinheit wird die verbrauchte elektrische Energie E auf der Stromabrechnung für Haushalte üblicherweise angegeben?",
    "answers": ["In Voltampere pro Minute (VAm).", "In Ampere pro Stunde (A/h).", "In Kilowattstunden (kWh).", "In Newtonmeter (Nm)."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die elektrische Energie berechnet sich über E = P · t. Neben der SI-Einheit Joule (J = Ws) nutzt man im Haushalt Kilowattstunden (kWh)."
  },
  {
    "id": "k8_ph_061",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Schutzvorrichtung im Sicherungskasten schützt Haushaltsstromkreise vor Überlastung und Kurzschlüssen?",
    "answers": ["Ein kleiner Spannungswandler im Sicherungskasten.", "Ein zusätzlicher Generator im Sicherungskasten.", "Der Leitungsschutzschalter.", "Ein einfacher Transformator im Sicherungskasten."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Fließt durch zu viele Geräte oder einen Kurzschluss zu viel Strom, unterbricht die Sicherung schlagartig den Stromkreis, um Kabelbrände zu verhindern."
  },
  {
    "id": "k8_ph_062",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was unterscheidet den Schutzleiter (grün-gelbes Kabel) von den anderen Leitungen im Haushaltsnetz?",
    "answers": [
      "Er leitet Fehlerströme bei defekten Metallgehäusen gefahrlos in die Erde ab.",
      "Er verdoppelt automatisch die Spannung im gesamten Hausnetz sofort auf 400 Volt.",
      "Er transportiert allein den normalen Betriebsstrom von der Steckdose zum Verbraucher.",
      "Er schaltet Geräte bei längerer Inaktivität automatisch komplett vom Netz ab."
    ],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Der Schutzleiter (PE) sorgt dafür, dass bei einem Gehäuseschluss die Sicherung oder der FI-Schalter auslöst, bevor ein Mensch einen tödlichen Schlag bekommt."
  },
  {
    "id": "k8_ph_063",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was geschieht bei einem 'Kurzschluss' in einem elektrischen Stromkreis?",
    "answers": ["Der Widerstand steigt plötzlich sehr stark an und der ganze Stromkreis erkaltet dabei völlig.", "Die Spannung der angeschlossenen Batterie sinkt langsam auf einen negativen Wert ab und bleibt so.", "Die Ladungen fließen für einen kurzen Moment plötzlich rückwärts durch sämtliche Messgeräte im gesamten Stromkreis und darüber hinaus.", "Hin- und Rückleiter berühren sich direkt, wodurch der Widerstand extrem fällt und die Stromstärke gefährlich ansteigt."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Wird der Verbraucher überbrückt (R → 0), wächst die Stromstärke nach I = U/R drastisch an, was zur Überhitzung der Leitungen führt."
  },
  {
    "id": "k8_ph_064",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Wirkung zeigt der elektrische Strom beim Durchfließen einer Spule mit Eisenkern?",
    "answers": ["Das Eisen verliert dauerhaft jegliche Masse.", "Die Spule wandelt sich vollständig in rein optisches Licht um.", "Es bildet sich ein Vakuum im Umkreis der Spule.", "Es entsteht ein steuerbares Magnetfeld."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ein stromdurchflossener Leiter erzeugt ein Magnetfeld. Durch das Wickeln zu einer Spule mit Eisenkern verstärkt sich dieses Feld stark (Elektromagnet)."
  },
  {
    "id": "k8_ph_065",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Auf welchem physikalischen Prinzip basiert die Funktion eines Elektromotors?",
    "answers": ["Die Kraftwirkung auf einen stromdurchflossenen Leiter im Magnetfeld.", "Die Wärmeausdehnung eines stromdurchflossenen Metallstabs innerhalb eines Magnetfeldes.", "Die chemische Reaktion zweier verschiedener Elektrolytlösungen in einer Batteriezelle.", "Die Lichtbrechung an einer stromdurchflossenen Glasoberfläche im elektrischen Feld."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Ein Elektromagnet im Inneren des Motors erfährt im Feld von Permanentmagneten Abstumpfung bzw. Anziehungskraft (Lorentzkraft) und versetzt den Rotor in Rotation."
  },
  {
    "id": "k8_ph_066",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt die elektromagnetische Induktion?",
    "answers": [
      "Durch das bloße Erwärmen eines Kabels entsteht dort automatisch von selbst ein elektrischer Strom.",
      "Durch das feste Zusammenpressen zweier Metalle entsteht sofort ein sehr starkes Magnetfeld.",
      "Durch zeitliche Änderung eines Magnetfeldes in einer Spule wird eine elektrische Spannung erzeugt.",
      "Durch die Bestrahlung einer Spule mit hellem Licht entsteht darin eine sehr hohe Spannung."
    ],
    "correct": 2,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Wird ein Magnet in einer Spule bewegt (oder das Magnetfeld verändert), wird in der Spule eine Induktionsspannung erzeugt (Grundprinzip des Generators)."
  },
  {
    "id": "k8_ph_067",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welches Gerät wandelt mechanische Bewegungsenergie mithilfe von Induktion in elektrische Energie um?",
    "answers": ["Ein Generator.", "Ein gewöhnlicher elektrischer Tauchsieder.", "Ein simpler Bimetallschalter zweier Metalle.", "Ein einfacher Elektromotor mit Magnet."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ein Generator nutzt die Drehung eines Magneten in/an einer Spule, um mechanische Energie in elektrische Energie umzuwandeln."
  },
  {
    "id": "k8_ph_068",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie ist ein einfacher Transformator aufgebaut?",
    "answers": [
      "Aus zwei parallel geschalteten Batterien, verbunden über einen einzelnen Kondensator.",
      "Aus einer Glühlampe, die fest an eine gewölbte Sammellinse gekoppelt ist.",
      "Aus einem starken Permanentmagneten zwischen zwei blanken Kupferplatten.",
      "Aus einem geschlossenen Eisenkern mit einer Primär- und einer Sekundärspule."
    ],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ein Transformator besteht aus zwei getrennten Spulen auf einem gemeinsamen Eisenkern zur Umwandlung von Wechselspannungen."
  },
  {
    "id": "k8_ph_069",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verhalten sich die Spannungen U₁ und U₂ an den Spulen eines idealen Transformators zu den Windungszahlen N₁ und N₂?",
    "answers": ["Die Spannungen verhalten sich genau wie die Windungszahlen: U₁/U₂ = N₁/N₂.", "Die Spannung verhält sich stets genau umgekehrt proportional zu den beiden Windungszahlen der Spulen.", "Die Windungszahlen der beiden Spulen haben keinerlei Einfluss auf die Ausgangsspannung.", "Die Spannung an der Sekundärspule ist stets exakt doppelt so hoch wie an der Primärspule."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Beim Transformator gilt das Übersetzungsverhältnis der Spannungen gleich dem Verhältnis der Windungszahlen: U₁/U₂ = N₁/N₂."
  },
  {
    "id": "k8_ph_070",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Ein Transformator hat primär N₁ = 500 Windungen und sekundär N₂ = 1000 Windungen. An der Primärspule liegen 230 V Wechselspannung an. Wie hoch ist die Ausgangsspannung U₂?",
    "answers": ["920 Volt.", "230 Volt.", "115 Volt.", "460 Volt."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Da die Sekundärspule doppelt so viele Windungszahlen hat (1000 : 500 = 2), verdoppelt sich auch die Spannung auf 230 V · 2 = 460 V."
  },

  {
    "id": "k8_ph_071",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Warum wird elektrischer Strom über weite Strecken (Hochspannungsleitungen) mit sehr hohen Spannungen (z. B. 380 kV) transportiert?",
    "answers": ["Damit die Elektronen in den langen Leitungen deutlich schneller fließen können als sonst üblich.", "Um die Stromstärke gering zu halten und dadurch Wärmeverluste in den Leitungen zu minimieren.", "Weil Hochspannung in der Luft einen geringeren Luftwiderstand erfährt als Niederspannung.", "Weil die großen Generatoren im Kraftwerk nur sehr hohe Wechselspannungen erzeugen können."],
    "correct": 1,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Da die Verlustleistung im Leitungswiderstand quadratisch von der Stromstärke abhängt (PVerlust = I² · R), wird bei hoher Spannung die Stromstärke I für dieselbe Leistung klein gehalten."
  },
  {
    "id": "k8_ph_072",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was versteht man unter dem Wirkungsgrad η einer Maschine oder einer Lampe?",
    "answers": ["Das Verhältnis von nutzbarer abgegebener Energie zur zugeführten Gesamtenergie.", "Die Summe aus der zugeführten Energie und der dabei entstehenden Reibungswärme.", "Die Zeitspanne, die ein Gerät ohne jede Unterbrechung betrieben werden kann.", "Die höchste Geschwindigkeit, mit der eine Maschine arbeiten kann, ohne zu überhitzen."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Der Wirkungsgrad η = Enutz/Ezu gibt an, welcher Anteil der eingesetzten Energie tatsächlich für den gewünschten Zweck genutzt wird."
  },
  {
    "id": "k8_ph_073",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Eine Glühlampe nimmt 60 Watt elektrische Leistung auf, strahlt aber nur 3 Watt als sichtbares Licht ab. Wie hoch ist ihr Wirkungsgrad?",
    "answers": ["50 %", "5 %", "95 %", "20 %"],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "η = Pnutz/Pzu = (3 W)/(60 W) = 0,05 = 5%. Der Rest geht als unerwünschte Wärme verloren."
  },
  {
    "id": "k8_ph_074",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt der Energieerhaltungssatz der Physik?",
    "answers": [
      "Elektrische Energie lässt sich angeblich vollkommen verlustfrei in mechanische Bewegungsenergie umwandeln, ganz ohne Reibung.",
      "Energie kann bei ausreichend starken Magnetfeldern angeblich spontan völlig neu entstehen.",
      "Die Gesamtenergie eines abgeschlossenen Systems nimmt mit der Zeit stetig weiter ab.",
      "In einem abgeschlossenen System kann Energie weder erzeugt noch vernichtet, sondern nur umgewandelt werden."
    ],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Der Energieerhaltungssatz gehört zu den fundamentalen Grundgesetzen: Die Gesamtenergie in einem geschlossenen System bleibt stets konstant."
  },
  {
    "id": "k8_ph_075",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Welche Energieform besitzt ein Buch, das auf einem 2 Meter hohen Regal liegt?",
    "answers": ["Kinetische Energie (Bewegungsenergie).", "Thermische Strahlungsenergie.", "Elektrische Energie.", "Potenzielle Energie (Lageenergie)."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Körper, die sich in einer bestimmten Höhe im Schwerefeld der Erde befinden, besitzen Lageenergie (potenzielle Energie Epot = m · g · h)."
  },
  {
    "id": "k8_ph_076",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie berechnet man die kinetische Energie (Bewegungsenergie) Ekin eines Körpers der Masse m mit der Geschwindigkeit v?",
    "answers": ["Ekin = m · g · h", "Ekin = (m · v)/2", "Ekin = 1/2 · m · v²", "Ekin = m · v · 2 (ohne das Quadrat)"],
    "correct": 2,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Die kinetische Energie hängt quadratisch von der Geschwindigkeit ab: Ekin = 1/2 m v²."
  },
  {
    "id": "k8_ph_077",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was passiert mit der kinetischen Energie eines Autos, wenn sich seine Geschwindigkeit verdoppelt (z. B. von 30 km/h auf 60 km/h)?",
    "answers": ["Die kinetische Energie vervierfacht sich.", "Die kinetische Energie verdoppelt sich ebenfalls.", "Die kinetische Energie bleibt exakt unverändert.", "Die kinetische Energie steigt um das Achtfache an."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Da v quadratisch in Ekin = 1/2 m v² eingeht, führt eine Verdopplung der Geschwindigkeit ((2v)² = 4v²) zur vervierfachten Energie (und damit vervierfachtem Bremsweg!)."
  },
  {
    "id": "k8_ph_078",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie ist die physikalische Arbeit W definiert, wenn eine Kraft F entlang eines Weges s in Kraftrichtung wirkt?",
    "answers": ["W = F · s", "W = F/s", "W = F + s", "W = m · a · s²"],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Arbeit ist Kraft mal Weg (W = F · s). Die Einheit der Arbeit ist Newtonmeter (Nm) bzw. Joule (J)."
  },
  {
    "id": "k8_ph_079",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Ein Beutel mit der Gewichtskraft F = 50 N wird vertikal um 2 m angehoben. Welche Hubarbeit wird dabei verrichtet?",
    "answers": ["100 Joule", "25 Joule", "200 Joule", "52 Joule"],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Hubarbeit W = F · s = 50 N · 2 m = 100 J."
  },
  {
    "id": "k8_ph_080",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie ist die physikalische Leistung P allgemein definiert?",
    "answers": ["Leistung ist verrichtete Arbeit pro Zeitspanne (P = W/t).", "Leistung ist die Dauer, die ein Körper für eine bestimmte Strecke benötigt.", "Leistung ist das Produkt aus Masse und Weg (P = m · s) eines Körpers.", "Leistung ist Kraft mal Beschleunigung (P = F · a) bei jeder Bewegung."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Leistung P gibt an, wie schnell eine Arbeit W verrichtet wird: P = W/t. Einheit: Watt (W = J/s)."
  },
  {
    "id": "k8_ph_081",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt die 'Goldene Regel der Mechanik'?",
    "answers": ["Kräfte addieren sich immer vektoriell nach der Parallelogrammregel.", "Was man an Kraft spart, muss man an Weg zulegen.", "Die Reibungskraft ist stets größer als die Hubkraft.", "Die Leistung einer Maschine steigt mit der Länge des Hebels."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Die Goldene Regel der Mechanik (z. B. bei Hebeln, Flaschenzügen, geneigten Ebenen) besagt: W = F · s = konstant. Erspart ein Gerät Kraft, verlängert sich der Weg."
  },
  {
    "id": "k8_ph_082",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie verändert sich die benötigte Zugkraft beim Heben einer Last mit einer festen Rolle?",
    "answers": ["Die Zugkraft verringert sich bei einer festen Rolle deutlich auf ein Drittel des Wertes.", "Die Zugkraft steigt bei einer festen Rolle stark auf das Doppelte des Ausgangswerts an.", "Die Betrag der Zugkraft bleibt gleich, nur die Richtung der Kraft wird umgelenkt.", "Die benötigte Zugkraft sinkt dabei, während sich der zurückgelegte Kraftweg verdoppelt."],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Eine feste Rolle spart keine Kraft (FZug = FLast), sondern dient lediglich als Umlenkrolle für die Kraftrichtung."
  },
  {
    "id": "k8_ph_083",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Um welchen Faktor verringert sich die erforderliche Zugkraft bei Verwendung einer losen Rolle (vernachlässigbare Eigengewichte)?",
    "answers": ["Die Zugkraft steigt bei Verwendung einer losen Rolle auf das Doppelte des Wertes an.", "Die Zugkraft halbiert sich auf FZug = FLast/2.", "Die Zugkraft bleibt bei einer losen Rolle völlig unverändert wie ohne jede Rolle.", "Die Zugkraft sinkt bei der losen Rolle auf ein Viertel des ursprünglichen Wertes ab."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Eine lose Rolle verteilt die Last auf zwei Tragseile. Die Zugkraft halbiert sich, dafür verdoppelt sich der Seilweg."
  },
  {
    "id": "k8_ph_084",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie berechnet man das Drehmoment M an einem Hebel?",
    "answers": ["M = r/F (Kraftarm durch Kraft)", "M = F - r (Kraft minus Kraftarm)", "M = F : r (Kraft durch Kraftarm)", "M = F · r (Kraft mal Kraftarm)"],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Das Drehmoment M ist das Produkt aus Kraft F und dem senkrechten Abstand r (Hebelarm) zum Drehpunkt. Einheit: Newtonmeter (Nm)."
  },
  {
    "id": "k8_ph_085",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet das Hebelgesetz im Gleichgewichtsfall für einen zweiseitigen Hebel?",
    "answers": ["F₁ - r₁ = F₂ - r₂ (Differenz von Kraft und Kraftarm ist gleich)", "F₁/F₂ = r₁ · r₂ (Kraftverhältnis gleich Produkt der Kraftarme)", "F₁ · r₁ = F₂ · r₂ (Kraft mal Kraftarm ist gleich Last mal Lastarm)", "F₁ · r₂ = F₂ · r₁ · 2 (mit doppeltem zweiten Kraftarm)"],
    "correct": 2,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ein Hebel befindet sich im Gleichgewicht, wenn die Drehmomente links und rechts gleich groß sind: F₁ · r₁ = F₂ · r₂."
  },
  {
    "id": "k8_ph_086",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "An einem Wipp-Hebel sitzt ein Kind mit F₁ = 300 N in einem Abstand von r₁ = 2 m zum Drehpunkt. In welchem Abstand r₂ muss ein Kind mit F₂ = 400 N sitzen, damit Gleichgewicht herrscht?",
    "answers": ["2,67 Meter.", "3,0 Meter.", "1,0 Meter.", "1,5 Meter."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Nach F₁ · r₁ = F₂ · r₂ gilt: 300 N · 2 m = 400 N · r₂ ⇒ 600 = 400 · r₂ ⇒ r₂ = 1,5 m."
  },
  {
    "id": "k8_ph_087",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was beschreibt der physikalische Begriff 'Druck' p?",
    "answers": ["Die Geschwindigkeit eines frei fallenden Körpers zu einem Zeitpunkt (v = g · t).", "Das Verhältnis von senkrecht wirkender Kraft F zur Fläche A (p = F/A).", "Die Anzahl aller einzelnen Gasteilchen in einem vollständig geschlossenen Behälter.", "Das Produkt aus der Masse und dem Volumen eines beliebigen festen Stoffs."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Druck ist Kraft pro Fläche (p = F/A). Die SI-Einheit ist Pascal (Pa = N/m²) oder Bar (bar)."
  },
  {
    "id": "k8_ph_088",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Warum sinkt eine Person mit Schneeschuhen im tiefen Schnee viel weniger tief ein als mit normalen Stiefeln?",
    "answers": ["Der Schnee unter den Schneeschuhen schmilzt sofort und wird dadurch schlagartig hart und fest wie festes Eis.", "Die Schneeschuhe vergrößern die Auflagefläche A, wodurch sich der Druck p auf den Schnee verringert.", "Die Schneeschuhe erzeugen ein aufwärts gerichtetes Magnetfeld, das die Person leicht trägt.", "Schneeschuhe verringern durch ihr geringes Gewicht direkt die Masse der tragenden Person."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Bei gleicher Kraft F führt eine größere Fläche A nach p = F/A zu einem wesentlich kleineren Druck."
  },
  {
    "id": "k8_ph_089",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die Umrechnung zwischen der Druckeinheit Bar (bar) und Pascal (Pa)?",
    "answers": ["1 bar = 1.000 Pa (10³ Pa).", "1 bar = 100.000 Pa (10⁵ Pa).", "1 bar = 10.000 Pa (10⁴ Pa).", "1 bar = 100 Pa (10² Pa), viel zu wenig."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ein Bar entspricht genau 100.000 Pascal bzw. 100 kPa."
  },
  {
    "id": "k8_ph_090",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt das Gesetz von Pascal für Flüssigkeiten in geschlossenen Gefäßen?",
    "answers": [
      "Der Druck in einer Flüssigkeit nimmt mit zunehmender Tiefe stetig immer weiter deutlich ab.",
      "Flüssigkeiten lassen sich unter hohem Druck beliebig stark zusammendrücken.",
      "Der Druck wirkt in Flüssigkeiten stets nur in Richtung der Erdanziehungskraft.",
      "Der auf eine Flüssigkeit ausgeübte Druck breitet sich nach allen Seiten gleichmäßig aus."
    ],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Da Flüssigkeiten praktisch inkompressibel sind, verteilt sich ein äußerer Druck allseitig gleichmäßig im gesamten Volumen (Grundprinzip der Hydraulik)."
  },
  {
    "id": "k8_ph_091",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Auf welchem Prinzip basiert die Wirkung einer hydraulischen Presse?",
    "answers": ["Auf dem Pascalschen Prinzip: Gleicher Druck auf unterschiedlich große Kolbenflächen erzeugt Kraftübersetzung.", "Auf der Reibung zwischen dem strömenden Öl und den Innenwänden der engen Rohre selbst.", "Auf der thermischen Ausdehnung von speziellem Hydrauliköl beim sehr starken Erwärmen der ganzen hydraulischen Presse.", "Auf der magnetischen Abstoßung zweier sich gegenüberliegender massiver Eisenkerne im Gehäuse."],
    "correct": 0,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Da p = F₁/A₁ = F₂/A₂ gilt, erzeugt eine kleine Kraft auf einem kleinen Kolben an einem großen Kolben eine um das Flächenverhältnis vergrößerte Kraft F₂ = F₁ · A₂/A₁."
  },
  {
    "id": "k8_ph_092",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was beschreibt der 'Schweredruck' (hydrostatische Druck) in einer Flüssigkeit?",
    "answers": ["Der Druck, der durch das Eigengewicht der darüber stehenden Flüssigkeitssäule entsteht.", "Die Reibungskraft, die beim Vorbeiströmen des Wassers an Schiffsrümpfen stets entsteht.", "Der Druck der Erdatmosphäre, der von oben ständig auf die Meeresoberfläche wirkt.", "Der Druck, der beim Kochen von Wasser durch die starke Dampfentwicklung entsteht."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Der Schweredruck wächst linear mit der Tiefe h und der Dichte ρ der Flüssigkeit: phydr = ρ · g · h."
  },
  {
    "id": "k8_ph_093",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie hoch ist der durchschnittliche Luftdruck der Erdatmosphäre auf Meereshöhe?",
    "answers": ["Ca. 100.000 bar auf Meereshöhe.", "Ca. 10 hPa auf Meereshöhe.", "Ca. 50 bar auf Meereshöhe.", "Ca. 1013 hPa."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Der mittlere Luftdruck auf Meereshöhe beträgt 1013,25 hPa ≈ 1 bar."
  },
  {
    "id": "k8_ph_094",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was besagt das Archimedische Prinzip für einen in eine Flüssigkeit eingetauchten Körper?",
    "answers": ["Die Auftriebskraft ist stets exakt gleich groß wie die Masse des eingetauchten Körpers.", "Die Auftriebskraft entspricht der Gewichtskraft der vom Körper verdrängten Flüssigkeitsmenge.", "Ein Körper erfährt unter Wasser nur dann Auftrieb, wenn er ganz und gar aus Holz besteht.", "Die Auftriebskraft nimmt mit zunehmender Eintauchtiefe stets unendlich stark weiter zu und zu."],
    "correct": 1,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Das Archimedische Prinzip: Die Auftriebskraft ist so groß wie die Gewichtskraft der verdrängten Flüssigkeit (F = ρ · V · g)."
  },
  {
    "id": "k8_ph_095",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wann schwimmt ein Körper auf einer Flüssigkeit?",
    "answers": ["Wenn seine mittlere Dichte kleiner ist als die Dichte der Flüssigkeit.", "Wenn seine Dichte genau doppelt so groß ist wie die Dichte der Flüssigkeit.", "Wenn seine Form vollkommen rund und glatt ohne jede Ecke geformt ist.", "Wenn seine Masse insgesamt mehr als hundert Kilogramm beträgt."],
    "correct": 0,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Ein Körper schwimmt, wenn seine mittlere Dichte geringer ist als die der Flüssigkeit (ρKörper < ρFlüssigkeit), sodass er nur teilweise eintaucht."
  },
  {
    "id": "k8_ph_096",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wann schwebt ein Körper vollständig untergetaucht in einer Flüssigkeit?",
    "answers": ["Wenn die umgebende Flüssigkeit vollständig frei von jeglicher Reibung ist.", "Wenn die Dichte des Körpers exakt gleich der Dichte der Flüssigkeit ist.", "Wenn die Temperatur der Flüssigkeit am Gefäßboden deutlich am höchsten ist.", "Wenn die Auftriebskraft insgesamt kleiner ist als die wirkende Gewichtskraft."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Gilt ρKörper = ρFlüssigkeit, halten sich Gewichtskraft und Auftriebskraft die Waage: Der Körper schwebt im Wasser."
  },
  {
    "id": "k8_ph_097",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Warum kann ein riesiges Schiff aus Stahl auf dem Wasser schwimmen, obwohl Stahl eine viel höhere Dichte als Wasser hat?",
    "answers": [
      "Weil der starke Schiffsantrieb das Wasser unter dem gesamten Rumpf ständig fest zusammendrückt und dauerhaft nach unten presst.",
      "Durch den hohlen Schiffskörper verdrängt das Schiff viel Wasser; seine mittlere Gesamtdichte ist kleiner als Wasser.",
      "Weil das Salzwasser im Meer angeblich eine unendlich hohe Dichte besitzt, egal wie tief man misst.",
      "Weil die spezielle Schiffsfarbe das umgebende Wasser optisch stark abstößt und fernhält."
    ],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Aufgrund der großen Lufträume im Rumpf berechnet sich die mittlere Dichte aus Gesamtmasse geteilt durch das riesige Gesamtsystemvolumen, wodurch sie unter der Dichte von Wasser liegt."
  },
  {
    "id": "k8_ph_098",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Was versteht man unter der 'Dichte' ρ eines Stoffes?",
    "answers": ["Das Gewicht eines Körpers geteilt durch seine gesamte Länge in Metern.", "Das Verhältnis von Masse m zum Volumen V (ρ = m/V).", "Das Produkt aus der Gewichtskraft und der Härte eines beliebigen Stoffes.", "Die höchste Temperatur, bei der ein fester Stoff überhaupt schmelzen kann."],
    "correct": 1,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "Dichte ist Masse pro Volumen (ρ = m/V). Einheiten sind g/(cm³) oder kg/(m³)."
  },
  {
    "id": "k8_ph_099",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Ein Würfel mit dem Volumen V = 100 cm³ hat eine Masse von m = 780 g. Wie groß ist seine Dichte?",
    "answers": ["0,78 g/(cm³) (verschoben).", "78 g/(cm³) (hundertfach zu groß).", "1,2 g/(cm³) (Dichte von Wasser).", "7,8 g/(cm³) (Eisen)."],
    "correct": 3,
    "difficulty": "leicht",
    "points": 10,
    "explanation": "ρ = m/V = (780 g)/(100 cm³) = 7,8 g/(cm³)."
  },
  {
    "id": "k8_ph_100",
    "category": "k8_physik",
    "area": "schule",
    "grade": 8,
    "subject": "physik",
    "question": "Wie lautet die SI-Einheit für die elektrische Ladung Q?",
    "answers": ["Ohm (Ω), der Widerstand.", "Ampere (A), der Strom.", "Volt (V), Einheit der Spannung.", "Coulomb (C = A · s)."],
    "correct": 3,
    "difficulty": "mittel",
    "points": 15,
    "explanation": "Die elektrische Ladung Q wird in Coulomb (C) angegeben. 1 Coulomb entspricht der Ladung von etwa 6,24 · 10¹⁸ Elektronen."
  }




];