// Beruf · beruf_verkaeufer
const BERUF_VERKAEUFER_QUESTIONS = [
  { id: "q0772", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was muss bei der Anlieferung von Ware als Erstes geprüft werden?", answers: ["Der Wiederverkaufswert im Vergleich zum Katalogpreis", "Der Zustand der Verkaufsverpackung für das Schaufenster", "Anzahl der Packstücke, Äußere Beschädigungen und Übereinstimmung mit dem Frachtbrief", "Das Ablaufdatum aller im Lager befindlichen Altbestände"], correct: 2, difficulty: "schwer", points: 15, explanation: "Mängel müssen sofort dokumentiert und gemeldet werden." },
  { id: "q0773", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Wie lange ist die gesetzliche Gewährleistungsfrist für Neuwaren gegenüber Verbrauchern?", answers: ["6 Monate", "12 Monate", "5 Jahre", "24 Monate (2 Jahre)"], correct: 3, difficulty: "schwer", points: 15, explanation: "Die Gewährleistung ist gesetzlich, die Garantie dagegen eine freiwillige Zusage des Herstellers." },
  { id: "q0774", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Besteht im stationären Einzelhandel ein gesetzliches Recht auf Umtausch bei Nichtgefallen?", answers: ["Nein, der Umtausch einwandfreier Ware ist reine Kulanz des Händlers", "Ja, der Händler muss die Ware innerhalb von 14 Tagen zurücknehmen", "Ja, aber der Kunde erhält gesetzlich vorgeschrieben stets Bargeld zurück", "Ja, sofern der Kaufpreis den Betrag von 50 Euro überschreitet"], correct: 0, difficulty: "schwer", points: 15, explanation: "Im Ladengeschäft besteht kein gesetzliches Umtauschrecht bei Nichtgefallen – anders als im Onlinehandel." },
  { id: "q0775", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Welches Hauptziel verfolgt die professionelle Warenpräsentation im Ladengeschäft?", answers: ["Den Lagerbestand auf der Verkaufsfläche möglichst hoch zu stapeln", "Die Ware kaufanregend zu platzieren und die Orientierung zu erleichtern", "Verpackungsmüll vor den Augen des Kunden zu verbergen", "Die Diebstahlsicherung optisch vor den Käufern zu tarnen"], correct: 1, difficulty: "schwer", points: 15, explanation: "Sichtzone und Griffzone in Augen- und Handhöhe verkaufen am besten." },
  { id: "q0776", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was versteht man unter einer 'offenen Frage' im Verkaufsgespräch?", answers: ["Eine Frage, die der Verkäufer direkt selbst beantwortet", "Eine Suggestivfrage, die den Kunden zum Kauf drängt", "Eine W-Frage, die dem Kunden ausführliche Antworten ermöglicht", "Eine Kontrollfrage, die nur mit Ja oder Nein beantwortet werden kann"], correct: 2, difficulty: "schwer", points: 15, explanation: "W-Fragen wie 'Wofür möchten Sie es nutzen?' bringen den Kunden ins Erzählen." },
  { id: "q0777", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was schreibt die Preisangabenverordnung (PAngV) für den Einzelhandel vor?", answers: ["Preise dürfen nur auf Nachfrage an der Kasse genannt werden", "Nettopreise reichen bei Verkäufen an Endverbraucher aus", "Rabatte dürfen maximal 10 Prozent des Verkaufspreises betragen", "Endpreise müssen inklusive Umsatzsteuer und allen Bestandteilen angegeben sein"], correct: 3, difficulty: "schwer", points: 15, explanation: "Verbraucher müssen den Endpreis auf einen Blick erkennen können." },
  { id: "q0778", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Wie verhält man sich bei einer Kundenreklamation fachgerecht und kundenorientiert?", answers: ["Aktiv zuhören, Empathie zeigen, den Sachverhalt prüfen und eine Lösung anbieten", "Den Kunden sofort an den Hersteller verweisen und das Gespräch beenden", "Den Vorwurf vorsorglich bestreiten, um Regressansprüche abzuwehren", "Dem Kunden ohne Prüfung sofort den Kaufpreis in bar auszahlen"], correct: 0, difficulty: "schwer", points: 15, explanation: "Eine gut gelöste Reklamation stärkt oft die Kundenbindung." },
  { id: "q0779", category: "beruf_verkaeufer", area: "beruf", subject: "verkaeufer", question: "Was versteht man im Einzelhandel unter dem Begriff 'Warenschwund'?", answers: ["Den gezielten Abverkauf von Saisonware durch Preisnachlässe", "Ungeplante Differenzen zwischen Soll- und Ist-Bestand durch Diebstahl oder Schwund", "Den normalen Schwund von Verpackungsmaterial im Lagerbereich", "Die geplante Entsorgung abgelaufener Lebensmittel"], correct: 1, difficulty: "schwer", points: 15, explanation: "Der Schwund wird über die Inventur ermittelt und mindert den Gewinn." }
];
if (typeof window !== "undefined") window.BERUF_VERKAEUFER_QUESTIONS = BERUF_VERKAEUFER_QUESTIONS;