// Beruf · beruf_elektro
const BERUF_ELEKTRO_QUESTIONS = [
  { id: "q0732", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Wie lauten die 5 Sicherheitsregeln der Elektrotechnik in korrekter Reihenfolge?", answers: ["Messen, erden, freischalten, abdecken, sichern", "Erden, sichern, freischalten, prüfen, abdecken", "Freischalten, gegen Wiedereinschalten sichern, Spannungsfreiheit feststellen, Erden und Kurzschließen, Benachbarte unter Spannung stehende Teile abdecken", "Sichern, freischalten, abdecken, erden, messen"], correct: 2, difficulty: "schwer", points: 15, explanation: "Die Reihenfolge ist verbindlich und schützt vor Stromunfällen." },
  { id: "q0733", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Welche Farbkombination ist normgerecht für den Schutzleiter (PE) vorgeschrieben?", answers: ["Blau-weiß", "Braun-schwarz", "Rein Schwarz", "Grün-gelb"], correct: 3, difficulty: "schwer", points: 15, explanation: "Grün-gelb ist ausschließlich dem Schutzleiter vorbehalten, blau ist der Neutralleiter." },
  { id: "q0734", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Welche Hauptfunktion hat ein Fehlerstrom-Schutzschalter (RCD)?", answers: ["Er schützt Personen durch Abschaltung bei Fehlerströmen", "Er schützt Leitungen vor thermischer Überlastung bei Kurzschluss", "Er regelt die Netzspannung auf konstante 230 Volt ein", "Er misst den elektrischen Stromverbrauch für die Zählerabrechnung"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der RCD vergleicht Hin- und Rückstrom und löst bei einer Differenz (Fehlerstrom) aus." },
  { id: "q0735", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Wie verhält sich der Gesamtwiderstand bei einer Parallelschaltung von Widerständen?", answers: ["Er entspricht exakt dem größten Einzelwiderstand im Kreis", "Er ist kleiner als der kleinste beteiligte Einzelwiderstand", "Er steigt proportional zur Anzahl der angeschlossenen Verbraucher", "Er entspricht der einfachen Summe aller Einzelwiderstände"], correct: 1, difficulty: "schwer", points: 15, explanation: "Bei Parallelschaltung addieren sich die Leitwerte, der Gesamtwiderstand sinkt." },
  { id: "q0736", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was sagt der Nennstrom einer elektrischen Sicherung aus?", answers: ["Die maximale Auslösespannung bei einem Erdschluss", "Die Mindeststromstärke, die zur sofortigen Zerstörung führt", "Den Strom, den die Sicherung dauerhaft ohne Auslösung führen kann", "Den Widerstandswert der angeschlossenen Kupferleitung"], correct: 2, difficulty: "schwer", points: 15, explanation: "Die Sicherung schützt vor allem die Leitung vor Überlastung und Brand." },
  { id: "q0737", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Warum muss bei langen Leitungswegen ein größerer Leiterquerschnitt gewählt werden?", answers: ["Um die mechanische Zugfestigkeit im Kabelkanal zu erhöhen", "Um das Auftreten von Induktionsspannungen zu unterbinden", "Damit die Stromstärke am Ende der Leitung vervielfacht wird", "Um den Leitungswiderstand, Spannungsfall und die Erwärmung zu begrenzen"], correct: 3, difficulty: "schwer", points: 15, explanation: "Ein größerer Querschnitt senkt den Leitungswiderstand und damit den Spannungsfall." },
  { id: "q0738", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was bedeutet die Schutzart IP44 für ein elektrisches Betriebsmittel?", answers: ["Schutz gegen feste Fremdkörper >1 mm und Schutz gegen Spritzwasser", "Schutz gegen Staub in schädigender Menge und Schutz gegen Strahlwasser", "Vollständiger Berührungsschutz und Schutz gegen dauerndes Untertauchen", "Kein Schutz gegen Berührung, aber Schutz gegen senkrechtes Tropfwasser"], correct: 0, difficulty: "schwer", points: 15, explanation: "Die erste Ziffer steht für Fremdkörper-, die zweite für Wasserschutz." },
  { id: "q0739", category: "beruf_elektro", area: "beruf", subject: "elektro", question: "Was unterscheidet Gleichstrom (DC) im Wesentlichen von Wechselstrom (AC)?", answers: ["Gleichstrom verringert seine Spannung periodisch im Sinustakt", "Gleichstrom behält seine Richtung und Polung über die Zeit bei", "Wechselstrom kann nicht über Transformationen übertragen werden", "Gleichstrom fließt ausschließlich in hochfrequenten Impulsen"], correct: 1, difficulty: "schwer", points: 15, explanation: "Im deutschen Netz beträgt die Frequenz des Wechselstroms 50 Hz." }
];
if (typeof window !== "undefined") window.BERUF_ELEKTRO_QUESTIONS = BERUF_ELEKTRO_QUESTIONS;