// Beruf · beruf_buero
const BERUF_BUERO_QUESTIONS = [
  { id: "q0764", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was versteht man unter 'Skonto' auf einer Lieferantenrechnung?", answers: ["Einen Verzugszuschlag bei verspäteter Bezahlung", "Einen festen Abzug für mangelhafte Ware", "Einen Prozentualen Preisnachlass bei Zahlung innerhalb einer Frist", "Die gesetzlich geschuldete Umsatzeinfuhrsteuer"], correct: 2, difficulty: "schwer", points: 15, explanation: "Beispiel: '2 % Skonto bei Zahlung innerhalb von 10 Tagen'." },
  { id: "q0765", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wie hoch ist der reguläre Umsatzsteuersatz in Deutschland?", answers: ["7 Prozent", "16 Prozent", "21 Prozent", "19 Prozent"], correct: 3, difficulty: "schwer", points: 15, explanation: "Der ermäßigte Satz von 7 Prozent gilt etwa für Lebensmittel und Bücher." },
  { id: "q0766", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wodurch kommt ein rechtsgültiger Kaufvertrag im Normalfall zustande?", answers: ["Durch zwei übereinstimmende Willenserklärungen (Angebot und Annahme)", "Erst durch die vollständige Bezahlung der Ware per Überweisung", "Ausschließlich durch die Unterschrift eines Notars auf dem Vertrag", "Erst durch die physische Aushändigung der Ware an den Käufer"], correct: 0, difficulty: "schwer", points: 15, explanation: "Antrag und Annahme genügen; ein schriftlicher Vertrag ist meist nicht nötig." },
  { id: "q0767", category: "beruf_buero", area: "beruf", subject: "buero", question: "Welche Regelungen enthält die Norm DIN 5008 im Büroalltag?", answers: ["Sicherheitsvorschriften für elektrische Bürogerätesysteme", "Schreib- und Gestaltungsregeln für die Text- und Informationsverarbeitung", "Richtlinien für die ergonomische Einstellung von Bürostühlen", "Gesetzliche Aufbewahrungsfristen für Steuerunterlagen"], correct: 1, difficulty: "schwer", points: 15, explanation: "Sie legt Abstände, Anschriftfeld und Aufbau von Geschäftsbriefen fest." },
  { id: "q0768", category: "beruf_buero", area: "beruf", subject: "buero", question: "Was bezeichnet der Begriff 'Inventur' im Rechnungswesen?", answers: ["Die Ermittlung des Gewinns am Ende des Geschäftsjahres", "Eine Kundenbefragung zur Sortimentsgestaltung im Laden", "Mengen- und wertmäßige Bestandsaufnahme aller Vermögenswerte und Schulden", "Die jährliche Überprüfung der Leistungsbeurteilung von Angestellten"], correct: 2, difficulty: "schwer", points: 15, explanation: "Die Inventur ist gesetzlich vorgeschrieben und Grundlage des Inventars." },
  { id: "q0769", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wann gerät ein Schuldner bei einer Entgeltforderung typischerweise in Zahlungsverzug?", answers: ["Sofort mit dem Erhalt des Lieferscheins im Warenausgang", "Wenn er die Ware nicht innerhalb von drei Tagen umtauscht", "Sobald der Rechnungsbetrag die Bagatellgrenze überschreitet", "Wenn er nach Fälligkeit und Mahnung oder Ablauf einer Frist nicht zahlt"], correct: 3, difficulty: "schwer", points: 15, explanation: "Nach Verzugseintritt können Verzugszinsen und Mahnkosten verlangt werden." },
  { id: "q0770", category: "beruf_buero", area: "beruf", subject: "buero", question: "Welches Ziel verfolgt eine strukturierte Ablageorganisation im Büro?", answers: ["Systematisches Ordnungsverfahren zur schnellen Wiederauffindbarkeit von Dokumenten", "Reduzierung des Papierverbrauchs durch sofortiges Vernichten aller Belege", "Ausschließliche Archivierung von vertraulichen Personalakten im Tresor", "Steuerung des Wareneinkaufs und der Lieferantenkontakte"], correct: 0, difficulty: "schwer", points: 15, explanation: "Wichtig sind einheitliche Ordnungssysteme und die Beachtung von Aufbewahrungsfristen." },
  { id: "q0771", category: "beruf_buero", area: "beruf", subject: "buero", question: "Wie lange müssen Buchungsbelege und Rechnungen handels- und steuerrechtlich aufbewahrt werden?", answers: ["3 Jahre", "10 Jahre", "5 Jahre", "2 Jahre"], correct: 1, difficulty: "schwer", points: 15, explanation: "Buchungsbelege und Jahresabschlüsse unterliegen der zehnjährigen Aufbewahrungsfrist." }
];
if (typeof window !== "undefined") window.BERUF_BUERO_QUESTIONS = BERUF_BUERO_QUESTIONS;