// Beruf · beruf_tischler
const BERUF_TISCHLER_QUESTIONS = [
  { id: "q0740", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Welche der aufgeführten Holzarten gehört zur Gruppe der Nadelhölzer?", answers: ["Eiche", "Buche", "Fichte", "Ahorn"], correct: 2, difficulty: "schwer", points: 15, explanation: "Fichte, Kiefer und Tanne sind Nadelhölzer; Eiche und Buche sind Laubhölzer." },
  { id: "q0741", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Welche Holzfeuchte wird für Möbel im beheizten Innenraum angestrebt?", answers: ["Etwa 18 bis 22 Prozent", "Etwa 30 bis 35 Prozent", "Etwa 2 bis 4 Prozent", "Etwa 8 bis 10 Prozent"], correct: 3, difficulty: "schwer", points: 15, explanation: "Zu feuchtes Holz schwindet später und die Verbindungen reißen auf." },
  { id: "q0742", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Was zeichnet eine klassische Zinkenverbindung im Holzbau aus?", answers: ["Eine formschlüssige Eckverbindung aus ineinandergreifenden Zinken und Zapfen", "Eine stumpfe Verleimung zweier Plattenstöße mithilfe von Furnierstreifen", "Eine rein mechanische Verbindung, die ausschließlich mit Blechlaschen verschraubt wird", "Eine Eckverbindung, die ausschließlich durch runde Holzdübel zusammengehalten wird"], correct: 0, difficulty: "schwer", points: 15, explanation: "Schwalbenschwanzzinken sind besonders zugfest und ein Qualitätsmerkmal im Möbelbau." },
  { id: "q0743", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Warum 'arbeitet' Holz (Quellen und Schwinden) auch nach der Verarbeitung?", answers: ["Weil das Holz Zellmasse an die Umgebungsluft abgibt", "Weil es Feuchtigkeit aufnimmt und an die Umgebung abgibt", "Weil sich das Lignin durch UV-Strahlung dauerhaft ausdehnt", "Weil die Holzfasern unter Belastung nachgeben"], correct: 1, difficulty: "schwer", points: 15, explanation: "Holz quillt und schwindet quer zur Faser deutlich stärke als in Längsrichtung." },
  { id: "q0744", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Wofür wird ein Stechbeitel in der Holzbearbeitung hauptsächlich eingesetzt?", answers: ["Zum Glätten breiter Holzoberflächen anstelle eines Hobels", "Zum sauberen Trennen von langen Brettern in Faserrichtung", "Zum Ausstemmen und Nachstechen von Aussparungen oder Zapfenlöchern", "Zum Anzeichnen von schnurgeraden Schnittlinien auf Massivholz"], correct: 2, difficulty: "schwer", points: 15, explanation: "Der Stechbeitel wird mit dem Klüpfel oder von Hand geführt." },
  { id: "q0745", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Was versteht man im Tischlerhandwerk unter Furnier?", answers: ["Eine Schicht aus verpressten Sägemehlresten", "Ein transparenter Schutzlack auf Harzbasis", "Eine hochfeste Kunststoffbeschichtung", "Dünne Holzblätter zum Belegen von Trägerplatten"], correct: 3, difficulty: "schwer", points: 15, explanation: "Furniere sind meist 0,5 bis 0,9 mm dick und sparen wertvolles Vollholz." },
  { id: "q0746", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Welche Schutzeinrichtungen sind an einer Tischkreissäge zwingend vorgeschrieben?", answers: ["Spaltkeil und Schutzhaube zur Abdeckung des Sägeblatts", "Absauganlage und Vorschubapparat für alle Schnittarten", "Gehrungsanschlag und Werkstückspanner an der Tischkante", "Splitterschutz und Parallelschiene mit Not-Aus-Pedal"], correct: 0, difficulty: "schwer", points: 15, explanation: "Der Spaltkeil verhindert das Klemmen des Werkstücks und damit gefährliche Rückschläge." },
  { id: "q0747", category: "beruf_tischler", area: "beruf", subject: "tischler", question: "Warum ist eine funktionierende Absauganlage in der Holzwerkstatt unerlässlich?", answers: ["Sie kühlt die Sägeblätter zur Standzeitverlängerung", "Sie schützt vor gesundheitsschädlichem Holzstaub und Spänen", "Sie hält die Raumluftfeuchtigkeit konstant auf 50 Prozent", "Sie verhindert das Festbrennen von Leimresten am Werkstück"], correct: 1, difficulty: "schwer", points: 15, explanation: "Holzstaub gilt als krebserzeugend, besonders Eichen- und Buchenstaub." }
];
if (typeof window !== "undefined") window.BERUF_TISCHLER_QUESTIONS = BERUF_TISCHLER_QUESTIONS;