// Beruf · beruf_fachinformatiker
const BERUF_FACHINFORMATIKER_QUESTIONS = [
  { id: "q0756", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Wofür steht die Abkürzung IP im Netzwerkbereich?", answers: ["Internal Port", "Internet Package", "Internet Protocol", "Integrated Provider"], correct: 2, difficulty: "schwer", points: 15, explanation: "Die IP-Adresse identifiziert ein Gerät eindeutig im Netzwerk." },
  { id: "q0757", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Welche Hauptaufgabe hat ein Domain Name System (DNS) Server im Netzwerk?", answers: ["Er verschlüsselt den gesamten Datenverkehr zwischen Rechnern", "Er vergibt dynamische IP-Adressen an lokale Netzwerkgeräte", "Er schützt das Heimnetz vor Viren und unbefugten Zugriffen", "Er auflöst Klarnamen (Domainnamen) in IP-Adressen auf"], correct: 3, difficulty: "schwer", points: 15, explanation: "Ohne DNS müsste man IP-Adressen statt Namen wie beispiel.de eingeben." },
  { id: "q0758", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Welche Funktion erfüllt der SQL-Befehl 'SELECT' in einer relationalen Datenbank?", answers: ["Er fragt Daten aus einer oder mehreren Tabellen ab", "Er löscht Datensätze unwiderruflich aus der Datenbank", "Er erstellt eine neue Datenbankstruktur inklusive Indizes", "Er verändert bestehende Datensätze in einer Tabelle"], correct: 0, difficulty: "schwer", points: 15, explanation: "SELECT ist der Abfragebefehl; DELETE löscht und CREATE legt an." },
  { id: "q0759", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was besagt die 3-2-1-Regel bei der Datensicherung?", answers: ["3 Benutzer, 2 Passwörter, 1 Administrator-Account", "3 Datenkopien, 2 verschiedene Medien, 1 Kopie außer Haus", "3 Sicherungen pro Tag, 2 pro Woche, 1 pro Monat", "3 Festplatten, 2 Switches, 1 unterbrechungsfreie Stromversorgung"], correct: 1, difficulty: "schwer", points: 15, explanation: "Sie schützt vor Datenverlust durch Defekt, Diebstahl oder Brand." },
  { id: "q0760", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Welche Funktionsweise kennzeichnet ein RAID-1-System?", answers: ["Verteilung der Datenblöcke auf mindestens drei Platten ohne Parität", "Erhöhung der Speicherkapazität durch einfaches Zusammenlegen", "Spiegelung der Daten auf mindestens zwei Festplatten für Ausfallsicherheit", "Datensicherung auf externen Bandspeichern im Netz"], correct: 2, difficulty: "schwer", points: 15, explanation: "RAID 1 erhöht die Ausfallsicherheit, ersetzt aber kein Backup." },
  { id: "q0761", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Welche Hauptaufgabe übernimmt eine Firewall in der IT-Sicherheit?", answers: ["Sie beschleunigt den Datendurchsatz bei Downloads", "Sie kühlt die Serverkomponenten bei hoher Auslastung", "Sie speichert Sicherungskopien wichtiger Systemdateien", "Sie überwacht und filtert den Netzwerktraffic nach Regeln"], correct: 3, difficulty: "schwer", points: 15, explanation: "Firewalls erlauben oder blockieren Verbindungen anhand von Ports, Adressen und Protokollen." },
  { id: "q0762", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Was unterscheidet Hardware von Software in einem Computersystem?", answers: ["Hardware umfasst alle physischen Komponenten, Software die Programme", "Hardware bezeichnet die Betriebssysteme, Software die Bauteile", "Software ist stets fest im Prozessor verdrahtet, Hardware ist variabel", "Es gibt keinen Unterschied, beide Begriffe beschreiben Speicherplatz"], correct: 0, difficulty: "schwer", points: 15, explanation: "Hardware ist der physische Teil, Software die Menge der Programme und Daten." },
  { id: "q0763", category: "beruf_fachinformatiker", area: "beruf", subject: "fachinformatiker", question: "Welchem Zweck dient die Datenschutz-Grundverordnung (DSGVO) primär?", answers: ["Der Vorgabe von Mindeststandards für Serverhardware", "Dem Schutz personenbezogener Daten und deren Verarbeitung", "Der Überwachung der Arbeitszeiten von IT-Mitarbeitern", "Der Regulierung der Preise für Softwarelizenzen"], correct: 1, difficulty: "schwer", points: 15, explanation: "Verstöße können empfindliche Bußgelder nach sich ziehen." }
];
if (typeof window !== "undefined") window.BERUF_FACHINFORMATIKER_QUESTIONS = BERUF_FACHINFORMATIKER_QUESTIONS;