const K1_SACHUNTERRICHT_QUESTIONS = [
  // ================================================================
  // 1. TIERE & PFLANZEN (30 Fragen)
  // ================================================================
  {
    id: "q1_s_001",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches dieser Tiere hält einen Winterschlaf?",
    answers: ["Spatz", "Katze", "Igel", "Hund"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Igel rollt sich im Winter zusammen und hält Winterschlaf."
  },
  {
    id: "q1_s_002",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was brauchen Pflanzen hauptsächlich zum Wachsen?",
    answers: ["Saft und Milch", "Wasser und Licht", "Schatten und Kälte", "Schokolade"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Pflanzen brauchen Erde, Wasser und Sonnenlicht."
  },
{
  id: "q1_s_003",
  category: "k1_sachunterricht",
  topic: "tiere_pflanzen",
  area: "schule",
  grade: 1,
  subject: "sachunterricht",
  question: "Wie heißt das Baby einer Kuh?",
  answers: ["Kalb", "Fohlen", "Ferkel", "Küken"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "Das Junge einer Kuh nennt man Kalb."
},
  {
    id: "q1_s_004",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier legt Eier?",
    answers: ["Kuh", "Huhn", "Hund", "Schaf"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Hühner legen Eier, aus denen Küken schlüpfen können."
  },
{
  id: "q1_s_005",
  category: "k1_sachunterricht",
  topic: "tiere_pflanzen",
  area: "schule",
  grade: 1,
  subject: "sachunterricht",
  question: "Woraus entsteht später ein Schmetterling?",
  answers: ["Made", "Fliege", "Käfer", "Raupe"],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "Aus dem Ei schlüpft eine Raupe, die sich verpuppt und zum Schmetterling wird."
},
  {
    id: "q1_s_006",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier ist mit Stacheln geschützt?",
    answers: ["Fuchs", "Reh", "Igel", "Hase"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Igel hat spitze Stacheln auf dem Rücken."
  },
  {
    id: "q1_s_007",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was machen Zugvögel im Herbst?",
    answers: ["Sie bauen ein Schneehaus", "Sie fliegen in warme Länder", "Sie halten Winterschlaf im Nest", "Sie verlieren ihre Flügel"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Zugvögel fliegen im Herbst in den Süden, weil es dort wärmer ist."
  },
  {
    id: "q1_s_008",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welcher Baum behält im Winter seine grünen Nadeln?",
    answers: ["Buche", "Ahorn", "Tanne", "Eiche"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Tannen sind Nadelbäume und bleiben auch im Winter grün."
  },
  {
    id: "q1_s_009",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was fressen Eichhörnchen besonders gern?",
    answers: ["Gras in der Praxis", "Käse in der Praxis", "Fische im Alltag", "Nüsse und Eicheln"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Eichhörnchen sammeln Nüsse und Eicheln als Vorrat."
  },
  {
    id: "q1_s_010",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches dieser Tiere ist ein klassisches Haustier?",
    answers: ["Fuchs", "Katze", "Wildschwein", "Reh"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Katzen leben oft als Haustiere bei Menschen zu Hause."
  },
  {
    id: "q1_s_011",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was fällt im Herbst von den Laubbäumen?",
    answers: ["Grüne Tannenzweige", "Weiße Schneeflocken", "Rote Erdbeeren", "Bunte Blätter"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Herbst färben sich die Blätter bunt und fallen ab."
  },
  {
    id: "q1_s_012",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welcher Vogel klopft laut an Baumstämme?",
    answers: ["Kuckuck", "Elster", "Amsel", "Specht"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Specht meißelt mit seinem Schnabel Löcher in Bäume."
  },
  {
    id: "q1_s_013",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wo wohnen Bienen zusammen?",
    answers: ["Im Hundekorb", "Im Bienenstock", "Unter dem Dach", "Im Vogelhaus"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bienen leben in einem Bienenstock oder Bienenstock-Kasten."
  },
  {
    id: "q1_s_014",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was stellen Bienen aus Blütennektar her?",
    answers: ["Honig", "Marmelade", "Butter", "Milch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bienen sammeln Nektar und machen daraus süßen Honig."
  },
  {
    id: "q1_s_015",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier baut Holz-Dämme im Wasser?",
    answers: ["Enten", "Fisch", "Biber", "Frosch"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Biber nagt Bäume um und baut Dämme im Fluss."
  },
  {
    id: "q1_s_016",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie nennt man ein Hundebaby?",
    answers: ["Küken", "Welpe", "Ferkel", "Lamm"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Junge Hunde nennt man Welpen."
  },
  {
    id: "q1_s_017",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie heißt das Junge vom Schaf?",
    answers: ["Kalb", "Fohlen", "Kitten", "Lamm"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Baby vom Schaf heißt Lamm."
  },
  {
    id: "q1_s_018",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was schlüpft aus einem Hühnereilein?",
    answers: ["Fisch", "Küken", "Ferkel", "Raupe"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus dem Ei schlüpft ein kleines Küken."
  },
  {
    id: "q1_s_019",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier gräbt Tunnel unter der Erde und macht Erd-Haufen im Garten?",
    answers: ["Eichhörnchen", "Maulwurf", "Vogel", "Igel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Maulwurf gräbt unter der Erde und wirft Maulwurfshügel auf."
  },
  {
    id: "q1_s_020",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Farbe hat eine blühende Sonnenblume am Rand?",
    answers: ["Gelb", "Schwarz", "Blau", "Lila"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Blütenblätter der Sonnenblume strahlen leuchtend gelb."
  },
  {
    id: "q1_s_021",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was passiert mit den Bäumen im Frühling?",
    answers: ["Sie bekommen neue Knospen und Blätter", "Sie verlieren im Frühling alle Blätter", "Sie schlafen den ganzen Frühling", "Sie werden im Frühling ganz braun"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Frühling erwachen die Bäume und treiben neue grüne Blätter aus."
  },
{
  id: "q1_s_022",
  category: "k1_sachunterricht",
  topic: "tiere_pflanzen",
  area: "schule",
  grade: 1,
  subject: "sachunterricht",
  question: "Welches Bauernhoftier gibt uns frische Milch?",
  answers: ["Huhn", "Hund", "Gans", "Kuh"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "Kühe werden gemolken und geben uns leckere Milch."
},
  {
    id: "q1_s_023",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier schenkt uns Wolle für warme Pullover?",
    answers: ["Pferd", "Schaf", "Katze", "Schwein"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Schafe werden geschoren und aus ihrer Wolle wird Garn gemacht."
  },
  {
    id: "q1_s_024",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welcher dieser Pilze ist giftig und rot mit weißen Punkten?",
    answers: ["Steinpilz", "Champignon", "Fliegenpilz", "Pfifferling"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Fliegenpilz ist giftig und darf auf keinen Fall gegessen werden."
  },
  {
    id: "q1_s_025",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier lebt im Teich und macht 'Quak'?",
    answers: ["Frosch", "Schwalbe", "Igel", "Hase"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Frösche quaken am Weiher oder Teich."
  },
  {
    id: "q1_s_026",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wo versteckt das Eichhörnchen Vorräte für den Winter?",
    answers: ["Tief unten in einem kalten Bach im Wald", "In Verstecken in der Erde oder in Baumhöhlen", "Oben im weichen warmen Nest der Zugvögel", "In der Speisekammer bei den Menschen zuhause"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Eichhörnchen vergraben Nüsse in der Erde und finden sie oft nach dem Geruch wieder."
  },
  {
    id: "q1_s_027",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Aus was schlüpft ein kleiner Keimling in der Erde?",
    answers: ["Aus einem Stein", "Aus einem Blatt", "Aus einem Samen", "Aus Holz"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus Pflanzensamen sprießen neue Pflanzen heraus."
  },
  {
    id: "q1_s_028",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches kleine Insekt ist rot mit schwarzen Punkten?",
    answers: ["Marienkäfer", "Schmetterling", "Ameise", "Libelle"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Marienkäfer hat rote Flügeldecken mit schwarzen Punkten."
  },
  {
    id: "q1_s_029",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wo atmen Fische Sauerstoff und schwimmen?",
    answers: ["In der Wüste", "Auf den Bäumen", "In der Luft", "Im Wasser"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Fische leben und atmen im Wasser mit ihren Kiemen."
  },
  {
    id: "q1_s_030",
    category: "k1_sachunterricht",
    topic: "tiere_pflanzen",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Tier trägt sein eigenes Haus auf dem Rücken?",
    answers: ["Schildkröte", "Schnecke", "Raupe", "Assel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Gehäuseschnecke hat ihr Schneckenhaus immer dabei."
  },

  // ================================================================
  // 2. JAHRESZEITEN & WETTER (25 Fragen)
  // ================================================================
  {
    id: "q1_s_031",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie viele Jahreszeiten hat ein Jahr?",
    answers: ["4 Jahreszeiten", "12 Jahreszeiten", "2 Jahreszeiten", "6 Jahreszeiten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die 4 Jahreszeiten heißen Frühling, Sommer, Herbst und Winter."
  },
  {
    id: "q1_s_032",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "In welcher Jahreszeit schneit es meistens?",
    answers: ["Winter", "Herbst", "Frühling", "Sommer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im kalten Winter fällt Niederschlag oft als Schnee."
  },
  {
    id: "q1_s_033",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "In welcher Jahreszeit ist es am wärmsten und wir gehen schwimmen?",
    answers: ["Herbst", "Sommer", "Frühling", "Winter"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Sommer ist die heißeste Jahreszeit mit langen Sonnentagen."
  },
  {
    id: "q1_s_034",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was entsteht am Himmel, wenn gleichzeitig die Sonne scheint und es regnet?",
    answers: ["Nebel", "Regenbogen", "Schneesturm", "Mondlicht"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sonnenlicht bricht sich in Wassertropfen und erzeugt einen bunten Regenbogen."
  },
  {
    id: "q1_s_035",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "In welcher Jahreszeit erwacht die Natur und erste Frühblüher wachsen?",
    answers: ["Frühherbst", "Sommer", "Frühling", "Winter"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Frühling sprießen Blumen wie Schneeglöckchen und Krokusse."
  },
  {
    id: "q1_s_036",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was zieht man am besten an, wenn es draußen stark regnet?",
    answers: ["Sonnenhut und kurze Hose", "Badehose und einen Schwimmflügel", "Schlafanzug und Hausschuhe", "Gummistiefel und Regenjacke"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Regenkleidung schützt uns vor Nässe."
  },
  {
    id: "q1_s_037",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Waraus besteht Schnee?",
    answers: ["Winzigen weißen Zuckerkörnern", "Weicher weißer Watte", "Gefrorenen Eiskristallen", "Kleinen bunten Seifenblasen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Schnee ist gefrorenes Wasser aus den Wolken."
  },
  {
    id: "q1_s_038",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was passiert mit einem Schneemann, wenn es warm wird?",
    answers: ["Er schmilzt zu Wasser", "Er wird bunt", "Er friert noch mehr ein", "Er fliegt weg"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei Temperaturen über 0 Grad schmilzt das Eis/Schnee."
  },
  {
    id: "q1_s_039",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Womit messen wir, wie warm oder kalt es draußen ist?",
    answers: ["Thermometer", "Wasserwaage", "Kompass", "Lineal"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Thermometer zeigt die Temperatur in Grad an."
  },
  {
    id: "q1_s_040",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was bringt man im windigen Herbst oft zum Fliegen?",
    answers: ["Drachen", "Schneebälle", "Luftballons unter Wasser", "Papierflieger im Schnee"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Herbstwind ist ideal, um Drachen steigen zu lassen."
  },
  {
    id: "q1_s_041",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Woraus fällt der Regen auf die Erde?",
    answers: ["Aus Wolken", "Vom Mond", "Aus den Bäumen", "Aus Flugzeugen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wenn Wassertröpfchen in den Wolken zu schwer werden, fallen sie als Regen."
  },
  {
    id: "q1_s_042",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was hört man bei einem Gewitter kurz nach dem hellen Blitz?",
    answers: ["Vogelgesang", "Donner", "Pfeifen", "Musik"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Erst sieht man den Blitz, danach krachte der Donner."
  },
  {
    id: "q1_s_043",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Jahreszeit folgt direkt auf den Sommer?",
    answers: ["Winter", "Frühling", "Herbst", "Neujahr"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach dem warmen Sommer kommt der kühler werdende Herbst."
  },
  {
    id: "q1_s_044",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Jahreszeit folgt direkt auf den Winter?",
    answers: ["Herbst", "Frühling", "Dezember", "Sommer"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach der eisigen Winterzeit beginnt der Frühling."
  },
  {
    id: "q1_s_045",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was soll man im Sommer auftragen, um die Haut vor Sonnenbrand zu schützen?",
    answers: ["Seife", "Zahnpasta", "Sonnencreme", "Wasserfarben"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sonnencreme schützt unsere Haut vor schädlicher UV-Strahlung."
  },
  {
    id: "q1_s_046",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wann wird es im Winter morgens und abends?",
    answers: ["Niemals dunkel im Alltag", "Früh dunkel und spät hell", "Immer warm in der Praxis", "Der ganze Tag ist leuchtend hell"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Im Winter sind die Tage kurz und die Nächte lang."
  },
  {
    id: "q1_s_047",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was schützt im Winter den Kopf vor Kälte?",
    answers: ["Eine Mütze", "Ein Sonnenhut", "Ein Stirnband aus Papier", "Eine Brille"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Warme Wollmützen halten Ohren und Kopf im Winter warm."
  },
  {
    id: "q1_s_048",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie fühlt sich Hagel an, der aus den Wolken fällt?",
    answers: ["Weich und warm wie kuschelige Watte", "Nass und klebrig wie dicker Schleim", "Warm und flüssig wie heißer Tee", "Kalt und hart wie kleine Eiskugeln"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Hagel besteht aus kleinen, gefrorenen Eisklumpen."
  },
  {
    id: "q1_s_049",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was ist Nebel?",
    answers: ["Ein Schnee mitten im Sommer", "Eine Wolke direkt am Boden", "Rauch von einem Lagerfeuer", "Ein Regen ohne jedes Wasser"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Nebel sind winzige Wassertröpfchen in der Luft nahe am Boden."
  },
  {
    id: "q1_s_050",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "In welcher Jahreszeit ernten Landwirte viele Früchte und Kürbisse?",
    answers: ["Winter", "Mitte Januar", "Herbst", "Frühling"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Herbst ist die Haupterntezeit für viele Obst- und Gemüsesorten."
  },
  {
    id: "q1_s_051",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Fest feiert man oft im kalten Dezember?",
    answers: ["Weihnachten", "Sankt Martin im Frühling", "Ostern", "Sommerfest"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Weihnachten fällt in die Winterzeit im Dezember."
  },
  {
    id: "q1_s_052",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "In welcher Jahreszeit suchen wir bunt bemalt Eier im Garten?",
    answers: ["Herbst im bunten Wald", "Winter im tiefen Schnee", "Frühling (Ostern)", "Tiefster Hochsommer"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ostern wird im Frühling gefeiert."
  },
  {
    id: "q1_s_053",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was passiert mit Pfützen nach dem Regen, wenn wieder heiß die Sonne scheint?",
    answers: ["Sie werden rot im Alltag", "Sie trocknen langsam aus", "Sie werden riesengroß", "Sie frieren zu Eis"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Wasser verdunstet in die Luft und die Pfütze verschwindet."
  },
  {
    id: "q1_s_054",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welcher Monat ist der allererste im neuen Kalenderjahr?",
    answers: ["Mai", "Dezember", "Juli", "Januar"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Jahr beginnt am 1. Januar."
  },
  {
    id: "q1_s_055",
    category: "k1_sachunterricht",
    topic: "jahreszeiten",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Jahreszeit schließt den Kreis nach dem Herbst ab?",
    answers: ["Frühling", "Winter", "Mai", "Sommer"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Reihenfolge ist: Frühling -> Sommer -> Herbst -> Winter."
  },

  // ================================================================
  // 3. KÖRPER & GESUNDHEIT (25 Fragen)
  // ================================================================
  {
    id: "q1_s_056",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Mit welchem Sinnesorgan hören wir Geräusche und Musik?",
    answers: ["Mund", "Nase", "Ohren", "Augen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit unseren beiden Ohren nehmen wir Töne wahr."
  },
  {
    id: "q1_s_057",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Womit riechen wir den Duft einer Blume?",
    answers: ["Zunge", "Nase", "Haut", "Augen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Geruchssinn sitzt in der Nase."
  },
  {
    id: "q1_s_058",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Womit schmecken wir, ob etwas süß oder sauer ist?",
    answers: ["Ohren", "Finger", "Nase", "Zunge"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmacksknospen auf der Zunge lassen uns schmecken."
  },
  {
    id: "q1_s_059",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Mit welchen Organen sehen wir unsere Umwelt?",
    answers: ["Ohren", "Augen", "Füße", "Hände"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit den Augen nehmen wir Licht und Bilder wahr."
  },
  {
    id: "q1_s_060",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Womit fühlen wir, ob sich etwas rau, glatt, warm oder kalt anfühlt?",
    answers: ["Haut (Tastsinn)", "Nase im Alltag", "Augen im Alltag", "Zähne im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Unser Tastsinn funktioniert über die Haut, besonders an den Händen."
  },
  {
    id: "q1_s_061",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie oft am Tag sollte man mindestens die Zähne gründlich putzen?",
    answers: ["Nur einmal im Monat", "Nur an ganz hohen Feiertagen", "Mindestens 2-mal täglich", "Gar nicht putzen müssen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Morgens und abends Zähneputzen schützt vor Karies."
  },
  {
    id: "q1_s_062",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was tun wir mit den Händen vor jedem Essen und nach der Toilette?",
    answers: ["Nur an der Hose abwischen in der Praxis", "Nichts", "Eincremen ohne Waschen in der Praxis", "Gründlich mit Wasser und Seife waschen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Händewaschen entfernt Schmutz und gefährliche Keime."
  },
  {
    id: "q1_s_063",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Organ klopft ununterbrochen in unserer Brust und pumpt Blut?",
    answers: ["Magen", "Herz", "Lunge", "Gehirn"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Herz pumpt pausenlos Blut durch den Körper."
  },
  {
    id: "q1_s_064",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was gehört zu einer gesunden Ernährung dazu?",
    answers: ["Jeden Tag Pommes", "Nur Bonbons und Lollis", "Nur Limonade zur Auswahl", "Frisches Obst und Gemüse"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Obst und Gemüse enthalten viele Vitamine für den Körper."
  },
  {
    id: "q1_s_065",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Warum müssen wir nachts ausreichend schlafen?",
    answers: ["Damit es in der Nacht draußen dunkler wird", "Damit sich Körper und Gehirn erholen können", "Damit unsere alten Schuhe schneller wachsen können", "Nur weil uns abends langweilig ist"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Schlaf tankt der Körper Kraft für den nächsten Tag."
  },
  {
    id: "q1_s_066",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Gelenk verbinden Bein-Ober- und Unterschenkel?",
    answers: ["Schulter", "Knie", "Ellenbogen", "Handgelenk"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Kniegelenk lässt uns die Beine beugen."
  },
  {
    id: "q1_s_067",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie viele Zehen hat ein Mensch im Normalfall an einem Fuß?",
    answers: ["4 Zehen", "8 Zehen", "10 Zehen", "5 Zehen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Wir haben 5 Zehen an jedem Fuß (zusammen 10)."
  },
  {
    id: "q1_s_068",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Getränk ist am besten gegen Durst und gesund?",
    answers: ["Wasser", "Energi drink", "Kola", "Eistee mit viel Zucker"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Reines Wasser ist der beste Durstlöscher ohne Zucker."
  },
  {
    id: "q1_s_069",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wohin sollte man beim Niesen oder Husten am besten niesen?",
    answers: ["Andere Kinder mitten ins Gesicht", "Auf die Handfläche", "Auf den Esstisch", "In die eigene Armbeuge"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "In die Armbeuge niesen verhindert, dass sich Viren über die Hände verteilen."
  },
  {
    id: "q1_s_070",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie heißen die ersten Zähne, die Kinder bekommen und später ausfallen?",
    answers: ["Weisheitszähne", "Milchzähne", "Goldzähne", "Dauerzähne"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die ersten Zähne heissen Milchzähne. Sie machen Platz für die bleibenden Zähne."
  },
  {
    id: "q1_s_071",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wo liegt unser Gehirn geschützt im Körper?",
    answers: ["Tief unten im Bauch", "Im Kopf (Schädel)", "Im linken Fuß unten", "Oben im Rücken"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Gehirn sitzt im Kopf und wird vom Schädelknochen geschützt."
  },
  {
    id: "q1_s_072",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was passiert mit der Lunge, wenn wir tief Luft holen?",
    answers: ["Nichts in der Praxis", "Sie macht Geräusche wie eine Glocke", "Sie füllt sich mit Luft/Sauerstoff", "Sie wird kleiner in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Lunge dehnt sich beim Einatmen aus wie ein Ballon."
  },
  {
    id: "q1_s_073",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Warum tut Bewegung beim Sport dem Körper gut?",
    answers: ["Sie macht uns für immer nur müde und schlapp", "Sie stärkt Muskeln, Herz und Knochen", "Sie lässt unsere Haare schnell ausfallen", "Nur weil man dabei Süßes isst"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Regelmäßige Bewegung hält das Herz fit und kräftigt Muskeln."
  },
  {
    id: "q1_s_074",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welcher Arzt kontrolliert regelmäßig unsere Zähne?",
    answers: ["Zahnarzt", "Tierarzt", "Augenarzt", "Kinderarzt für Ohren"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Zahnarzt schaut nach, ob alle Zähne gesund sind."
  },
  {
    id: "q1_s_075",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Womit nehmen wir Nahrung auf und kauen sie klein?",
    answers: ["Augen", "Hände", "Nase und Ohren", "Mund und Zähne"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Mund wird das Essen mit den Zähnen zerkleinert."
  },
  {
    id: "q1_s_076",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welchen Sinn nutzen blinde Menschen oft besonders stark mit den Fingern?",
    answers: ["Geschmackssinn", "Tastsinn", "Geruchssinn", "Sehsinn"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Blinde erfühlen Erhebungen und Braille-Schrift mit dem Tastsinn der Finger."
  },
  {
    id: "q1_s_077",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was schützt unsere Augen vor Staub und Schweiß?",
    answers: ["Die Haare auf unserem Kopf", "Unsere Ohren und Nase", "Wimpern und Augenbrauen", "Unsere Lippen und Zähne"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Wimpern fangen Staub ab, Augenbrauen halten Schweiß auf."
  },
  {
    id: "q1_s_078",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wo landet geschlucktes Essen als Nächstes im Körper?",
    answers: ["In der Lunge", "Im Kopf", "Im Fuß", "Im Magen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Über die Speiseröhre gelangt die Nahrung direkt in den Magen."
  },
  {
    id: "q1_s_079",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Gefühl warnt uns davor, eine heiße Herdplatte anzufassen?",
    answers: ["Schmerz / Hitze-Gefühl", "Durst in der Praxis", "Hunger in der Praxis", "Müdigkeit in der Praxis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gefühle von Hitze und Schmerz schützen uns vor Verletzungen."
  },
  {
    id: "q1_s_080",
    category: "k1_sachunterricht",
    topic: "koerper",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was befindet sich unter unserer Haut und gibt dem Körper Halt?",
    answers: ["Wasser allein", "Luft in der Praxis", "Skelett / Knochen", "Kissen im Alltag"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Unsere Knochen bilden das Skelett, das uns aufrecht hält."
  },

  // ================================================================
  // 4. VERKEHR & SICHERHEIT (20 Fragen)
  // ================================================================
  {
    id: "q1_s_081",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Farbe hat die Fußgängerampel, wenn du über die Straße gehen darfst?",
    answers: ["Gelb", "Blau", "Rot", "Grün"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Grün heißt: Gehen! Bei Rot musst du stehen."
  },
  {
    id: "q1_s_082",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was bedeutet die ROTE Ampel für Fußgänger und Autos?",
    answers: ["Langsam weiterfahren", "Ganz schnell losrennen", "Stopp / Stehen bleiben!", "Laut hupen und laut rufen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei Rot muss man immer sofort anhalten und warten."
  },
  {
    id: "q1_s_083",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wo überquert man eine Straße ohne Ampel am sichersten?",
    answers: ["Rennend ohne Hinschauen", "Am Zebrastreifen", "In der Kurve", "Mitten zwischen parkenden Autos"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Zebrastreifen ist ein geschützter Fußgängerüberweg."
  },
  {
    id: "q1_s_084",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was musst du beim Fahrradfahren immer zum Schutz auf dem Kopf tragen?",
    answers: ["Eine Wollmütze", "Einen Fahrradhelm", "Eine Basecap", "Gar nichts tragen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Fahrradhelm schützt den Kopf bei Stürzen vor schweren Verletzungen."
  },
  {
    id: "q1_s_085",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie schaust du richtig, bevor du über die Straße gehst?",
    answers: ["Links - Rechts - Links schauen", "Immer nur geradeaus schauen", "Die Augen fest zumachen", "Einfach schnell über die Straße rennen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zuerst nach links, dann nach rechts und nochmal nach links schauen!"
  },
  {
    id: "q1_s_086",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Telefonnummer wählt man in Deutschland bei einem Notfall für die Feuerwehr?",
    answers: ["110", "123", "111", "112"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die 112 ist der kostenfreie Notruf für Feuerwehr und Rettungsdienst."
  },
  {
    id: "q1_s_087",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welche Notrufnummer wählt man direkt für die POLIZEI?",
    answers: ["112", "110", "911", "007"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Polizeinotrufnummer lautet 110."
  },
  {
    id: "q1_s_088",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was hilft dir auf dem Schulweg im Dunkeln, von Autofahrern gut gesehen zu werden?",
    answers: ["Dunkle schwarze Jacke", "Verstecken hinter Bäumen", "Eine Sonnenbrille in der Praxis", "Helle Kleidung und Reflektoren"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Reflektoren leuchten im Scheinwerferlicht der Autos auf."
  },
  {
    id: "q1_s_089",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was musst du im Auto als Erstes tun, wenn du einsteigst?",
    answers: ["Laut Musik hören und mitsingen", "Auf dem Sitz herumhüpfen", "Den Sicherheitsgurt anschnallen", "Sofort ein Buch zu lesen beginnen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Anschnallen ist Pflicht und rettet bei Unfällen Leben!"
  },
  {
    id: "q1_s_090",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Darf man einfach zwischen zwei parkenden Autos auf die Straße laufen?",
    answers: ["Ja, das ist immer völlig ungefährlich für jeden Menschen", "Ja, aber nur wenn man dabei ganz leise ist", "Ja, wenn man dabei besonders schnell rennt", "Nein, weil Autofahrer einen dort nicht sehen können"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Zwischen parkenden Autos wird man leicht übersehen – das ist sehr gefährlich!"
  },
  {
    id: "q1_s_091",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Einsatzfahrzeug hat ein Blaulicht und eine laute Sirene?",
    answers: ["Feuerwehr und Krankenwagen", "Ein normales Fahrrad", "Ein Schulbus in der Praxis", "Ein Müllauto in der Praxis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rettungsfahrzeuge nutzen Martinshorn und Blaulicht bei Notfällen."
  },
  {
    id: "q1_s_092",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wer hilft Kindern vor der Schule oft in leuchtender Westen über die Straße?",
    answers: ["Ein Pilot in der Praxis", "Der Busfahrer während der Fahrt", "Der Bäcker in der Praxis", "Schülerlotsen / Elternlotsen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Schülerlotsen sichern den Übergang an verkehrsreichen Schulwegen."
  },
  {
    id: "q1_s_093",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Auf welcher Seite der Straße sollten Fußgänger gehen, wenn es keinen Gehweg gibt?",
    answers: ["Gegen Mülleimer in der Praxis", "Augen zu auf der rechten Seite", "Dem Verkehr entgegen (links)", "In der Mitte der Fahrbahn"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Geht man dem Verkehr entgegen, sieht man entgegenkommende Autos rechtzeitig."
  },
  {
    id: "q1_s_094",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Warum braucht ein Fahrrad vorn und hinten Lichter sowie Reflektoren?",
    answers: ["Damit man im Dunkeln sieht und selbst gesehen wird", "Damit das Fahrrad dadurch viel schneller fahren kann", "Damit es dabei lustige Töne von sich gibt", "Nur weil es dadurch viel hübscher aussieht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Licht macht das Fahrrad verkehrssicher in der Dämmerung und Nacht."
  },
  {
    id: "q1_s_095",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wer löscht Brände und hilft bei Überschwemmungen?",
    answers: ["Die Feuerwehr", "Die Lehrerin", "Der Krankenpfleger", "Die Post"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Feuerwehr löscht Brände, rettet und birgt."
  },
  {
    id: "q1_s_096",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Wie verhält man sich friedlich und sicher im Schulbus während der Fahrt?",
    answers: ["Ganz laut schreien und wild singen", "Aufstehen und im Gang herumtoben während der Fahrt", "Ruhig sitzen bleiben und nicht herumrenne", "Dem Busfahrer die Augen zuhalten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sitzplatz einnehmen und Ruhe bewahren schützt vor Stürzen beim Bremsen."
  },
  {
    id: "q1_s_097",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was bedeutet ein rotes, achteckiges Schild mit der Aufschrift 'STOP'?",
    answers: ["Parken erlaubt in der Praxis", "Hupen und umdrehen zur Auswahl", "Anhalten und Vorfahrt gewähren", "Schneller weiterfahren"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Beim Stoppschild muss jedes Fahrzeug komplett zum Stillstand kommen."
  },
  {
    id: "q1_s_098",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welches Auto bringt verletzte oder kranke Menschen schnell ins Krankenhaus?",
    answers: ["Rettungswagen / Krankenwagen", "Ein großer gelber Müllwagen", "Ein sehr schneller roter Rennwagen", "Ein alter langsamer Traktor"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sanitäter und Notärzte fahren im Rettungswagen."
  },
  {
    id: "q1_s_099",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Welcher Weg ist für Fußgänger neben der Straße gebaut?",
    answers: ["Der Radweg allein", "Der Gehweg / Bürgersteig", "Die Autobahn zur Auswahl", "Die Schienen zur Auswahl"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Fußgänger nutzen den Gehweg abseits des Autoverkehrs."
  },
  {
    id: "q1_s_100",
    category: "k1_sachunterricht",
    topic: "verkehr",
    area: "schule",
    grade: 1,
    subject: "sachunterricht",
    question: "Was tun alle Schüler, wenn das Signal für Feueralarm in der Schule ertönt?",
    answers: ["Unter die Tische krabbeln und dort ganz still schlafen", "Schnell noch etwas Eis essen gehen", "Die Mappen im Spind gut verstecken", "Ruhig mit der Klasse geordnet ins Freie gehen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei Alarm verlässt man zügig und geordnet mit der Lehrkraft das Gebäude zum Sammelplatz."
  }
];