const K1_MATHE_QUESTIONS = [
  // ================================================================
  // 1. ZÄHLEN & NACHBARZAHLEN (30 Fragen)
  // ================================================================
  {
    id: "q1_m_001",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Finger hat man an beiden Händen zusammen?",
    answers: ["12", "8", "14", "10"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "An jeder Hand sind 5 Finger, zusammen ergibt das 10.",
  },
  {
    id: "q1_m_002",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl ist größer: 5 oder 8?",
    answers: ["5", "Beide gleich", "Man kann es nicht sagen", "8"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die 8 kommt beim Zählen nach der 5, ist also größer.",
  },
  {
    id: "q1_m_003",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl kommt direkt nach der 9?",
    answers: ["11", "12", "10", "8"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Nachfolger der 9 ist die 10.",
  },
  {
    id: "q1_m_004",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl kommt direkt vor der 10?",
    answers: ["7", "8", "9", "11"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Vorgänger der 10 ist die 9.",
  },
  {
    id: "q1_m_005",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl fehlt: 1, 2, 3, __, 5?",
    answers: ["4", "7", "0", "6"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zwischen 3 und 5 liegt die Zahl 4.",
  },
  {
    id: "q1_m_006",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Vorgänger von 7?",
    answers: ["9", "8", "6", "5"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zahl vor der 7 ist die 6.",
  },
  {
    id: "q1_m_007",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Vorgänger von 15?",
    answers: ["14", "15", "13", "16"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Zahl vor der 15 ist die 14.",
  },
  {
    id: "q1_m_008",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Vorgänger von 20?",
    answers: ["21", "19", "18", "10"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Direkt vor der 20 kommt die 19.",
  },
  {
    id: "q1_m_009",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Nachfolger von 14?",
    answers: ["13", "15", "12", "16"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt nach der 14 kommt die 15.",
  },
  {
    id: "q1_m_010",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Nachfolger von 18?",
    answers: ["16", "19", "20", "17"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Direkt nach der 18 kommt die 19.",
  },
  {
    id: "q1_m_011",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was sind die Nachbarzahlen von 8?",
    answers: ["7 und 9", "6 und 7", "8 und 9", "6 und 8"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Vorgänger ist 7, der Nachfolger ist 9.",
  },
  {
    id: "q1_m_012",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was sind die Nachbarzahlen von 15?",
    answers: ["13 und 14", "15 und 17", "14 und 16", "10 und 20"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Vor der 15 steht 14, nach der 15 steht 16.",
  },
  {
    id: "q1_m_013",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was sind die Nachbarzahlen von 11?",
    answers: ["10 und 12", "8 und 12", "11 und 13", "9 und 10"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "10 steht direkt vor der 11, 12 steht direkt danach.",
  },
  {
    id: "q1_m_014",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was sind die Nachbarzahlen von 19?",
    answers: ["19 und 20", "18 und 19", "18 und 20", "17 und 18"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Vorgänger ist 18, der Nachfolger ist 20.",
  },
  {
    id: "q1_m_015",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was sind die Nachbarzahlen von 5?",
    answers: ["5 und 6", "3 und 4", "2 und 4", "4 und 6"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Vor der 5 kommt die 4, nach der 5 kommt die 6.",
  },
  {
    id: "q1_m_016",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welches Zeichen passt: 4 __ 7?",
    answers: ["+", "<", "=", ">"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 ist kleiner als 7 (4 < 7).",
  },
  {
    id: "q1_m_017",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welches Zeichen passt: 15 __ 12?",
    answers: [">", "<", "-", "="],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "15 ist größer als 12 (15 > 12).",
  },
  {
    id: "q1_m_018",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welches Zeichen passt: 9 __ 9?",
    answers: ["=", "<", "+", ">"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Zahlen sind genau gleich groß (9 = 9).",
  },
  {
    id: "q1_m_019",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl liegt genau zwischen 13 und 15?",
    answers: ["12", "16", "14", "11"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Zahl 14 liegt zwischen 13 und 15.",
  },
  {
    id: "q1_m_020",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl liegt genau zwischen 6 und 8?",
    answers: ["4", "7", "9", "5"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die 7 liegt zwischen 6 und 8.",
  },
  {
    id: "q1_m_021",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welches ist die kleinste Zahl: 3, 7, 2, 9?",
    answers: ["7", "2", "9", "3"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die 2 ist die kleinste der genannten Zahlen.",
  },
  {
    id: "q1_m_022",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welches ist die größte Zahl: 12, 18, 14, 9?",
    answers: ["14", "18", "12", "9"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Die 18 ist die größte Zahl in der Auswahl.",
  },
  {
    id: "q1_m_023",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Setze die Reihe fort: 2, 4, 6, __, 10",
    answers: ["9", "5", "8", "7"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Hier wird immer um 2 weitergezählt: Nach 6 kommt 8.",
  },
  {
    id: "q1_m_024",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Setze die Reihe fort: 5, 10, 15, __",
    answers: ["16", "20", "25", "18"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Hier zählen wir in 5er-Schritten: Nach 15 kommt 20.",
  },
  {
    id: "q1_m_025",
    category: "k1_mathe",
    topic: "zaehlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Würfelpunkte sind auf einer höchsten Würfelseite?",
    answers: ["10", "6", "4", "5"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein normaler Spielwürfel hat 1 bis 6 Punkte.",
  },
  {
    id: "q1_m_026",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Vorgänger von 1?",
    answers: ["3", "0", "2", "10"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Vor der 1 kommt die 0.",
  },
  {
    id: "q1_m_027",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Nachfolger von 0?",
    answers: ["10", "2", "0", "1"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt nach der 0 kommt die 1.",
  },
  {
    id: "q1_m_028",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl fehlt: 16, 17, __, 19?",
    answers: ["20", "18", "15", "14"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Zwischen 17 und 19 liegt die 18.",
  },
  {
    id: "q1_m_029",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Vorgänger von 11?",
    answers: ["8", "9", "12", "10"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Direkt vor der 11 kommt die 10.",
  },
  {
    id: "q1_m_030",
    category: "k1_mathe",
    topic: "nachbarzahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist der Nachfolger von 11?",
    answers: ["10", "13", "9", "12"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Direkt nach der 11 kommt die 12.",
  },

  // ================================================================
  // 2. ADDITION (+) (30 Fragen)
  // ================================================================
  {
    id: "q1_m_031",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 3 + 4?",
    answers: ["6", "7", "8", "9"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 plus 4 ergibt zusammen 7.",
  },
  {
    id: "q1_m_032",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 2 + 5?",
    answers: ["8", "6", "7", "9"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "2 und 5 zusammen ergeben 7.",
  },
  {
    id: "q1_m_033",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 1 + 1?",
    answers: ["1", "4", "3", "2"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 plus 1 ergibt 2.",
  },
  {
    id: "q1_m_034",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 5 + 5?",
    answers: ["8", "9", "11", "10"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "5 plus 5 ergibt genau 10.",
  },
  {
    id: "q1_m_035",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 6 + 3?",
    answers: ["10", "7", "9", "8"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "6 und 3 zusammen ergeben 9.",
  },
  {
    id: "q1_m_036",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Das Doppelte von 4: Was ist 4 + 4?",
    answers: ["8", "7", "6", "9"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4 plus 4 ergibt 8.",
  },
  {
    id: "q1_m_037",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 2 + 6?",
    answers: ["10", "8", "9", "7"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "2 plus 6 ergibt 8.",
  },
  {
    id: "q1_m_038",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 7 + 1?",
    answers: ["8", "6", "9", "7"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 plus 1 ist der Nachfolger von 7, also 8.",
  },
  {
    id: "q1_m_039",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Verliebte Zahlen bis 10: 3 + __ = 10",
    answers: ["7", "8", "6", "5"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "3 und 7 sind verliebte Zahlen (zusammen 10).",
  },
  {
    id: "q1_m_040",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Verliebte Zahlen bis 10: 8 + __ = 10",
    answers: ["1", "3", "4", "2"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "8 und 2 sind verliebte Zahlen (zusammen 10).",
  },
  {
    id: "q1_m_041",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Verliebte Zahlen bis 10: 1 + __ = 10",
    answers: ["8", "10", "9", "7"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "1 und 9 sind verliebte Zahlen (zusammen 10).",
  },
  {
    id: "q1_m_042",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Verliebte Zahlen bis 10: 6 + __ = 10",
    answers: ["2", "4", "5", "3"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "6 und 4 sind verliebte Zahlen (zusammen 10).",
  },
  {
    id: "q1_m_043",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Tauschaufgabe: Wenn 3 + 5 = 8 ist, was ist dann 5 + 3?",
    answers: ["9", "10", "7", "8"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Plusaufgabe darf man vertauschen: Das Ergebnis bleibt 8.",
  },
  {
    id: "q1_m_044",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 10 + 4?",
    answers: ["15", "14", "13", "12"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "10 und 4 ergibt zusammen 14.",
  },
  {
    id: "q1_m_045",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 12 + 3?",
    answers: ["15", "13", "14", "16"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "2 + 3 ist 5, also ist 12 + 3 = 15.",
  },
  {
    id: "q1_m_046",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 15 + 2?",
    answers: ["16", "17", "18", "19"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "15 plus 2 ist 17.",
  },
  {
    id: "q1_m_047",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 11 + 5?",
    answers: ["15", "17", "18", "16"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "1 + 5 = 6, also ist 11 + 5 = 16.",
  },
  {
    id: "q1_m_048",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 14 + 4?",
    answers: ["19", "18", "17", "20"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "4 + 4 = 8, also ist 14 + 4 = 18.",
  },
  {
    id: "q1_m_049",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 13 + 3?",
    answers: ["17", "15", "16", "14"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "3 + 3 = 6, also ist 13 + 3 = 16.",
  },
  {
    id: "q1_m_050",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 16 + 1?",
    answers: ["19", "17", "18", "15"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Nachfolger von 16 ist 17.",
  },
  {
    id: "q1_m_051",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 10 + 10?",
    answers: ["20", "18", "10", "15"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zwei Zehner zusammen ergeben 20.",
  },
  {
    id: "q1_m_052",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Das Doppelte von 7: Was ist 7 + 7?",
    answers: ["12", "13", "14", "15"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "7 plus 7 ergibt 14.",
  },
  {
    id: "q1_m_053",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Das Doppelte von 8: Was ist 8 + 8?",
    answers: ["16", "17", "15", "14"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "8 plus 8 ergibt 16.",
  },
  {
    id: "q1_m_054",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Das Doppelte von 9: Was ist 9 + 9?",
    answers: ["20", "18", "19", "17"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "9 plus 9 ergibt 18.",
  },
  {
    id: "q1_m_055",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 8 + 3?",
    answers: ["10", "13", "11", "12"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "8 + 2 ist 10, und 1 dazu ergibt 11.",
  },
  {
    id: "q1_m_056",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 7 + 5?",
    answers: ["11", "14", "12", "13"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "7 + 3 ist 10, und noch 2 dazu macht 12.",
  },
  {
    id: "q1_m_057",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 9 + 4?",
    answers: ["14", "13", "12", "15"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "9 + 1 ist 10, plus 3 sind 13.",
  },
  {
    id: "q1_m_058",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 6 + 5?",
    answers: ["11", "13", "10", "12"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "6 + 4 ist 10, und 1 dazu macht 11.",
  },
  {
    id: "q1_m_059",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 8 + 5?",
    answers: ["15", "12", "13", "14"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "8 + 2 ist 10, plus 3 macht 13.",
  },
  {
    id: "q1_m_060",
    category: "k1_mathe",
    topic: "addition",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 9 + 6?",
    answers: ["15", "16", "14", "17"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "9 + 1 ist 10, plus 5 ergibt 15.",
  },

  // ================================================================
  // 3. SUBTRAKTION (-) (25 Fragen)
  // ================================================================
  {
    id: "q1_m_061",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 10 - 4?",
    answers: ["8", "5", "6", "7"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 10 vier weggenommen bleiben 6.",
  },
  {
    id: "q1_m_062",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 9 - 3?",
    answers: ["7", "8", "6", "5"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 9 drei abgezogen ergibt 6.",
  },
  {
    id: "q1_m_063",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 5 - 2?",
    answers: ["1", "2", "4", "3"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "5 minus 2 ergibt 3.",
  },
  {
    id: "q1_m_064",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 8 - 4?",
    answers: ["4", "5", "2", "3"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "8 minus 4 ist genau die Hälfte, also 4.",
  },
  {
    id: "q1_m_065",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 7 - 2?",
    answers: ["5", "4", "3", "6"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 minus 2 ist 5.",
  },
  {
    id: "q1_m_066",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 6 - 6?",
    answers: ["6", "0", "1", "12"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wenn man von 6 alle 6 wegnimmt, bleibt 0 übrig.",
  },
  {
    id: "q1_m_067",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 10 - 5?",
    answers: ["5", "3", "6", "4"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 minus 5 ergibt 5.",
  },
  {
    id: "q1_m_068",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 8 - 3?",
    answers: ["4", "7", "6", "5"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "8 minus 3 ergibt 5.",
  },
  {
    id: "q1_m_069",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 9 - 5?",
    answers: ["6", "5", "4", "3"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "9 minus 5 ergibt 4.",
  },
  {
    id: "q1_m_070",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 7 - 4?",
    answers: ["3", "5", "4", "2"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 minus 4 ist 3.",
  },
  {
    id: "q1_m_071",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 15 - 3?",
    answers: ["11", "13", "10", "12"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "5 - 3 = 2, also ist 15 - 3 = 12.",
  },
  {
    id: "q1_m_072",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 17 - 5?",
    answers: ["12", "14", "11", "13"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "7 - 5 = 2, also ist 17 - 5 = 12.",
  },
  {
    id: "q1_m_073",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 19 - 4?",
    answers: ["14", "16", "15", "13"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "9 - 4 = 5, also ist 19 - 4 = 15.",
  },
  {
    id: "q1_m_074",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 14 - 2?",
    answers: ["10", "11", "12", "13"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "14 minus 2 macht 12.",
  },
  {
    id: "q1_m_075",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 16 - 6?",
    answers: ["9", "12", "11", "10"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Zieht man die 6 Einser ab, bleibt genau der Zehner (10).",
  },
  {
    id: "q1_m_076",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 18 - 3?",
    answers: ["14", "15", "17", "16"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "8 - 3 = 5, also ist 18 - 3 = 15.",
  },
  {
    id: "q1_m_077",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 13 - 3?",
    answers: ["9", "12", "10", "11"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "13 minus 3 ergibt 10.",
  },
  {
    id: "q1_m_078",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 20 - 5?",
    answers: ["16", "14", "10", "15"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "20 minus 5 ergibt 15.",
  },
  {
    id: "q1_m_079",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 20 - 10?",
    answers: ["10", "5", "15", "0"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "20 minus 10 ergibt genau 10.",
  },
  {
    id: "q1_m_080",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Umkehraufgabe: Wenn 7 + 3 = 10 ist, was ist dann 10 - 3?",
    answers: ["6", "8", "3", "7"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Umkehraufgabe kehrt die Plusaufgabe um: 10 - 3 = 7.",
  },
  {
    id: "q1_m_081",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 11 - 2?",
    answers: ["8", "7", "9", "10"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "11 - 1 = 10, noch 1 weg ist 9.",
  },
  {
    id: "q1_m_082",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 12 - 4?",
    answers: ["9", "8", "6", "7"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "12 - 2 = 10, minus 2 ist 8.",
  },
  {
    id: "q1_m_083",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 14 - 5?",
    answers: ["8", "9", "7", "10"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "14 - 4 = 10, minus 1 ist 9.",
  },
  {
    id: "q1_m_084",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 13 - 6?",
    answers: ["9", "6", "8", "7"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "13 - 3 = 10, minus 3 ist 7.",
  },
  {
    id: "q1_m_085",
    category: "k1_mathe",
    topic: "subtraktion",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist 15 - 7?",
    answers: ["7", "6", "8", "9"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "15 - 5 = 10, minus 2 ist 8.",
  },

  // ================================================================
  // 4. GEOMETRIE & GRÖSSEN (15 Fragen)
  // ================================================================
  {
    id: "q1_m_086",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Ecken hat ein Dreieck?",
    answers: ["3", "5", "2", "4"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Dreieck heißt so, weil es 3 Ecken hat.",
  },
  {
    id: "q1_m_087",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Form hat ein Fußball?",
    answers: ["Würfel", "Kugel", "Quadrat", "Dreieck"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Fußball ist rund und körperlich eine Kugel.",
  },
  {
    id: "q1_m_088",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Ecken hat ein Quadrat?",
    answers: ["4", "6", "5", "3"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Quadrat hat genau 4 Ecken und 4 gleich lange Seiten.",
  },
  {
    id: "q1_m_089",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Form hat eine Schokoladentafel oft?",
    answers: ["Quadrat", "Sechseck", "Rechteck", "Fünfeck"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Schokoladentafel ist flach mit 4 Ecken und langen/kurzen Seiten: ein Rechteck.",
  },
  {
    id: "q1_m_090",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Seiten hat ein Quadrat?",
    answers: ["3", "2", "4", "5"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Quadrat hat 4 Seiten, die alle gleich lang sind.",
  },
  {
    id: "q1_m_091",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Ecken hat ein Kreis?",
    answers: ["2", "4", "0", "1"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Kreis ist vollkommen rund und hat 0 Ecken.",
  },
  {
    id: "q1_m_092",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Womit bezahlt man im Supermarkt in Deutschland?",
    answers: ["Muscheln und Perlen", "Euro und Cent", "Bonbons und Sterne", "Steine und Blätter"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Unsere Währung ist der Euro (und Cent).",
  },
  {
    id: "q1_m_093",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Mia hat 2 Euro und bekommt 3 Euro dazu. Wie viel Euro hat sie?",
    answers: ["10 Euro", "6 Euro", "5 Euro", "4 Euro"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "2 Euro + 3 Euro = 5 Euro.",
  },
  {
    id: "q1_m_094",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Was ist mehr wert?",
    answers: ["1 Euro", "20 Cent", "10 Cent", "50 Cent"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "1 Euro entspricht 100 Cent und ist somit mehr als 50 Cent.",
  },
  {
    id: "q1_m_095",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Du kaufst ein Eis für 2 Euro und bezahlst mit 5 Euro. Wie viel Wechselgeld bekommst du?",
    answers: ["4 Euro", "3 Euro", "2 Euro", "1 Euro"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "5 Euro minus 2 Euro für das Eis = 3 Euro Wechselgeld.",
  },
  {
    id: "q1_m_096",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Der kleine Zeiger steht auf der 3, der große auf der 12. Wie viel Uhr ist es?",
    answers: ["6 Uhr", "3 Uhr", "15 Uhr", "12 Uhr"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der kleine Zeiger zeigt die Stunde: Es ist genau 3 Uhr.",
  },
  {
    id: "q1_m_097",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Der kleine Zeiger steht auf der 8, der große auf der 12. Wie viel Uhr ist es?",
    answers: ["4 Uhr", "10 Uhr", "8 Uhr", "12 Uhr"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der kleine Zeiger steht auf der 8, also ist es 8 Uhr.",
  },
  {
    id: "q1_m_098",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Der kleine und der große Zeiger stehen beide oben auf der 12. Wie viel Uhr ist es?",
    answers: ["12 Uhr", "24 Uhr", "6 Uhr", "1 Uhr"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wenn beide Zeiger auf der 12 stehen, ist es 12 Uhr.",
  },
  {
    id: "q1_m_099",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Tage hat eine Woche?",
    answers: ["10 Tage", "12 Tage", "5 Tage", "7 Tage"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Woche besteht aus genau 7 Tagen.",
  },
  {
    id: "q1_m_100",
    category: "k1_mathe",
    topic: "geometrie",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welcher Tag kommt direkt nach dem Dienstag?",
    answers: ["Donnerstag", "Montag", "Freitag", "Mittwoch"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Reihenfolge ist: Montag, Dienstag, Mittwoch.",
  },

  {
    id: "q1_m_vz01",
    category: "k1_mathe",
    topic: "verliebte_zahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl ist die 'verliebte Zahl' zur 7 (ergänze zu 10)?",
    answers: ["3", "4", "2", "5"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 und 3 sind verliebte Zahlen, weil 7 + 3 = 10 ist."
  },
  {
    id: "q1_m_vz02",
    category: "k1_mathe",
    topic: "verliebte_zahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl fehlt: 4 + __ = 10?",
    answers: ["4", "7", "6", "5"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "4 und 6 ergeben zusammen 10."
  },
  {
    id: "q1_m_vz03",
    category: "k1_mathe",
    topic: "verliebte_zahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche zwei Zahlen sind 'verliebte Zahlen'?",
    answers: ["2 und 8", "1 und 7", "4 und 4", "3 und 5"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "2 + 8 = 10, daher sind 2 und 8 verliebte Zahlen."
  },
  {
    id: "q1_m_vz04",
    category: "k1_mathe",
    topic: "verliebte_zahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl ist die 'verliebte Zahl' zur 1?",
    answers: ["8", "10", "7", "9"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "1 und 9 ergeben zusammen 10."
  },
  {
    id: "q1_m_vz05",
    category: "k1_mathe",
    topic: "verliebte_zahlen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welche Zahl ist mit der 5 verliebt?",
    answers: ["4", "6", "0", "5"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "5 + 5 = 10. Die 5 ist mit sich selbst verliebt!"
  },
  {
    id: "q1_m_gm01",
    category: "k1_mathe",
    topic: "groessen_messen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Wie viele Cent sind 1 Euro?",
    answers: ["10 Cent", "100 Cent", "200 Cent", "50 Cent"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "1 Euro besteht genau aus 100 Cent."
  },
  {
    id: "q1_m_gm02",
    category: "k1_mathe",
    topic: "groessen_messen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Du hast eine 5-Cent-Münze und eine 2-Cent-Münze. Wie viel Cent ist das zusammen?",
    answers: ["7 Cent", "6 Cent", "10 Cent", "8 Cent"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "5 Cent + 2 Cent = 7 Cent."
  },
  {
    id: "q1_m_gm03",
    category: "k1_mathe",
    topic: "groessen_messen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Der kleine Zeiger steht auf der 4, der große auf der 12. Wie viel Uhr ist es?",
    answers: ["12 Uhr", "1 Uhr", "8 Uhr", "4 Uhr"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Der kleine Zeiger zeigt die Stunden an. Wenn der große auf der 12 steht, ist es punkt 4 Uhr."
  },
  {
    id: "q1_m_gm04",
    category: "k1_mathe",
    topic: "groessen_messen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welcher Wochentag kommt direkt nach dem Sonntag?",
    answers: ["Montag", "Freitag", "Samstag", "Dienstag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit dem Montag beginnt die neue Woche."
  },
  {
    id: "q1_m_gm05",
    category: "k1_mathe",
    topic: "groessen_messen",
    area: "schule",
    grade: 1,
    subject: "mathe",
    question: "Welcher Tag liegt genau zwischen Mittwoch und Freitag?",
    answers: ["Dienstag", "Samstag", "Übermorgen", "Donnerstag"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Reihenfolge ist: Mittwoch, Donnerstag, Freitag."
  }
];