export const QUESTIONS_KINDER_TIERE_NATUR = [
    // 001
    {
        id: "k_tn_001",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Haustier macht leise 'Miau' und schnurrt gerne?",
        answers: ["Eine Hauskatze", "Ein kleiner Hund", "Ein buntes Huhn", "Eine braune Kuh"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Katzen miauen, um mit Menschen zu kommunizieren."
    },
    {
        id: "k_tn_002",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier legt auf dem Bauernhof die frischen Eier?",
        answers: ["Die Milchkuh", "Das Haushuhn", "Das Wollschaf", "Das Rosa-Schwein"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Hühner legen täglich Eier in ihrem Nest."
    },
    {
        id: "k_tn_003",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat frisches Gras auf der Wiese im Frühling?",
        answers: ["Bunte Farbe", "Gelbe Farbe", "Grüne Farbe", "Blaue Farbe"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Chlorophyll in den Halmen färbt das Gras grün."
    },
    {
        id: "k_tn_004",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier trägt sein eigenes Haus immer auf dem Rücken?",
        answers: ["Der Regenwurm", "Der Waldkäfer", "Die Marienkäfer", "Die Landschnecke"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Schnecken ziehen sich bei Gefahr in ihr Schneckenhaus zurück."
    },
    {
        id: "k_tn_005",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Wüstentier hat einen oder zwei Höcker auf dem Rücken?",
        answers: ["Das Kamel", "Der Elefant", "Das Nashorn", "Die Giraffe"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Kamele speichern Fett in ihren Höckern als Energievorrat."
    },
    {
        id: "k_tn_006",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Meerestier hat acht Arme und schießt schwarze Tinte?",
        answers: ["Der Seestern", "Der Oktopus", "Der Blauwal", "Der Hammerhai"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Oktopusse nutzen Tinte zur Abwehr von Feinden."
    },
    {
        id: "k_tn_007",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Aus welchen Gebilden bauen Vögel im Frühling ihre Nester?",
        answers: ["Aus Plastik", "Aus Steinen", "Aus Zweigen", "Aus Blättern"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Vögel verflechten kleine Zweige, Halme und Moos zu Nestern."
    },
    {
        id: "k_tn_008",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Was stellen Bienen aus dem gesammelten Blütennektar her?",
        answers: ["Süßen Saft", "Warme Milch", "Kaltes Eis", "Süßen Honig"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Bienen verarbeiten Nektar zu nahrhaftem Honig."
    },
    {
        id: "k_tn_009",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Raubtier wird oft als 'König der Tiere' bezeichnet?",
        answers: ["Der Steppenlöwe", "Der Königstiger", "Der Braunbär", "Der Silberwolf"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Wegen seiner prächtigen Mähne nennt man den Löwen König der Tiere."
    },
    {
        id: "k_tn_010",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Aus welchem Insekt entsteht nach der Verpuppung ein Schmetterling?",
        answers: ["Aus der Fliege", "Aus der Raupe", "Aus der Mücke", "Aus der Biene"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Raupe verpuppt sich und verwandelt sich in einen Schmetterling."
    },
    {
        id: "k_tn_011",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier baut im Fluss mit Stöcken große Staudämme?",
        answers: ["Der Fischotter", "Der Flusskrebs", "Der Fleißige Biber", "Die Bisamratte"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Biber fällen Bäume mit den Zähnen und bauen feste Dämme."
    },
    {
        id: "k_tn_012",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Wo leben Pinguine in großer Zahl in freier Wildbahn?",
        answers: ["Im Wüstensand", "Im Regenwald", "In den Bergen", "Im Ewigen Eis"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Die meisten Pinguinarten leben in den kalten Regionen der Südhalbkugel."
    },
    {
        id: "k_tn_013",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches kleine Tier hat rote Flügeldecken mit schwarzen Punkten?",
        answers: ["Der Marienkäfer", "Der Kartoffelkäfer", "Der Rosenkäfer", "Der Glühwürmchen"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Siebenpunkt-Marienkäfer ist ein bekannter Glücksbringer."
    },
    {
        id: "k_tn_014",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist das größte lebende Säugetier der Welt?",
        answers: ["Der Elefant", "Der Blauwal", "Die Giraffe", "Das Nashorn"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Blauwal lebt im Ozean und wiegt bis zu 150 Tonnen."
    },
    {
        id: "k_tn_015",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Womit atmen Fische unter Wasser den Sauerstoff ein?",
        answers: ["Mit der Lunge", "Mit der Haut", "Mit den Kiemen", "Mit den Flossen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Kiemen filtern den gelösten Sauerstoff direkt aus dem Wasser."
    },
    {
        id: "k_tn_016",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Heimtier frisst am liebsten frische Karotten und Heu?",
        answers: ["Der Wellensittich", "Die Hauskatze", "Der Goldfisch", "Das Zwergkaninchen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Kaninchen ernähren sich hauptsächlich von Gras, Heu und Gemüseraspeln."
    },
    {
        id: "k_tn_017",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Stacheltier rollt sich bei Gefahr zu einer Kugel zusammen?",
        answers: ["Der Waldigel", "Das Stachelschwein", "Der Erdvogel", "Der Maulwurf"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Igel richten ihre spitzen Stacheln auf und schützen sich als Kugel."
    },
    {
        id: "k_tn_018",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche Pflanzenart verliert im Herbst ihre bunten Blätter?",
        answers: ["Der Nadelbaum", "Der Laubbaum", "Der Kaktus", "Der Farn"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Laubbäume werfen ihre Blätter ab, um im Winter Wasser zu sparen."
    },
    {
        id: "k_tn_019",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier hüpft mit langen Hinterbeinen durch Australien?",
        answers: ["Der Bär", "Der Wolf", "Das Känguru", "Der Fuchs"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Kängurus sind Beuteltiere und bewegen sich springend fort."
    },
    {
        id: "k_tn_020",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Wo verbringen Zugvögel den kalten europäischen Winter?",
        answers: ["Im Nordpol", "Im Eismeer", "In den Alpen", "Im Süden"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Viele Zugvögel fliegen im Herbst in wärmere südliche Länder."
    },

    // 021 - 040
    {
        id: "k_tn_021",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel kann als einziger starr rückwärts fliegen?",
        answers: ["Der Kolibri", "Der Spatz", "Der Adler", "Die Schwalbe"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Kolibris können ihre Flügel so schnell bewegen, dass sie rückwärts fliegen."
    },
    {
        id: "k_tn_022",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches schwarze Tier gräbt lange Haufen und Tunnels unter der Erde?",
        answers: ["Die Feldmaus", "Der Maulwurf", "Der Dachs", "Der Hamster"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Maulwürfe schaufeln mit ihren Grabschaufeln Gänge in den Boden."
    },
    {
        id: "k_tn_023",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Woraus besteht der Stamm eines großen Baumes im Wald?",
        answers: ["Aus Stein", "Aus Metall", "Aus Holz", "Aus Erde"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Baumstämme bestehen aus stabilem Holz und sind von Rinde geschützt."
    },
    {
        id: "k_tn_024",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier gibt uns die frische Trinkmilch?",
        answers: ["Das Pferd", "Der Hund", "Das Schaf", "Die Kuh"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Kühe werden auf dem Bauernhof gemolken, um Milch zu gewinnen."
    },
    {
        id: "k_tn_025",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die Babys von Hunden kurz nach der Geburt?",
        answers: ["Welpen", "Ferkel", "Küken", "Lämmer"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Junge Hunde nennt man im ersten Lebensjahr Welpen."
    },
    {
        id: "k_tn_026",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher große Schwarzbär frisst fast ausschließlich grünen Bambus?",
        answers: ["Der Eisbär", "Der Pandabär", "Der Koalabär", "Der Braunbär"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Große Pandas ernähren sich zu 99 Prozent von Bambuspflanzen."
    },
    {
        id: "k_tn_027",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Wassertier hat scharfe Zähne und eine spitze Rückenflosse?",
        answers: ["Der Delfin", "Der Seelöwe", "Der Hai", "Der Rochen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Haie sind Raubfische mit Knorpelskelett und scharfen Zähnen."
    },
    {
        id: "k_tn_028",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Was wächst im Wald auf dem Boden und hat einen Hut?",
        answers: ["Die Blume", "Das Moos", "Der Farn", "Der Pilz"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Viele Pilzarten bestehen aus einem Stiel und einem Hut."
    },
    {
        id: "k_tn_029",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches kleine Tier sammelt im Herbst Nüsse für den Winter?",
        answers: ["Das Eichhörnchen", "Die Feldmaus", "Der Waldigel", "Der Siebenschläfer"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Eichhörnchen vergraben Nüsse als Vorrat für kalte Tage."
    },
    {
        id: "k_tn_030",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt hat bunte Flügel und fliegt von Blüte zu Blüte?",
        answers: ["Die Fliege", "Der Schmetterling", "Die Wespe", "Der Käfer"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Schmetterlinge trinken Nektar mit ihrem langen Saugrüssel."
    },
    {
        id: "k_tn_031",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist für sein wolliges Fell bekannt, aus dem Wolle gemacht wird?",
        answers: ["Die Ziege", "Das Pferd", "Das Schaf", "Das Schwein"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Schafe werden einmal im Jahr geschoren, um Wolle zu gewinnen."
    },
    {
        id: "k_tn_032",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt nervt uns im Sommer mit summenden Stichen?",
        answers: ["Die Biene", "Die Ameise", "Der Käfer", "Die Mücke"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Weibliche Stechmücken saugen Blut, um Eier bilden zu können."
    },
    {
        id: "k_tn_033",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches grüne Tier quakt am Teich und kann weit hüpfen?",
        answers: ["Der Frosch", "Die Kröte", "Der Molch", "Die Eidechse"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Frösche sind Amphibien, die an Land und im Wasser leben."
    },
    {
        id: "k_tn_034",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches große Wüstentier kann wochenlang ohne Wasser überleben?",
        answers: ["Der Löwe", "Das Kamel", "Die Hyäne", "Der Gepard"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Kamele passen ihren Wasserhaushalt perfekt an die Trockenheit an."
    },
    {
        id: "k_tn_035",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches flugfähige Säugetier schläft tagsüber mit dem Kopf nach unten?",
        answers: ["Eule", "Specht", "Fledermaus", "Schwalbe"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Fledermäuse hängen sich zum Schlafen an Krallen an Höhlendecken."
    },
    {
        id: "k_tn_036",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Raubtier hat Streifen auf dem Fell und gehört zu den Katzen?",
        answers: ["Der Löwe", "Der Luchs", "Der Gepard", "Der Tiger"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Tiger sind die größten Katzen der Welt und besitzen dunkle Streifen."
    },
    {
        id: "k_tn_037",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier baut hügelartige Bauten aus Nadeln im Wald?",
        answers: ["Die Ameise", "Der Biber", "Die Biene", "Der Maulwurf"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Waldameisen türmen riesige Ameisenhügel aus Fichtennadeln auf."
    },
    {
        id: "k_tn_038",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die Jungtiere der Katzen?",
        answers: ["Welpen", "Kätzchen", "Ferkel", "Lämmer"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Junge Katzen nennt man Kätzchen oder Katzenwelpen."
    },
    {
        id: "k_tn_039",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches gepanzerte Reptil bewegt sich an Land sehr langsam fort?",
        answers: ["Die Eidechse", "Das Krokodil", "Die Schildkröte", "Die Schlange"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Schildkröten sind durch ihren harten Rückenpanzer gut geschützt."
    },
    {
        id: "k_tn_040",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel hämmert mit dem Schnabel Löcher in Baumstämme?",
        answers: ["Der Spatz", "Die Amsel", "Der Star", "Der Specht"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Buntspechte meißeln Rinde auf, um an Insektenlarven zu gelangen."
    },

    // 041 - 060
    {
        id: "k_tn_041",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches bunte Tier kann menschliche Worte nachsprechen?",
        answers: ["Der Papagei", "Der Kanarienvogel", "Der Wellensittich", "Die Taube"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Viele Papageienarten imitierten Geräusche und Stimmen."
    },
    {
        id: "k_tn_042",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Säugetier hat einen langen Rüssel und große Ohren?",
        answers: ["Das Nashorn", "Der Elefant", "Das Flusspferd", "Die Giraffe"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Elefanten nutzen ihren Rüssel als Nase und Greifwerkzeug."
    },
    {
        id: "k_tn_043",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Meerestier hat die Form eines Sterns?",
        answers: ["Der Krebs", "Die Qualle", "Der Seestern", "Der Rochen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Seesterne haben meist fünf Arme und leben auf dem Meeresboden."
    },
    {
        id: "k_tn_044",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Haustier bellt laut, wenn es den Besuch ankündigt?",
        answers: ["Die Katze", "Das Kaninchen", "Der Meerschweinchen", "Der Hund"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Hunde bellen, um ihr Revier zu verteidigen oder Freude zu zeigen."
    },
    {
        id: "k_tn_045",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches weiße Tier lebt im Schnee der arktischen Eiswüsten?",
        answers: ["Der Eisbär", "Der Braungrizzly", "Der Schwarzbär", "Der Kragenbär"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Eisbären sind durch ihr weißes Fell perfekt getarnt."
    },
    {
        id: "k_tn_046",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches langgestreckte Tier hat keine Beine und gleitet lautlos?",
        answers: ["Der Wurm", "Die Schlange", "Die Eidechse", "Der Raupe"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Schlangen bewegen sich durch Muskelwellen ohne Beine fort."
    },
    {
        id: "k_tn_047",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches rosa Tier wälzt sich gern im Schlamm zur Kühlung?",
        answers: ["Die Kuh", "Das Schaf", "Das Schwein", "Die Ziege"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Schweine nutzen Schlamm als Sonnenschutz und zur Abkühlung."
    },
    {
        id: "k_tn_048",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Raubvogel sieht nachts mit großen Augen extrem gut?",
        answers: ["Der Falken", "Der Adler", "Bussard", "Die Eule"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Eulen sind nachtaktiv und jagen Mäuse im Dunkeln."
    },
    {
        id: "k_tn_049",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Meerestier ist extrem intelligent und springt aus dem Wasser?",
        answers: ["Der Delfin", "Der Hai", "Der Thunfisch", "Der Schwamm"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Delfine sind Säugetiere, die in Gruppen (Schulen) schwimmen."
    },
    {
        id: "k_tn_050",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Hufsäugetier wird vom Menschen geritten und hat eine Mähne?",
        answers: ["Die Kuh", "Das Pferd", "Der Esel", "Das Schaf"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Pferde sind seit Jahrtausenden Begleiter des Menschen."
    },
    {
        id: "k_tn_051",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches scheue Waldtier trägt im Sommer ein geflecktes Fell?",
        answers: ["Der Wolf", "Der Dachs", "Das Rehkitz", "Der Marder"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Junge Rehkitze haben Punkte auf dem Rücken zur Tarnung im Gras."
    },
    {
        id: "k_tn_052",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier hat ein schwarz-weißes Fell mit Streifen muster?",
        answers: ["Das Pferd", "Der Esel", "Das Okapi", "Das Zebra"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Zebras tragen Streifen, die Insekten abwehren und verwirren."
    },
    {
        id: "k_tn_053",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Säugetier hängt den ganzen Tag faul im Baum?",
        answers: ["Das Faultier", "Der Koala", "Der Lemur", "Das Opossum"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Faultiere bewegen sich extrem langsam und schlafen viele Stunden."
    },
    {
        id: "k_tn_054",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Beuteltier frisst fast nur die Blätter von Eukalyptusbäumen?",
        answers: ["Das Känguru", "Der Koala", "Der Wombat", "Der Beutelteufel"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Koalas schlafen viel, weil Eukalyptus wenig Energie liefert."
    },
    {
        id: "k_tn_055",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche Blumenart dreht ihre Blüte immer nach dem Sonnenlicht?",
        answers: ["Die Rose", "Die Tulpe", "Die Sonnenblume", "Die Gänseblümchen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Junge Sonnenblumen folgen im Tagesverlauf dem Stand der Sonne."
    },
    {
        id: "k_tn_056",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier klettert behände von Ast zu Ast in den Bäumen?",
        answers: ["Der Hund", "Das Schwein", "Das Schaf", "Der Affe"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Affen nutzen Hände, Füße und oft auch ihren Schwanz zum Klettern."
    },
    {
        id: "k_tn_057",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel schlägt im Rad sein prächtiges buntes Gefieder auf?",
        answers: ["Der Pfau", "Der Fasan", "Der Flamingo", "Der Kakadu"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Pfauenmännchen schlagen ihr Rad, um Weibchen zu beeindrucken."
    },
    {
        id: "k_tn_058",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher rosafarbene Vogel steht oft auf nur einem Bein im Wasser?",
        answers: ["Der Storch", "Der Flamingo", "Der Reiher", "Der Pelikan"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Flamingos sparen Energie, wenn sie auf einem Bein ruhen."
    },
    {
        id: "k_tn_059",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche weiße Frühlingsblume sprießt oft schon durch den Schnee?",
        answers: ["Die Osterglocke", "Die Tulpe", "Das Schneeglöckchen", "Das Veilchen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Schneeglöckchen blühen bereits sehr früh im Jahr."
    },
    {
        id: "k_tn_060",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Stacheltier schützt sich durch lange Stacheln auf dem Rücken?",
        answers: ["Der Igel", "Die Raupe", "Der Seegurke", "Das Stachelschwein"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Stachelschweine haben weitaus längere Stacheln als normale Igel."
    },

    // 061 - 080
    {
        id: "k_tn_061",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel bringt im Märchen den Neugeborenen die Eier oder Babys?",
        answers: ["Der Storch", "Der Kranich", "Der Schwan", "Der Reiher"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "In alten Volkssagen gilt der Klapperstorch als Babybringer."
    },
    {
        id: "k_tn_062",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier verfärbt seine Haut zur Tarnung in der Umgebung?",
        answers: ["Die Eidechse", "Das Chamäleon", "Der Frosch", "Die Kropfkröte"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Chamäleons wechseln die Farbe zur Kommunikation und Tarnung."
    },
    {
        id: "k_tn_063",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche gelbe Blume verwandelt sich später in eine Pusteblume?",
        answers: ["Die Butterblume", "Die Sonnenblume", "Der Löwenzahn", "Die Narzisse"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Samen des Löwenzahns fliegen als Schirmchen vom Wind davon."
    },
    {
        id: "k_tn_064",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Nagetier hat dicke Backentaschen zum Nüsse transportieren?",
        answers: ["Die Hausmaus", "Rennmaus", "Das Meerschweinchen", "Der Feldhamster"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Hamster stopfen Vorräte in ihre elastischen Backentaschen."
    },
    {
        id: "k_tn_065",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher stolze Vogel mit rotem Kamm kräht morgens auf dem Zaun?",
        answers: ["Der Hahn", "Der Truthahn", "Der Erpel", "Der Gockel"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Hahn kräht morgens, um sein Revier abzustecken."
    },
    {
        id: "k_tn_066",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt baut aus Erde feste Hügel in Afrika?",
        answers: ["Die Ameise", "Die Termite", "Die Wespe", "Hornisse"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Termiten bauen meterdicke Bauten mit Belüftungssystemen."
    },
    {
        id: "k_tn_067",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche nützlichen Tiere lockern den Gartenboden auf?",
        answers: ["Die Schnecken", "Die Raupen", "Die Regenwürmer", "Die Käfer"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Regenwürmer fressen Erde und hinterlassen fruchtbaren Humus."
    },
    {
        id: "k_tn_068",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Wassertier hat zwei große Scheren zum Kneifen?",
        answers: ["Der Garnelenfisch", "Der Seestern", "Der Seepferd", "Der Strandkrebs"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Krebse nutzen ihre Scheren zur Verteidigung und Nahrungssuche."
    },
    {
        id: "k_tn_069",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Raubtier lebt in Rudeln und heult den Mond an?",
        answers: ["Der Waldwolf", "Der Rotfuchs", "Der Goldschakal", "Der Steppenhyäne"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Wölfe heulen, um sich mit ihrem Rudel über Distanzen zu verständigen."
    },
    {
        id: "k_tn_070",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche Frucht fällt im Herbst im braunen Stachelpanzer vom Kastanienbaum?",
        answers: ["Die Eichel", "Die Kastanie", "Die Bucheckern", "Die Walnuss"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Roßkastanien liegen in stachligen grünen Hüllen am Boden."
    },
    {
        id: "k_tn_071",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher kleine Singvogel hat eine rote Brust?",
        answers: ["Die Blaumeise", "Der Buchfink", "Das Rotkehlchen", "Der Grünfink"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Rotkehlchen ist an seinem orange-roten Lätzchen leicht erkennbar."
    },
    {
        id: "k_tn_072",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Raubtier schleicht mit rotem Fell und buschigem Schwanz durch den Wald?",
        answers: ["Der Wolf", "Der Marder", "Der Luchs", "Der Rotfuchs"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Füchse haben ein rötliches Fell und eine weiße Schwanzspitze."
    },
    {
        id: "k_tn_073",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches kleine Tier leuchtet lauen Sommernächten im Dunkeln?",
        answers: ["Das Glühwürmchen", "Der Marienkäfer", "Der Rosenkäfer", "Die Goldfliege"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Glühwürmchen erzeugen Licht durch eine chemische Reaktion."
    },
    {
        id: "k_tn_074",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Baum behält auch im schneereichen Winter seine grünen Nadeln?",
        answers: ["Die Eiche", "Die Tanne", "Die Buche", "Der Ahorn"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Tannen und Fichten sind Nadelbäume, die ihre Nadeln im Winter nicht verlieren."
    },
    {
        id: "k_tn_075",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Säugetier verschläft den gesamten Winter fest im Versteck?",
        answers: ["Der Wolf", "Der Hirsch", "Der Siebenschläfer", "Das Wildschwein"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Siebenschläfer halten bis zu sieben Monate Winterschlaf."
    },
    {
        id: "k_tn_076",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Meeresfisch sieht aus wie eine Spielfigur auf dem Schachbrett?",
        answers: ["Der Clownsfish", "Der Kugelfisch", "Der Drachenfisch", "Das Seepferdchen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Seepferdchen haben einen Kopf, der dem eines Pferdes ähnelt."
    },
    {
        id: "k_tn_077",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Raubtier hat dunkle Flecken auf dem gelben Fell und rennt extrem schnell?",
        answers: ["Der Gepard", "Der Löwe", "Der Tiger", "Der Schwarzbär"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Geparden sind die schnellsten Landtiere der Welt."
    },
    {
        id: "k_tn_078",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Wie nennt man die männliche Ente mit dem grün leuchtenden Kopf?",
        answers: ["Der Gockel", "Der Erpel", "Der Ganter", "Der Hahn"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Männliche Stockenten heißen Erpel und tragen ein buntes Prachtkleid."
    },
    {
        id: "k_tn_079",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt gelb-schwarz gestreift baut Waben aus Wachs?",
        answers: ["Die Fliege", "Die Hummel", "Die Honigbiene", "Die Mücke"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Bienen schwitzen Wachs aus, um Sechseckwaben für Honig zu bauen."
    },
    {
        id: "k_tn_080",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier spuckt zur Verteidigung Magensaft und Spucke?",
        answers: ["Das Kamel", "Der Strauß", "Das Eselchen", "Das Lama"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Lamas spucken Zielgenau, wenn sie sich bedroht fühlen."
    },

    // 081 - 100
    {
        id: "k_tn_081",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier sticht mit dem Stachel nur einmal, weil er stecken bleibt?",
        answers: ["Die Honigbiene", "Die Feldwespe", "Die Hornisse", "Die Mücke"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Stachel der Honigbiene hat Widerhaken und verbleibt in der Haut."
    },
    {
        id: "k_tn_082",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Wasservogel ist komplett weiß und hat einen langen gebogenen Hals?",
        answers: ["Die Ente", "Der Höckerschwan", "Die Kormoran", "Die Möwe"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Schwäne sind große Wasservögel mit schneeweißem Gefieder."
    },
    {
        id: "k_tn_083",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche dicke brummende Biene ist dicht pelzig behaart?",
        answers: ["Die Wespe", "Die Hornisse", "Die Hummel", "Die Bremse"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Hummeln sind pelzige Wildbienen, die auch bei Kälte fliegen."
    },
    {
        id: "k_tn_084",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Fisch bläst sich bei Gefahr kugelrund mit Wasser auf?",
        answers: ["Der Goldfisch", "Der Thunfisch", "Der Seeteufel", "Der Kugelfisch"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Kugelfische pumpen Wasser in ihren Magen, um Fressfeinde abzuschrecken."
    },
    {
        id: "k_tn_085",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Huftier trägt ein prächtiges Geweih auf dem Kopf?",
        answers: ["Der Rothirsch", "Das Hausschwein", "Das Zwergschaf", "Das Wildpferd"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Hirsche werfen ihr Geweih jedes Jahr ab und wachsen es neu."
    },
    {
        id: "k_tn_086",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche nützlichen Tiere stellen aus Blütennektar süßen Honig her?",
        answers: ["Die Wespen", "Die Bienen", "Die Fliegen", "Die Mücken"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Honigbienen fliegen im Frühling von Blüte zu Blüte."
    },
    {
        id: "k_tn_087",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Grauvogel lebt in Städten und frisst Brotkrumen im Park?",
        answers: ["Der Adler", "Der Fasan", "Die Taube", "Der Specht"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Stadttauben sind an das Leben nahe dem Menschen angepasst."
    },
    {
        id: "k_tn_088",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier hat eine schwarze Fellmaske und wäscht seine Nahrung?",
        answers: ["Der Dachs", "Der Marder", "Der Otte", "Der Waschbär"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Waschbären ertasten ihr Futter im Wasser, was wie Waschen aussieht."
    },
    {
        id: "k_tn_089",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welche Frühjahrsblume hat gelbe Glockenblüten und heißt wie ein Fest?",
        answers: ["Die Osterglocke", "Die Tulpe", "Das Schneeglöckchen", "Die Lilie"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Osterglocken (Gelbe Narzissen) blühen rund um die Osterzeit."
    },
    {
        id: "k_tn_090",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher graue Verwandte des Pferdes hat lange Ohren und macht 'I-A'?",
        answers: ["Das Zebra", "Der Esel", "Das Ponny", "Das Muli"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Esel sind ausdauernde Tragtiere mit charakteristischem Rufen."
    },
    {
        id: "k_tn_091",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher große Raubfisch lebt im Meer und erneuert abgebrochene Zähne?",
        answers: ["Der Karpfen", "Der Hering", "Der Hai", "Der Kabeljau"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Haie besitzen ein Revolvergebiss, bei dem Zähne ständig nachrücken."
    },
    {
        id: "k_tn_092",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Reptil hat ein riesiges Gebiss und lebt im Flussufer Afrikas?",
        answers: ["Die Eidechse", "Die Leguan", "Die Schildkröte", "Das Krokodil"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Krokodile sind Panzerechsen, die im Wasser auf Beute lauern."
    },
    {
        id: "k_tn_093",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt schlüpft aus einer Puppe und hat vier bunte Flügel?",
        answers: ["Der Schmetterling", "Die Libelle", "Der Käfer", "Die Fliege"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Verwandlung von der Raupe zum Schmetterling nennt man Metamorphose."
    },
    {
        id: "k_tn_094",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Singvogel legt seine Eier in fremde Nester legen?",
        answers: ["Die Drossel", "Der Kuckuck", "Der Fink", "Der Star"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Kuckucke lassen ihre Jungen von fremden Zieheltern aufziehen."
    },
    {
        id: "k_tn_095",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches flinke Raubtier jagt Mäuse auf den Feldern und hat braunes Fell?",
        answers: ["Der Dachs", "Der Biber", "Der Rotfuchs", "Der Fischotter"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Füchse springen mit dem 'Mäusesprung' zielsicher auf Beute."
    },
    {
        id: "k_tn_096",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Meeres-Säuger stößt durch ein Loch auf dem Rücken Luft aus?",
        answers: ["Der Hai", "Der Thunfisch", "Der Rochen", "Der Wal"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Wale atmen an der Wasseroberfläche durch ihr Blasloch aus."
    },
    {
        id: "k_tn_097",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welcher Insekt Jäger fliegt wie ein Hubschrauber über Teiche?",
        answers: ["Die Libelle", "Die Biene", "Die Mücke", "Der Käfer"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Libellen können ihre Flügel unabhängig bewegen und rückwärts fliegen."
    },
    {
        id: "k_tn_098",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Säugetier hat ein Horn auf der Nase und dicke Haut?",
        answers: ["Der Elefant", "Das Nashorn", "Das Flusspferd", "Der Büffel"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Horn des Nashorns besteht aus festem Keratin."
    },
    {
        id: "k_tn_099",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches Krebstier wandert im Frühling in großen Mengen zum Laichen ans Meer?",
        answers: ["Die Garnele", "Der Hummer", "Die Krabbe", "Der Seestern"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Landrappen wandern zur Eiablage ans Meeresufer."
    },
    {
        id: "k_tn_100",
        category: "kinder_tiere_natur",
        area: "spass",
        subject: "kinder",
        question: "Welches weiche Moosgewächs wächst dicht auf schattigen Waldböden?",
        answers: ["Das Gras", "Der Farn", "Das Fleischkraut", "Das Moos"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Moose bilden grüne, weiche Teppiche im Wald."
    }
];

if (typeof window !== 'undefined') {
    window.QUESTIONS_KINDER_TIERE_NATUR = QUESTIONS_KINDER_TIERE_NATUR;
}