// Fun · kinder_maerchen.js
const KINDER_MAERCHEN_QUESTIONS = [
  {
        id: "k_dis_001",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was bringt Rotkäppchen der kranken Großmutter im Wald?",
        answers: ["Kuchen und Wein", "Brot und Wasser", "Kekse und Saft", "Obst und Milch"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Rotkäppchen bringt Kuchen und Wein im Korb zur Großmutter."
    },
  {
        id: "k_dis_002",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Zwerge wohnen zusammen im Haus im Wald?",
        answers: ["Fünf Zwerge", "Sieben Zwerge", "Neun Zwerge", "Zehn Zwerge"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Schneewittchen wohnt bei den sieben Zwergen hinter den sieben Bergen."
    },
  {
        id: "k_dis_003",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die Schwester von Eiskönigin Elsa im Film?",
        answers: ["Rapunzel", "Cinderella", "Prinzessin Anna", "Arielle"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Anna ist die jüngere Schwester von Elsa im Königreich Arendelle."
    },
  {
        id: "k_dis_004",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Erdmännchen ist der beste Freund von Pumbaa?",
        answers: ["Kater Simba", "Vogel Zazu", "Affe Rafiki", "Erdmännchen Timon"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Timon und Pumbaa bilden das fröhliche Duo im König der Löwen."
    },
  {
        id: "k_dis_005",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was verliert Aschenputtel auf der Treppe des Schlosses?",
        answers: ["Einen Schuh", "Einen Ring", "Eine Krone", "Ein Tuch"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Aschenputtel verliert um Mitternacht ihren feinen Schuh."
    },
  {
        id: "k_dis_006",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches magische Wesen erfüllt Aladdin genau drei Wünsche?",
        answers: ["Ein Zauberer", "Der Dschinn", "Ein Drache", "Ein Geist"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Dschinn kommt aus der Wunderlampe und erfüllt Aladdin drei Wünsche."
    },
  {
        id: "k_dis_007",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Fischart ist der kleine Fisch Nemo im Film?",
        answers: ["Ein Goldfisch", "Ein Haifisch", "Ein Clownfisch", "Ein Kugelfisch"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Nemo ist ein orange-weiß gestreifter Clownfisch."
    },
  {
        id: "k_dis_008",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was ist das besondere Merkmal von Prinzessin Rapunzel?",
        answers: ["Ihre rote Nase", "Ihr rotes Kleid", "Ihre Zauberwand", "Ihr langes Haar"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Rapunzel hat wunderschönes, langes magisches Haar."
    },
  {
        id: "k_dis_009",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das berühmte rote Rennauto im Film Cars?",
        answers: ["Lightning McQueen", "Cruz Ramirez", "Jackson Storm", "Doc Hudson"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Lightning McQueen ist die rote Startnummer 95."
    },
  {
        id: "k_dis_010",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wohin fliegt Peter Pan gemeinsam mit den Kindern?",
        answers: ["Ins Zauberland", "Ins Nimmerland", "Ins Traumland", "Ins Wunderland"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Peter Pan bringt Wendy und ihre Brüder ins Nimmerland."
    },
  {
        id: "k_dis_011",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche magische Blume steht im Schloss des Biests?",
        answers: ["Eine Lilie", "Eine Tulpe", "Eine Rose", "Eine Nelke"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die verzauberte Rose verliert langsam ihre Blütenblätter."
    },
  {
        id: "k_dis_012",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Woraus besteht das Häuschen der bösen Hexe im Wald?",
        answers: ["Aus Treibholz", "Aus Flussstein", "Aus trockenem Stroh", "Aus Knusper-Lebkuchen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Hänsel und Gretel finden das Hexenhaus aus Knusper-Lebkuchen."
    },
  {
        id: "k_dis_013",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist der gemütliche Balu im Dschungelbuch?",
        answers: ["Ein Bär", "Ein Tiger", "Ein Panther", "Ein Wolf"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Balu der Bär singt das Lied von den 'Probier's mal mit Gemütlichkeit'."
    },
  {
        id: "k_dis_014",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer ist die beste Freundin von Mickey Maus?",
        answers: ["Daisy Duck", "Minnie Maus", "Klara Kuh", "Madam Mim"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Minnie Maus trägt meist eine Schleife und gehört fest zu Mickey."
    },
  {
        id: "k_dis_015",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der mutige Spielzeug-Cowboy aus Toy Story?",
        answers: ["Buzz Lightyear", "Slinky Dog", "Woody", "Rex"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Sheriff Woody ist der Spielzeug-Cowboy von Andy."
    },
  {
        id: "k_dis_016",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was passiert mit Pinocchios Nase, wenn er lügt?",
        answers: ["Sie wird kleiner", "Sie wird rot", "Sie wird dick", "Sie wird länger"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Wenn die Holzpuppe Pinocchio lügt, wächst seine Nase."
    },
  {
        id: "k_dis_017",
        category: "kinder_maerchen_disney",
        subject: "kinder",
        question: "Welche Tiermaske trägt der Held Miraculous Cat Noir?",
        answers: ["Eine Katzenmaske", "Eine Hundemaske", "Eine Bärenmaske", "Eine Eulenmaske"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Cat Noir verwandelt sich mithilfe von Plagg in einen schwarzen Kater."
    },
  {
        id: "k_dis_018",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier träumt im Film Ratatouille vom Kochen?",
        answers: ["Eine Hamsterdame", "Eine Hausratte", "Eine Rennmaus", "Ein Eichhörnchen"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Ratte Remy kocht heimlich in einem Gourmet-Restaurant."
    },
  {
        id: "k_dis_019",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was fällt der Königstochter im Märchen in den Brunnen?",
        answers: ["Ein Silberring", "Ein Goldkrönchen", "Eine Goldkugel", "Eine Glasperle"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die goldene Kugel fällt der Prinzessin ins tiefe Brunnenwasser."
    },
  {
        id: "k_dis_020",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist der bekannte Hirschjunge Bambi?",
        answers: ["Ein Elch", "Ein Rentier", "Ein Wildschwein", "Ein Rehkitz"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Bambi wächst als junges Rehkitz im Wald auf."
    },
  {
        id: "k_dis_021",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Womit lässt Opa Carl sein Haus im Film Oben fliegen?",
        answers: ["Mit Luftballons", "Mit Hubschraubern", "Mit Drachenseilen", "Mit Raketen-Düsen"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Tausende bunte Luftballons heben das kleine Haus in den Himmel."
    },
  {
        id: "k_dis_022",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat das lange Haar der Meerjungfrau Arielle?",
        answers: ["Blond", "Feuerrot", "Schwarz", "Braun"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Arielle hat auffallendes leuchtend rotes Haar."
    },
  {
        id: "k_dis_023",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier versucht die Häuser der drei Schweinchen umzupusten?",
        answers: ["Der Luchs", "Der Bär", "Der Wolf", "Der Tiger"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der böse Wolf pustet an den Häusern aus Stroh und Holz."
    },
  {
        id: "k_dis_024",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was isst der niedliche Bär Winnie Puuh am liebsten?",
        answers: ["Käsebrot", "Apfelmus", "Schokolade", "Blütenhonig"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Winnie Puuh hat immer großen Appetit auf frischen Honig."
    },
  {
        id: "k_dis_025",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der Schneemann, der den Sommer liebt?",
        answers: ["Schneemann Olaf", "Schneemann Frost", "Schneemann Sven", "Schneemann Nils"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Olaf der Schneemann träumt von warmer Sonne und Sommer."
    },
  {
        id: "k_dis_026",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Fabeltier ist Baymax aus dem Film Bajmax – Riesiges Robowabohu?",
        answers: ["Ein Drache", "Ein Pflegeroboter", "Ein Zauberer", "Ein Kuschelbär"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Baymax ist ein aufblasbarer Gesundheitsroboter."
    },
  {
        id: "k_dis_027",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer verliert ihren gläsernen Schuh auf dem Schlossball?",
        answers: ["Dornröschen", "Schneewittchen", "Cinderella", "Rapunzel"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Cinderella (Aschenputtel) verliert den gläsernen Schuh."
    },
  {
        id: "k_dis_028",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was verzaubert die böse Fee bei Dornröschen?",
        answers: ["Ein Apfel", "Ein Spiegel", "Ein Kamintop", "Eine Spindel"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Dornröschen sticht sich an der Spindel eines Spinnrads."
    },
  {
        id: "k_dis_029",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der schlaue Drache und Gefährte von Mulan?",
        answers: ["Mushu", "Sisu", "Elliott", "Toothless"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Der kleine rote Drache Mushu beschützt Mulan."
    },
  {
        id: "k_dis_030",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Auf welchem Fluggerät reisen Aladdin und Jasmin durch die Nacht?",
        answers: ["Auf einem Besen", "Auf einem Teppich", "Auf einem Drachen", "Auf einer Wolke"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Sie fliegen auf dem magischen fliegenden Teppich."
    },
  {
        id: "k_dis_031",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die kleinen Wesen aus Ich – Einfach unverbesserlich?",
        answers: ["Die Schlümpfe", "Die Gremlins", "Die Minions", "Die Ewoks"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die gelben Minions tragen Latzhosen und helfen Gru."
    },
  {
        id: "k_dis_032",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer schläft im Märchen genau einhundert Jahre lang?",
        answers: ["Schneewittchen", "Aschenputtel", "Rapunzel", "Dornröschen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Dornröschen fällt zusammen mit dem ganzen Schloss in Tiefschlaf."
    },
  {
        id: "k_dis_033",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier führt Alice im Wunderland in den Kaninchenbau?",
        answers: ["Ein weißes Kaninchen", "Eine weiße Taube", "Ein brauner Bär", "Ein roter Fuchs"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Das weiße Kaninchen mit der Taschenuhr läuft voraus."
    },
  {
        id: "k_dis_034",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das freundliche Gespenst aus den bekannten Kinderfilmen?",
        answers: ["Hui Buh", "Casper", "Slimer", "Labrador"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Casper ist als das kleine freundliche Gespenst bekannt."
    },
  {
        id: "k_dis_035",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was trägt die Schildkröte Meister Oogway in Kung Fu Panda?",
        answers: ["Einen Helm", "Einen Schild", "Einen Gehstock", "Eine Krone"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Meister Oogway stützt sich auf seinen Holzgehstock."
    },
  {
        id: "k_dis_036",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer legt im Märchen goldene Eier?",
        answers: ["Die Ente", "Die Taube", "Die Wachtel", "Die Gans"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Die goldene Gans ist ein bekanntes Märchenmotiv."
    },
  {
        id: "k_dis_037",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat das Fell des bekannten Bären Paddington?",
        answers: ["Braunes Fell", "Schwarzes Fell", "Weißes Fell", "Graues Fell"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Paddington Bär hat braunes Fell und trägt einen blauen Dufflecoat."
    },
  {
        id: "k_dis_038",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer wohnt in einer Ananas ganz tief unten im Meer?",
        answers: ["Patrick Star", "SpongeBob Schwammkopf", "Thaddäus Tentakel", "Mr. Krabs"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "SpongeBob Schwammkopf wohnt in der gelben Ananas in Bikini Bottom."
    },
  {
        id: "k_dis_039",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heilt Rapunzel Wunden im Film Verwickelt?",
        answers: ["Mit Zaubersalz", "Mit Kräutertee", "Durch ihren Gesang", "Mit Handauflegen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Wenn Rapunzel singt, fängt ihr Haar an zu leuchten und heilt Wunden."
    },
  {
        id: "k_dis_040",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Zauberwort öffnet im Märchen die Höhle der 40 Räuber?",
        answers: ["Hokus Pokus", "Abrakadabra", "Simsalabim", "Sesam öffne dich"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Mit 'Sesam, öffne dich!' öffnet sich das Felsentor."
    },
  {
        id: "k_dis_041",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das Haustier-Chamäleon von Rapunzel im Film?",
        answers: ["Pascal", "Maximus", "Sven", "Flounder"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Pascal das kleine grüne Chamäleon ist Rapunzels treuer Freund."
    },
  {
        id: "k_dis_042",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel liefert dem Löwenkönig Mufasa tägliche Berichte?",
        answers: ["Papagei Iago", "Nashornvogel Zazu", "Eule Bagheera", "Kranich Kai"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Zazu der Rotschnabeltokko ist der Hausminister des Königs."
    },
  {
        id: "k_dis_043",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Rentier gehört treu zum Bergmann Kristoff?",
        answers: ["Olaf", "Pumbaa", "Sven", "Maximus"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Sven ist das treue Rentier an Kristoffs Seite."
    },
  {
        id: "k_dis_044",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die kleine Elfe und Begleiterin von Peter Pan?",
        answers: ["Flora", "Fauna", "Sonnenschein", "Tinkerbell"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Tinkerbell hinterlässt feinen Fee-Feenstaub beim Fliegen."
    },
  {
        id: "k_dis_045",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Fisch begleitet Arielle stets treu im Meer?",
        answers: ["Fabius", "Sebastian", "Scuttle", "Nemo"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Fabius ist der gelb-blaue kleine Fischfreund von Arielle."
    },
  {
        id: "k_dis_046",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer befreit den gestiefelten Kater aus misslichen Lagen?",
        answers: ["Ein Zauberer", "Er sich selbst", "Ein Müllerssohn", "Ein König"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der gestiefelte Kater hilft mit Schlauheit dem armen Müllerssohn."
    },
  {
        id: "k_dis_047",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was für ein Tier ist der rote Feuerkrebs Sebastian?",
        answers: ["Ein Hummer", "Ein Seestern", "Ein Krabbenkrebs", "Ein Seeigel"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Sebastian ist ein Krabbenkrebs und Hofmusiker des Königs."
    },
  {
        id: "k_dis_048",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer wacht im Märchen über den Brunnen mit den Broten und Äpfeln?",
        answers: ["Schneewittchen", "Aschenputtel", "Dornröschen", "Frau Holle"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Frau Holle lässt es auf der Erde schneien, wenn sie ihre Betten schüttelt."
    },
  {
        id: "k_dis_049",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der neugierige Roboter, der die Erde aufräumt?",
        answers: ["WALL-E", "EVE", "Baymax", "R2-D2"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "WALL-E sammelt Müll und entdeckt eine kleine grüne Pflanze."
    },
  {
        id: "k_dis_050",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Prinz weckt Schneewittchen aus dem Schlaf?",
        answers: ["Prinz Eric", "Prinz Florian", "Prinz Philip", "Prinz Hans"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Prinz Florian löst mit der Liebe den Zauberschlaf."
    },
  {
        id: "k_dis_051",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer verwandelt sich im Märchen durch einen Kuss wieder zurück?",
        answers: ["Ein Kater", "Ein Bär", "Der Froschkönig", "Ein Wolf"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Frosch verwandelt sich durch das Versprechen der Königstochter in einen Prinzen."
    },
  {
        id: "k_dis_052",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das blaue Außerirdische-Wesen bei Lilo & Stitch?",
        answers: ["Gantu", "Jumba", "Pleakley", "Stitch"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Experiment 626 nennt sich Stitch und wird Lilos bester Freund."
    },
  {
        id: "k_dis_053",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Hexe verlangt Arielles Stimme im Tausch gegen Beine?",
        answers: ["Meerhexe Ursula", "Hexe Maleficent", "Die böse Königin", "Hexe Gothel"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Ursula fordert Arielles schöne Stimme für den Zaubertrank."
    },
  {
        id: "k_dis_054",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer verfütterte die Hand von Käpt'n Hook an das Krokodil?",
        answers: ["Wendy", "Peter Pan", "Tinkerbell", "Smee"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Peter Pan schlug Hooks Hand ab, die das Krokodil verschlang."
    },
  {
        id: "k_dis_055",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was sammelt die kleine Meerjungfrau Arielle in ihrer Höhle?",
        answers: ["Fische", "Muscheln", "Menschliche Sachen", "Perlen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Arielle sammelt voller Neugier Gegenstände aus der Menschenwelt."
    },
  {
        id: "k_dis_056",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier zieht das Kutschen-Gespann von Aschenputtel?",
        answers: ["Weiße Tauben", "Graue Mäuse", "Kleine Hunde", "Weiße Schimmel"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Die gute Fee verwandelt weiße Mäuse in edle Schimmel-Pferde."
    },
  {
        id: "k_dis_057",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt zeigt Pinocchio, was richtig und falsch ist?",
        answers: ["Grille Jiminy", "Biene Maja", "Marienkäfer", "Ameise Fred"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Jiminy Grille dient Pinocchio als sein treues Gewissen."
    },
  {
        id: "k_dis_058",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was schenkt die Fee der Prinzessin Vaiana auf dem Ozean?",
        answers: ["Ein Segelboot", "Das Herz von Te Fiti", "Eine Zauberkette", "Einen Kompass"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Ozean wählt Vaiana aus, um das Herz von Te Fiti zurückzugeben."
    },
  {
        id: "k_dis_059",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel warnt Mufasa im König der Löwen vor den Hyänen?",
        answers: ["Papagei Iago", "Eule Archimedes", "Nashornvogel Zazu", "Kranich Kevin"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Zazu behält das Königreich von oben immer im Blick."
    },
  {
        id: "k_dis_060",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer wohnt zusammen mit den Bremer Stadtmusikanten im Haus?",
        answers: ["Keine Menschen", "Die Waldfeen", "Ein alter Bauer", "Die Räuber"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Vier Tiere vertreiben die Räuber aus dem Waldhaus."
    },
  {
        id: "k_dis_061",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat der Umhang des Schneewittchens im klassischen Disney-Film?",
        answers: ["Rot und Gelb", "Blau und Gelb", "Grün und Weiß", "Lila und Rot"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Schneewittchen trägt ein Kleid mit gelbem Rock und rotem Umhang."
    },
  {
        id: "k_dis_062",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Gegenstand verrät der bösen Königin, wer die Schönste ist?",
        answers: ["Ein Zauberstab", "Der Zauberspiegel", "Ein Buch", "Ein Kristallglas"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der magische Wandspiegel antwortet der Königin stets wahrheitsgemäß."
    },
  {
        id: "k_dis_063",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der große Schneeroboter, den Elsa zum Schutz baut?",
        answers: ["Eisriese Goliath", "Schneemann Olaf", "Schnee-Ungeheuer Marshmallow", "Frostie Bär"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Marshmallow beschützt den Eispalast von Elsa."
    },
  {
        id: "k_dis_064",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der treue Pferdefreund von Flynn Rider in Rapunzel?",
        answers: ["Pferd Sven", "Pferd Angus", "Pferd Samson", "Pferd Maximus"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Palastpferd Maximus jagt zuerst Flynn und wird dann sein Freund."
    },
  {
        id: "k_dis_065",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was muss Prinzessin Tiana im Film Küss den Frosch küssen?",
        answers: ["Einen grünen Frosch", "Einen Krötenkönig", "Einen Zauberfisch", "Einen Wassermann"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Tiana küsst Frosch Naveen und verwandelt sich selbst kurz in einen Frosch."
    },
  {
        id: "k_dis_066",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die bekannten Zwillinge im Film Die Eiskönigin 2 nicht?",
        answers: ["Anna und Elsa", "Sven und Olaf", "Kristoff und Hans", "Mickey und Donald"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Mickey und Donald gehören zur Micky-Maus-Welt."
    },
  {
        id: "k_dis_067",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Aus welchem Holz wurde Pinocchio von seinem Vater geschnitzt?",
        answers: ["Eichenholz", "Pinienholz", "Kiefernholz", "Buchenholz"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Holzschnitzer Gepetto fertigt die Puppe aus Pinienholz."
    },
  {
        id: "k_dis_068",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Figur schläft in einer Walnussschale im gleichnamigen Märchen?",
        answers: ["Aschenputtel", "Dornröschen", "Däumelinchen", "Rapunzel"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Däumelinchen ist so winzig klein wie ein Daumen."
    },
  {
        id: "k_dis_069",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer baute das erste Haus im Märchen Die drei Schweinchen?",
        answers: ["Das zweite Schwein", "Das jüngste Schwein", "Das älteste Schwein", "Das klügste Schwein"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das erste faule Schweinchen baut sein Haus schnell aus Stroh."
    },
  {
        id: "k_dis_070",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist der Bösewicht Shere Khan im Dschungelbuch?",
        answers: ["Ein Schlange", "Ein Königstiger", "Ein Bär", "Ein Panther"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Shere Khan ist der gefürchtete Tiger im Dschungel."
    },
  {
        id: "k_dis_071",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der neugierige kleine Drache im Film Elliott, das Schmunzelmonster?",
        answers: ["Mushu", "Sisu", "Elliott", "Fuchur"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Elliott ist der liebe grüne, unsichtbare Drache."
    },
  {
        id: "k_dis_072",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Frucht bekommt Schneewittchen von der verkleideten Hexe?",
        answers: ["Eine Birne", "Eine Pflaume", "Eine Kirsche", "Einen Apfel"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Schneewittchen beißt in die vergiftete rote Hälfte des Apfels."
    },
  {
        id: "k_dis_073",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die Hauptfigur im Film Merida – Legende der Highlands?",
        answers: ["Prinzessin Merida", "Prinzessin Rapunzel", "Prinzessin Moana", "Prinzessin Belle"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Merida ist die geschickte Bogenschützin aus Schottland."
    },
  {
        id: "k_dis_074",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was vergisst die vergessliche Fischdame Dorie dauernd?",
        answers: ["Ihren Namen", "Alles nach kurzer Zeit", "Das Schwimmen", "Wo sie wohnt"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Dorie leidet unter verlässlichem Kurzzeitgedächtnisschwund."
    },
  {
        id: "k_dis_075",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der sprechende Halbgott im Disney-Film Vaiana?",
        answers: ["Maui", "Hercules", "Zeus", "Tarzan"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Maui besitzt einen Zauberhaken und hilft Vaiana."
    },
  {
        id: "k_dis_076",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Haustier besitzt der Bösewicht Jafar in Aladdin?",
        answers: ["Einen Affen", "Einen Hund", "Einen Papageien", "Einen Kater"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Iago ist der gemeine rote Papagei von Jafar."
    },
  {
        id: "k_dis_077",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Aus welchem Land stammt das Märchen von der Schneekönigin ursprünglich?",
        answers: ["Deutschland", "Frankreich", "Dänemark", "Russland"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Hans Christian Andersen aus Dänemark verfasste das Original-Märchen."
    },
  {
        id: "k_dis_078",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das Schneemonster, das den Palast in Die Eiskönigin bewacht?",
        answers: ["Goliath", "Yeti", "Eisklotz", "Marshmallow"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Marshmallow verteidigt den Eispalast auf dem Nordberg."
    },
  {
        id: "k_dis_079",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die Bremer Stadtmusikanten allesamt?",
        answers: ["Esel, Hund, Katze, Hahn", "Pferd, Hund, Katze, Huhn", "Esel, Wolf, Kater, Hahn", "Kuh, Hund, Katze, Vogel"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die vier Tiere wandern gemeinsam nach Bremen."
    },
  {
        id: "k_dis_080",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Fee zieht Maleficent im Realfilm auf?",
        answers: ["Die Waldfee", "Die Dunkelelfin Maleficent", "Die feine Feenkönigin", "Die gute Waldfee"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Maleficent schützt die Moore und kümmert sich um Aurora."
    },
  {
        id: "k_dis_081",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Meereswesen leitet die Unterwasser-Musik in Arielle?",
        answers: ["Krabbe Sebastian", "Fisch Fabius", "König Triton", "Hai Wassermann"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Sebastian komponiert die Unterwasser-Symphonien."
    },
  {
        id: "k_dis_082",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Gegenstand lässt der Teufel mit den drei goldenen Haaren suchen?",
        answers: ["Die Wünsche", "Die drei Haare", "Das Zauberschwert", "Das Krönchen"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Glückskind-Junge muss dem Teufel drei goldene Haare stehlen."
    },
  {
        id: "k_dis_083",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer liefert die Geschenke im Disney-Klassiker Night Before Christmas?",
        answers: ["Der Weihnachtsmann", "Der Osterhase", "Jack Skellington", "Der Sandmann"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Jack Skellington übernimmt versehentlich das Weihnachtsfest."
    },
  {
        id: "k_dis_084",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die zwei Mäusefreunde von Aschenputtel?",
        answers: ["Mickey und Minnie", "Chip und Chap", "Bernard und Bianca", "Jaq und Gus"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Jaq und Gus nähen und helfen Aschenputtel fleißig."
    },
  {
        id: "k_dis_085",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist der Panther Bagheera im Dschungelbuch?",
        answers: ["Ein schwarzer Panther", "Ein gepunkteter Leopard", "Ein Wüstenluchs", "Ein wilder Tiger"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Bagheera beschützt Mogli von klein auf im Dschungel."
    },
  {
        id: "k_dis_086",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das kleine Meerschweinchen aus Die Sorgenfresser?",
        answers: ["Muffel", "Flitzi", "Plüsch", "Sorgenfresser"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Flitzi hilft den Kindern durch den Schulalltag."
    },
  {
        id: "k_dis_087",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Was verwandelt sich im Märchen vom Aschenputtel in eine Kutsche?",
        answers: ["Ein großer Apfel", "Ein gelber Kürbis", "Eine Melone", "Ein großer Stein"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Die gute Fee verzaubert den Kürbis in eine prunkvolle Kutsche."
    },
  {
        id: "k_dis_088",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Insekt sammelt fleißig Vorräte für den kalten Winter?",
        answers: ["Die Heuschrecke", "Der Grashüpfer", "Die Fleißige Ameise", "Die Schmetterlinge"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Ameise arbeitet den Sommer durch, während der Grashüpfer musiziert."
    },
  {
        id: "k_dis_089",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heit der kleine Holzwurm im Disney-Film Die Hexe und der Zauberer?",
        answers: ["Wurm Archimedes", "Wurm Merlin", "Eule Archimedes", "Kater Lucifer"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Archimedes ist Merlins gelehrte und leicht grummelige Eule."
    },
  {
        id: "k_dis_090",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die zwei Chipmunks Streifenhörnchen bei Disney?",
        answers: ["Mickey und Donald", "Timon und Pumbaa", "Bernard und Bianca", "Chip und Chap"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Chip und Chap sind die beiden frechen Streifenhörnchen."
    },
  {
        id: "k_dis_091",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Bärenjunge wächst bei den Wölfen im Dschungel auf?",
        answers: ["Das Menschenkind Mogli", "Balu der Bär", "Bambi das Kitz", "Tarzan das Baby"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Mogli wird von der Wölfin Raksha wie ihr eigenes Junges aufgezogen."
    },
  {
        id: "k_dis_092",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die drei kleinen Drachen aus Drachenzähmen leicht gemacht?",
        answers: ["Schatten, Licht, Glut", "Ohnezahn, Tagschatten, Sturmpfeil", "Nacht, Feuer, Sturm", "Drago, Hicks, Astrid"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Ohnezahn ist der berühmte Nachtschatten-Drache."
    },
  {
        id: "k_dis_093",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welcher Vogel führt die Enten im Film In einem Land vor unserer Zeit an?",
        answers: ["Saurier Cera", "Flugsaurier Petrie", "Saurier Littlefoot", "Saurier Ducky"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Petrie ist der kleine ängstliche Flugsaurier."
    },
  {
        id: "k_dis_094",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Aus welcher Stadt kommen die Helden von Baymax?",
        answers: ["New York", "San Francisco", "San Fransokyo", "Tokio City"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Handlung spielt in der erfundenen Stadt San Fransokyo."
    },
  {
        id: "k_dis_095",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer singt das berühmte Lied 'Unter dem Meer' in Arielle?",
        answers: ["Prinz Eric", "König Triton", "Fabius der Fisch", "Krabbe Sebastian"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Sebastian versucht Arielle vom Leben im Ozean zu überzeugen."
    },
  {
        id: "k_dis_096",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier rettet Tarzan als Baby im afrikanischen Dschungel?",
        answers: ["Gorilla-Mutter Kala", "Affen-Vater Kerchak", "Leopard Sabor", "Elefanten-Kuh Tantor"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Kala nimmt das verwaiste Menschenbaby liebevoll bei sich auf."
    },
  {
        id: "k_dis_097",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der schnellste Flieger unter den Fee-Feen im Tal der Feen?",
        answers: ["Fee Rosetta", "Fee Vidia", "Fee Tinkerbell", "Fee Klara"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Vidia ist die schnelle Frühlingsfeen-Rivalin."
    },
  {
        id: "k_dis_098",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der Panda-Bär im Animationsfilm Kung Fu Panda?",
        answers: ["Meister Shifu", "Meister Tai Lung", "Panda Po", "Panda Mei"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Po verwandelt sich vom Nudelkoch zum Drachenkrieger."
    },
  {
        id: "k_dis_099",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welche Blumenart pflückt das Rumpelstilzchen im Wald?",
        answers: ["Gänseblümchen", "Waldbeeren", "Grasfaser", "Stroh zu Gold"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Rumpelstilzchen spinnt für die Müllerstochter Stroh zu reinem Gold."
    },
  {
        id: "k_dis_100",
        category: "kinder_maerchen_disney",
        area: "spass",
        subject: "kinder",
        question: "Welches Zauberwort sagt die Feenmutter in Cinderella?",
        answers: ["Bibbidi Babbidi Boo", "Simsalabim Hokus Pokus", "Abrakadabra Hokuspokus", "Sesam öffne dich"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Mit 'Bibbidi Babbidi Boo' verwandelt die Fee die Kleidung und den Kürbis."
    }
];

if (typeof window !== "undefined") window.KINDER_MAERCHEN_QUESTIONS = KINDER_MAERCHEN_QUESTIONS;
