 const QUESTIONS_KINDER_ERSTES_WISSEN = [
    // 001
    {
        id: "k_ew_001",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was bedeutet die rote Farbe bei einer Fußgängerampel?",
        answers: ["Stehen bleiben", "Schnell rennen", "Langsam gehen", "Weiter fahren"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Rot heißt Stopp: Man muss am Bordstein warten."
    },
    {
        id: "k_ew_002",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Tage hat eine vollständige Woche?",
        answers: ["Fünf Tage", "Sieben Tage", "Zehn Tage", "Zwölf Tage"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Eine Woche besteht aus Montag bis Sonntag."
    },
    {
        id: "k_ew_003",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was zeigt der kurze Zeiger auf einer Wanduhr an?",
        answers: ["Die Sekunden", "Die Minuten", "Die Stunden", "Die Tage"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der kurze Zeiger wandert langsam von Stunde zu Stunde."
    },
    {
        id: "k_ew_004",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "In welcher Jahreszeit blühen die ersten Blumen im Garten?",
        answers: ["Im Sommer", "Im Herbst", "Im Winter", "Im Frühling"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Frühling erwacht die Natur nach dem Winter."
    },
    {
        id: "k_ew_005",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Finger hat ein Mensch an einer Hand?",
        answers: ["Fünf Finger", "Sechs Finger", "Vier Finger", "Zehn Finger"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "An einer Hand befinden sich normalerweise fünf Finger."
    },
    {
        id: "k_ew_006",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Woraus werden Schulhefte und Bücher hergestellt?",
        answers: ["Aus Plastik", "Aus Papier", "Aus Metall", "Aus Gummi"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Papier wird aus Holzfasern hergestellt."
    },
    {
        id: "k_ew_007",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit misst man die Temperatur bei Fieber?",
        answers: ["Lineal", "Waage", "Thermometer", "Stoppuhr"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Thermometer zeigt die Körperwärme in Grad an."
    },
    {
        id: "k_ew_008",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Sinnesorgan nutzen wir zum Hören von Musik?",
        answers: ["Die Augen", "Die Nase", "Die Zunge", "Die Ohren"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Mit den Ohren nehmen wir Schallwellen wahr."
    },
    {
        id: "k_ew_009",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was entsteht am Himmel, wenn Sonne und Regen gleichzeitig vorkommen?",
        answers: ["Ein Regenbogen", "Ein Gewitter", "Ein Schneefall", "Ein Sturmwind"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Sonnenlicht bricht sich in den Regentropfen zu bunten Farben."
    },
    {
        id: "k_ew_010",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die Flüssigkeit, die im Körper durch Adern fließt?",
        answers: ["Wasser", "Blut", "Speichel", "Tränen"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Blut transportiert Sauerstoff durch den Körper."
    },
    {
        id: "k_ew_011",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Himmelsrichtung liegt der aufgehenden Sonne gegenüber?",
        answers: ["Der Norden", "Der Osten", "Der Westen", "Der Süden"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Sonne geht im Osten auf und geht im Westen unter."
    },
    {
        id: "k_ew_012",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was schützt den Kopf beim Fahrradfahren vor Verletzungen?",
        answers: ["Mütze", "Kappe", "Helm", "Hut"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein geprüfter Fahrradhelm fängt Stürze sicher ab."
    },
    {
        id: "k_ew_013",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie nennt man gefrorenes Wasser in fester Form?",
        answers: ["Eis", "Dampf", "Nebel", "Regen"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Unterschreitet Wasser 0 °C, gefriert es zu Eis."
    },
    {
        id: "k_ew_014",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Monate hat ein Kalenderjahr insgesamt?",
        answers: ["Zehn Monate", "Zwölf Monate", "Fünf Monate", "Acht Monate"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Von Januar bis Dezember vergehen zwölf Monate."
    },
    {
        id: "k_ew_015",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wo sollte man den Müll unterwegs hineinwerfen?",
        answers: ["Auf die Wiese", "In den Fluss", "In den Mülleimer", "Auf den Gehweg"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Abfall gehört in den Mülleimer zur sauberen Entsorgung."
    },
    {
        id: "k_ew_016",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Buchstabe steht an erster Stelle im Alphabet?",
        answers: ["Buchstabe B", "Buchstabe C", "Buchstabe Z", "Buchstabe A"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Alphabet beginnt mit dem Buchstaben A."
    },
    {
        id: "k_ew_017",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Körperteil schlägt ununterbrochen in unserer Brust?",
        answers: ["Das Herz", "Die Lunge", "Der Magen", "Die Leber"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Herz pumpt pausenlos Blut durch den Körper."
    },
    {
        id: "k_ew_018",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat eine reife Zitrone in der Schale?",
        answers: ["Grün", "Gelb", "Rot", "Blau"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Reife Zitronen erkennst du an ihrer gelben Farbe."
    },
    {
        id: "k_ew_019",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was sollten Kinder morgens und abends gründlich putzen?",
        answers: ["Schuhe", "Haare", "Zähne", "Hände"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Zähneputzen schützt vor Karies und hält gesund."
    },
    {
        id: "k_ew_020",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Gegenstand hilft beim Ziehen von geraden Linien?",
        answers: ["Zirkel", "Pinsel", "Gummi", "Lineal"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Mit dem Lineal zieht man exakt gerade Striche."
    },

    // 021 - 040
    {
        id: "k_ew_021",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der Stern, der tagsüber Licht und Wärme spendet?",
        answers: ["Die Sonne", "Der Mond", "Der Mars", "Der Jupiter"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Sonne ist das Zentrum unseres Sonnensystems."
    },
    {
        id: "k_ew_022",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Aus welcher Wolkenart fällt im kalten Winter weißer Schnee?",
        answers: ["Nebelwolke", "Schneewolke", "Rauchwolke", "Staubwolke"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Bei Kälte kristallisieren Regentropfen zu Schneeflocken."
    },
    {
        id: "k_ew_023",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was nutzen wir in der Schule zum Radieren von Bleistift?",
        answers: ["Schere", "Kleber", "Radiergummi", "Spitzer"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Radiergummi entfernt Graphitspuren auf Papier."
    },
    {
        id: "k_ew_024",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Himmelsrichtung zeigt der Kompass nach oben an?",
        answers: ["Süden", "Osten", "Westen", "Norden"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Magnetnadel zeigt immer Richtung Norden."
    },
    {
        id: "k_ew_025",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Beine hat ein gesunder Mensch üblicherweise?",
        answers: ["Zwei Beine", "Vier Beine", "Drei Beine", "Sechs Beine"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Mensch gehört zu den zweibeinigen Lebewesen."
    },
    {
        id: "k_ew_026",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was ziehen wir an den Füßen an, bevor wir Schuhe anziehen?",
        answers: ["Handschuhe", "Socken", "Mützen", "Gürtel"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Socken halten die Füße warm und schützen im Schuh."
    },
    {
        id: "k_ew_027",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit schneidet man Papier im Kunstunterricht?",
        answers: ["Messer", "Gabel", "Schere", "Löffel"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Eine Bastelschere teilt Papier sauber und sicher."
    },
    {
        id: "k_ew_028",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das Verkehrsschild mit weißen Streifen auf der Straße?",
        answers: ["Fahrradweg", "Bürgersteig", "Spielstraße", "Zebrastreifen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Zebrastreifen hilft beim sicheren Überqueren."
    },
    {
        id: "k_ew_029",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gebiss verliert man im Kindesalter nach und nach?",
        answers: ["Milchgebiss", "Raubgebiss", "Dauergebiss", "Nagegebiss"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Milchzähne weichen den bleibenden Erwachsenenzähnen."
    },
    {
        id: "k_ew_030",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Woraus besteht die weiße Flüssigkeit aus dem Euter der Kuh?",
        answers: ["Wasser", "Milch", "Saft", "Tee"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Kuhmilch enthält viel Kalzium für Knochen und Zähne."
    },
    {
        id: "k_ew_031",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was liegt nachts oft leuchtend am dunklen Himmel?",
        answers: ["Komet", "Sonne", "Mond", "Wolke"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Mond spiegelt das Licht der Sonne zur Erde."
    },
    {
        id: "k_ew_032",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Schulstunde macht draußen oder in der Halle Bewegung?",
        answers: ["Mathe", "Deutsch", "Musik", "Sport"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Sportunterricht rennt, springt und spielt man."
    },
    {
        id: "k_ew_033",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das Fach, in dem man mit Zahlen rechnet?",
        answers: ["Mathematik", "Sachkunde", "Geschichte", "Geografie"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Mathe lehrt Plus, Minus, Mal und Geteilt."
    },
    {
        id: "k_ew_034",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was passiert mit Eis, wenn die Sonne warm darauf scheint?",
        answers: ["Gefriert", "Schmilzt", "Trocknet", "Verbröselt"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Wärme verwandelt festes Eis wieder in flüssiges Wasser."
    },
    {
        id: "k_ew_035",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Buch enthält Erklärungen von Begriffen im Alphabet?",
        answers: ["Comic", "Roman", "Lexikon", "Märchen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Lexikon erklärt Sachwissen nach Buchstaben geordnet."
    },
    {
        id: "k_ew_036",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie nennt man die Zeit zwischen Mittagessen und Abendbrot?",
        answers: ["Morgen", "Nacht", "Frühstücken", "Nachmittag"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Nachmittag liegt in der zweiten Tageshälfte."
    },
    {
        id: "k_ew_037",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat das Schild mit dem Buchstaben 'H' für Busse?",
        answers: ["Gelb-Grün", "Rot-Weiß", "Blau-Gelb", "Schwarz-Weiß"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Haltestellen-Schilder zeigen ein grünes H im gelben Kreis."
    },
    {
        id: "k_ew_038",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die Wochenendtage Samstag und Sonntag zusammen?",
        answers: ["Schultage", "Wochenende", "Ferientage", "Feiertage"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Samstag und Sonntag bilden gemeinsam das Wochenende."
    },
    {
        id: "k_ew_039",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was schützt die Augen vor hellen UV-Strahlen der Sonne?",
        answers: ["Lesebrille", "Taucherbrille", "Sonnenbrille", "Schutzbrille"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Getönte Gläser filtern grelles Licht ab."
    },
    {
        id: "k_ew_040",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit wäscht man Schmutz von den Händen gründlich ab?",
        answers: ["Creme", "Öl", "Mehl", "Seife"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Wasser und Seife beseitigen Keime und Dreck."
    },

    // 041 - 060
    {
        id: "k_ew_041",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Räder hat ein normales Einrad im Zirkus?",
        answers: ["Ein Rad", "Zwei Räder", "Drei Räder", "Vier Räder"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Einrad besitzt exakt ein einziges Rad."
    },
    {
        id: "k_ew_042",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Monat ist der erste im neuen Kalenderjahr?",
        answers: ["Februar", "Januar", "März", "April"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das neue Jahr beginnt am 1. Januar."
    },
    {
        id: "k_ew_043",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gebilde am Körper schützt unser Gehirn vor Stößen?",
        answers: ["Rippe", "Becken", "Schädel", "Wirbelsäule"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der feste Schädelknochen umhüllt das Gehirn."
    },
    {
        id: "k_ew_044",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Woraus werden Kleider, T-Shirts und Socken meist gewebt?",
        answers: ["Papier", "Glas", "Holz", "Stoff"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Textilien entstehen aus Garnen wie Baumwolle."
    },
    {
        id: "k_ew_045",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was zeigt die Nadel einer Waage in Gramm oder Kilogramm an?",
        answers: ["Gewicht", "Größe", "Länge", "Breite"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Waage misst, wie schwer etwas ist."
    },
    {
        id: "k_ew_046",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was spritzt bei der Feuerwehr mit hohem Druck aus dem Schlauch?",
        answers: ["Schaum", "Wasser", "Luft", "Sand"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Wasser kühlt Brände schnell ab."
    },
    {
        id: "k_ew_047",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die zwei Öffnungen in unserer Nase?",
        answers: ["Augenhöhlen", "Mundwinkel", "Nasenlöcher", "Ohrkanäle"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Durch die Nasenlöcher strömt die Atemluft."
    },
    {
        id: "k_ew_048",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "In welcher Himmelsrichtung geht die Sonne jeden Abend unter?",
        answers: ["Osten", "Süden", "Norden", "Westen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Merksatz: Im Westen geht sie unter."
    },
    {
        id: "k_ew_049",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie lautet die Notrufnummer der Feuerwehr in Deutschland?",
        answers: ["112", "110", "116", "118"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Unter der 112 erreicht man Feuerwehr und Rettungsdienst."
    },
    {
        id: "k_ew_050",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Fach lehrt Singen und Instrumente in der Schule?",
        answers: ["Kunst", "Musik", "Sport", "Ethik"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Musikunterricht geht es um Töne, Lieder und Rhythmus."
    },
    {
        id: "k_ew_051",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Monat ist der allerletzte im Kalenderjahr?",
        answers: ["Oktober", "November", "Dezember", "September"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der 31. Dezember schließt das Jahr ab."
    },
    {
        id: "k_ew_052",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit spitzt man abgestumpfte Buntstifte wieder an?",
        answers: ["Gummi", "Schere", "Lineal", "Spitzer"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Anspitzer schnitzt eine frische Mine."
    },
    {
        id: "k_ew_053",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Zähne bildet das Milchgebiss insgesamt aus?",
        answers: ["20 Zähne", "32 Zähne", "10 Zähne", "28 Zähne"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Das vollständige Milchgebiss hat 20 Zähne."
    },
    {
        id: "k_ew_054",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie nennt man ein Land, das ringsum von Wasser umgeben ist?",
        answers: ["Küste", "Insel", "Halbinsel", "Strand"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Eine Insel hat überall Wasser als Grenze."
    },
    {
        id: "k_ew_055",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Teil der Pflanze verankert sie fest in der Erde?",
        answers: ["Blatt", "Blüte", "Wurzel", "Stängel"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Wurzeln nehmen Wasser auf und halten die Pflanze."
    },
    {
        id: "k_ew_056",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Monat hat üblicherweise als einziger nur 28 Tage?",
        answers: ["März", "Mai", "Juli", "Februar"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Februar ist der kürzeste Monat des Jahres."
    },
    {
        id: "k_ew_057",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Organ im Körper verarbeitet die aufgenommene Nahrung?",
        answers: ["Der Magen", "Die Lunge", "Das Herz", "Das Hirn"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Magen beginnt die Zersetzung des Essens."
    },
    {
        id: "k_ew_058",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat das Schild für die Autobahn in Deutschland?",
        answers: ["Gelb", "Blau", "Rot", "Grün"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Deutsche Autobahnschilder besitzen einen blauen Hintergrund."
    },
    {
        id: "k_ew_059",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welchen Sinn nutzen wir, um Gerüche in der Luft zu riechen?",
        answers: ["Gehör", "Sehsinn", "Geruchssinn", "Tastsinn"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Geruchssinn sitzt in der Nase."
    },
    {
        id: "k_ew_060",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was schützt die Fußgänger vor autosicheren Fahrspuren?",
        answers: ["Fahrbahn", "Streifen", "Gleis", "Gehweg"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Fußgänger nutzen den erhöhten Gehweg."
    },

    // 061 - 080
    {
        id: "k_ew_061",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie lautet die Notrufnummer der Polizei in Deutschland?",
        answers: ["110", "112", "115", "118"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Unter der 110 wählt man den Polizeinotruf."
    },
    {
        id: "k_ew_062",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Aus welchen zwei Farben mischt man die Farbe Orange?",
        answers: ["Blau-Gelb", "Rot-Gelb", "Rot-Blau", "Grün-Gelb"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Mischt man Rot und Gelb, entsteht Orange."
    },
    {
        id: "k_ew_063",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Organ füllt sich beim tiefen Einatmen mit Luft?",
        answers: ["Magen", "Leber", "Lunge", "Niere"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Lunge nimmt den Sauerstoff aus der Atemluft auf."
    },
    {
        id: "k_ew_064",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "In welcher Jahreszeit fallen bunte Blätter von den Bäumen?",
        answers: ["Frühling", "Sommer", "Winter", "Herbst"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Herbst verfärben sich die Blätter und fallen ab."
    },
    {
        id: "k_ew_065",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was zeigt das Stoppschild im Straßenverkehr für Autos an?",
        answers: ["Anhalten", "Langsamer", "Abbiegen", "Beschleunigen"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Am Stoppschild muss das Fahrzeug komplett halten."
    },
    {
        id: "k_ew_066",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Jahreszeiten unterteilen das gesamte Jahr?",
        answers: ["Drei", "Vier", "Fünf", "Sechs"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Frühling, Sommer, Herbst und Winter."
    },
    {
        id: "k_ew_067",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Fach lehrt Schreiben, Lesen und Grammatik?",
        answers: ["Mathe", "Englisch", "Deutsch", "Sachkunde"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Deutschunterricht geht es um Wörter und Texte."
    },
    {
        id: "k_ew_068",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit klebt man zwei Stücke Papier im Bastelunterricht zusammen?",
        answers: ["Schere", "Lineal", "Stift", "Kleber"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Klebestift verbindet Papierbögen dauerhaft."
    },
    {
        id: "k_ew_069",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Himmelskörper umkreist unsere Erde kontinuierlich?",
        answers: ["Der Mond", "Die Sonne", "Der Mars", "Die Venus"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Mond ist der natürliche Begleiter der Erde."
    },
    {
        id: "k_ew_070",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Sinnesorgan-Teil nimmt verschiedene Farben und Licht wahr?",
        answers: ["Ohren", "Augen", "Nase", "Mund"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Mit den Augen sehen wir Formen und Farben."
    },
    {
        id: "k_ew_071",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Fach erklärt Tiere, Pflanzen und Experimente?",
        answers: ["Mathe", "Musik", "Sachkunde", "Deutsch"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Sachunterricht erforscht Natur und Umwelt."
    },
    {
        id: "k_ew_072",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Maßeinheit gibt kurze Strecken auf dem Lineal an?",
        answers: ["Meter", "Liter", "Gramm", "Zentimeter"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Auf Schullinealen misst man in Zentimetern (cm)."
    },
    {
        id: "k_ew_073",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die harten Gebilde im Mund zum Kauen?",
        answers: ["Zähne", "Lippen", "Zunge", "Wangen"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Zähne zerkleinern die Nahrung vor dem Schlucken."
    },
    {
        id: "k_ew_074",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was schiebt sich bei einer Sonnenfinsternis vor die Sonne?",
        answers: ["Erde", "Mond", "Mars", "Venus"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Mond zieht exakt zwischen Erde und Sonne vorbei."
    },
    {
        id: "k_ew_075",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Aus welchen Grundfarben mischt man die Farbe Grün?",
        answers: ["Rot-Gelb", "Rot-Blau", "Blau-Gelb", "Weiß-Schwarz"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Blau und Gelb ergeben die Mischfarbe Grün."
    },
    {
        id: "k_ew_076",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Stunden hat ein volles Tages-und-Nacht-Ganzes?",
        answers: ["12 Stunden", "48 Stunden", "18 Stunden", "24 Stunden"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein voller Tag dauert genau 24 Stunden."
    },
    {
        id: "k_ew_077",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Instrument schlägt die Pausenzeit in der Schule an?",
        answers: ["Schulglocke", "Schultrommel", "Schulpfeife", "Schulhupe"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Schulglocke signalisiert Unterrichtsanfang und -ende."
    },
    {
        id: "k_ew_078",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was spenden Bäume an heißen Sommertagen auf der Wiese?",
        answers: ["Regen", "Schatten", "Wind", "Kälte"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Dichte Baumkronen schirmen das Sonnenlicht ab."
    },
    {
        id: "k_ew_079",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit transportiert man Bücher und Hefte zur Schule?",
        answers: ["Koffer", "Einkaufstüte", "Schulranzen", "Sporttasche"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein ergonomischer Schulranzen schont den Rücken."
    },
    {
        id: "k_ew_080",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Monat liegt direkt vor dem Sommer-Beginn im Juni?",
        answers: ["März", "April", "Juli", "Mai"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Mai ist der fünfte Monat im Kalenderjahr."
    },

    // 081 - 100
    {
        id: "k_ew_081",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was zeigt ein Thermometer im Sommer bei Hitze an?",
        answers: ["Hohe Gradzahl", "Tiefe Gradzahl", "Null Grad", "Minus Grad"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Je wärmer es ist, desto höher steigt die Temperaturanzeige."
    },
    {
        id: "k_ew_082",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gebilde bedeckt den Körper und schützt vor Keimen?",
        answers: ["Knochen", "Haut", "Muskel", "Ader"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Haut bildet die äußere Schutzhülle unseres Körpers."
    },
    {
        id: "k_ew_083",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Verkehrsmittel fährt unter der Erde auf Schienen?",
        answers: ["Straßenbahn", "S-Bahn", "U-Bahn", "Schwebebahn"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "U-Bahnen befördern Passagiere in unterirdischen Tunneln."
    },
    {
        id: "k_ew_084",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was spritzt man sich auf Wunden zur Sauberkeit?",
        answers: ["Wasser", "Seife", "Salbe", "Desinfektion"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Desinfektionsmittel beseitigt Keime in Wunden."
    },
    {
        id: "k_ew_085",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Aus wie vielen Tagen besteht ein normales Kalenderjahr?",
        answers: ["365 Tage", "300 Tage", "350 Tage", "400 Tage"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein gewöhnliches Jahr hat exakt 365 Tage."
    },
    {
        id: "k_ew_086",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat das mittlere Licht an der Ampel?",
        answers: ["Rot", "Gelb", "Grün", "Blau"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Gelb kündigt den Wechsel zwischen Rot und Grün an."
    },
    {
        id: "k_ew_087",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie nennt man die Zeit, in der die Schule im Sommer schließt?",
        answers: ["Pause", "Wochenende", "Sommerferien", "Feiertag"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "In den Sommerferien entspannen Schüler mehrere Wochen."
    },
    {
        id: "k_ew_088",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was tragen Schwimmer an den Augen im Chlorwasser?",
        answers: ["Sonnenbrille", "Lesebrille", "Schutzbrille", "Schwimmbrille"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Eine Schwimmbrille hält das Wasser von den Augen fern."
    },
    {
        id: "k_ew_089",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Zahn fällt bei Kindern meist als erster aus?",
        answers: ["Schneidezahn", "Eckzahn", "Backenzahn", "Weisheitszahn"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die vorderen Schneidezähne wackeln zuerst."
    },
    {
        id: "k_ew_090",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gebilde liegt im Kopf und lässt uns denken?",
        answers: ["Herz", "Gehirn", "Lunge", "Magen"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Gehirn steuert alle Gedanken und Bewegungen."
    },
    {
        id: "k_ew_091",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe hat das grüne Ampelmännchen für Fußgänger?",
        answers: ["Rot", "Gelb", "Grün", "Weiß"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Grün bedeutet: Der Weg kann sicher überquert werden."
    },
    {
        id: "k_ew_092",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Worauf schreiben Lehrer mit Kreide im Klassenzimmer?",
        answers: ["Tisch", "Wand", "Papier", "Tafel"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Auf der Schultafel entstehen Aufgaben und Texte."
    },
    {
        id: "k_ew_093",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welcher Tag folgt im Kalender direkt auf den Freitag?",
        answers: ["Samstag", "Sonntag", "Montag", "Donnerstag"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Auf Freitag folgt der Samstag als erster Wochenendtag."
    },
    {
        id: "k_ew_094",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Womit misst man die Länge eines Tisches genau?",
        answers: ["Waage", "Zollstock", "Uhr", "Thermometer"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Zollstock misst Meter und Zentimeter."
    },
    {
        id: "k_ew_095",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Aus welcher Knochen-Kette besteht die Stütze unseres Rückens?",
        answers: ["Rippen", "Becken", "Wirbelsäule", "Schädel"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Wirbelsäule hält den Oberkörper aufrecht."
    },
    {
        id: "k_ew_096",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die zwei Phasen der Gezeiten am Meer?",
        answers: ["Sonne und Mond", "Warm und Kalt", "Sturm und Wind", "Ebbe und Flut"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Ebbe ist das abfließende, Flut das auflaufende Wasser."
    },
    {
        id: "k_ew_097",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gefäß schützt warme Getränke unterwegs vor dem Abkühlen?",
        answers: ["Thermoskanne", "Glasflasche", "Plastikbecher", "Tasse"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Eine Isolierkanne hält die Wärme im Inneren."
    },
    {
        id: "k_ew_098",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gebilde zieht im Frühling Wasser aus dem Erdreich?",
        answers: ["Blatt", "Wurzel", "Blüte", "Frucht"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Wurzeln versorgen die Pflanze mit Wasser und Nährstoffen."
    },
    {
        id: "k_ew_099",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Welches Gerät erzeugt Wind in der Wohnung an heißen Tagen?",
        answers: ["Heizung", "Herd", "Ventilator", "Kühlschrank"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein Ventilator wirbelt die Raumluft zur Abkühlung auf."
    },
    {
        id: "k_ew_100",
        category: "kinder_erstes_wissen",
        area: "spass",
        subject: "kinder",
        question: "Was schnallt man im Auto immer zu Beginn der Fahrt fest?",
        answers: ["Helm", "Schuhe", "Jacke", "Sicherheitsgurt"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Anschnallgurt schützt Insassen bei Unfällen."
    }
];

if (typeof window !== 'undefined') {
    window.QUESTIONS_KINDER_ERSTES_WISSEN = QUESTIONS_KINDER_ERSTES_WISSEN;
}