// Fun · kinder_anime.js
const KINDER_ANIME_QUESTIONS = [
  {
        id: "k_ani_001",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchem Element-Typ gehört das bekannte Pokémon Pikachu an?",
        answers: ["Pflanze-Typ", "Feuer-Typ", "Wasser-Typ", "Elektro-Typ"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Pikachu ist das berühmteste Elektro-Pokémon."
    },
  {
        id: "k_ani_002",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Hunderasse ist der Polizeihund Chase bei der Paw Patrol?",
        answers: ["Mopshund", "Pudelhund", "Schäferhund", "Labradorhund"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Chase ist ein schlaues deutsches Schäferhund-Welpenkind."
    },
  {
        id: "k_ani_003",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Teufelsfrucht hat der Piratenkapitän Ruffy gegessen?",
        answers: ["Gum-Gum-Frucht", "Stein-Frucht", "Holz-Frucht", "Eis-Eis-Frucht"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Gum-Gum-Frucht macht Ruffys Körper dehnbar wie Gummi."
    },
  {
        id: "k_ani_004",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Farbe bekommen Son Gokus Haare als Super-Saiyajin?",
        answers: ["Rot-Farbe", "Grün-Farbe", "Blau-Farbe", "Gold-Farbe"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Als Super-Saiyajin leuchten Son Gokus Haare golden."
    },
  {
        id: "k_ani_005",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der rote Ninja des Feuers in Lego Ninjago?",
        answers: ["Kai", "Jay", "Cole", "Zane"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Kai ist der Meister des Feuers und trägt den roten Anzug."
    },
  {
        id: "k_ani_006",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der allerbeste Freund von SpongeBob Schwammkopf?",
        answers: ["Sheldon Plankton", "Eugene Mr. Krabs", "Thaddäus Tentakel", "Patrick Seestern"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Patrick der Seestern wohnt direkt neben SpongeBob."
    },
  {
        id: "k_ani_007",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der kleine Bruder von Peppa Wutz?",
        answers: ["Richard Löffel", "Edmond Elefant", "Schorsch Wutz", "Pedro Poni"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Schorsch ist Peppas kleiner Bruder und liebt seinen Saurier."
    },
  {
        id: "k_ani_008",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welcher Hafenstadt arbeitet der mutige Feuerwehrmann Sam?",
        answers: ["Pontypandy", "Entenhausen", "Adventure Bay", "Bikini Bottom"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Sam schützt das kleine walisische Städtchen Pontypandy."
    },
  {
        id: "k_ani_009",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchem Element-Typ gehört das Schildkröten-Pokémon Schiggy an?",
        answers: ["Wasser-Typ", "Feuer-Typ", "Gestein-Typ", "Elektro-Typ"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Schiggy ist das klassische Wasser-Starter-Pokémon."
    },
  {
        id: "k_ani_010",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie nennt sich Marinette, wenn sie sich in eine Heldenfigur verwandelt?",
        answers: ["Queen Bee", "Mayura", "Ladybug", "Rena Rouge"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Marinette beschützt Paris als die Heldin Ladybug."
    },
  {
        id: "k_ani_011",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der neugierige gelbe Bagger bei Bob der Baumeister?",
        answers: ["Rumpel", "Heppo", "Mixi", "Buddel"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Buddel ist der fröhliche gelbe Bagger im Team."
    },
  {
        id: "k_ani_012",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchen Anführer-Titel möchte der junge Ninja Naruto erreichen?",
        answers: ["Anbu-Leiter", "Sannin-Schüler", "Hokage-Titel", "Jounin-Meister"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Naruto träumt davon, der oberste Hokage seines Dorfes zu werden."
    },
  {
        id: "k_ani_013",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches erste Pokémon bekommt der Trainer Ash Ketchum?",
        answers: ["Glumanda", "Schiggy", "Bisasam", "Pikachu"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Da Ash zu spät kam, erhielt er das eigensinnige Pikachu."
    },
  {
        id: "k_ani_014",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die fliegende Hündin mit dem Helikopter bei der Paw Patrol?",
        answers: ["Skye", "Marshall", "Rocky", "Zuma"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Skye fliegt den Rosa-Helikopter und hebt gerne ab."
    },
  {
        id: "k_ani_015",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Mit wie vielen Schwertern gleichzeitig kämpft der Pirat Zorro?",
        answers: ["Vier Schwertern", "Drei Schwertern", "Zwei Schwertern", "Einem Schwert"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Zorro nutzt den Drei-Schwerter-Stil mit einem Schwert im Mund."
    },
  {
        id: "k_ani_016",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Was macht der kleine Wikinger Wickie, wenn er eine rettende Idee hat?",
        answers: ["Reibt die Nase", "Klopft den Fuß", "Reibt die Hand", "Winkt dem Arm"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Wenn sich Wickie an der Nase reibt, fliegen die Sterne für seine Idee."
    },
  {
        id: "k_ani_017",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchem Element-Typ gehört das Pflanzen-Pokémon Bisasam an?",
        answers: ["Elektro-Typ", "Gestein-Typ", "Psycho-Typ", "Pflanze-Typ"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Bisasam trägt eine Pflanzenknospe auf seinem Rücken."
    },
  {
        id: "k_ani_018",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie viele magische Bälle muss man in Dragon Ball sammeln?",
        answers: ["Sieben Bälle", "Neunzehn Bälle", "Zehn Bälle", "Fünf Bälle"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Sind alle sieben Dragon Balls vereint, erscheint der Wunschdrache."
    },
  {
        id: "k_ani_019",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die schwarze sprechende Katze von Sailor Moon?",
        answers: ["Luna", "Diana", "Felix", "Artemis"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Luna trägt einen Halbmond auf der Stirn und hilft Bunny."
    },
  {
        id: "k_ani_020",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die stärkste Lieblingskarte des Duellanten Yugi Muto?",
        answers: ["Weißer Flügeldrache", "Dunkler Magier", "Blauer Drache", "Roter Drache"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Dunkle Magier ist Yugis treueste Zauberkarte."
    },
  {
        id: "k_ani_021",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Fahrzeug steuert der Feuerwehr-Hund Marshall bei Paw Patrol?",
        answers: ["Müllwagenauto", "Baggerfahrzeug", "Feuerwehrwagen", "Polizeiwagen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Marshall fährt das rote Feuerwehrfahrzeug."
    },
  {
        id: "k_ani_022",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Katzen-Pokémon begleitet die Bösewichte von Team Rocket?",
        answers: ["Pikachu", "Mauzi", "Enton", "Evoli"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Mauzi kann als eines der wenigen Pokémon die Menschensprache sprechen."
    },
  {
        id: "k_ani_023",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer wird in Lego Ninjago schließlich zum Grünen Ninja offenbart?",
        answers: ["Skylor", "Lloyd", "Cole", "Jay"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Lloyd Garmadon entwickelt sich zum legendären Grünen Ninja."
    },
  {
        id: "k_ani_024",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist der schlaue Schiffsarzt Tony Chopper in One Piece?",
        answers: ["Ein Koala", "Ein Hund", "Ein Waschbär", "Ein Rentier"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Chopper ist ein kleines Rentier mit einer blauen Nase."
    },
  {
        id: "k_ani_025",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der beste Hirtenfreund von Heidi oben auf der Alm?",
        answers: ["Geißen-Peter", "Senner-Klaus", "Ziegen-Jakob", "Hirten-Hans"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Geißen-Peter hütet zusammen mit Heidi die Ziegen."
    },
  {
        id: "k_ani_026",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der faule, dickliche Bienenfreund der kleinen Biene Maja?",
        answers: ["Bienenfreund Ferdinand", "Bienenfreund Kurt", "Bienenfreund Willi", "Bienenfreund Flip"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Willi schläft sehr gerne und begleitet Maja überall hin."
    },
  {
        id: "k_ani_027",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welches Pokémon entwickelt sich Glumanda auf der ersten Stufe?",
        answers: ["Pikachu", "Evoli", "Glurak", "Glutexo"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Glumanda entwickelt sich zu Glutexo und danach zu Glurak."
    },
  {
        id: "k_ani_028",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welchem Restaurant arbeitet SpongeBob als leidenschaftlicher Koch?",
        answers: ["Burger-Bude", "Bikini-Boden-Grill", "Abfalleimer", "Krosse Krabbe"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "SpongeBob brät die besten Krabbenburger in der Krossen Krabbe."
    },
  {
        id: "k_ani_029",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches riesige Pokémon versperrt oft schlafend den Weg?",
        answers: ["Machollo", "Hornliu", "Taubsi", "Relaxo"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Relaxo schläft stundenlang und muss mit einer Flöte geweckt werden."
    },
  {
        id: "k_ani_030",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welche schwarze Heldenfigur verwandelt sich der Schüler Adrien?",
        answers: ["Hawk Moth", "Carapace", "Viperion", "Cat Noir"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Adrien wird mithilfe von Plagg zum Helden Cat Noir."
    },
  {
        id: "k_ani_031",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der zehnjährige Junge und Anführer der Paw Patrol?",
        answers: ["Rocky", "Chase", "Ryder", "Marshall"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ryder leitet die Einsätze der Fellfreunde an."
    },
  {
        id: "k_ani_032",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die fliegende gelbe Wolke von Son Goku in Dragon Ball?",
        answers: ["Nebelwolke", "Jindujun-Wolke", "Regenbogenwolke", "Zauberwolke"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Nur Personen mit reinem Herzen können auf der Jindujun fliegen."
    },
  {
        id: "k_ani_033",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie hieß das erste eigene Piratenschiff der Strohhutbande?",
        answers: ["Oro Jackson", "Going Merry", "Thousand Sunny", "Red Force"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Going Merry war das erste Schiff von Ruffys Mannschaft."
    },
  {
        id: "k_ani_034",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Aus welchem schwachen Fisch entwickelt sich das mächtige Garados?",
        answers: ["Sterndu", "Schiggy", "Tentacha", "Karpador"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Karpador verwandelt sich auf Level 20 in das wilde Garados."
    },
  {
        id: "k_ani_035",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie lautet der echte Name des geschrumpften Detektivs Conan Edogawa?",
        answers: ["Shin'ichi Kudo", "Heiji Hattori", "Kogoro Mori", "Kaito Kuroba Kid"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Shin'ichi Kudo wurde durch ein Gift in ein Kind verwandelt."
    },
  {
        id: "k_ani_036",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der böse Zauberer, der die Schlümpfe fangen will?",
        answers: ["Schlauchi", "Clumsy", "Gargamel", "Papa Schlumpf"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Gargamel und seine Katze Azrael jagen die kleinen Schlümpfe."
    },
  {
        id: "k_ani_037",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Starter-Pokémon trägt eine kleine Flamme an der Schwanzspitze?",
        answers: ["Bisaflor", "Schiggy", "Bisasam", "Glumanda"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Glumandas Flamme zeigt seinen Gesundheitszustand an."
    },
  {
        id: "k_ani_038",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das kleine Totenkopfäffchen von Pippi Langstrumpf?",
        answers: ["Herr Nilsson", "Annika Settergren", "Kleiner Onkel", "Tommi Settergren"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Herr Nilsson sitzt oft auf Pippis Schulter."
    },
  {
        id: "k_ani_039",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Tierart ist die sprechende Kinderbuchfigur Benjamin Blümchen?",
        answers: ["Ein Nilpferd", "Ein Elefant", "Ein Nashorn", "Ein Erdbär"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Benjamin Blümchen ist der liebe Elefant aus Neustadt."
    },
  {
        id: "k_ani_040",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welchem Ort leitet Sam die örtliche Feuerwache?",
        answers: ["Cardiff-Ort", "London-Stadt", "Bristol-Dorf", "Pontypandy"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Pontypandy ist der Einsatzort von Feuerwehrmann Sam."
    },
  {
        id: "k_ani_041",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welcher Welpe kümmert sich bei Paw Patrol um das Recycling?",
        answers: ["Skye", "Chase", "Zuma", "Rocky"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Rocky repariert Dinge mit recycelten Materialien."
    },
  {
        id: "k_ani_042",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Unter welcher Plage leidet das Enten-Pokémon Enton ständig?",
        answers: ["Ohrschmerzen", "Bauchschmerzen", "Zahnschmerzen", "Kopfschmerzen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Entons Psycho-Kräfte verstärken sich bei starken Kopfschmerzen."
    },
  {
        id: "k_ani_043",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das dinosaurierähnliche Haupt-Digimon von Tai?",
        answers: ["Patamon", "Gatomon", "Gabumon", "Agumon"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Agumon ist das kleine orange Digimon von Tai."
    },
  {
        id: "k_ani_044",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der weise alte Lehrmeister der Lego Ninjago?",
        answers: ["Meister Ray", "Meister Chen", "Meister Wu", "Meister Cole"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Meister Wu unterrichtet die Ninja in der Kunst des Spinjitzu."
    },
  {
        id: "k_ani_045",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der grün gekleidete Bruder des Klempners Super Mario?",
        answers: ["Bowser", "Toad", "Luigi", "Yoshi"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Luigi trägt eine grüne Mütze und hilft Mario."
    },
  {
        id: "k_ani_046",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welches Feuer-Pokémon entwickelt sich Evoli mit einem Feuerstein?",
        answers: ["Folipurba", "Aquana", "Flamara", "Blitza"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Flamara ist die flauschige Feuer-Entwicklung von Evoli."
    },
  {
        id: "k_ani_047",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer kocht die leckersten Gerichte für die Strohhut-Piraten?",
        answers: ["Jinbei", "Sanji", "Brook", "Franky"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Sanji ist der meisterhafte Chefkoch der Piratenbande."
    },
  {
        id: "k_ani_048",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der rothaarige Kobold bei Schreiner Meister Eder?",
        answers: ["Samsling", "Pumuckl", "Rumpelstilz", "Klabauter"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Pumuckl klebt am Leimtopf fest und wird dadurch sichtbar."
    },
  {
        id: "k_ani_049",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches legendäre Eis-Vogel-Pokémon gehört zur ersten Generation?",
        answers: ["Lucario", "Arktos", "Mewtu", "Gengar"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Arktos bildet zusammen mit Zapdos und Lavados das Vogel-Trio."
    },
  {
        id: "k_ani_050",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Nagerart ist der kleine Rufus bei der Agentin Kim Possible?",
        answers: ["Eichhörnchen", "Meerschwein", "Feldhamster", "Nacktmull"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Rufus ist ein rosa Nacktmull und lebt in Rons Tasche."
    },
  {
        id: "k_ani_051",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welcher Tierart gehört der kleine grüne Tabaluga an?",
        answers: ["Feuersalamander", "Grasfrosch", "Leguankopf", "Grüner Drache"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Tabaluga ist ein kleiner grüner Drache aus Grünland."
    },
  {
        id: "k_ani_052",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welcher Welpe liebt das Wasser und fährt ein Luftkissenboot?",
        answers: ["Skye", "Rocky", "Zuma", "Chase"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Zuma ist der Wasserspezialist der Paw Patrol."
    },
  {
        id: "k_ani_053",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die Heimatstadt von Pokémon-Trainer Ash Ketchum?",
        answers: ["Alabastia", "Azuria City", "Vertania City", "Marmoria City"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Ash startet seine Reise im beschaulichen Dorf Alabastia."
    },
  {
        id: "k_ani_054",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der beste Freund von Son Goku seit ihrer Kindheit?",
        answers: ["Krillin", "Piccolo", "Yamchu", "Vegeta"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Krillin trainierte zusammen mit Son Goku bei Muten Roshi."
    },
  {
        id: "k_ani_055",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welcher Berufung geht das Mädchen Bibi Blocksberg nach?",
        answers: ["Kleine Hexe", "Hexenschülerin", "Magierin", "Zauberin"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Bibi ist eine kleine Hexe und fliegt auf ihrem Besen Kartoffelbrei."
    },
  {
        id: "k_ani_056",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Was trinken Homer Simpson und seine Freunde im Moe's am liebsten?",
        answers: ["Apfelsaft", "Mineralglas", "Cola-Dose", "Duff-Bier"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Duff-Bier ist die bekannteste Marke in der Stadt Springfield."
    },
  {
        id: "k_ani_057",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Was wächst auf dem Rücken des Pokémon Bisasam?",
        answers: ["Eine Blüte", "Ein Felsstein", "Eine Knospe", "Ein Palmblatt"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Zwiebelknospe wächst mit Bisasam mit."
    },
  {
        id: "k_ani_058",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das geheime Agenten-Schnabeltier bei Phineas und Ferb?",
        answers: ["Bobo", "Perry", "Rufus", "Gary"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Agent P. heißt bürgerlich Perry das Schnabeltier."
    },
  {
        id: "k_ani_059",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der weiße Ninja des Eises in Lego Ninjago?",
        answers: ["Zane", "Jay", "Kai", "Cole"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Zane ist der kluge Meister des Eises."
    },
  {
        id: "k_ani_060",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die freche Affenfreundin von Tarzan im Dschungel?",
        answers: ["Jane", "Kala", "Tantor", "Terk"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Terk ist die kesse Gorilla-Cousine von Tarzan."
    },
  {
        id: "k_ani_061",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchen gelben Bagger fährt die Bulldogge Rubble bei Paw Patrol?",
        answers: ["Baustellenbagger", "Feuerwehrlöschfahrzeug", "Polizeiwagen", "Rettungsboot"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Rubble ist der Bau-Spezialist im Team."
    },
  {
        id: "k_ani_062",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wozu dient der rot-weiße Pokéball in der Pokémon-Welt?",
        answers: ["Zum Füttern", "Zum Fangen", "Zum Waschen", "Zum Heilen"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Trainer nutzen Pokébälle, um wilde Pokémon zu fangen."
    },
  {
        id: "k_ani_063",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die schlaue Navigatorin der Strohhut-Piratenbande?",
        answers: ["Nefertari Vivi", "Nico Robin", "Nami", "Carrot"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Nami zeichnet Seekarten und steuert das Schiff."
    },
  {
        id: "k_ani_064",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Symbol ist auf Narutos Stirnband eingraviert?",
        answers: ["Wasser-Zeichen", "Blitz-Zeichen", "Feuer-Zeichen", "Blatt-Zeichen"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Symbol steht für Konohagakure, das Dorf unter den Blättern."
    },
  {
        id: "k_ani_065",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "In welches größere Pokémon entwickelt sich Pikachu mit einem Donnerstein?",
        answers: ["Pichu", "Raichu", "Flamara", "Blitza"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Pikachu entwickelt sich durch den Donnerstein zu Raichu."
    },
  {
        id: "k_ani_066",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das kleine Marienkäfer-Kwami von Ladybug?",
        answers: ["Tikki", "Trixx", "Plagg", "Wayzz"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Tikki hilft Marinette bei der Verwandlung."
    },
  {
        id: "k_ani_067",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Woraus brauen die Gummibären ihren magischen Zaubertrank?",
        answers: ["Aus Erdbeeren", "Aus Zauberwurzeln", "Aus Hüpferbeeren", "Aus Waldäpfeln"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Hüpferbeerensaft lässt Gummibären superhoch hüpfen."
    },
  {
        id: "k_ani_068",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wo bewahrt der reiche Onkel Dagobert Duck sein Geld auf?",
        answers: ["Im Geldspeicher", "Im großen Tresorraum", "In der Bank", "Im Keller"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Dagobert schwimmt täglich in den Münzen seines Geldspeichers."
    },
  {
        id: "k_ani_069",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchen Haupt-Typen besitzt der drachenähnliche Glurak?",
        answers: ["Elektro-Typ", "Wasser-Typ", "Psycho-Typ", "Feuer-Typ"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Glurak ist vom Typ Feuer und Flug."
    },
  {
        id: "k_ani_070",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der blaue Ninja des Blitzes in Lego Ninjago?",
        answers: ["Jay", "Cole", "Kai", "Zane"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Jay ist der humorvolle Meister des Blitzes."
    },
  {
        id: "k_ani_071",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Figur wohnt unter einem braunen Stein in Bikini Bottom?",
        answers: ["Plankton", "Mr. Krabs", "Thaddäus", "Patrick"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Patrick Star schläft unter einem großen runden Stein."
    },
  {
        id: "k_ani_072",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißen die Kampfkarten im Kartenspiel von Yu-Gi-Oh!?",
        answers: ["Monsterkarten", "Kampfmagiekarten", "Zaubermünzen", "Spielfiguren"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "In Yu-Gi-Oh! beschwört man starke Monsterkarten auf das Feld."
    },
  {
        id: "k_ani_073",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches kleine Pflanzen-Pokémon hat die Nummer 001 im Pokédex?",
        answers: ["Glumanda", "Endivie", "Bisasam", "Schiggy"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Bisasam ist der erste Eintrag im offiziellen Pokédex."
    },
  {
        id: "k_ani_074",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die schneeliebende Husky-Hündin der Paw Patrol?",
        answers: ["Tracker", "Everest", "Liberty", "Skye"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Everest hilft bei allen Einsätzen im Schnee und Eis."
    },
  {
        id: "k_ani_075",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer baut und repariert als Schiffszimmermann das Piratenschiff?",
        answers: ["Chopper", "Franky", "Usopp", "Brook"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Cyborg Franky ist der meisterhafte Zimmermann der Bande."
    },
  {
        id: "k_ani_076",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das weiße Lieblingspferd der kleinen Hexe Bibi Blocksberg?",
        answers: ["Maharadscha", "Amadeus", "Felix", "Sabrina"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Bibi reitet am liebsten auf der Stute Sabrina."
    },
  {
        id: "k_ani_077",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Was passiert mit anderen, wenn das Pokémon Pummeluff sein Lied singt?",
        answers: ["Sie lachen laut", "Sie weinen leise", "Sie schlafen ein", "Sie tanzen wild"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Pummeluffs Gesang bringt jeden Zuhörer sofort zum Einschlafen."
    },
  {
        id: "k_ani_078",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der Schildkröten-Meister von Son Goku?",
        answers: ["Meister Kaio", "Muten Roshi", "Gott Kami", "Meister Korin"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Muten Roshi brachte Son Goku das Kamehameha bei."
    },
  {
        id: "k_ani_079",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Tierart ist der blaue Kater Tom aus Tom und Jerry?",
        answers: ["Eine Ratte", "Eine Wildkatze", "Eine Hauskatze", "Eine Dogge"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Tom ist die Katze, die vergebens die Maus Jerry jagt."
    },
  {
        id: "k_ani_080",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Worein fiel der kleine Obelix als Kind bei den Galliern?",
        answers: ["In den Fluss", "In den geheimen Kessel", "In den Zaubertrank", "In den Brunnen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Obelix fiel in den Kessel und hat deshalb dauerhaft Zauberkraft."
    },
  {
        id: "k_ani_081",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der Dschungel-Welpe mit den großen Ohren bei Paw Patrol?",
        answers: ["Everest", "Tracker", "Liberty", "Chase"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Tracker hört mit seinen Riesenohren jedes Geräusch im Dschungel."
    },
  {
        id: "k_ani_082",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Pokémon sieht aus wie eine gelbe Ente mit Schnabel?",
        answers: ["Flegmon", "Schiggy", "Enton", "Pikachu"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Enton ist ein gelbes Enten-Pokémon vom Typ Wasser."
    },
  {
        id: "k_ani_083",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wer ist der braune Ninja der Erde in Lego Ninjago?",
        answers: ["Cole", "Kai", "Jay", "Zane"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Cole ist der meisterhafte Verteidiger der Erde."
    },
  {
        id: "k_ani_084",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das musikalische Skelett in Ruffys Piratenbande?",
        answers: ["Franky", "Sanji", "Ruffy", "Brook"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Brook ist der singende Musiker und Skelett-Pirat."
    },
  {
        id: "k_ani_085",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Was trägt das Katzen-Pokémon Mauzi spürbar auf der Stirn?",
        answers: ["Einen Stein", "Einen Stern", "Eine Münze", "Eine Krone"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Mauzi hat eine glänzende Goldmünze auf der Stirn."
    },
  {
        id: "k_ani_086",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das schwarze Katzen-Kwami von Cat Noir?",
        answers: ["Nooroo", "Wayzz", "Tikki", "Plagg"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Plagg liebt Camembert-Käse über alles."
    },
  {
        id: "k_ani_087",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie viele Haare hat der kleine Junge Caillou auf dem Kopf?",
        answers: ["Keine Haare", "Lockenhaare", "Viele Haare", "Kurze Haare"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Caillou ist bekannt für seinen kahlköpfigen Look."
    },
  {
        id: "k_ani_088",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt das große rote Feuerwehrfahrzeug von Sam?",
        answers: ["Venus", "Mercury", "Jupiter", "Bessie"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Jupiter ist das Haupt-Einsatzfahrzeug der Wache."
    },
  {
        id: "k_ani_089",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Pokémon ist der Wasser-Starter der ersten Generation?",
        answers: ["Bisasam", "Schiggy", "Glumanda", "Karnimani"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Schiggy spritzt Wasser und zieht sich im Panzer zurück."
    },
  {
        id: "k_ani_090",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Was trägt Papa Wutz im Gesicht über seinen Augen?",
        answers: ["Sonnenbrille", "Mütze", "Maske", "Brille"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Papa Wutz trägt eine runde Brille."
    },
  {
        id: "k_ani_091",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die Heldin Sailor Moon im japanischen Original?",
        answers: ["Usagi", "Rei", "Makoto", "Ami"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Ihr originaler Name lautet Usagi Tsukino."
    },
  {
        id: "k_ani_092",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Tier ist der grüne Flip bei der Biene Maja?",
        answers: ["Grashüpfer", "Marienkäfer", "Ameise", "Mistkäfer"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Flip ist ein eleganter grüner Grashüpfer mit Zylinder."
    },
  {
        id: "k_ani_093",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt Ashs erster männlicher Reisebegleiter und Arena-Leiter?",
        answers: ["Misty", "Benny", "Tracey", "Rocko"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Rocko war der Arena-Leiter von Marmoria City."
    },
  {
        id: "k_ani_094",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt die Bucht, in der die Paw Patrol zu Hause ist?",
        answers: ["Pontypandy", "Bikini Bottom", "Entenhausen", "Adventure Bay"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Adventure Bay (Abenteuerbucht) ist die Heimat der Hunde."
    },
  {
        id: "k_ani_095",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der erstgeborene Sohn von Son Goku in Dragon Ball?",
        answers: ["Meister Piccolo", "Trunks", "Son Gohan", "Goten"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Son Gohan ist der ältere Sohn von Goku und Chi-Chi."
    },
  {
        id: "k_ani_096",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Wie heißt der beste Freund von Agentin Kim Possible?",
        answers: ["Wade Load", "Lord Monkey Fist", "Ron Stoppable", "Drakken"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Ron Stoppable begleitet Kim bei allen Missionen."
    },
  {
        id: "k_ani_097",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches künstliche Psycho-Pokémon wurde im Labor erschaffen?",
        answers: ["Mewtu", "Rayquaza", "Dialga", "Lucario"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Mewtu wurde aus der DNA von Mew kloniert."
    },
  {
        id: "k_ani_098",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welches Blasinstrument spielt Thaddäus Tentakel in seiner Freizeit?",
        answers: ["Klarinette", "Elektrogitarre", "Trompete", "Flöte"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Thaddäus liebt das Spiel auf seiner Klarinette."
    },
  {
        id: "k_ani_099",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welchem Element gebietet der rote Ninja Kai in Ninjago?",
        answers: ["Eiselement", "Feuerelement", "Erdelement", "Blitzelement"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Kai beherrscht die Flammen des Feuers."
    },
  {
        id: "k_ani_100",
        category: "kinder_anime_cartoons",
        area: "spass",
        subject: "kinder",
        question: "Welche Spezialfunktion besitzt die Brille des kleinen Detektivs Conan?",
        answers: ["Nachtsichtkamera", "Ortungssystem", "Kompass", "Taschenlampe"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Mit der Brille kann Conan den Peilsender verfolgen."
    }
];

if (typeof window !== "undefined") window.KINDER_ANIME_QUESTIONS = KINDER_ANIME_QUESTIONS;
