// Fun · spass_humor (31 Fragen)
const SPASS_HUMOR_QUESTIONS = [
  { id: "q1024", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist das gefährlichste Tier Deutschlands?", answers: ["Der Montagmorgen", "Der Wolf", "Wildschwein", "Die Stechmücke"], correct: 0, difficulty: "mittel", points: 10, explanation: "😱 Kein Tier ist so gefährlich wie der Wecker am Montag!" },
  { id: "q1025", category: "spass_humor", area: "spass", subject: "humor", question: "Wie überlebt man eine Gruppenarbeit?", answers: ["Alles selbst machen", "Nichts machen", "Kaffee trinken und nicken", "Sich unsichtbar machen"], correct: 0, difficulty: "mittel", points: 10, explanation: "🤝 Gruppenarbeit = Eine(r) macht's, der Rest guckt zu!" },
  { id: "q1026", category: "spass_humor", area: "spass", subject: "humor", question: "Was bedeutet 'kurz' auf Deutsch?", answers: ["Zuverlässig weniger als eine Minute", "Irgendwas zwischen 5 Minuten und 3 Stunden", "Höchstens fünf Minuten, wie versprochen", "Genau eine halbe Ewigkeit in der Praxis"], correct: 1, difficulty: "mittel", points: 10, explanation: "⏰ 'Ich bin kurz weg' = Komm in 3 Stunden wieder!" },
  { id: "q1028", category: "spass_humor", area: "spass", subject: "humor", question: "Wofür steht die Abkürzung 'LOL' bei Lehrern?", answers: ["Lernziel Ohne Lust", "Laughing Out Loud", "Lehrer Ohne Lust", "Lehrer Ohne Langeweile"], correct: 0, difficulty: "mittel", points: 10, explanation: "😂 Lehrer-LOL = 'Warum lacht da jemand? Das ist ein ernstes Thema!'" },
  { id: "q1029", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist die häufigste Ausrede für fehlende Hausaufgaben?", answers: ["'Die Cloud hat sie verschluckt'", "'Mein Hund hat sie gefressen'", "'Ich dachte, das ist freiwillig'", "'Der Drucker war kaputt'"], correct: 1, difficulty: "mittel", points: 10, explanation: "🐶 Der Klassiker! Funktioniert seit 100 Jahren." },
  { id: "q1030", category: "spass_humor", area: "spass", subject: "humor", question: "Was denkt ein Lehrer wirklich, wenn er sagt 'Das wird eine leichte Übung'?", answers: ["'Ich will einfach nur meine Ruhe'", "'Viel Spaß beim Verzweifeln'", "'Das habe ich aus dem Internet'", "'Ihr werdet alle scheitern'"], correct: 3, difficulty: "mittel", points: 10, explanation: "😈 'Leichte Übung' = Lehrer-Code für 'Ihr werdet leiden'!" },
  { id: "q1031", category: "spass_humor", area: "spass", subject: "humor", question: "Wofür steht die Abkürzung 'Muttizettel'?", answers: ["Mündliche Unverbindliche Teilnahme-Toleranz", "Mutti, toleriere meinen Zockerabend", "Mütterliche Unterschrift auf Testarbeit", "Mutti tobt immer zu laut in der Praxis"], correct: 0, difficulty: "mittel", points: 10, explanation: "📝 Bürokratisch korrekt: M.U.T.T.! Egal was draufsteht – Hauptsache unterschrieben!" },
  { id: "q1032", category: "spass_humor", area: "spass", subject: "humor", question: "Was macht ein Schüler in der letzten Reihe?", answers: ["Schlafen mit offenen Augen", "Heimlich das Handy streicheln", "Das echte Leben planen", "Das Aufpassen"], correct: 2, difficulty: "mittel", points: 10, explanation: "💭 Letzte Reihe = Denkfabrik für alles außer Unterricht!" },
  { id: "q1033", category: "spass_humor", area: "spass", subject: "humor", question: "Was passiert, wenn der Lehrer sagt 'Ich brauche einen Freiwilligen'?", answers: ["Der Klassenbeste steht routiniert auf", "Sofort schnellen alle Arme nach oben", "Alle schauen aus dem Fenster in der Praxis", "Plötzlich sind alle Schnürsenkel interessant"], correct: 3, difficulty: "mittel", points: 10, explanation: "👀 Nie war der Fußboden so spannend wie in diesem Moment!" },
  { id: "q1034", category: "spass_humor", area: "spass", subject: "humor", question: "Wie lange dauert 'gleich' bei Eltern?", answers: ["Ungefähr eine Minute", "Ungefähr fünf Minuten", "Niemand hat es je gemessen", "Ungefähr drei Stunden"], correct: 2, difficulty: "mittel", points: 10, explanation: "⌛ 'Gleich' ist die dehnbarste Zeiteinheit der Welt." },
  { id: "q1035", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist das Erste, was man nach den Ferien in der Schule lernt?", answers: ["Wie man wieder früh aufsteht", "Die neuen Regeln zur Auswahl", "Den neuen Stundenplan", "Wie der eigene Klassenraum aussieht"], correct: 0, difficulty: "mittel", points: 10, explanation: "😴 Und das ist mit Abstand das schwerste Fach!" },
  { id: "q1036", category: "spass_humor", area: "spass", subject: "humor", question: "Was sagt der Lehrer, wenn die Klasse zu laut ist?", answers: ["'Ich zähle bis drei'", "'Ich warte'", "'Ruhe jetzt'", "'Fünf Minuten früher Schluss'"], correct: 1, difficulty: "mittel", points: 10, explanation: "'Ich warte' ist der Klassiker – aber die Klasse wartet erst, wenn sie leise ist." },
  { id: "q1037", category: "spass_humor", area: "spass", subject: "humor", question: "Was macht ein Schüler, wenn er die Hausaufgaben vergessen hat?", answers: ["'Die Datei ist beschädigt' im Alltag", "'Mein Hund hat es gefressen'", "'Ich war gestern krank' in der Praxis", "'Ich hatte es dabei, aber es ist weg'"], correct: 3, difficulty: "mittel", points: 10, explanation: "Die Ausrede mit dem Hund ist uralt – aber funktioniert heute kaum noch." },
  { id: "q1038", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist der Unterschied zwischen einem Lehrer und einem Klavier?", answers: ["Ein Lehrer kann schimpfen", "Ein Klavier stimmt manchmal", "Ein Beides ist laut", "Beide brauchen Stimmung"], correct: 1, difficulty: "mittel", points: 10, explanation: "Ein Klavier kann gestimmt werden – bei Lehrern ist das selten der Fall." },
  { id: "q1039", category: "spass_humor", area: "spass", subject: "humor", question: "Warum haben Lehrer keine Angst vor Zombies?", answers: ["Weil sie schon graue Haare haben", "Weil Zombies keine Hausaufgaben machen", "Weil sie schon alle Toten sehen", "Weil sie selbst unsterblich sind"], correct: 2, difficulty: "mittel", points: 10, explanation: "Lehrer sehen jeden Tag so viele müde Gesichter – Zombies sind da nicht anders." },
  { id: "q1040", category: "spass_humor", area: "spass", subject: "humor", question: "Was macht ein Schüler, wenn der Lehrer sagt: 'Das wird eine leichte Arbeit'?", answers: ["Er freut sich ehrlich darauf", "Er packt schon mal ein", "Er lernt gar nicht erst", "Er weiß, dass es schwer wird"], correct: 3, difficulty: "mittel", points: 10, explanation: "'Leichte Arbeit' ist Lehrer-Code für 'Ihr werdet lernen'!" },
  { id: "q1041", category: "spass_humor", area: "spass", subject: "humor", question: "Warum hat der Mathelehrer einen Tag Urlaub?", answers: ["Weil er keine Lust auf Algebra hat", "Weil er die Gleichung nicht lösen kann", "Weil er sich verrechnet hat", "Weil er sich in einer Aufgabe verirrt hat"], correct: 0, difficulty: "mittel", points: 10, explanation: "Mathelehrer nehmen selten Urlaub – aber wenn, dann wegen Algebra." },
  { id: "q1042", category: "spass_humor", area: "spass", subject: "humor", question: "Was sagt der Lehrer, wenn ein Schüler zu spät kommt?", answers: ["'Dann geh gleich wieder raus'", "'Na, noch einen Kaffee getrunken?'", "'Der Bus war wohl unsichtbar?'", "'Setz dich einfach schnell hin'"], correct: 1, difficulty: "mittel", points: 10, explanation: "Der Kaffee-Spruch ist ein Klassiker – jeder Lehrer hat ihn schon einmal gebracht." },
  { id: "q1043", category: "spass_humor", area: "spass", subject: "humor", question: "Warum sind Schüler immer müde?", answers: ["Weil Lernen anstrengend aussieht", "Weil sie nachts lernen im Alltag", "Weil sie die ganze Nacht zocken", "Weil sie zu früh aufstehen müssen"], correct: 3, difficulty: "mittel", points: 10, explanation: "Frühes Aufstehen ist der Hauptgrund – die innere Uhr ist nicht für 6 Uhr gemacht." },
  { id: "q1044", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist der Lieblingssatz eines Lehrers nach den Ferien?", answers: ["'Wo waren wir stehen geblieben?'", "'Jetzt wird wieder gearbeitet'", "'Ihr habt gar nichts vergessen, oder?'", "'Willkommen zurück'"], correct: 3, difficulty: "mittel", points: 10, explanation: "'Ihr habt gar nichts vergessen, oder?' – mit einem ironischen Unterton." },
  { id: "q1045", category: "spass_humor", area: "spass", subject: "humor", question: "Warum haben Schüler Angst vor dem Montag?", answers: ["Weil es der Tag des Lehrers ist in der Praxis", "Weil sie dann die Hausaufgaben abgeben müssen", "Weil das Wochenende vorbei ist in der Praxis", "Weil dann die Schule wieder anfängt im Alltag"], correct: 1, difficulty: "mittel", points: 10, explanation: "Am Montag müssen Hausaufgaben abgegeben werden – der Schrecken des Wochenendes." },
  { id: "q1046", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist der Lieblingsspruch von Schülern?", answers: ["'Kriegen wir das noch?'", "'Ich hab's verstanden'", "'Wie lange haben wir noch?'", "'Wann ist Pause?' im Alltag"], correct: 2, difficulty: "mittel", points: 10, explanation: "'Wie lange haben wir noch?' ist der meistgestellte Satz in jedem Klassenzimmer." },
  { id: "q1047", category: "spass_humor", area: "spass", subject: "humor", question: "Warum sind Schüler im Unterricht leise?", answers: ["Sie hören zu", "Sie schlafen", "Sie denken nach", "Sie träumen vom Wochenende"], correct: 1, difficulty: "mittel", points: 10, explanation: "Leise im Unterricht bedeutet oft: Sie schlafen – eine winzige Wahrheit." },
  { id: "q1180", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist der Unterschied zwischen einem Lehrer und einem Drillings?", answers: ["Ein Drillings sind drei, ein Lehrer ist einer", "Ein Drillings machen mehr Lärm in der Praxis", "Ein Beide sind laut in der Praxis", "Ein Lehrer können schimpfen in der Praxis"], correct: 0, difficulty: "mittel", points: 10, explanation: "Ein Drillings sind drei Kinder – ein Lehrer ist nur eine Person." },
  { id: "q1181", category: "spass_humor", area: "spass", subject: "humor", question: "Warum essen Schüler gern Pizza?", answers: ["Weil sie warm ist", "Weil sie keine Hausaufgaben dabei hat", "Weil sie rund ist", "Weil sie schnell geht"], correct: 3, difficulty: "mittel", points: 10, explanation: "Pizza ist schnell, warm und stressfrei – perfekt nach der Schule." },
  { id: "q1183", category: "spass_humor", area: "spass", subject: "humor", question: "Wie viele Lehrer braucht man, um eine Glühbirne zu wechseln?", answers: ["Einen – wenn er die Energie hat in der Praxis", "Es ist ein Geheimnis – niemand weiß es", "Keinen – die Schüler machen es selbst", "Drei – einen für den Strom, zwei für die Show"], correct: 3, difficulty: "mittel", points: 10, explanation: "Lehrer brauchen oft einen Plan, bevor sie handeln – aber der Strom muss stimmen." },
  { id: "q1184", category: "spass_humor", area: "spass", subject: "humor", question: "Was sagt ein Schüler, wenn der Lehrer sagt: 'Ihr habt die Hausaufgaben vergessen?'", answers: ["'Wir hatten keine Zeit' in der Praxis", "'Das war ein Versehen' in der Praxis", "'Nein, wir haben es gestern nicht verstanden'", "'Wir dachten, das ist freiwillig' zur Auswahl"], correct: 2, difficulty: "mittel", points: 10, explanation: "'Nicht verstanden' ist die beliebteste Ausrede – sie funktioniert auch mal." },
  { id: "q1185", category: "spass_humor", area: "spass", subject: "humor", question: "Warum sind Lehrer immer pünktlich?", answers: ["Weil sie wissen, dass die Schüler warten", "Weil sie die Stunde zählen", "Weil sie gern Ordnung haben", "Weil sie keine Zeit verschwenden wollen"], correct: 2, difficulty: "mittel", points: 10, explanation: "Lehrer lieben Struktur und Pünktlichkeit – das ist ihr Markenzeichen." },
  { id: "q1186", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist die meistgestellte Frage im Unterricht?", answers: ["'Wie lange haben wir noch?'", "'Können wir das wiederholen?'", "'Kann ich auf die Toilette?'", "'Habe ich das richtig verstanden?'"], correct: 0, difficulty: "mittel", points: 10, explanation: "Die Frage nach der Zeit ist der Klassiker – und sie kommt alle 5 Minuten." },
  { id: "q1187", category: "spass_humor", area: "spass", subject: "humor", question: "Was macht ein Schüler, wenn er eine 1 in Mathe bekommt?", answers: ["Er feiert am nächsten Tag", "Er glaubt es nicht", "Er ruft seine Mutter an", "Er ist stolz"], correct: 1, difficulty: "mittel", points: 10, explanation: "Bei einer 1 in Mathe ist der Schock so groß, dass er es kaum glauben kann." },
  { id: "q1188", category: "spass_humor", area: "spass", subject: "humor", question: "Was denkt ein Lehrer, wenn er sagt: 'Das wird eine leichte Übung'?", answers: ["'Ihr werdet leiden'", "'Endlich mal etwas Einfaches'", "'Ich will nur, dass ihr ruhig seid'", "'Das war ein Witz'"], correct: 0, difficulty: "mittel", points: 10, explanation: "Lehrer-Code: 'Leichte Übung' bedeutet genau das Gegenteil." },

  { id: "q_hum_n01", category: "spass_humor", area: "spass", subject: "humor", question: "Was sagt der Lehrer, wenn alle Hausaufgaben fehlen?", answers: ["Super!", "Na, dann freut sich das Wochenende?", "Wir machen eine Pause", "Alles egal"], correct: 1, difficulty: "leicht", points: 10, explanation: "Humor hilft – aber Hausaufgaben sollte man trotzdem machen." },
  { id: "q_hum_n02", category: "spass_humor", area: "spass", subject: "humor", question: "Warum nimmt der Mathelehrer einen Regenschirm mit in die Klasse?", answers: ["Weil es draußen regnet", "Wegen der Prozentrechnung (Prozent = 'pro Cent'? Nein – Scherz)", "Für den Sport", "Zum Malen"], correct: 0, difficulty: "leicht", points: 10, explanation: "Manchmal ist die einfachste Antwort die richtige – und draußen regnet es wirklich." },
  { id: "q_hum_n03", category: "spass_humor", area: "spass", subject: "humor", question: "Was ist der Lieblingssnack einer Uhr?", answers: ["Pommes", "Sekundenhäppchen", "Pizza", "Salat"], correct: 1, difficulty: "leicht", points: 10, explanation: "Ein Wortspiel: Uhren 'fressen' die Sekunden – im Scherz." },
  { id: "q_hum_n04", category: "spass_humor", area: "spass", subject: "humor", question: "Warum können Geister so schlecht lügen?", answers: ["Weil man durch sie hindurchschaut", "Weil sie müde sind", "Weil sie keine Stimme haben", "Weil sie hungrig sind"], correct: 0, difficulty: "leicht", points: 10, explanation: "Klassischer Scherz: Durch Geister schaut man hindurch." },
  { id: "q_hum_n05", category: "spass_humor", area: "spass", subject: "humor", question: "Was macht ein Clown im Büro?", answers: ["Er schreibt Witze in Excel", "Er putzt Fenster", "Er kocht Kaffee", "Er schläft"], correct: 0, difficulty: "leicht", points: 10, explanation: "Nur ein Scherz – Clowns gehören eher in den Zirkus." },
  { id: "q_hum_n06", category: "spass_humor", area: "spass", subject: "humor", question: "Warum ging das Schulbuch zum Arzt?", answers: ["Es hatte zu viele Geschichten (und war 'zugeklappt')", "Es wollte Sport machen", "Es war hungrig", "Es wollte malen"], correct: 0, difficulty: "leicht", points: 10, explanation: "Ein Kinderwitz – Bücher werden zugeklappt, Menschen klappen manchmal auch 'zusammen'." },
  { id: "q_hum_n07", category: "spass_humor", area: "spass", subject: "humor", question: "Was sagt man, wenn die Hausaufgaben im Hund gelandet sind?", answers: ["Der Hund hat sie gefressen – der Klassiker", "Alles super", "Morgen nochmal", "Egal"], correct: 0, difficulty: "leicht", points: 10, explanation: "Der ewige Schüler-Scherz: 'Der Hund hat meine Hausaufgaben gefressen'." },
  { id: "q_hum_n08", category: "spass_humor", area: "spass", subject: "humor", question: "Welches Fach 'rechnet' mit deiner Ausrede?", answers: ["Kunst", "Mathe", "Sport", "Musik"], correct: 1, difficulty: "leicht", points: 10, explanation: "Mathe 'rechnet' – im doppelten Sinne." },
  {
    id: "hum_ext_001",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Geister so schlecht lügen?",
    answers: ["Man sieht durch sie hindurch", "Sie sind zu laut", "Sie sind zu schwer", "Sie schlafen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wortspiel."
  },
  {
    id: "hum_ext_002",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist grün und klopft an der Tür?",
    answers: ["Ein Klopfsalat", "Ein Apfel", "Ein Hund", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_003",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Clown im Büro?",
    answers: ["Faxen", "Seriös arbeiten", "Schlafen", "Kochen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Faxen machen."
  },
  {
    id: "hum_ext_004",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum nahm der Mathebuch den Therapeuten?",
    answers: ["Es hatte viele Probleme", "Es war zu dick", "Es war zu leicht", "Es war bunt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Probleme."
  },
  {
    id: "hum_ext_005",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist orange und läuft durch den Wald?",
    answers: ["Eine Saftlane", "Ein Fuchs", "Ein Bär", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wortspiel."
  },
  {
    id: "hum_ext_006",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Geister schlechte Lügner?",
    answers: ["Man sieht durch sie", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "durchsichtig."
  },
  {
    id: "hum_ext_007",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt ein großer Stift zum kleinen Stift?",
    answers: ["Wachs-mal-stift", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wachsmalstift."
  },
  {
    id: "hum_ext_008",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging das Huhn über die Straße?",
    answers: ["Um auf die andere Seite zu kommen", "Zum Einkaufen", "Zum Schlafen", "Zum Fliegen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Klassiker."
  },
  {
    id: "hum_ext_009",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist weiß und stört beim Essen?",
    answers: ["Eine Lawine", "Schnee im Sommer", "Milch", "Zucker"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Lawine – Witz."
  },
  {
    id: "hum_ext_010",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Skelette so schlecht lügen?",
    answers: ["Ihnen fehlt der Mut (Mut=Courage/Organ-Witz)", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wortspiel."
  },
  {
    id: "hum_ext_011",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Pirat am Computer?",
    answers: ["Er drückt die Enter-Taste", "Segelt", "Schläft", "Kocht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Enter."
  },
  {
    id: "hum_ext_012",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war der Computer kalt?",
    answers: ["Windows war offen", "Zu langsam", "Zu schnell", "Zu alt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Windows."
  },
  {
    id: "hum_ext_013",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist braun und hopsst durch den Wald?",
    answers: ["Ein Känguruh-Keks", "Ein Hase", "Ein Bär", "Ein Reh"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_014",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum nahm der Schreiner eine Leiter mit ins Bett?",
    answers: ["Weil er hohe Träume hatte", "Zu kalt", "Zu warm", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "hohe Träume."
  },
  {
    id: "hum_ext_015",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt die Null zur Acht?",
    answers: ["Schicker Gürtel", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gürtel-Witz."
  },
  {
    id: "hum_ext_016",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Fische so schlau?",
    answers: ["Weil sie in Schulen schwimmen", "Zu groß", "Zu klein", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fischschwarm=school."
  },
  {
    id: "hum_ext_017",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist gelb und kann nicht schwimmen?",
    answers: ["Ein Bagger", "Eine Banane", "Die Sonne", "Ein Taxi"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bagger-Witz."
  },
  {
    id: "hum_ext_018",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging der Frosch zum Arzt?",
    answers: ["Er fühlte sich nicht well (well=Quelle)", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Englisch-Wortspiel."
  },
  {
    id: "hum_ext_019",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Matrose auf dem Dach?",
    answers: ["Schifffahrt", "Segelt", "Schläft", "Kocht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Schifffahrt."
  },
  {
    id: "hum_ext_020",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war das Smartphone zum Psychologen?",
    answers: ["Es hatte zu viele Apps-Probleme", "Zu alt", "Zu neu", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Apps."
  },
  {
    id: "hum_ext_021",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist grün und steht im Wald?",
    answers: ["Ein Rührei-Baum? Ein Förster mit Neid", "Ein Baum", "Ein Busch", "Ein Stein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Förster-Witz Variante."
  },
  {
    id: "hum_ext_022",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Vampire so schlecht rechnen?",
    answers: ["Weil sie Blut saugen (nicht Blut zählen)", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "saugen/zählen."
  },
  {
    id: "hum_ext_023",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt ein großes Ei zum kleinen Ei?",
    answers: ["Einhaltung der Größe – Ei-nig", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wortspiel."
  },
  {
    id: "hum_ext_024",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war der Bleistift schlecht gelaunt?",
    answers: ["Er hatte einen Punkt", "Zu kurz", "Zu lang", "Zu bunt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Punkt."
  },
  {
    id: "hum_ext_025",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist schwarz-weiß und rot (read) all over?",
    answers: ["Eine Zeitung", "Ein Zebra", "Ein Panda", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Klassiker (engl.)."
  },
  {
    id: "hum_ext_026",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum nahm der Musiker eine Leiter mit?",
    answers: ["Für hohe Töne", "Zu kalt", "Zu warm", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "hohe Töne."
  },
  {
    id: "hum_ext_027",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Clown im Verkehr?",
    answers: ["Faxen am Steuer – besser nicht", "Seriös fahren", "Schlafen", "Kochen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Faxen."
  },
  {
    id: "hum_ext_028",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Uhren schüchtern?",
    answers: ["Sie haben sich bedeckt (Zifferblatt)", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "bedeckt."
  },
  {
    id: "hum_ext_029",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist orange und schleicht durch die Küche?",
    answers: ["Eine Saft-Lane", "Eine Karotte", "Ein Apfel", "Ein Hund"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_030",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging das Buch zum Arzt?",
    answers: ["Es hatte eine schlechte Bindung", "Zu dick", "Zu dünn", "Zu bunt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bindung."
  },
  {
    id: "hum_ext_031",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt der große Computer zum kleinen?",
    answers: ["Bit-te warten", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bit."
  },
  {
    id: "hum_ext_032",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Skelette so schlecht Karaoke?",
    answers: ["Ihnen fehlt die Kehle/Stimme", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "keine Organe."
  },
  {
    id: "hum_ext_033",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist weiß und springt vom Berg?",
    answers: ["Eine Lawine", "Schnee", "Milch", "Zucker"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Lawine."
  },
  {
    id: "hum_ext_034",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war der Mathelehrer verdächtig?",
    answers: ["Er hatte zu viele Probleme", "Zu streng", "Zu nett", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Probleme."
  },
  {
    id: "hum_ext_035",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Pirat mit einem Handy?",
    answers: ["Er sucht den Netz-Anker", "Segelt", "Schläft", "Kocht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Anker."
  },
  {
    id: "hum_ext_036",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging der Computer zur Schule?",
    answers: ["Um zu bytes (beissen/Bytes)", "Zu alt", "Zu neu", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bytes."
  },
  {
    id: "hum_ext_037",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist grün und hat Räder?",
    answers: ["Ein Gurken-Mobil? Ein Rasenmäher", "Ein Auto", "Ein Zug", "Ein Boot"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rasenmäher-Witz."
  },
  {
    id: "hum_ext_038",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Geister schlechte Tänzer?",
    answers: ["Sie haben keinen Körpergefühl", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "durchsichtig."
  },
  {
    id: "hum_ext_039",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt ein großes Brot zum kleinen?",
    answers: ["Du bist ein Brötchen", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Brötchen."
  },
  {
    id: "hum_ext_040",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum nahm der Astronaut einen Stift mit?",
    answers: ["Für Raum-Notizen", "Zu kalt", "Zu warm", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Notizen."
  },
  {
    id: "hum_ext_041",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist braun und klebt an der Wand?",
    answers: ["Ein Pfannkuchen-Fehler", "Ein Bild", "Ein Nagel", "Ein Schatten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_042",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war die Glühbirne so klug?",
    answers: ["Sie hatte gute Ideen (hell)", "Zu hell", "Zu dunkel", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ideen."
  },
  {
    id: "hum_ext_043",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Clown im Park?",
    answers: ["Faxen", "Seriös joggen", "Schlafen", "Kochen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Faxen."
  },
  {
    id: "hum_ext_044",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Fledermäuse so schlecht singen?",
    answers: ["Sie haben Ultrahall nicht Melodie", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ultraschall."
  },
  {
    id: "hum_ext_045",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist gelb und schreibt?",
    answers: ["Ein Bleistift? Eine Banane mit Stift", "Ein Apfel", "Ein Hund", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_046",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging der Frosch in die Disco?",
    answers: ["Zum Abhoppen", "Zum Schlafen", "Zum Kochen", "Zum Lernen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "hoppen."
  },
  {
    id: "hum_ext_047",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt die Straße zum Auto?",
    answers: ["Fahr mich nicht zu hart", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_048",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Clouds so entspannt?",
    answers: ["Sie haben den Kopf in den Wolken", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wolken."
  },
  {
    id: "hum_ext_049",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist schwarz und macht miau?",
    answers: ["Eine Katze im Dunkeln", "Ein Hund", "Ein Auto", "Ein Baum"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Katze."
  },
  {
    id: "hum_ext_050",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum nahm der Koch eine Uhr mit?",
    answers: ["Für die Garzeit", "Zu kalt", "Zu warm", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zeit."
  },
  {
    id: "hum_ext_051",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Matrose im Büro?",
    answers: ["Schifffahrt der Akten", "Segelt", "Schläft", "Kocht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Akten."
  },
  {
    id: "hum_ext_052",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war das WiFi traurig?",
    answers: ["Es hatte schlechten Empfang", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Empfang."
  },
  {
    id: "hum_ext_053",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist grün und sitzt im Gefängnis?",
    answers: ["Ein Knast-Salat", "Ein Apfel", "Ein Hund", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_054",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum gingen die Skelette nicht zum Party?",
    answers: ["Ihnen fehlte der Körper", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "keine Körper."
  },
  {
    id: "hum_ext_055",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt ein großes Handy zum kleinen?",
    answers: ["Du bist ein Smart-chen", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_056",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war der Bleistift im Stress?",
    answers: ["Er war abgeschrieben", "Zu kurz", "Zu lang", "Zu bunt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "abgeschrieben."
  },
  {
    id: "hum_ext_057",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Clown beim Zahnarzt?",
    answers: ["Faxen mit dem Bohrer-Geräusch", "Seriös sitzen", "Schlafen", "Kochen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Faxen."
  },
  {
    id: "hum_ext_058",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Roboter so schlecht tanzen?",
    answers: ["Steife Gelenke / Programm fehlt", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "steif."
  },
  {
    id: "hum_ext_059",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist orange und trägt eine Krone?",
    answers: ["Eine Königskarotte", "Ein Apfel", "Ein Hund", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_060",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging der Computer schwimmen?",
    answers: ["Um den Cache zu leeren (See)", "Zu alt", "Zu neu", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Cache/See."
  },
  {
    id: "hum_ext_061",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt der große Ball zum kleinen?",
    answers: ["Du bist ein Ballon?", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_062",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Kekse so schlecht im Versteckspiel?",
    answers: ["Man findet sie immer (Keks-Dose)", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_063",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Pirat in der Schule?",
    answers: ["Er lernt die See-Kunde", "Segelt", "Schläft", "Kocht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Seekunde."
  },
  {
    id: "hum_ext_064",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war die Tastatur müde?",
    answers: ["Sie hatte eine Shift-Arbeit", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Shift."
  },
  {
    id: "hum_ext_065",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist weiß und läuft rückwärts?",
    answers: ["Ein Rückwärts-Milch? Ein Eisbär im Spiegel", "Schnee", "Zucker", "Milch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_066",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging das Huhn zum Fitnessstudio?",
    answers: ["Um Eier-training", "Zum Schlafen", "Zum Kochen", "Zum Fliegen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Training."
  },
  {
    id: "hum_ext_067",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt ein großes Boot zum kleinen?",
    answers: ["Du bist ein Boot-chen", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_068",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Uhren immer gestresst?",
    answers: ["Sie sind ständig unter Druck (Feder)", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Druck."
  },
  {
    id: "hum_ext_069",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Clown im Zoo?",
    answers: ["Faxen vor den Affen", "Seriös schauen", "Schlafen", "Kochen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Faxen."
  },
  {
    id: "hum_ext_070",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum konnte der Geisterfahrer nicht parallel parken?",
    answers: ["Geister-Problem", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_071",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist braun und singt?",
    answers: ["Eine Schoko-Note", "Ein Hund", "Ein Auto", "Ein Baum"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_072",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum nahm der Lehrer einen Schwamm mit ins Bett?",
    answers: ["Um Fehler im Traum zu löschen", "Zu kalt", "Zu warm", "Zu laut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "löschen."
  },
  {
    id: "hum_ext_073",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt die Ampel zum Auto?",
    answers: ["Halt bei Rot", "Hallo", "Tschüss", "Fahr immer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rot."
  },
  {
    id: "hum_ext_074",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum war das Buch langweilig?",
    answers: ["Es hatte keine Spannung", "Zu dick", "Zu dünn", "Zu bunt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spannung."
  },
  {
    id: "hum_ext_075",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was macht ein Matrose beim Zahnarzt?",
    answers: ["Er sagt Aaaah wie auf See", "Segelt", "Schläft", "Kocht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Aah."
  },
  {
    id: "hum_ext_076",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum können Katzen so schlecht Geheimnisse behalten?",
    answers: ["Sie plaudern aus dem Nähkästchen", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_077",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was ist gelb und wohnt in der Wand?",
    answers: ["Ein Bananen-Nagel? Eine Banane im Regal", "Ein Apfel", "Ein Hund", "Ein Auto"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_078",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum ging der Frosch zur Bank?",
    answers: ["Um seinen Teich-Kontostand", "Zum Schlafen", "Zum Kochen", "Zum Lernen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Teich."
  },
  {
    id: "hum_ext_079",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Was sagt ein großes Rad zum kleinen?",
    answers: ["Du bist ein Rädchen", "Hallo", "Tschüss", "Stopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Witz."
  },
  {
    id: "hum_ext_080",
    category: "spass_humor",
    area: "spass",
    subject: "spass",
    question: "Warum sind Seifenblasen so optimistisch?",
    answers: ["Sie gehen immer hoch hinaus", "Zu laut", "Zu schwer", "Zu klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "hoch."
  }
];
if (typeof window !== "undefined") window.SPASS_HUMOR_QUESTIONS = SPASS_HUMOR_QUESTIONS;
