 const QUESTIONS_ALLGEMEIN = [
    // 001
    {
        id: "allg_001",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Tage hat ein gewöhnliches Schaltjahr?",
        answers: ["364 Tage", "365 Tage", "366 Tage", "367 Tage"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein Schaltjahr besitzt 366 Tage durch den Zusatztag im Februar."
    },
    {
        id: "allg_002",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Mischfarbe entsteht aus den Grundfarben Blau und Gelb?",
        answers: ["Grün", "Lila", "Orange", "Braun"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Kombination der Grundfarben Blau und Gelb ergibt Grün."
    },
    {
        id: "allg_003",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Säugetier gilt auf Kurzstrecken als das schnellste Landtier?",
        answers: ["Der Löwe", "Der Gepard", "Das Pferd", "Die Gazelle"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Gepard erreicht Geschwindigkeiten von über 100 km/h."
    },
    {
        id: "allg_004",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Laufbeine besitzen Spinnentiere im Unterschied zu Insekten?",
        answers: ["6 Beine", "8 Beine", "10 Beine", "12 Beine"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Spinnentiere besitzen acht Beine, während Insekten sechs haben."
    },
    {
        id: "allg_005",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem europäischen Land befindet sich der berühmte Eiffelturm?",
        answers: ["Spanien", "Italien", "Frankreich", "Deutschland"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Eiffelturm steht in der französischen Hauptstadt Paris."
    },
    {
        id: "allg_006",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches ist das größte und schwerste lebende Tier der Erde?",
        answers: ["Afrikanischer Elefant", "Der mächtige Blauwal", "Die große Netzgiraffe", "Das Breitmaulnashorn"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Blauwal kann eine Länge von bis zu 30 Metern erreichen."
    },
    {
        id: "allg_007",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Hauptfarben werden dem klassischen Regenbogen zugeschrieben?",
        answers: ["5 Farben", "7 Farben", "9 Farben", "11 Farben"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Klassisch werden Rot, Orange, Gelb, Grün, Blau, Indigo und Violett gezählt."
    },
    {
        id: "allg_008",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele verschlungene Ringe bildet das offizielle olympische Symbol?",
        answers: ["Vier Ringe", "Fünf Ringe", "Sechs Ringe", "Sieben Ringe"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die fünf Ringe repräsentieren die fünf bewohnten Kontinente."
    },
    {
        id: "allg_009",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt die offizielle Hauptstadt der Republik Südkorea?",
        answers: ["Busan", "Incheon", "Daegu", "Seoul"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Seoul ist das politische und wirtschaftliche Zentrum Südkoreas."
    },
    {
        id: "allg_010",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Feldspieler stehen beim Fußball pro Team auf dem Platz?",
        answers: ["9 Spieler", "10 Spieler", "11 Spieler", "12 Spieler"],
        correct: 2,
        difficulty: "mittel", points: 10,
        explanation: "Eine Mannschaft besteht aus 10 Feldspielern und einem Torwart."
    },
    {
        id: "allg_011",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Saiten besitzt eine gewöhnliche Konzertgitarre?",
        answers: ["Vier Saiten", "Sechs Saiten", "Acht Saiten", "Zehn Saiten"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Eine Standard-Gitarre ist mit sechs Saiten bespannt."
    },
    {
        id: "allg_012",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land besitzt die flächenmäßig größte Staatsfläche der Erde?",
        answers: ["China", "Russland", "Kanada", "Brasilien"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Russland erstreckt sich über eine Fläche von rund 17 Millionen km²."
    },
    {
        id: "allg_013",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus wie vielen Bundesländern besteht die Republik Österreich?",
        answers: ["7 Länder", "9 Länder", "12 Länder", "16 Länder"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Österreich ist ein Bundesstaat aus insgesamt neun Bundesländern."
    },
    {
        id: "allg_014",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches chemische Element ist bei Raumtemperatur flüssig?",
        answers: ["Quecksilber", "Flüssigeisen", "Reinkupfer", "Weichblei"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Quecksilber ist das einzige Metall, das bei Raumtemperatur flüssig ist."
    },
    {
        id: "allg_015",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Spieler stehen pro Volleyball-Team in der Halle auf dem Feld?",
        answers: ["Sechs Spieler", "Fünf Spieler", "Sieben Spieler", "Acht Spieler"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Beim Hallenvolleyball besteht eine Mannschaft aus sechs Spielern."
    },
    {
        id: "allg_016",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Amtssprache wird im südamerikanischen Land Brasilien gesprochen?",
        answers: ["Spanisch", "Portugiesisch", "Französisch", "Italienisch"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Brasilien ist das einzige portugiesischsprachige Land Amerikas."
    },
    {
        id: "allg_017",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt der höchste Berg der Erde über dem Meeresspiegel?",
        answers: ["Mount Everest", "Der K2 (Godwin)", "Der Mont Blanc", "Kilimandscharo"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Mount Everest im Himalaya ist 8.848 Meter hoch."
    },
    {
        id: "allg_018",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches chemische Element kommt im Universum am häufigsten vor?",
        answers: ["Wasserstoff", "Reinhelium", "Sauerstoff", "Kohlenstoff"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Wasserstoff macht etwa 75 % der gesamten sichtbaren Materie aus."
    },
    {
        id: "allg_019",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem historischen Jahr fiel die Berliner Mauer?",
        answers: ["Jahr 1987", "Jahr 1989", "Jahr 1991", "Jahr 1993"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Berliner Mauer fiel am 9. November 1989."
    },
    {
        id: "allg_020",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Zähne besitzt das Gebiss eines erwachsenen Menschen üblicherweise?",
        answers: ["28 Zähne", "32 Zähne", "36 Zähne", "40 Zähne"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das vollständige bleibende Gebiss hat 32 Zähne inklusive Weisheitszähne."
    },
    {
        id: "allg_021",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt die offizielle Hauptstadt von Australien?",
        answers: ["Sydney", "Melbourne", "Brisbane", "Canberra"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Canberra wurde als Kompromiss zwischen Sydney und Melbourne bestimmt."
    },
    {
        id: "allg_022",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Was stellt flächenmäßig das größte Organ des menschlichen Körpers dar?",
        answers: ["Die Leber", "Die Haut", "Die Lunge", "Der Darm"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Haut ist mit rund 1,8 bis 2 Quadratmetern das größte Organ."
    },
    {
        id: "allg_023",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Auf welchen beiden Ländern erstreckt sich die Wüste Gobi?",
        answers: ["China und Mongolei", "Indien und Pakistan", "Ägypten und Sudan", "Chile und Peru"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Wüste Gobi liegt im Grenzgebiet von China und der Mongolei."
    },
    {
        id: "allg_024",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Planet unseres Sonnensystems steht der Sonne am nächsten?",
        answers: ["Die Venus", "Der Merkur", "Der Mars", "Die Erde"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Merkur ist mit einer Entfernung von rund 58 Mio. km der innerste Planet."
    },
    {
        id: "allg_025",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Einzelknochen besitzt der Körper eines Babys bei der Geburt?",
        answers: ["Etwa 300", "Etwa 206", "Etwa 150", "Etwa 420"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Säuglinge haben ca. 300 Knochen, von denen viele später zusammenwachsen."
    },

    // 26 - 50
    {
        id: "allg_026",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Zahl entspricht die mathematische Definition einer Primzahl?",
        answers: ["Zahl 21", "Zahl 23", "Zahl 25", "Zahl 27"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "23 lässt sich nur durch 1 und sich selbst teilen."
    },
    {
        id: "allg_027",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Ozean bedeckt die größte Gesamtfläche auf unserer Erde?",
        answers: ["Der Atlantik", "Der Pazifik", "Der Indik", "Der Arktik"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Pazifische Ozean ist der größte Ozean der Erde."
    },
    {
        id: "allg_028",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt der höchste und bekannteste aktive Vulkan Europas?",
        answers: ["Der Ätna", "Der Vesuv", "Stromboli", "Teide-Berg"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Ätna liegt auf Sizilien und ragt rund 3.300 Meter hoch."
    },
    {
        id: "allg_029",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus wie vielen Bundesländern besteht die Bundesrepublik Deutschland?",
        answers: ["14 Länder", "15 Länder", "16 Länder", "17 Länder"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Deutschland besteht aus 16 Bundesländern inklusive der Stadtstaaten."
    },
    {
        id: "allg_030",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Bundesland ist flächenmäßig das kleinste Flächenland Deutschlands?",
        answers: ["Saarland", "Bremen", "Hamburg", "Sachsen"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Saarland ist das kleinste deutsche Flächenland."
    },
    {
        id: "allg_031",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher große mitteleuropäische Fluss durchfließt die Stadt Wien?",
        answers: ["Die Donau", "Der Rhein", "Die Elbe", "Der Main"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Donau fließt durch Wien sowie weitere europäische Hauptstädte."
    },
    {
        id: "allg_032",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Organ im Körper treibt den Blutkreislauf ununterbrochen an?",
        answers: ["Das Herz", "Die Leber", "Die Lunge", "Die Niere"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Herz pumpt kontinuierlich Blut durch das Gefäßsystem."
    },
    {
        id: "allg_033",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt die schwedische Hauptstadt, die auf 14 Inseln liegt?",
        answers: ["Malmö", "Stockholm", "Göteborg", "Uppsala"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Stockholm liegt an der Mündung des Mälaren in die Ostsee."
    },
    {
        id: "allg_034",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche offizielle Währung gilt in der Schweizerischen Eidgenossenschaft?",
        answers: ["Der Euro", "Der Franken", "Die Krone", "Der Schilling"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "In der Schweiz zahlt man offiziell mit Schweizer Franken."
    },
    {
        id: "allg_035",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Nachbarplanet der Erde wird wegen Eisenoxid als 'Roter Planet' bezeichnet?",
        answers: ["Der Mars", "Die Venus", "Der Jupiter", "Der Saturn"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Eisenoxidstaub verleiht der Marsoberfläche ihre rote Farbe."
    },
    {
        id: "allg_036",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Was bezeichnet man in der Physik als die Maßeinheit der elektrischen Spannung?",
        answers: ["Ampere", "Watt", "Volt", "Ohm"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Elektrische Spannung wird in Volt (V) gemessen."
    },
    {
        id: "allg_037",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Edelmetall besitzt die chemische Bezeichnung Au im Periodensystem?",
        answers: ["Silber", "Gold", "Platin", "Kupfer"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Au leitet sich vom lateinischen Wort Aurum für Gold ab."
    },
    {
        id: "allg_038",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt die arktische Tierart, deren Haut unter dem Fell schwarz gefärbt ist?",
        answers: ["Polarfuchs", "Eisbär", "Schneeleopard", "Walross"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die schwarze Haut des Eisbären absorbiert Sonnenwärme optimal."
    },
    {
        id: "allg_039",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welcher deutschen Stadt befindet sich das berühmte Brandenburger Tor?",
        answers: ["Hamburg", "München", "Berlin", "Köln"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Brandenburger Tor ist ein bekanntes Wahrzeichen von Berlin."
    },
    {
        id: "allg_040",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Gaskomponente macht den größten Teil der Erdatmosphäre aus?",
        answers: ["Sauerstoff", "Stickstoff", "Kohlendioxid", "Argon"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Stickstoff macht etwa 78 % der Erdatmosphäre aus."
    },
    {
        id: "allg_041",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Maßeinheit gibt die Frequenz von Schall- und Lichtwellen an?",
        answers: ["Hertz", "Pascal", "Joule", "Newton"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Frequenz wird in Hertz (Hz) gemessen."
    },
    {
        id: "allg_042",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Meer grenzt im Nordwesten direkt an Deutschland?",
        answers: ["Die Ostsee", "Die Nordsee", "Das Kaspische Meer", "Das Schwarze Meer"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Deutschland grenzt im Nordwesten an die Nordsee."
    },
    {
        id: "allg_043",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Wissenschaftler begründete die Relativitätstheorie?",
        answers: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Max Planck"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Albert Einstein veröffentlichte die Relativitätstheorie im 20. Jahrhundert."
    },
    {
        id: "allg_044",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem europäischen Land liegt das Gebirgsmassiv der Pyrenäen teilweise?",
        answers: ["Frankreich", "Italien", "Österreich", "Griechenland"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Pyrenäen bilden die natürliche Grenze zwischen Frankreich und Spanien."
    },
    {
        id: "allg_045",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus wie vielen Herzkammern setzt sich das Herz von Menschen zusammen?",
        answers: ["Zwei Kammern", "Drei Kammern", "Vier Kammern", "Fünf Kammern"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Das menschliche Herz unterteilt sich in zwei Vorhöfe und zwei Hauptkammern."
    },
    {
        id: "allg_046",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet die chemische Summenformel für reines Wasser?",
        answers: ["CO2", "H2O", "NaCl", "O2"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Wasser besteht aus zwei Wasserstoffatomen und einem Sauerstoffatom."
    },
    {
        id: "allg_047",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt der flächenmäßig zweitgrößte Kontinent unserer Erde?",
        answers: ["Afrika", "Asien", "Nordamerika", "Europa"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Afrika ist nach Asien der zweitgrößte Kontinent der Erde."
    },
    {
        id: "allg_048",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Planeten gehören offiziell zu unserem Sonnensystem?",
        answers: ["7 Planeten", "8 Planeten", "9 Planeten", "10 Planeten"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Seit 2006 gilt Pluto als Zwergplanet, somit verbleiben 8 Planeten."
    },
    {
        id: "allg_049",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus welchem Land stammt das weltbekannte Gericht Sushi ursprünglich?",
        answers: ["China", "Japan", "Vietnam", "Thailand"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Sushi entwickelte sich in seiner heutigen Form im Japan des 19. Jahrhunderts."
    },
    {
        id: "allg_050",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt die Maßeinheit zur Bestimmung der Lautstärke von Schall?",
        answers: ["Lumen", "Kelvin", "Dezibel", "Pascal"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Schalldruckpegel beziehungsweise die Lautstärke wird in Dezibel (dB) angegeben."
    },

    // 51 - 75
    {
        id: "allg_051",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Ozean befindet sich die tiefste Stelle der Erde, der Marianengraben?",
        answers: ["Atlantischer Ozean", "Pazifischer Ozean", "Indischer Ozean", "Arktischer Ozean"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Challengertief im Marianengraben liegt im westlichen Pazifischen Ozean."
    },
    {
        id: "allg_052",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land war der Gastgeber der Olympischen Sommerspiele im Jahr 2016?",
        answers: ["China", "Brasilien", "Großbritannien", "Japan"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Spiele 2016 fanden in Rio de Janeiro in Brasilien statt."
    },
    {
        id: "allg_053",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie nennt man die Lehre von der Entstehung und Entwicklung der Lebewesen?",
        answers: ["Geologie", "Ökologie", "Evolutionstheorie", "Anatomie"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Evolutionstheorie beschreibt die genetische Veränderung über Generationen."
    },
    {
        id: "allg_054",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus welchem Material besteht die Hülle eines Vogeleies zum Großteil?",
        answers: ["Eisenverbindungen", "Kalziumkarbonat", "Siliziumdioxid", "Magnesiumsulfat"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Vogeleierschalen bestehen zu rund 95 Prozent aus Kalziumkarbonat."
    },
    {
        id: "allg_055",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Stadt ist der Sitz der Europäischen Kommission?",
        answers: ["Strassburg", "Luxemburg", "Brüssel", "Frankfurt"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Hauptsitz der Europäischen Kommission befindet sich in Brüssel."
    },
    {
        id: "allg_056",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Kontinente gibt es nach dem vereinfachten 7-Kontinente-Modell?",
        answers: ["Fünf Kontinente", "Sechs Kontinente", "Sieben Kontinente", "Acht Kontinente"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Gezählt werden Asien, Afrika, Nordamerika, Südamerika, Antarktika, Europa, Australien."
    },
    {
        id: "allg_057",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer entwickelte den ersten modernen Buchdruck mit beweglichen Metalllettern?",
        answers: ["Johannes Gutenberg", "Martin Luther", "Galileo Galilei", "Leonardo da Vinci"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Gutenberg erfand den Buchdruck um 1450 in Mainz."
    },
    {
        id: "allg_058",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Farbe nimmt ein Säure-Indikator wie Lackmus in sauren Lösungen an?",
        answers: ["Blau", "Rot", "Grün", "Gelb"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Lackmus verfärbt sich in Gegenwart von Säuren intensiv rot."
    },
    {
        id: "allg_059",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Fluss ist von der Länge her der längste Strom der Erde?",
        answers: ["Der Mississippi", "Der Amazonas", "Der Nil", "Der Jangtsekiang"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Nil gilt mit etwa 6.650 km meist als der längste Fluss der Welt."
    },
    {
        id: "allg_060",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet die Einheit zur Bemessung der elektrischen Stromstärke?",
        answers: ["Volt", "Ampere", "Ohm", "Watt"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Stromstärke wird international in Ampere (A) gemessen."
    },
    {
        id: "allg_061",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus welcher Pflanzenart gewinnen Imker echten Honig?",
        answers: ["Aus Pflanzenblättern", "Aus Blütennektar", "Aus Baumrinden", "Aus Graswurzeln"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Bienen sammeln Nektar sowie Honigtau und verarbeiten diesen zu Honig."
    },
    {
        id: "allg_062",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Gebirge bildet die natürliche Grenze zwischen Europa und Asien?",
        answers: ["Das Ural-Gebirge", "Die Kaukasus-Kette", "Die Alpengipfel", "Das Himalaya-Massiv"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Ural wird traditionell als östliche Grenze Europas definiert."
    },
    {
        id: "allg_063",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer malte das weltberühmte Gemälde der Mona Lisa?",
        answers: ["Michelangelo", "Leonardo da Vinci", "Vincent van Gogh", "Pablo Picasso"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Leonardo da Vinci erschuf das Ölgemälde im frühen 16. Jahrhundert."
    },
    {
        id: "allg_064",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Sprache weist weltweit die meisten Muttersprachler auf?",
        answers: ["Englisch", "Hochchinesisch", "Spanisch", "Hindi"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Mandarin (Hochchinesisch) hat über 900 Millionen Muttersprachler."
    },
    {
        id: "allg_065",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Edelgas wird wegen seiner geringen Dichte für Luftballons verwendet?",
        answers: ["Neon", "Helium", "Argon", "Krypton"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Helium ist leichter als Luft und bringt Ballons zum Steigen."
    },
    {
        id: "allg_066",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Planet besitzt die auffälligsten und bekanntesten Ringe?",
        answers: ["Jupiter", "Uranus", "Saturn", "Neptun"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Saturn ist berühmt für sein ausgeprägtes Ringsystem aus Eis und Gestein."
    },
    {
        id: "allg_067",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Vogel gilt als größter flugunfähiger Vogel der Welt?",
        answers: ["Kaiserpinguin", "Afrikanischer Strauß", "Emu", "Kasuars"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Strauß ist der größte lebende Vogel der Erde."
    },
    {
        id: "allg_068",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt der flächenmäßig größte See der Erde, der von Land umschlossen ist?",
        answers: ["Der Viktoriasee", "Das Kaspische Meer", "Der Oberer See", "Der Baikal See"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Kaspische Meer ist der flächengrößte See der Erde."
    },
    {
        id: "allg_069",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Organ des menschlichen Körpers wird die Galle gebildet?",
        answers: ["In der Gallenblase", "In der Leber", "In der Bauchspeicheldrüse", "Im Magen"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Galle wird in der Leber produziert und in der Gallenblase gespeichert."
    },
    {
        id: "allg_070",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land schenkte den USA die berühmte Freiheitsstatue?",
        answers: ["Großbritannien", "Spanien", "Frankreich", "Niederlande"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Frankreich schenkte die Statue den USA zur Unabhängigkeitserklärung."
    },
    {
        id: "allg_071",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Planeten in unserem Sonnensystem besitzen feste Oberflächen?",
        answers: ["Zwei Planeten", "Drei Planeten", "Vier Planeten", "Fünf Planeten"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Die vier inneren Planeten (Merkur, Venus, Erde, Mars) sind Gesteinsplaneten."
    },
    {
        id: "allg_072",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches ist das härteste natürliche Mineral auf der Erde?",
        answers: ["Der Diamant", "Das Korund", "Der Quarz", "Das Topas"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Diamant besitzt auf der Mohs-Skala den Höchstwert 10."
    },
    {
        id: "allg_073",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Kontinent liegt die berühmte Wüste Sahara?",
        answers: ["Asien", "Afrika", "Australien", "Südamerika"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Sahara erstreckt sich über das gesamte nördliche Afrika."
    },
    {
        id: "allg_074",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Tier nutzt Echo-Ortung zur Orientierung in der Dunkelheit?",
        answers: ["Der Waldkauz", "Die Fledermaus", "Der Erdwolf", "Die Waldmaus"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Fledermäuse senden Ultraschallwellen aus, um Hindernisse zu orten."
    },
    {
        id: "allg_075",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer entdeckte im Jahr 1928 das erste wirksame Antibiotikum Penicillin?",
        answers: ["Robert Koch", "Alexander Fleming", "Louis Pasteur", "Paul Ehrlich"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Fleming entdeckte die bakterientötende Wirkung des Schimmelpilzes."
    },

    // 76 - 100
    {
        id: "allg_076",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Farbe hat der Farbstoff Chlorophyll in den Zellen von Pflanzen?",
        answers: ["Gelb", "Grün", "Rot", "Blau"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Chlorophyll sorgt für die grüne Ausfärbung von Pflanzenblättern."
    },
    {
        id: "allg_077",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Ozean trennt die Kontinente Europa und Nordamerika voneinander?",
        answers: ["Der Pazifik", "Der Atlantik", "Der Indik", "Der Arktik"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Atlantische Ozean erstreckt sich zwischen Amerika, Europa und Afrika."
    },
    {
        id: "allg_078",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt das größte Binnengewässer im Inneren des Kontinents Nordamerika?",
        answers: ["Der Huronsee", "Der Oberer See", "Der Michigansee", "Der Eriesee"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Obere See ist flächenmäßig der größte Süßwassersee der Erde."
    },
    {
        id: "allg_079",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land hat die größte Bevölkerungszahl weltweit aufzuweisen?",
        answers: ["China", "Indien", "USA", "Indonesien"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Indien hat China als bevölkerungsreichstes Land abgelöst."
    },
    {
        id: "allg_080",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus wie vielen einzelnen Spielern besteht ein normales Eishockey-Team auf dem Eis?",
        answers: ["5 Spieler", "6 Spieler", "7 Spieler", "8 Spieler"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein Team besteht aus 5 Feldspielern und einem Torwart."
    },
    {
        id: "allg_081",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Sekunden enthält eine Zeitspanne von genau einer Stunde?",
        answers: ["1.800 Sekunden", "3.600 Sekunden", "4.200 Sekunden", "7.200 Sekunden"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "60 Minuten mal 60 Sekunden ergeben exakt 3.600 Sekunden."
    },
    {
        id: "allg_082",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer verfasste das berühmte Drama 'Romeo und Julia'?",
        answers: ["Johann Goethe", "William Shakespeare", "Friedrich Schiller", "Molière"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Shakespeare schrieb die Tragödie Ende des 16. Jahrhunderts."
    },
    {
        id: "allg_083",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Vitamin bildet die menschliche Haut mithilfe von Sonnenlicht?",
        answers: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "UV-B-Strahlung regt die Bildung von Vitamin D in der Haut an."
    },
    {
        id: "allg_084",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet die wissenschaftliche Bezeichnung für den Verdunstungsprozess der Pflanzen?",
        answers: ["Fotosynthese", "Respiration", "Transpiration", "Fermentation"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Als Transpiration wird die Verdunstung von Wasser über Blätter bezeichnet."
    },
    {
        id: "allg_085",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Zähne hat das Milchgebiss eines Kindes im Vollzustand?",
        answers: ["16 Zähne", "20 Zähne", "24 Zähne", "28 Zähne"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das vollständige Milchgebiss umfasst genau 20 Zähne."
    },
    {
        id: "allg_086",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Organ steuert das Gleichgewichtsgefühl im menschlichen Körper?",
        answers: ["Das Kleinhirn", "Das Innenohr", "Das Rückenmark", "Die Augen"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Vestibularorgan im Innenohr ist für den Gleichgewichtssinn zuständig."
    },
    {
        id: "allg_087",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Element ist der Hauptbestandteil von Diamanten und Graphit?",
        answers: ["Silizium", "Kohlenstoff", "Sauerstoff", "Stickstoff"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Sowohl Diamant als auch Graphit bestehen aus reiner Kohle."
    },
    {
        id: "allg_088",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Staat der USA liegt der berühmte Yellowstone-Nationalpark?",
        answers: ["Kalifornien", "Wyoming", "Texas", "Alaska"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Großteil des Yellowstone-Nationalparks liegt im US-Bundesstaat Wyoming."
    },
    {
        id: "allg_089",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Gasverbindung verursacht den natürlichen Treibhauseffekt vorrangig?",
        answers: ["Methangas", "Wasserdampf", "Kohlendioxid", "Ozon"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Wasserdampf leistet den größten Beitrag zum natürlichen Treibhauseffekt."
    },
    {
        id: "allg_090",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie nennt man ein Dreieck, bei dem zwei Seiten genau gleich lang sind?",
        answers: ["Gleichseitig", "Gleichschenklig", "Rechtwinklig", "Unregelmäßig"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Bei einem gleichschenkligen Dreieck sind zwei Seiten (Schenkel) gleich lang."
    },
    {
        id: "allg_091",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Jahr landete die erste bemannte Mondmission Apollo 11?",
        answers: ["Jahr 1965", "Jahr 1969", "Jahr 1972", "Jahr 1975"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Neil Armstrong betrat am 21. Juli 1969 als erster Mensch den Mond."
    },
    {
        id: "allg_092",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet die Hauptstadt der Bundesrepublik Deutschland?",
        answers: ["Hamburg", "München", "Berlin", "Frankfurt"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Berlin ist seit der Wiedervereinigung 1990 die deutsche Bundeshauptstadt."
    },
    {
        id: "allg_093",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Säugetier bringt als einziges echte Eier zur Welt?",
        answers: ["Känguru", "Schnabeltier", "Koalabär", "Wombat"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Schnabeltier gehört zu den eierlegenden Ursäugern (Kloakentiere)."
    },
    {
        id: "allg_094",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Fluss durchfließt die ägyptische Hauptstadt Kairo?",
        answers: ["Der Kongo", "Der Nil", "Der Niger", "Der Sambesi"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Nil durchfließt Ägypten und prägt die Hauptstadt Kairo."
    },
    {
        id: "allg_095",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt das hellste Objekt an unserem nächtlichen Himmel?",
        answers: ["Der Venus-Stern", "Der Erdmond", "Der Polarstern", "Der Sirius-Stern"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Mond reflektiert das Sonnenlicht und ist das hellste Objekt bei Nacht."
    },
    {
        id: "allg_096",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Erdteil besitzt die geringste Landfläche aller Kontinente?",
        answers: ["Europa", "Australien", "Antarktika", "Südamerika"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Australien ist der flächenmäßig kleinste Kontinent."
    },
    {
        id: "allg_097",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher griechische Philosoph war der Lehrer von Alexander dem Großen?",
        answers: ["Sokrates", "Platon", "Aristoteles", "Pythagoras"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Aristoteles unterrichtete den jungen Alexander ab 343 v. Chr."
    },
    {
        id: "allg_098",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Maßeinheit gibt die Leistung von Verbrennungsmotoren offiziell im SI-System an?",
        answers: ["Kilowatt", "PS-Zahl", "Newton", "Joule"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die offizielle internationale Maßeinheit für Leistung ist Watt bzw. Kilowatt."
    },
    {
        id: "allg_099",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Spieler bilden ein Basketball-Team auf dem Spielfeld?",
        answers: ["4 Spieler", "5 Spieler", "6 Spieler", "7 Spieler"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein Basketballteam hat immer 5 aktive Spieler auf dem Platz."
    },
    {
        id: "allg_100",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Gebirge trennt Italien vom übrigen europäischen Festland im Norden ab?",
        answers: ["Die Pyrenäen", "Die Alpen", "Die Karpaten", "Der Apennin"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Alpen bilden den nördlichen Grenzwall Italiens zu seinen Nachbarstaaten."
    },

    // 101 - 125
    {
        id: "allg_101",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche geometrische Form besitzt die Grundfläche einer ägyptischen Pyramide üblicherweise?",
        answers: ["Ein Dreieck", "Ein Quadrat", "Ein Sechseck", "Ein Kreis"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die klassischen Pyramiden in Ägypten haben eine quadratische Grundfläche."
    },
    {
        id: "allg_102",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus wie vielen Spielkarten besteht ein klassisches Skat-Blatt?",
        answers: ["24 Karten", "32 Karten", "52 Karten", "36 Karten"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein Skatspiel wird mit genau 32 Karten gespielt."
    },
    {
        id: "allg_103",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer entdeckte auf seiner Seereise im Jahr 1492 Amerika für Europa?",
        answers: ["Vasco da Gama", "Christoph Kolumbus", "Ferdinand Magellan", "Amerigo Vespucci"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Kolumbus erreichte 1492 die karibischen Inseln."
    },
    {
        id: "allg_104",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welcher Stadt steht die berühmte Ruine des Kolosseums?",
        answers: ["Athen", "Rom", "Mailand", "Neapel"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Kolosseum ist das größte antike Amphitheater in Rom."
    },
    {
        id: "allg_105",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet der Name der flächenmäßig größten Insel der Erde?",
        answers: ["Madagaskar", "Grönland", "Borneo", "Neuguinea"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Grönland ist mit über 2,1 Mio. km² die größte Insel der Erde."
    },
    {
        id: "allg_106",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Organ filtrert Abfallstoffe aus dem menschlichen Blutkreislauf?",
        answers: ["Die Leber", "Die Niere", "Die Milz", "Der Magen"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Nieren filtern Abfallstoffe und regulieren den Wasserhaushalt."
    },
    {
        id: "allg_107",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Metall besitzt von allen Metallen die höchste elektrische Leitfähigkeit?",
        answers: ["Kupfer", "Silber", "Gold", "Aluminium"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Silber leitet elektrischen Strom noch besser als Kupfer."
    },
    {
        id: "allg_108",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie nennt man ein Wort, das vorwärts und rückwärts gelesen denselben Sinn ergibt?",
        answers: ["Anagramm", "Palindrom", "Synonym", "Antonym"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Beispiele für Palindrome sind 'Anna' oder 'Otto'."
    },
    {
        id: "allg_109",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Meeresgetier besitzt drei Herzen und blaues Blut?",
        answers: ["Der Quallen-Fisch", "Der Kraken-Oktopus", "Der Seestern", "Der Hammerhai"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Oktopusse besitzen drei Herzen und ein kupferbasiertes blaues Blut."
    },
    {
        id: "allg_110",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Jahr begann der Erste Weltkrieg in Europa?",
        answers: ["Jahr 1912", "Jahr 1914", "Jahr 1918", "Jahr 1939"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Erste Weltkrieg dauerte von 1914 bis 1918."
    },
    {
        id: "allg_111",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet das chemische Symbol für den Grundstoff Eisen?",
        answers: ["Ir", "Fe", "Ei", "Fm"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Symbol Fe leitet sich vom lateinischen Begriff Ferrum ab."
    },
    {
        id: "allg_112",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Vogel ist für seine Fähigkeit bekannt, fremde Geräusche nachzuahmen?",
        answers: ["Der Kolibri", "Der Beo-Vogel", "Der Zaunkönig", "Der Wanderfalke"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Beo gehört zu den Staren und kann Stimmen perfekt imitieren."
    },
    {
        id: "allg_113",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Land liegen die Ruinen des antiken Inka-Ortes Machu Picchu?",
        answers: ["Bolivien", "Peru", "Chile", "Kolumbien"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Machu Picchu liegt in den Anden in Peru."
    },
    {
        id: "allg_114",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie nennt man die Phasenumwandlung von fest direkt zu gasförmig?",
        answers: ["Kondensation", "Sublimation", "Verdampfung", "Erstarren"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Sublimation bezeichnet den direkten Übergang von fest zu gasförmig."
    },
    {
        id: "allg_115",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Organ im Körper produziert das Hormon Insulin?",
        answers: ["Die Schilddrüse", "Die Bauchspeicheldrüse", "Die Nebenniere", "Die Hypophyse"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Insulin wird in den Langerhans-Inseln der Bauchspeicheldrüse gebildet."
    },
    {
        id: "allg_116",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt der tiefste Süßwassersee der Erde mit rund 1.642 Metern Tiefe?",
        answers: ["Der Tanganjikasee", "Der Baikal See", "Der Kaspische See", "Der Viktoriasee"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Baikalsee in Sibirien ist der tiefste und älteste Süßwassersee."
    },
    {
        id: "allg_117",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Planeten im Sonnensystem besitzen ein Ringsystem?",
        answers: ["Ein Planet", "Vier Planeten", "Zwei Planeten", "Drei Planeten"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Alle vier Gasriesen (Jupiter, Saturn, Uranus, Neptun) besitzen Ringe."
    },
    {
        id: "allg_118",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land hat die meisten natürlichen Nachbarländer auf dem Festland?",
        answers: ["Russland", "China", "Brasilien", "Deutschland"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "China und Russland haben jeweils 14 Nachbarländer auf dem Festland."
    },
    {
        id: "allg_119",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus welchem Land stammt die Tanzsportart Tango ursprünglich?",
        answers: ["Spanien", "Argentinien", "Brasilien", "Kuba"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Tango entstand Ende des 19. Jahrhunderts in Argentinien und Uruguay."
    },
    {
        id: "allg_120",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Maßeinheit gibt den Widerstand in einem elektrischen Stromkreis an?",
        answers: ["Ampere", "Ohm", "Volt", "Watt"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der elektrische Widerstand wird in Ohm (Ω) gemessen."
    },
    {
        id: "allg_121",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Zeitalter lebten die berühmten Riesenechsen wie der Tyrannosaurus Rex?",
        answers: ["Im Känozoikum", "Im Mesozoikum", "Im Paläozoikum", "Im Präkambrium"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Dinosaurier lebten im Mesozoikum (Erdmittelalter)."
    },
    {
        id: "allg_122",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer gilt als Erfinder des ersten funktionsfähigen Autos im Jahr 1886?",
        answers: ["Henry Ford", "Carl Benz", "Gottlieb Daimler", "Rudolf Diesel"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Carl Benz meldete 1886 seinen Motorwagen zum Patent an."
    },
    {
        id: "allg_123",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches chemische Element hat die Ordnungszahl 1 im Periodensystem?",
        answers: ["Helium", "Wasserstoff", "Lithium", "Kohlenstoff"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Wasserstoff ist das einfachste und leichteste Element."
    },
    {
        id: "allg_124",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land hat die längste Meeresküste weltweit?",
        answers: ["Australien", "Kanada", "Russland", "Indonesien"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Kanada besitzt mit über 202.000 km die längste Küstenlinie."
    },
    {
        id: "allg_125",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Spieler gehören beim Handball zu einer Mannschaft auf dem Feld?",
        answers: ["6 Spieler", "7 Spieler", "8 Spieler", "9 Spieler"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Beim Hallenhandball spielen 6 Feldspieler und ein Torwart."
    },

    // 126 - 150
    {
        id: "allg_126",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Aus welcher Sprache stammt der Begriff 'Demokratie' ursprünglich?",
        answers: ["Aus dem Lateinischen", "Aus dem Altgriechischen", "Aus dem Hebräischen", "Aus dem Arabischen"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Demokratie leitet sich von 'demos' (Volk) und 'kratein' (herrschen) ab."
    },
    {
        id: "allg_127",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Blutgruppen-System ist weltweit am weitesten verbreitet?",
        answers: ["Das Kell-System", "Das AB0-System", "Das Rhesus-System", "Das MNS-System"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das AB0-System ist das wichtigste Blutgruppensystem beim Menschen."
    },
    {
        id: "allg_128",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt das größte zusammenhängende Waldgebiet der Erde?",
        answers: ["Amazonas-Regenwald", "Die sibirische Taiga", "Kongo-Regenwald", "Schwarzwald-Massiv"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die boreale Taiga in Sibirien ist der größte zusammenhängende Wald."
    },
    {
        id: "allg_129",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Planet benötigt für eine Umrundung der Sonne am längsten?",
        answers: ["Uranus", "Neptun", "Saturn", "Jupiter"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Neptun ist der äußerste Planet und braucht ca. 165 Erdenjahre."
    },
    {
        id: "allg_130",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Vogel gilt als das Symbol der Weisheit in der antiken Mythologie?",
        answers: ["Der Rabe", "Die Eule", "Der Adler", "Der Schwan"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Steinkauzeule war das Begleittier der Göttin Athene."
    },
    {
        id: "allg_131",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Bundesländer grenzen direkt an die Bundesrepublik Deutschland?",
        answers: ["7 Nachbarländer", "9 Nachbarländer", "10 Nachbarländer", "12 Nachbarländer"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Deutschland hat genau 9 direkte Nachbarstaaten."
    },
    {
        id: "allg_132",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer formulierte das physikalische Gesetz des Auftriebs in Flüssigkeiten?",
        answers: ["Pythagoras", "Archimedes", "Euklid", "Sokrates"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Das archimedische Prinzip beschreibt den statischen Auftrieb."
    },
    {
        id: "allg_133",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Teil des Auges befinden sich die Zapfen und Stäbchen zum Sehen?",
        answers: ["In der Hornhaut", "In der Netzhaut", "In der Iris", "In der Linse"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Zapfen und Stäbchen sind die Lichtrezeptoren der Netzhaut."
    },
    {
        id: "allg_134",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Edelmetall leuchtet rötlich und besitzt eine sehr hohe Wärmeleitfähigkeit?",
        answers: ["Messing", "Kupfer", "Bronze", "Zinn"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Kupfer leitet Wärme und Strom hervorragend."
    },
    {
        id: "allg_135",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie lautet die chemische Bezeichnung für Kochsalz?",
        answers: ["Kaliumchlorid", "Natriumchlorid", "Kalziumkarbonat", "Magnesiumsulfat"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Kochsalz besteht chemisch aus Natrium und Chlor (NaCl)."
    },
    {
        id: "allg_136",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Meer grenzt östlich direkt an die Halbinsel Italien?",
        answers: ["Das Tyrrhenische Meer", "Die Adriatische See", "Das Ligurische Meer", "Das Ionische Meer"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Adria liegt zwischen Italien und der Balkanhalbinsel."
    },
    {
        id: "allg_137",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer gilt als Erfinder des dynamischen Schießpulvers Nitroglycerin (Dynamit)?",
        answers: ["Thomas Edison", "Alfred Nobel", "Nikola Tesla", "Alexander Bell"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Alfred Nobel erfand das Dynamit und stiftete den Nobelpreis."
    },
    {
        id: "allg_138",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Zeitzonen umspannen die Erde von West nach Ost offiziell?",
        answers: ["12 Zeitzonen", "24 Zeitzonen", "36 Zeitzonen", "48 Zeitzonen"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Erde ist in 24 Standard-Zeitzonen zu je 15 Längengraden unterteilt."
    },
    {
        id: "allg_139",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Gasverbindung benötigen Pflanzen zwingend für die Fotosynthese?",
        answers: ["Stickstoff", "Kohlendioxid", "Wasserstoff", "Helium"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Pflanzen wandeln Kohlendioxid und Wasser mithilfe von Licht in Traubenzucker um."
    },
    {
        id: "allg_140",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wer schrieb die weltberühmte Komödie 'Der zerbrochne Krug'?",
        answers: ["Goethe", "Heinrich von Kleist", "Schiller", "Lessing"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Heinrich von Kleist verfasste das Drama im Jahr 1806."
    },
    {
        id: "allg_141",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "In welchem Ozean liegen die bekannten Inseln von Hawaii?",
        answers: ["Atlantischer Ozean", "Pazifischer Ozean", "Indischer Ozean", "Arktischer Ozean"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Hawaii ist eine Inselkette im Pazifischen Ozean."
    },
    {
        id: "allg_142",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt das kleinste Säugetier der Welt nach Körpergewicht?",
        answers: ["Zwergmaus", "Kitti-Schweinsnase", "Zwergspitzmaus", "Schläferling"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Kitti-Schweinsnasenfledermaus wiegt nur etwa 2 Gramm."
    },
    {
        id: "allg_143",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welche Stadt ist der Sitz des Internationalen Gerichtshofs?",
        answers: ["Genf", "Den Haag", "Brüssel", "Wien"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Internationale Gerichtshof hat seinen Sitz im Friedenspalast in Den Haag."
    },
    {
        id: "allg_144",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie nennt man die Wissenschaft von den Fossilien und versteinerten Lebewesen?",
        answers: ["Archäologie", "Paläontologie", "Geologie", "Anthropologie"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Paläontologie erforscht fossile Organismen aus vergangenen Erdzeitaltern."
    },
    {
        id: "allg_145",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Fluss durchfließt die französische Hauptstadt Paris?",
        answers: ["Die Rhone", "Die Seine", "Die Loire", "Die Garonne"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Seine durchfließt das Stadtgebiet von Paris."
    },
    {
        id: "allg_146",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Organ im Körper dient primär der Speicherung von Glukose als Glykogen?",
        answers: ["Die Niere", "Die Leber", "Der Magen", "Die Milz"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Leber speichert Kohlenhydrate in Form von Glykogen."
    },
    {
        id: "allg_147",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie viele Spieler bilden ein offizielles Rugby-Union-Team auf dem Platz?",
        answers: ["11 Spieler", "15 Spieler", "13 Spieler", "12 Spieler"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein Rugby-Union-Team besteht auf dem Feld aus 15 Spielern."
    },
    {
        id: "allg_148",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welches Land hat als einziges eine nicht-rechteckige Nationalflagge?",
        answers: ["Bhutan", "Nepal", "Sri Lanka", "Laos"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Flagge von Nepal besteht aus zwei übereinandergelegten Dreiecken."
    },
    {
        id: "allg_149",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Wie heißt das Enzym im Speichel, das Stärke in Zucker spaltet?",
        answers: ["Pepsin", "Ptialin (Amylase)", "Trypsin", "Lipase"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Speichel-Amylase (Ptialin) beginnt bereits im Mund mit dem Stärkeabbau."
    },
    {
        id: "allg_150",
        category: "spass_allgemein",
        area: "spass",
        subject: "allgemein",
        question: "Welcher Stern ist unserer Erde nach der Sonne am nächsten gelegen?",
        answers: ["Sirius", "Proxima Centauri", "Alpha Centauri A", "Betelgeuse"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Proxima Centauri ist mit etwa 4,24 Lichtjahren der sonnennächste Stern."
    }
];

if (typeof window !== 'undefined') {
    window.QUESTIONS_ALLGEMEIN = QUESTIONS_ALLGEMEIN;
}