// Fun · spass_wuerdest_du (37 Fragen)
const SPASS_WUERDEST_DU_QUESTIONS = [
  { id: "q0588", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Was würden die meisten eher tun – einen Popel essen oder Fallschirmspringen?", answers: ["Fallschirmspringen 🪂", "Beides auf keinen Fall!", "Popel essen 🤢", "Erst Popel, dann springen"], correct: 0, difficulty: "mittel", points: 10, explanation: "😄 Die meisten würden wohl eher springen als naschen." },
  { id: "q0589", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Was wählen die meisten: Ketchup oder Senf für immer?", answers: ["Mayonnaise 🥚", "Senf 🌭", "Ketchup 🍅", "Lieber gar nichts"], correct: 2, difficulty: "mittel", points: 10, explanation: "😄 Ketchup gewinnt in Umfragen fast immer." },
  { id: "q0590", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Welche Superkraft wünschen sich die meisten?", answers: ["Keine davon", "Gedankenlesen 🧠", "Fliegen ✈️", "Unsichtbarkeit 👻"], correct: 2, difficulty: "mittel", points: 10, explanation: "😄 Fliegen liegt meist knapp vorn." },
  { id: "q0591", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Was mögen die meisten Menschen lieber: Hunde oder Katzen?", answers: ["Katzen 🐈", "Weder noch", "Beide gleich", "Hunde 🐕"], correct: 3, difficulty: "mittel", points: 10, explanation: "😄 Hunde liegen als Lieblingshaustier meist vorn." },
  { id: "q1326", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Was ist bei Kindern beliebter: Pizza oder Pommes?", answers: ["Weder noch", "Pizza 🍕", "Beides zusammen", "Pommes 🍟"], correct: 1, difficulty: "mittel", points: 10, explanation: "😄 Pizza landet fast immer auf Platz 1." },
  { id: "q1327", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Wo würden die meisten lieber für immer leben?", answers: ["Immer Frühling 🌸", "Immer Winter ❄️", "Immer Sommer ☀️", "Alle vier Jahreszeiten"], correct: 2, difficulty: "mittel", points: 10, explanation: "😄 Der Sommer gewinnt weltweit deutlich." },
  { id: "q1328", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Worauf würden die meisten eher eine Woche verzichten?", answers: ["Auf beides nicht", "Auf Fernsehen 📺", "Auf Süßigkeiten 🍭", "Auf das Handy 📵"], correct: 2, difficulty: "mittel", points: 10, explanation: "😄 Das Handy fällt den meisten schwerer wegzudenken." },
  { id: "q1329", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Riesige Hände oder riesige Füße – was ist die ehrlichste Antwort?", answers: ["Riesige Füße 🦶", "Beide riesig!", "Riesige Hände 🖐️", "Weder noch, bitte!"], correct: 3, difficulty: "mittel", points: 10, explanation: "😄 Beides klingt nach Problemen beim Schuhkauf." },
  { id: "q1330", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Was ist beliebter als Urlaubsziel – Berge oder Meer?", answers: ["Beides gleich", "Meer 🏖️", "Berge ⛰️", "Städtetrip 🏙️"], correct: 1, difficulty: "mittel", points: 10, explanation: "😄 In Umfragen liegt der Strandurlaub meist deutlich vorn." },
  { id: "q1331", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Was trinken die meisten Deutschen morgens?", answers: ["Kakao", "Wasser 💧", "Tee 🍵", "Kaffee ☕"], correct: 3, difficulty: "mittel", points: 10, explanation: "😄 Deutschland ist ein Kaffeeland – rund 160 Liter pro Kopf und Jahr." },
  { id: "q1332", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Scherzfrage: Aufstehen um 6 Uhr oder bis Mittag schlafen – was ist die ehrlichste Antwort?", answers: ["Kommt ganz auf den Tag an", "Bis Mittag schlafen 😴", "Um 6 Uhr aufstehen ⏰", "Am besten durchschlafen"], correct: 0, difficulty: "mittel", points: 10, explanation: "😄 Am Wochenende sieht die Antwort meist anders aus als am Montag." },
  { id: "q1333", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Was ist das beliebteste Haustier in Deutschland?", answers: ["Hamster 🐹", "Kaninchen 🐇", "Katze 🐈", "Hund 🐕"], correct: 2, difficulty: "mittel", points: 10, explanation: "😄 In deutschen Haushalten leben mehr Katzen als Hunde." },
  { id: "q1334", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Scherzfrage: Nie wieder Pizza oder nie wieder Pommes?", answers: ["Bitte beides behalten!", "Nie wieder Pommes 🍟", "Nie wieder Pizza 🍕", "Nie wieder beides"], correct: 0, difficulty: "mittel", points: 10, explanation: "😄 Die ehrlichste Antwort am Familienabend." },
  { id: "q0945", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Welche Eissorte wird weltweit am meisten gegessen?", answers: ["Vanille 🍦", "Erdbeere 🍓", "Zitrone 🍋", "Schokolade 🍫"], correct: 0, difficulty: "mittel", points: 10, explanation: "😄 Vanille gilt als beliebteste Eissorte der Welt." },
  { id: "q0946", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Stunden am Tag ist der Durchschnittsdeutsche online (Handy, PC, TV)?", answers: ["ca. 8 Stunden", "ca. 5 Stunden", "ca. 12 Stunden", "ca. 3 Stunden"], correct: 0, difficulty: "mittel", points: 10, explanation: "Die durchschnittliche Online-Zeit liegt bei etwa 8 Stunden pro Tag – das ist fast ein ganzer Arbeitstag." },
  { id: "q0947", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viel Prozent der Deutschen essen morgens ein Brötchen?", answers: ["ca. 60 %", "ca. 80 %", "ca. 95 %", "ca. 30 %"], correct: 0, difficulty: "mittel", points: 10, explanation: "Rund 60 % der Deutschen frühstücken ein Brötchen – ein echter Brot-Kult." },
  { id: "q0948", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Selfies werden pro Tag weltweit geschossen?", answers: ["ca. 10 Milliarden", "ca. 100 Millionen", "ca. 10 Millionen", "ca. 1 Milliarde"], correct: 1, difficulty: "mittel", points: 10, explanation: "Schätzungen zufolge werden täglich etwa 100 Millionen Selfies gemacht." },
  { id: "q0949", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viel Zucker steckt im Durchschnitt in einer Tasse Cola?", answers: ["10 Stück", "1 Stück", "20 Stück", "5 Stück"], correct: 3, difficulty: "mittel", points: 10, explanation: "Eine Tasse Cola (250 ml) enthält etwa 5-6 Stück Würfelzucker – das ist viel!" },
  { id: "q0950", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Kilometer fährt ein Auto durchschnittlich pro Jahr?", answers: ["12.000 km", "5.000 km", "50.000 km", "25.000 km"], correct: 0, difficulty: "mittel", points: 10, explanation: "Der durchschnittliche PKW in Deutschland fährt rund 12.000 km pro Jahr." },
  { id: "q0951", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Ein Jahr ohne Internet oder ein Jahr ohne Schokolade?", answers: ["Beides weglassen", "Keins von beiden!", "Ohne Schokolade 🍫", "Ohne Internet 📵"], correct: 1, difficulty: "mittel", points: 10, explanation: "Die meisten würden sagen: Auf beide möchte ich ungern verzichten!" },
  { id: "q0952", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Für immer Strandurlaub oder für immer Bergurlaub?", answers: ["Weder noch", "Beides!", "Für immer Strand 🏖️", "Für immer Berge ⛰️"], correct: 1, difficulty: "mittel", points: 10, explanation: "Warum entscheiden? Die meisten träumen von Abwechslung." },
  { id: "q0953", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Deutsche gehen regelmäßig zum Sport (mind. 1x/Woche)?", answers: ["ca. 35 %", "ca. 75 %", "ca. 15 %", "ca. 55 %"], correct: 0, difficulty: "mittel", points: 10, explanation: "Rund ein Drittel der Deutschen treibt regelmäßig Sport – Potenzial nach oben!" },
  { id: "q0954", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Deutsche lesen ein Buch pro Monat?", answers: ["ca. 25 %", "ca. 50 %", "ca. 70 %", "ca. 10 %"], correct: 0, difficulty: "mittel", points: 10, explanation: "Etwa jeder Vierte liest ein Buch pro Monat – der Rest schaut lieber Serien." },
  { id: "q0955", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Nie wieder ins Kino oder nie wieder Netflix?", answers: ["Nie wieder Kino 🍿", "Beides weglassen", "Beides behalten!", "Nie wieder Netflix 📺"], correct: 2, difficulty: "mittel", points: 10, explanation: "Die meisten wollen beides – Streaming ist aber oft beliebter." },
  { id: "q0956", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie lange liegt der durchschnittliche Deutsche am Tag auf dem Sofa?", answers: ["ca. 1 Stunde", "ca. 7 Stunden", "ca. 3 Stunden", "ca. 5 Stunden"], correct: 2, difficulty: "mittel", points: 10, explanation: "Rund 3 Stunden gemütliche Sofa-Zeit am Tag – die meiste Zeit abends." },
  { id: "q0957", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Tassen Kaffee trinkt der Deutsche pro Tag im Durchschnitt?", answers: ["1 Tasse", "3 Tassen", "7 Tassen", "5 Tassen"], correct: 1, difficulty: "mittel", points: 10, explanation: "Der Durchschnitt liegt bei etwa 3 Tassen Kaffee pro Tag – knapp 160 Liter im Jahr." },
  { id: "q0958", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Einen Monat ins All fliegen oder einen Monat auf eine einsame Insel?", answers: ["Monat im All 🚀 zur Auswahl", "Monat auf der Insel 🏝️", "Beides klingt anstrengend!", "Weder noch in der Praxis"], correct: 2, difficulty: "mittel", points: 10, explanation: "Im All ist es kalt, auf der Insel einsam – die meisten sind lieber zu Hause." },
  { id: "q0959", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viel Prozent der Deutschen sind Linkshänder?", answers: ["ca. 5 %", "ca. 10 %", "ca. 30 %", "ca. 20 %"], correct: 1, difficulty: "mittel", points: 10, explanation: "Rund 10 % der Bevölkerung sind Linkshänder – ein häufiger Irrglaube ist 5 %." },
  { id: "q1081", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Für immer in einer Großstadt oder auf dem Land leben?", answers: ["Großstadt 🏙️", "Auf dem Land 🌾", "Beides gleich", "Weder noch"], correct: 2, difficulty: "mittel", points: 10, explanation: "Die meisten wünschen sich die Vorteile beider Welten." },
  { id: "q1082", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Bücher liest der Durchschnittsdeutsche pro Jahr?", answers: ["ca. 1", "ca. 5", "ca. 20", "ca. 12"], correct: 1, difficulty: "mittel", points: 10, explanation: "Im Schnitt werden etwa 5 Bücher pro Jahr gelesen – viele lesen aber deutlich mehr." },
  { id: "q1083", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Stunden am Tag ist der durchschnittliche Deutsche am Handy?", answers: ["ca. 1 Stunde", "ca. 6 Stunden", "ca. 2 Stunden", "ca. 3,5 Stunden"], correct: 3, difficulty: "mittel", points: 10, explanation: "Die tägliche Smartphone-Nutzung liegt bei etwa 3,5 Stunden – ein echter Zeitfresser." },
  { id: "q1084", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viel Prozent der Deutschen haben ein Haustier?", answers: ["ca. 80 %", "ca. 40 %", "ca. 60 %", "ca. 20 %"], correct: 1, difficulty: "mittel", points: 10, explanation: "Etwa 40 % der deutschen Haushalte haben ein Haustier, meist Katzen oder Hunde." },
  { id: "q1085", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Ein Jahr ohne Auto oder ein Jahr ohne Fernsehen?", answers: ["Beides wäre schlimm", "Ohne Fernsehen 📺", "Ohne Auto 🚗", "Beides egal"], correct: 0, difficulty: "mittel", points: 10, explanation: "Für die meisten ist beides ein großer Verzicht – aber das Auto ist oft wichtiger." },
  { id: "q1086", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Tassen Kaffee trinken die Deutschen durchschnittlich am Tag?", answers: ["3 Tassen", "5 Tassen", "7 Tassen", "1 Tasse"], correct: 0, difficulty: "mittel", points: 10, explanation: "Mit etwa 3 Tassen am Tag ist Deutschland ein Kaffeeland." },
  { id: "q1087", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Selfies werden weltweit pro Tag gemacht?", answers: ["ca. 10 Milliarden", "ca. 1 Milliarde", "ca. 100 Millionen", "ca. 10 Millionen"], correct: 2, difficulty: "mittel", points: 10, explanation: "Täglich werden etwa 100 Millionen Selfies geschossen – ein Selfie-Wahn!" },
  { id: "q1088", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Schätzfrage: Wie viele Schritte geht der Durchschnittsdeutsche am Tag?", answers: ["ca. 6.000", "ca. 15.000", "ca. 10.000", "ca. 3.000"], correct: 3, difficulty: "mittel", points: 10, explanation: "Die empfohlenen 10.000 Schritte werden im Alltag meist nicht erreicht." },
  { id: "q1089", category: "spass_wuerdest_du", area: "spass", subject: "wuerdest_du", question: "Würdest du eher: Eine Weltreise machen oder ein neues Auto kaufen?", answers: ["Weltreise ✈️", "Neues Auto 🚗", "Eher sparen", "Beides wäre toll"], correct: 3, difficulty: "mittel", points: 10, explanation: "Die meisten wollen beides – aber die Weltreise ist das größere Abenteuer." },
  {
    id: "wue_ext_001",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher fliegen können oder unsichtbar sein?",
    answers: ["Fliegen", "Unsichtbar", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_002",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ewig Sommer oder ewig Winter haben?",
    answers: ["Sommer", "Winter", "Wechsel", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_003",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nur süß oder nur salzig essen?",
    answers: ["Süß", "Salzig", "Beides mal", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_004",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher reich und gestresst oder arm und entspannt sein?",
    answers: ["Reich/gestresst", "Arm/entspannt", "Mitte", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_005",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in der Zukunft oder in der Vergangenheit leben?",
    answers: ["Zukunft", "Vergangenheit", "Gegenwart", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_006",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher sprechen können mit Tieren oder alle Sprachen können?",
    answers: ["Tiere", "Sprachen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_007",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer die Wahrheit sagen oder immer lügen müssen?",
    answers: ["Wahrheit", "Lügen", "Situativ", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_008",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher berühmt und beobachtet oder anonym und frei sein?",
    answers: ["Berühmt", "Anonym", "Mitte", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_009",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder fernsehen oder nie wieder Internet?",
    answers: ["Kein TV", "Kein Netz", "Beides selten", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_010",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher auf dem Land oder in der Großstadt leben?",
    answers: ["Land", "Stadt", "Beides mal", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_011",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer zu heiß oder immer zu kalt haben?",
    answers: ["Heiß", "Kalt", "Angenehm", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_012",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher superstark oder superschnell sein?",
    answers: ["Stark", "Schnell", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_013",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nur Bücher oder nur Filme für den Rest des Lebens?",
    answers: ["Bücher", "Filme", "Beides mal", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_014",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in die Berge oder ans Meer in den Urlaub?",
    answers: ["Berge", "Meer", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_015",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher früh aufstehen oder lange aufbleiben?",
    answers: ["Früh", "Spät", "Variabel", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_016",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher kochen können wie ein Profi oder singen wie ein Profi?",
    answers: ["Kochen", "Singen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_017",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder Süßigkeiten oder nie wieder Fast Food?",
    answers: ["Kein Süß", "Kein Fast Food", "Beides selten", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_018",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher Zeitreisen oder Gedanken lesen?",
    answers: ["Zeitreisen", "Gedanken", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_019",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer Glück oder immer Gesundheit haben?",
    answers: ["Glück", "Gesundheit", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_020",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Haustier-Drache oder ein Haustier-Einhorn haben?",
    answers: ["Drache", "Einhorn", "Keins", "Beides unmöglich"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_021",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher unter Wasser oder im Weltall leben können?",
    answers: ["Unter Wasser", "Weltall", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_022",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder Sport oder nie wieder Musik?",
    answers: ["Kein Sport", "Keine Musik", "Beides wenig", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_023",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer die neueste Technik oder immer klassische Dinge?",
    answers: ["Technik", "Klassisch", "Mischung", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_024",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher alleine reisen oder immer in der Gruppe?",
    answers: ["Alleine", "Gruppe", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_025",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Foto von dir löschen können aus dem Netz oder nie online gewesen sein?",
    answers: ["Löschen", "Nie online", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_026",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer recht haben oder immer beliebt sein?",
    answers: ["Recht", "Beliebt", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_027",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in einem Baumhaus oder in einem Hausboot wohnen?",
    answers: ["Baumhaus", "Hausboot", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_028",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder lügen dürfen oder nie wieder Geheimnisse haben?",
    answers: ["Keine Lügen", "Keine Geheimnisse", "Situativ", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_029",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher fliegen ohne Flugzeug oder tauchen ohne Gerät?",
    answers: ["Fliegen", "Tauchen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_030",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer Musik im Ohr oder immer Stille haben?",
    answers: ["Musik", "Stille", "Wechsel", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_031",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr ohne Handy oder ein Jahr ohne Freunde treffen?",
    answers: ["Kein Handy", "Keine Treffen", "Beides hart", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_032",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher superhören oder supersehen?",
    answers: ["Hören", "Sehen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_033",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer gewinnen oder immer fair spielen?",
    answers: ["Gewinnen", "Fair", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_034",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in der Vergangenheit berühmt oder in der Zukunft unbekannt leben?",
    answers: ["Vergangenheit berühmt", "Zukunft anonym", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_035",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder lachen oder nie wieder weinen?",
    answers: ["Kein Lachen", "Kein Weinen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_036",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein unsichtbares Haustier oder ein sprechendes Haustier?",
    answers: ["Unsichtbar", "Sprechend", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_037",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer zu spät oder immer zu früh kommen?",
    answers: ["Zu spät", "Zu früh", "Pünktlich", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_038",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher alle Sprachen fließend oder alle Instrumente spielen?",
    answers: ["Sprachen", "Instrumente", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_039",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher im Schnee oder in der Wüste überleben trainieren?",
    answers: ["Schnee", "Wüste", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_040",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder träumen oder immer lebhafte Träume haben?",
    answers: ["Keine Träume", "Viele Träume", "Normal", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_041",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Tag als Tier oder ein Tag als Roboter?",
    answers: ["Tier", "Roboter", "Mensch bleiben", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_042",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer die Wahrheit hören oder nie Kritik bekommen?",
    answers: ["Wahrheit", "Keine Kritik", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_043",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher auf einer Insel oder in einer Großstadt feststecken (ein Jahr)?",
    answers: ["Insel", "Stadt", "Beides ok", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_044",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher fliegen können wie ein Vogel oder schwimmen wie ein Fisch?",
    answers: ["Fliegen", "Schwimmen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_045",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder Fast Food oder nie wieder Restaurant?",
    answers: ["Kein Fast Food", "Kein Restaurant", "Beides selten", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_046",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer Glück haben beim Spielen oder immer lernen leicht?",
    answers: ["Glück", "Leicht lernen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_047",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr ohne Süßes oder ein Jahr ohne Salz?",
    answers: ["Kein Süß", "Kein Salz", "Beides hart", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_048",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher berühmt für Sport oder berühmt für Kunst sein?",
    answers: ["Sport", "Kunst", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_049",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer den Sonnenuntergang oder immer den Sonnenaufgang sehen?",
    answers: ["Untergang", "Aufgang", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_050",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein unsichtbares Auto oder ein fliegendes Fahrrad?",
    answers: ["Auto unsichtbar", "Fahrrad fliegend", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_051",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder zornig sein oder nie wieder ängstlich?",
    answers: ["Kein Zorn", "Keine Angst", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_052",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in einem Schloss oder in einem modernen Loft wohnen?",
    answers: ["Schloss", "Loft", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_053",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher alle Bücher der Welt lesen oder alle Filme sehen können?",
    answers: ["Bücher", "Filme", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_054",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer ehrlich Feedback oder immer Komplimente bekommen?",
    answers: ["Feedback", "Komplimente", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_055",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Tag ohne Schlaf oder eine Woche ohne Handy?",
    answers: ["Kein Schlaf", "Kein Handy", "Beides hart", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_056",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher superkochen oder superbacken?",
    answers: ["Kochen", "Backen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_057",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in der Natur campen oder im Hotel mit Spa?",
    answers: ["Campen", "Hotel", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_058",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer gewinnen dürfen oder immer spannende Spiele haben?",
    answers: ["Gewinnen", "Spannung", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_059",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein sprechender Spiegel oder ein fliegender Teppich?",
    answers: ["Spiegel", "Teppich", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_060",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder Regen oder nie wieder Wind?",
    answers: ["Kein Regen", "Kein Wind", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_061",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr nur Pizza oder ein Jahr nur Pasta?",
    answers: ["Pizza", "Pasta", "Wechsel", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_062",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher früh berühmt oder spät weise werden?",
    answers: ["Früh berühmt", "Spät weise", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_063",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer Musik wählen dürfen oder immer den Film wählen?",
    answers: ["Musik", "Film", "Wechsel", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_064",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein unsichtbarer Freund oder ein sichtbarer Roboter-Freund?",
    answers: ["Unsichtbar", "Roboter", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_065",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder warten müssen oder nie wieder suchen müssen?",
    answers: ["Kein Warten", "Kein Suchen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_066",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher auf dem Mond oder unter dem Meer eine Nacht verbringen?",
    answers: ["Mond", "Meer", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_067",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer die perfekte Playlist oder immer das perfekte Wetter?",
    answers: ["Playlist", "Wetter", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_068",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Tag als König/Königin oder ein Tag als Entdecker?",
    answers: ["König", "Entdecker", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_069",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder müde sein oder nie wieder hungrig?",
    answers: ["Nicht müde", "Nicht hungrig", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_070",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in Schwarz-Weiß oder in Stille einen Film ansehen?",
    answers: ["Schwarz-Weiß", "Stille", "Normal", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_071",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Haustier, das fliegt, oder eines, das spricht?",
    answers: ["Fliegt", "Spricht", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_072",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer pünktlich oder immer überraschend sein?",
    answers: ["Pünktlich", "Überraschend", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_073",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher die Weltkarte auswendig oder alle Hauptstädte kennen?",
    answers: ["Karte", "Hauptstädte", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_074",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr nur Lachen oder ein Jahr nur Nachdenken?",
    answers: ["Lachen", "Nachdenken", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_075",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher im Zelt bei Freunden oder allein im Hotel?",
    answers: ["Zelt/Freunde", "Hotel allein", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_076",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer die beste Ausrede oder immer die beste Idee haben?",
    answers: ["Ausrede", "Idee", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_077",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher fliegen ohne Angst oder tauchen ohne Angst?",
    answers: ["Fliegen", "Tauchen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_078",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder streiten oder nie wieder bereuen?",
    answers: ["Kein Streit", "Kein Bereuen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_079",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein magisches Buch oder ein magisches Instrument?",
    answers: ["Buch", "Instrument", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_080",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer den Sonnenplatz oder immer den Schattenplatz?",
    answers: ["Sonne", "Schatten", "Wechsel", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_081",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Tag ohne Worte oder ein Tag ohne Bilder?",
    answers: ["Ohne Worte", "Ohne Bilder", "Beides hart", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_082",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher Superheld mit unsichtbarer Kraft oder mit lauter Kraft?",
    answers: ["Unsichtbar", "Laut", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_083",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer Tee oder immer Kaffee (wenn nur eines)?",
    answers: ["Tee", "Kaffee", "Wasser", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_084",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher die Nacht zum Tag oder den Tag zur Nacht machen können?",
    answers: ["Nacht zum Tag", "Tag zur Nacht", "Normal", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_085",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr reisen oder ein Jahr bauen/kreativ sein?",
    answers: ["Reisen", "Bauen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_086",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer die Wahrheit über dich oder über andere wissen?",
    answers: ["Über dich", "Über andere", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_087",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein unsichtbares Fahrrad oder ein sprechendes Auto?",
    answers: ["Fahrrad", "Auto", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_088",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder langweilig oder nie wieder gestresst sein?",
    answers: ["Nicht langweilig", "Nicht gestresst", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_089",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in den Bergen trainieren oder am Strand entspannen?",
    answers: ["Berge", "Strand", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_090",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein magischer Schlüssel oder eine magische Karte?",
    answers: ["Schlüssel", "Karte", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_091",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer gewinnen im Sport oder immer gewinnen in Quizzen?",
    answers: ["Sport", "Quiz", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_092",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Tag als Lehrer oder ein Tag als Schüler nochmal?",
    answers: ["Lehrer", "Schüler", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_093",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher die Sterne berühren oder den Meeresgrund sehen können?",
    answers: ["Sterne", "Meeresgrund", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_094",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer improvisieren oder immer planen?",
    answers: ["Improvisieren", "Planen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_095",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr nur Podcasts oder ein Jahr nur Musik?",
    answers: ["Podcasts", "Musik", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_096",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Freund der Tiere oder ein Freund der Technik sein?",
    answers: ["Tiere", "Technik", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_097",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher nie wieder lügen hören oder nie wieder Lügen erzählen?",
    answers: ["Nicht hören", "Nicht erzählen", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_098",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein magisches Fenster oder eine magische Tür?",
    answers: ["Fenster", "Tür", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_099",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher immer den ersten Schritt oder immer den letzten Schritt machen?",
    answers: ["Erster", "Letzter", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_100",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher in Farbe träumen oder in Musik träumen?",
    answers: ["Farbe", "Musik", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spaßfrage."
  },
  {
    id: "wue_ext_101",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher ein Jahr ohne Spiegel oder ein Jahr ohne Fotos?",
    answers: ["Kein Spiegel", "Keine Fotos", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  },
  {
    id: "wue_ext_102",
    category: "spass_wuerdest_du",
    area: "spass",
    subject: "spass",
    question: "Würdest du eher Superfocus oder Superspaß als Kraft haben?",
    answers: ["Focus", "Spaß", "Beides", "Keins"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Geschmackssache."
  }
];

if (typeof window !== "undefined") window.SPASS_WUERDEST_DU_QUESTIONS = SPASS_WUERDEST_DU_QUESTIONS;
