const K2_DEUTSCH_QUESTIONS = [
  // ================================================================
  // 1. NOMEN & MEHRZAHL (25 Fragen)
  // ================================================================
  {
    id: "q2_d_001",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort ist ein Nomen (Namenwort)?",
    answers: ["laufen", "grün", "Baum", "schnell"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Baum ist ein Nomen – man sagt 'der Baum' und schreibt es groß."
  },
  {
    id: "q2_d_002",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort schreibt man groß?",
    answers: ["rennt", "schnell", "bunt", "Hund"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Hund ist ein Nomen und wird großgeschrieben."
  },
  {
    id: "q2_d_003",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Haus'?",
    answers: ["Häusern", "Häuser", "Hausen", "Häuse"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Mehrzahl von Haus ist Häuser."
  },
  {
    id: "q2_d_004",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches dieser Wörter ist ein Nomen (Namenwort) und wird großgeschrieben?",
    answers: ["spazierengehen", "unglaublich", "Fensterscheibe", "vorsichtig"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Fensterscheibe' ist ein Nomen (die Fensterscheibe) und wird großgeschrieben."
  },
  {
    id: "q2_d_005",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie lautet die richtige Mehrzahl von dem Wort 'Baum'?",
    answers: ["Baume", "Bäume", "Beume", "Bäumen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus dem 'au' in Baum wird in der Mehrzahl der Umlaut 'äu' (die Bäume)."
  },
  {
    id: "q2_d_006",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Aus welchen zwei Wörtern setzt sich das Wort 'Sonnenschirm' zusammen?",
    answers: ["Sonn und Schirm", "Sonne und Schirm", "Sonne und Schein", "Sommer und Schirm"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Sonne + Schirm = Sonnenschirm."
  },
  {
    id: "q2_d_007",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Artikel passt zu 'Kindergarten'?",
    answers: ["Einige", "Das", "Der", "Die"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Es heißt: der Kindergarten."
  },
  {
    id: "q2_d_008",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie lautet die Mehrzahl von 'Hand'?",
    answers: ["Hände", "Hander", "Handen", "Händen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus 'a' wird in der Mehrzahl 'ä': die Hände."
  },
  {
    id: "q2_d_009",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher bestimmter Artikel gehört zu 'Katze'?",
    answers: ["Die", "Ein", "Das", "Der"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es heißt: die Katze."
  },
  {
    id: "q2_d_010",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher bestimmter Artikel gehört zu 'Buch'?",
    answers: ["Eine", "Die", "Der", "Das"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Es heißt: das Buch."
  },
  {
    id: "q2_d_011",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Buch'?",
    answers: ["Büche", "Buchen", "Büchern", "Bücher"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Mehrzahl lautet: die Bücher."
  },
  {
    id: "q2_d_012",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Maus'?",
    answers: ["Mäusen", "Mäusern", "Mausen", "Mäuse"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus 'au' wird 'äu': die Mäuse."
  },
  {
    id: "q2_d_013",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Apfel'?",
    answers: ["Äpfel", "Äpfeln", "Apfeln", "Apfels"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus 'A' wird 'Ä': die Äpfel."
  },
  {
    id: "q2_d_014",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Tasse'?",
    answers: ["Tassen", "Tasseln", "Tasse", "Tässer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mehrere Exemplare nennt man: die Tassen."
  },
  {
    id: "q2_d_015",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Aus welchen zwei Wörtern besteht 'Haustür'?",
    answers: ["Haus und Tor", "Haus und Fenster", "Heim und Tür", "Haus und Tür"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Haus + Tür = Haustür."
  },
  {
    id: "q2_d_016",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Aus welchen zwei Wörtern besteht 'Zahnbürste'?",
    answers: ["Zahn und Bürste", "Zähne und Bürste", "Zaun und Bürste", "Zahn und Kamm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zahn + Bürste = Zahnbürste."
  },
  {
    id: "q2_d_017",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort verwendet man als unbestimmten Artikel für 'Hund'?",
    answers: ["einen Hund", "eines Hund", "ein Hund", "eine Hund"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Unbestimmt heißt es: ein Hund (der Hund)."
  },
  {
    id: "q2_d_018",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher unbestimmte Artikel passt zu 'Katze'?",
    answers: ["einer Katze", "eine Katze", "ein Katze", "einen Katze"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Es heißt: eine Katze (die Katze)."
  },
  {
    id: "q2_d_019",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Finde das Nomen im Satz: 'Der kleine Junge rennt.'",
    answers: ["rennt", "kleine", "Junge", "Der"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "'Junge' ist das Nomen (der Junge) und wird großgeschrieben."
  },
  {
    id: "q2_d_020",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Finde das Nomen im Satz: 'Das rote Auto bremst.'",
    answers: ["bremst", "Das", "rote", "Auto"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'Auto' ist das Nomen (das Auto)."
  },
  {
    id: "q2_d_021",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Vogel'?",
    answers: ["Vögel", "Vögels", "Vogeler", "Vogeln"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In der Mehrzahl wird aus 'o' der Umlaut 'ö': die Vögel."
  },
  {
    id: "q2_d_022",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist die Mehrzahl von 'Fuß'?",
    answers: ["Fußen", "Füßer", "Füße", "Füßen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Aus 'u' wird 'ü': die Füße."
  },
  {
    id: "q2_d_023",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort ist KEIN Nomen?",
    answers: ["Schrank", "schnell", "Stuhl", "Tisch"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'schnell' beschreibt eine Eigenschaft (Adjektiv), die anderen Wörter sind Nomen."
  },
{
  id: "q2_d_024",
  category: "k2_deutsch",
  topic: "nomen",
  area: "schule",
  grade: 2,
  subject: "deutsch",
  question: "Wie nennt man Nomen auch noch?",
  answers: ["Namenwörter", "Bindewörter", "Tunwörter", "Wie-Wörter"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "Nomen sind Namenwörter. Sie bezeichnen Lebewesen, Pflanzen und Dinge."
},
  {
    id: "q2_d_025",
    category: "k2_deutsch",
    topic: "nomen",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Aus welchen zwei Wörtern besteht das Nomen 'Winterjacke'?",
    answers: ["Schnee und Jacke", "Winter und Mantel", "Winter und Jacke", "Wind und Jacke"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Winter + Jacke = Winterjacke."
  },

  // ================================================================
  // 2. VERBEN & ADJEKTIVE (25 Fragen)
  // ================================================================
  {
    id: "q2_d_026",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'hell'?",
    answers: ["laut", "schnell", "dunkel", "warm"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Hell und dunkel sind Gegenteile."
  },
  {
    id: "q2_d_027",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'klein'?",
    answers: ["schnell", "laut", "leise", "groß"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Klein und groß sind Gegenteile."
  },
  {
    id: "q2_d_028",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort ist ein Verb (Tunwort)?",
    answers: ["schön", "Schule", "Hund", "laufen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Verben beschreiben, was jemand tut (z. B. laufen, hüpfen, lesen)."
  },
  {
    id: "q2_d_029",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort ist ein Adjektiv (Wie-Wort)?",
    answers: ["springen", "schnell", "Haus", "Katze"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Adjektive sagen uns, WIE etwas ist (z. B. schnell, leise, bunt)."
  },
  {
    id: "q2_d_030",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'laut'?",
    answers: ["schwer", "hell", "leise", "kalt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Gegenteil von laut ist leise."
  },
  {
    id: "q2_d_031",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'schwer'?",
    answers: ["stabil", "kräftig", "gewichtig", "leicht"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Schwer und leicht sind Gegenteile."
  },
  {
    id: "q2_d_032",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'kalt'?",
    answers: ["trocken", "nass", "warm", "rot"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Kalt und warm sind Gegenteile."
  },
  {
    id: "q2_d_033",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'alt'?",
    answers: ["groß", "leise", "jung", "schnell"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Gegenteil von alt bei Personen ist jung."
  },
  {
    id: "q2_d_034",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'nass'?",
    answers: ["schmutzig", "eiskalt", "trocken", "glitschig"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Wenn etwas nicht nass ist, ist es trocken."
  },
  {
    id: "q2_d_035",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Ergänze das Verb richtig: 'Ich renne, du ___.'",
    answers: ["renne", "rennen", "rennt", "rennst"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei 'du' hängen wir an den Wortstamm '-st' an: du rennst."
  },
  {
    id: "q2_d_036",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Ergänze das Verb: 'Er ___ einen bunten Ball.'",
    answers: ["spiele", "spielt", "spielen", "spielst"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei 'er/sie/es' lautet die Endung '-t': er spielt."
  },
  {
    id: "q2_d_037",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Ergänze das Verb: 'Wir ___ heute lange.'",
    answers: ["schlafe", "schläfst", "schlafen", "schläft"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei 'wir' steht meist die Grundform mit der Endung '-en': wir schlafen."
  },
  {
    id: "q2_d_038",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie nennt man die Grundform eines Verbs (z. B. 'lachen')?",
    answers: ["Adjektiv in der Praxis", "Nomen in der Praxis", "Mehrzahl in der Praxis", "Grundform / Infinitiv"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Grundform nennt man Infinitiv (z. B. lachen, rennen, lesen)."
  },
  {
    id: "q2_d_039",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie heißt die Grundform von 'er fliegt'?",
    answers: ["fliegen", "fliegst", "geflogen", "flug"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Grundform des Verbs lautet 'fliegen'."
  },
  {
    id: "q2_d_040",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie heißt die Grundform von 'sie liest'?",
    answers: ["lesen", "lese", "liest", "gelesen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Grundform lautet 'lesen'."
  },
  {
    id: "q2_d_041",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'hart'?",
    answers: ["schwer", "klein", "weich", "kalt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Hart und weich sind Gegenteile."
  },
  {
    id: "q2_d_042",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'schnell'?",
    answers: ["vorsichtig", "neugierig", "langsam", "freundlich"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Schnell und langsam sind Gegenteile."
  },
  {
    id: "q2_d_043",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort ist ein Verb?",
    answers: ["Fenster", "Schule", "orange", "lachen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'lachen' ist etwas, das man tut (Tunwort / Verb)."
  },
  {
    id: "q2_d_044",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Wort ist ein Adjektiv?",
    answers: ["Teller", "Apfel", "essen", "lecker"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'lecker' verrät uns, WIE der Apfel schmeckt (Adjektiv)."
  },
  {
    id: "q2_d_045",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'traurig'?",
    answers: ["wütend und sehr gereizt", "fröhlich / glücklich", "müde und ganz erschöpft", "krank und etwas schwach"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Traurig und fröhlich sind Gegenteile."
  },
  {
    id: "q2_d_046",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was ist das Gegenteil von 'voll'?",
    answers: ["klein", "leicht", "leer", "wenig"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Voll und leer sind Gegenteile."
  },
  {
    id: "q2_d_047",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Ergänze das Verb: 'Du ___ ein tolles Buch.'",
    answers: ["liest", "lese", "liesten", "lesen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es heißt: du liest."
  },
  {
    id: "q2_d_048",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie schreibt man Verben mitten im Satz normalerweise?",
    answers: ["mit Ausrufezeichen", "klein", "immer doppelt", "groß"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Verben und Adjektive schreibt man im Satz klein."
  },
  {
    id: "q2_d_049",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Adjektiv passt am besten zu Speiseeis?",
    answers: ["eckig", "kalt", "heiß", "trocken"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Eis ist kalt."
  },
  {
    id: "q2_d_050",
    category: "k2_deutsch",
    topic: "verben_adjektive",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was fragt man, um ein Adjektiv im Satz zu finden?",
    answers: ["Was tut jemand?", "Wo ist es?", "Wie ist etwas?", "Wer oder was?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Adjektive antworten auf die Frage: Wie ist etwas?"
  },

  // ================================================================
  // 3. SATZARTEN & SATZZEICHEN (25 Fragen)
  // ================================================================
  {
    id: "q2_d_051",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Satz ist richtig geschrieben?",
    answers: ["Ich gehe nach hause","Ich gehe nach Haus","Ich gehe nach Hause.","Ich gehe nach Hausse."],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Satzanfang groß, Nomen groß, Punkt am Ende."
  },
  {
    id: "q2_d_052",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Schreibweise ist richtig: der Hund spielt?",
    answers: ["der Hund spilt.","der Hund spielt","Der Hund spield","Der Hund spielt."],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Satzanfang groß, Nomen groß, Punkt am Ende."
  },
  {
    id: "q2_d_053",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Satzzeichen gehört am Ende an diesen Satz: 'Kannst du mir helfen'?",
    answers: ["Fragezeichen (?)", "Ausrufezeichen (!)", "Punkt (.)", "Komma (,)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es handelt sich um eine Frage, deshalb steht am Ende ein Fragezeichen."
  },
  {
    id: "q2_d_054",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Satzzeichen steht nach einem Ausruf wie 'Stopp, bleib stehen'?",
    answers: ["Fragezeichen (?)", "Auslassungspunkte (...)", "Ausrufezeichen (!)", "Semikolon (;)"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach Befehlen und Rufen steht ein Ausrufezeichen (!)."
  },
  {
    id: "q2_d_055",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie wird das allererste Wort in einem Satz IMMER geschrieben?",
    answers: ["Groß", "Rot", "In Klammern", "Klein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Satzanfang wird immer mit einem Großbuchstaben begonnen."
  },
  {
    id: "q2_d_056",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Satzzeichen steht am Ende eines ganz normalen Aussagesatzes?",
    answers: ["Fragezeichen (?)", "Ausrufezeichen (!)", "Komma (,)", "Punkt (.)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Aussagesatz endet mit einem einfachen Punkt."
  },
  {
    id: "q2_d_057",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher dieser Sätze ist ein Fragesatz?",
    answers: ["Ich heiße Paul.", "Wie alt bist du?", "Komm jetzt her!", "Die Sonne scheint."],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Wie alt bist du?' verlangt eine Antwort und ist daher eine Frage."
  },
  {
    id: "q2_d_058",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher dieser Sätze ist ein Ausrufe- oder Befehlssatz?",
    answers: ["Pass gut auf!", "Ich mag Eis.", "Wo wohnst du?", "Ein Vogel fliegt."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Pass gut auf!' fordert zu etwas auf und endet mit einem Ausrufezeichen."
  },
  {
    id: "q2_d_059",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher dieser Sätze ist ein Aussagesatz?",
    answers: ["Die Lauf schneller! zur Auswahl", "Die Katze schläft auf dem Sofa.", "Die Wie heißt du? in der Praxis", "Die Kommst du mit? in der Praxis"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Die Katze schläft auf dem Sofa.' erzählt eine Information (Aussage)."
  },
  {
    id: "q2_d_060",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Korrigiere den Satz: 'die sonne scheint.'",
    answers: ["Die sonne scheind.","Die Sonne scheint","Die Sonne scheints.","Die Sonne scheint."],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Satzanfang 'Die' groß, Nomen 'Sonne' groß und Punkt am Ende."
  },
  {
    id: "q2_d_061",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Satzzeichen fehlt hier: 'Wo ist mein Ball__'",
    answers: ["Doppelpunkt (:)", "Fragezeichen (?)", "Punkt (.)", "Ausrufezeichen (!)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Es ist eine Frage ('Wo...'), deshalb fehlt das Fragezeichen."
  },
  {
    id: "q2_d_062",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Fragewort passt in die Lücke: '___ alt bist du?'",
    answers: ["Warum", "Wo", "Wie", "Wer"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die passende Frage heißt: Wie alt bist du?"
  },
  {
    id: "q2_d_063",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Fragewort passt: '___ wohnst du?'",
    answers: ["Was", "Wer", "Wo", "Wie"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Wenn man nach einem Ort fragt, nutzt man 'Wo'."
  },
  {
    id: "q2_d_064",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Fragewort passt: '___ hast du in der Tasche?'",
    answers: ["Wie", "Wer", "Wo", "Was"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Wenn man nach Dingen fragt, nutzt man 'Was'."
  },
  {
    id: "q2_d_065",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Fragewort passt: '___ kommt heute zu Besuch?'",
    answers: ["Wie", "Wer", "Wo", "Was"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Fragt man nach einer Person, verwendet man 'Wer'."
  },
  {
    id: "q2_d_066",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Bringe die Satzteile in die richtige Reihenfolge: 'spielt / Der / Ball. / Junge'",
    answers: ["Der spielt Junge Ball.", "Der Junge spielt Ball.", "Ball spielt Der Junge.", "Junge spielt Ball Der."],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der korrekte Satz lautet: Der Junge spielt Ball."
  },
  {
    id: "q2_d_067",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Bringe die Satzteile in die richtige Reihenfolge: 'fliegt / Vogel / Der / hoch.'",
    answers: ["Hoch fliegt Vogel Der.", "Der Vogel fliegt hoch.", "Vogel fliegt Der hoch.", "Der fliegt hoch Vogel."],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Richtig heisst es: Der Vogel fliegt hoch."
  },
  {
    id: "q2_d_068",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Satzzeichen gehört ans Ende von 'Hurra, wir haben gewonnen__'",
    answers: ["Doppelpunkt (:)", "Auslassungspunkte (...)", "Ausrufezeichen (!)", "Fragezeichen (?)"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei Freude und Rufen steht ein Ausrufezeichen (!)."
  },
  {
    id: "q2_d_069",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches Fragewort fragt nach einer Zeit: '___ beginnt die Schule?'",
    answers: ["Warum", "Wann", "Wieso", "Wohin"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach der Uhrzeit oder dem Zeitpunkt fragt man mit 'Wann'."
  },
  {
    id: "q2_d_070",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Satz ist grammatikalisch richtig?",
    answers: ["Kuchen der Oma backt lecker.", "Oma backt einen leckeren Kuchen.", "Backt Oma Kuchen leckeren einen.", "Oma einen Kuchen backt lecker."],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der erste Satz bildet die einzig richtige Satzstruktur."
  },
  {
    id: "q2_d_071",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Satz drückt eine Frage aus?",
    answers: ["Lauf ganz schnell zum Bus!", "Heute ist wirklich schönes Wetter.", "Ich spiele sehr gerne draußen.", "Kommst du heute mit mir spielen?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Kommst du heute mit mir spielen?' ist eine Frage."
  },
  {
    id: "q2_d_072",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Satz ist eine Aufforderung?",
    answers: ["Ich habe mein Zimmer aufgeräumt.", "Ist dein Zimmer sauber? im Alltag", "Räum bitte sofort dein Zimmer auf!", "Das Zimmer ist groß. in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Satz fordert jemanden auf, das Zimmer aufzuräumen."
  },
  {
    id: "q2_d_073",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Was gehört ans Ende dieses Satzes: 'Wir fahren im Sommer an die See__'",
    answers: ["Fragezeichen (?)", "Ausrufezeichen (!)", "Doppelpunkt (:)", "Punkt (.)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das ist eine normale Aussage und bekommt einen Punkt."
  },
  {
    id: "q2_d_074",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Buchstabe muss am Satzanfang stehen?",
    answers: ["Ein Kleinbuchstabe", "Ein Umlaut", "Eine Zahl", "Ein Großbuchstabe"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Man beginnt jeden Satz mit einem Großbuchstaben."
  },
  {
    id: "q2_d_075",
    category: "k2_deutsch",
    topic: "satzarten",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Warum steht am Ende von 'Gibt es heute Mittag Suppe?' ein Fragezeichen?",
    answers: ["Weil der Satz etwas wissen möchte (Frage)", "Weil das Wort Suppe groß ist in der Praxis", "Weil es eine Aussage ist in der Praxis", "Weil jemand schreit in der Praxis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fragen verlangen Antworten, deshalb steht am Ende ein Fragezeichen."
  },

  // ================================================================
  // 4. ABC & RECHTSCHREIBUNG (25 Fragen)
  // ================================================================
  {
    id: "q2_d_076",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Schreibweise ist richtig?",
    answers: ["Sone", "Zonne", "Sonne", "Sonnne"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Sonne schreibt man mit doppeltem n."
  },
  {
    id: "q2_d_077",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie viele Silben hat 'Schmet-ter-ling'?",
    answers: ["2", "4", "3", "5"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Schmet-ter-ling hat drei Silben."
  },
  {
    id: "q2_d_078",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie viele Silben hat 'Ap-fel'?",
    answers: ["3", "2", "4", "1"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ap-fel – das sind zwei Silben."
  },
  {
    id: "q2_d_079",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welches dieser Wörter steht im Wörterbuch an erster Stelle?",
    answers: ["Apfel", "Citrone", "Dattel", "Birne"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das ABC beginnt mit A, weshalb 'Apfel' zuerst kommt."
  },
  {
    id: "q2_d_080",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Buchstabe kommt im Alphabet direkt nach dem B?",
    answers: ["D", "E", "A", "C"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Reihenfolge ist: A, B, C."
  },
  {
    id: "q2_d_081",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Buchstabe steht im Alphabet direkt vor dem Z?",
    answers: ["V", "W", "X", "Y"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Am Ende des Alphabets heißt es: X, Y, Z."
  },
  {
    id: "q2_d_082",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Doppel-Konsonanten fehlen bei 'So__er' (Sommer)?",
    answers: ["mm", "tt", "pp", "nn"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sommer schreibt man mit doppel-m (mm)."
  },
  {
    id: "q2_d_083",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Doppel-Konsonanten fehlen bei 'Be__' (Bett)?",
    answers: ["dd", "tt", "ll", "pp"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bett wird mit doppeltem t geschrieben."
  },
  {
    id: "q2_d_084",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Buchstabe steht am Ende von 'Hun_'? Verlängere das Wort: 'Hunde'.",
    answers: ["g", "t", "k", "d"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Man hört am Ende ein 't', aber weil die Mehrzahl 'Hunde' heißt, schreibt man 'd'."
  },
  {
    id: "q2_d_085",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Buchstabe steht am Ende von 'Han_'? Verlängere: 'Hände'.",
    answers: ["b", "p", "d", "t"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Durch Verlängern (Hände) hört man deutlich das 'd'."
  },
{
  id: "q2_d_086",
  category: "k2_deutsch",
  topic: "abc_rechtschreibung",
  area: "schule",
  grade: 2,
  subject: "deutsch",
  question: "Welcher Buchstabe steht am Ende von 'Ta_'? Verlängere: 'Tage'.",
  answers: ["k", "ch", "g", "ck"],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "Die Mehrzahl 'Tage' zeigt, dass 'Tag' mit 'g' geschrieben wird."
},
  {
    id: "q2_d_087",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie schreibt man 'Sch_ne' (Schiene / langes i)?",
    answers: ["ih", "ie", "iehh", "i"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das lange gesprochene 'i' schreibt man meistens als 'ie'."
  },
  {
    id: "q2_d_088",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Buchstaben fehlen bei 'Ka__e' (Katze)?",
    answers: ["z", "zz", "ts", "tz"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach einem kurzen Vokal schreibt man 'tz' (Katze)."
  },
  {
    id: "q2_d_089",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Buchstaben fehlen bei 'Schne__e' (Schnecke)?",
    answers: ["k", "ck", "kk", "gk"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach einem kurzen Vokal schreibt man 'ck' statt doppel-k."
  },
  {
    id: "q2_d_090",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Sortiere nach dem Alphabet: Welches Wort kommt als ERSTES im Wörterbuch?",
    answers: ["Butter", "Biene", "Brot", "Ball"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Alle fangen mit B an. Der zweite Buchstabe 'a' bei 'Ball' kommt zuerst."
  },
  {
    id: "q2_d_091",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie trennt man das Wort 'Katze' richtig in Silben?",
    answers: ["Katz-e", "Kat-ze", "K-atze", "Ka-tze"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die richtige Silbentrennung lautet Kat-ze."
  },
  {
    id: "q2_d_092",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie trennt man das Wort 'Wasser' richtig am Zeilenende?",
    answers: ["W-asser", "Wass-er", "Wa-sser", "Was-ser"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Doppel-Konsonanten werden in der Mitte getrennt: Was-ser."
  },
  {
    id: "q2_d_093",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Buchstabe ist stumm bei 'Za_n' (Zahn)?",
    answers: ["h", "a", "n", "e"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Dehnungs-h hört man nicht direkt, es macht das 'a' lang: Zahn."
  },
  {
    id: "q2_d_094",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Buchstaben schreibt man am Anfang von 'S_ern' (Stern)?",
    answers: ["Scht", "St", "S", "Sch"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Man hört zwar 'Scht', schreibt am Wortanfang aber 'St'."
  },
  {
    id: "q2_d_095",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Buchstaben schreibt man am Anfang von 'S_iel' (Spiel)?",
    answers: ["Sch", "S", "Sp", "Schp"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Man hört 'Schp', schreibt am Wortanfang aber 'Sp'."
  },
  {
    id: "q2_d_096",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welcher Königsbuchstabe (Vokal) fehlt in 'F_sch'?",
    answers: ["a", "i", "e", "u"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Wort heißt Fisch mit 'i'."
  },
  {
    id: "q2_d_097",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche Schreibweise mit doppeltem Konsonanten ist RICHTIG?",
    answers: ["Zrennen", "Rennnen", "Renen", "Rennen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Verb 'rennen' wird mit doppel-n geschrieben."
  },
  {
    id: "q2_d_098",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Wie viele Buchstaben hat das deutsche Alphabet (ohne Umlaute)?",
    answers: ["24 Buchstaben", "26 Buchstaben", "20 Buchstaben", "30 Buchstaben"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Alphabet von A bis Z besteht aus genau 26 Buchstaben."
  },
  {
    id: "q2_d_099",
    category: "k2_deutsch",
    topic: "abc_rechtschreibung",
    area: "schule",
    grade: 2,
    subject: "deutsch",
    question: "Welche drei Buchstaben nennt man 'Umlaute'?",
    answers: ["A, E, I", "Ä, Ö, Ü", "B, C, D", "O, U, Y"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die drei Umlaute im Deutschen sind Ä, Ö und Ü."
  },
{
  id: "q2_d_100",
  category: "k2_deutsch",
  topic: "abc_rechtschreibung",
  area: "schule",
  grade: 2,
  subject: "deutsch",
  question: "Wie trennt man das Wort 'Ei-s'?",
  answers: ["Man trennt es so: E-is, ganz einfach.", "Gar nicht, es hat nur 1 Silbe!", "Es geht so: Ei-i-s, mit drei Silben.", "Man trennt so: Ei-s, mit zwei Silben."],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "Wörter mit nur einer Silbe wie 'Eis', 'Haus' oder 'Baum' werden nicht getrennt."
}
];