const K2_ENGLISCH_QUESTIONS = [
  // ================================================================
  // 1. BEGRÜSSUNG & REDEWENDUNGEN (greetings)
  // ================================================================
  {
    id: "q2_e_001",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'Hello' auf Deutsch?",
    answers: ["Danke", "Tschüss", "Guten Morgen", "Hallo"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Hello' heißt auf Deutsch 'Hallo'."
  },
  {
    id: "q2_e_002",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet 'Goodbye'?",
    answers: ["Guten Morgen, wie geht's?", "Bitte und danke schön", "Herzlich willkommen hier", "Auf Wiedersehen / Tschüss"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Goodbye' (oder kurz 'Bye') bedeutet Auf Wiedersehen oder Tschüss."
  },
  {
    id: "q2_e_003",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Wie sagt man auf Englisch 'Danke'?",
    answers: ["Hello", "Thank you", "Goodbye", "Excuse me"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Thank you' bedeutet Danke."
  },
  {
    id: "q2_e_004",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Wie sagt man morgens auf Englisch 'Guten Morgen'?",
    answers: ["Good night", "Good morning", "Goodbye", "Good evening"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Good morning' ist der englische Gruß am Morgen."
  },
  {
    id: "q2_e_005",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was antwortest du, wenn jemand fragt: 'How are you?' (Wie geht es dir?)",
    answers: ["My name is Anna.", "I'm fine, thank you!", "I am seven years old.", "See you later, bye!"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "'I'm fine, thank you!' heißt: Mir geht es gut, danke!"
  },
  {
    id: "q2_e_006",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet 'Please' auf Deutsch?",
    answers: ["Bitte", "Danke", "Ja", "Entschuldigung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Please' bedeutet Bitte."
  },
  {
    id: "q2_e_007",
    category: "k2_englisch",
    topic: "greetings",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Wie fragt man auf Englisch nach dem Namen ('Wie heißt du?')?",
    answers: ["How old are you today?", "Where do you live now?", "Do you like your name?", "What's your name?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'What's your name?' bedeutet: Wie heißt du?"
  },

  // ================================================================
  // 2. FARBEN & ZAHLEN (colors_numbers)
  // ================================================================
  {
    id: "q2_e_008",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Farbe ist 'red'?",
    answers: ["Gelb", "Grün", "Rot", "Blau"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Red' ist die englische Bezeichnung für Rot."
  },
  {
    id: "q2_e_009",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Farbe ist 'blue'?",
    answers: ["Blau", "Weiß", "Grün", "Schwarz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Blue' heißt Blau auf Deutsch."
  },
  {
    id: "q2_e_010",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Farbe hat die Sonne auf Englisch: 'yellow'?",
    answers: ["Rot", "Gelb", "Lila", "Braun"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Yellow' bedeutet Gelb."
  },
  {
    id: "q2_e_011",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'green'?",
    answers: ["Grün", "Gelb", "Grau", "Blau"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Green' ist Grün (wie das Gras)."
  },
  {
    id: "q2_e_012",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Zahl ist 'one'?",
    answers: ["3", "1", "4", "2"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'One' ist die Zahl 1."
  },
  {
    id: "q2_e_013",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Zahl ist 'three'?",
    answers: ["10", "2", "3", "4"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Three' ist die Zahl 3."
  },
  {
    id: "q2_e_014",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Zahl ist 'five'?",
    answers: ["4", "15", "6", "5"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Five' ist die Zahl 5."
  },
  {
    id: "q2_e_015",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welche Zahl ist 'ten'?",
    answers: ["10", "20", "2", "12"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Ten' ist die Zahl 10."
  },
  {
    id: "q2_e_016",
    category: "k2_englisch",
    topic: "colors_numbers",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'black'?",
    answers: ["Braun", "Violett", "Türkis", "Schwarz"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Black' bedeutet Schwarz."
  },

  // ================================================================
  // 3. TIERE (animals)
  // ================================================================
  {
    id: "q2_e_017",
    category: "k2_englisch",
    topic: "animals",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was ist ein 'dog'?",
    answers: ["Katze", "Maus", "Hund", "Vogel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Dog' heißt Hund auf Deutsch."
  },
  {
    id: "q2_e_018",
    category: "k2_englisch",
    topic: "animals",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was ist eine 'cat'?",
    answers: ["Kuh", "Pferd", "Hund", "Katze"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Cat' ist die Katze."
  },
  {
    id: "q2_e_019",
    category: "k2_englisch",
    topic: "animals",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was ist eine 'mouse'?",
    answers: ["Bär", "Maus", "Schaf", "Elefant"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Mouse' heißt Maus."
  },
  {
    id: "q2_e_020",
    category: "k2_englisch",
    topic: "animals",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Wie heißt 'Pferd' auf Englisch?",
    answers: ["Sheep", "Goat", "Mouse", "Horse"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Pferd heißt auf Englisch 'horse'."
  },
  {
    id: "q2_e_021",
    category: "k2_englisch",
    topic: "animals",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was für ein Tier ist ein 'monkey'?",
    answers: ["Tiger", "Fisch", "Löwe", "Affe"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Monkey' ist der Affe."
  },
  {
    id: "q2_e_022",
    category: "k2_englisch",
    topic: "animals",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Wie heißt 'Fisch' auf Englisch?",
    answers: ["Snake", "Frog", "Fish", "Bird"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Fish' heißt Fisch."
  },

  // ================================================================
  // 4. SCHULE, FAMILIE & KÖRPER (school_family)
  // ================================================================
  {
    id: "q2_e_023",
    category: "k2_englisch",
    topic: "school_family",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet 'mother' (oder kurz 'mum')?",
    answers: ["Oma", "Schwester", "Vater", "Mutter"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Mother' oder 'mum' heißt Mutter."
  },
  {
    id: "q2_e_024",
    category: "k2_englisch",
    topic: "school_family",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet 'father' (oder kurz 'dad')?",
    answers: ["Bruder", "Opa", "Vater", "Onkel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Father' oder 'dad' heißt Vater."
  },
  {
    id: "q2_e_025",
    category: "k2_englisch",
    topic: "school_family",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was ist ein 'pencil'?",
    answers: ["Schulranzen", "Bleistift", "Lineal", "Buch"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Pencil' heißt Bleistift."
  },
  {
    id: "q2_e_026",
    category: "k2_englisch",
    topic: "school_family",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was ist ein 'book'?",
    answers: ["Tisch", "Fenster", "Stuhl", "Buch"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Book' heißt Buch."
  },
  {
    id: "q2_e_027",
    category: "k2_englisch",
    topic: "school_family",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Welches Körperteil ist der 'head' im Lied 'Head, shoulders, knees and toes'?",
    answers: ["Nase", "Kopf", "Hand", "Fuß"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Head' bedeutet Kopf."
  },
  {
    id: "q2_e_028",
    category: "k2_englisch",
    topic: "school_family",
    area: "schule",
    grade: 2,
    subject: "englisch",
    question: "Was bedeutet 'hand' auf Deutsch?",
    answers: ["Arm", "Hand", "Bein", "Fuß"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Hand' wird auf Englisch fast genauso geschrieben und heißt Hand."
  },

  // ================================================================
// ZUSÄTZLICHE ENGLISCH-FRAGEN FÜR KLASSE 2
// ================================================================

// --- WEITERE TIERE (animals) ---
{
  id: "q2_e_029",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'elephant'?",
  answers: ["Giraffe", "Tiger", "Elefant", "Löwe"],
  correct: 2,
  difficulty: "leicht",
  points: 5,
  explanation: "'Elephant' heißt auf Deutsch Elefant."
},
{
  id: "q2_e_030",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'lion'?",
  answers: ["Löwe", "Schlange", "Vogel", "Affe"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "'Lion' ist der Löwe."
},
{
  id: "q2_e_031",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'tiger'?",
  answers: ["Hirsch", "Wolf", "Bär", "Tiger"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'Tiger' heißt auf Englisch tiger."
},
{
  id: "q2_e_032",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'bird'?",
  answers: ["Fisch", "Vogel", "Biene", "Schmetterling"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Bird' ist der Vogel."
},
{
  id: "q2_e_033",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'sheep'?",
  answers: ["Pferd", "Schaf", "Ziege", "Kuh"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Sheep' heißt Schaf."
},
{
  id: "q2_e_034",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'cow'?",
  answers: ["Huhn", "Kuh", "Schaf", "Schwein"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Cow' ist die Kuh."
},
{
  id: "q2_e_035",
  category: "k2_englisch",
  topic: "animals",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist ein 'pig'?",
  answers: ["Ziege", "Elefant", "Hase", "Schwein"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'Pig' heißt Schwein."
},

// --- WEITERE FARBEN (colors) ---
{
  id: "q2_e_036",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Farbe ist 'orange'?",
  answers: ["Violett", "Orange", "Türkis", "Braun"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Orange' heißt auf Deutsch Orange."
},
{
  id: "q2_e_037",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Farbe ist 'pink'?",
  answers: ["Pink / Rosa", "Blau / Grün", "Lila / Violett", "Rot / Orange"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "'Pink' bedeutet Rosa oder Pink."
},
{
  id: "q2_e_038",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Farbe ist 'brown'?",
  answers: ["Schwarz", "Grau", "Grün", "Braun"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'Brown' heißt Braun."
},
{
  id: "q2_e_039",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Farbe ist 'white'?",
  answers: ["Hellblau", "Schwarz", "Grau", "Weiß"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'White' bedeutet Weiß."
},
{
  id: "q2_e_040",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Farbe ist 'grey' (oder gray)?",
  answers: ["Dunkelblau", "Grau", "Braun", "Schwarz"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Grey' (AE: gray) bedeutet Grau."
},

// --- ZAHLEN BIS 20 (numbers 1-20) ---
{
  id: "q2_e_041",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'six'?",
  answers: ["8", "7", "5", "6"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'Six' ist die Zahl 6."
},
{
  id: "q2_e_042",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'seven'?",
  answers: ["9", "7", "8", "6"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Seven' ist die Zahl 7."
},
{
  id: "q2_e_043",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'eight'?",
  answers: ["6", "9", "8", "7"],
  correct: 2,
  difficulty: "leicht",
  points: 5,
  explanation: "'Eight' ist die Zahl 8."
},
{
  id: "q2_e_044",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'nine'?",
  answers: ["8", "9", "10", "7"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Nine' ist die Zahl 9."
},
{
  id: "q2_e_045",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'eleven'?",
  answers: ["11", "12", "1", "10"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "'Eleven' ist die Zahl 11."
},
{
  id: "q2_e_046",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'twelve'?",
  answers: ["12", "2", "11", "13"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "'Twelve' ist die Zahl 12."
},
{
  id: "q2_e_047",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'thirteen'?",
  answers: ["12", "3", "14", "13"],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "'Thirteen' ist die Zahl 13."
},
{
  id: "q2_e_048",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'fifteen'?",
  answers: ["16", "5", "14", "15"],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "'Fifteen' ist die Zahl 15."
},
{
  id: "q2_e_049",
  category: "k2_englisch",
  topic: "colors_numbers",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Welche Zahl ist 'twenty'?",
  answers: ["12", "20", "10", "2"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Twenty' ist die Zahl 20."
},

// --- WEITERE KÖRPERTEILE (body) ---
{
  id: "q2_e_050",
  category: "k2_englisch",
  topic: "school_family",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'eyes'?",
  answers: ["Augen", "Ohren", "Nase", "Mund"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "'Eyes' sind die Augen."
},
{
  id: "q2_e_051",
  category: "k2_englisch",
  topic: "school_family",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'ears'?",
  answers: ["Ohren", "Füße", "Hände", "Augen"],
  correct: 0,
  difficulty: "leicht",
  points: 5,
  explanation: "'Ears' sind die Ohren."
},
{
  id: "q2_e_052",
  category: "k2_englisch",
  topic: "school_family",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'nose'?",
  answers: ["Ohr", "Nase", "Auge", "Mund"],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "'Nose' ist die Nase."
},
{
  id: "q2_e_053",
  category: "k2_englisch",
  topic: "school_family",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'mouth'?",
  answers: ["Nase", "Ohr", "Mund", "Auge"],
  correct: 2,
  difficulty: "leicht",
  points: 5,
  explanation: "'Mouth' ist der Mund."
},
{
  id: "q2_e_054",
  category: "k2_englisch",
  topic: "school_family",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'feet'?",
  answers: ["Beine", "Hände", "Füße", "Arme"],
  correct: 2,
  difficulty: "leicht",
  points: 5,
  explanation: "'Feet' ist die Mehrzahl von 'foot' und bedeutet Füße."
},

// --- ERSTE SÄTZE / AUSDRÜCKE (simple sentences) ---
{
  id: "q2_e_055",
  category: "k2_englisch",
  topic: "greetings",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'I like apples.' auf Deutsch?",
  answers: ["Ich sehe Äpfel.", "Ich esse Äpfel.", "Ich mag Äpfel.", "Ich kaufe Äpfel."],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "'I like ...' bedeutet 'Ich mag ...'."
},
{
  id: "q2_e_056",
  category: "k2_englisch",
  topic: "greetings",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'I can swim.' auf Deutsch?",
  answers: ["Ich sehe schwimmen.", "Ich will schwimmen.", "Ich kann schwimmen.", "Ich mag schwimmen."],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "'I can ...' bedeutet 'Ich kann ...'."
},
{
  id: "q2_e_057",
  category: "k2_englisch",
  topic: "greetings",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'I have a cat.' auf Deutsch?",
  answers: ["Ich kaufe eine Katze.", "Ich habe eine Katze.", "Ich sehe eine Katze.", "Ich mag eine Katze."],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "'I have ...' bedeutet 'Ich habe ...'."
},
{
  id: "q2_e_058",
  category: "k2_englisch",
  topic: "greetings",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was ist die richtige englische Übersetzung für 'Ich bin 7 Jahre alt.'?",
  answers: ["I have 7 years old.", "I am 7 years old.", "I is 7 years old.", "Me is 7 years old."],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "'I am ... years old.' ist die korrekte englische Form."
},
{
  id: "q2_e_059",
  category: "k2_englisch",
  topic: "greetings",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'Good night!' auf Deutsch?",
  answers: ["Guten Morgen!", "Auf Wiedersehen!", "Guten Tag!", "Gute Nacht!"],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'Good night!' sagt man, wenn man ins Bett geht (Gute Nacht)."
},
{
  id: "q2_e_060",
  category: "k2_englisch",
  topic: "greetings",
  area: "schule",
  grade: 2,
  subject: "englisch",
  question: "Was bedeutet 'I'm sorry.' auf Deutsch?",
  answers: ["Hallo! im Alltag", "Danke schön.", "Bitte schön.", "Es tut mir leid."],
  correct: 3,
  difficulty: "leicht",
  points: 5,
  explanation: "'I'm sorry.' bedeutet 'Es tut mir leid' oder 'Entschuldigung'."
}
];