const K2_MATHE_QUESTIONS = [
  // ================================================================
  // 1. HUNDERTERRAUM & ZAHLEN (25 Fragen)
  // ================================================================
  {
    id: "q2_m_001",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl ist größer: 18 oder 14?",
    answers: ["18", "14", "Beide gleich", "Man kann es nicht sagen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "18 kommt später beim Zählen als 14, also ist 18 größer."
  },
  {
    id: "q2_m_002",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl liegt im Hunderterfeld genau zwischen 39 und 41?",
    answers: ["38", "42", "50", "40"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Beim Zählen im Hunderterraum kommt nach 39 die 40 und dann die 41."
  },
  {
    id: "q2_m_003",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist der Nachfolger der Zahl 89?",
    answers: ["90", "88", "91", "100"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt nach der 89 kommt die 90."
  },
  {
    id: "q2_m_004",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist der Vorgänger der Zahl 70?",
    answers: ["69", "71", "60", "80"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt vor der 70 steht die 69."
  },
  {
    id: "q2_m_005",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Aus wie vielen Zehnern und Einern besteht die Zahl 54?",
    answers: ["5 Zehner und 4 Einer", "4 Zehner und 5 Einer", "54 Zehner", "5 Einer und 4 Zehner"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "54 = 5 Zehner (50) + 4 Einer."
  },
  {
    id: "q2_m_006",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was sind die Nachbarzehner von 43?",
    answers: ["40 und 50", "30 und 40", "42 und 44", "40 und 60"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Zehner davor ist 40, der Zehner danach 50."
  },
  {
    id: "q2_m_007",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was sind die Nachbarzehner von 76?",
    answers: ["70 und 80", "60 und 70", "75 und 77", "70 und 90"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der reine Zehner vor 76 ist 70, danach kommt 80."
  },
  {
    id: "q2_m_008",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl hat 8 Zehner und 3 Einer?",
    answers: ["83", "38", "80", "30"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "8 Zehner (80) + 3 Einer (3) = 83."
  },
  {
    id: "q2_m_009",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl hat 6 Zehner und 0 Einer?",
    answers: ["60", "6", "66", "10"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "6 Zehner entspricht der Zahl 60."
  },
  {
    id: "q2_m_010",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welches Zeichen passt: 67 __ 76?",
    answers: ["<", ">", "=", "+"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "67 ist kleiner als 76 (67 < 76)."
  },
  {
    id: "q2_m_011",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welches Zeichen passt: 91 __ 89?",
    answers: [">", "<", "=", "-"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "91 ist größer als 89 (91 > 89)."
  },
  {
    id: "q2_m_012",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Zähle in 10er-Schritten: 10, 20, 30, __, 50. Welche Zahl fehlt?",
    answers: ["40", "35", "45", "60"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In 10er-Schritten folgt auf 30 die 40."
  },
  {
    id: "q2_m_013",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Zähle in 5er-Schritten: 15, 20, 25, __, 35",
    answers: ["30", "26", "28", "40"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Immer +5: Nach 25 kommt 30."
  },
  {
    id: "q2_m_014",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl liegt genau in der Mitte zwischen 0 und 100?",
    answers: ["50", "40", "60", "25"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Hälfte von 100 ist 50."
  },
  {
    id: "q2_m_015",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie schreibt man die Zahl 'vierundachtzig' als Ziffer?",
    answers: ["84", "48", "804", "408"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Deutschen sprechen wir erst die Einer (vier) und dann die Zehner (achtzig) -> 84."
  },
  {
    id: "q2_m_016",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie schreibt man 'siebenundsiebzig'?",
    answers: ["77", "707", "7", "717"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 Zehner und 7 Einer ergeben 77."
  },
  {
    id: "q2_m_017",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist die kleinste zweistellige Zahl?",
    answers: ["10", "11", "0", "1"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "10 ist die erste Zahl mit zwei Stellen (Zehner und Einer)."
  },
  {
    id: "q2_m_018",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist die größte zweistellige Zahl?",
    answers: ["99", "100", "90", "98"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die 99 ist die letzte zweistellige Zahl vor der 100."
  },
  {
    id: "q2_m_019",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl ist der Vorgänger von 100?",
    answers: ["99", "90", "101", "98"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt vor der 100 steht die 99."
  },
  {
    id: "q2_m_020",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Rückwärts in 10er-Schritten: 90, 80, 70, __, 50",
    answers: ["60", "65", "55", "40"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rückwärts immer -10: Von 70 minus 10 ist 60."
  },
  {
    id: "q2_m_021",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl hat 3 Zehner und 9 Einer?",
    answers: ["39", "93", "309", "30"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "3 Zehner (30) + 9 Einer (9) = 39."
  },
  {
    id: "q2_m_022",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist der Nachfolger von 99?",
    answers: ["100", "98", "90", "101"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Auf die 99 folgt die 100."
  },
  {
    id: "q2_m_023",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl ist um 10 kleiner als 65?",
    answers: ["55", "75", "64", "50"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "65 minus 10 = 55."
  },
  {
    id: "q2_m_024",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche Zahl ist um 10 größer als 48?",
    answers: ["58", "38", "49", "68"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "48 plus 10 = 58."
  },
  {
    id: "q2_m_025",
    category: "k2_mathe",
    topic: "hunderterraum",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welches ist der nächste glatte Zehner nach der 37?",
    answers: ["40", "30", "50", "38"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der nächste reine Zehner beim Aufwärtszählen ist 40."
  },

  // ================================================================
  // 2. PLUS & MINUS BIS 100 (30 Fragen)
  // ================================================================
  {
    id: "q2_m_026",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 7 + 8?",
    answers: ["14", "15", "16", "17"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "7 + 7 = 14, und einer mehr ergibt 15."
  },
  {
    id: "q2_m_027",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 3 + 9?",
    answers: ["11", "12", "13", "14"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 und 9 zusammengezählt sind 12."
  },
  {
    id: "q2_m_028",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 20 - 7?",
    answers: ["12", "13", "14", "15"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 20 sieben weggenommen bleiben 13."
  },
  {
    id: "q2_m_029",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 15 - 8?",
    answers: ["6", "7", "8", "9"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 15 acht weggenommen bleiben 7."
  },
  {
    id: "q2_m_030",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist die Hälfte von 12?",
    answers: ["5", "6", "7", "8"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "12 geteilt durch 2 ergibt 6."
  },
  {
    id: "q2_m_031",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist das Doppelte der Zahl 35?",
    answers: ["60", "65", "70", "75"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "35 + 35 = 70."
  },
  {
    id: "q2_m_032",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 50 + 30?",
    answers: ["70", "80", "90", "85"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "5 Zehner + 3 Zehner = 8 Zehner (80)."
  },
  {
    id: "q2_m_033",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 90 - 40?",
    answers: ["40", "50", "60", "30"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "9 Zehner minus 4 Zehner = 5 Zehner (50)."
  },
  {
    id: "q2_m_034",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Ergänze zum Hunderter: 40 + __ = 100",
    answers: ["50", "60", "70", "40"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 Zehner + 6 Zehner = 10 Zehner (100)."
  },
  {
    id: "q2_m_035",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Ergänze zum Hunderter: 70 + __ = 100",
    answers: ["20", "30", "40", "10"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "7 Zehner und 3 Zehner ergeben zusammen 10 Zehner (100)."
  },
  {
    id: "q2_m_036",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Ergänze zum Hunderter: 85 + __ = 100",
    answers: ["10", "15", "20", "25"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "85 + 5 ist 90, und noch 10 dazu macht 100. Also 15."
  },
  {
    id: "q2_m_037",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 24 + 5?",
    answers: ["28", "29", "30", "27"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 Einer + 5 Einer = 9 Einer, also 29."
  },
  {
    id: "q2_m_038",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 36 + 10?",
    answers: ["45", "46", "47", "37"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Zehner dazu: Aus 3 Zehnern werden 4 Zehner (46)."
  },
  {
    id: "q2_m_039",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 58 - 6?",
    answers: ["51", "52", "53", "54"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "8 Einer - 6 Einer = 2 Einer, also 52."
  },
  {
    id: "q2_m_040",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 47 - 10?",
    answers: ["36", "37", "38", "27"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Zehner weg: 4 Zehner minus 1 Zehner = 3 Zehner (37)."
  },
  {
    id: "q2_m_041",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 28 + 4?",
    answers: ["31", "32", "33", "30"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "28 + 2 = 30, plus 2 = 32."
  },
  {
    id: "q2_m_042",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 45 + 7?",
    answers: ["51", "52", "53", "50"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "45 + 5 = 50, plus 2 = 52."
  },
  {
    id: "q2_m_043",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 63 - 5?",
    answers: ["57", "58", "59", "60"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "63 - 3 = 60, minus 2 = 58."
  },
  {
    id: "q2_m_044",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 82 - 6?",
    answers: ["75", "76", "77", "74"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "82 - 2 = 80, minus 4 = 76."
  },
  {
    id: "q2_m_045",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist das Doppelte von 25?",
    answers: ["40", "50", "60", "45"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "25 + 25 = 50."
  },
  {
    id: "q2_m_046",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist das Doppelte von 40?",
    answers: ["70", "80", "90", "60"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "40 + 40 = 80."
  },
  {
    id: "q2_m_047",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist die Hälfte von 100?",
    answers: ["40", "50", "60", "25"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "100 geteilt durch 2 = 50."
  },
  {
    id: "q2_m_048",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist die Hälfte von 80?",
    answers: ["30", "40", "50", "35"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Hälfte von 8 Zehnern sind 4 Zehner (40)."
  },
  {
    id: "q2_m_049",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist die Hälfte von 60?",
    answers: ["20", "30", "40", "25"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "6 Zehner halbieren ergibt 3 Zehner (30)."
  },
  {
    id: "q2_m_050",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 33 + 33?",
    answers: ["65", "66", "67", "64"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "30 + 30 = 60, und 3 + 3 = 6 -> zusammen 66."
  },
  {
    id: "q2_m_051",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 100 - 25?",
    answers: ["70", "75", "80", "65"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "100 - 20 = 80, minus 5 = 75."
  },
  {
    id: "q2_m_052",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 100 - 50?",
    answers: ["40", "50", "60", "30"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "10 Zehner minus 5 Zehner = 5 Zehner (50)."
  },
  {
    id: "q2_m_053",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 19 + 19?",
    answers: ["37", "38", "39", "36"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "20 + 20 = 40, minus 2 = 38."
  },
  {
    id: "q2_m_054",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 75 + 25?",
    answers: ["90", "100", "95", "85"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "75 + 20 = 95, plus 5 = 100."
  },
  {
    id: "q2_m_055",
    category: "k2_mathe",
    topic: "add_sub_20_100",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Tauschaufgabe: Wenn 34 + 12 = 46 ist, was ist dann 12 + 34?",
    answers: ["44", "46", "48", "50"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Addition darf man die Zahlen vertauschen, das Ergebnis bleibt 46."
  },

  // ================================================================
  // 3. DAS KLEINE EINMALEINS (25 Fragen)
  // ================================================================
  {
    id: "q2_m_056",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 5 × 2?",
    answers: ["8", "10", "12", "14"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "5 zweimal genommen ergibt 10."
  },
  {
    id: "q2_m_057",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 5 × 0?",
    answers: ["0", "5", "10", "1"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Jede Zahl mal 0 ergibt immer 0."
  },
  {
    id: "q2_m_058",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist das Ergebnis der Malaufgabe 4 × 5?",
    answers: ["15", "20", "25", "18"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 mal 5 ergibt 20 (5 + 5 + 5 + 5)."
  },
  {
    id: "q2_m_059",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 3 × 10?",
    answers: ["20", "30", "40", "13"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 mal 10 = 30."
  },
  {
    id: "q2_m_060",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 2 × 2?",
    answers: ["2", "4", "6", "8"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "2 mal 2 ergibt 4."
  },
  {
    id: "q2_m_061",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 3 × 3?",
    answers: ["6", "9", "12", "15"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 mal 3 = 9."
  },
  {
    id: "q2_m_062",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 4 × 4?",
    answers: ["12", "16", "20", "14"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 mal 4 ergibt 16."
  },
  {
    id: "q2_m_063",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 5 × 5?",
    answers: ["20", "25", "30", "15"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "5 mal 5 ist 25."
  },
  {
    id: "q2_m_064",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 6 × 2?",
    answers: ["10", "12", "14", "16"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: " Das Doppelte von 6 ist 12."
  },
  {
    id: "q2_m_065",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 7 × 10?",
    answers: ["60", "70", "80", "17"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "7 mal 10 ergibt 70."
  },
  {
    id: "q2_m_066",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 8 × 2?",
    answers: ["14", "16", "18", "20"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "8 plus 8 = 16."
  },
  {
    id: "q2_m_067",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 6 × 5?",
    answers: ["25", "30", "35", "40"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "6 mal 5 ergibt 30."
  },
  {
    id: "q2_m_068",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 8 × 5?",
    answers: ["35", "40", "45", "50"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "8 mal 5 ist genau 40."
  },
  {
    id: "q2_m_069",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 10 × 10?",
    answers: ["90", "100", "110", "1000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "10 Zehner ergeben zusammen 100."
  },
  {
    id: "q2_m_070",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 2 × 7?",
    answers: ["12", "14", "16", "18"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "2 mal 7 ist 14."
  },
  {
    id: "q2_m_071",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 3 × 4?",
    answers: ["10", "12", "14", "16"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "3 mal 4 ist 12."
  },
  {
    id: "q2_m_072",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 4 × 10?",
    answers: ["30", "40", "50", "14"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 mal 10 = 40."
  },
  {
    id: "q2_m_073",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 9 × 2?",
    answers: ["16", "18", "20", "14"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Doppelte von 9 ist 18."
  },
  {
    id: "q2_m_074",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 7 × 5?",
    answers: ["30", "35", "40", "45"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "7 mal 5 = 35."
  },
  {
    id: "q2_m_075",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 1 × 8?",
    answers: ["1", "8", "18", "0"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Jede Zahl mal 1 bleibt die Zahl selbst (8)."
  },
  {
    id: "q2_m_076",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Tauschaufgabe: 2 × 6 = 12. Was ist 6 × 2?",
    answers: ["10", "12", "14", "16"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Beim Multiplizieren darf man tauschen: Das Ergebnis bleibt 12."
  },
  {
    id: "q2_m_077",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 10 × 5?",
    answers: ["40", "50", "60", "15"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "10 mal 5 ist 50."
  },
  {
    id: "q2_m_078",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche dieser Zahlen gehört zur 2er-Reihe?",
    answers: ["14", "15", "17", "19"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "14 ist eine gerade Zahl und gehört zur 2er-Reihe (7 x 2 = 14)."
  },
  {
    id: "q2_m_079",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welche dieser Zahlen gehört zur 5er-Reihe?",
    answers: ["35", "32", "28", "41"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zahlen der 5er-Reihe enden immer auf 0 oder 5. Hier also 35."
  },
  {
    id: "q2_m_080",
    category: "k2_mathe",
    topic: "einmaleins",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Was ist 0 × 10?",
    answers: ["0", "10", "100", "1"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "0 mal irgendwas bleibt immer 0."
  },

  // ================================================================
  // 4. GELD, UHRZEIT & GEOMETRIE (20 Fragen)
  // ================================================================
  {
    id: "q2_m_081",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele Minuten hat eine Stunde?",
    answers: ["30", "60", "100", "90"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Stunde hat genau 60 Minuten."
  },
  {
    id: "q2_m_082",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele Minuten hat eine halbe Stunde?",
    answers: ["30", "20", "60", "45"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Stunde hat 60 Minuten, die Hälfte davon sind 30 Minuten."
  },
  {
    id: "q2_m_083",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Lina kauft ein Heft für 1,50 € und bezahlt mit einer 2-Euro-Münze. Wie viel Rückgeld bekommt sie?",
    answers: ["50 Cent", "20 Cent", "1 Euro", "80 Cent"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 1,50 € bis 2,00 € fehlen genau 50 Cent."
  },
{
  id: "q2_m_084",
  category: "k2_mathe",
  topic: "groessen_geometrie_k2",
  area: "schule",
  grade: 2,
  subject: "mathe",
  question: "Wenn der große Zeiger auf der 6 steht und der kleine Zeiger zwischen 3 und 4 steht, wie viel Uhr ist es?",
  answers: ["Punkt 3 Uhr", "Halb 3 Uhr", "Halb 4 Uhr", "Punkt 4 Uhr"],
  correct: 2,
  difficulty: "leicht",
  points: 5,
  explanation: "Bei halb 4 steht der große Zeiger auf der 6 und der kleine Zeiger zwischen der 3 und der 4."
},
  {
    id: "q2_m_085",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele Cent fehlen bei 70 Cent zu 1 Euro?",
    answers: ["30 Cent", "20 Cent", "40 Cent", "10 Cent"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Euro entspricht 100 Cent. 100 - 70 = 30 Cent."
  },
  {
    id: "q2_m_086",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele Zentimeter (cm) sind genau 1 Meter (m)?",
    answers: ["100 cm", "10 cm", "50 cm", "1000 cm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Meter besteht aus genau 100 Zentimetern."
  },
  {
    id: "q2_m_087",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Womit misst man in der Schule Längen von Stiften oder Heften in Zentimetern?",
    answers: ["Lineal", "Uhr", "Waage", "Thermometer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit dem Lineal misst man Zentimeter ab."
  },
  {
    id: "q2_m_088",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Der große Zeiger steht oben auf der 12, der kleine auf der 9. Wie viel Uhr ist es?",
    answers: ["9 Uhr", "12 Uhr", "3 Uhr", "6 Uhr"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der kleine Zeiger zeigt auf die 9 -> punkt 9 Uhr."
  },
  {
    id: "q2_m_089",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Der große Zeiger steht rechts auf der 3. Was zeigt er bei der Uhrzeit an?",
    answers: ["Viertel nach", "Viertel vor", "Halb", "Punkt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Zeigt der große Zeiger auf die 3, ist 1 Viertelstunde vergangen (Viertel nach)."
  },
  {
    id: "q2_m_090",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Der große Zeiger steht links auf der 9. Was bedeutet das für die Uhrzeit?",
    answers: ["Viertel vor", "Viertel nach", "Halb", "Punkt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Zeigt der große Zeiger auf die 9, fehlt noch 1 Viertelstunde bis zur nächsten vollen Stunde (Viertel vor)."
  },
  {
    id: "q2_m_091",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele quadratische Flächen hat ein Spielwürfel?",
    answers: ["6 Flächen", "4 Flächen", "8 Flächen", "12 Flächen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Würfel hat 6 quadratische Außenseiten."
  },
  {
    id: "q2_m_092",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welches dieser Gebilde ist ein dreidimensionaler Körperform?",
    answers: ["Kugel", "Kreis", "Dreieck", "Quadrat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Kugel ist ein räumlicher Körper, Kreis und Quadrat sind flach."
  },
  {
    id: "q2_m_093",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie nennt man eine flache Form mit genau 3 Ecken und 3 Seiten?",
    answers: ["Dreieck", "Quadrat", "Kreis", "Rechteck"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Drei Ecken = Dreieck."
  },
  {
    id: "q2_m_094",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele 50-Cent-Münzen ergeben zusammen genau 1 Euro?",
    answers: ["2 Münzen", "5 Münzen", "10 Münzen", "4 Münzen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "50 Cent + 50 Cent = 100 Cent = 1 Euro."
  },
  {
    id: "q2_m_095",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele 20-Cent-Münzen brauchst du für 1 Euro?",
    answers: ["5 Münzen", "2 Münzen", "10 Münzen", "4 Münzen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "5 mal 20 Cent = 100 Cent = 1 Euro."
  },
  {
    id: "q2_m_096",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele 10-Cent-Münzen sind zusammen 1 Euro?",
    answers: ["10 Münzen", "5 Münzen", "100 Münzen", "20 Münzen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 mal 10 Cent = 100 Cent = 1 Euro."
  },
  {
    id: "q2_m_097",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Tim hat zwei 2-Euro-Münzen in der Tasche. Wie viel Euro hat er insgesamt?",
    answers: ["4 Euro", "2 Euro", "5 Euro", "22 Euro"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "2 € + 2 € = 4 €."
  },
  {
    id: "q2_m_098",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Wie viele Stunden hat ein ganzer Tag (Tag und Nacht zusammen)?",
    answers: ["24 Stunden", "12 Stunden", "60 Stunden", "10 Stunden"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein voller Tag hat 24 Stunden."
  },
  {
    id: "q2_m_099",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Ein Stift ist 12 cm lang, ein anderer 15 cm. Um wie viele cm ist der zweite Stift länger?",
    answers: ["3 cm", "2 cm", "5 cm", "4 cm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "15 cm - 12 cm = 3 cm."
  },
  {
    id: "q2_m_100",
    category: "k2_mathe",
    topic: "groessen_geometrie_k2",
    area: "schule",
    grade: 2,
    subject: "mathe",
    question: "Welches Scheingeld ist der kleinste Euro-Geldschein?",
    answers: ["5-Euro-Schein", "10-Euro-Schein", "1-Euro-Schein", "2-Euro-Schein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der kleinstwertige Papierschein im Euro-System ist der 5-Euro-Schein."
  }
];