const K4_DEUTSCH_QUESTIONS = [
  // ================================================================
  // 1. GRAMMATIK & 4 FÄLLE (25 Fragen)
  // ================================================================
  {
    id: "q4_d_001",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Mit welchem Fragewort erfragt man den 1. Fall (Nominativ)?",
    answers: ["Wessen?", "Wem?", "Wer oder was?", "Wen oder was?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Nominativ ist die Wer-Form: 'Wer oder was?'"
  },
  {
    id: "q4_d_002",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Mit welchem Fragewort erfragt man den 2. Fall (Genitiv)?",
    answers: ["Wen oder was?", "Wer oder was?", "Wessen?", "Wem?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Genitiv ist die Wessen-Form: 'Wessen Haus ist das?'"
  },
  {
    id: "q4_d_003",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Mit welchem Fragewort erfragt man den 3. Fall (Dativ)?",
    answers: ["Wessen?", "Wer oder was?", "Wem?", "Wen oder was?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Dativ ist die Wem-Form: 'Wem helfe ich?'"
  },
  {
    id: "q4_d_004",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Mit welchem Fragewort erfragt man den 4. Fall (Akkusativ)?",
    answers: ["Wem?", "Wer oder was?", "Wen oder was?", "Wessen?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Akkusativ ist die Wen-Form: 'Wen oder was sehe ich?'"
  },
  {
    id: "q4_d_005",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "In welchem Fall steht das Wort 'des Hundes' im Satz: 'Das Hütte des Hundes ist neu'?",
    answers: ["Akkusativ (4. Fall)", "Nominativ (1. Fall)", "Dativ (3. Fall)", "Genitiv (2. Fall)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Wessen Hütte? -> des Hundes (Genitiv)."
  },
  {
    id: "q4_d_006",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "In welchem Fall steht 'dem Kind' im Satz: 'Ich gebe dem Kind den Ball'?",
    answers: ["Genitiv (2. Fall)", "Dativ (3. Fall)", "Nominativ (1. Fall)", "Akkusativ (4. Fall)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wem gebe ich den Ball? -> dem Kind (Dativ)."
  },
  {
    id: "q4_d_007",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "In welchem Fall steht 'den Ball' im Satz: 'Ich sehe den Ball'?",
    answers: ["Genitiv (2. Fall)", "Akkusativ (4. Fall)", "Dativ (3. Fall)", "Nominativ (1. Fall)"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wen oder was sehe ich? -> den Ball (Akkusativ)."
  },
  {
    id: "q4_d_008",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie lautet die Genitiv-Form von 'der Mann'?",
    answers: ["des Mannes", "dem Mann", "den Mann", "die Männer"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Im Genitiv lautet es: des Mannes."
  },
  {
    id: "q4_d_009",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "In welcher Zeitform steht der Satz: 'Er hatte das Buch schon gelesen'?",
    answers: ["Futur I (Zukunft)", "Präteritum", "Perfekt", "Plusquamperfekt"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'hatte gelesen' bildet das Plusquamperfekt (Vorvergangenheit)."
  },
  {
    id: "q4_d_010",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "In welcher Zeitform steht der Satz: 'Morgen werden wir in den Urlaub fahren'?",
    answers: ["Präteritum", "Perfekt im Alltag", "Futur I (Zukunft)", "Präsens (Gegenwart)"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Hilfsverb 'werden' + Infinitiv ('fahren') drückt das Futur I (Zukunft) aus."
  },
  {
    id: "q4_d_011",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie heißt das Plusquamperfekt von 'ich gehe'?",
    answers: ["ich ging", "ich bin gegangen", "ich werde gehen", "ich war gegangen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Vorvergangenheit wird mit 'war/hatte' + Partizip II gebildet: ich war gegangen."
  },
  {
    id: "q4_d_012",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Wort ist eine Konjunktion (Bindewort)?",
    answers: ["Haus", "laufen", "schnell", "weil"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'weil' verbindet Sätze miteinander und ist eine Konjunktion."
  },
  {
    id: "q4_d_013",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Wort ist eine Präposition (Verhältniswort)?",
    answers: ["rennen", "schön", "auf", "Kind"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'auf' gibt Verhältnisse wie den Ort an (auf dem Tisch) und ist eine Präposition."
  },
  {
    id: "q4_d_014",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Ergänze den richtigen Genitiv: 'Das Auto ___ (die Lehrerin) ist rot.'",
    answers: ["die Lehrerin", "den Lehrerin", "der Lehrerin", "dem Lehrerin"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Wessen Auto? -> der Lehrerin (Genitiv weiblich)."
  },
  {
    id: "q4_d_015",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Ergänze den richtigen Dativ: 'Wir helfen ___ (der alte Mann).' ",
    answers: ["des alten Mannes", "dem alten Mann", "den alten Mann", "der alte Mann"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Wem helfen wir? -> dem alten Mann (Dativ)."
  },
  {
    id: "q4_d_016",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Ergänze den richtigen Akkusativ: 'Sie sucht ___ (ihr Schlüssel).' ",
    answers: ["ihr Schlüssel", "ihrem Schlüssel", "ihren Schlüssel", "ihres Schlüssels"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Wen oder was sucht sie? -> ihren Schlüssel (Akkusativ)."
  },
  {
    id: "q4_d_017",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Wortart ist 'sein' im Satz: 'Das ist sein Fahrrad'?",
    answers: ["Artikel im Alltag", "Personalpronomen", "Verb in der Praxis", "Possessivpronomen"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'sein' drückt Besitz aus -> Possessivpronomen."
  },
  {
    id: "q4_d_018",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie lautet die Steigerung von 'viel'?",
    answers: ["viel, mehr, am meisten", "viel, vieler, am vielsten", "viel, größer, am größten", "viel, mehrer, am mehrsten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die unregelmäßige Steigerung heißt: viel -> mehr -> am meisten."
  },
  {
    id: "q4_d_019",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welchen Fall verlangt die Präposition 'wegen' im Standarddeutschen?",
    answers: ["Genitiv (2. Fall)", "Dativ (3. Fall)", "Akkusativ (4. Fall)", "Nominativ (1. Fall)"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Standardsprachlich steht nach 'wegen' der Genitiv (z. B. wegen des Regens)."
  },
  {
    id: "q4_d_020",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie heißt das Partizip II des Verbs 'fliegen'?",
    answers: ["fliegte", "flog", "gefliegt", "geflogen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Partizip II heißt 'geflogen' (er ist geflogen)."
  },
  {
    id: "q4_d_021",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches sind die drei Hilfsverben im Deutschen?",
    answers: ["gehen, kommen, laufen", "sein, haben, werden", "können, müssen, wollen", "lesen, schreiben, rechnen"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Sein, haben und werden bilden zusammen mit anderen Verben die Zeiten."
  },
  {
    id: "q4_d_022",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Fürwort ist ein Demonstrativpronomen (hinweisendes Fürwort)?",
    answers: ["dieser", "ich", "wer", "mein"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'dieser / diese / dieses' weist auf etwas Bestimmtes hin."
  },
  {
    id: "q4_d_023",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie nennt man die 4 Fälle in der Fachsprache der Grammatik?",
    answers: ["Nominativ, Genitiv, Dativ, Akkusativ", "Subjekt, Prädikat, Objekt, Adverbial", "Präsens, Präteritum, Perfekt, Futur", "Nomen, Verb, Adjektiv, Artikel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die vier grammatischen Fälle heißen Nominativ (1.), Genitiv (2.), Dativ (3.) und Akkusativ (4.)."
  },
  {
    id: "q4_d_024",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Setze in den richtigen Fall ein: 'Wir stehen vor ___ (das große Haus).'",
    answers: ["des großen Hauses", "dem großen Haus", "den großen Haus", "das große Haus"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Wo stehen wir? -> vor dem großen Haus (Dativ)."
  },
  {
    id: "q4_d_025",
    category: "k4_deutsch",
    topic: "grammatik_4faelle",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist der Unterschied zwischen 'bestimmtem' und 'unbestimmtem' Artikel?",
    answers: ["heute vs. gestern", "groß/klein vs. gut/schlecht in der Praxis", "ich/du/er (bestimmt) vs. mein/dein (unbestimmt)", "der/die/das (bestimmt) vs. ein/eine (unbestimmt)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Bestimmte Artikel bezeichnen Konkretes (der Hund), unbestimmte Allgemeines (ein Hund)."
  },

  // ================================================================
  // 2. RECHTSCHREIBSTRATEGIEN & FREMDWÖRTER (25 Fragen)
  // ================================================================
  {
    id: "q4_d_026",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wann schreibt man 'dass' mit Doppel-s?",
    answers: ["Wenn man es durch 'ein' ersetzen kann", "Wenn man es nicht durch 'dieses', 'jenes' oder 'welches' ersetzen kann", "Immer nach einem Komma", "Wenn es am Satzanfang steht"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Lässt sich das Wort durch dieses/jenes/welches ersetzen, schreibt man 'das' mit s. Ansonsten 'dass'."
  },
  {
    id: "q4_d_027",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welcher Satz enthält das richtig geschriebene 'dass'?",
    answers: ["Ich kenne dass Kind. in der Praxis", "Ich hoffe, dass morgen die Sonne scheint.", "Das Buch, dass ich lese, ist toll.", "Dass ist mein neues Fahrrad. in der Praxis"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Im ersten Satz ist 'dass' eine Bindewort-Verbindung (Konjunktion)."
  },
  {
    id: "q4_d_028",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wann benutzt man 'seit' mit 't' am Ende?",
    answers: ["Immer am Satzanfang", "Bei Personen (ihr seid)", "Bei Zeitangaben", "Nur bei Zahlen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "SeiT mit 't' drückt eine Zeitdauer oder einen Zeitpunkt aus."
  },
  {
    id: "q4_d_029",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie schreibt man das Wort 'Laufen' im Satz: 'Zum ___ braucht man gute Schuhe'?",
    answers: ["Klein (laufen), weil es ein Verb ist im Alltag", "Wie man möchte", "Groß (Laufen), weil ein Signalwort davor steht", "Groß nur am Satzanfang in der Praxis"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Durch das Signalwort 'Zum' (Zu dem) wird das Verb zum Nomen (Nominalisierung) und großgeschrieben."
  },
  {
    id: "q4_d_030",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie schreibt man das Fremdwort für den Gleichklang der Töne richtig?",
    answers: ["Rytmus", "Rhythmus", "Rhytmus", "Rhythmuß"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Rhythmus wird mit rh und yth geschrieben."
  },
  {
    id: "q4_d_031",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Schreibweise des Fremdworts ist korrekt?",
    answers: ["Computar", "Kompjuter", "Komputer", "Computer"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das aus dem Englischen stammende Wort schreibt man Computer."
  },
  {
    id: "q4_d_032",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie schreibt man das Wort für ein technisches Gerät richtig?",
    answers: ["Maschine", "Maschiene", "Maschihne", "Maschineh"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Maschine wird trotz langem i nur mit 'i' geschrieben (Ausnahme von der ie-Regel)."
  },
  {
    id: "q4_d_033",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Vor welchem dieser Bindewörter muss im Satz immer ein Komma stehen?",
    answers: ["oder", "und", "weil", "sowie"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Vor Nebensatz-Einleitungen wie 'weil', 'dass', 'wenn' gehört ein Komma."
  },
  {
    id: "q4_d_034",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Adjektiv wird im Satz großgeschrieben: 'Sie wünschte ihm alles ___ (Gute)'?",
    answers: ["Gute", "gute", "gutes", "Gutes"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Nach unbestimmten Zahlwörtern wie 'alles', 'etwas', 'nichts' werden Adjektive nominalisiert und großgeschrieben."
  },
  {
    id: "q4_d_035",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was nutzt man bei der Rechtschreibstrategie 'Verlängern' bei Wörtern wie 'Hund'?",
    answers: ["Man schreibt das Wort 10 Mal auf", "Man trennt es in Silben", "Man bildet die Mehrzahl (Hunde), um das 'd' am Ende deutlich zu hören", "Man sucht im Duden"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Auslautverhärtung am Wortende hört man durch Verlängern (Hun-de)."
  },
  {
    id: "q4_d_036",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Wort wird mit 'V' geschrieben?",
    answers: ["Phogel", "Fogel", "Vogel", "Wogel"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Vogel schreibt man mit dem Merkwort-Buchstaben V."
  },
  {
    id: "q4_d_037",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was passiert mit Vokalen vor einem doppelten Konsonanten (z. B. schwimmen, rennen)?",
    answers: ["Sie werden kurz gesprochen", "Sie werden lang gesprochen", "Sie werden zu Umlauten", "Sie fallen weg zur Auswahl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Doppelkonsonanten (mm, nn, tt...) zeigen an, dass der Vokal davor kurz betont ist."
  },
  {
    id: "q4_d_038",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Nachsilbe bildet aus Verben Nomen?",
    answers: ["-ung (z. B. Rettung)", "-lich in der Praxis", "-sam in der Praxis", "-ig in der Praxis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wörter mit Endungen wie -ung, -heit, -keit, -nis, -schaft sind Nomen."
  },
  {
    id: "q4_d_039",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches dieser Wörter hat einen Doppelvokal?",
    answers: ["Schne", "Schneh", "Schneegh", "Schnee"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Schnee hat das Doppel-e (ee)."
  },
  {
    id: "q4_d_040",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie trennt man das Wort 'Kiste' nach neuen Trennregeln richtig?",
    answers: ["Kis-te", "Ki-ste", "K-iste", "Kist-e"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach den Rechtschreibregeln wird 'st' getrennt: Kis-te."
  },
  {
    id: "q4_d_041",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Fremdwort schreibt man richtig?",
    answers: ["Training", "Träning", "Trening", "Trainink"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das englische Sportwort schreibt man Training."
  },
  {
    id: "q4_d_042",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist ein Merkwort?",
    answers: ["Ein sehr langes Wort", "Ein Wort in einer fremden Sprache", "Ein Wort, dessen Rechtschreibung man lernen muss, weil Regeln nicht reichen", "Ein Nomen"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Merkwörter (z. B. mit V oder stummem h) muss man sich einprägen."
  },
  {
    id: "q4_d_043",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Wort wird mit 'sp' am Anfang geschrieben, obwohl man 'schp' spricht?",
    answers: ["Schbiegel", "Schpiegel", "Sbiegel", "Spiegel"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Am Wortanfang schreibt man sp (gesprochen schp)."
  },
  {
    id: "q4_d_044",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Wort wird mit 'st' am Anfang geschrieben, obwohl man 'scht' spricht?",
    answers: ["Sdein", "Schdein", "Stein", "Schtein"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Am Wortanfang schreibt man st (gesprochen scht)."
  },
  {
    id: "q4_d_045",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie schreibt man die Mehrzahl von 'Zirkus'?",
    answers: ["Zirkuse", "Zirkusen", "Zirkusse", "Zirke"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Mehrzahl lautet Zirkusse (mit doppel-s)."
  },
  {
    id: "q4_d_046",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Vorsilbe drückt das Gegenteil aus (z. B. bei glücklich -> ___glücklich)?",
    answers: ["zer-", "ver-", "ge-", "un-"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Vorsilbe un- kehrt die Bedeutung ins Gegenteil um."
  },
  {
    id: "q4_d_047",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Wort enthält ein Dehnungs-h?",
    answers: ["Spur", "Kiste", "Uhr", "Schule"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "In 'Uhr' dehnt das h den Vokal u lang."
  },
  {
    id: "q4_d_048",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was meint man mit der Strategie 'Ableiten'?",
    answers: ["Großschreibung prüfen", "Verwandte Wörter mit ä oder äu auf a oder au zurückführen", "Silben klatschen", "Wörter rückwärts lesen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Man leitet z. B. Hand -> Hände oder Haus -> Häuser ab."
  },
  {
    id: "q4_d_049",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wo findet man im Wörterbuch das Wort 'Elefant'?",
    answers: ["Unter dem Buchstaben D", "Unter dem Buchstaben E", "Ganz hinten bei Z", "Unter dem Buchstaben F"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wörterbücher sind nach dem Alphabet geordnet (E)."
  },
  {
    id: "q4_d_050",
    category: "k4_deutsch",
    topic: "rechtschreibung_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Nachsilbe macht aus dem Nomen 'Gefahr' ein Adjektiv?",
    answers: ["-ung in der Praxis", "-heit in der Praxis", "-nis in der Praxis", "-lich (gefährlich)"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Gefahr -> gefährlich (Adjektiv durch -lich und Umlaut)."
  },

  // ================================================================
  // 3. SATZGLIEDER (OBJEKTE & ADVERBIALE) (25 Fragen)
  // ================================================================
  {
    id: "q4_d_051",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie fragt man nach dem Dativobjekt (Wem-Ergänzung)?",
    answers: ["Wo?", "Wem?", "Wer oder was?", "Wen oder was?"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Dativobjekt erfragt man mit 'Wem?'."
  },
  {
    id: "q4_d_052",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie fragt man nach dem Akkusativobjekt (Wen-Ergänzung)?",
    answers: ["Warum?", "Wessen?", "Wem?", "Wen oder was?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Akkusativobjekt erfragt man mit 'Wen oder was?'."
  },
  {
    id: "q4_d_053",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was für ein Satzglied ist 'seiner Mutter' im Satz: 'Paul schenkt seiner Mutter Blumen'?",
    answers: ["Prädikat", "Subjekt", "Dativobjekt", "Akkusativobjekt"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Wem schenkt Paul Blumen? -> seiner Mutter (Dativobjekt)."
  },
  {
    id: "q4_d_054",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was für ein Satzglied ist 'Blumen' im Satz: 'Paul schenkt seiner Mutter Blumen'?",
    answers: ["Ortsangabe", "Akkusativobjekt", "Dativobjekt", "Subjekt"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Wen oder was schenkt Paul seiner Mutter? -> Blumen (Akkusativobjekt)."
  },
  {
    id: "q4_d_055",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie nennt man ein Satzglied, das nach der Zeit fragt (Wann? Wie lange?)?",
    answers: ["Subjekt in der Praxis", "Dativobjekt in der Praxis", "Ortsangabe in der Praxis", "Adverbiale Bestimmung der Zeit"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Zeitangaben (wann, wie lange) nennt man Adverbiale der Zeit."
  },
  {
    id: "q4_d_056",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie nennt man ein Satzglied, das nach dem Ort fragt (Wo? Wohin? Woher?)?",
    answers: ["Prädikat in der Praxis", "Zeitangabe in der Praxis", "Genitivobjekt in der Praxis", "Adverbiale Bestimmung des Ortes"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Ortsangaben (wo, wohin) heissen Adverbiale des Ortes."
  },
  {
    id: "q4_d_057",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie erfragt man die 'Adverbiale Bestimmung der Art und Weise'?",
    answers: ["Warum?", "Wann?", "Wo?", "Wie?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Art und Weise (z. B. leise, schnell) erfragt man mit 'Wie?'."
  },
  {
    id: "q4_d_058",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie erfragt man die 'Adverbiale Bestimmung des Grundes'?",
    answers: ["Wen? in der Praxis", "Wo? in der Praxis", "Wie? in der Praxis", "Warum? / Weshalb?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Gründe (z. B. wegen des Regens) erfragt man mit 'Warum?' oder 'Weshalb?'."
  },
  {
    id: "q4_d_059",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Bestimme das unterstrichene Satzglied: 'Gestern _gingen_ wir ins Kino.'",
    answers: ["Subjekt", "Ortsangabe", "Zeitangabe", "Prädikat"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'gingen' ist das Verb und bildet das Prädikat."
  },
  {
    id: "q4_d_060",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Bestimme das Satzglied 'im Garten': 'Die Kinder spielen im Garten.'",
    answers: ["Dativobjekt", "Adverbiale der Zeit", "Subjekt in der Praxis", "Adverbiale des Ortes"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Wo spielen die Kinder? -> im Garten (Ortsangabe)."
  },
  {
    id: "q4_d_061",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "satzglieder_k4",
    question: "Bestimme das Satzglied 'sehr vorsichtig': 'Der Katze schleicht sehr vorsichtig.'",
    answers: ["Adverbiale der Art und Weise", "Adverbiale der Zeit", "Akkusativobjekt in der Praxis", "Prädikat in der Praxis"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wie schleicht die Katze? -> sehr vorsichtig (Art und Weise)."
  },
  {
    id: "q4_d_062",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist ein zweiteiliges Prädikat?",
    answers: ["Ein Zwei Nomen im Satz im Alltag", "Ein Satz mit zwei Subjekten", "Ein Prädikat aus zwei Verbteilen", "Ein Satz ohne Verb in der Praxis"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei zusammengesetzten Zeiten oder trennbaren Verben besteht das Prädikat aus zwei Teilen."
  },
  {
    id: "q4_d_063",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wo steht das gebeugte Verb im deutschen Hauptsatz normalerweise?",
    answers: ["An zweiter Stelle", "An dritter Stelle", "Ganz am Anfang", "Ganz am Ende"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Hauptsatz besetzt das Prädikat immer die 2. Stelle im Satz."
  },
  {
    id: "q4_d_064",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wo steht das Verb in einem Nebensatz (z. B. nach 'weil')?",
    answers: ["An 2. Stelle", "Ganz am Anfang in der Praxis", "Ganz am Ende des Nebensatzes", "Vor dem Komma in der Praxis"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "In Nebensätzen wandert das gebeugte Verb ganz ans Ende ('... weil er krank IST.')."
  },
  {
    id: "q4_d_065",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Satzglied ist 'des Diebstahls' im Satz: 'Man beschuldigt ihn des Diebstahls'?",
    answers: ["Dativobjekt", "Subjekt", "Ortsangabe", "Genitivobjekt"],
    correct: 3,
    difficulty: "schwer",
    points: 5,
    explanation: "Wessen beschuldigt man ihn? -> des Diebstahls (Genitivobjekt)."
  },
  {
    id: "q4_d_066",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie viele Satzglieder hat der Satz: '[Der alte Mann] [liest] [abends] [eine Zeitung]'?",
    answers: ["4 Satzglieder", "3 Satzglieder", "2 Satzglieder", "5 Satzglieder"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "1. Der alte Mann (Subjekt), 2. liest (Prädikat), 3. abends (Zeitangabe), 4. eine Zeitung (Akkusativobjekt)."
  },
  {
    id: "q4_d_067",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist das Subjekt im Satz: 'Den kleinen Hund füttert das liebe Mädchen'?",
    answers: ["füttert im Alltag", "das liebe Mädchen", "Den kleinen Hund", "Hund in der Praxis"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Wer oder was füttert den Hund? -> das liebe Mädchen."
  },
  {
    id: "q4_d_068",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was versteht man unter ein Satzgefüge?",
    answers: ["Ein Fragesatz", "Eine Verbindung aus mindestens einem Hauptsatz und einem Nebensatz", "Eine Zwei zusammengesetzte Hauptsätze", "Ein Satz aus nur zwei Wörtern"],
    correct: 1,
    difficulty: "schwer",
    points: 5,
    explanation: "Hauptsatz + Nebensatz bilden zusammen ein Satzgefüge."
  },
  {
    id: "q4_d_069",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Konjunktion leitet einen Nebensatz ein?",
    answers: ["denn", "oder", "und", "obwohl"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'obwohl' leitet einen Nebensatz ein, bei dem das Verb am Ende steht."
  },
  {
    id: "q4_d_070",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Konjunktion verbindet zwei Hauptsätze, ohne das Verb ans Ende zu schieben?",
    answers: ["dass", "weil", "wenn", "und"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'und', 'oder', 'aber', 'denn' verändern die Satzstellung im 2. Satz nicht."
  },
  {
    id: "q4_d_071",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Wörter gehören zusammen als EIN Satzglied: 'Die Schüler der vierten Klasse laufen'?",
    answers: ["Die Schüler der vierten Klasse", "der vierten Klasse laufen", "Die Schüler in der Praxis", "Die Schüler laufen zur Auswahl"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'Die Schüler der vierten Klasse' ist das komplexe Subjekt und lässt sich nur geschlossen umstellen."
  },
  {
    id: "q4_d_072",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist das Prädikat im Satz: 'Lisa hat ihrer Freundin ein Geschenk gekauft'?",
    answers: ["hat zur Auswahl", "hat ... gekauft", "ein Geschenk", "gekauft"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Das zweiteilige Perfekt-Prädikat lautet: 'hat ... gekauft'."
  },
  {
    id: "q4_d_073",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Bestimme das Satzglied 'Wegen des Nebels': 'Wegen des Nebels verspätete sich der Bus.'",
    answers: ["Dativobjekt im Alltag", "Subjekt in der Praxis", "Adverbiale des Grundes", "Ortsangabe zur Auswahl"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Warum verspätete sich der Bus? -> Wegen des Nebels (Grund)."
  },
  {
    id: "q4_d_074",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Frage hilft, das Subjekt von einem Akkusativobjekt zu unterscheiden?",
    answers: ["Wo-Frage vs. Wann-Frage", "Wer-Frage fürs Subjekt ('Wer?') vs. Wen-Frage fürs Objekt ('Wen?')", "Wessen-Frage vs. Wem-Frage", "Warum-Frage vs. Wie-Frage"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Subjekt = Wer oder was? / Akkusativobjekt = Wen oder was?"
  },
  {
    id: "q4_d_075",
    category: "k4_deutsch",
    topic: "satzglieder_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie nennt man die Satzglieder 'Dativobjekt' und 'Akkusativobjekt' gemeinsam?",
    answers: ["Objekte (Ergänzungen)", "Subjekte in der Praxis", "Satzzeichen im Alltag", "Prädikate zur Auswahl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Objekte sind Ergänzungen im Satz, die vom Verb gefordert werden."
  },

  // ================================================================
  // 4. TEXTE, SAGEN & LESEVERSTÄNDNIS (25 Fragen)
  // ================================================================
  {
    id: "q4_d_076",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was unterscheidet eine 'Sage' von einem 'Märchen'?",
    answers: ["Sagen sind immer lustig", "Sagen beziehen sich oft auf reale Orte oder historische Personen", "Sagen spielen nur in der Zukunft", "Märchen sind immer wahr"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Sagen verknüpfen echte Orte oder Personen (z. B. Drachenfels am Rhein) mit phantastischen Begebenheiten."
  },
  {
    id: "q4_d_077",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche bekannte Narren-Figur spielte den Menschen Streiche und nahm Redewendungen wörtlich?",
    answers: ["Siegfried der Drachentöter", "Robin Hood", "Der Rattenfänger von Hameln", "Till Eulenspiegel"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Till Eulenspiegel ist die berühmteste deutsche Schalk- und Sagenfigur."
  },
  {
    id: "q4_d_078",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Womit lockte der Rattenfänger von Hameln die Ratten und später die Kinder aus der Stadt?",
    answers: ["Mit den Klängen einer Flöte", "Mit einer Zaubergeige", "Mit frischem Brot im Alltag", "Mit einer Trommel im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Er spielte auf seiner Flöte zauberhafte Melodien."
  },
  {
    id: "q4_d_079",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welcher Held der Nibelungensage tötete einen Drachen und badete in dessen Blut?",
    answers: ["Parzival", "Till Eulenspiegel", "Siegfried", "König Arthur"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Siegfried der Drachentöter wurde durch das Drachenblut bis auf eine Stelle am Rücken unverwundbar."
  },
  {
    id: "q4_d_080",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist ein sachlicher 'Zeitungsbericht'?",
    answers: ["Eine Zaubergeschichte in der Praxis", "Ein erfundenes Gedicht in der Praxis", "Ein informierender Text über ein reales Ereignis", "Ein Witzblatt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Berichte informieren sachlich, objektiv und ohne persönliche Meinung."
  },
  {
    id: "q4_d_081",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "In welcher Zeitform schreibt man eine Zusammenfassung / Inhaltsangabe eines Textes?",
    answers: ["Plusquamperfekt", "Präsens (Gegenwart)", "Futur (Zukunft)", "Präteritum (Vergangenheit)"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Inhaltsangaben werden stets im Präsens verfasst."
  },
  {
    id: "q4_d_082",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was gehört in eine sachliche 'Personenbeschreibung'?",
    answers: ["Größe, Haarfarbe, Kleidung und besondere Merkmale ohne Wertung", "Erfundene Abenteuer", "Ein Gedicht über die Person", "Geheimwünsche der Person"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Personenbeschreibungen halten beobachtbare Fakten genau und sachlich fest."
  },
  {
    id: "q4_d_083",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wozu nutzt man eine 'Mindmap' vor dem Schreiben einer Geschichte?",
    answers: ["Um das Heft sauber zu halten in der Praxis", "Um Rechtschreibfehler ausradieren zu können", "Um Ideen zu sammeln, zu ordnen und zu verknüpfen", "Zum Zeichnen von Bildern in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Mindmap ordnet Gedanken rund um ein zentrales Thema."
  },
  {
    id: "q4_d_084",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was bedeutet die Redewendung: „Jemandem auf den Keks gehen“?",
    answers: ["Gemeinsam backen in der Praxis", "Auf Essen treten in der Praxis", "Jemandem Kekse schenken in der Praxis", "Jemanden stark nerven oder irritieren"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Es ist ein umgangssprachlicher Ausdruck für 'jemanden nerven'."
  },
  {
    id: "q4_d_085",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was bedeutet die Redewendung: „Zwei Fliegen mit einer Klappe schlagen“?",
    answers: ["Zwei Aufgaben gleichzeitig mit einer Aktion erledigen", "Insekten jagen", "Sehr ungeschickt sein", "Aufgabe abbrechen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es bedeutet, zwei Ziele auf einmal zu erreichen."
  },
  {
    id: "q4_d_086",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was bedeutet die Redewendung: „Den Faden verlieren“?",
    answers: ["Verwirrt im Wald stehen", "Beim Sprechen oder Erzählen vergessen, was man sagen wollte", "Beim Nähen kein Garn mehr haben in der Praxis", "Ein Buch verlieren"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Wer den Faden verliert, kommt in seinem Vortrag aus dem Konzept."
  },
  {
    id: "q4_d_087",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist ein sprachlicher 'Vergleich'?",
    answers: ["Ein anderes Wort für Reim", "Die Überschrift eines Textes", "Eine Verknüpfung mit 'wie'", "Ein Satzzeichen im Alltag"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Vergleiche nutzen meist das Wort 'wie' (schlau wie ein Fuchs)."
  },
  {
    id: "q4_d_088",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist eine 'Metapher'?",
    answers: ["Eine Aufzählung in der Praxis", "Ein Buchstabe in der Praxis", "Ein bildhafter Ausdruck ohne 'wie'", "Ein langer Absatz in der Praxis"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "Metaphern übertragen Wortbedeutungen bildhaft auf etwas Neues (z. B. 'Wüstenschiff' für Kamel)."
  },
  {
    id: "q4_d_089",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Lehre steckt in der Fabel 'Die Schildkröte und der Hase'?",
    answers: ["Ausdauer und Stetigkeit siegen über Überheblichkeit", "Hasen sind die schnellsten Tiere in der Praxis", "Schildkröten können fliegen in der Praxis", "Man soll nicht sportlich sein in der Praxis"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der angeberische Hase verliert das Rennen, weil er trödelt und die stetige Schildkröte unterschätzt."
  },
  {
    id: "q4_d_090",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was ist der rote Faden in einem Erlebniserzählung-Text?",
    answers: ["Eine rote Markierung", "Das Alphabet", "Der innere logische Aufbau von Einleitung, Hauptteil (Spannung) und Schluss", "Der rote Einband des Buches"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Der rote Faden führt den Leser sinnvoll durch die Handlung."
  },
  {
    id: "q4_d_091",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Reimschema hat die Form 'abab'?",
    answers: ["Kreuzreim", "Haufenreim", "Umarmender Reim", "Paarreim (aabb)"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei 'abab' reimen sich Zeile 1+3 sowie 2+4 überkreuz (Kreuzreim)."
  },
  {
    id: "q4_d_092",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welches Reimschema hat die Form 'abba'?",
    answers: ["Kreuzreim (abab)", "Kein Reim", "Paarreim (aabb)", "Umarmender Reim"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Zeile 1 und 4 umschließen ('umarmen') die Zeilen 2 und 3 (abba)."
  },
  {
    id: "q4_d_093",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was unterscheidet eine 'Vorgangsbeschreibung' (z. B. Rezept) von einer Erlebniserzählung?",
    answers: ["Sie ist reiner Reim", "Sie ist sachlich, chronologisch und nutzt oft die Man-Form oder Befehlsform", "Sie erfindet Monster", "Sie hat keine Reihenfolge"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Vorgangsbeschreibungen erklären Schritt für Schritt sachlich einen Ablauf."
  },
  {
    id: "q4_d_094",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Lesestrategie hilft beim Verstehen schwieriger Sachtexte?",
    answers: ["Text umdrehen", "Wichtige Begriffe unterstreichen und Absätzen Stichwörter zuordnen", "Möglichst schnell ohne Pausen lesen", "Nur das letzte Wort lesen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Strukturierung durch Unterstreichen und Stichpunkte sichert das Textverständnis."
  },
  {
    id: "q4_d_095",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was bedeutet die Redewendung: „Da liegt der Hund begraben“?",
    answers: ["Das ist die eigentliche Ursache / das Kernproblem", "Das Hunde mögen keine Erde in der Praxis", "Ein Schatz ist versteckt in der Praxis", "Das Hier ruht ein Haustier in der Praxis"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Es bedeutet: 'Das ist die entscheidende Ursache des Problems'."
  },
  {
    id: "q4_d_096",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Sagengestalt verzauberte mit ihrem Gesang Schiffer am Felsen im Rhein?",
    answers: ["König Laurin", "Die Loreley", "Die Schildbürger", "Frau Holle"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Sage der Loreley erzählt von einer Nixe auf dem Felsen über dem Rhein."
  },
  {
    id: "q4_d_097",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Welche Sagenfiguren sind bekannt dafür, dass sie dumm wirkende Dinge taten (z. B. Licht in Eimern ins Rathaus tragen)?",
    answers: ["Die Schildbürger", "Die Bremer Stadtmusikanten", "Die Heinzelmännchen", "Die 7 Zwerge"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Schildbürgerstreiche schildern die Taten der Einwohner von Schilda."
  },
  {
    id: "q4_d_098",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was gehört in den 'Hauptteil' einer spannenden Erlebniserzählung?",
    answers: ["Die Adresse des Autors", "Eine Aufzählung aller Nomen", "Der Höhepunkt der Geschichte mit Gefühlen und Sinneseindrücken", "Das Inhaltsverzeichnis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Hauptteil baut sich die Handlung bis zum dramatischen Höhepunkt auf."
  },
  {
    id: "q4_d_099",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Was macht einen guten 'Schluss' bei einer Erlebniserzählung aus?",
    answers: ["Er bricht mitten im Satz ab", "Er stellt Fragen an den Lehrer in der Praxis", "Er beginnt mit 'Es war einmal' in der Praxis", "Er rundet das Erlebnis ab und zeigt Reaktionen oder Folgen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Schluss löst die Spannung auf und rundet das Ereignis ab."
  },
  {
    id: "q4_d_100",
    category: "k4_deutsch",
    topic: "leseverstaendnis_k4",
    area: "schule",
    grade: 4,
    subject: "deutsch",
    question: "Wie heißen die Helferwesen aus Köln, die nachts heimlich die Arbeit der Handwerker verrichteten?",
    answers: ["Kobolde", "Goblinsk", "Heinzelmännchen", "Zwerge"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Kölner Heinzelmännchensage erzählt von den fleißigen nächtlichen Helfern."
  }
,  { id: "q4_d_101", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Welche Wortart ist „obwohl“?", answers: ["Nomen", "Verb", "Konjunktion", "Artikel"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "obwohl verknüpft Sätze." },
  { id: "q4_d_102", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Partizip II von „schreiben“?", answers: ["schreibt", "schrieb", "geschrieben", "schreibend"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "geschrieben." },
  { id: "q4_d_103", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Aktiv oder Passiv: „Der Brief wird geschrieben.“?", answers: ["Aktiv", "Passiv", "Frage", "Nomen"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Passiv." },
  { id: "q4_d_104", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Zeitform: „Ich habe gelesen.“?", answers: ["Präsens", "Futur", "Perfekt", "Plusquamperfekt"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Perfekt." },
  { id: "q4_d_105", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "Richtig?", answers: ["seperat", "separat", "seperrat", "säperat"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "separat." },
  { id: "q4_d_106", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "„das“ oder „dass“: Ich weiß, ___ du kommst.", answers: ["das", "dass", "des", "dads"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "dass." },
  { id: "q4_d_107", category: "k4_deutsch", topic: "satz", area: "schule", grade: 4, subject: "deutsch",
    question: "Nebensatz wird oft eingeleitet durch …", answers: ["und", "oder", "weil/dass/wenn", "nur Punkt"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "unterordnende Konjunktionen." },
  { id: "q4_d_108", category: "k4_deutsch", topic: "satz", area: "schule", grade: 4, subject: "deutsch",
    question: "Im Nebensatz steht das finite Verb oft …", answers: ["am Anfang", "in der Mitte", "am Ende", "gar nicht"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "am Ende." },
  { id: "q4_d_109", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Adverb Beispiel?", answers: ["Haus", "laufen", "gestern", "der"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "gestern." },
  { id: "q4_d_110", category: "k4_deutsch", topic: "literatur", area: "schule", grade: 4, subject: "deutsch",
    question: "Reimpaar: Mund – …?", answers: ["Hand", "Wand", "Kind", "Haus"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Mund/Wand." },
  { id: "q4_d_111", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "Großschreibung nach …", answers: ["Komma immer", "Satzanfang", "jeder Präposition", "nie"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Satzanfang und Nomen." },
  { id: "q4_d_112", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Komparativ von „gut“?", answers: ["guter", "besser", "am besten", "mehr gut"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "besser." },
  { id: "q4_d_113", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Superlativ von „viel“?", answers: ["vieler", "mehr", "am meisten", "vielsten"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "am meisten." },
  { id: "q4_d_114", category: "k4_deutsch", topic: "satz", area: "schule", grade: 4, subject: "deutsch",
    question: "Wörtliche Rede steht in …", answers: ["Klammern", "Anführungszeichen", "Schrägstrichen", "nichts"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Anführungszeichen." },
  { id: "q4_d_115", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Pronomen ersetzt …", answers: ["Verben", "Nomen/Namen", "Kommas", "Zahlen"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Nomen." },
  { id: "q4_d_116", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "ck oder k: Ba___er", answers: ["k", "ck", "kk", "g"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Bäcker mit ck." },
  { id: "q4_d_117", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Akkusativ-Frage?", answers: ["Wem?", "Wo?", "Wen oder was?", "Wann?"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Wen/was?" },
  { id: "q4_d_118", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Dativ-Frage?", answers: ["Wen?", "Wem?", "Was?", "Wie?"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Wem?" },
  { id: "q4_d_119", category: "k4_deutsch", topic: "satz", area: "schule", grade: 4, subject: "deutsch",
    question: "Beispiel Hauptsatz?", answers: ["weil es regnet", "als er kam", "Sie lacht.", "wenn du willst"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Sie lacht." },
  { id: "q4_d_120", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Präposition Beispiel?", answers: ["schön", "auf", "rennt", "Kind"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "auf." },
  { id: "q4_d_121", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "ss oder ß: Groß___adt", answers: ["ss", "ß", "s", "sz"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Großstadt mit ß? Wait - Großstadt has ß in groß. Großstadt." },
  { id: "q4_d_122", category: "k4_deutsch", topic: "literatur", area: "schule", grade: 4, subject: "deutsch",
    question: "Erzähler in Ich-Form = …", answers: ["auktorial", "Ich-Erzähler", "neutral nur", "Lyrik"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Ich-Erzähler." },
  { id: "q4_d_123", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Infinitiv von „ging“?", answers: ["gegangen", "geht", "gehen", "ginge"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "gehen." },
  { id: "q4_d_124", category: "k4_deutsch", topic: "satz", area: "schule", grade: 4, subject: "deutsch",
    question: "Beistrich bei Aufzählung: Äpfel___ Birnen und Trauben", answers: [".", "!", ",", ";"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Komma." },
  { id: "q4_d_125", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Numerale Beispiel?", answers: ["schnell", "drei", "Haus", "und"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "drei." },
  { id: "q4_d_126", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "Dehnung: ___ (lange Zeitspanne)", answers: ["Jar", "Jahr", "Yahr", "Gaar"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Jahr." },
  { id: "q4_d_127", category: "k4_deutsch", topic: "grammatik", area: "schule", grade: 4, subject: "deutsch",
    question: "Konjunktiv oft für …", answers: ["Befehle nur", "Irreales/Wünsche", "Nur Zahlen", "Nur Nomen"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Irreales." },
  { id: "q4_d_128", category: "k4_deutsch", topic: "satz", area: "schule", grade: 4, subject: "deutsch",
    question: "Attribut beschreibt …", answers: ["nur Verben", "ein Nomen näher", "den Punkt", "die Zeit immer"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Nomen." },
  { id: "q4_d_129", category: "k4_deutsch", topic: "wortarten", area: "schule", grade: 4, subject: "deutsch",
    question: "Interjektion Beispiel?", answers: ["Haus", "au!", "laufen", "der"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "au!" },
  { id: "q4_d_130", category: "k4_deutsch", topic: "rechtschreibung", area: "schule", grade: 4, subject: "deutsch",
    question: "Zusammengesetztes Nomen: Fahrrad + Weg = …", answers: ["fahrrad weg", "Fahrradweg", "fahrRadWeg", "Fahrrad-weg immer"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Fahrradweg." }
];
