const K4_ENGLISCH_QUESTIONS = [
  // ================================================================
  // 1. HOBBIES, FREE TIME & SPORTS (25 Fragen)
  // ================================================================
  {
    id: "q4_e_001",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Fußball spielen' auf Englisch?",
    answers: ["playing football", "playing basketball", "playing tennis", "swimming"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing football' bedeutet Fußball spielen."
  },
  {
    id: "q4_e_002",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Hobby 'swimming'?",
    answers: ["Schwimmen", "Tauchen", "Segeln", "Klettern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'swimming' heißt Schwimmen."
  },
  {
    id: "q4_e_003",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Rad fahren' auf Englisch?",
    answers: ["riding a bike", "riding a horse", "driving a car", "skateboarding"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'riding a bike' bedeutet Fahrrad fahren."
  },
  {
    id: "q4_e_004",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'reading a book'?",
    answers: ["ein Buch lesen", "ein Buch schreiben", "ein Buch kaufen", "ein Buch malen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'reading a book' heißt ein Buch lesen."
  },
  {
    id: "q4_e_005",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'listening to music'?",
    answers: ["Musik hören", "Musik machen", "Singen", "Tanzen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'listening to music' bedeutet Musik hören."
  },
  {
    id: "q4_e_006",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie frage ich jemanden nach seinem Lieblingshobby?",
    answers: ["What is your favourite hobby?", "What is your name?", "Where do you live?", "How old are you?"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'What is your favourite hobby?' bedeutet 'Was ist dein Lieblingshobby?'."
  },
  {
    id: "q4_e_007",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie antwortet man auf 'Can you swim?' wenn man es KANN?",
    answers: ["Yes, I can.", "No, I can't.", "Yes, I am.", "No, I don't."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Yes, I can.' bedeutet 'Ja, ich kann es'."
  },
  {
    id: "q4_e_008",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie antwortet man auf 'Can you play tennis?' wenn man es NICHT kann?",
    answers: ["No, I can't.", "Yes, I can.", "No, I am not.", "Yes, I do."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'No, I can't.' (Kurzform von cannot) heißt 'Nein, ich kann nicht'."
  },
  {
    id: "q4_e_009",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Verb 'climbing'?",
    answers: ["Klettern", "Laufen", "Springen", "Rennen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'climbing' heißt Klettern."
  },
  {
    id: "q4_e_010",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'dancing'?",
    answers: ["Tanzen", "Singen", "Lachen", "Spielen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'dancing' bedeutet Tanzen."
  },
  {
    id: "q4_e_011",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Klavier spielen' auf Englisch?",
    answers: ["playing the piano", "playing the guitar", "playing the drums", "playing flute"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing the piano' heißt Klavier spielen."
  },
  {
    id: "q4_e_012",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Gitarre spielen' auf Englisch?",
    answers: ["playing the guitar", "playing the piano", "playing games", "singing songs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing the guitar' bedeutet Gitarre spielen."
  },
  {
    id: "q4_e_013",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'playing computer games'?",
    answers: ["Computerspiele spielen", "Computer reparieren", "im Internet surfen", "Fernsehen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing computer games' heißt Computerspiele spielen."
  },
  {
    id: "q4_e_014",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'cooking'?",
    answers: ["Kochen", "Backen", "Essen", "Trinken"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'cooking' heißt Kochen."
  },
  {
    id: "q4_e_015",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'drawing a picture'?",
    answers: ["ein Bild zeichnen", "ein Foto machen", "ein Bild ausneiden", "ein Bild aufhängen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'drawing' heißt Zeichnen."
  },
  {
    id: "q4_e_016",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'singing'?",
    answers: ["Singen", "Sprechen", "Schreien", "Rufen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'singing' heißt Singen."
  },
  {
    id: "q4_e_017",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Reiten' (auf einem Pferd) auf Englisch?",
    answers: ["horse riding / riding a horse", "cycling", "running", "walking"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'horse riding' bedeutet Pferdereiten."
  },
  {
    id: "q4_e_018",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Skateboard fahren' auf Englisch?",
    answers: ["skateboarding", "snowboarding", "rollerblading", "skiing"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'skateboarding' heißt Skateboard fahren."
  },
  {
    id: "q4_e_019",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Inlineskaten / Rollschuh fahren' auf Englisch?",
    answers: ["rollerblading / roller skating", "skateboarding", "ice skating", "running"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'rollerblading' bedeutet Inlineskaten."
  },
  {
    id: "q4_e_020",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'I like playing football'?",
    answers: ["Ich spiele gerne Fußball", "Ich spiele nicht gerne Fußball", "Ich kann kein Fußball spielen", "Ich sehe Fußball im Fernsehen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'I like ...' bedeutet 'Ich mag ... / Ich mache gerne ...'."
  },
  {
    id: "q4_e_021",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'I don't like running'?",
    answers: ["Ich laufe nicht gerne", "Ich laufe sehr gerne", "Ich kann schnell laufen", "Ich laufe morgen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'I don't like ...' heißt 'Ich mag ... nicht'."
  },
  {
    id: "q4_e_022",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Ski fahren' auf Englisch?",
    answers: ["skiing", "ice skating", "sledging", "climbing"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'skiing' heißt Skifahren."
  },
  {
    id: "q4_e_023",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schlittschuhlaufen' auf Englisch?",
    answers: ["ice skating", "rollerblading", "skiing", "swimming"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'ice skating' heißt Schlittschuhlaufen."
  },
  {
    id: "q4_e_024",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'team'?",
    answers: ["Mannschaft / Team", "Trainer", "Spielplatz", "Ball"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'team' heißt Mannschaft."
  },
  {
    id: "q4_e_025",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Turnen / Gymnastik' auf Englisch?",
    answers: ["gymnastics", "athletics", "dancing", "fitness"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'gymnastics' bedeutet Turnen."
  },

  // ================================================================
  // 2. AT SCHOOL, IN TOWN & DIRECTIONS (25 Fragen)
  // ================================================================
  {
    id: "q4_e_026",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach heißt auf Englisch 'maths'?",
    answers: ["Mathematik", "Musik", "Kunst", "Deutsch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'maths' (oder 'mathematics') ist Mathematik."
  },
  {
    id: "q4_e_027",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach heißt 'PE' (Physical Education)?",
    answers: ["Sport", "Physik", "Politik", "Sachunterricht"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'PE' steht für Sportunterricht."
  },
  {
    id: "q4_e_028",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach heißt 'art'?",
    answers: ["Kunst", "Musik", "Erdkunde", "Englisch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'art' bedeutet Kunstunterricht."
  },
  {
    id: "q4_e_029",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach entspricht am ehesten 'science'?",
    answers: ["Sachunterricht / Naturwissenschaften", "Sport", "Geschichte", "Religion"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'science' umfasst Sachunterricht und Naturwissenschaften."
  },
  {
    id: "q4_e_030",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'timetable'?",
    answers: ["Stundenplan", "Uhr", "Tischzeiten", "Kalender"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'timetable' heißt Stundenplan."
  },
  {
    id: "q4_e_031",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Turn left' bei einer Wegbeschreibung?",
    answers: ["Biege links ab", "Biege rechts ab", "Gehe geradeaus", "Stoppe hier"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Turn left' heißt links abbiegen."
  },
  {
    id: "q4_e_032",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Turn right'?",
    answers: ["Biege rechts ab", "Biege links ab", "Drehe um", "Gehe zurück"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Turn right' heißt rechts abbiegen."
  },
  {
    id: "q4_e_033",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Go straight ahead'?",
    answers: ["Gehe geradeaus weiter", "Biege sofort ab", "Warte an der Ampel", "Gehe durch den Park"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Go straight ahead' heißt geradeaus gehen."
  },
  {
    id: "q4_e_034",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Bahnhof' auf Englisch?",
    answers: ["railway station / train station", "bus stop", "airport", "supermarket"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'train station' oder 'railway station' ist der Bahnhof."
  },
  {
    id: "q4_e_035",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Kino' auf Englisch?",
    answers: ["cinema / movie theater", "theatre", "museum", "library"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'cinema' heißt Kino."
  },
  {
    id: "q4_e_036",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schwimmbad' auf Englisch?",
    answers: ["swimming pool", "playground", "park", "sports hall"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'swimming pool' heißt Schwimmbad."
  },
  {
    id: "q4_e_037",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Krankenhaus' auf Englisch?",
    answers: ["hospital", "hotel", "house", "hall"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'hospital' bedeutet Krankenhaus."
  },
  {
    id: "q4_e_038",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'library'?",
    answers: ["Bibliothek / Bücherei", "Buchhandlung", "Schulklasse", "Kino"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'library' ist die Bücherei oder Bibliothek."
  },
  {
    id: "q4_e_039",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet die Präposition 'next to'?",
    answers: ["neben", "hinter", "vor", "unter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'next to' bedeutet direkt neben."
  },
  {
    id: "q4_e_040",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet die Ortsangabe 'opposite'?",
    answers: ["gegenüber von", "neben", "hinter", "in"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'opposite' bedeutet gegenüber."
  },
  {
    id: "q4_e_041",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'in front of'?",
    answers: ["vor", "hinter", "auf", "unter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'in front of' bedeutet vor (z. B. in front of the house)."
  },
  {
    id: "q4_e_042",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'behind'?",
    answers: ["hinter", "vor", "neben", "zwischen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'behind' bedeutet hinter."
  },
  {
    id: "q4_e_043",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Lineal' im Federmäppchen auf Englisch?",
    answers: ["ruler", "rubber", "pencil", "scissors"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'ruler' heißt Lineal."
  },
  {
    id: "q4_e_044",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Radiergummi' auf Englisch?",
    answers: ["rubber / eraser", "ruler", "sharpener", "glue"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'rubber' (oder im Amerikanischen 'eraser') ist der Radiergummi."
  },
  {
    id: "q4_e_045",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Anspatzer / Anspitzer' auf Englisch?",
    answers: ["sharpener", "scissors", "pencil case", "pen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'sharpener' (pencil sharpener) ist der Anspitzer."
  },
  {
    id: "q4_e_046",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schere' auf Englisch?",
    answers: ["scissors", "glue", "ruler", "paper"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'scissors' bedeutet Schere."
  },
  {
    id: "q4_e_047",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Klebstoff' auf Englisch?",
    answers: ["glue / glue stick", "paper", "pen", "desk"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'glue' ist der Klebstoff."
  },
  {
    id: "q4_e_048",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie frage ich höflich nach dem Weg: 'Wo ist der Supermarkt?'?",
    answers: ["Where is the supermarket, please?", "How much is the supermarket?", "What is the supermarket?", "Who is in the supermarket?"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Where is ...?' fragt nach dem Ort."
  },
  {
    id: "q4_e_049",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Pausenhof' auf Englisch?",
    answers: ["playground / schoolyard", "classroom", "gym", "hall"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'schoolyard' oder 'playground' ist der Pausenhof."
  },
  {
    id: "q4_e_050",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'between'?",
    answers: ["zwischen", "neben", "auf", "unter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'between' bedeutet zwischen zwei Dingen."
  },

  // ================================================================
  // 3. SHOPPING, MONEY & FOOD (25 Fragen)
  // ================================================================
  {
    id: "q4_e_051",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie frage ich beim Einkaufen nach dem Preis: 'Wie viel kostet das?'?",
    answers: ["How much is it?", "How many is it?", "What time is it?", "Where is it?"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'How much is it?' fragt nach dem Preis."
  },
  {
    id: "q4_e_052",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie sagt man beim Überreichen der Ware oder des Geldes 'Bitte sehr!'?",
    answers: ["Here you are.", "Thank you.", "You're welcome.", "Please stop."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Here you are' bedeutet 'Bitte sehr / Hier bitte'."
  },
  {
    id: "q4_e_053",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie heißt die offizielle Währung in Großbritannien (Pfund)?",
    answers: ["pound / pounds", "euro", "dollar", "franc"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In Großbritannien bezahlt man mit 'pounds' (£)."
  },
  {
    id: "q4_e_054",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie heißen die Kleingeld-Münzen in Großbritannien (Pennies)?",
    answers: ["pence / penny", "cents", "pesos", "coins"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "1 Pound entspricht 100 Pence (p)."
  },
  {
    id: "q4_e_055",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie bestellt man höflich ein Eis: 'Kann ich bitte ein Eis haben?'?",
    answers: ["Can I have an ice cream, please?", "Give me ice cream!", "I want ice cream now!", "Ice cream is good."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Can I have ..., please?' ist die höfliche Formel beim Einkaufen."
  },
  {
    id: "q4_e_056",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'cheap'?",
    answers: ["günstig / billig", "teuer", "schwer", "alt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'cheap' bedeutet preiswert oder billig."
  },
  {
    id: "q4_e_057",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'expensive'?",
    answers: ["teuer", "billig", "klein", "schnell"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'expensive' bedeutet teuer."
  },
  {
    id: "q4_e_058",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Gemüse' auf Englisch?",
    answers: ["vegetables", "fruit", "meat", "sweets"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'vegetables' heißt Gemüse."
  },
  {
    id: "q4_e_059",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Obst / Früchte' auf Englisch?",
    answers: ["fruit", "vegetables", "bread", "drink"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'fruit' bedeutet Obst."
  },
  {
    id: "q4_e_060",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Gemüse heißt 'carrots'?",
    answers: ["Karotten / Möhren", "Kartoffeln", "Gurken", "Tomaten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'carrots' sind Karotten."
  },
  {
    id: "q4_e_061",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Gemüse heißt 'potatoes'?",
    answers: ["Kartoffeln", "Möhren", "Erbsen", "Bohnen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'potatoes' sind Kartoffeln."
  },
  {
    id: "q4_e_062",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'strawberries'?",
    answers: ["Erdbeeren", "Himbeeren", "Äpfel", "Kirschen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'strawberries' sind Erdbeeren."
  },
  {
    id: "q4_e_063",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'butter'?",
    answers: ["Butter", "Käse", "Milch", "Margarine"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'butter' heißt Butter."
  },
  {
    id: "q4_e_064",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Marmelade' auf Englisch?",
    answers: ["jam / marmalade", "honey", "butter", "sugar"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'jam' ist die allgemeine Bezeichnung für Marmelade."
  },
  {
    id: "q4_e_065",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'sugar'?",
    answers: ["Zucker", "Salz", "Mehl", "Pfeffer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'sugar' heißt Zucker."
  },
  {
    id: "q4_e_066",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'salt'?",
    answers: ["Salz", "Senf", "Essig", "Öl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'salt' bedeutet Salz."
  },
  {
    id: "q4_e_067",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'market'?",
    answers: ["Markt", "Bäckerei", "Kasse", "Regal"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'market' heißt Markt."
  },
  {
    id: "q4_e_068",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Bäckerei' auf Englisch?",
    answers: ["bakery", "supermarket", "butcher", "shop"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'bakery' heißt Bäckerei."
  },
  {
    id: "q4_e_069",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Metzgerei / Fleischer' auf Englisch?",
    answers: ["butcher's", "bakery", "pharmacy", "sweet shop"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'butcher's' ist die Metzgerei."
  },
  {
    id: "q4_e_070",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Süßigkeiten' auf Englisch?",
    answers: ["sweets / candy", "fruit", "cakes", "cookies"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'sweets' (britisch) oder 'candy' (amerikanisch) sind Süßigkeiten."
  },
  {
    id: "q4_e_071",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'cake'?",
    answers: ["Kuchen / Torte", "Keks", "Brot", "Schokolade"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'cake' ist der Kuchen."
  },
  {
    id: "q4_e_072",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'biscuit / cookie'?",
    answers: ["Keks / Plätzchen", "Kuchen", "Brötchen", "Bonbon"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'biscuit' (UK) oder 'cookie' (US) heißt Keks."
  },
  {
    id: "q4_e_073",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Fleisch' auf Englisch?",
    answers: ["meat", "fish", "chicken", "cheese"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'meat' heißt Fleisch."
  },
  {
    id: "q4_e_074",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Hähnchen / Huhn' auf Englisch?",
    answers: ["chicken", "beef", "pork", "duck"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'chicken' bedeutet Hähnchen."
  },
  {
    id: "q4_e_075",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet der Satz 'That is 3 pounds, please'?",
    answers: ["Das macht 3 Pfund, bitte.", "Das wiegt 3 Kilo.", "Geben Sie mir 3 Münzen.", "Ich kaufe 3 Sachen."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es ist der Zahlungsbetrag an der Kasse."
  },

  // ================================================================
  // 4. BODY, HEALTH & CLOTHES (25 Fragen)
  // ================================================================
  {
    id: "q4_e_076",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Kopf' auf Englisch?",
    answers: ["head", "hand", "hair", "heart"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'head' heißt Kopf."
  },
  {
    id: "q4_e_077",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Schultern' auf Englisch?",
    answers: ["shoulders", "knees", "toes", "arms"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'shoulders' sind die Schultern."
  },
  {
    id: "q4_e_078",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Knie' auf Englisch?",
    answers: ["knees", "toes", "legs", "feet"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'knees' sind die Knie."
  },
  {
    id: "q4_e_079",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Zehen' auf Englisch?",
    answers: ["toes", "fingers", "feet", "legs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'toes' sind die Zehen am Fuß."
  },
  {
    id: "q4_e_080",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Augen' auf Englisch?",
    answers: ["eyes", "ears", "mouth", "nose"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'eyes' sind die Augen."
  },
  {
    id: "q4_e_081",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Ohren' auf Englisch?",
    answers: ["ears", "eyes", "arms", "legs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'ears' sind die Ohren."
  },
  {
    id: "q4_e_082",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Mund' auf Englisch?",
    answers: ["mouth", "nose", "face", "chin"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'mouth' heißt Mund."
  },
  {
    id: "q4_e_083",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Nase' auf Englisch?",
    answers: ["nose", "mouth", "neck", "hair"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'nose' ist die Nase."
  },
  {
    id: "q4_e_084",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'headache'?",
    answers: ["Kopfschmerzen", "Bauchschmerzen", "Zahnschmerzen", "Halsschmerzen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'headache' besteht aus head (Kopf) + ache (Schmerz) = Kopfschmerzen."
  },
  {
    id: "q4_e_085",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'stomach ache'?",
    answers: ["Bauchschmerzen", "Kopfschmerzen", "Rückenschmerzen", "Ohrenschmerzen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'stomach ache' heißt Bauchschmerzen."
  },
  {
    id: "q4_e_086",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'toothache'?",
    answers: ["Zahnschmerzen", "Kopfschmerzen", "Fieber", "Husten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'toothache' heißt Zahnschmerzen."
  },
  {
    id: "q4_e_087",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'I have got a cold'?",
    answers: ["Ich habe eine Erkältung", "Mir ist kalt", "Ich habe Fieber", "Ich bin müde"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'to have a cold' heißt erkältet sein."
  },
  {
    id: "q4_e_088",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Arzt' auf Englisch?",
    answers: ["doctor", "teacher", "driver", "baker"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'doctor' heißt Arzt."
  },
  {
    id: "q4_e_089",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet der Satz 'I am ill'?",
    answers: ["Ich bin krank", "Ich bin gesund", "Ich bin traurig", "Ich bin müde"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'ill' (oder 'sick') heißt krank."
  },
  {
    id: "q4_e_090",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Pullover' auf Englisch?",
    answers: ["jumper / sweater", "trousers", "shirt", "coat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'jumper' (UK) oder 'sweater' (US) ist der Pullover."
  },
  {
    id: "q4_e_091",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schal' auf Englisch?",
    answers: ["scarf", "gloves", "hat", "cap"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'scarf' heißt Schal."
  },
  {
    id: "q4_e_092",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Handschuhe' auf Englisch?",
    answers: ["gloves", "socks", "boots", "shoes"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'gloves' sind die Handschuhe."
  },
  {
    id: "q4_e_093",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Stiefel' auf Englisch?",
    answers: ["boots", "shoes", "socks", "slippers"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'boots' sind Stiefel."
  },
  {
    id: "q4_e_094",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Put on your coat!'?",
    answers: ["Zieh deinen Mantel an!", "Zieh deinen Mantel aus!", "Kauf einen Mantel!", "Wasche deinen Mantel!"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'put on' heißt anziehen."
  },
  {
    id: "q4_e_095",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Take off your shoes!'?",
    answers: ["Zieh deine Schuhe aus!", "Zieh deine Schuhe an!", "Binde deine Schuhe!", "Putze deine Schuhe!"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'take off' heißt ausziehen."
  },
  {
    id: "q4_e_096",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'fingers'?",
    answers: ["Finger", "Zehen", "Hände", "Füße"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'fingers' sind die Finger an den Händen."
  },
  {
    id: "q4_e_097",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'feet' (Mehrzahl von foot)?",
    answers: ["Füße", "Beine", "Arme", "Hände"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "one foot (ein Fuß) -> two feet (zwei Füße)."
  },
  {
    id: "q4_e_098",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Bauch' auf Englisch?",
    answers: ["stomach / tummy", "back", "chest", "neck"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'stomach' (oder umgangssprachlich 'tummy') ist der Bauch."
  },
  {
    id: "q4_e_099",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Rücken' auf Englisch?",
    answers: ["back", "stomach", "arm", "shoulder"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'back' heißt Rücken."
  },
  {
    id: "q4_e_100",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Zähne' (Mehrzahl von tooth) auf Englisch?",
    answers: ["teeth", "tooths", "mouths", "lips"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "one tooth (ein Zahn) -> many teeth (viele Zähne)."
  }
];