const K4_SACHUNTERRICHT_QUESTIONS = [
  // ================================================================
  // 1. DEUTSCHLAND, BUNDESLÄNDER & EUROPA (25 Fragen)
  // ================================================================
  {
    id: "q4_s_001",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Landeshauptstadt von Nordrhein-Westfalen (NRW)?",
    answers: ["Düsseldorf", "Köln", "Dortmund", "Essen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Düsseldorf ist die Landeshauptstadt von NRW."
  },
  {
    id: "q4_s_002",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie viele Bundesländer hat Deutschland insgesamt?",
    answers: ["16", "14", "12", "18"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Deutschland besteht aus 16 Bundesländern."
  },
  {
    id: "q4_s_003",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Bundeshauptstadt von Deutschland?",
    answers: ["Berlin", "München", "Frankfurt", "Hamburg"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Berlin ist die Hauptstadt der Bundesrepublik Deutschland."
  },
  {
    id: "q4_s_004",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches der folgenden Länder ist ein Stadtstaat in Deutschland?",
    answers: ["Hamburg", "Bayern", "Hessen", "Sachsen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hamburg, Bremen und Berlin sind die drei Stadtstaaten Deutschlands."
  },
  {
    id: "q4_s_005",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches ist flächenmäßig das größte Bundesland Deutschlands?",
    answers: ["Bayern", "Nordrhein-Westfalen", "Niedersachsen", "Baden-Württemberg"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bayern ist das flächenmäßig größte Bundesland."
  },
  {
    id: "q4_s_006",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welcher Fluss ist der längste Fluss, der durch Deutschland fließt?",
    answers: ["Rhein", "Donau", "Elbe", "Mosel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Rhein ist die bedeutendste und längste Wasserstraße innerhalb Deutschlands."
  },
  {
    id: "q4_s_007",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt das höchste Gebirge Deutschlands?",
    answers: ["Die Alpen", "Der Harz", "Der Schwarzwald", "Die Eifel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Alpen im Süden Deutschlands bilden das höchste Gebirge."
  },
  {
    id: "q4_s_008",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt der höchste Berg Deutschlands?",
    answers: ["Zugspitze", "Feldberg", "Brocken", "Watzmann"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zugspitze in Bayern ist mit 2.962 m der höchste Berg Deutschlands."
  },
  {
    id: "q4_s_009",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche zwei Meere grenzen im Norden an Deutschland?",
    answers: ["Nordsee und Ostsee", "Mittelmeer und Ostsee", "Nordsee und Schwarzes Meer", "Ostsee und Atlantik"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Norden grenzt Deutschland an die Nordsee und die Ostsee."
  },
  {
    id: "q4_s_010",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Währung der meisten europäischen Länder in der Europäischen Union?",
    answers: ["Euro", "D-Mark", "Pfund", "Franken"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Euro (€) ist das gemeinsame Zahlungsmittel in vielen EU-Staaten."
  },
  {
    id: "q4_s_011",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Hauptstadt von Frankreich?",
    answers: ["Paris", "Rom", "Madrid", "London"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Paris ist die Hauptstadt unseres Nachbarlandes Frankreich."
  },
  {
    id: "q4_s_012",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Nachbarland liegt direkt westlich von Nordrhein-Westfalen?",
    answers: ["Niederlande", "Polen", "Österreich", "Dänemark"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Niederlande grenzen im Westen direkt an NRW."
  },
  {
    id: "q4_s_013",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Flagge der Europäischen Union (EU)?",
    answers: ["Blaues Feld mit 12 gelben Sternen im Kreis", "Schwarz-Rot-Goldene Streifen", "Rotes Feld mit gelbem Stern", "Blau-Weiß-Rot gestreift"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die EU-Flagge zeigt 12 goldene Sterne auf blauem Grund."
  },
  {
    id: "q4_s_014",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt das Nachbarland südlich von Deutschland, in dem man unter anderem Deutsch spricht?",
    answers: ["Österreich", "Belgien", "Tschechien", "Ungarn"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Österreich ist Deutschlands südliches Nachbarland mit Amtssprache Deutsch."
  },
  {
    id: "q4_s_015",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was bedeutet die Abkürzung 'EU'?",
    answers: ["Europäische Union", "Europäische Umwelt", "Europa-Unterkunft", "Einheitliche Union"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "EU steht für die Europäische Union."
  },
  {
    id: "q4_s_016",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Landeshauptstadt von Bayern?",
    answers: ["München", "Nürnberg", "Augsburg", "Stuttgart"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "München ist die Landeshauptstadt von Bayern."
  },
  {
    id: "q4_s_017",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt das Bundesland, das ganz im Norden an Dänemark grenzt?",
    answers: ["Schleswig-Holstein", "Niedersachsen", "Mecklenburg-Vorpommern", "Brandenburg"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Schleswig-Holstein liegt zwischen den Meeren ganz im Norden."
  },
  {
    id: "q4_s_018",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welcher Fluss fließt durch die Stadt Köln?",
    answers: ["Rhein", "Ruhr", "Donau", "Elbe"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Köln liegt am Rhein."
  },
  {
    id: "q4_s_019",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Nachbarland grenzt im Osten an Deutschland?",
    answers: ["Polen", "Frankreich", "Niederlande", "Schweiz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Polen und Tschechien liegen im Osten von Deutschland."
  },
  {
    id: "q4_s_020",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Hauptstadt von Italien?",
    answers: ["Rom", "Mailand", "Venedig", "Neapel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rom ist die Hauptstadt von Italien."
  },
  {
    id: "q4_s_021",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man die deutschen Bundesländer, die früher eigene Städte waren und keine großen Flächenländer sind?",
    answers: ["Stadtstaaten", "Hauptstädte", "Großkreise", "Bundesregionen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Berlin, Bremen und Hamburg heissen Stadtstaaten."
  },
  {
    id: "q4_s_022",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt das Gebirge, das NRW im Süden begrenzt?",
    answers: ["Eifel", "Alpen", "Harz", "Erzgebirge"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Eifel liegt im Südwesten von NRW."
  },
  {
    id: "q4_s_023",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt das Wappentier auf der Flagge des Bundespräsidenten und im Bundestag?",
    answers: ["Bundesadler", "Löwe", "Bär", "Falke"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Adler ist das Wappentier Deutschlands (Bundesadler)."
  },
  {
    id: "q4_s_024",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt die Landeshauptstadt von Hessen?",
    answers: ["Wiesbaden", "Frankfurt", "Kassel", "Darmstadt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Landeshauptstadt von Hessen ist Wiesbaden (Frankfurt ist die größte Stadt)."
  },
  {
    id: "q4_s_025",
    category: "k4_sachunterricht",
    topic: "deutschland_europa",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man das Grenz-Abkommen in der EU, durch das man meist ohne Passkontrolle von einem EU-Land ins andere reisen kann?",
    answers: ["Schengener Abkommen", "Europa-Pass", "Zollfrei-Gesetz", "Euro-Vertrag"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Das Schengener Abkommen hebt die Grenzkontrollen im Schengen-Raum auf."
  },

  // ================================================================
  // 2. GESCHICHTE (RÖMER, RITTER & STEINZEIT) (25 Fragen)
  // ================================================================
  {
    id: "q4_s_026",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Woraus bauten die Menschen in der Altsteinzeit ihre ersten Werkzeuge?",
    answers: ["Feuerstein, Knochen und Holz", "Eisen und Stahl", "Plastik", "Bronze"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Silex (Feuerstein) war der wichtigste Rohstoff für Schaber, Messer und Pfeilspitzen."
  },
  {
    id: "q4_s_027",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was bedeutet es, dass die Menschen in der Jungsteinzeit 'sesshaft' wurden?",
    answers: ["Sie bauten feste Häuser und betrieben Ackerbau und Viehzucht", "Sie wanderten ständig den Tieren hinterher", "Sie lebten nur noch in Höhlen", "Sie fuhren auf Schiffen über die Meere"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sesshaft werden heißt, an einem festen Ort zu bleiben, Felder zu bestellen und Tiere zu halten."
  },
  {
    id: "q4_s_028",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches ausgestorbene eiszeitliche Mammut-Verwandte Tier jagten die Menschen der Altsteinzeit?",
    answers: ["Mammut", "Dinosaurier", "Säbelzahntiger-Kuh", "Riesenelefant"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Mammut lieferte Fleisch, Fell für Kleidung und Elfenbein für Schnitzereien."
  },
  {
    id: "q4_s_029",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nannte man die befestigte Grenze des Römischen Reiches in Deutschland?",
    answers: ["Limes", "Römerwall", "Kaisermauer", "Siegfriedlinie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Limes war der Grenzwall der Römer gegen die germanischen Stämme."
  },
  {
    id: "q4_s_030",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche deutsche Großstadt in NRW wurde von den Römern gegründet (Colonia Claudia Ara Agrippinensium)?",
    answers: ["Köln", "Düsseldorf", "Duisburg", "Münster"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Köln geht auf eine bedeutende römische Kolonie zurück."
  },
  {
    id: "q4_s_031",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie hießen die römischen Wasserleitungen, die frisches Quellwasser über weite Strecken in die Städte leiteten?",
    answers: ["Aquädukte", "Viadukte", "Kanäle", "Thermen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Aquädukte transportierten Quellwasser über Steinbrücken in römische Städte."
  },
  {
    id: "q4_s_032",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man die öffentlichen Badeanstalten der Römer?",
    answers: ["Thermen", "Bäderhäuser", "Forum", "Amphitheater"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In den Thermen entspannten und wuschen sich die Römer."
  },
  {
    id: "q4_s_033",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie hieß der berühmteste römische Feldherr und spätere Diktator, der Gallien eroberte?",
    answers: ["Julius Cäsar", "Augustus", "Nero", "Spartacus"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gaius Julius Cäsar war ein bedeutender römischer Feldherr."
  },
  {
    id: "q4_s_034",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nannte man den jungen Knappen, bevor er nach jahrelanger Ausbildung zum Ritter geschlagen wurde?",
    answers: ["Knappe (vorher Page)", "Knecht", "Edelmann", "Söldner"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ein Junge begann als Page (ca. 7 Jahre), wurde mit 14 Knappe und mit 21 Ritter."
  },
  {
    id: "q4_s_035",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie hieß die Feierlichkeit, bei der ein Knappe offiziell in den Ritterstand erhoben wurde?",
    answers: ["Ritterschlag", "Kröung", "Taufe", "Turnier"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beim Ritterschlag erhielt der Knappe Schwert und Sporen."
  },
  {
    id: "q4_s_036",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche Schutzrüstung trugen Ritter im späten Mittelalter im Kampf?",
    answers: ["Kettenhemd und Plattenpanzer", "Lederjacke und Helm", "Stofftunica", "Holzschild allein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Ritter schützten sich mit schweren Eisenpanzern und Kettenhemden."
  },
  {
    id: "q4_s_037",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was ist ein 'Zugbrücke' bei einer mittelalterlichen Burg?",
    answers: ["Eine brücke über den Burggraben, die mit Ketten hochgezogen werden konnte", "Eine Brücke für die Eisenbahn", "Eine feste Steinbrücke", "Eine Brücke aus Seilen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zugbrücke verhinderte bei Gefahr das Eindringen von Feinden."
  },
  {
    id: "q4_s_038",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißt der höchste und am stärksten befestigte Turm im Zentrum einer Ritterburg?",
    answers: ["Bergfried", "Wachturm", "Wehrturm", "Glockenturm"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Bergfried diente als letzte Zuflucht bei einer Belagerung."
  },
  {
    id: "q4_s_039",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Zeitalter folgte auf die Steinzeit, als die Menschen lernten, Metalle zu schmelzen?",
    answers: ["Bronzezeit (und danach Eisenzeit)", "Ritterzeit", "Neuzeit", "Mittelalter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach der Steinzeit begann das Zeitalter der Metalle (Kupfer-, Bronze- und Eisenzeit)."
  },
  {
    id: "q4_s_040",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißen die Kampfspiele, bei denen Ritter auf Pferden mit Lanzen gegeneinander antraten?",
    answers: ["Turnier (Lanzenstechen)", "Olympiade", "Zirkus", "Schlacht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Auf Turnieren bewiesen Ritter Mut, Kraft und Geschicklichkeit."
  },
  {
    id: "q4_s_041",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nannte man das Schriftzeichen-System der alten Ägypter?",
    answers: ["Hieroglyphen", "Römische Zahlen", "Keilschrift", "Alphabet"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Ägypter schrieben mit Bildzeichen, den Hieroglyphen."
  },
  {
    id: "q4_s_042",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was lag mitten im Römischen Reich als zentraler Versammlungs- und Marktplatz einer Stadt?",
    answers: ["Forum", "Colosseum", "Zirkus", "Kapitol"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Forum (z. B. Forum Romanum in Rom) war der Marktplatz und das politische Zentrum."
  },
  {
    id: "q4_s_043",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nannte man den Schutzmantel / die Tunika der römischen Bürger?",
    answers: ["Toga", "Rüstung", "Kettenhemd", "Kutte"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Freie römische Bürger trugen zu feierlichen Anlässen eine Toga."
  },
  {
    id: "q4_s_044",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wer kämpfte im römischen Amphitheater (z. B. dem Kolosseum) zur Unterhaltung des Volks?",
    answers: ["Gladiatoren", "Ritter", "Knappen", "Legionäre"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gladiatoren waren bewaffnete Kämpfer in den Arenen des Römischen Reiches."
  },
  {
    id: "q4_s_045",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man die Götterwelt oder Kultur der Germanen und Römer im Vergleich zum Christentum?",
    answers: ["Mehrgötterglaube (Polytheismus)", "Monotheismus", "Steinzeitreligion", "Ritualismus"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Sowohl Römer (Jupiter, Mars...) als auch Germanen (Thor, Odin...) verehrten viele verschiedene Götter."
  },
  {
    id: "q4_s_046",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie hieß der berühmte Eismann aus der Kupferzeit, der in den Alpen im Eis gefunden wurde?",
    answers: ["Ötzi", "Lucy", "Cäsar", "Siegfried"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ötzi ist eine Mumie aus der Jungsteinzeit/Kupferzeit (ca. 5.300 Jahre alt)."
  },
  {
    id: "q4_s_047",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißen die Wappen, die Ritter auf Schilden trugen, um im Kampf erkannt zu werden?",
    answers: ["Familien- / Ritterwappen", "Fahnenzeichen", "Kaiserstempel", "Siegel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Da der Helm das Gesicht verdeckte, erkannte man Ritter an ihrem bunten Wappen auf dem Schild."
  },
  {
    id: "q4_s_048",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nannte man die Handwerker und Bauern, die im Mittelalter auf den Feldern des Adels arbeiten mussten?",
    answers: ["Leibeigene / Hörige Bauern", "Ritter", "Bürger", "Gildenmeister"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Leibeigene Bauern waren vom Grundherrn abhängig und mussten Abgaben leisten."
  },
  {
    id: "q4_s_049",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wer erfand um 1450 den Buchdruck mit beweglichen Metallbuchstaben in Deutschland?",
    answers: ["Johannes Gutenberg", "Martin Luther", "Leonardo da Vinci", "Albert Einstein"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Johannes Gutenberg revolutionierte das Vervielfältigen von Büchern."
  },
  {
    id: "q4_s_050",
    category: "k4_sachunterricht",
    topic: "geschichte_kultur",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Zeitalter folgte auf das Mittelalter (ab ca. 1500)?",
    answers: ["Neuzeit", "Steinzeit", "Römerzeit", "Zukunft"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit der Entdeckung Amerikas und dem Buchdruck begann die Neuzeit."
  },

  // ================================================================
  // 3. KÖRPER & ENTWICKLUNG (14 Fragen)
  // ================================================================
  {
    id: "q4_s_051",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man die Entwicklungsphase vom Kind zum Jugendlichen / Erwachsenen?",
    answers: ["Pubertät", "Babyzeit", "Erwachsenenalter", "Seniorenzeit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In der Pubertät verändert sich der Körper körperlich und seelisch."
  },
  {
    id: "q4_s_052",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heissen die chemischen Botenstoffe im Körper, die das Wachstum und die Pubertät steuern?",
    answers: ["Hormone", "Vitamine", "Enzyme", "Muskeln"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hormone steuern die körperlichen Veränderungen während des Wachstums."
  },
            {
    id: "q4_s_058",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was bleibt am Bauch eines jeden Menschen als Erinnerung an die Geburt zurück?",
    answers: ["Bauchnabel", "Muttermal", "Leberfleck", "Narbe am Arm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Bauchnabel ist die Stelle, wo die Nabelschnur nach der Geburt abgetrennt wurde."
  },
  {
    id: "q4_s_059",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche körperliche Veränderung tritt bei Jungen in der Pubertät durch das Stimmwachstum auf?",
    answers: ["Stimmbruch (die Stimme wird tiefer)", "Die Stimme wird höher", "Man verliert das Sprechen", "Keine Veränderung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beim Stimmbruch wächst der Kehlkopf und die Stimme wird tiefer."
  },
      {
    id: "q4_s_062",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Organ im Körper pumpt das Blut durch die Adern?",
    answers: ["Herz", "Lunge", "Gehirn", "Leber"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Herz ist der Hohlmuskel, der das Blut kontinuierlich pumpt."
  },
  {
    id: "q4_s_063",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Organ ist für das Aufnehmen von Sauerstoff aus der Luft zuständig?",
    answers: ["Lunge", "Magen", "Niere", "Darm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Über die Lunge gelangt Sauerstoff ins Blut."
  },
  {
    id: "q4_s_064",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Organ filtert Abfallstoffe aus dem Blut und bildet Urin?",
    answers: ["Nieren", "Herzen", "Lungenflügel", "Gallenblase"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die beiden Nieren reinigen das Blut stetig."
  },
  {
    id: "q4_s_065",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was gehört zu den guten Hygienemaßnahmen in der Pubertät, da man schneller schwitzt?",
    answers: ["Regelmäßig duschen und frische Kleidung tragen", "Weniger trinken", "Gar nicht mehr bewegen", "Nichts verändern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Körperpflege gewinnt in der Pubertät an Bedeutung, da Schweißdrüsen aktiver werden."
  },
    {
    id: "q4_s_067",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man die Phase, in der die Knochen in der Pubertät besonders rasch wachsen?",
    answers: ["Wachstumsschub", "Knochenbruch", "Dehnungsschmerz", "Reifungsstopp"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Während eines Wachstumsschubs nimmt die Körpergröße schnell zu."
  },
  {
    id: "q4_s_068",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Darfst du 'Nein' sagen, wenn jemand deine persönlichen Grenzen verletzt oder dir eine Berührung unangenehm ist?",
    answers: ["Ja, absolut! Mein Körper gehört mir und ich darf Stopp sagen", "Nein, man muss immer gehorchen", "Nur bei Fremden", "Nur wenn ein Lehrer daneben steht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Jeder Mensch hat das Recht auf körperliche Selbstbestimmung (Mein Körper gehört mir)."
  },
  {
    id: "q4_s_069",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was verändert sich in der Pubertät neben dem Körper auch sehr stark?",
    answers: ["Gefühle und Stimmungsschwankungen", "Die Augenfarbe", "Der Name", "Die Anzahl der Zähne"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Durch Hormone verändern sich auch Emotionen und Wahrnehmungen."
  },
      {
    id: "q4_s_072",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was ist Mitose?",
    answers: ["Zellteilung, bei der aus einer Zelle zwei identische Tochterzellen entstehen", "Ein Knochenkrankheit", "Der Herzschlag", "Die Verdauung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Durch Zellteilung (Mitose) wächst der menschliche Körper."
  },
    {
    id: "q4_s_074",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man die Vererbung von Eigenschaften (z. B. Augenfarbe, Haare) von den Eltern auf die Kinder?",
    answers: ["Genetik / Vererbung", "Impfung", "Erziehung", "Gewöhnung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Über Gene (Erbanlagen) werden körperliche Merkmale vererbt."
  },
  {
    id: "q4_s_075",
    category: "k4_sachunterricht",
    topic: "koerper_entwicklung",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Warum bekommen Jugendliche in der Pubertät manchmal Mitesser oder Pickel?",
    answers: ["Weil Talgdrüsen in der Haut durch Hormone mehr Hautfett produzieren", "Weil man zu viel schläft", "Weil man Sport treibt", "Weil die Haut austrocknet"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hormone aktivieren die Talgdrüsen, was zu unreiner Haut führen kann."
  },

  // ================================================================
  // 4. RADFAHRPRÜFUNG, VERKEHR & TECHNIK (25 Fragen)
  // ================================================================
  {
    id: "q4_s_076",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Ausrüstungsstück ist zwar laut Gesetz keine Pflicht, schützt aber den Kopf bei Stürzen lebensrettend?",
    answers: ["Fahrradhelm", "Klingel", "Rückstrahler", "Schutzblech"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Fahrradhelm verhindert schwere Kopfverletzungen."
  },
  {
    id: "q4_s_077",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie viele voneinander unabhängige Bremsen muss ein verkehrssicheres Fahrrad haben?",
    answers: ["Zwei Bremsen (Vorderrad- und Hinterradbremse)", "Eine Bremse reicht", "Drei Bremsen", "Vier Bremsen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Fahrrad muss zwei getrennt voneinander funktionierende Bremsen besitzen."
  },
  {
    id: "q4_s_078",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche Farbe hat der Scheinwerfer vorne am Fahrrad?",
    answers: ["Weiß", "Rot", "Gelb", "Grün"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Vorderlicht leuchtet stets weiß."
  },
  {
    id: "q4_s_079",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche Farbe hat das Rücklicht am Fahrrad?",
    answers: ["Rot", "Weiß", "Gelb", "Blau"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Rücklicht und der hintere Reflektor leuchten rot."
  },
  {
    id: "q4_s_080",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie viele Reflektoren (Katzenaugen) gehören mindestens in die Speichen jedes Raades?",
    answers: ["Zwei gelbe Speichenreflektoren pro Rad (oder zusammenhängende weiße Reflektorstreifen)", "Einer pro Rad", "Keine Pflicht", "Vier pro Rad"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mindestens zwei gelbe Reflektoren pro Rad oder durchgehende Speichen-Reflektorhüllen."
  },
  {
    id: "q4_s_081",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was bedeutet das Verkehrszeichen 'Rechts vor Links' an Kreuzungen ohne Schilder?",
    answers: ["Fahrzeuge von rechts haben Vorfahrt", "Fahrzeuge von links haben Vorfahrt", "Wer schneller ist darf fahren", "Radfahrer haben immer Vorfahrt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gibt es keine Ampeln oder Schilder, gilt: Rechts vor Links."
  },
  {
    id: "q4_s_082",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie heißen die Schritte beim Linksabbiegen mit dem Fahrrad in der richtigen Reihenfolge?",
    answers: ["Umschauen -> Handzeichen geben -> Einordnen -> Vorfahrt beachten -> Abbiegen", "Abbiegen -> Handzeichen -> Schauen", "Handzeichen -> Abbiegen", "Sofort abbiegen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Abbiege-Reihenfolge sichert das Überleben im Straßenverkehr."
  },
  {
    id: "q4_s_083",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was versteht man unter dem 'Toten Winkel' bei Lkws oder Bussen?",
    answers: ["Der Bereich rund um das Fahrzeug, den der Fahrer im Spiegel nicht sehen kann", "Der Motorraum", "Der Kofferraum", "Die Scheinwerferzone"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Toten Winkel wird man vom Lkw-Fahrer leicht übersehen – niemals neben abbiegenden Lkws stehenbleiben!"
  },
  {
    id: "q4_s_084",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche Form und Farbe hat das Vorfahrt-Gewähren-Schild?",
    answers: ["Dreieck auf der Spitze mit rotem Rand und weißem Feld", "Runder roter Kreis", "Blaues Quadrat", "Achteckiges rotes Schild"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Schild steht auf der Spitze (Dreieck) mit rotem Rand."
  },
  {
    id: "q4_s_085",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche Form hat das 'STOPP'-Schild als einziges Verkehrszeichen?",
    answers: ["Achteckig (rot mit weißer Aufschrift STOPP)", "Rund", "Dreieckig", "Quadratisch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Stoppschild ist achteckig, damit man es auch bei Schnee von hinten erkennt."
  },
  {
    id: "q4_s_086",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Auf welcher Straßenseite fährt man mit dem Fahrrad in Deutschland auf der Fahrbahn?",
    answers: ["Rechts", "Links", "In der Mitte", "Egal"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In Deutschland gilt das Rechtsfahrgebot."
  },
  {
    id: "q4_s_087",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Bis zu welchem Alter DÜRFEN Kinder in NRW auf dem Gehweg mit dem Fahrrad fahren?",
    answers: ["Bis zum vollendeten 10. Lebensjahr (bis 8 Jahre MÜSSEN sie es)", "Bis 14 Jahre", "Gar nicht", "Bis 18 Jahre"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bis 8 Jahre müssen Kinder auf den Gehweg, bis 10 Jahre dürfen sie ihn noch nutzen."
  },
  {
    id: "q4_s_088",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was baut man in einen einfachen Stromkreis ein, um den Stromfluss bequem zu unterbrechen?",
    answers: ["Schalter", "Klingel", "Spule", "Magnet"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Schalter öffnet oder schließt den Stromkreis."
  },
  {
    id: "q4_s_089",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Metall leitet elektrischen Strom besonders gut und wird in Kabeln verwendet?",
    answers: ["Kupfer", "Holz", "Gummi", "Plastik"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kupfer leitet den elektrischen Strom hervorragend."
  },
  {
    id: "q4_s_090",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man Materialien (wie Plastik oder Gummi), die den Strom NICHT leiten?",
    answers: ["Isolatoren", "Leiter", "Pole", "Stromquellen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Isolatoren schützen uns vor Stromschlägen."
  },
  {
    id: "q4_s_091",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welche zwei Pole besitzt jeder Magnet?",
    answers: ["Nordpol und Südpol", "Ostpol und Westpol", "Pluspol und Minuspol", "Oberpol und Unterpol"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Magnet hat immer einen Nordpol und einen Südpol."
  },
  {
    id: "q4_s_092",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was passiert, wenn man zwei gleiche Pole zweier Magnete (z. B. Nordpol und Nordpol) aneinanderhält?",
    answers: ["Sie stoßen sich ab", "Sie ziehen sich an", "Nichts passiert", "Sie werden heiß"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gleiche Pole stoßen sich ab, ungleiche Pole ziehen sich an."
  },
  {
    id: "q4_s_093",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Welches Metall zieht ein Magnet an?",
    answers: ["Eisen (und Nickel/Kobalt)", "Aluminium", "Gold", "Kupfer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Magnete ziehen magnetische Stoffe wie Eisen an."
  },
  {
    id: "q4_s_094",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was treibt beim Fahrrad das Licht an, wenn kein Akku verbaut ist?",
    answers: ["Dynamo", "Motor", "Bremskabel", "Kette"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Dynamo wandelt Bewegung in elektrischen Strom um."
  },
  {
    id: "q4_s_095",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was zeigt die Nadel eines Kompasses immer an?",
    answers: ["Den magnetischen Nordpol der Erde", "Die Sonne", "Den Süden", "Den Wind"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Kompassnadel richtet sich am Magnetfeld der Erde nach Norden aus."
  },
  {
    id: "q4_s_096",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Warum darf man niemals an Haushaltssteckdosen (230 Volt) experimentieren?",
    answers: ["Weil Netzstrom lebensgefährlich ist!", "Weil die Sicherung rausfliegt", "Weil es langweilig ist", "Weil Batterien teurer sind"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "230 Volt Wechselstrom aus der Steckdose kann tödlich sein. Experimente nur mit Batterien (z. B. 4,5V oder 9V) machen!"
  },
  {
    id: "q4_s_097",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was bedeutet das blaue runde Verkehrszeichen mit einem Fahrrad darauf?",
    answers: ["Benutzungspflichtiger Radweg", "Verbot für Radfahrer", "Gefahrenstelle für Räder", "Fahrradgeschäft"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Blau + rund = Gebot! Dieser Radweg muss benutzt werden."
  },
  {
    id: "q4_s_098",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Was bedeutet ein roter Kreis als Verkehrszeichen (z. B. mit einem Fahrrad im Kreis)?",
    answers: ["Verbot für Fahrradfahrer", "Vorfahrt für Fahrräder", "Radweg beginnt", "Empfohlene Strecke"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rot umrandete runde Schild drücke Verbote aus."
  },
  {
    id: "q4_s_099",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Wie nennt man ein Radgetriebe, das Kraft und Geschwindigkeit überträgt (wie beim Fahrrad)?",
    answers: ["Kettenantrieb (Kette + Zahnräder)", "Riemenmotor", "Hebelgesetz", "Magnetantrieb"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Pedaltreten wird über die Kette auf das Hinterrad übertragen."
  },
  {
    id: "q4_s_100",
    category: "k4_sachunterricht",
    topic: "radfahrpruefung_technik",
    area: "schule",
    grade: 4,
    subject: "sachunterricht",
    question: "Warum müssen die Pedale des Fahrrads mit Reflektoren ausgestattet sein?",
    answers: ["Damit man die Tretbewegung im Dunkeln von vorne und hinten gut erkennt (jeweils 2 pro Pedal)", "Damit sie im Dunkeln leuchten", "Aus Verschönerungsgründen", "Damit die Füße Halt haben"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Pedalreflektoren (nach vorne und hinten leuchtend) sind gesetzlich vorgeschrieben."
  }
];