const K4_MATHE_QUESTIONS = [
  // ================================================================
  // 1. MILLIONENRAUM & ORIENTIERUNG (25 Fragen)
  // ================================================================
  {
    id: "q4_m_001",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welche Zahl besteht aus 5 Hunderttausendern, 3 Zehntausendern, 4 Hundertern und 2 Einern?",
    answers: ["350.402", "534.002", "503.402", "530.402"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "5 HT (500.000) + 3 ZT (30.000) + 0 T + 4 H (400) + 0 Z + 2 E = 530.402."
  },
  {
    id: "q4_m_002",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist der Nachfolger der Zahl 999.999?",
    answers: ["1.000.001", "999.990", "1.000.000 (1 Million)", "100.000"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Zählt man zur 999.999 eins hinzu, erhält man 1.000.000 (1 Million)."
  },
  {
    id: "q4_m_003",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist der Vorgänger der Zahl 500.000?",
    answers: ["500.001", "400.000", "490.000", "499.999"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt vor 500.000 steht 499.999."
  },
  {
    id: "q4_m_004",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie lauten die Nachbartausender von 45.600?",
    answers: ["45.000 und 46.000", "40.000 und 50.000", "45.500 und 45.700", "45.000 und 50.000"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der reine Tausender davor ist 45.000, der danach 46.000."
  },
  {
    id: "q4_m_005",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Runde die Zahl 472.000 auf Hunderttausender.",
    answers: ["400.000", "500.000", "480.000", "470.000"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Da an der Zehntausenderstelle eine 7 steht, wird auf 500.000 aufgerundet."
  },
  {
    id: "q4_m_006",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ergänze zur 1 Million: 600.000 + __ = 1.000.000",
    answers: ["300.000", "500.000", "600.000", "400.000"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "600.000 + 400.000 = 1.000.000."
  },
  {
    id: "q4_m_007",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welches Zeichen passt: 754.300 __ 745.300?",
    answers: [">", "+", "=", "<"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "754.300 ist größer als 745.300 (754.300 > 745.300)."
  },
  {
    id: "q4_m_008",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Zehntausender stecken in 100.000?",
    answers: ["10", "1.000", "100", "5"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 mal 10.000 = 100.000."
  },
  {
    id: "q4_m_009",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Zähle in 50.000er-Schritten weiter: 150.000, 200.000, __",
    answers: ["300.000", "250.000", "210.000", "205.000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Immer 50.000 dazu: 200.000 + 50.000 = 250.000."
  },
  {
    id: "q4_m_010",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist die Hälfte von 1.000.000?",
    answers: ["100.000", "500.000", "750.000", "250.000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "1.000.000 geteilt durch 2 = 500.000."
  },
  {
    id: "q4_m_011",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Runde die Zahl 3.480 auf volle Tausender.",
    answers: ["3.000", "3.400", "4.000", "3.500"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "An der Hunderterstelle steht eine 4 -> abrunden auf 3.000."
  },
  {
    id: "q4_m_012",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Runde die Zahl 3.520 auf volle Tausender.",
    answers: ["3.600", "3.500", "3.000", "4.000"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "An der Hunderterstelle steht eine 5 -> aufrunden auf 4.000."
  },
  {
    id: "q4_m_013",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie lauten die Nachbarzehntausender der Zahl 73.000?",
    answers: ["72.000 und 74.000", "70.000 und 80.000", "60.000 und 80.000", "70.000 und 75.000"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Zehntausender davor ist 70.000, der danach 80.000."
  },
  {
    id: "q4_m_014",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie schreibt man 'zweihundertfünfundfünfzigtausend' als Zahl?",
    answers: ["250.500", "205.500", "552.000", "255.000"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Zweihundertfünfundfünfzig Tausender = 255.000."
  },
  {
    id: "q4_m_015",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welche Zahl besteht aus 3 Hunderttausendern, 9 Tausendern und 1 Zehner?",
    answers: ["309.010", "390.100", "309.100", "390.010"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "3 HT (300.000) + 0 ZT + 9 T (9.000) + 0 H + 1 Z (10) + 0 E = 309.010."
  },
  {
    id: "q4_m_016",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ergibt 1.000.000 minus 1?",
    answers: ["999.999", "999.000", "999.990", "900.000"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Einer weniger als 1 Million ist 999.999."
  },
  {
    id: "q4_m_017",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 450.000 + 350.000?",
    answers: ["700.000", "850.000", "750.000", "800.000"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "450 + 350 = 800 (Tausend)."
  },
  {
    id: "q4_m_018",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 1.000.000 - 200.000?",
    answers: ["800.000", "700.000", "850.000", "900.000"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 Hunderttausender - 2 Hunderttausender = 8 Hunderttausender (800.000)."
  },
  {
    id: "q4_m_019",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welche Zahl liegt genau in der Mitte zwischen 300.000 und 400.000?",
    answers: ["340.000", "350.000", "360.000", "325.000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Mitte von 300.000 und 400.000 ist 350.000."
  },
  {
    id: "q4_m_020",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist die größte 6-stellige Zahl?",
    answers: ["1.000.000", "900.000", "999.000", "999.999"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "999.999 hat 6 Stellen und ist die größte davon."
  },
  {
    id: "q4_m_021",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist die kleinste 6-stellige Zahl?",
    answers: ["99.999", "111.111", "100.001", "100.000"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "100.000 ist die kleinste 6-stellige Zahl."
  },
  {
    id: "q4_m_022",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Hunderter sind in 10.000 enthalten?",
    answers: ["1.000 Hunderter", "100 Hunderter", "50 Hunderter", "10 Hunderter"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "100 × 100 = 10.000."
  },
  {
    id: "q4_m_023",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 700.000 - 350.000?",
    answers: ["450.000", "350.000", "300.000", "400.000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Hälfte von 700.000 ist 350.000."
  },
  {
    id: "q4_m_024",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was bedeutet die Abkürzung 'ZT' in der Stellenwerttafel?",
    answers: ["Zehnhunderter", "Zehner", "Zehntausender", "Zentimeter"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'ZT' steht für Zehntausender."
  },
  {
    id: "q4_m_025",
    category: "k4_mathe",
    topic: "millionenraum",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was bedeutet die Abkürzung 'HT' in der Stellenwerttafel?",
    answers: ["Haupttausender", "Hunderter", "Hunderttausender", "Hochtausender"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'HT' steht für Hunderttausender."
  },

  // ================================================================
  // 2. SCHRIFTLICHE MULTIPLIKATION & DIVISION (25 Fragen)
  // ================================================================
  {
    id: "q4_m_026",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 324 × 3 =",
    answers: ["974", "972", "872", "962"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 × 4 = 12, 3 × 20 = 60 (+10) = 70, 3 × 300 = 900 -> 972."
  },
  {
    id: "q4_m_027",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 150 × 4 =",
    answers: ["600", "650", "550", "500"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "150 × 4 = 600."
  },
  {
    id: "q4_m_028",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 484 : 4 =",
    answers: ["112", "121", "124", "122"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4:4=1, 8:4=2, 4:4=1 -> 121."
  },
  {
    id: "q4_m_029",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 963 : 3 =",
    answers: ["321", "323", "312", "331"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "9:3=3, 6:3=2, 3:3=1 -> 321."
  },
  {
    id: "q4_m_030",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 23 × 100?",
    answers: ["230.000", "2.300", "230", "23.000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Multiplikation mit 100 hängt man zwei Nullen an."
  },
  {
    id: "q4_m_031",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 4.500 : 10?",
    answers: ["45.000", "4.500", "450", "45"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Division durch 10 streicht man eine Null."
  },
  {
    id: "q4_m_032",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne mit Zehnerzahlen: 30 × 40 =",
    answers: ["120", "1.200", "1.400", "12.000"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 × 4 = 12 -> zwei Nullen anhängen = 1.200."
  },
  {
    id: "q4_m_033",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne mit Zehnerzahlen: 70 × 80 =",
    answers: ["6.400", "560", "56.000", "5.600"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "7 × 8 = 56 -> zwei Nullen anhängen = 5.600."
  },
  {
    id: "q4_m_034",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 5.600 : 70?",
    answers: ["70", "800", "8", "80"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "56 : 7 = 8 -> Nullen verrechnen = 80."
  },
  {
    id: "q4_m_035",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 142 × 5 =",
    answers: ["710", "610", "715", "705"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "5 × 2 = 10, 5 × 40 = 200 (+10) = 210, 5 × 100 = 500 (+200) = 710."
  },
  {
    id: "q4_m_036",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 628 : 2 =",
    answers: ["304", "324", "314", "312"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "6:2=3, 2:2=1, 8:2=4 -> 314."
  },
  {
    id: "q4_m_037",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Schriftliche Division mit Rest: 125 : 4 =",
    answers: ["32 Rest 0", "30 Rest 5", "31 Rest 2", "31 Rest 1"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "120 : 4 = 30; 5 : 4 = 1 Rest 1 -> 31 Rest 1."
  },
  {
    id: "q4_m_038",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 500 × 6?",
    answers: ["30.000", "3.500", "300", "3.000"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "5 × 6 = 30 -> zwei Nullen anhängen = 3.000."
  },
  {
    id: "q4_m_039",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 4.000 : 50?",
    answers: ["80", "800", "40", "8"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "400 : 5 = 80."
  },
  {
    id: "q4_m_040",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was passiert mit den Nullen bei der Multiplikation einer Zahl mit 1.000?",
    answers: ["Zwei Nullen werden gestrichen", "Es verändert sich nichts im Alltag", "Drei Nullen werden hinten angehängt", "Eine Null wird angehängt im Alltag"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Tausendfache einer Zahl bekommt 3 Nullen am Ende."
  },
  {
    id: "q4_m_041",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 412 × 2 =",
    answers: ["624", "824", "834", "814"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "412 mal 2 = 824."
  },
  {
    id: "q4_m_042",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 755 : 5 =",
    answers: ["161", "151", "141", "155"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "7:5=1 (Rest 2), 25:5=5, 5:5=1 -> 151."
  },
  {
    id: "q4_m_043",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 80 × 900?",
    answers: ["720.000", "7.200", "64.000", "72.000"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "8 × 9 = 72 -> drei Nullen anhängen = 72.000."
  },
  {
    id: "q4_m_044",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was ist 36.000 : 6?",
    answers: ["600", "60", "60.000", "6.000"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "36 : 6 = 6 -> drei Nullen anhängen = 6.000."
  },
  {
    id: "q4_m_045",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wende die Punkt-vor-Strich-Regel an: 10 + 5 × 4 =",
    answers: ["60", "20", "40", "30"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Zuerst Mal rechnen: 5 × 4 = 20. Danach Plus: 10 + 20 = 30."
  },
  {
    id: "q4_m_046",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wende die Punkt-vor-Strich-Regel an: 50 - 20 : 2 =",
    answers: ["30", "15", "40", "25"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Zuerst Geteilt rechnen: 20 : 2 = 10. Dann Minus: 50 - 10 = 40."
  },
  {
    id: "q4_m_047",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was rechnet man bei Klammern zuerst: (10 + 5) × 4 =",
    answers: ["30", "50", "60", "40"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Klammern haben Vorrang! Zuerst (10+5)=15, dann 15 × 4 = 60."
  },
  {
    id: "q4_m_048",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 203 × 4 =",
    answers: ["824", "812", "802", "816"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "4 × 3 = 12, 4 × 0 = 0 (+1) = 1, 4 × 200 = 800 -> 812."
  },
  {
    id: "q4_m_049",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Rechne schriftlich: 840 : 4 =",
    answers: ["210", "201", "240", "220"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "8:4=2, 4:4=1, 0:4=0 -> 210."
  },
  {
    id: "q4_m_050",
    category: "k4_mathe",
    topic: "schriftliche_multiplikation_division",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welcher Überschlag passt am besten zu 49 × 31?",
    answers: ["40 × 30 = 1.200", "50 × 40 = 2.000", "50 × 30 = 1.500", "40 × 40 = 1.600"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "49 ist nah an 50, 31 ist nah an 30 -> 50 × 30 = 1.500."
  },

  // ================================================================
  // 3. UMFANG, FLÄCHEN, GEOMETRIE & WINKEL (25 Fragen)
  // ================================================================
  {
    id: "q4_m_051",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie berechnet man den UMFANG eines Rechtecks?",
    answers: ["Alle 4 Seiten zusammenzählen (a + b + a + b)", "Länge durch Breite teilen in der Praxis", "Nur zwei Seiten addieren in der Praxis", "Länge mal Breite rechnen (a × b) zur Auswahl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Umfang ist die Gesamtlänge der Umrandung (alle Seiten addieren)."
  },
  {
    id: "q4_m_052",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Rechteck hat die Seiten a = 5 cm und b = 3 cm. Wie groß ist sein Umfang?",
    answers: ["15 cm", "16 cm", "30 cm", "8 cm"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Umfang = 5 cm + 3 cm + 5 cm + 3 cm = 16 cm."
  },
  {
    id: "q4_m_053",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Quadrat hat eine Seitenlänge von a = 4 cm. Wie groß ist sein Umfang?",
    answers: ["12 cm", "16 cm", "20 cm", "8 cm"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Umfang des Quadrats = 4 × 4 cm = 16 cm."
  },
  {
    id: "q4_m_054",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie berechnet man den FLÄCHENINHALT eines Rechtecks?",
    answers: ["Länge mal Breite (a × b)", "Durchmesser geteilt durch 2", "Alle 4 Seiten zusammenzählen", "Länge plus Breite"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Flächeninhalt A = Seite a × Seite b."
  },
  {
    id: "q4_m_055",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Rechteck hat a = 6 cm und b = 4 cm. Wie groß ist der Flächeninhalt?",
    answers: ["24 cm²", "20 cm", "10 cm²", "24 cm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Flächeninhalt = 6 cm × 4 cm = 24 Quadratzentimeter (cm²)."
  },
  {
    id: "q4_m_056",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Quadrat hat eine Seitenlänge von 5 cm. Wie groß ist sein Flächeninhalt?",
    answers: ["10 cm²", "25 cm", "25 cm²", "20 cm²"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Flächeninhalt = 5 cm × 5 cm = 25 cm²."
  },
  {
    id: "q4_m_057",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man einen exakten 90-Grad-Winkel (z. B. in einer Tischecke)?",
    answers: ["Stumpfer Winkel", "Rechter Winkel", "Runder Winkel", "Spitzer Winkel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein 90°-Winkel heißt rechter Winkel."
  },
  {
    id: "q4_m_058",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man einen Winkel, der kleiner als 90 Grad ist?",
    answers: ["Flacher Winkel", "Spitzer Winkel", "Stumpfer Winkel", "Rechter Winkel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Winkel unter 90° heissen spitze Winkel."
  },
  {
    id: "q4_m_059",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man einen Winkel, der größer als 90 Grad ist (aber kleiner als 180°)?",
    answers: ["Spitzer Winkel", "Stumpfer Winkel", "Rechter Winkel", "Gestreckter Winkel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Winkel zwischen 90° und 180° nennt man stumpfe Winkel."
  },
  {
    id: "q4_m_060",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man zwei Geraden, die überall denselben Abstand haben und sich nie schneiden?",
    answers: ["Symmetrische Linien", "Diagonale Linien", "Senkrechte Linien", "Parallele Linien"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Parallele Linien laufen nebeneinander wie Schienen und treffen sich nie."
  },
  {
    id: "q4_m_061",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man zwei Linien, die sich in einem rechten Winkel (90°) schneiden?",
    answers: ["Waagerechte Linien", "Parallele Linien", "Senkrechte Linien", "Krumme Linien"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Stehen zwei Linien rechtwinklig aufeinander, sind sie senkrecht zueinander."
  },
  {
    id: "q4_m_062",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welcher Körper hat 6 quadratische Begrenzungsflächen?",
    answers: ["Quader", "Würfel", "Pyramide", "Zylinder"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Würfel besteht aus 6 deckungsgleichen Quadraten."
  },
  {
    id: "q4_m_063",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welcher Körper hat eine kreisförmige Grundfläche und eine Spitze oben?",
    answers: ["Zylinder", "Kegel", "Prisma", "Kugel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Kegel (wie eine Schultüte) hat eine runde Grundfläche und eine Spitze."
  },
  {
    id: "q4_m_064",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welcher Körper hat zwei kreisförmige Grund- und Deckflächen (z. B. wie eine Dose)?",
    answers: ["Kugel", "Zylinder", "Würfel", "Kegel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Zylinder besitzt zwei parallele Kreisflächen."
  },
  {
    id: "q4_m_065",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welcher Körper hat dreieckige Seitenflächen, die oben in einer Spitze zusammenlaufen?",
    answers: ["Pyramide", "Zylinder", "Würfel", "Quader"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Pyramide hat Dreiecke als Seitenflächen und eine Spitze."
  },
  {
    id: "q4_m_066",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man die Strecke vom Mittelpunkt eines Kreises bis zum Außenrand?",
    answers: ["Winkel", "Umfang", "Radius (r)", "Durchmesser (d)"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Radius reicht genau von der Mitte bis zum Rand des Kreises."
  },
  {
    id: "q4_m_067",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man die geradlinige Strecke von einem Kreisrand durch den Mittelpunkt zum gegenüberliegenden Rand?",
    answers: ["Kante im Alltag", "Radius (r)", "Diagonale", "Durchmesser (d)"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Durchmesser d geht durch die Mitte und ist genau doppelt so lang wie der Radius r."
  },
  {
    id: "q4_m_068",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welches Zeichengerät benötigt man, um exakte Kreise zu zeichnen?",
    answers: ["Zirkel", "Radiergummi", "Geodreieck", "Lineal allein"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit dem Zirkel stellt man den Radius ein und zeichnet saubere Kreise."
  },
  {
    id: "q4_m_069",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Für welche Größe steht die Einheit 'cm²'?",
    answers: ["Flächeninhalt", "Umfang", "Länge", "Gewicht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "cm² bedeutet Quadratzentimeter und misst eine Fläche."
  },
  {
    id: "q4_m_070",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Für welche Größe steht die Einheit 'm²'?",
    answers: ["Länge in Metern", "Volumen", "Flächeninhalt", "Gewicht"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "m² (Quadratmeter) ist die Einheit für größere Flächen (z. B. Zimmergröße)."
  },
  {
    id: "q4_m_071",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele rechte Winkel besitzt ein normales Rechteck?",
    answers: ["2 rechte Winkel", "0 rechte Winkel", "6 rechte Winkel", "4 rechte Winkel"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Rechteck hat in allen 4 Ecken einen rechten Winkel (90°)."
  },
  {
    id: "q4_m_072",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was bedeutet Achsensymmetrie?",
    answers: ["Dass sie blau gefärbt ist", "Dass sie aus Würfeln besteht", "Dass man eine Figur an einer Spiegelachse deckungsgleich klappen kann", "Dass eine Figur nur 3 Ecken hat"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Achsensymmetrische Figuren sind an der Symmetrieachse spiegelgleich."
  },
  {
    id: "q4_m_073",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Welcher dieser Buchstaben ist senkrecht achsensymmetrisch?",
    answers: ["F", "A", "G", "R"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Buchstabe A lässt sich in der Mitte senkrecht spiegeln."
  },
  {
    id: "q4_m_074",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Aus wie vielen Quadraten besteht ein Netz eines Würfels?",
    answers: ["12 Quadrate", "8 Quadrate", "6 Quadrate", "4 Quadrate"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Würfelnetz besteht immer aus 6 zusammenhängenden Quadraten."
  },
  {
    id: "q4_m_075",
    category: "k4_mathe",
    topic: "geometrie_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Rechteck hat einen Umfang von 20 cm. Die Seite a ist 6 cm lang. Wie lang ist b?",
    answers: ["8 cm", "6 cm", "4 cm", "5 cm"],
    correct: 2,
    difficulty: "schwer",
    points: 5,
    explanation: "zwei mal 6 cm = 12 cm. 20 cm - 12 cm = 8 cm. 8 cm : 2 = 4 cm."
  },

  // ================================================================
  // 4. TONNEN, VOLUMINA, GEWICHTE & DIAGRAMME (25 Fragen)
  // ================================================================
  {
    id: "q4_m_076",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Kilogramm (kg) entsprechen genau 1 Tonne (t)?",
    answers: ["500 kg", "1.000 kg", "10.000 kg", "100 kg"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Tonne = 1.000 Kilogramm."
  },
  {
    id: "q4_m_077",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Gramm (g) wiegt 1/2 Kilogramm (ein halbes Kilo)?",
    answers: ["250 g", "750 g", "100 g", "500 g"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "1 kg = 1.000 g -> die Hälfte ist 500 Gramm."
  },
  {
    id: "q4_m_078",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Meter (m) sind 1/2 Kilometer?",
    answers: ["500 m", "100 m", "250 m", "750 m"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 km = 1.000 m -> die Hälfte sind 500 Meter."
  },
  {
    id: "q4_m_079",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Milliliter (ml) entsprechen 1/4 Liter (einem Viertel Liter)?",
    answers: ["250 ml", "100 ml", "750 ml", "500 ml"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Liter = 1.000 ml. 1.000 ml : 4 = 250 ml."
  },
  {
    id: "q4_m_080",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Milliliter (ml) entsprechen 3/4 Liter (drei Viertel Liter)?",
    answers: ["500 ml", "750 ml", "800 ml", "250 ml"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3 × 250 ml = 750 ml."
  },
  {
    id: "q4_m_081",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wandle um: 2,5 km in Meter (m)",
    answers: ["25.000 m", "2.050 m", "2.500 m", "250 m"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "2 km = 2.000 m, 0,5 km = 500 m -> 2.500 Meter."
  },
  {
    id: "q4_m_082",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wandle um: 1,5 kg in Gramm (g)",
    answers: ["150 g", "15.000 g", "1.050 g", "1.500 g"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "1,5 kg = 1.500 Gramm."
  },
  {
    id: "q4_m_083",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Minuten entsprechen 2 1/2 Stunden?",
    answers: ["150 Minuten", "180 Minuten", "120 Minuten", "130 Minuten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "2 Stunden = 120 min + 30 min (halbe Std) = 150 Minuten."
  },
  {
    id: "q4_m_084",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Sekunden hat eine halbe Minute?",
    answers: ["45 Sekunden", "50 Sekunden", "15 Sekunden", "30 Sekunden"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine volle Minute hat 60 s -> die Hälfte ist 30 s."
  },
  {
    id: "q4_m_085",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wandle um: 3.500 g in Kilogramm (kg)",
    answers: ["350 kg", "3,5 kg", "35 kg", "0,35 kg"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "3.500 g = 3 kg 500 g = 3,5 kg."
  },
  {
    id: "q4_m_086",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Mit welcher Maßeinheit misst man das Volumen (Rauminhalt) von Getränken?",
    answers: ["Quadratmeter", "Liter / Milliliter", "Meter in der Praxis", "Gramm in der Praxis"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Flüssigkeitsmengen werden in Litern oder Millilitern gemessen."
  },
  {
    id: "q4_m_087",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was stellt ein Säulendiagramm übersichtlich dar?",
    answers: ["Wörterbuch-Begriffe", "Häufigkeiten und Ergebnisse in unterschiedlich hohen Balken/Säulen", "Uhrzeiten", "Geometrische Winkel"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Säulendiagramme zeigen Zahlenwerte durch die Höhe von Balken."
  },
  {
    id: "q4_m_088",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Berechne den Durchschnitte (Mittelwert) der drei Zahlen 4, 6 und 8.",
    answers: ["5", "7", "6", "18"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "4 + 6 + 8 = 18. Dann 18 geteilt durch 3 Zahlen = 6."
  },
  {
    id: "q4_m_089",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Auto wiegt 1,5 Tonnen. Wie viel Kilogramm (kg) sind das?",
    answers: ["15.000 kg", "1.500 kg", "1.005 kg", "150 kg"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "1 t = 1.000 kg, 0,5 t = 500 kg -> 1.500 kg."
  },
  {
    id: "q4_m_090",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Zentimeter fehlen bei 75 cm noch bis zu 2 Metern?",
    answers: ["125 cm", "25 cm", "175 cm", "100 cm"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "2 m = 200 cm. 200 cm - 75 cm = 125 cm."
  },
  {
    id: "q4_m_091",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Gramm fehlen bei 450 Gramm noch bis zu 1 Kilogramm?",
    answers: ["500 g", "450 g", "650 g", "550 g"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "1 kg = 1.000 g. 1.000 g - 450 g = 550 g."
  },
  {
    id: "q4_m_092",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Milliliter fehlen bei 350 ml noch bis zu 1 Liter?",
    answers: ["650 ml", "450 ml", "550 ml", "750 ml"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Liter = 1.000 ml. 1.000 ml - 350 ml = 650 ml."
  },
  {
    id: "q4_m_093",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie viele Stunden hat ein kompletter Kalendertag (Tag und Nacht zusammen)?",
    answers: ["20 Stunden", "12 Stunden", "48 Stunden", "24 Stunden"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein voller Tag dauert genau 24 Stunden."
  },
  {
    id: "q4_m_094",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Was bleibt übrig, wenn man von 1 Tonne genau 400 kg abzieht?",
    answers: ["400 kg", "600 kg", "500 kg", "700 kg"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "1.000 kg - 400 kg = 600 kg."
  },
  {
    id: "q4_m_095",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Aus wie vielen Tagen besteht ein Schaltjahr?",
    answers: ["366 Tage", "360 Tage", "370 Tage", "365 Tage"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Schaltjahr hat der Februar 29 Tage, somit hat das Jahr 366 Tage."
  },
  {
    id: "q4_m_096",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wie nennt man die Strichgruppen (4 senkrechte Striche + 1 Schrägstrich), mit denen man schnell auszählt?",
    answers: ["Uhrzeiten", "Zahlenstrahl", "Strichliste", "Prozentrechnung"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "In einer Strichliste schnürt der 5. Strich ein Fünferpaket."
  },
  {
    id: "q4_m_097",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wahrscheinlichkeit: Wie hoch ist die Chance, bei einem normalen Spielwürfel eine 6 zu würfeln?",
    answers: ["1 von 6", "Absolut sicher", "Unmöglich", "1 von 2"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ein Würfel hat 6 Seiten. Die Chance für eine 6 beträgt genau 1 zu 6."
  },
  {
    id: "q4_m_098",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Beutel enthält 5 rote und 0 blaue Kugeln. Wie wahrscheinlich ist es, blind eine blaue Kugel zu ziehen?",
    answers: ["Sehr wahrscheinlich", "Möglich", "Sicher", "Unmöglich"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "Da keine blaue Kugel im Beutel liegt, ist es unmöglich."
  },
  {
    id: "q4_m_099",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Ein Beutel enthält 10 rote Kugeln. Wie wahrscheinlich ist es, blind eine rote Kugel zu ziehen?",
    answers: ["Unwahrscheinlich", "Unmöglich", "Sicher", "Möglich"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Da nur rote Kugeln enthalten sind, zieht man garantiert eine rote (sicher)."
  },
  {
    id: "q4_m_100",
    category: "k4_mathe",
    topic: "groessen_daten_k4",
    area: "schule",
    grade: 4,
    subject: "mathe",
    question: "Wofür steht das Einheitszeichen 't' in der Mathematik?",
    answers: ["Tasse", "Tausend", "Tag", "Tonne"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'t' ist das offizielle Kürzel für Tonne (1.000 kg)."
  }
,  { id: "q4_m_101", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 25 × 4?", answers: ["80", "100", "90", "50"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "25 × 4 = 100." },
  { id: "q4_m_102", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 144 ÷ 12?", answers: ["11", "12", "13", "10"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "144 ÷ 12 = 12." },
  { id: "q4_m_103", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 1/2 von 80?", answers: ["20", "30", "40", "50"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Die Hälfte von 80 ist 40." },
  { id: "q4_m_104", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 3/4 von 20?", answers: ["10", "15", "5", "18"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "3/4 von 20 = 15." },
  { id: "q4_m_105", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 15 % von 100?", answers: ["10", "20", "15", "5"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "15 Prozent von 100 = 15." },
  { id: "q4_m_106", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 9²?", answers: ["18", "81", "72", "99"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "9 × 9 = 81." },
  { id: "q4_m_107", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist √49?", answers: ["6", "8", "7", "9"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "7 × 7 = 49." },
  { id: "q4_m_108", category: "k4_mathe", topic: "groessen", area: "schule", grade: 4, subject: "mathe",
    question: "1 km = ? m", answers: ["10", "100", "1000", "10000"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "1 Kilometer = 1000 Meter." },
  { id: "q4_m_109", category: "k4_mathe", topic: "groessen", area: "schule", grade: 4, subject: "mathe",
    question: "2,5 kg = ? g", answers: ["250", "2500", "25", "2000"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "2,5 kg = 2500 g." },
  { id: "q4_m_110", category: "k4_mathe", topic: "geometrie", area: "schule", grade: 4, subject: "mathe",
    question: "Fläche Rechteck 6 cm × 4 cm?", answers: ["10 cm²", "24 cm²", "20 cm²", "16 cm²"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "6×4=24." },
  { id: "q4_m_111", category: "k4_mathe", topic: "geometrie", area: "schule", grade: 4, subject: "mathe",
    question: "Umfang Quadrat Seite 5 cm?", answers: ["10 cm", "20 cm", "25 cm", "15 cm"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "4×5=20 cm." },
  { id: "q4_m_112", category: "k4_mathe", topic: "geometrie", area: "schule", grade: 4, subject: "mathe",
    question: "Wie viele Grad hat ein voller Kreis?", answers: ["90", "180", "360", "100"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "360°." },
  { id: "q4_m_113", category: "k4_mathe", topic: "zahlen", area: "schule", grade: 4, subject: "mathe",
    question: "Runde 4 567 auf Hunderter.", answers: ["4500", "4600", "4570", "5000"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "4567 ≈ 4600." },
  { id: "q4_m_114", category: "k4_mathe", topic: "zahlen", area: "schule", grade: 4, subject: "mathe",
    question: "Welche Zahl ist eine Primzahl?", answers: ["9", "15", "11", "21"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "11 ist nur durch 1 und sich selbst teilbar." },
  { id: "q4_m_115", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 0,5 + 0,5?", answers: ["0,25", "1", "1,5", "0"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "0,5+0,5=1." },
  { id: "q4_m_116", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 120 − 45?", answers: ["85", "65", "75", "55"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "120−45=75." },
  { id: "q4_m_117", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 8 × 12?", answers: ["88", "96", "84", "108"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "8×12=96." },
  { id: "q4_m_118", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 56 ÷ 7?", answers: ["6", "9", "8", "7"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "56÷7=8." },
  { id: "q4_m_119", category: "k4_mathe", topic: "geometrie", area: "schule", grade: 4, subject: "mathe",
    question: "Ein Würfel hat wie viele Ecken?", answers: ["6", "8", "12", "4"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "8 Ecken." },
  { id: "q4_m_120", category: "k4_mathe", topic: "groessen", area: "schule", grade: 4, subject: "mathe",
    question: "¾ Stunde in Minuten?", answers: ["30", "45", "60", "15"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "45 Minuten." },
  { id: "q4_m_121", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 1000 − 275?", answers: ["725", "735", "825", "700"], correct: 0, difficulty: "leicht", points: 5,
    explanation: "1000−275=725." },
  { id: "q4_m_122", category: "k4_mathe", topic: "zahlen", area: "schule", grade: 4, subject: "mathe",
    question: "Nachfolger von 9 999?", answers: ["9998", "10000", "99000", "10001"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "10 000." },
  { id: "q4_m_123", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 2³?", answers: ["6", "8", "9", "4"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "2×2×2=8." },
  { id: "q4_m_124", category: "k4_mathe", topic: "geometrie", area: "schule", grade: 4, subject: "mathe",
    question: "Parallel bedeutet …", answers: ["senkrecht", "gleicher Abstand/nie treffend", "rund", "spitz"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Parallelen treffen sich nicht." },
  { id: "q4_m_125", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Mittelwert von 4 und 10?", answers: ["6", "7", "8", "14"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "(4+10)/2=7." },
  { id: "q4_m_126", category: "k4_mathe", topic: "groessen", area: "schule", grade: 4, subject: "mathe",
    question: "1 t (Tonne) = ? kg", answers: ["10", "100", "1000", "10000"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "1000 kg." },
  { id: "q4_m_127", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 45 + 55?", answers: ["90", "110", "100", "95"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "100." },
  { id: "q4_m_128", category: "k4_mathe", topic: "zahlen", area: "schule", grade: 4, subject: "mathe",
    question: "Welche ist durch 5 teilbar?", answers: ["12", "18", "25", "31"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "25 endet auf 5." },
  { id: "q4_m_129", category: "k4_mathe", topic: "geometrie", area: "schule", grade: 4, subject: "mathe",
    question: "Diagonale im Rechteck verbindet …", answers: ["benachbarte Ecken", "gegenüberliegende Ecken", "Seitenmitten", "Kreis"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "gegenüberliegende Ecken." },
  { id: "q4_m_130", category: "k4_mathe", topic: "rechnen", area: "schule", grade: 4, subject: "mathe",
    question: "Was ist 1/4 + 1/4?", answers: ["1/8", "1/2", "2/4 nur", "1"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "1/4+1/4=1/2." }
];
