const K4_ENGLISCH_QUESTIONS = [
  // ================================================================
  // 1. HOBBIES, FREE TIME & SPORTS (25 Fragen)
  // ================================================================
  {
    id: "q4_e_001",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Fußball spielen' auf Englisch?",
    answers: ["playing basketball", "playing tennis", "playing football", "swimming"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing football' bedeutet Fußball spielen."
  },
  {
    id: "q4_e_002",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Hobby 'swimming'?",
    answers: ["Klettern", "Tauchen", "Schwimmen", "Segeln"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'swimming' heißt Schwimmen."
  },
  {
    id: "q4_e_003",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Rad fahren' auf Englisch?",
    answers: ["skateboarding", "driving a car", "riding a horse", "riding a bike"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'riding a bike' bedeutet Fahrrad fahren."
  },
  {
    id: "q4_e_004",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'reading a book'?",
    answers: ["ein Buch schreiben", "ein Buch lesen", "ein Buch kaufen", "ein Buch malen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'reading a book' heißt ein Buch lesen."
  },
  {
    id: "q4_e_005",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'listening to music'?",
    answers: ["Singen", "Musik machen", "Tanzen", "Musik hören"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'listening to music' bedeutet Musik hören."
  },
  {
    id: "q4_e_006",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie frage ich jemanden nach seinem Lieblingshobby?",
    answers: ["What is your favourite hobby?", "How old are you? in der Praxis", "Where do you live? im Alltag", "What is your name? im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'What is your favourite hobby?' bedeutet 'Was ist dein Lieblingshobby?'."
  },
  {
    id: "q4_e_007",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie antwortet man auf 'Can you swim?' wenn man es KANN?",
    answers: ["No, I don't.", "No, I can't.", "Yes, I can.", "Yes, I am."],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'Yes, I can.' bedeutet 'Ja, ich kann es'."
  },
  {
    id: "q4_e_008",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie antwortet man auf 'Can you play tennis?' wenn man es NICHT kann?",
    answers: ["No, I am not.", "Yes, I do.", "Yes, I can.", "No, I can't."],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'No, I can't.' (Kurzform von cannot) heißt 'Nein, ich kann nicht'."
  },
  {
    id: "q4_e_009",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Verb 'climbing'?",
    answers: ["Rennen", "Springen", "Laufen", "Klettern"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'climbing' heißt Klettern."
  },
  {
    id: "q4_e_010",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'dancing'?",
    answers: ["Singen", "Tanzen", "Spielen", "Lachen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'dancing' bedeutet Tanzen."
  },
  {
    id: "q4_e_011",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Klavier spielen' auf Englisch?",
    answers: ["playing the guitar", "playing the drums", "playing flute", "playing the piano"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing the piano' heißt Klavier spielen."
  },
  {
    id: "q4_e_012",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Gitarre spielen' auf Englisch?",
    answers: ["singing songs", "playing games", "playing the guitar", "playing the piano"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing the guitar' bedeutet Gitarre spielen."
  },
  {
    id: "q4_e_013",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'playing computer games'?",
    answers: ["Fernsehen in der Praxis", "Computerspiele spielen", "im Internet surfen", "Computer reparieren"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'playing computer games' heißt Computerspiele spielen."
  },
  {
    id: "q4_e_014",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'cooking'?",
    answers: ["Trinken", "Backen", "Essen", "Kochen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'cooking' heißt Kochen."
  },
  {
    id: "q4_e_015",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'drawing a picture'?",
    answers: ["ein Bild zeichnen", "ein Bild aufhängen", "ein Bild ausneiden", "ein Foto machen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'drawing' heißt Zeichnen."
  },
  {
    id: "q4_e_016",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'singing'?",
    answers: ["Singen", "Schreien", "Rufen", "Sprechen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'singing' heißt Singen."
  },
  {
    id: "q4_e_017",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Reiten' (auf einem Pferd) auf Englisch?",
    answers: ["walking in der Praxis", "horse riding / riding a horse", "running in der Praxis", "cycling in der Praxis"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'horse riding' bedeutet Pferdereiten."
  },
  {
    id: "q4_e_018",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Skateboard fahren' auf Englisch?",
    answers: ["rollerblading", "skiing", "skateboarding", "snowboarding"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'skateboarding' heißt Skateboard fahren."
  },
  {
    id: "q4_e_019",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Inlineskaten / Rollschuh fahren' auf Englisch?",
    answers: ["ice skating in der Praxis", "running in der Praxis", "rollerblading / roller skating", "skateboarding in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'rollerblading' bedeutet Inlineskaten."
  },
  {
    id: "q4_e_020",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'I like playing football'?",
    answers: ["Ich spiele nicht gerne Fußball", "Ich spiele gerne Fußball", "Ich sehe Fußball im Fernsehen", "Ich kann kein Fußball spielen"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'I like ...' bedeutet 'Ich mag ... / Ich mache gerne ...'."
  },
  {
    id: "q4_e_021",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'I don't like running'?",
    answers: ["Ich laufe nicht gerne", "Ich kann schnell laufen", "Ich laufe morgen", "Ich laufe sehr gerne"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'I don't like ...' heißt 'Ich mag ... nicht'."
  },
  {
    id: "q4_e_022",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Ski fahren' auf Englisch?",
    answers: ["ice skating", "climbing", "skiing", "sledging"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'skiing' heißt Skifahren."
  },
  {
    id: "q4_e_023",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schlittschuhlaufen' auf Englisch?",
    answers: ["skiing", "rollerblading", "swimming", "ice skating"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'ice skating' heißt Schlittschuhlaufen."
  },
  {
    id: "q4_e_024",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'team'?",
    answers: ["Spielplatz", "Trainer im Alltag", "Mannschaft / Team", "Ball in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'team' heißt Mannschaft."
  },
  {
    id: "q4_e_025",
    category: "k4_englisch",
    topic: "hobbies_sports",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Turnen / Gymnastik' auf Englisch?",
    answers: ["athletics", "fitness", "gymnastics", "dancing"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'gymnastics' bedeutet Turnen."
  },

  // ================================================================
  // 2. AT SCHOOL, IN TOWN & DIRECTIONS (25 Fragen)
  // ================================================================
  {
    id: "q4_e_026",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach heißt auf Englisch 'maths'?",
    answers: ["Deutsch", "Kunst", "Musik", "Mathematik"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'maths' (oder 'mathematics') ist Mathematik."
  },
  {
    id: "q4_e_027",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach heißt 'PE' (Physical Education)?",
    answers: ["Sachunterricht", "Sport", "Physik", "Politik"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "'PE' steht für Sportunterricht."
  },
  {
    id: "q4_e_028",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach heißt 'art'?",
    answers: ["Kunst", "Musik", "Englisch", "Erdkunde"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'art' bedeutet Kunstunterricht."
  },
  {
    id: "q4_e_029",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Schulfach entspricht am ehesten 'science'?",
    answers: ["Sport", "Sachunterricht / Naturwissenschaften", "Religion in der Praxis", "Geschichte in der Praxis"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "'science' umfasst Sachunterricht und Naturwissenschaften."
  },
  {
    id: "q4_e_030",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'timetable'?",
    answers: ["Kalender", "Uhr", "Stundenplan", "Tischzeiten"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'timetable' heißt Stundenplan."
  },
  {
    id: "q4_e_031",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Turn left' bei einer Wegbeschreibung?",
    answers: ["Stoppe hier", "Gehe geradeaus", "Biege rechts ab", "Biege links ab"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Turn left' heißt links abbiegen."
  },
  {
    id: "q4_e_032",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Turn right'?",
    answers: ["Biege rechts ab", "Drehe um", "Gehe zurück", "Biege links ab"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Turn right' heißt rechts abbiegen."
  },
  {
    id: "q4_e_033",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Go straight ahead'?",
    answers: ["Gehe geradeaus weiter", "Gehe durch den Park", "Biege sofort ab", "Warte an der Ampel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Go straight ahead' heißt geradeaus gehen."
  },
  {
    id: "q4_e_034",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Bahnhof' auf Englisch?",
    answers: ["bus stop in der Praxis", "supermarket in der Praxis", "railway station / train station", "airport in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'train station' oder 'railway station' ist der Bahnhof."
  },
  {
    id: "q4_e_035",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Kino' auf Englisch?",
    answers: ["library in der Praxis", "theatre in der Praxis", "museum in der Praxis", "cinema / movie theater"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'cinema' heißt Kino."
  },
  {
    id: "q4_e_036",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schwimmbad' auf Englisch?",
    answers: ["sports hall", "park", "playground", "swimming pool"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'swimming pool' heißt Schwimmbad."
  },
  {
    id: "q4_e_037",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Krankenhaus' auf Englisch?",
    answers: ["hospital", "hotel", "hall", "house"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'hospital' bedeutet Krankenhaus."
  },
  {
    id: "q4_e_038",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'library'?",
    answers: ["Buchhandlung", "Schulklasse im Alltag", "Bibliothek / Bücherei", "Kino in der Praxis"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "'library' ist die Bücherei oder Bibliothek."
  },
  {
    id: "q4_e_039",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet die Präposition 'next to'?",
    answers: ["vor", "hinter", "neben", "unter"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'next to' bedeutet direkt neben."
  },
  {
    id: "q4_e_040",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet die Ortsangabe 'opposite'?",
    answers: ["neben", "in im Alltag", "hinter", "gegenüber von"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'opposite' bedeutet gegenüber."
  },
  {
    id: "q4_e_041",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'in front of'?",
    answers: ["vor", "auf", "unter", "hinter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'in front of' bedeutet vor (z. B. in front of the house)."
  },
  {
    id: "q4_e_042",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'behind'?",
    answers: ["zwischen", "neben", "hinter", "vor"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'behind' bedeutet hinter."
  },
  {
    id: "q4_e_043",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Lineal' im Federmäppchen auf Englisch?",
    answers: ["scissors", "pencil", "rubber", "ruler"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'ruler' heißt Lineal."
  },
  {
    id: "q4_e_044",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Radiergummi' auf Englisch?",
    answers: ["ruler im Alltag", "rubber / eraser", "sharpener", "glue im Alltag"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'rubber' (oder im Amerikanischen 'eraser') ist der Radiergummi."
  },
  {
    id: "q4_e_045",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Anspatzer / Anspitzer' auf Englisch?",
    answers: ["scissors", "pencil case", "pen", "sharpener"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'sharpener' (pencil sharpener) ist der Anspitzer."
  },
  {
    id: "q4_e_046",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schere' auf Englisch?",
    answers: ["glue", "scissors", "paper", "ruler"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'scissors' bedeutet Schere."
  },
  {
    id: "q4_e_047",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Klebstoff' auf Englisch?",
    answers: ["glue / glue stick", "paper zur Auswahl", "pen in der Praxis", "desk in der Praxis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'glue' ist der Klebstoff."
  },
  {
    id: "q4_e_048",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie frage ich höflich nach dem Weg: 'Wo ist der Supermarkt?'?",
    answers: ["How much is the supermarket?", "Where is the supermarket, please?", "Who is in the supermarket?", "What is the supermarket?"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Where is ...?' fragt nach dem Ort."
  },
  {
    id: "q4_e_049",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Pausenhof' auf Englisch?",
    answers: ["hall in der Praxis", "classroom in der Praxis", "gym in der Praxis", "playground / schoolyard"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'schoolyard' oder 'playground' ist der Pausenhof."
  },
  {
    id: "q4_e_050",
    category: "k4_englisch",
    topic: "school_town_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'between'?",
    answers: ["unter", "auf", "neben", "zwischen"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'between' bedeutet zwischen zwei Dingen."
  },

  // ================================================================
  // 3. SHOPPING, MONEY & FOOD (25 Fragen)
  // ================================================================
  {
    id: "q4_e_051",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie frage ich beim Einkaufen nach dem Preis: 'Wie viel kostet das?'?",
    answers: ["How many is it?", "What time is it?", "How much is it?", "Where is it?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'How much is it?' fragt nach dem Preis."
  },
  {
    id: "q4_e_052",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie sagt man beim Überreichen der Ware oder des Geldes 'Bitte sehr!'?",
    answers: ["Thank you.", "You're welcome.", "Please stop.", "Here you are."],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Here you are' bedeutet 'Bitte sehr / Hier bitte'."
  },
  {
    id: "q4_e_053",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie heißt die offizielle Währung in Großbritannien (Pfund)?",
    answers: ["euro im Alltag", "pound / pounds", "dollar", "franc"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "In Großbritannien bezahlt man mit 'pounds' (£)."
  },
  {
    id: "q4_e_054",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie heißen die Kleingeld-Münzen in Großbritannien (Pennies)?",
    answers: ["pesos", "cents", "pence / penny", "coins"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "1 Pound entspricht 100 Pence (p)."
  },
  {
    id: "q4_e_055",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Wie bestellt man höflich ein Eis: 'Kann ich bitte ein Eis haben?'?",
    answers: ["Ice cream is good. in der Praxis", "I want ice cream now! im Alltag", "Give me ice cream! in der Praxis", "Can I have an ice cream, please?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Can I have ..., please?' ist die höfliche Formel beim Einkaufen."
  },
  {
    id: "q4_e_056",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'cheap'?",
    answers: ["alt in der Praxis", "schwer im Alltag", "günstig / billig", "teuer im Alltag"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "'cheap' bedeutet preiswert oder billig."
  },
  {
    id: "q4_e_057",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'expensive'?",
    answers: ["klein", "schnell", "billig", "teuer"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'expensive' bedeutet teuer."
  },
  {
    id: "q4_e_058",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Gemüse' auf Englisch?",
    answers: ["sweets", "meat", "vegetables", "fruit"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'vegetables' heißt Gemüse."
  },
  {
    id: "q4_e_059",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Obst / Früchte' auf Englisch?",
    answers: ["drink", "bread", "fruit", "vegetables"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'fruit' bedeutet Obst."
  },
  {
    id: "q4_e_060",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Gemüse heißt 'carrots'?",
    answers: ["Karotten / Möhren", "Gurken im Alltag", "Kartoffeln", "Tomaten im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'carrots' sind Karotten."
  },
  {
    id: "q4_e_061",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Welches Gemüse heißt 'potatoes'?",
    answers: ["Möhren", "Bohnen", "Erbsen", "Kartoffeln"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'potatoes' sind Kartoffeln."
  },
  {
    id: "q4_e_062",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'strawberries'?",
    answers: ["Kirschen", "Erdbeeren", "Äpfel", "Himbeeren"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'strawberries' sind Erdbeeren."
  },
  {
    id: "q4_e_063",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'butter'?",
    answers: ["Butter", "Käse", "Margarine", "Milch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'butter' heißt Butter."
  },
  {
    id: "q4_e_064",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Marmelade' auf Englisch?",
    answers: ["jam / marmalade", "sugar im Alltag", "honey im Alltag", "butter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'jam' ist die allgemeine Bezeichnung für Marmelade."
  },
  {
    id: "q4_e_065",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'sugar'?",
    answers: ["Zucker", "Pfeffer", "Salz", "Mehl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'sugar' heißt Zucker."
  },
  {
    id: "q4_e_066",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'salt'?",
    answers: ["Salz", "Essig", "Öl", "Senf"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'salt' bedeutet Salz."
  },
  {
    id: "q4_e_067",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'market'?",
    answers: ["Markt", "Regal", "Bäckerei", "Kasse"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'market' heißt Markt."
  },
  {
    id: "q4_e_068",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Bäckerei' auf Englisch?",
    answers: ["supermarket", "butcher", "shop", "bakery"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'bakery' heißt Bäckerei."
  },
  {
    id: "q4_e_069",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Metzgerei / Fleischer' auf Englisch?",
    answers: ["sweet shop", "pharmacy", "bakery", "butcher's"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'butcher's' ist die Metzgerei."
  },
  {
    id: "q4_e_070",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Süßigkeiten' auf Englisch?",
    answers: ["cookies", "cakes", "sweets / candy", "fruit"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'sweets' (britisch) oder 'candy' (amerikanisch) sind Süßigkeiten."
  },
  {
    id: "q4_e_071",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'cake'?",
    answers: ["Schokolade", "Kuchen / Torte", "Keks im Alltag", "Brot im Alltag"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'cake' ist der Kuchen."
  },
  {
    id: "q4_e_072",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'biscuit / cookie'?",
    answers: ["Keks / Plätzchen", "Kuchen im Alltag", "Brötchen", "Bonbon im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'biscuit' (UK) oder 'cookie' (US) heißt Keks."
  },
  {
    id: "q4_e_073",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Fleisch' auf Englisch?",
    answers: ["fish", "meat", "cheese", "chicken"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'meat' heißt Fleisch."
  },
  {
    id: "q4_e_074",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Hähnchen / Huhn' auf Englisch?",
    answers: ["duck", "beef", "pork", "chicken"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'chicken' bedeutet Hähnchen."
  },
  {
    id: "q4_e_075",
    category: "k4_englisch",
    topic: "shopping_food",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet der Satz 'That is 3 pounds, please'?",
    answers: ["Das macht 3 Pfund, bitte.", "Geben Sie mir 3 Münzen.", "Das wiegt 3 Kilo.", "Das Ich kaufe 3 Sachen."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Es ist der Zahlungsbetrag an der Kasse."
  },

  // ================================================================
  // 4. BODY, HEALTH & CLOTHES (25 Fragen)
  // ================================================================
  {
    id: "q4_e_076",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Kopf' auf Englisch?",
    answers: ["heart", "hair", "head", "hand"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'head' heißt Kopf."
  },
  {
    id: "q4_e_077",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Schultern' auf Englisch?",
    answers: ["shoulders", "knees", "toes", "arms"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'shoulders' sind die Schultern."
  },
  {
    id: "q4_e_078",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Knie' auf Englisch?",
    answers: ["knees", "toes", "feet", "legs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'knees' sind die Knie."
  },
  {
    id: "q4_e_079",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Zehen' auf Englisch?",
    answers: ["legs", "feet", "toes", "fingers"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'toes' sind die Zehen am Fuß."
  },
  {
    id: "q4_e_080",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Augen' auf Englisch?",
    answers: ["ears", "mouth", "nose", "eyes"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'eyes' sind die Augen."
  },
  {
    id: "q4_e_081",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Ohren' auf Englisch?",
    answers: ["legs", "ears", "arms", "eyes"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'ears' sind die Ohren."
  },
  {
    id: "q4_e_082",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Mund' auf Englisch?",
    answers: ["chin", "mouth", "nose", "face"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'mouth' heißt Mund."
  },
  {
    id: "q4_e_083",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Nase' auf Englisch?",
    answers: ["nose", "hair", "mouth", "neck"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'nose' ist die Nase."
  },
  {
    id: "q4_e_084",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'headache'?",
    answers: ["Zahnschmerzen", "Bauchschmerzen", "Kopfschmerzen", "Halsschmerzen"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "'headache' besteht aus head (Kopf) + ache (Schmerz) = Kopfschmerzen."
  },
  {
    id: "q4_e_085",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'stomach ache'?",
    answers: ["Bauchschmerzen", "Ohrenschmerzen", "Kopfschmerzen", "Rückenschmerzen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'stomach ache' heißt Bauchschmerzen."
  },
  {
    id: "q4_e_086",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'toothache'?",
    answers: ["Kopfschmerzen", "Fieber", "Zahnschmerzen", "Husten"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "'toothache' heißt Zahnschmerzen."
  },
  {
    id: "q4_e_087",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'I have got a cold'?",
    answers: ["Ich habe Fieber", "Mir ist kalt im Alltag", "Ich habe eine Erkältung", "Ich bin müde im Alltag"],
    correct: 2,
    difficulty: "mittel",
    points: 5,
    explanation: "'to have a cold' heißt erkältet sein."
  },
  {
    id: "q4_e_088",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Arzt' auf Englisch?",
    answers: ["doctor", "teacher", "driver", "baker"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'doctor' heißt Arzt."
  },
  {
    id: "q4_e_089",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet der Satz 'I am ill'?",
    answers: ["Ich bin müde", "Ich bin traurig", "Ich bin gesund", "Ich bin krank"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'ill' (oder 'sick') heißt krank."
  },
  {
    id: "q4_e_090",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Pullover' auf Englisch?",
    answers: ["trousers", "jumper / sweater", "coat zur Auswahl", "shirt im Alltag"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'jumper' (UK) oder 'sweater' (US) ist der Pullover."
  },
  {
    id: "q4_e_091",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Schal' auf Englisch?",
    answers: ["hat", "gloves", "cap", "scarf"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'scarf' heißt Schal."
  },
  {
    id: "q4_e_092",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Handschuhe' auf Englisch?",
    answers: ["socks", "shoes", "gloves", "boots"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'gloves' sind die Handschuhe."
  },
  {
    id: "q4_e_093",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Stiefel' auf Englisch?",
    answers: ["socks", "boots", "shoes", "slippers"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'boots' sind Stiefel."
  },
  {
    id: "q4_e_094",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Put on your coat!'?",
    answers: ["Zieh deinen Mantel an!", "Kauf einen Mantel!", "Wasche deinen Mantel!", "Zieh deinen Mantel aus!"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'put on' heißt anziehen."
  },
  {
    id: "q4_e_095",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet 'Take off your shoes!'?",
    answers: ["Zieh deine Schuhe aus!", "Binde deine Schuhe!", "Putze deine Schuhe!", "Zieh deine Schuhe an!"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'take off' heißt ausziehen."
  },
  {
    id: "q4_e_096",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'fingers'?",
    answers: ["Füße", "Zehen", "Finger", "Hände"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'fingers' sind die Finger an den Händen."
  },
  {
    id: "q4_e_097",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was bedeutet das Wort 'feet' (Mehrzahl von foot)?",
    answers: ["Füße", "Hände", "Arme", "Beine"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "one foot (ein Fuß) -> two feet (zwei Füße)."
  },
  {
    id: "q4_e_098",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Bauch' auf Englisch?",
    answers: ["stomach / tummy", "back im Alltag", "chest im Alltag", "neck im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'stomach' (oder umgangssprachlich 'tummy') ist der Bauch."
  },
  {
    id: "q4_e_099",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißt 'Rücken' auf Englisch?",
    answers: ["back", "stomach", "shoulder", "arm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'back' heißt Rücken."
  },
  {
    id: "q4_e_100",
    category: "k4_englisch",
    topic: "body_clothes_k4",
    area: "schule",
    grade: 4,
    subject: "englisch",
    question: "Was heißen 'Zähne' (Mehrzahl von tooth) auf Englisch?",
    answers: ["mouths", "teeth", "tooths", "lips"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "one tooth (ein Zahn) -> many teeth (viele Zähne)."
  }
,  { id: "q4_e_101", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Difficult“ means …", answers: ["leicht", "schwierig", "schnell", "laut"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "difficult = schwierig." },
  { id: "q4_e_102", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "Opposite of „early“?", answers: ["soon", "late", "fast", "near"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "late." },
  { id: "q4_e_103", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Library“ heißt …", answers: ["Buchhandlung", "Bibliothek", "Schule", "Museum"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Bibliothek." },
  { id: "q4_e_104", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Past of „go“?", answers: ["goed", "went", "gone", "goes"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "went." },
  { id: "q4_e_105", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Present perfect: I ___ finished.", answers: ["has", "have", "had", "am"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "I have finished." },
  { id: "q4_e_106", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Comparative of „good“?", answers: ["gooder", "better", "best", "more good"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "better." },
  { id: "q4_e_107", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "„There is“ / „There are“: ___ two cats.", answers: ["There is", "There are", "It is", "They is"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "There are." },
  { id: "q4_e_108", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Question form: ___ you like pizza?", answers: ["Does", "Do", "Is", "Are"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Do you like…" },
  { id: "q4_e_109", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Weather“ means …", answers: ["Wetter", "Wetterfrosch", "Kleidung", "Uhrzeit"], correct: 0, difficulty: "leicht", points: 5,
    explanation: "weather = Wetter." },
  { id: "q4_e_110", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "Days: What comes after Monday?", answers: ["Sunday", "Wednesday", "Tuesday", "Friday"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Tuesday." },
  { id: "q4_e_111", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Hungry“ heißt …", answers: ["durstig", "müde", "hungrig", "froh"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "hungrig." },
  { id: "q4_e_112", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Article: ___ hour (Aussprache!)", answers: ["a", "an", "the", "some"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "an hour." },
  { id: "q4_e_113", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Possessive: This is ___ (she) bag.", answers: ["she", "her", "hers", "him"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "her bag." },
  { id: "q4_e_114", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Mountain“ means …", answers: ["Fluss", "Berg", "Meer", "Wald"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Berg." },
  { id: "q4_e_115", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Because“ heißt …", answers: ["aber", "oder", "weil", "und"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "weil." },
  { id: "q4_e_116", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Future: I ___ help you.", answers: ["will", "wills", "woulds", "am"], correct: 0, difficulty: "leicht", points: 5,
    explanation: "will." },
  { id: "q4_e_117", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Plural of „leaf“?", answers: ["leafs", "leaves", "leafes", "leave"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "leaves." },
  { id: "q4_e_118", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Always“ means …", answers: ["nie", "manchmal", "immer", "selten"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "immer." },
  { id: "q4_e_119", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Never“ heißt …", answers: ["immer", "oft", "nie", "manchmal"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "nie." },
  { id: "q4_e_120", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "„He doesn’t …“ braucht …", answers: ["Infinitiv ohne to oft", "-s Form", "Past", "Plural"], correct: 0, difficulty: "leicht", points: 5,
    explanation: "doesn’t + Grundform." },
  { id: "q4_e_121", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Station“ ist …", answers: ["Krankenhaus", "Bahnhof", "Schule", "Park"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Bahnhof." },
  { id: "q4_e_122", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Quickly“ is an …", answers: ["noun", "adverb", "article", "number"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "adverb." },
  { id: "q4_e_123", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Irregular: past of „see“?", answers: ["seed", "saw", "seen", "see"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "saw." },
  { id: "q4_e_124", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "„Was/were“: They ___ at home.", answers: ["was", "were", "is", "be"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "were." },
  { id: "q4_e_125", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Healthy“ means …", answers: ["krank", "gesund", "müde", "alt"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "gesund." },
  { id: "q4_e_126", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "Months: December is in …", answers: ["summer", "winter", "spring only", "autumn only"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "winter (in DE)." },
  { id: "q4_e_127", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "Object pronoun: Give it to … (I).", answers: ["I", "me", "my", "mine"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "me." },
  { id: "q4_e_128", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Enough“ heißt …", answers: ["zu wenig", "genug", "viel zu", "kein"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "genug." },
  { id: "q4_e_129", category: "k4_englisch", topic: "grammar", area: "schule", grade: 4, subject: "englisch",
    question: "„Who“ fragt nach …", answers: ["Ort", "Person", "Zeit", "Grund"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Person." },
  { id: "q4_e_130", category: "k4_englisch", topic: "vocab", area: "schule", grade: 4, subject: "englisch",
    question: "„Together“ means …", answers: ["allein", "zusammen", "später", "früher"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "zusammen." }
];
