// Fun · spass_schaetzfragen.js
const SPASS_SCHAETZFRAGEN_QUESTIONS = [
  {
        id: "sch_mko_001",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Kilometer legt das Blut eines Erwachsenen am Tag im Körper zurück?",
        answers: ["ca. 19.000 km", "ca. 28.000 km", "ca. 37.000 km", "ca. 46.000 km"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Das Herz pumpt das Blut pausenlos durch den Körper, sodass der gegliederte Weg am Tag ca. 19.000 km beträgt."
    },
  {
        id: "sch_mko_002",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Liter Speichel produziert ein Mensch im Laufe seines Lebens durchschnittlich?",
        answers: ["ca. 12.000 Liter", "ca. 25.000 Liter", "ca. 38.000 Liter", "ca. 51.000 Liter"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Täglich bilden die Speicheldrüsen etwa 1 bis 1,5 Liter Speichel, was hochgerechnet rund 25.000 Litern entspricht."
    },
  {
        id: "sch_mko_003",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie oft schlägt das Herz eines Menschen in einem 80-jährigen Leben etwa?",
        answers: ["ca. 1,5 Milliarden", "ca. 2,2 Milliarden", "ca. 3,0 Milliarden", "ca. 3,8 Milliarden"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Bei einem Ruhepuls von rund 70 Schlägen pro Minute erreicht das Herz nach 80 Jahren etwa 3 Milliarden Schläge."
    },
  {
        id: "sch_mko_004",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Skelettmuskeln besitzt der menschliche Körper insgesamt?",
        answers: ["ca. 350 Muskeln", "ca. 480 Muskeln", "ca. 550 Muskeln", "ca. 650 Muskeln"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Je nach Zählweise der feinen Sehnenansätze besitzt der Mensch etwa 650 verschiedene Skelettmuskeln."
    },
  {
        id: "sch_mko_005",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Knochen besitzt der Körper eines ausgewachsenen Menschen?",
        answers: ["206 Knochen", "236 Knochen", "266 Knochen", "296 Knochen"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein erwachsener Mensch hat exakt 206 Knochen, da viele Säuglingsknochen im Laufe des Wachstums zusammenwachsen."
    },
  {
        id: "sch_mko_006",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Mit wie vielen einzelnen Knochen kommt ein Neugeborenes etwa auf die Welt?",
        answers: ["ca. 240 Knochen", "ca. 300 Knochen", "ca. 360 Knochen", "ca. 420 Knochen"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Babys haben rund 300 Knorpel und Knochenansätze, die später zu den 206 stabilen Knochen verschmelzen."
    },
  {
        id: "sch_mko_007",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Um wie viele Zentimeter wächst das menschliche Kopfhaar im Durchschnitt pro Monat?",
        answers: ["ca. 0,5 Zentimeter", "ca. 0,8 Zentimeter", "ca. 1,2 Zentimeter", "ca. 1,8 Zentimeter"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Kopfhaare wachsen durchschnittlich ca. 1 bis 1,2 cm pro Monat bzw. etwa 0,3 bis 0,4 mm pro Tag."
    },
  {
        id: "sch_mko_008",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Kopfhaare verliert ein Mensch natürlicherweise pro Tag?",
        answers: ["ca. 25 Haare", "ca. 50 Haare", "ca. 75 Haare", "ca. 100 Haare"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der Verlust von bis zu 100 Haaren am Tag ist durch den natürlichen Erneuerungszyklus der Haarwurzeln normal."
    },
  {
        id: "sch_mko_009",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Atemzüge macht ein erwachsener Mensch im Ruhezustand pro Tag?",
        answers: ["ca. 20.000 Atemzüge", "ca. 32.000 Atemzüge", "ca. 44.000 Atemzüge", "ca. 56.000 Atemzüge"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Bei durchschnittlich 12 bis 15 Atemzügen pro Minute ergeben sich rund 20.000 Atemzüge am Tag."
    },
  {
        id: "sch_mko_010",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie groß ist die Hautoberfläche eines erwachsenen Menschen durchschnittlich?",
        answers: ["ca. 1,2 Quadratmeter", "ca. 1,8 Quadratmeter", "ca. 2,4 Quadratmeter", "ca. 3,0 Quadratmeter"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Haut ist das größte Organ des Menschen und misst je nach Körpergröße zwischen 1,5 und 2 Quadratmeter."
    },
  {
        id: "sch_mko_011",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Kilogramm wiegt die Haut eines Erwachsenen (inklusive Unterhaut)?",
        answers: ["ca. 2,5 Kilogramm", "ca. 3,5 Kilogramm", "ca. 4,5 Kilogramm", "ca. 5,5 Kilogramm"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Je nach Körperbau bringt die reine Hautschicht samt Fettgewebe zwischen 3,5 und 5 Kilogramm auf die Waage."
    },
  {
        id: "sch_mko_012",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Prozent des menschlichen Körpers bestehen bei Erwachsenen aus Wasser?",
        answers: ["ca. 30 Prozent", "ca. 45 Prozent", "ca. 50 Prozent", "ca. 60 Prozent"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Der menschliche Körper besteht je nach Alter und Geschlecht zu etwa 50 bis 65 Prozent aus Wasser."
    },
  {
        id: "sch_mko_013",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lang ist der gesamte Verdauungstrakt vom Mund bis zum Ausgang?",
        answers: ["ca. 7 bis 9 Meter", "ca. 10 bis 12 Meter", "ca. 13 bis 15 Meter", "ca. 16 bis 18 Meter"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Verdauungstrakt misst im entspannten Zustand bei Erwachsenen etwa 7 bis 9 Meter."
    },
  {
        id: "sch_mko_014",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie oft blinzelt ein Mensch durchschnittlich pro Minute mit den Augen?",
        answers: ["ca. 8 Mal", "ca. 15 Mal", "ca. 22 Mal", "ca. 29 Mal"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Im Normalfall blinzeln wir etwa 10 bis 15 Mal pro Minute, um die Hornhaut feucht zu halten."
    },
  {
        id: "sch_mko_015",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Geschmacksknospen befinden sich ungefähr auf einer menschlichen Zunge?",
        answers: ["ca. 3.000 Knospen", "ca. 6.000 Knospen", "ca. 10.000 Knospen", "ca. 14.000 Knospen"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Auf der Zunge sitzen zwischen 2.000 und 10.000 Geschmacksknospen für Süß, Sauer, Salzig, Bitter und Umami."
    },
  {
        id: "sch_mko_016",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Liter Blut fließen durchschnittlich im Körper eines Erwachsenen?",
        answers: ["ca. 2 bis 3 Liter", "ca. 3 bis 4 Liter", "ca. 4 bis 5 Liter", "ca. 5 bis 6 Liter"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Ein erwachsener Mensch besitzt je nach Körpergewicht etwa 5 bis 6 Liter Blut."
    },
  {
        id: "sch_mko_017",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Bakterien besiedeln den menschlichen Körper (Mikrobiom) etwa?",
        answers: ["ca. 38 Billionen", "ca. 58 Billionen", "ca. 78 Billionen", "ca. 98 Billionen"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Im und auf dem Körper leben geschätzt 38 Billionen Bakterien – ungefähr so viele wie eigene Körperzellen."
    },
  {
        id: "sch_mko_018",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Mit welcher Höchstgeschwindigkeit können Nervensignale im Körper reisen?",
        answers: ["ca. 200 km/h", "ca. 400 km/h", "ca. 600 km/h", "ca. 800 km/h"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "In dikken, isolierten Nervenfasern erreichen elektrische Impulse Geschwindigkeiten von bis zu 400 km/h (120 m/s)."
    },
  {
        id: "sch_mko_019",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel wiegt das Gehirn eines erwachsenen Menschen im Durchschnitt?",
        answers: ["ca. 0,9 Kilogramm", "ca. 1,1 Kilogramm", "ca. 1,4 Kilogramm", "ca. 1,8 Kilogramm"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das menschliche Gehirn wiegt durchschnittlich etwa 1,3 bis 1,4 Kilogramm."
    },
  {
        id: "sch_mko_020",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Kilokalorien verbrennt das Gehirn im Schlaf pro Stunde etwa?",
        answers: ["ca. 20 Kilokalorien", "ca. 35 Kilokalorien", "ca. 50 Kilokalorien", "ca. 65 Kilokalorien"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Selbst im Ruhezustand und Schlaf verbraucht das Gehirn stetig rund 20 % der Energie, etwa 65 kcal/Std."
    },
  {
        id: "sch_mko_021",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lang wären alle Blutgefäße eines Menschen aneinandergereiht?",
        answers: ["ca. 100.000 km", "ca. 150.000 km", "ca. 200.000 km", "ca. 250.000 km"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Sämtliche Adern, Venen und feinsten Kapillaren ergeben zusammen eine Länge von etwa 100.000 Kilometern."
    },
  {
        id: "sch_mko_022",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Schweißdrüsen besitzt die menschliche Haut ungefähr?",
        answers: ["ca. 1,2 Millionen", "ca. 2,5 Millionen", "ca. 3,8 Millionen", "ca. 5,0 Millionen"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Über den gesamten Körper verteilt befinden sich rund 2 bis 4 Millionen mikroskopisch kleine Schweißdrüsen."
    },
  {
        id: "sch_mko_023",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Rippenpaare bilden den Brustkorb eines gesunden Menschen?",
        answers: ["10 Rippenpaare", "11 Rippenpaare", "12 Rippenpaare", "13 Rippenpaare"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Männer und Frauen besitzen gleichermaßen 12 Rippenpaare (insgesamt 24 Rippen)."
    },
  {
        id: "sch_mko_024",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Wimpern befinden sich durchschnittlich am oberen Augenlid?",
        answers: ["ca. 60 Wimpern", "ca. 90 Wimpern", "ca. 120 Wimpern", "ca. 150 Wimpern"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Am oberen Lid wachsen etwa 150 bis 200 Wimpern, am unteren Lid rund halb so viele."
    },
  {
        id: "sch_mko_025",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange lebt eine rote Blutzelle (Erythrozyt) im Körper?",
        answers: ["ca. 120 Tage", "ca. 180 Tage", "ca. 240 Tage", "ca. 300 Tage"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Rote Blutzellen kreisen etwa 120 Tage im Blutkreislauf, bevor sie in der Milz abgebaut werden."
    },
  {
        id: "sch_mko_026",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Gramm Hautschuppen verliert ein Mensch täglich?",
        answers: ["ca. 0,5 Gramm", "ca. 1,5 Gramm", "ca. 2,5 Gramm", "ca. 3,5 Gramm"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Täglich stoßen wir etwa 1,5 Gramm mikroskopische Hautschuppen ab, die Hausstaubmilben als Nahrung dienen."
    },
  {
        id: "sch_mko_027",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welche Höchstgeschwindigkeit erreicht die Luft beim Niesen?",
        answers: ["ca. 80 km/h", "ca. 120 km/h", "ca. 160 km/h", "ca. 200 km/h"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Beim Niesen wird die Luft schlagartig mit bis zu 160 km/h aus der Nase herausgepresst."
    },
  {
        id: "sch_mko_028",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Zähne hat das vollständige Gebiss eines Kleinkindes (Milchgebiss)?",
        answers: ["12 Milchzähne", "16 Milchzähne", "18 Milchzähne", "20 Milchzähne"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Das vollständige Milchgebiss besteht aus genau 20 Zähnen (10 im Oberkiefer, 10 im Unterkiefer)."
    },
  {
        id: "sch_mko_029",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange dauert die vollständige Verdauung einer normalen Mahlzeit insgesamt?",
        answers: ["ca. 24 bis 72 Std.", "ca. 80 bis 100 Std.", "ca. 105 bis 125 Std.", "ca. 130 bis 150 Std."],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Vom Schlucken bis zur Ausscheidung vergehen je nach Ballaststoffgehalt zwischen 24 und 72 Stunden."
    },
  {
        id: "sch_mko_030",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Gesichtsmuskeln sind aktiv beteiligt, wenn wir ehrlich lächeln?",
        answers: ["ca. 12 Muskeln", "ca. 17 Muskeln", "ca. 25 Muskeln", "ca. 32 Muskeln"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Beim Lächeln bewegen sich rund 17 Gesichtsmuskeln synchron rund um Mund und Augen."
    },
  {
        id: "sch_mko_031",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welches Fassungsvermögen hat eine gesunde Harnblase vor starkem Harndrang?",
        answers: ["ca. 300 Milliliter", "ca. 500 Milliliter", "ca. 800 Milliliter", "ca. 1100 Milliliter"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Drang setzt ab ca. 300 ml ein; das maximale Fassungsvermögen liegt bei etwa 500 bis 800 Millilitern."
    },
  {
        id: "sch_mko_032",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welchen Ruhepuls pro Minute kann ein gut trainierter Ausdauersportler erreichen?",
        answers: ["ca. 20 Schläge/Min.", "ca. 30 Schläge/Min.", "ca. 40 Schläge/Min.", "ca. 50 Schläge/Min."],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Extrem gut trainierte Sportler haben ein vergrößertes Sportherz mit Ruhepulswerten von ca. 35 bis 40 Schlägen."
    },
  {
        id: "sch_mko_033",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Nervenzellen (Neuronen) enthält das menschliche Gehirn etwa?",
        answers: ["ca. 86 Milliarden", "ca. 120 Milliarden", "ca. 150 Milliarden", "ca. 180 Milliarden"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Moderne Zählungen bestätigen durchschnittlich etwa 86 Milliarden Nervenzellen im Gehirn."
    },
  {
        id: "sch_mko_034",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie hoch ist der Muskelanteil am Gesamtkörpergewicht bei gesunden Männern?",
        answers: ["ca. 30 Prozent", "ca. 40 Prozent", "ca. 50 Prozent", "ca. 60 Prozent"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Der normale Muskelanteil liegt bei Männern bei etwa 40 bis 45 %, bei Frauen bei rund 30 bis 35 %."
    },
  {
        id: "sch_mko_035",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Tage wächst eine einzelne Wimper, bevor sie von selbst ausfällt?",
        answers: ["ca. 60 Tage", "ca. 100 Tage", "ca. 150 Tage", "ca. 200 Tage"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Wimpern haben eine Lebensdauer von etwa 100 bis 150 Tagen, bevor sie erneuert werden."
    },
  {
        id: "sch_mko_036",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Millimeter wachsen Fingernägel im Durchschnitt pro Woche?",
        answers: ["ca. 0,2 Millimeter", "ca. 0,5 Millimeter", "ca. 0,7 Millimeter", "ca. 1,0 Millimeter"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Fingernägel wachsen ca. 0,7 bis 1 Millimeter pro Woche (ca. 3 bis 4 mm im Monat)."
    },
  {
        id: "sch_mko_037",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Prozent des gesamten vom Körper aufgenommenen Sauerstoffs verbraucht das Gehirn?",
        answers: ["ca. 20 Prozent", "ca. 32 Prozent", "ca. 44 Prozent", "ca. 56 Prozent"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Gehirn benötigt etwa 20 % des gesamten Sauerstoffs im Blut, obwohl es nur 2 % des Gewichts ausmacht."
    },
  {
        id: "sch_mko_038",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Gramm Reinesisen stecken im Körper eines erwachsenen Menschen?",
        answers: ["ca. 2 Gramm", "ca. 4 Gramm", "ca. 6 Gramm", "ca. 8 Gramm"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Im Körper befinden sich ca. 3,5 bis 5 Gramm Eisen, hauptsächlich gebunden im Blutfarbstoff Hämoglobin."
    },
  {
        id: "sch_mko_039",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Knochen befinden sich allein in einem einzelnen menschlichen Fuß?",
        answers: ["20 Knochen", "23 Knochen", "26 Knochen", "29 Knochen"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein Fuß besteht aus genau 26 Knochen – zusammen enthalten beide Füße ein Viertel aller Körperknochen."
    },
  {
        id: "sch_mko_040",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Knochen befinden sich in einer menschlichen Hand (inklusive Handwurzel)?",
        answers: ["21 Knochen", "23 Knochen", "25 Knochen", "27 Knochen"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Eine menschliche Hand besitzt exakt 27 Knochen (8 Handwurzelknochen, 5 Mittelhandknochen, 14 Fingerknochen)."
    },
  {
        id: "sch_mko_041",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange dauert ein vollständiger Herzzyklus (Anspannung und Entspannung) in Ruhe?",
        answers: ["ca. 0,8 Sekunden", "ca. 1,4 Sekunden", "ca. 2,0 Sekunden", "ca. 2,6 Sekunden"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Bei einem Puls von 75 Schlägen pro Minute dauert ein kompletter Herzschlag genau 0,8 Sekunden."
    },
  {
        id: "sch_mko_042",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Milliliter Luft atmet ein Erwachsener bei einem normalen Atemzug in Ruhe ein?",
        answers: ["ca. 300 Milliliter", "ca. 500 Milliliter", "ca. 700 Milliliter", "ca. 900 Milliliter"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das normale Atemzugvolumen eines erwachsenen Menschen liegt bei etwa 500 Millilitern Luft."
    },
  {
        id: "sch_mko_043",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welche normale Kerntemperatur hat der menschliche Körper im gesunden Zustand?",
        answers: ["ca. 35,5 Grad C", "ca. 36,2 Grad C", "ca. 37,0 Grad C", "ca. 37,8 Grad C"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Die normale Körperkerntemperatur im Inneren schwankt leicht um den Mittelwert von 37,0 °C."
    },
  {
        id: "sch_mko_044",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele kleine Muskeln steuern die feinen Bewegungen der Ohrmuschel?",
        answers: ["2 Muskeln", "4 Muskeln", "5 Muskeln", "6 Muskeln"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Jedes Ohr hat 6 kleine Muskeln, mit denen manchen Menschen das Wackeln der Ohren gelingt."
    },
  {
        id: "sch_mko_045",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welchen pH-Wert hat die Magensäure im nüchternen Magen des Menschen?",
        answers: ["pH 1,5 bis 2,0", "pH 2,8 bis 3,3", "pH 4,0 bis 4,5", "pH 5,2 bis 5,7"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Magensäure ist mit einem pH-Wert von 1,5 bis 2,0 extrem sauer, um Nahrung zu zersetzen und Keime zu töten."
    },
  {
        id: "sch_mko_046",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "In welchem Frequenzbereich liegt das Gehör eines jungen gesunden Menschen?",
        answers: ["10 bis 15.000 Hz", "20 bis 20.000 Hz", "30 bis 25.000 Hz", "40 bis 30.000 Hz"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Das menschliche Gehör nimmt Schwingungen zwischen 20 Hz (Tiefbass) und 20.000 Hz (hohe Töne) wahr."
    },
  {
        id: "sch_mko_047",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel wiegt das Herz eines erwachsenen Menschen im Durchschnitt?",
        answers: ["ca. 150 Gramm", "ca. 220 Gramm", "ca. 300 Gramm", "ca. 420 Gramm"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das faustgroße menschliche Herz wiegt bei Frauen ca. 250 bis 280 g, bei Männern ca. 300 bis 350 g."
    },
  {
        id: "sch_mko_048",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lang ist der menschliche Dünndarm im aufgerollten Zustand etwa?",
        answers: ["ca. 2 bis 3 Meter", "ca. 3 bis 4 Meter", "ca. 4 bis 5 Meter", "ca. 5 bis 6 Meter"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Dünndarm misst bei Erwachsenen je nach Körpergröße ca. 5 bis 6 Meter."
    },
  {
        id: "sch_mko_049",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lang ist der menschliche Dickdarm im Vergleich zum Dünndarm?",
        answers: ["ca. 1,5 Meter", "ca. 2,5 Meter", "ca. 3,5 Meter", "ca. 4,5 Meter"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Dickdarm ist kürzer, aber deutlich dicker als der Dünndarm und misst ca. 1,5 Meter."
    },
  {
        id: "sch_mko_050",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Geschmacksknospen hat ein Neugeborenes im Mundraum etwa?",
        answers: ["ca. 5.000 Knospen", "ca. 10.000 Knospen", "ca. 15.000 Knospen", "ca. 20.000 Knospen"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Babys kommen mit ca. 10.000 Geschmacksknospen zur Welt, die sich im Alter langsam reduzieren."
    },
  {
        id: "sch_mko_051",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Tränenflüssigkeit produzieren die Tränendrüsen pro Tag ohne Weinen?",
        answers: ["ca. 0,5 Milliliter", "ca. 1,0 Milliliter", "ca. 2,0 Milliliter", "ca. 3,5 Milliliter"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Die Tränendrüsen bilden täglich ca. 1,5 bis 2 Milliliter Flüssigkeit zur Befeuchtung des Auges."
    },
  {
        id: "sch_mko_052",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange verweilt eine durchschnittliche Mischkost-Mahlzeit im Magen?",
        answers: ["ca. 30 bis 60 Min.", "ca. 1 bis 2 Std.", "ca. 2 bis 3 Std.", "ca. 2 bis 4 Std."],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Im Magen verbleibt der Speisebrei je nach Fettgehalt zwischen 2 und 4 Stunden."
    },
  {
        id: "sch_mko_053",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Nach wie vielen Tagen hat sich die oberste Schicht der Haut komplett erneuert?",
        answers: ["ca. 28 Tage", "ca. 42 Tage", "ca. 56 Tage", "ca. 70 Tage"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Oberhaut (Epidermis) erneuert sich bei jungen Erwachsenen etwa alle 28 Tage vollständig."
    },
  {
        id: "sch_mko_054",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Schweißdrüsen befinden sich auf den beiden Fußsohlen zusammen?",
        answers: ["ca. 100.000 Drüsen", "ca. 250.000 Drüsen", "ca. 400.000 Drüsen", "ca. 550.000 Drüsen"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Die Fußsohlen besitzen eine sehr hohe Dichte mit rund 250.000 Schweißdrüsen."
    },
  {
        id: "sch_mko_055",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Prozent des Körpergewichts macht das Blut beim Menschen aus?",
        answers: ["ca. 4 Prozent", "ca. 6 Prozent", "ca. 8 Prozent", "ca. 10 Prozent"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das Blut macht bei Erwachsenen ca. 7 bis 8 Prozent des gesamten Körpergewichts aus."
    },
  {
        id: "sch_mko_056",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Aus welcher Entfernung kann das menschliche Auge in völliger Dunkelheit ein Kerzenlicht wahrnehmen?",
        answers: ["ca. 10 Kilometer", "ca. 25 Kilometer", "ca. 35 Kilometer", "ca. 48 Kilometer"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Bei flachem Terrain ohne Hindernisse erkennt die Netzhaut eine brennende Kerze aus bis zu 48 km Entfernung."
    },
  {
        id: "sch_mko_057",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele einzelne Wirbelknochen bilden die menschliche Wirbelsäule?",
        answers: ["33 Wirbel", "36 Wirbel", "39 Wirbel", "42 Wirbel"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Wirbelsäule besteht aus 33 bis 34 Wirbeln (7 Hals-, 12 Brust-, 5 Lendenwirbel sowie Kreuz- und Steißbein)."
    },
  {
        id: "sch_mko_058",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Kilogramm wiegt die menschliche Leber im gesunden Zustand?",
        answers: ["ca. 1,0 Kilogramm", "ca. 1,5 Kilogramm", "ca. 2,0 Kilogramm", "ca. 2,5 Kilogramm"],
        correct: 1,
        difficulty: "leicht",
        points: 10,
        explanation: "Die Leber ist das schwerste innere Organ und wiegt etwa 1,4 bis 1,8 Kilogramm."
    },
  {
        id: "sch_mko_059",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Haupt-Blutgruppen gibt es im weltweiten AB0-System?",
        answers: ["2 Hauptgruppen", "3 Hauptgruppen", "4 Hauptgruppen", "5 Hauptgruppen"],
        correct: 2,
        difficulty: "leicht",
        points: 10,
        explanation: "Das AB0-System teilt das Blut in die 4 Hauptgruppen A, B, AB und 0 ein."
    },
  {
        id: "sch_mko_060",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lang ist der kleinste Knochen im menschlichen Körper (der Steigbügel im Ohr)?",
        answers: ["ca. 1,5 Millimeter", "ca. 2,0 Millimeter", "ca. 2,5 Millimeter", "ca. 3,0 Millimeter"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Der Steigbügel im Mittelohr misst winzige 2,5 bis 3 Millimeter."
    },
  {
        id: "sch_mko_061",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Kopfhaare besitzen blonde Menschen im Durchschnitt?",
        answers: ["ca. 150.000 Haare", "ca. 200.000 Haare", "ca. 250.000 Haare", "ca. 300.000 Haare"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Blonde Menschen haben die dünnsten Haare, dafür aber mit ca. 150.000 die meisten einzelnen Kopfhaare."
    },
  {
        id: "sch_mko_062",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Kopfhaare besitzen rothaarige Menschen im Durchschnitt?",
        answers: ["ca. 60.000 Haare", "ca. 90.000 Haare", "ca. 120.000 Haare", "ca. 150.000 Haare"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Rothaarige haben besonders dickes Haar, mit rund 90.000 Haaren jedoch die geringste Gesamtzahl."
    },
  {
        id: "sch_mko_063",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welchen Beißdruck kann der menschliche Kiefermuskel auf den Backenzähnen erzeugen?",
        answers: ["ca. 30 Kilogramm", "ca. 50 Kilogramm", "ca. 80 Kilogramm", "ca. 110 Kilogramm"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Kaumuskel (Masseter) kann kurzzeitig einen Druck von bis zu 80 kg erzeugen."
    },
  {
        id: "sch_mko_064",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange benötigt ein Blutstropfen, um einmal den gesamten Körperkreislauf zu durchströmen?",
        answers: ["ca. 15 Sekunden", "ca. 30 Sekunden", "ca. 45 Sekunden", "ca. 60 Sekunden"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "In Ruhe benötigt das Blut etwa 60 Sekunden für eine komplette Runde durch Herz, Lunge und Körper."
    },
  {
        id: "sch_mko_065",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "In wie viele Verzweigungsstufen unterteilen sich die Bronchien in der Lunge?",
        answers: ["ca. 23 Stufen", "ca. 30 Stufen", "ca. 37 Stufen", "ca. 44 Stufen"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Der Bronchialbaum verzweigt sich schrittweise in genau 23 Generationen von immer feineren Kanälen."
    },
  {
        id: "sch_mko_066",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Lungenbläschen (Alveolen) besitzen beide Lungenflügel zusammen?",
        answers: ["ca. 150 Millionen", "ca. 300 Millionen", "ca. 450 Millionen", "ca. 600 Millionen"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "In beiden Lungenflügeln befinden sich etwa 300 Millionen winzige Lungenbläschen zum Gasaustausch."
    },
  {
        id: "sch_mko_067",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welche Gesamtfläche ergäben alle Lungenbläschen, wenn man sie flach ausbreiten würde?",
        answers: ["ca. 40 Quadratmeter", "ca. 60 Quadratmeter", "ca. 100 Quadratmeter", "ca. 140 Quadratmeter"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Aufgefaltet bedecken die Lungenbläschen eine riesige Fläche von etwa 80 bis 100 Quadratmetern."
    },
  {
        id: "sch_mko_068",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Milliliter Wasser gibt der Körper täglich allein über die Atemluft ab?",
        answers: ["ca. 100 Milliliter", "ca. 250 Milliliter", "ca. 350 Milliliter", "ca. 500 Milliliter"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Über die angefeuchtete Ausatemluft verlieren wir täglich etwa 400 bis 500 ml reine Flüssigkeit."
    },
  {
        id: "sch_mko_069",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Nach wie vielen Jahren haben sich fast alle Zellen des Körpers (statistischer Schnitt) erneuert?",
        answers: ["ca. 7 Jahre", "ca. 10 Jahre", "ca. 13 Jahre", "ca. 16 Jahre"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Durch stetige Zellteilung ist der Großteil des Körpers nach rund 7 bis 10 Jahren komplett erneuert."
    },
  {
        id: "sch_mko_070",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie schnell erneuern sich die Zellen der empfindlichen Magenschleimhaut?",
        answers: ["ca. 1 bis 2 Tage", "ca. 3 bis 5 Tage", "ca. 7 bis 9 Tage", "ca. 11 bis 13 Tage"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Wegen der aggressiven Säure erneuert der Magen seine Schleimhaut extrem schnell alle 3 bis 5 Tage."
    },
  {
        id: "sch_mko_071",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Aus wie vielen einzelnen Knochen setzt sich der menschliche Schädel zusammen?",
        answers: ["14 Knochen", "18 Knochen", "22 Knochen", "26 Knochen"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Der Schädel besteht aus 22 Knochen (8 Schädelknochen und 14 Gesichtsknochen), die fest verzahnt sind."
    },
  {
        id: "sch_mko_072",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Liter Primärharn filtern beide Nieren täglich aus dem Blut?",
        answers: ["ca. 90 Liter", "ca. 120 Liter", "ca. 150 Liter", "ca. 180 Liter"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Die Nieren filtern täglich rund 180 Liter Flüssigkeit, konzentrieren diese jedoch auf ca. 1,5 Liter Urin."
    },
  {
        id: "sch_mko_073",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Liter Endharn (Urin) scheidet ein Erwachsener pro Tag im Durchschnitt aus?",
        answers: ["ca. 1,5 Liter", "ca. 2,5 Liter", "ca. 3,5 Liter", "ca. 4,5 Liter"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Bei normaler Flüssigkeitsaufnahme scheidet der Mensch täglich etwa 1,0 bis 1,5 Liter Urin aus."
    },
  {
        id: "sch_mko_074",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Prozent der Trockenmasse des menschlichen Gehirns bestehen aus Fett?",
        answers: ["ca. 40 Prozent", "ca. 60 Prozent", "ca. 75 Prozent", "ca. 85 Prozent"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Ohne Wasser besteht das Gehirn zu rund 60 % aus Lipiden (Fett), was es zum fettreichsten Organ macht."
    },
  {
        id: "sch_mko_075",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel schneller wachsen Fingernägel im Vergleich zu den Zehennägeln?",
        answers: ["ca. 1,5-mal so schnell", "ca. 2-mal so schnell", "ca. 4-mal so schnell", "ca. 6-mal so schnell"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Fingernägel wachsen aufgrund der besseren Durchblutung ca. 4-mal schneller als Zehennägel."
    },
  {
        id: "sch_mko_076",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele sichtbare Geschmackspapillen befinden sich auf der Zungenoberfläche?",
        answers: ["ca. 500 Papillen", "ca. 1.000 Papillen", "ca. 1.500 Papillen", "ca. 2.000 Papillen"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Auf der Zunge liegen etwa 2.000 Erhebungen (Papillen), in denen die mikroskopischen Knospen sitzen."
    },
  {
        id: "sch_mko_077",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel wiegen beide Nieren eines erwachsenen Menschen zusammen etwa?",
        answers: ["ca. 300 Gramm", "ca. 450 Gramm", "ca. 600 Gramm", "ca. 750 Gramm"],
        correct: 0,
        difficulty: "leicht",
        points: 10,
        explanation: "Eine einzelne Niere wiegt rund 150 Gramm, beide zusammen bringen also ca. 300 Gramm auf die Waage."
    },
  {
        id: "sch_mko_078",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Nephrone (Filtereinheiten) besitzt eine menschliche Niere ungefähr?",
        answers: ["ca. 500.000 Nephrone", "ca. 1.000.000 Nephrone", "ca. 1.500.000 Nephrone", "ca. 2.000.000 Nephrone"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Jede Niere enthält etwa 1 Million mikroskopisch feine Nephrone zur Blutreinigung."
    },
  {
        id: "sch_mko_079",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie dick ist die menschliche Hornhaut (Cornea) des Auges in der Mitte?",
        answers: ["ca. 0,2 Millimeter", "ca. 0,3 Millimeter", "ca. 0,5 Millimeter", "ca. 0,8 Millimeter"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Die hochtransparente Hornhaut im Zentrum des Auges ist nur knapp 0,5 Millimeter dick."
    },
  {
        id: "sch_mko_080",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welchen Durchmesser hat eine reife menschliche Eizelle (die größte Zelle des Körpers)?",
        answers: ["ca. 0,02 Millimeter", "ca. 0,05 Millimeter", "ca. 0,08 Millimeter", "ca. 0,12 Millimeter"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Die Eizelle misst etwa 0,12 mm (120 Mikrometer) und ist mit bloßem Auge gerade noch als Pünktchen erkennbar."
    },
  {
        id: "sch_mko_081",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Spermien befinden sich im Normalfall in einem Milliliter Ejakulat?",
        answers: ["ca. 20 bis 100 Mio.", "ca. 110 bis 180 Mio.", "ca. 190 bis 260 Mio.", "ca. 270 bis 340 Mio."],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein gesunder Milliliter Samenflüssigkeit enthält zwischen 20 und 100 Millionen Spermien."
    },
  {
        id: "sch_mko_082",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange dauert die Entwicklung eines neuen Spermiums im menschlichen Körper?",
        answers: ["ca. 30 Tage", "ca. 64 Tage", "ca. 90 Tage", "ca. 120 Tage"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Von der Stammzelle bis zum ausgereiften Spermium vergehen etwa 64 Tage."
    },
  {
        id: "sch_mko_083",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel wiegt der längste Knochen des Körpers (Oberschenkelknochen) durchschnittlich?",
        answers: ["ca. 150 Gramm", "ca. 280 Gramm", "ca. 450 Gramm", "ca. 600 Gramm"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der Oberschenkelknochen (Femur) ist der längste und stabilste Knochen und wiegt ca. 450 Gramm."
    },
  {
        id: "sch_mko_084",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Prozent des gesamten Körper-Kalziums stecken in Knochen und Zähnen?",
        answers: ["ca. 85 Prozent", "ca. 90 Prozent", "ca. 95 Prozent", "ca. 99 Prozent"],
        correct: 3,
        difficulty: "leicht",
        points: 10,
        explanation: "Knochen und Zähne dienen als Vorratsspeicher und enthalten 99 % des gesamten Kalziums im Körper."
    },
  {
        id: "sch_mko_085",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Rippenpaare setzen als 'echte Rippen' direkt vorne am Brustbein an?",
        answers: ["7 Rippenpaare", "9 Rippenpaare", "11 Rippenpaare", "12 Rippenpaare"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die oberen 7 Rippenpaare sind direkt mit dem Brustbein verbunden; die restlichen 5 heißen 'falsche Rippen'."
    },
  {
        id: "sch_mko_086",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lang ist die menschliche Luftröhre (Trachea) beim Erwachsenen etwa?",
        answers: ["ca. 6 bis 8 cm", "ca. 10 bis 12 cm", "ca. 14 bis 16 cm", "ca. 18 bis 20 cm"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Die durch Knorpelringe stabilisierte Luftröhre ist etwa 10 bis 12 cm lang."
    },
  {
        id: "sch_mko_087",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele einzelne Lungenlappen besitzt der rechte Lungenflügel des Menschen?",
        answers: ["1 Lungenlappen", "2 Lungenlappen", "3 Lungenlappen", "4 Lungenlappen"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Der rechte Lungenflügel unterteilt sich in 3 Lappen (Ober-, Mittel- und Unterlappen)."
    },
  {
        id: "sch_mko_088",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Lungenlappen besitzt der linke Lungenflügel (Platz für das Herz)?",
        answers: ["3 Lungenlappen", "4 Lungenlappen", "1 Lungenlappen", "2 Lungenlappen"],
        correct: 3,
        difficulty: "mittel",
        points: 10,
        explanation: "Da das Herz links liegt, ist der linke Lungenflügel kleiner und hat nur 2 Lungenlappen."
    },
  {
        id: "sch_mko_089",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie lange überleben Blutplättchen (Thrombozyten) im Blutkreislauf?",
        answers: ["ca. 8 bis 12 Tage", "ca. 20 bis 25 Tage", "ca. 35 bis 40 Tage", "ca. 50 bis 60 Tage"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Blutplättchen für die Wundheilung haben eine kurze Lebensdauer von etwa 8 bis 12 Tagen."
    },
  {
        id: "sch_mko_090",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie hoch ist der Kohlendioxid-Anteil (CO2) in der normalen Ausatemluft des Menschen?",
        answers: ["ca. 2 Prozent", "ca. 4 Prozent", "ca. 6 Prozent", "ca. 8 Prozent"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Einatemluft enthält 0,04 % CO2, während die Ausatemluft ca. 4 % Kohlendioxid enthält."
    },
  {
        id: "sch_mko_091",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie dick ist die Wand der linken Herzkammer beim gesunden Erwachsenen?",
        answers: ["ca. 5 Millimeter", "ca. 8 Millimeter", "ca. 12 Millimeter", "ca. 18 Millimeter"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "Die linke Kammer muss den Hauptkreislauf versorgen und hat eine kräftige Wanddicke von ca. 10 bis 12 mm."
    },
  {
        id: "sch_mko_092",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welches normale Speichervolumen besitzt die menschliche Gallenblase?",
        answers: ["ca. 15 Milliliter", "ca. 30 Milliliter", "ca. 45 Milliliter", "ca. 60 Milliliter"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Die birnenförmige Gallenblase fasst etwa 30 bis 60 Milliliter eingedickte Galle."
    },
  {
        id: "sch_mko_093",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele zusätzliche Geschmacksknospen sitzen außerhalb der Zunge am Gaumen?",
        answers: ["ca. 2.000 Knospen", "ca. 4.000 Knospen", "ca. 6.000 Knospen", "ca. 8.000 Knospen"],
        correct: 0,
        difficulty: "schwer",
        points: 10,
        explanation: "Auch am weichen Gaumen und Kehlkopf sitzen zusätzlich ca. 2.000 funktionale Geschmacksknospen."
    },
  {
        id: "sch_mko_094",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viel Speichel geben die Speicheldrüsen bei der Nahrungsaufnahme pro Minute maximal ab?",
        answers: ["ca. 0,5 Milliliter", "ca. 1,5 Milliliter", "ca. 2,5 Milliliter", "ca. 3,5 Milliliter"],
        correct: 1,
        difficulty: "schwer",
        points: 10,
        explanation: "Bei leckerem Essen steigern die Drüsen die Abgabe auf bis zu 1,5 bis 2 Milliliter pro Minute."
    },
  {
        id: "sch_mko_095",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Welche Spitzengeschwindigkeit erreicht ein starker Hustenstoß beim Ausstoßen?",
        answers: ["ca. 100 km/h", "ca. 200 km/h", "ca. 300 km/h", "ca. 400 km/h"],
        correct: 2,
        difficulty: "mittel",
        points: 10,
        explanation: "Ein heftiger Hustenstoß drückt die Luft blitzartig mit bis zu 300 km/h aus den Bronchien."
    },
  {
        id: "sch_mko_096",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "In wie viele Schichten gliedert sich die menschliche Oberhaut (Epidermis)?",
        answers: ["2 Schichten", "3 Schichten", "4 Schichten", "5 Schichten"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Die Oberhaut besteht aus 5 Schichten (von der Keimschicht bis zur abgestorbenen Hornschicht)."
    },
  {
        id: "sch_mko_097",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie dünn ist die Haut an den Augenlidern (die dünnste Haut des Körpers)?",
        answers: ["ca. 0,5 Millimeter", "ca. 1,0 Millimeter", "ca. 1,5 Millimeter", "ca. 2,0 Millimeter"],
        correct: 0,
        difficulty: "mittel",
        points: 10,
        explanation: "Die Haut der Augenlider ist extrem zart und misst nur ca. 0,5 Millimeter."
    },
  {
        id: "sch_mko_098",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie dick ist die Hornhautschicht an den Fußsohlen bei starker Beanspruchung?",
        answers: ["ca. 2 Millimeter", "ca. 4 Millimeter", "ca. 6 Millimeter", "ca. 8 Millimeter"],
        correct: 1,
        difficulty: "mittel",
        points: 10,
        explanation: "An stark belasteten Stellen wie den Fersen kann die Hautschicht bis zu 4 Millimeter dick werden."
    },
  {
        id: "sch_mko_099",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Zapfen (Sehzellen für Farben) befinden sich in einer menschlichen Netzhaut?",
        answers: ["ca. 2 Millionen", "ca. 4 Millionen", "ca. 6 Millionen", "ca. 8 Millionen"],
        correct: 2,
        difficulty: "schwer",
        points: 10,
        explanation: "In der Netzhaut sitzen ca. 6 Millionen Zapfen für das Farbsehen bei Tageslicht."
    },
  {
        id: "sch_mko_100",
        category: "schaetzen_mensch_koerper",
        area: "spass",
        subject: "schaetzen",
        question: "Wie viele Stäbchen (Sehzellen für Hell-Dunkel) befinden sich in der Netzhaut?",
        answers: ["ca. 60 Millionen", "ca. 90 Millionen", "ca. 100 Millionen", "ca. 120 Millionen"],
        correct: 3,
        difficulty: "schwer",
        points: 10,
        explanation: "Für das Dämmerungs- und Nachtsehen sorgen rund 120 Millionen lichtempfindliche Stäbchen."
    }
];

if (typeof window !== "undefined") window.SPASS_SCHAETZFRAGEN_QUESTIONS = SPASS_SCHAETZFRAGEN_QUESTIONS;
