const K10_DEUTSCH_QUESTIONS = [
  // ================================================================
  // 1. LITERARISCHE TEXTE – DRAMA (20 Fragen)
  // ================================================================
  {
    id: "q10_d_001",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man den Teil eines Dramas, in dem der zentrale Konflikt erstmals deutlich wird?",
    answers: ["Exposition", "Klimax", "Peripetie", "Katastrophe"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "In der Exposition werden Figuren, Ort, Zeit und der Ausgangskonflikt vorgestellt."
  },
  {
    id: "q10_d_002",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welches Merkmal kennzeichnet das klassische aristotelische Drama besonders?",
    answers: ["Einheit von Ort, Zeit und Handlung", "Viele Ortswechsel und Zeitsprünge", "Offenes Ende ohne Auflösung", "Verzicht auf Dialoge"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Aristoteles forderte die drei Einheiten für ein geschlossenes Drama."
  },
  {
    id: "q10_d_003",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie heißt der Wendepunkt in einem klassischen Drama, an dem sich das Geschehen umkehrt?",
    answers: ["Peripetie", "Exposition", "Retardation", "Prolog"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Peripetie ist der Umschlag vom Glück zum Unglück oder umgekehrt."
  },
  {
    id: "q10_d_004",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was unterscheidet das epische Theater nach Brecht vom aristotelischen Drama?",
    answers: ["Verfremdungseffekt und Distanz zum Geschehen", "Strenge Einheit von Ort und Zeit", "Rein emotionale Identifikation der Zuschauer", "Verzicht auf politische Aussagen"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Brecht wollte durch Verfremdung zum Nachdenken anregen statt zur Einfühlung."
  },
  {
    id: "q10_d_005",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die abschließende Lösung oder den Untergang am Ende eines Dramas?",
    answers: ["Katastrophe", "Exposition", "Höhepunkt", "Zwischenakt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Katastrophe bildet den Abschluss der dramatischen Handlung."
  },
  {
    id: "q10_d_006",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Textsorte gehört zur dramatischen Gattung?",
    answers: ["Tragödie und Komödie", "Roman und Novelle", "Ballade und Sonett", "Essay und Reportage"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Tragödie und Komödie sind die klassischen Formen des Dramas."
  },
  {
    id: "q10_d_007",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was bezeichnet man als 'Figurenkonstellation' in einem Drama?",
    answers: ["Die Beziehungen und Gegensätze zwischen den Figuren", "Die Anzahl der Auftritte einer Figur", "Die Kostüme der Schauspieler", "Die Länge der Monologe"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Figurenkonstellation zeigt, wie Figuren zueinander stehen und handeln."
  },
  {
    id: "q10_d_008",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man einen längeren Redeabschnitt einer Figur, der an sich selbst gerichtet ist?",
    answers: ["Monolog", "Dialog", "Stichomythie", "Regieanweisung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Monolog äußert eine Figur ihre Gedanken ohne direkten Ansprechpartner."
  },
  {
    id: "q10_d_009",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine 'Regieanweisung' in einem dramatischen Text?",
    answers: ["Hinweis des Autors zu Spielweise, Ort oder Gestik", "Ein langer Monolog der Hauptfigur", "Die Zusammenfassung der Handlung", "Ein Liedtext im Stück"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Regieanweisungen geben Hinweise zur Inszenierung und sind nicht gesprochen."
  },
  {
    id: "q10_d_010",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welches Drama gilt als klassisches Beispiel für ein bürgerliches Trauerspiel?",
    answers: ["Kabale und Liebe von Schiller", "Faust von Goethe", "Die Räuber von Schiller", "Nathan der Weise von Lessing"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Kabale und Liebe behandelt den Konflikt zwischen Stand und Liebe im Bürgertum."
  },
  {
    id: "q10_d_011",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was bedeutet 'offenes Drama' im Gegensatz zum geschlossenen Drama?",
    answers: ["Episodischer Aufbau mit mehreren Handlungssträngen", "Strenge Einhaltung der drei Einheiten", "Ausschließlich komischer Charakter", "Verzicht auf jegliche Figuren"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Offene Dramen (z. B. bei Brecht) brechen mit der klassischen Geschlossenheit."
  },
  {
    id: "q10_d_012",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man den schnellen Wechsel kurzer Redebeiträge zwischen zwei Figuren?",
    answers: ["Stichomythie", "Monolog", "Chorlied", "Epilog"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Stichomythie steigert die Spannung durch raschen Dialogwechsel."
  },
  {
    id: "q10_d_013",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Funktion hat der Prolog in vielen klassischen Dramen?",
    answers: ["Einführung in Handlung und Thema", "Auflösung des Konflikts", "Zusammenfassung am Ende", "Musikalisches Zwischenspiel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Prolog bereitet das Publikum auf das folgende Geschehen vor."
  },
  {
    id: "q10_d_014",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'tragischer Schuld' in der klassischen Tragödie?",
    answers: ["Fehler oder Charakterzug, der zum Untergang führt", "Absichtliche böse Tat ohne Grund", "Zufälliges Unglück ohne Ursache", "Schuld der Zuschauer"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die tragische Schuld (Hamartia) führt den Helden unausweichlich in den Untergang."
  },
  {
    id: "q10_d_015",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welches Element gehört typischerweise zum Aufbau eines klassischen fünfaktigen Dramas?",
    answers: ["Steigende Handlung bis zum Höhepunkt", "Nur zwei Akte ohne Höhepunkt", "Reine Beschreibung ohne Dialog", "Zufällige Szenenfolge"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die steigende Handlung führt zur Peripetie und Katastrophe."
  },
  {
    id: "q10_d_016",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'Antagonist' in einem Drama?",
    answers: ["Gegenspieler der Hauptfigur", "Freund der Hauptfigur", "Erzähler außerhalb der Handlung", "Zuschauer im Publikum"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Antagonist steht dem Protagonisten gegenüber und erzeugt den Konflikt."
  },
  {
    id: "q10_d_017",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Technik, bei der das Publikum mehr weiß als die Figuren auf der Bühne?",
    answers: ["Dramatische Ironie", "Innere Monologtechnik", "Stream of Consciousness", "Erlebte Rede"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Dramatische Ironie entsteht durch den Wissensvorsprung des Publikums."
  },
  {
    id: "q10_d_018",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welches Merkmal ist typisch für Brechts episches Theater?",
    answers: ["Unterbrechung der Handlung durch Songs und Kommentare", "Strenge Einhaltung der drei Einheiten", "Ausschließlich private Konflikte", "Verzicht auf jegliche Botschaft"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Songs und Kommentare dienen der Verfremdung und dem Nachdenken."
  },
  {
    id: "q10_d_019",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was bezeichnet der Begriff 'Katharsis' in der Tragödientheorie?",
    answers: ["Reinigung der Affekte durch Mitleid und Furcht", "Komische Auflösung am Ende", "Einführung neuer Figuren", "Musikalische Untermalung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Aristoteles sah in der Katharsis die reinigende Wirkung der Tragödie."
  },
  {
    id: "q10_d_020",
    category: "k10_deutsch",
    topic: "drama",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Aussage trifft auf eine 'geschlossene Form' des Dramas zu?",
    answers: ["Klare Struktur mit Anfang, Mitte und Ende", "Viele Handlungsstränge ohne Auflösung", "Verzicht auf Dialoge", "Zufällige Szenen ohne Zusammenhang"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die geschlossene Form folgt einer strengen dramatischen Architektur."
  },

  // ================================================================
  // 2. EPIK & ERZÄHLTECHNIK (15 Fragen)
  // ================================================================
  {
    id: "q10_d_021",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Erzählperspektive, bei der der Erzähler alles über alle Figuren weiß?",
    answers: ["Auktoriale Erzählperspektive", "Personale Erzählperspektive", "Ich-Erzählung", "Neutrale Erzählperspektive"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der auktoriale Erzähler kommentiert und kennt Gedanken und Hintergründe."
  },
  {
    id: "q10_d_022",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Erzählperspektive beschränkt sich auf die Wahrnehmung einer Figur?",
    answers: ["Personale Erzählperspektive", "Auktoriale Erzählperspektive", "Neutrale Erzählperspektive", "Rahmenerzählung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei personaler Erzählsituation erlebt der Leser die Welt aus der Sicht einer Figur."
  },
  {
    id: "q10_d_023",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine 'Rahmenerzählung'?",
    answers: ["Eine Geschichte, die eine Binnenerzählung umschließt", "Ein Roman ohne Kapitel", "Eine reine Dialogform", "Ein Gedicht in Prosa"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Rahmenerzählung bildet den äußeren Rahmen für eine oder mehrere Binnengeschichten."
  },
  {
    id: "q10_d_024",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie unterscheidet sich eine Novelle typischerweise von einem Roman?",
    answers: ["Konzentration auf ein zentrales Ereignis", "Sehr große Länge und viele Handlungsstränge", "Ausschließlich lyrische Form", "Verzicht auf Figuren"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Novelle ist kürzer und fokussiert oft auf eine unerhörte Begebenheit."
  },
  {
    id: "q10_d_025",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'erlebter Rede'?",
    answers: ["Gedanken einer Figur in der 3. Person ohne Anführungszeichen", "Direkte wörtliche Rede mit Anführungszeichen", "Reine Beschreibung der Landschaft", "Monolog in der 1. Person"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Erlebte Rede mischt Erzählerbericht und Figurenbewusstsein."
  },
  {
    id: "q10_d_026",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Erzähltechnik gibt Gedanken einer Figur unmittelbar wieder?",
    answers: ["Innerer Monolog", "Auktorialer Kommentar", "Neutrale Beschreibung", "Dialog ohne Gedanken"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der innere Monolog zeigt das ungeschönte Denken der Figur."
  },
  {
    id: "q10_d_027",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was kennzeichnet eine 'Ich-Erzählung'?",
    answers: ["Der Erzähler ist selbst Teil der Handlung", "Der Erzähler kennt alle Gedanken", "Es gibt keinen Erzähler", "Nur Dialoge ohne Bericht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In der Ich-Form berichtet eine Figur aus ihrer eigenen Perspektive."
  },
  {
    id: "q10_d_028",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man den Wechsel zwischen Erzählzeit und erzählter Zeit?",
    answers: ["Zeitstruktur der Erzählung", "Figurenkonstellation", "Stilmittel der Ironie", "Gattungsmerkmal"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Erzählzeit ist die Dauer des Lesens, erzählte Zeit die Dauer der Handlung."
  },
  {
    id: "q10_d_029",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'allwissender Erzähler'?",
    answers: ["Ein Erzähler mit Überblick über alle Geschehnisse", "Ein Erzähler, der nur eine Figur kennt", "Ein Erzähler ohne Kommentar", "Ein Erzähler in der Ich-Form"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der allwissende (auktoriale) Erzähler kann alles wissen und kommentieren."
  },
  {
    id: "q10_d_030",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Form der Zeitgestaltung beschleunigt die Erzählung stark?",
    answers: ["Zeitraffung", "Zeitdehnung", "Gleichzeitigkeit", "Rückblende"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei Zeitraffung wird lange erzählte Zeit in kurzer Erzählzeit zusammengefasst."
  },
  {
    id: "q10_d_031",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Stream of Consciousness'?",
    answers: ["Ungefilterter Gedankenstrom einer Figur", "Streng logischer Bericht", "Reine Dialogform", "Beschreibung äußerer Handlungen"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Der Bewusstseinsstrom gibt Gedanken assoziativ und ungeordnet wieder."
  },
  {
    id: "q10_d_032",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man eine kurze erzählende Prosaform mit pointierter Wendung?",
    answers: ["Anekdote oder Kurzgeschichte", "Epos", "Roman", "Drama"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kurzgeschichten und Anekdoten sind knappe epische Formen."
  },
  {
    id: "q10_d_033",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine 'Rückblende' in einem erzählenden Text?",
    answers: ["Rückgriff auf frühere Ereignisse", "Vorausschau auf zukünftige Ereignisse", "Gleichzeitige Handlung", "Beschreibung der Gegenwart"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Rückblende (Analepse) unterbricht die chronologische Ordnung."
  },
  {
    id: "q10_d_034",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Erzählhaltung kommentiert und wertet das Geschehen deutlich?",
    answers: ["Auktoriale Erzählhaltung", "Personale Erzählhaltung", "Neutrale Erzählhaltung", "Ich-Erzählung ohne Kommentar"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der auktoriale Erzähler nimmt Stellung und deutet das Geschehen."
  },
  {
    id: "q10_d_035",
    category: "k10_deutsch",
    topic: "epik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was kennzeichnet eine 'multiperspektivische' Erzählung?",
    answers: ["Mehrere Sichtweisen auf dasselbe Geschehen", "Nur eine Figursperspektive", "Kein Erzähler", "Reine Dialogform"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mehrere Perspektiven ermöglichen ein komplexeres Bild der Ereignisse."
  },

  // ================================================================
  // 3. LYRIK & STILMITTEL (20 Fragen)
  // ================================================================
  {
    id: "q10_d_036",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Wiederholung gleicher Laute am Versanfang?",
    answers: ["Alliteration", "Assonanz", "Reim", "Metapher"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Alliteration ist der Stabreim am Wortanfang (z. B. Wind und Wogen)."
  },
  {
    id: "q10_d_037",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine Metapher?",
    answers: ["Übertragung eines Wortes auf einen anderen Bedeutungsbereich", "Vergleich mit 'wie' oder 'als'", "Übertreibung einer Aussage", "Untertreibung einer Aussage"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Metapher ersetzt einen Begriff durch einen bildhaften Ausdruck ohne Vergleichspartikel."
  },
  {
    id: "q10_d_038",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie unterscheidet sich ein Vergleich von einer Metapher?",
    answers: ["Der Vergleich verwendet 'wie' oder 'als'", "Der Vergleich verzichtet auf Bildlichkeit", "Der Vergleich ist immer ironisch", "Der Vergleich hat keinen Sinn"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beim Vergleich bleibt die Vergleichspartikel erhalten, bei der Metapher nicht."
  },
  {
    id: "q10_d_039",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine Personifikation?",
    answers: ["Vermenschlichung von Abstraktem oder Unbelebtem", "Vergleich zweier Menschen", "Beschreibung einer Person", "Übertreibung einer Eigenschaft"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Personifikation erhalten Dinge oder Begriffe menschliche Eigenschaften."
  },
  {
    id: "q10_d_040",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die bewusste Übertreibung als Stilmittel?",
    answers: ["Hyperbel", "Litotes", "Euphemismus", "Ironie"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Hyperbel steigert eine Aussage weit über das Maß hinaus."
  },
  {
    id: "q10_d_041",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine Anapher?",
    answers: ["Wiederholung gleicher Wörter am Satz- oder Versanfang", "Wiederholung am Versende", "Gegensatz zweier Begriffe", "Aufzählung ohne Verbindung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Anapher betont durch Wiederholung am Anfang (z. B. 'Ich kam, ich sah…')."
  },
  {
    id: "q10_d_042",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man den Gleichklang am Versende?",
    answers: ["Endreim", "Alliteration", "Assonanz", "Onomatopoesie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Endreim verbindet Verse klanglich am Ende."
  },
  {
    id: "q10_d_043",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Enjambement'?",
    answers: ["Zeilensprung ohne syntaktischen Einschnitt", "Strenger Endreim", "Wiederholung eines Wortes", "Gegensatzbildung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Beim Enjambement läuft der Satz über das Versende hinaus weiter."
  },
  {
    id: "q10_d_044",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Gedichtform besteht aus 14 Versen mit festem Reimschema?",
    answers: ["Sonett", "Ballade", "Haiku", "Ode"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Sonett hat in der klassischen Form 14 Verse (zwei Quartette und zwei Terzette)."
  },
  {
    id: "q10_d_045",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine Allegorie?",
    answers: ["Sinnbildliche Darstellung eines abstrakten Begriffs", "Einfacher Vergleich", "Lautmalerei", "Wortspiel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Allegorie verkörpert Ideen (z. B. Justitia als Frau mit Waage)."
  },
  {
    id: "q10_d_046",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Lautmalerei in der Lyrik?",
    answers: ["Onomatopoesie", "Metapher", "Hyperbel", "Anapher"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Onomatopoesie ahmt Naturlaute sprachlich nach (z. B. 'Kuckuck')."
  },
  {
    id: "q10_d_047",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein Oxymoron?",
    answers: ["Verbindung widersprüchlicher Begriffe", "Einfache Wiederholung", "Lautmalerei", "Vergleich mit 'wie'"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Ein Oxymoron verbindet Gegensätze (z. B. 'beredtes Schweigen')."
  },
  {
    id: "q10_d_048",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Funktion hat der Reim in einem Gedicht häufig?",
    answers: ["Klangliche Bindung und Strukturierung", "Rein inhaltliche Information", "Nur optische Gestaltung", "Vermeidung von Rhythmus"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Reime gliedern und erzeugen musikalische Wirkung."
  },
  {
    id: "q10_d_049",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was bezeichnet man als 'lyrisches Ich'?",
    answers: ["Die sprechende Instanz im Gedicht", "Den realen Autor", "Eine Figur im Roman", "Den Leser"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das lyrische Ich ist nicht identisch mit dem Autor, sondern eine Textinstanz."
  },
  {
    id: "q10_d_050",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Wiederholung gleicher Vokale in betonten Silben?",
    answers: ["Assonanz", "Alliteration", "Endreim", "Konsonanz"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Assonanz ist der Gleichklang der Vokale bei unterschiedlichen Konsonanten."
  },
  {
    id: "q10_d_051",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist eine Antithese?",
    answers: ["Gegenüberstellung entgegengesetzter Begriffe", "Wiederholung gleicher Wörter", "Lautmalerei", "Übertreibung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Antithese stellt Gegensätze scharf gegenüber (z. B. 'Krieg und Frieden')."
  },
  {
    id: "q10_d_052",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Gedichtform erzählt eine Handlung und ist oft länger?",
    answers: ["Ballade", "Sonett", "Haiku", "Epigramm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Ballade verbindet lyrische, epische und dramatische Elemente."
  },
  {
    id: "q10_d_053",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Kadenz' in der Verslehre?",
    answers: ["Abschluss eines Verses (männlich oder weiblich)", "Reimschema eines Gedichts", "Anzahl der Strophen", "Thema des Gedichts"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Die Kadenz beschreibt, ob der Vers auf betonter oder unbetonter Silbe endet."
  },
  {
    id: "q10_d_054",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die bewusste Abschwächung einer Aussage?",
    answers: ["Litotes oder Understatement", "Hyperbel", "Metapher", "Anapher"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Litotes verneint das Gegenteil (z. B. 'nicht schlecht' für 'gut')."
  },
  {
    id: "q10_d_055",
    category: "k10_deutsch",
    topic: "lyrik",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein Chiasmus?",
    answers: ["Überkreuzte Stellung von Satzgliedern", "Einfache Wiederholung", "Lautmalerei", "Vergleich"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Beim Chiasmus werden Glieder über Kreuz gestellt (a-b-b-a)."
  },

  // ================================================================
  // 4. ARGUMENTATION & ERÖRTERUNG (15 Fragen)
  // ================================================================
  {
    id: "q10_d_056",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist der Unterschied zwischen linearer und dialektischer Erörterung?",
    answers: ["Dialektisch wägt Pro und Contra ab", "Linear behandelt nur eine Seite", "Dialektisch verzichtet auf Beispiele", "Linear ist immer kürzer"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die dialektische Erörterung stellt Argumente beider Seiten gegenüber."
  },
  {
    id: "q10_d_057",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welcher Teil einer Erörterung enthält die eigene begründete Stellungnahme?",
    answers: ["Schluss / Fazit", "Einleitung", "Hauptteil ohne Wertung", "Titel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Schluss wird das Ergebnis der Argumentation zusammengefasst und bewertet."
  },
  {
    id: "q10_d_058",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein stichhaltiges Argument?",
    answers: ["Behauptung mit nachvollziehbarer Begründung und Beleg", "Reine Meinung ohne Begründung", "Emotionaler Ausruf", "Wiederholung der These"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gute Argumente sind begründet und durch Beispiele oder Fakten gestützt."
  },
  {
    id: "q10_d_059",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Gegenposition in einer dialektischen Erörterung?",
    answers: ["Antithese", "These", "Synthese", "Hypothese"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Antithese stellt die Gegenthese zur Ausgangsthese dar."
  },
  {
    id: "q10_d_060",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'materialgestütztem Schreiben'?",
    answers: ["Schreiben auf Grundlage vorgegebener Texte und Materialien", "Freies Schreiben ohne Vorgaben", "Nur mündliche Präsentation", "Abschreiben eines Textes"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Materialgestütztes Schreiben nutzt vorgegebene Quellen als Grundlage."
  },
  {
    id: "q10_d_061",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Funktion hat die Einleitung einer Erörterung?",
    answers: ["Hinführung zum Thema und These", "Zusammenfassung aller Argumente", "Nur stilistische Ausschmückung", "Widerspruch zur These"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Einleitung führt in das Thema ein und formuliert oft die Ausgangsthese."
  },
  {
    id: "q10_d_062",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'Scheingargument'?",
    answers: ["Scheinbar überzeugendes, aber fehlerhaftes Argument", "Besonders starkes Argument", "Argument mit vielen Belegen", "Neutrales Argument"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Scheingargumente wirken überzeugend, halten einer Prüfung aber nicht stand."
  },
  {
    id: "q10_d_063",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie sollte man in einer Erörterung mit Gegenargumenten umgehen?",
    answers: ["Sie nennen und widerlegen oder relativieren", "Sie komplett verschweigen", "Sie als eigene Meinung übernehmen", "Sie nur emotional ablehnen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Auseinandersetzung mit Gegenargumenten stärkt die eigene Position."
  },
  {
    id: "q10_d_064",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist der Zweck eines Beispiels in der Argumentation?",
    answers: ["Veranschaulichung und Stützung der Behauptung", "Ersatz für jede Begründung", "Ablenkung vom Thema", "Nur stilistische Ausschmückung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele machen abstrakte Argumente greifbar und nachvollziehbar."
  },
  {
    id: "q10_d_065",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Textsorte gehört zu den argumentierenden Texten?",
    answers: ["Kommentar und Erörterung", "Märchen und Fabel", "Gedicht und Ballade", "Beschreibung und Bericht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kommentar und Erörterung vertreten und begründen eine Position."
  },
  {
    id: "q10_d_066",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'These' in der Argumentation?",
    answers: ["Zu begründende Behauptung", "Bereits bewiesene Tatsache", "Reines Beispiel", "Gegenposition"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die These ist die Ausgangsbehauptung, die argumentativ gestützt wird."
  },
  {
    id: "q10_d_067",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die abschließende Zusammenführung von These und Antithese?",
    answers: ["Synthese", "Exposition", "Klimax", "Peripetie"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Synthese verbindet oder überwindet die Gegensätze zu einem Ergebnis."
  },
  {
    id: "q10_d_068",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist bei einer textgebundenen Erörterung besonders wichtig?",
    answers: ["Bezug auf den vorgegebenen Text und seine Argumente", "Vollständiger Verzicht auf den Text", "Nur eigene Meinung ohne Textbezug", "Abschreiben des Textes"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die textgebundene Erörterung setzt sich mit dem Ausgangstext auseinander."
  },
  {
    id: "q10_d_069",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Rolle spielt die Leserlenkung in argumentativen Texten?",
    answers: ["Steuerung der Aufmerksamkeit und Überzeugung", "Reine Unterhaltung", "Nur stilistische Spielerei", "Vermeidung von Argumenten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Durch Aufbau, Sprache und Beispiele wird der Leser gelenkt."
  },
  {
    id: "q10_d_070",
    category: "k10_deutsch",
    topic: "argumentation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was kennzeichnet eine gelungene Argumentationsstruktur?",
    answers: ["Klare Gliederung mit nachvollziehbaren Begründungen", "Zufällige Reihenfolge der Gedanken", "Nur emotionale Appelle", "Wiederholung derselben Behauptung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Logischer Aufbau und stichhaltige Begründungen machen Argumentation überzeugend."
  },

  // ================================================================
  // 5. SPRACHE, GRAMMATIK & SPRACHWANDEL (15 Fragen)
  // ================================================================
  {
    id: "q10_d_071",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Sprachvarietät'?",
    answers: ["Unterschiedliche Ausprägungen einer Sprache", "Nur die Standardsprache", "Eine tote Sprache", "Ein einzelnes Wort"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Dialekte, Soziolekte und Fachsprachen sind Sprachvarietäten."
  },
  {
    id: "q10_d_072",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein Anglizismus?",
    answers: ["Übernahme eines englischen Ausdrucks ins Deutsche", "Altdeutsches Wort", "Lateinisches Lehnwort", "Rein deutsches Kunstwort"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Anglizismen sind Entlehnungen aus dem Englischen (z. B. 'Computer')."
  },
  {
    id: "q10_d_073",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Aussage trifft auf Sprachwandel zu?",
    answers: ["Sprache verändert sich ständig durch Gebrauch", "Sprache bleibt für immer gleich", "Nur Grammatik ändert sich nie", "Nur Fremdwörter ändern sich"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sprachwandel betrifft Wortschatz, Bedeutung und teilweise auch Grammatik."
  },
  {
    id: "q10_d_074",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist der Unterschied zwischen Standard- und Umgangssprache?",
    answers: ["Standardsprache folgt festeren Normen", "Umgangssprache ist immer fehlerhaft", "Standardsprache wird nie gesprochen", "Es gibt keinen Unterschied"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Standardsprache orientiert sich an kodifizierten Regeln, die Umgangssprache ist freier."
  },
  {
    id: "q10_d_075",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Pragmatik' in der Sprachwissenschaft?",
    answers: ["Lehre vom sprachlichen Handeln und der Wirkung", "Reine Lautlehre", "Wortbildungslehre", "Satzbauregeln"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Die Pragmatik untersucht, wie Sprache in Situationen wirkt und verwendet wird."
  },
  {
    id: "q10_d_076",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Wortart verändert sich in der Konjugation?",
    answers: ["Verb", "Nomen", "Adjektiv", "Adverb"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verben werden nach Person, Numerus, Tempus und Modus konjugiert."
  },
  {
    id: "q10_d_077",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'Partizip'?",
    answers: ["Mittelwort zwischen Verb und Adjektiv", "Reine Konjunktion", "Nur ein Nomen", "Ein Fragewort"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Partizip I und II können verbal und adjektivisch gebraucht werden."
  },
  {
    id: "q10_d_078",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man Wörter, die aus einer anderen Sprache übernommen wurden?",
    answers: ["Lehnwörter oder Fremdwörter", "Neologismen ohne Herkunft", "Nur Dialektwörter", "Nur Fachbegriffe"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fremd- und Lehnwörter stammen aus anderen Sprachen."
  },
  {
    id: "q10_d_079",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was kennzeichnet einen 'Neologismus'?",
    answers: ["Neu gebildetes oder neu gebrauchtes Wort", "Sehr altes Wort", "Nur Dialektausdruck", "Fehlerhafte Bildung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Neologismen entstehen durch neue Bedürfnisse oder Mode."
  },
  {
    id: "q10_d_080",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Funktion hat der Konjunktiv häufig in der indirekten Rede?",
    answers: ["Kennzeichnung der wiedergegebenen Aussage", "Nur Höflichkeitsform", "Nur Bedingungssatz", "Nur Wunschsatz"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Konjunktiv markiert in der indirekten Rede die Fremdheit der Aussage."
  },
  {
    id: "q10_d_081",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'Homonym'?",
    answers: ["Gleich lautendes Wort mit unterschiedlicher Bedeutung", "Wort mit gleicher Bedeutung", "Zusammengesetztes Wort", "Veraltetes Wort"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Homonyme klingen gleich, bedeuten aber Verschiedenes (z. B. 'Bank')."
  },
  {
    id: "q10_d_082",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Ebene der Sprache untersucht die Syntax?",
    answers: ["Satzbau und Satzstruktur", "Lautstruktur", "Wortbedeutung", "Textwirkung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Syntax beschäftigt sich mit der Verknüpfung von Wörtern zu Sätzen."
  },
  {
    id: "q10_d_083",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Bildungssprache'?",
    answers: ["Sprachform, die in Schule und Wissenschaft gefordert wird", "Nur Umgangssprache", "Nur Dialekt", "Nur Fachjargon"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bildungssprache ist die abstraktere, präzisere Variante der Standardsprache."
  },
  {
    id: "q10_d_084",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Wie nennt man die Lehre von der Bedeutung der Wörter?",
    answers: ["Semantik", "Phonetik", "Morphologie", "Syntax"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Semantik untersucht Wort- und Satzbedeutungen."
  },
  {
    id: "q10_d_085",
    category: "k10_deutsch",
    topic: "sprache",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'Euphemismus'?",
    answers: ["Beschönigende Umschreibung", "Derbe Ausdrucksweise", "Fachbegriff", "Dialektwort"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Euphemismen mildern unangenehme Sachverhalte ab (z. B. 'entschlafen')."
  },

  // ================================================================
  // 6. KOMMUNIKATION & MEDIEN (15 Fragen)
  // ================================================================
  {
    id: "q10_d_086",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was beschreibt das Kommunikationsmodell von Schulz von Thun mit vier Seiten?",
    answers: ["Sache, Beziehung, Appell und Selbstoffenbarung", "Nur Sender und Empfänger", "Nur Inhalt und Form", "Nur verbale und nonverbale Zeichen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Jede Nachricht hat nach Schulz von Thun vier Aspekte."
  },
  {
    id: "q10_d_087",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'nonverbaler Kommunikation'?",
    answers: ["Kommunikation durch Gestik, Mimik und Körperhaltung", "Nur geschriebene Sprache", "Nur gesprochene Wörter", "Nur digitale Nachrichten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nonverbale Signale begleiten oder ersetzen die verbale Kommunikation."
  },
  {
    id: "q10_d_088",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Rolle spielt der 'Kanal' im Kommunikationsprozess?",
    answers: ["Übertragungsweg der Nachricht", "Nur der Inhalt", "Nur der Empfänger", "Nur die Absicht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Kanal ist das Medium, über das die Nachricht transportiert wird."
  },
  {
    id: "q10_d_089",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist 'Feedback' in der Kommunikation?",
    answers: ["Rückmeldung des Empfängers an den Sender", "Nur die erste Nachricht", "Störung im Kanal", "Absicht des Senders"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Feedback zeigt, wie die Nachricht angekommen ist und wirkt."
  },
  {
    id: "q10_d_090",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was kennzeichnet multimodale Texte?",
    answers: ["Verbindung von Text, Bild, Ton oder anderen Elementen", "Nur reine Schriftsprache", "Nur gesprochene Sprache", "Nur Bilder ohne Text"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Multimodale Texte nutzen mehrere Zeichensysteme gleichzeitig."
  },
  {
    id: "q10_d_091",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Gefahr besteht bei der Kommunikation in sozialen Medien besonders?",
    answers: ["Missverständnisse durch fehlende nonverbale Signale", "Zu viel Körpersprache", "Zu langsame Übertragung", "Zu klare Botschaften"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ohne Mimik und Gestik können Töne und Absichten leicht fehlinterpretiert werden."
  },
  {
    id: "q10_d_092",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was versteht man unter 'Medienkompetenz'?",
    answers: ["Fähigkeit, Medien kritisch zu nutzen und zu reflektieren", "Nur technisches Bedienen", "Nur Konsum von Medien", "Verzicht auf alle Medien"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Medienkompetenz umfasst Nutzung, Analyse und kritische Bewertung."
  },
  {
    id: "q10_d_093",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Funktion hat ein 'Sender' im Kommunikationsmodell?",
    answers: ["Erzeugt und übermittelt die Nachricht", "Empfängt nur die Nachricht", "Stört die Übertragung", "Speichert die Nachricht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Sender initiiert die Kommunikation durch eine Nachricht."
  },
  {
    id: "q10_d_094",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist ein 'Appell' nach dem Vier-Seiten-Modell?",
    answers: ["Aufforderung an den Empfänger zu einem Verhalten", "Reine Sachinformation", "Selbstaussage des Senders", "Beziehungshinweis"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Appell zielt darauf ab, den Empfänger zu etwas zu bewegen."
  },
  {
    id: "q10_d_095",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Textsorte dient vor allem der Information in den Medien?",
    answers: ["Nachricht und Reportage", "Kommentar und Glosse", "Werbespot", "Satire"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachrichten und Reportagen berichten vorrangig über Ereignisse."
  },
  {
    id: "q10_d_096",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was kennzeichnet eine 'Glosse'?",
    answers: ["Kurzer, oft ironischer Meinungsbeitrag", "Rein objektive Nachricht", "Langer Roman", "Gedicht"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Glosse kommentiert aktuelle Ereignisse pointiert und subjektiv."
  },
  {
    id: "q10_d_097",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Rolle spielt der 'Kontext' für das Verstehen einer Nachricht?",
    answers: ["Er beeinflusst die Deutung maßgeblich", "Er ist völlig irrelevant", "Er ersetzt den Inhalt", "Er stört nur"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ohne Kontext können dieselben Worte ganz anders verstanden werden."
  },
  {
    id: "q10_d_098",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was ist 'digitale Kommunikation' besonders geprägt von?",
    answers: ["Schnelligkeit und oft fehlender Unmittelbarkeit", "Nur langsamer Schriftverkehr", "Ausschließlich persönlicher Begegnung", "Verzicht auf Schrift"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Digitale Medien ermöglichen rasche, aber oft entpersonalisierte Kommunikation."
  },
  {
    id: "q10_d_099",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Welche Fähigkeit gehört zur kritischen Mediennutzung?",
    answers: ["Quellen prüfen und Absichten erkennen", "Alles ungeprüft weiterleiten", "Nur unterhalten lassen", "Medien komplett meiden"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kritische Nutzung bedeutet, Herkunft, Interesse und Wirkung zu hinterfragen."
  },
  {
    id: "q10_d_100",
    category: "k10_deutsch",
    topic: "kommunikation",
    area: "schule",
    grade: 10,
    subject: "deutsch",
    question: "Was beschreibt der Begriff 'Medienkonvergenz'?",
    answers: ["Verschmelzung verschiedener Medienformen", "Strikte Trennung aller Medien", "Nur Printmedien", "Nur Fernsehen"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Medienkonvergenz meint das Zusammenwachsen von Text, Bild, Ton und interaktiven Formaten."
  }
];
