const K10_BIOLOGIE_QUESTIONS = [
  // ================================================================
  // 1. ZELLE & ZELLBIOLOGIE (20 Fragen)
  // ================================================================
  {
    id: "q10_b_001",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die kleinste selbstständig lebensfähige Einheit eines Organismus?",
    answers: ["Die Zelle", "Das Organ", "Das Gewebe", "Der Organismus"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zelle ist die Grundeinheit des Lebens."
  },
  {
    id: "q10_b_002",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welches Zellorganell enthält die Erbinformation?",
    answers: ["Zellkern (Nucleus)", "Mitochondrium", "Ribosom", "Zellmembran"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Zellkern liegt die DNA in Form von Chromosomen vor."
  },
  {
    id: "q10_b_003",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Aufgabe haben die Mitochondrien?",
    answers: ["Energiegewinnung (Zellatmung)", "Photosynthese", "Eiweißsynthese", "Speicherung von Wasser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mitochondrien produzieren ATP durch Zellatmung."
  },
  {
    id: "q10_b_004",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen tierischen und pflanzlichen Zellen?",
    answers: ["Pflanzenzellen besitzen Zellwand und Chloroplasten", "Tierzellen haben immer Chloroplasten", "Pflanzenzellen haben keinen Zellkern", "Es gibt keinen Unterschied"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zellwand und Chloroplasten sind typisch für Pflanzenzellen."
  },
  {
    id: "q10_b_005",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Aufgabe hat die Zellmembran?",
    answers: ["Stoffaustausch und Abgrenzung der Zelle", "Photosynthese", "Energiegewinnung", "Speicherung der DNA"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Membran reguliert den Stoffdurchtritt."
  },
  {
    id: "q10_b_006",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Wo findet die Photosynthese in der Pflanzenzelle statt?",
    answers: ["In den Chloroplasten", "In den Mitochondrien", "Im Zellkern", "In den Ribosomen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Chloroplasten enthalten Chlorophyll und betreiben Photosynthese."
  },
  {
    id: "q10_b_007",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Ribosomen?",
    answers: ["Eiweißsynthese (Proteinbiosynthese)", "Energiegewinnung", "Photosynthese", "Stofftransport"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ribosomen übersetzen mRNA in Proteine."
  },
  {
    id: "q10_b_008",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was versteht man unter Diffusion?",
    answers: ["Ausgleich von Konzentrationsunterschieden ohne Energieaufwand", "Aktiver Transport gegen das Konzentrationsgefälle", "Nur Wasseraufnahme", "Nur Gasaustausch in der Lunge"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Diffusion ist passiver Stofftransport."
  },
  {
    id: "q10_b_009",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Osmose?",
    answers: ["Diffusion von Wasser durch eine semipermeable Membran", "Aktiver Ionentransport", "Photosynthese", "Zellteilung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Osmose ist die Wasserbewegung entlang des Konzentrationsgefälles."
  },
  {
    id: "q10_b_010",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Zellen besitzen keinen echten Zellkern?",
    answers: ["Bakterienzellen (Prokaryoten)", "Tierzellen", "Pflanzenzellen", "Pilzzellen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Prokaryoten haben kein abgetrenntes Kernkompartiment."
  },
  {
    id: "q10_b_011",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Zellplasmas (Cytoplasma)?",
    answers: ["Ort vieler Stoffwechselvorgänge und Transportmedium", "Nur Speicherung der DNA", "Nur Photosynthese", "Nur Energiegewinnung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Cytoplasma laufen zahlreiche Reaktionen ab."
  },
  {
    id: "q10_b_012",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind Chromosomen?",
    answers: ["Strukturen aus DNA und Proteinen, die die Erbinformation tragen", "Nur Zellorganellen für Energie", "Nur Membranbestandteile", "Nur Enzyme"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Chromosomen enthalten die Gene."
  },
  {
    id: "q10_b_013",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Phase der Mitose folgt auf die Prophase?",
    answers: ["Metaphase", "Anaphase", "Telophase", "Interphase"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Reihenfolge: Prophase – Metaphase – Anaphase – Telophase."
  },
  {
    id: "q10_b_014",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was geschieht in der Anaphase der Mitose?",
    answers: ["Die Schwesterchromatiden werden zu den Polen gezogen", "Die Chromosomen ordnen sich in der Äquatorialebene", "Der Zellkern löst sich auf", "Die Zellmembran schnürt sich durch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Anaphase = Trennung der Chromatiden."
  },
  {
    id: "q10_b_015",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Mitose und Meiose?",
    answers: ["Mitose erzeugt diploide Körperzellen, Meiose haploide Keimzellen", "Beide erzeugen immer haploide Zellen", "Beide erzeugen immer diploide Zellen", "Es gibt keinen Unterschied"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Meiose halbiert den Chromosomensatz."
  },
  {
    id: "q10_b_016",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ATP?",
    answers: ["Der universelle Energieträger der Zelle", "Ein Baustein der DNA", "Ein Hormon", "Ein Vitamin"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "ATP speichert und überträgt Energie."
  },
  {
    id: "q10_b_017",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Reaktion beschreibt die Photosynthese vereinfacht?",
    answers: ["CO₂ + H₂O + Licht → Zucker + O₂", "Zucker + O₂ → CO₂ + H₂O + Energie", "Nur CO₂ → O₂", "Nur Wasser → Sauerstoff"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Pflanzen bauen mit Licht aus CO₂ und Wasser Zucker auf und setzen O₂ frei."
  },
  {
    id: "q10_b_018",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Reaktion beschreibt die Zellatmung vereinfacht?",
    answers: ["Zucker + O₂ → CO₂ + H₂O + Energie (ATP)", "CO₂ + H₂O + Licht → Zucker + O₂", "Nur O₂ → CO₂", "Nur Zucker → Energie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zellatmung setzt die in Zucker gespeicherte Energie frei."
  },
  {
    id: "q10_b_019",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Enzym?",
    answers: ["Ein Biokatalysator, der Reaktionen beschleunigt", "Ein Energieträger", "Ein Baustein der Zellwand", "Ein Hormon"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Enzyme senken die Aktivierungsenergie."
  },
  {
    id: "q10_b_020",
    category: "k10_biologie",
    topic: "zelle",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet 'semipermeabel'?",
    answers: ["Teildurchlässig für bestimmte Stoffe", "Vollständig undurchlässig", "Für alle Stoffe durchlässig", "Nur für Gase durchlässig"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zellmembran ist selektiv permeabel."
  },

  // ================================================================
  // 2. GENETIK (30 Fragen)
  // ================================================================
  {
    id: "q10_b_021",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Gen?",
    answers: ["Ein Abschnitt der DNA, der für ein Merkmal codiert", "Ein ganzes Chromosom", "Ein Zellorganell", "Ein Hormon"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gene sind die Erbeinheiten."
  },
  {
    id: "q10_b_022",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet diploid?",
    answers: ["Doppelter Chromosomensatz (2n)", "Einfacher Chromosomensatz (n)", "Dreifacher Chromosomensatz", "Kein Chromosomensatz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Körperzellen sind diploid."
  },
  {
    id: "q10_b_023",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet haploid?",
    answers: ["Einfacher Chromosomensatz (n)", "Doppelter Chromosomensatz", "Vierfacher Chromosomensatz", "Kein Chromosomensatz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Keimzellen sind haploid."
  },
  {
    id: "q10_b_024",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Allel?",
    answers: ["Eine Variante eines Gens", "Ein ganzes Chromosom", "Ein Protein", "Ein Enzym"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Allele sind unterschiedliche Ausprägungen desselben Gens."
  },
  {
    id: "q10_b_025",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet dominant?",
    answers: ["Das Allel setzt sich im Phänotyp durch", "Das Allel wird nie ausgeprägt", "Das Allel ist immer rezessiv", "Das Allel liegt nur auf dem Y-Chromosom"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Dominante Allele überdecken rezessive."
  },
  {
    id: "q10_b_026",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet rezessiv?",
    answers: ["Das Allel wird nur ausgeprägt, wenn kein dominantes vorhanden ist", "Das Allel setzt sich immer durch", "Das Allel ist immer dominant", "Das Allel liegt nur auf dem X-Chromosom"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rezessive Merkmale erscheinen nur im homozygoten Zustand."
  },
  {
    id: "q10_b_027",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Genotyp?",
    answers: ["Die genetische Ausstattung eines Individuums", "Das äußere Erscheinungsbild", "Nur die Umweltfaktoren", "Nur die Chromosomenzahl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Genotyp = Allelkombination."
  },
  {
    id: "q10_b_028",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Phänotyp?",
    answers: ["Das äußere Erscheinungsbild", "Nur die DNA-Sequenz", "Nur die Chromosomenzahl", "Nur die Umwelt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Phänotyp = sichtbare Merkmale."
  },
  {
    id: "q10_b_029",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was besagt die 1. Mendel-Regel (Uniformitätsregel)?",
    answers: ["Kreuzung reinerbiger Eltern ergibt einheitliche Nachkommen", "Die Merkmale spalten im Verhältnis 3:1 auf", "Alle Merkmale werden unabhängig vererbt", "Nur dominante Merkmale werden vererbt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "F1-Generation ist uniform."
  },
  {
    id: "q10_b_030",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was besagt die 2. Mendel-Regel (Spaltungsregel)?",
    answers: ["In der F2-Generation spalten die Merkmale im Verhältnis 3:1 auf", "Alle Nachkommen sind gleich", "Es gibt keine Aufspaltung", "Nur rezessive Merkmale erscheinen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei monohybridem Erbgang: 3 dominant : 1 rezessiv."
  },
  {
    id: "q10_b_031",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist DNA?",
    answers: ["Desoxyribonukleinsäure – Träger der Erbinformation", "Ein Protein", "Ein Zucker", "Ein Hormon"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "DNA speichert die genetische Information."
  },
  {
    id: "q10_b_032",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Basen paaren in der DNA?",
    answers: ["Adenin mit Thymin, Guanin mit Cytosin", "Adenin mit Guanin, Thymin mit Cytosin", "Adenin mit Cytosin, Guanin mit Thymin", "Alle Basen paarweise beliebig"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Komplementäre Basenpaarung: A-T, G-C."
  },
  {
    id: "q10_b_033",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Mutation?",
    answers: ["Eine bleibende Veränderung der genetischen Information", "Nur eine vorübergehende Veränderung", "Nur eine Anpassung an die Umwelt", "Nur eine Zellteilung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mutationen verändern die DNA dauerhaft."
  },
  {
    id: "q10_b_034",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein homozygoter Genotyp?",
    answers: ["Beide Allele eines Gens sind gleich", "Beide Allele sind unterschiedlich", "Nur ein Allel ist vorhanden", "Keine Allele sind vorhanden"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Homozygot = reinerbig (AA oder aa)."
  },
  {
    id: "q10_b_035",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein heterozygoter Genotyp?",
    answers: ["Beide Allele eines Gens sind unterschiedlich", "Beide Allele sind gleich", "Nur ein Allel ist vorhanden", "Keine Allele sind vorhanden"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Heterozygot = mischerbig (Aa)."
  },
  {
    id: "q10_b_036",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Wie viele Chromosomen hat der Mensch in einer Körperzelle?",
    answers: ["46 (23 Paare)", "23", "92", "22"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "46 Chromosomen = 23 homologe Paare."
  },
  {
    id: "q10_b_037",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der mRNA?",
    answers: ["Übertragung der genetischen Information vom Kern zu den Ribosomen", "Speicherung der Erbinformation", "Energiegewinnung", "Photosynthese"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "mRNA ist die Boten-RNA."
  },
  {
    id: "q10_b_038",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Karyogramm?",
    answers: ["Die geordnete Darstellung aller Chromosomen einer Zelle", "Ein Stammbaum", "Ein Enzymschema", "Eine Nahrungskette"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Im Karyogramm werden Chromosomen nach Größe und Form sortiert."
  },
  {
    id: "q10_b_039",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was besagt die 3. Mendel-Regel (Unabhängigkeitsregel)?",
    answers: ["Verschiedene Gene werden unabhängig voneinander vererbt", "Alle Gene sind immer gekoppelt", "Nur dominante Gene werden vererbt", "Rezessive Gene verschwinden"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bei dihybridem Erbgang spalten die Merkmale unabhängig auf."
  },
  {
    id: "q10_b_040",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Doppelhelix?",
    answers: ["Die räumliche Struktur der DNA", "Ein Protein", "Ein Chromosomensatz", "Ein Enzym"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "DNA besteht aus zwei komplementären Strängen in Schraubenform."
  },
  {
    id: "q10_b_041",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein X-chromosomaler Erbgang?",
    answers: ["Das Gen liegt auf dem X-Chromosom", "Das Gen liegt auf dem Y-Chromosom", "Das Gen liegt auf einem Autosom", "Das Gen liegt nicht auf einem Chromosom"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Geschlechtsgebundene Vererbung über das X-Chromosom."
  },
  {
    id: "q10_b_042",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der tRNA?",
    answers: ["Transport von Aminosäuren zu den Ribosomen", "Speicherung der DNA", "Photosynthese", "Energiegewinnung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "tRNA bringt die passenden Aminosäuren."
  },
  {
    id: "q10_b_043",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Codon?",
    answers: ["Ein Triplett von Basen, das eine Aminosäure codiert", "Ein ganzes Gen", "Ein Chromosom", "Ein Protein"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Drei Basen bilden ein Codon."
  },
  {
    id: "q10_b_044",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was geschieht bei der Replikation der DNA?",
    answers: ["Die DNA wird verdoppelt", "Die DNA wird abgebaut", "Die DNA wird in RNA umgeschrieben", "Die DNA wird in Protein übersetzt"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Replikation sichert die Weitergabe der Erbinformation."
  },
  {
    id: "q10_b_045",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Transcription?",
    answers: ["Umschreibung der DNA-Information in mRNA", "Übersetzung der mRNA in Protein", "Verdopplung der DNA", "Abbau der RNA"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Transcription = DNA → mRNA."
  },
  {
    id: "q10_b_046",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Translation?",
    answers: ["Übersetzung der mRNA-Sequenz in eine Aminosäurekette", "Umschreibung der DNA in mRNA", "Verdopplung der DNA", "Zellteilung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Translation = Proteinbiosynthese an den Ribosomen."
  },
  {
    id: "q10_b_047",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Autosom?",
    answers: ["Ein Chromosom, das nicht an der Geschlechtsbestimmung beteiligt ist", "Ein Geschlechtschromosom", "Ein Gen", "Ein Protein"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Mensch hat 22 Autosomenpaare und ein Geschlechtschromosomenpaar."
  },
  {
    id: "q10_b_048",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Gen und Allel?",
    answers: ["Ein Gen ist der Ort, Allele sind die Varianten dieses Gens", "Es gibt keinen Unterschied", "Allele sind immer dominant", "Gene sind immer rezessiv"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Gen = Locus, Allele = alternative Formen."
  },
  {
    id: "q10_b_049",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Punnett-Quadrat?",
    answers: ["Ein Schema zur Vorhersage von Genotypen bei Kreuzungen", "Ein Chromosomenbild", "Ein Stammbaum", "Ein Enzymmodell"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mit dem Punnett-Quadrat lassen sich Mendel-Kreuzungen darstellen."
  },
  {
    id: "q10_b_050",
    category: "k10_biologie",
    topic: "genetik",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was bedeutet intermedärer Erbgang?",
    answers: ["Beide Allele beeinflussen den Phänotyp gemeinsam (Mischform)", "Nur das dominante Allel wirkt", "Nur das rezessive Allel wirkt", "Es gibt keine Vererbung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Beispiel: rote und weiße Blüten → rosa Nachkommen."
  },

  // ================================================================
  // 3. EVOLUTION (20 Fragen)
  // ================================================================
  {
    id: "q10_b_051",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Evolution?",
    answers: ["Die Veränderung von Lebewesen über Generationen hinweg", "Nur die Entwicklung eines Einzelwesens", "Nur die Anpassung innerhalb einer Generation", "Nur die Zellteilung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Evolution beschreibt die stammesgeschichtliche Entwicklung."
  },
  {
    id: "q10_b_052",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Wer formulierte die Evolutionstheorie durch natürliche Selektion?",
    answers: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Robert Koch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Darwin veröffentlichte 1859 'On the Origin of Species'."
  },
  {
    id: "q10_b_053",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist natürliche Selektion?",
    answers: ["Bevorzugte Fortpflanzung der besser angepassten Individuen", "Zufällige Veränderung der DNA", "Nur künstliche Züchtung", "Nur Mutation"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Selektion wirkt auf vorhandene Variation."
  },
  {
    id: "q10_b_054",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Anpassung (Adaptation)?",
    answers: ["Ein Merkmal, das die Überlebens- und Fortpflanzungschancen erhöht", "Nur eine Mutation", "Nur eine Umweltveränderung", "Nur ein Verhalten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Anpassungen entstehen durch Selektion."
  },
  {
    id: "q10_b_055",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind homologe Organe?",
    answers: ["Organe mit gleicher Herkunft, aber möglicherweise unterschiedlicher Funktion", "Organe mit gleicher Funktion, aber unterschiedlicher Herkunft", "Nur funktionslose Organe", "Nur Organe gleicher Form"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Homologie deutet auf gemeinsame Abstammung hin."
  },
  {
    id: "q10_b_056",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind analoge Organe?",
    answers: ["Organe mit ähnlicher Funktion, aber unterschiedlicher Herkunft", "Organe mit gleicher Herkunft", "Nur rudimentäre Organe", "Nur Organe gleicher Struktur"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Analogie entsteht durch konvergente Evolution."
  },
  {
    id: "q10_b_057",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind rudimentäre Organe?",
    answers: ["Zurückgebildete Organe, die ihre ursprüngliche Funktion verloren haben", "Besonders wichtige Organe", "Neu entstandene Organe", "Nur Sinnesorgane"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beispiel: Weisheitszähne oder Steißbein beim Menschen."
  },
  {
    id: "q10_b_058",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Artbildung (Speziation)?",
    answers: ["Die Entstehung neuer Arten aus bestehenden Populationen", "Nur die Veränderung innerhalb einer Art", "Nur Mutation", "Nur Selektion"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Artbildung kann z. B. durch geografische Isolation erfolgen."
  },
  {
    id: "q10_b_059",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Genpool?",
    answers: ["Die Gesamtheit aller Allele in einer Population", "Nur die DNA einer Zelle", "Nur die Chromosomen eines Individuums", "Nur die dominanten Allele"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Genpool ist die genetische Vielfalt einer Population."
  },
  {
    id: "q10_b_060",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Fitness in der Evolutionsbiologie?",
    answers: ["Der Fortpflanzungserfolg eines Individuums", "Nur die körperliche Leistungsfähigkeit", "Nur die Größe", "Nur die Intelligenz"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Fitness misst den Beitrag zum Genpool der nächsten Generation."
  },
  {
    id: "q10_b_061",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist konvergente Evolution?",
    answers: ["Unabhängige Entwicklung ähnlicher Merkmale bei nicht verwandten Arten", "Entwicklung aus einem gemeinsamen Vorfahren", "Nur Mutation", "Nur Selektion"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Beispiel: Flügel von Insekten und Vögeln."
  },
  {
    id: "q10_b_062",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Fossil?",
    answers: ["Ein erhaltener Rest oder Abdruck eines Lebewesens aus früherer Zeit", "Ein lebendes Tier", "Ein Mineral", "Ein Enzym"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossilien belegen die Evolution."
  },
  {
    id: "q10_b_063",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Stammbaum der Lebewesen?",
    answers: ["Eine Darstellung der verwandtschaftlichen Beziehungen", "Nur eine Liste von Arten", "Nur ein Chromosomensatz", "Nur ein Karyogramm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Stammbäume zeigen gemeinsame Vorfahren."
  },
  {
    id: "q10_b_064",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Selektionsdruck?",
    answers: ["Der Einfluss der Umweltfaktoren auf die Überlebenschancen", "Nur die Mutationrate", "Nur die Chromosomenzahl", "Nur die Temperatur"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Selektionsdruck führt zu Anpassung."
  },
  {
    id: "q10_b_065",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Isolation in der Evolution?",
    answers: ["Trennung von Populationen, die den Genaustausch verhindert", "Nur geografische Entfernung", "Nur Mutation", "Nur Selektion"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Isolation ist Voraussetzung für Artbildung."
  },
  {
    id: "q10_b_066",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Mikro- und Makroevolution?",
    answers: ["Mikroevolution = Veränderungen innerhalb einer Art, Makroevolution = Entstehung neuer Arten und höherer Taxa", "Es gibt keinen Unterschied", "Mikroevolution ist immer schneller", "Makroevolution betrifft nur Bakterien"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Die Begriffe beschreiben unterschiedliche Zeitskalen und Ebenen."
  },
  {
    id: "q10_b_067",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein lebendes Fossil?",
    answers: ["Eine Art, die sich über sehr lange Zeit kaum verändert hat", "Ein ausgestorbenes Tier", "Ein Fossil, das noch lebt", "Ein neu entstandenes Tier"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beispiel: Quastenflosser oder Ginkgo."
  },
  {
    id: "q10_b_068",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der genetische Drift?",
    answers: ["Zufällige Veränderung der Allelfrequenzen in kleinen Populationen", "Nur natürliche Selektion", "Nur Mutation", "Nur Anpassung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Genetische Drift ist besonders in kleinen Populationen wirksam."
  },
  {
    id: "q10_b_069",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der gemeinsame Vorfahre?",
    answers: ["Eine Art, aus der sich mehrere heutige Arten entwickelt haben", "Nur das älteste Fossil", "Nur eine Mutation", "Nur ein Individuum"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gemeinsame Vorfahren begründen Verwandtschaft."
  },
  {
    id: "q10_b_070",
    category: "k10_biologie",
    topic: "evolution",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Beweiswert von Fossilien für die Evolution?",
    answers: ["Sie zeigen die Veränderung von Lebensformen über geologische Zeiträume", "Sie beweisen nur die Existenz von Tieren", "Sie haben keinen Beweiswert", "Sie zeigen nur die Umwelt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossilreihen belegen Übergangsformen."
  },

  // ================================================================
  // 4. ÖKOLOGIE (30 Fragen)
  // ================================================================
  {
    id: "q10_b_071",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Ökosystem?",
    answers: ["Die Gesamtheit aus Lebensgemeinschaft und Lebensraum", "Nur die Tiere eines Gebiets", "Nur die Pflanzen eines Gebiets", "Nur der Boden"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ökosystem = Biozönose + Biotop."
  },
  {
    id: "q10_b_072",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Produzent?",
    answers: ["Ein Lebewesen, das organische Stoffe aus anorganischen aufbaut (z. B. Pflanzen)", "Ein Fleischfresser", "Ein Zersetzer", "Ein Allesfresser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Produzenten betreiben Photosynthese."
  },
  {
    id: "q10_b_073",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Konsument?",
    answers: ["Ein Lebewesen, das organische Stoffe aufnimmt (Tiere)", "Ein Produzent", "Nur Bakterien", "Nur Pflanzen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Konsumenten ernähren sich von anderen Organismen."
  },
  {
    id: "q10_b_074",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Destruent (Zersetzer)?",
    answers: ["Ein Lebewesen, das tote organische Substanz abbaut", "Ein Produzent", "Ein Primärkonsument", "Ein Endverbraucher"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bakterien und Pilze sind wichtige Destruenten."
  },
  {
    id: "q10_b_075",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Nahrungskette?",
    answers: ["Eine Abfolge von Fressbeziehungen", "Nur die Pflanzen eines Ökosystems", "Nur die Tiere eines Ökosystems", "Nur der Stoffkreislauf"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nahrungsketten zeigen den Energiefluss."
  },
  {
    id: "q10_b_076",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Nahrungsnetz?",
    answers: ["Die vernetzten Nahrungsbeziehungen in einem Ökosystem", "Nur eine lineare Kette", "Nur die Produzenten", "Nur die Destruenten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nahrungsnetze sind komplexer als einzelne Ketten."
  },
  {
    id: "q10_b_077",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die ökologische Nische?",
    answers: ["Die Gesamtheit der Umweltbeziehungen einer Art", "Nur der Lebensraum", "Nur die Nahrung", "Nur die Temperatur"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Nische beschreibt die Rolle einer Art im Ökosystem."
  },
  {
    id: "q10_b_078",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Konkurrenz?",
    answers: ["Wettbewerb um begrenzte Ressourcen", "Nur Zusammenarbeit", "Nur Räuber-Beute-Beziehung", "Nur Symbiose"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Konkurrenz kann inner- oder zwischenartlich sein."
  },
  {
    id: "q10_b_079",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Symbiose?",
    answers: ["Eine Beziehung, von der beide Partner profitieren", "Nur einseitig vorteilhaft", "Nur schädlich für beide", "Nur Räuber-Beute"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiel: Flechten (Pilz + Alge)."
  },
  {
    id: "q10_b_080",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Parasitismus?",
    answers: ["Eine Beziehung, bei der ein Partner schadet und der andere profitiert", "Eine beidseitig vorteilhafte Beziehung", "Nur Konkurrenz", "Nur Räuber-Beute"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Parasiten leben auf oder in einem Wirt."
  },
  {
    id: "q10_b_081",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Tragfähigkeit eines Ökosystems?",
    answers: ["Die maximale Populationsgröße, die dauerhaft erhalten werden kann", "Nur die Anzahl der Produzenten", "Nur die Temperatur", "Nur die Niederschlagsmenge"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Überschreitung der Tragfähigkeit führt zu Zusammenbrüchen."
  },
  {
    id: "q10_b_082",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Biodiversität?",
    answers: ["Die Vielfalt der Arten, Gene und Ökosysteme", "Nur die Anzahl der Tiere", "Nur die Anzahl der Pflanzen", "Nur die genetische Vielfalt einer Art"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Biodiversität umfasst mehrere Ebenen."
  },
  {
    id: "q10_b_083",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Treibhauseffekt?",
    answers: ["Erwärmung der Atmosphäre durch bestimmte Gase", "Nur die Abkühlung der Erde", "Nur der Ozonabbau", "Nur die Photosynthese"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Natürlicher und anthropogener Treibhauseffekt."
  },
  {
    id: "q10_b_084",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Welche Gase tragen besonders zum Treibhauseffekt bei?",
    answers: ["CO₂, Methan, Wasserdampf", "Nur Sauerstoff", "Nur Stickstoff", "Nur Edelgase"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Treibhausgase halten Wärmestrahlung zurück."
  },
  {
    id: "q10_b_085",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Biozönose und Biotop?",
    answers: ["Biozönose = Lebensgemeinschaft, Biotop = Lebensraum", "Beide bedeuten dasselbe", "Biozönose = Lebensraum, Biotop = Lebensgemeinschaft", "Beide betreffen nur Pflanzen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Zusammen bilden sie das Ökosystem."
  },
  {
    id: "q10_b_086",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein abiotischer Umweltfaktor?",
    answers: ["Ein unbelebter Faktor (Temperatur, Licht, Wasser)", "Ein belebter Faktor (Räuber, Konkurrenten)", "Nur die Nahrung", "Nur die Artgenossen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Abiotisch = nicht lebend."
  },
  {
    id: "q10_b_087",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein biotischer Umweltfaktor?",
    answers: ["Ein belebter Faktor (Räuber, Beute, Konkurrenten)", "Nur Temperatur", "Nur Licht", "Nur Bodenbeschaffenheit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Biotisch = durch andere Lebewesen bedingt."
  },
  {
    id: "q10_b_088",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Energiefluss in einem Ökosystem?",
    answers: ["Die Weitergabe von Energie von Produzenten zu Konsumenten", "Nur der Stoffkreislauf", "Nur die Photosynthese", "Nur die Zellatmung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Energie geht auf jeder Stufe teilweise verloren."
  },
  {
    id: "q10_b_089",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Stoffkreislauf?",
    answers: ["Der wiederholte Weg von Nährstoffen durch das Ökosystem", "Nur der Energiefluss", "Nur die Photosynthese", "Nur die Zellatmung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Stoffe werden im Gegensatz zur Energie recycelt."
  },
  {
    id: "q10_b_090",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Artenschutz?",
    answers: ["Maßnahmen zum Erhalt bedrohter Arten und ihrer Lebensräume", "Nur die Jagd", "Nur die Züchtung", "Nur die Forschung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Artenschutz ist Teil des Naturschutzes."
  },
  {
    id: "q10_b_091",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Indikatororganismus?",
    answers: ["Eine Art, die auf bestimmte Umweltbedingungen hinweist", "Nur ein Produzent", "Nur ein Destruent", "Nur ein Räuber"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Flechten zeigen z. B. Luftqualität an."
  },
  {
    id: "q10_b_092",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Population und Art?",
    answers: ["Population = Gruppe einer Art in einem Gebiet, Art = Gesamtheit aller fortpflanzungsfähigen Individuen", "Beide bedeuten dasselbe", "Population ist größer als Art", "Art ist immer lokal"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Populationen sind räumlich begrenzt."
  },
  {
    id: "q10_b_093",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Sukzession?",
    answers: ["Die zeitliche Abfolge von Lebensgemeinschaften an einem Standort", "Nur die Nahrungskette", "Nur die Konkurrenz", "Nur die Migration"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Sukzession führt oft zu einer Klimaxgesellschaft."
  },
  {
    id: "q10_b_094",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Ozonabbau?",
    answers: ["Die Zerstörung der Ozonschicht durch bestimmte Chemikalien", "Nur der Treibhauseffekt", "Nur die Photosynthese", "Nur die Zellatmung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "FCKW und ähnliche Stoffe schädigen die Ozonschicht."
  },
  {
    id: "q10_b_095",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen erneuerbaren und nicht erneuerbaren Ressourcen?",
    answers: ["Erneuerbare können sich regenerieren, nicht erneuerbare nicht", "Beide sind unerschöpflich", "Beide sind endlich", "Es gibt keinen Unterschied"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fossile Brennstoffe sind nicht erneuerbar."
  },
  {
    id: "q10_b_096",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Schlüsselart (Keystone Species)?",
    answers: ["Eine Art, die überproportional großen Einfluss auf das Ökosystem hat", "Nur die häufigste Art", "Nur die größte Art", "Nur ein Produzent"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Der Verlust einer Schlüsselart kann das System stark verändern."
  },
  {
    id: "q10_b_097",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Räuber und Parasit?",
    answers: ["Räuber tötet die Beute, Parasit lebt länger auf/in dem Wirt", "Beide sind identisch", "Parasiten sind immer größer", "Räuber sind immer kleiner"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Unterschiedliche Strategien der Ausbeutung."
  },
  {
    id: "q10_b_098",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der anthropogene Einfluss auf Ökosysteme?",
    answers: ["Der Einfluss des Menschen", "Nur der Einfluss von Tieren", "Nur der Einfluss von Pflanzen", "Nur der Einfluss des Klimas"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Menschliche Aktivitäten verändern viele Ökosysteme stark."
  },
  {
    id: "q10_b_099",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Habitat und Nische?",
    answers: ["Habitat = Lebensraum, Nische = ökologische Rolle", "Beide bedeuten dasselbe", "Habitat ist die Rolle, Nische der Raum", "Beide betreffen nur Tiere"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Nische ist multidimensional."
  },
  {
    id: "q10_b_100",
    category: "k10_biologie",
    topic: "oekologie",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist nachhaltige Nutzung?",
    answers: ["Nutzung, die die Regenerationsfähigkeit des Systems erhält", "Maximale Ausbeutung", "Nur Schutz ohne Nutzung", "Nur kurzfristige Nutzung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nachhaltigkeit sichert Ressourcen für die Zukunft."
  },

  // ================================================================
  // 5. MENSCH & GESUNDHEIT / NERVENSYSTEM / IMMUN (50 Fragen – Erweiterung)
  // ================================================================
  {
    id: "q10_b_101",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Nervensystems?",
    answers: ["Aufnahme, Weiterleitung und Verarbeitung von Informationen", "Nur die Verdauung", "Nur der Transport von Sauerstoff", "Nur die Abwehr von Krankheitserregern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Nervensystem steuert und koordiniert."
  },
  {
    id: "q10_b_102",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Neuron?",
    answers: ["Eine Nervenzelle", "Ein Muskel", "Ein Blutkörperchen", "Ein Hormon"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Neurone leiten elektrische Signale."
  },
  {
    id: "q10_b_103",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Synapse?",
    answers: ["Die Verbindungsstelle zwischen zwei Nervenzellen", "Ein Zellkern", "Ein Mitochondrium", "Ein Muskel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "An Synapsen wird das Signal chemisch übertragen."
  },
  {
    id: "q10_b_104",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist das zentrale Nervensystem?",
    answers: ["Gehirn und Rückenmark", "Nur die Nerven in den Armen", "Nur die Sinnesorgane", "Nur das vegetative System"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "ZNS = Gehirn + Rückenmark."
  },
  {
    id: "q10_b_105",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist das periphere Nervensystem?",
    answers: ["Die Nerven außerhalb von Gehirn und Rückenmark", "Nur das Gehirn", "Nur das Rückenmark", "Nur die Hormone"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "PNS verbindet ZNS mit dem Körper."
  },
  {
    id: "q10_b_106",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Reflex?",
    answers: ["Eine unwillkürliche, schnelle Reaktion auf einen Reiz", "Eine bewusste Entscheidung", "Nur eine willkürliche Bewegung", "Nur ein Gedanke"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Reflexe laufen über das Rückenmark ab."
  },
  {
    id: "q10_b_107",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Immunsystems?",
    answers: ["Abwehr von Krankheitserregern und fremden Stoffen", "Nur die Verdauung", "Nur der Sauerstofftransport", "Nur die Bewegung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Immunsystem schützt den Körper."
  },
  {
    id: "q10_b_108",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was sind Antikörper?",
    answers: ["Proteine, die gezielt gegen Erreger gerichtet sind", "Nur weiße Blutkörperchen", "Nur rote Blutkörperchen", "Nur Hormone"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Antikörper markieren oder neutralisieren Erreger."
  },
  {
    id: "q10_b_109",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Impfung?",
    answers: ["Die gezielte Aktivierung des Immunsystems gegen einen Erreger", "Nur die Gabe von Antibiotika", "Nur die Behandlung einer Krankheit", "Nur eine Bluttransfusion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Impfungen erzeugen immunologisches Gedächtnis."
  },
  {
    id: "q10_b_110",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen aktiver und passiver Immunisierung?",
    answers: ["Aktiv: Körper bildet selbst Antikörper; Passiv: fertige Antikörper werden gegeben", "Beide sind identisch", "Aktiv ist immer gefährlicher", "Passiv erzeugt immer Gedächtnis"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Aktive Immunisierung führt zu langfristigem Schutz."
  },
  {
    id: "q10_b_111",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der roten Blutkörperchen?",
    answers: ["Sauerstofftransport", "Abwehr von Erregern", "Blutgerinnung", "Nur Nährstofftransport"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Erythrozyten enthalten Hämoglobin."
  },
  {
    id: "q10_b_112",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der weißen Blutkörperchen?",
    answers: ["Abwehr von Krankheitserregern", "Sauerstofftransport", "Nur Blutgerinnung", "Nur Nährstofftransport"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Leukozyten sind Teil des Immunsystems."
  },
  {
    id: "q10_b_113",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Blutplättchen?",
    answers: ["Blutgerinnung", "Sauerstofftransport", "Abwehr von Erregern", "Nur Nährstofftransport"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Thrombozyten helfen bei der Wundheilung."
  },
  {
    id: "q10_b_114",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der große Blutkreislauf?",
    answers: ["Der Weg vom linken Herzen zum Körper und zurück zum rechten Herzen", "Nur der Lungenkreislauf", "Nur der Weg in die Beine", "Nur der Weg zum Gehirn"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Körperkreislauf versorgt die Organe."
  },
  {
    id: "q10_b_115",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der kleine Blutkreislauf?",
    answers: ["Der Weg vom rechten Herzen zur Lunge und zurück zum linken Herzen", "Nur der Körperkreislauf", "Nur der Weg zum Gehirn", "Nur der Weg in die Arme"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Lungenkreislauf dient dem Gasaustausch."
  },
  {
    id: "q10_b_116",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Lunge?",
    answers: ["Gasaustausch (O₂ aufnehmen, CO₂ abgeben)", "Nur die Verdauung", "Nur die Blutbildung", "Nur die Abwehr"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "In den Alveolen findet der Gasaustausch statt."
  },
  {
    id: "q10_b_117",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Herzens?",
    answers: ["Pumpe für den Blutkreislauf", "Nur die Blutbildung", "Nur die Abwehr", "Nur die Verdauung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Herz treibt das Blut an."
  },
  {
    id: "q10_b_118",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Nieren?",
    answers: ["Ausscheidung von Abbauprodukten und Regulation des Wasserhaushalts", "Nur die Verdauung", "Nur die Blutbildung", "Nur die Atmung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nieren filtern das Blut."
  },
  {
    id: "q10_b_119",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Leber?",
    answers: ["Stoffwechselzentrum, Entgiftung und Speicherung", "Nur die Atmung", "Nur die Blutbildung", "Nur die Bewegung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Leber hat viele zentrale Funktionen."
  },
  {
    id: "q10_b_120",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Hormon?",
    answers: ["Ein Botenstoff, der über das Blut wirkt", "Ein Nervensignal", "Ein Enzym der Verdauung", "Ein Antikörper"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hormone steuern viele Körperfunktionen."
  },
  {
    id: "q10_b_121",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen sensiblen und motorischen Nerven?",
    answers: ["Sensibel = zum ZNS, motorisch = vom ZNS zu den Muskeln", "Beide sind identisch", "Sensibel steuert Muskeln, motorisch leitet Sinne", "Beide leiten nur zum Gehirn"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Richtung der Erregungsleitung unterscheidet sie."
  },
  {
    id: "q10_b_122",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Ruhezustand einer Nervenzelle?",
    answers: ["Das Ruhepotenzial (innen negativ gegenüber außen)", "Ein Aktionspotenzial", "Nur die Synapse", "Nur die Erregungsleitung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Im Ruhezustand besteht ein Membranpotenzial."
  },
  {
    id: "q10_b_123",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Aktionspotenzial?",
    answers: ["Eine kurze Umkehrung des Membranpotenzials bei Erregung", "Der Ruhezustand", "Nur die Synapse", "Nur ein Hormon"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Aktionspotenziale leiten Informationen weiter."
  },
  {
    id: "q10_b_124",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Blut-Hirn-Schranke?",
    answers: ["Eine Schutzbarriere zwischen Blut und Gehirn", "Nur eine Nervenzelle", "Nur ein Hormon", "Nur ein Muskel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Sie schützt das Gehirn vor vielen Stoffen."
  },
  {
    id: "q10_b_125",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen angeborener und erworbener Immunität?",
    answers: ["Angeboren = unspezifisch und sofort, erworben = spezifisch und mit Gedächtnis", "Beide sind identisch", "Angeboren ist immer spezifisch", "Erworben ist immer unspezifisch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Systeme arbeiten zusammen."
  },
  {
    id: "q10_b_126",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist ein Antigen?",
    answers: ["Ein Stoff, der eine Immunreaktion auslöst", "Nur ein Antikörper", "Nur ein Hormon", "Nur ein Enzym"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Antigene werden vom Immunsystem erkannt."
  },
  {
    id: "q10_b_127",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Dickdarms?",
    answers: ["Wasserentzug und Formung des Kots", "Nur die Verdauung von Proteinen", "Nur die Aufnahme von Nährstoffen", "Nur die Produktion von Enzymen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Dickdarm wird dem Nahrungsbrei Wasser entzogen."
  },
  {
    id: "q10_b_128",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe des Dünndarms?",
    answers: ["Hauptort der Nährstoffaufnahme", "Nur die Wasseraufnahme", "Nur die Kotbildung", "Nur die Speicherung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Dünndarm werden die meisten Nährstoffe resorbiert."
  },
  {
    id: "q10_b_129",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Arterien und Venen?",
    answers: ["Arterien führen Blut vom Herzen weg, Venen zum Herzen hin", "Beide sind identisch", "Arterien führen immer sauerstoffarmes Blut", "Venen führen immer sauerstoffreiches Blut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Richtung relativ zum Herzen definiert sie."
  },
  {
    id: "q10_b_130",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Kapillaren?",
    answers: ["Feinste Blutgefäße, in denen der Stoffaustausch stattfindet", "Nur große Arterien", "Nur große Venen", "Nur Lymphgefäße"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kapillaren ermöglichen den Austausch mit den Geweben."
  },
  {
    id: "q10_b_131",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Puls?",
    answers: ["Die druckbedingte Ausdehnung der Arterienwände", "Nur die Herzfrequenz im Ruhezustand", "Nur die Atemfrequenz", "Nur der Blutdruck"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Puls spiegelt die Herzschläge wider."
  },
  {
    id: "q10_b_132",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Blutdruck?",
    answers: ["Der Druck des Blutes auf die Gefäßwände", "Nur die Herzfrequenz", "Nur der Puls", "Nur die Atemfrequenz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Blutdruck wird in mmHg gemessen."
  },
  {
    id: "q10_b_133",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Bauchspeicheldrüse (Pankreas)?",
    answers: ["Produktion von Verdauungsenzymen und Hormonen (Insulin)", "Nur die Speicherung von Galle", "Nur die Blutbildung", "Nur die Atmung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Pankreas hat exokrine und endokrine Funktionen."
  },
  {
    id: "q10_b_134",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Insulin?",
    answers: ["Ein Hormon, das den Blutzuckerspiegel senkt", "Ein Verdauungsenzym", "Ein Antikörper", "Ein Nervensignal"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Insulin fördert die Aufnahme von Glucose in die Zellen."
  },
  {
    id: "q10_b_135",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Schilddrüse?",
    answers: ["Produktion von Hormonen, die den Stoffwechsel regulieren", "Nur die Verdauung", "Nur die Blutbildung", "Nur die Abwehr"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Schilddrüsenhormone beeinflussen den Energieumsatz."
  },
  {
    id: "q10_b_136",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen somatischem und vegetativem Nervensystem?",
    answers: ["Somatisch = willkürlich, vegetativ = unwillkürlich", "Beide sind identisch", "Somatisch steuert nur innere Organe", "Vegetativ steuert nur Skelettmuskeln"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Vegetatives System reguliert innere Organe."
  },
  {
    id: "q10_b_137",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Sympathikus?",
    answers: ["Teil des vegetativen Systems, der den Körper leistungsbereit macht", "Nur der Parasympathikus", "Nur das somatische System", "Nur das Gehirn"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Sympathikus = 'Kampf-oder-Flucht'-Reaktion."
  },
  {
    id: "q10_b_138",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Parasympathikus?",
    answers: ["Teil des vegetativen Systems, der den Körper in Ruhe versetzt", "Nur der Sympathikus", "Nur das somatische System", "Nur das Rückenmark"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Parasympathikus = 'Rest-and-Digest'."
  },
  {
    id: "q10_b_139",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Haut?",
    answers: ["Schutz, Temperaturregulation und Sinnesorgan", "Nur die Verdauung", "Nur die Blutbildung", "Nur die Atmung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Haut hat multiple Funktionen."
  },
  {
    id: "q10_b_140",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen angeborener und erlernter Immunität?",
    answers: ["Angeboren ist unspezifisch, erlernt ist spezifisch und hat Gedächtnis", "Beide sind identisch", "Angeboren ist immer spezifisch", "Erlernt ist immer unspezifisch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das erworbene System lernt aus Kontakten mit Erregern."
  },
  {
    id: "q10_b_141",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist eine Allergie?",
    answers: ["Eine übersteigerte Immunreaktion gegen harmlose Stoffe", "Nur eine Infektion", "Nur eine Mangelerscheinung", "Nur eine Vergiftung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Allergien sind Fehlregulationen des Immunsystems."
  },
  {
    id: "q10_b_142",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Virus und Bakterium?",
    answers: ["Viren sind keine Zellen und brauchen Wirtszellen, Bakterien sind eigenständige Zellen", "Beide sind identisch", "Viren sind immer größer", "Bakterien brauchen immer Wirtszellen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Unterschiedliche Organisation und Vermehrung."
  },
  {
    id: "q10_b_143",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Antibiotika?",
    answers: ["Wirkstoffe gegen Bakterien", "Wirkstoffe gegen Viren", "Wirkstoffe gegen alle Erreger", "Nur Impfstoffe"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Antibiotika wirken nicht gegen Viren."
  },
  {
    id: "q10_b_144",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist Resilienz im gesundheitlichen Kontext?",
    answers: ["Die Fähigkeit, Belastungen zu bewältigen und sich zu erholen", "Nur die körperliche Fitness", "Nur die Immunität", "Nur die Ernährung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Resilienz umfasst körperliche und psychische Aspekte."
  },
  {
    id: "q10_b_145",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen akuter und chronischer Erkrankung?",
    answers: ["Akut = plötzlich und kurz, chronisch = lang andauernd", "Beide sind identisch", "Akut ist immer unheilbar", "Chronisch ist immer harmlos"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Zeitverlauf unterscheidet sie."
  },
  {
    id: "q10_b_146",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Lymphknoten?",
    answers: ["Filterung der Lymphe und Aktivierung von Immunzellen", "Nur die Blutbildung", "Nur die Verdauung", "Nur die Atmung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Lymphknoten sind wichtige Stationen der Immunabwehr."
  },
  {
    id: "q10_b_147",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen äußerer und innerer Atmung?",
    answers: ["Äußere = Gasaustausch in der Lunge, innere = Zellatmung", "Beide sind identisch", "Äußere ist nur die Zellatmung", "Innere ist nur der Lungengasaustausch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide Prozesse sind für die Energieversorgung nötig."
  },
  {
    id: "q10_b_148",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der pH-Wert des Magensaftes?",
    answers: ["Stark sauer (ca. 1–2)", "Neutral (7)", "Stark basisch (12–14)", "Schwach sauer (5–6)"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Salzsäure im Magen tötet viele Keime und aktiviert Enzyme."
  },
  {
    id: "q10_b_149",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist die Aufgabe der Galle?",
    answers: ["Emulgierung von Fetten zur besseren Verdauung", "Nur die Eiweißverdauung", "Nur die Kohlenhydratverdauung", "Nur die Abwehr"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Galle zerlegt Fette in kleinere Tröpfchen."
  },
  {
    id: "q10_b_150",
    category: "k10_biologie",
    topic: "mensch_gesundheit",
    area: "schule",
    grade: 10,
    subject: "biologie",
    question: "Was ist der Unterschied zwischen Nährstoffen und Ballaststoffen?",
    answers: ["Nährstoffe liefern Energie oder Bausteine, Ballaststoffe werden nicht verdaut", "Beide sind identisch", "Ballaststoffe liefern immer Energie", "Nährstoffe werden nie verdaut"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ballaststoffe fördern die Verdauung, liefern aber kaum Energie."
  }
];
