const K10_INFORMATIK_QUESTIONS = [
  // ================================================================
  // 1. INFORMATION, DATEN & CODIERUNG (35 Fragen)
  // ================================================================
  {
    id: "q10_i_001",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Daten und Information?",
    answers: ["Daten sind rohe Zeichenfolgen, Information ist interpretierte Bedeutung", "Beide sind identisch", "Daten sind immer Information", "Information ist immer Daten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Information entsteht durch Interpretation von Daten."
  },
  {
    id: "q10_i_002",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Bit?",
    answers: ["Die kleinste Informationseinheit mit den Zuständen 0 oder 1", "Ein Byte", "Ein Kilobyte", "Ein Zeichen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bit steht für Binary Digit."
  },
  {
    id: "q10_i_003",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Wie viele Bits hat ein Byte?",
    answers: ["8 Bits", "4 Bits", "16 Bits", "32 Bits"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Byte = 8 Bit."
  },
  {
    id: "q10_i_004",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das Dualsystem?",
    answers: ["Ein Zahlensystem mit der Basis 2 (Ziffern 0 und 1)", "Ein Zahlensystem mit der Basis 10", "Ein Zahlensystem mit der Basis 16", "Ein Zahlensystem mit der Basis 8"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Computer arbeiten intern im Dualsystem."
  },
  {
    id: "q10_i_005",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das Hexadezimalsystem?",
    answers: ["Ein Zahlensystem mit der Basis 16 (0–9 und A–F)", "Ein Zahlensystem mit der Basis 2", "Ein Zahlensystem mit der Basis 10", "Ein Zahlensystem mit der Basis 8"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hexadezimal wird oft für Speicheradressen und Farben genutzt."
  },
  {
    id: "q10_i_006",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ASCII?",
    answers: ["Ein Zeichencode, der Zeichen durch Zahlen darstellt", "Ein Bildformat", "Ein Dateiformat", "Ein Programmiersprache"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "ASCII codiert 128 Zeichen."
  },
  {
    id: "q10_i_007",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Unicode?",
    answers: ["Ein Zeichencode, der fast alle Schriftzeichen der Welt abbildet", "Nur ASCII", "Nur ein Bildformat", "Nur ein Dateiformat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "UTF-8 ist eine häufige Unicode-Kodierung."
  },
  {
    id: "q10_i_008",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Pixelgrafik?",
    answers: ["Ein Bild, das aus einzelnen Bildpunkten (Pixeln) besteht", "Ein Bild aus Vektoren", "Ein Text", "Ein Sound"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Pixelgrafiken verlieren bei Vergrößerung an Qualität."
  },
  {
    id: "q10_i_009",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Vektorgrafik?",
    answers: ["Ein Bild, das aus mathematischen Formen und Linien besteht", "Ein Bild aus Pixeln", "Ein Text", "Ein Sound"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Vektorgrafiken skalieren verlustfrei."
  },
  {
    id: "q10_i_010",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Kompression?",
    answers: ["Die Verkleinerung der Datenmenge bei möglichst geringem Qualitätsverlust", "Nur die Verschlüsselung", "Nur die Speicherung", "Nur die Übertragung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verlustbehaftet und verlustfrei sind zwei Arten."
  },
  {
    id: "q10_i_011",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist verlustfreie Kompression?",
    answers: ["Kompression, bei der die Originaldaten vollständig wiederherstellbar sind", "Kompression mit Qualitätsverlust", "Nur Bildkompression", "Nur Audiokompression"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "ZIP und PNG nutzen verlustfreie Verfahren."
  },
  {
    id: "q10_i_012",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist verlustbehaftete Kompression?",
    answers: ["Kompression, bei der Informationen dauerhaft weggelassen werden", "Kompression ohne Qualitätsverlust", "Nur Textkompression", "Nur Datenbankspeicherung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "JPEG und MP3 sind verlustbehaftet."
  },
  {
    id: "q10_i_013",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Dateiformat?",
    answers: ["Eine festgelegte Struktur zur Speicherung von Daten einer bestimmten Art", "Nur ein Dateiname", "Nur ein Ordner", "Nur ein Programm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: .txt, .jpg, .mp3, .pdf."
  },
  {
    id: "q10_i_014",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Metadaten?",
    answers: ["Daten über andere Daten (z. B. Erstellungsdatum, Autor)", "Nur die eigentlichen Inhaltsdaten", "Nur verschlüsselte Daten", "Nur komprimierte Daten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Metadaten beschreiben Eigenschaften von Dateien."
  },
  {
    id: "q10_i_015",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Algorithmus?",
    answers: ["Eine endliche Folge eindeutiger Schritte zur Lösung eines Problems", "Nur ein Computerprogramm", "Nur eine Formel", "Nur eine Hardwarekomponente"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Algorithmen sind Grundlage der Programmierung."
  },
  {
    id: "q10_i_016",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Variable in der Programmierung?",
    answers: ["Ein benannter Speicherplatz für veränderbare Werte", "Nur ein fester Wert", "Nur eine Funktion", "Nur eine Schleife"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Variablen speichern Daten während der Programmausführung."
  },
  {
    id: "q10_i_017",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Datentyp?",
    answers: ["Die Art der Daten, die eine Variable speichern kann (z. B. Zahl, Text)", "Nur der Name der Variable", "Nur der Speicherort", "Nur die Programmiersprache"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Häufige Typen: Integer, String, Boolean."
  },
  {
    id: "q10_i_018",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Boolesche Variable?",
    answers: ["Eine Variable, die nur wahr oder falsch speichern kann", "Eine Variable für Zahlen", "Eine Variable für Texte", "Eine Variable für Bilder"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Boolean-Werte sind true/false bzw. 1/0."
  },
  {
    id: "q10_i_019",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Array / eine Liste?",
    answers: ["Eine geordnete Sammlung von Elementen gleichen oder ähnlichen Typs", "Nur eine einzelne Variable", "Nur eine Funktion", "Nur eine Schleife"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Arrays speichern mehrere Werte unter einem Namen."
  },
  {
    id: "q10_i_020",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Datenbank?",
    answers: ["Ein organisiertes System zur Speicherung und Verwaltung großer Datenmengen", "Nur eine Excel-Tabelle", "Nur eine Textdatei", "Nur ein Ordner"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Datenbanken ermöglichen effiziente Abfragen."
  },
  {
    id: "q10_i_021",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist SQL?",
    answers: ["Eine Sprache zur Abfrage und Bearbeitung von relationalen Datenbanken", "Nur eine Programmiersprache für Apps", "Nur ein Dateiformat", "Nur ein Betriebssystem"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "SQL steht für Structured Query Language."
  },
  {
    id: "q10_i_022",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein relationales Datenbankmodell?",
    answers: ["Daten werden in Tabellen mit Beziehungen (Relationen) gespeichert", "Daten werden nur als Graph gespeichert", "Daten werden nur als Text gespeichert", "Daten werden nur als Bilder gespeichert"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Tabellen sind über Schlüssel verbunden."
  },
  {
    id: "q10_i_023",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Primärschlüssel?",
    answers: ["Ein eindeutiges Attribut, das jeden Datensatz in einer Tabelle identifiziert", "Nur ein Fremdschlüssel", "Nur ein Index", "Nur ein Datentyp"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Primärschlüssel gewährleisten Eindeutigkeit."
  },
  {
    id: "q10_i_024",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Fremdschlüssel?",
    answers: ["Ein Attribut, das auf den Primärschlüssel einer anderen Tabelle verweist", "Nur ein Primärschlüssel", "Nur ein Index", "Nur ein Datentyp"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Fremdschlüssel erzeugen Beziehungen zwischen Tabellen."
  },
  {
    id: "q10_i_025",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Normalisierung in Datenbanken?",
    answers: ["Die strukturierte Aufteilung von Daten zur Vermeidung von Redundanz", "Nur die Verschlüsselung", "Nur die Kompression", "Nur die Sicherung"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Normalformen helfen bei sauberer Datenbankstruktur."
  },
  {
    id: "q10_i_026",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Big Data?",
    answers: ["Sehr große und komplexe Datenmengen, die mit klassischen Methoden schwer zu verarbeiten sind", "Nur kleine Datensätze", "Nur Textdateien", "Nur Bilder"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Big Data erfordert spezielle Technologien."
  },
  {
    id: "q10_i_027",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Hash-Wert?",
    answers: ["Ein aus Daten berechneter fester Fingerabdruck", "Nur ein Passwort", "Nur ein Schlüssel", "Nur eine Adresse"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Hash-Funktionen werden für Integrität und Passwörter genutzt."
  },
  {
    id: "q10_i_028",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Verschlüsselung?",
    answers: ["Die Umwandlung von Daten in eine unleserliche Form mit Schlüssel", "Nur die Kompression", "Nur die Speicherung", "Nur die Übertragung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verschlüsselung schützt Vertraulichkeit."
  },
  {
    id: "q10_i_029",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist symmetrische Verschlüsselung?",
    answers: ["Ver- und Entschlüsselung mit demselben Schlüssel", "Ver- und Entschlüsselung mit unterschiedlichen Schlüsseln", "Nur Hashing", "Nur Kompression"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "AES ist ein bekanntes symmetrisches Verfahren."
  },
  {
    id: "q10_i_030",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist asymmetrische Verschlüsselung?",
    answers: ["Ver- und Entschlüsselung mit einem Schlüsselpaar (öffentlich/privat)", "Ver- und Entschlüsselung mit demselben Schlüssel", "Nur Hashing", "Nur Kompression"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "RSA ist ein bekanntes asymmetrisches Verfahren."
  },
  {
    id: "q10_i_031",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein digitaler Fingerabdruck / Hash?",
    answers: ["Ein kurzer, eindeutiger Wert, der aus Daten berechnet wird", "Nur ein Passwort", "Nur ein Zertifikat", "Nur ein Schlüssel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Hashes prüfen Integrität von Dateien."
  },
  {
    id: "q10_i_032",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Base64?",
    answers: ["Eine Kodierung von Binärdaten in lesbare ASCII-Zeichen", "Nur eine Verschlüsselung", "Nur eine Kompression", "Nur ein Dateiformat"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Base64 wird oft für E-Mail-Anhänge und Webdaten genutzt."
  },
  {
    id: "q10_i_033",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein QR-Code?",
    answers: ["Ein zweidimensionaler Code, der Informationen speichern kann", "Nur ein Barcode", "Nur ein Bild", "Nur ein Link"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "QR-Codes können Texte, URLs und mehr speichern."
  },
  {
    id: "q10_i_034",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Open Data?",
    answers: ["Frei zugängliche und nutzbare Daten ohne oder mit minimalen Einschränkungen", "Nur geheime Daten", "Nur bezahlte Daten", "Nur persönliche Daten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Open Data fördert Transparenz und Innovation."
  },
  {
    id: "q10_i_035",
    category: "k10_informatik",
    topic: "daten",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen analog und digital?",
    answers: ["Analog: stufenlos, digital: in diskreten Werten (0/1)", "Beide sind identisch", "Analog ist immer digital", "Digital ist immer analog"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Digitale Systeme arbeiten mit diskreten Zuständen."
  },

  // ================================================================
  // 2. ALGORITHMEN & PROGRAMMIERUNG (40 Fragen)
  // ================================================================
  {
    id: "q10_i_036",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Sequenz in einem Algorithmus?",
    answers: ["Die hintereinander ausgeführte Abfolge von Anweisungen", "Nur eine Wiederholung", "Nur eine Verzweigung", "Nur eine Funktion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sequenz ist die einfachste Kontrollstruktur."
  },
  {
    id: "q10_i_037",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Verzweigung (If-Then-Else)?",
    answers: ["Eine Entscheidung, die je nach Bedingung unterschiedliche Wege nimmt", "Nur eine Wiederholung", "Nur eine Sequenz", "Nur eine Funktion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verzweigungen ermöglichen bedingte Ausführung."
  },
  {
    id: "q10_i_038",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Schleife?",
    answers: ["Eine Wiederholung von Anweisungen, solange eine Bedingung gilt", "Nur eine Verzweigung", "Nur eine Sequenz", "Nur eine Funktion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Schleifen sparen Code und ermöglichen Iteration."
  },
  {
    id: "q10_i_039",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Zählschleife (For-Schleife)?",
    answers: ["Eine Schleife, die eine feste Anzahl von Wiederholungen ausführt", "Nur eine bedingte Schleife", "Nur eine Endlosschleife", "Nur eine Verzweigung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "For-Schleifen kennen den Wiederholungsbereich."
  },
  {
    id: "q10_i_040",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine bedingte Schleife (While-Schleife)?",
    answers: ["Eine Schleife, die läuft, solange eine Bedingung wahr ist", "Nur eine Zählschleife", "Nur eine Sequenz", "Nur eine Funktion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "While-Schleifen prüfen die Bedingung vor jedem Durchlauf."
  },
  {
    id: "q10_i_041",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Funktion / Prozedur?",
    answers: ["Ein benannter, wiederverwendbarer Codeabschnitt", "Nur eine Variable", "Nur eine Schleife", "Nur eine Verzweigung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Funktionen strukturieren und modularisieren Programme."
  },
  {
    id: "q10_i_042",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Parameter?",
    answers: ["Ein Wert, der an eine Funktion übergeben wird", "Nur der Rückgabewert", "Nur eine Variable im Hauptprogramm", "Nur eine Schleifenvariable"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Parameter machen Funktionen flexibel."
  },
  {
    id: "q10_i_043",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Rückgabewert?",
    answers: ["Der Wert, den eine Funktion an den Aufrufer zurückgibt", "Nur ein Parameter", "Nur eine Variable", "Nur eine Fehlermeldung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Funktionen können Ergebnisse zurückliefern."
  },
  {
    id: "q10_i_044",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Rekursion?",
    answers: ["Eine Funktion, die sich selbst aufruft", "Nur eine Schleife", "Nur eine Verzweigung", "Nur eine Sequenz"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Rekursion braucht eine Abbruchbedingung."
  },
  {
    id: "q10_i_045",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Sortieralgorithmus?",
    answers: ["Ein Algorithmus, der Elemente einer Liste in eine Ordnung bringt", "Nur ein Suchalgorithmus", "Nur eine Verschlüsselung", "Nur eine Kompression"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Bubble Sort, Selection Sort, Quicksort."
  },
  {
    id: "q10_i_046",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Bubble Sort?",
    answers: ["Ein einfacher Sortieralgorithmus, der benachbarte Elemente vertauscht", "Ein sehr schneller Sortieralgorithmus", "Ein Suchalgorithmus", "Ein Kompressionsalgorithmus"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bubble Sort ist anschaulich, aber ineffizient für große Listen."
  },
  {
    id: "q10_i_047",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Suchalgorithmus?",
    answers: ["Ein Algorithmus, der ein Element in einer Datenstruktur findet", "Nur ein Sortieralgorithmus", "Nur eine Verschlüsselung", "Nur eine Kompression"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Lineare und binäre Suche sind grundlegend."
  },
  {
    id: "q10_i_048",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist binäre Suche?",
    answers: ["Eine effiziente Suche in einer sortierten Liste durch Halbierung", "Eine Suche, die jedes Element prüft", "Nur eine Sortiermethode", "Nur eine Verschlüsselung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Binäre Suche benötigt eine sortierte Liste."
  },
  {
    id: "q10_i_049",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die Komplexität eines Algorithmus?",
    answers: ["Ein Maß dafür, wie der Ressourcenbedarf mit der Eingabegröße wächst", "Nur die Länge des Codes", "Nur die Anzahl der Zeilen", "Nur die Programmiersprache"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Oft in O-Notation (Big O) angegeben."
  },
  {
    id: "q10_i_050",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was bedeutet O(n) bei der Komplexität?",
    answers: ["Der Aufwand wächst linear mit der Eingabegröße", "Der Aufwand ist konstant", "Der Aufwand wächst quadratisch", "Der Aufwand wächst logarithmisch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Lineare Suche hat typischerweise O(n)."
  },
  {
    id: "q10_i_051",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Pseudocode?",
    answers: ["Eine menschenlesbare Beschreibung eines Algorithmus ohne strikte Syntax", "Nur echter Programmcode", "Nur Maschinencode", "Nur Assembler"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Pseudocode hilft beim Entwurf vor dem Programmieren."
  },
  {
    id: "q10_i_052",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Struktogramm / Nassi-Shneiderman-Diagramm?",
    answers: ["Eine grafische Darstellung von Algorithmen mit Blöcken", "Nur ein Flussdiagramm", "Nur ein Klassendiagramm", "Nur ein ER-Diagramm"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Struktogramme visualisieren Kontrollstrukturen."
  },
  {
    id: "q10_i_053",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Flussdiagramm?",
    answers: ["Eine grafische Darstellung von Abläufen mit Symbolen für Schritte und Entscheidungen", "Nur ein Struktogramm", "Nur ein Klassendiagramm", "Nur ein Netzwerkdiagramm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Flussdiagramme sind weit verbreitet."
  },
  {
    id: "q10_i_054",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Debugging?",
    answers: ["Das systematische Finden und Beheben von Fehlern im Programm", "Nur das Schreiben von Code", "Nur das Kompilieren", "Nur das Ausführen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Debugger helfen beim schrittweisen Testen."
  },
  {
    id: "q10_i_055",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Syntaxfehler?",
    answers: ["Ein Fehler gegen die Regeln der Programmiersprache", "Ein logischer Fehler", "Ein Laufzeitfehler", "Ein Hardwarefehler"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Syntaxfehler werden oft schon beim Übersetzen erkannt."
  },
  {
    id: "q10_i_056",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein logischer Fehler?",
    answers: ["Ein Fehler, bei dem das Programm läuft, aber falsche Ergebnisse liefert", "Ein Syntaxfehler", "Ein Compilerfehler", "Ein Hardwarefehler"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Logische Fehler sind oft schwerer zu finden."
  },
  {
    id: "q10_i_057",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Compiler?",
    answers: ["Ein Programm, das Quellcode in ausführbaren Maschinencode übersetzt", "Ein Interpreter", "Ein Editor", "Ein Debugger"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Compiler erzeugen eine ausführbare Datei."
  },
  {
    id: "q10_i_058",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Interpreter?",
    answers: ["Ein Programm, das Quellcode Zeile für Zeile ausführt", "Ein Compiler", "Ein Editor", "Ein Debugger"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Python wird typischerweise interpretiert."
  },
  {
    id: "q10_i_059",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist objektorientierte Programmierung (OOP)?",
    answers: ["Ein Paradigma, das Daten und Methoden in Objekten und Klassen organisiert", "Nur prozedurale Programmierung", "Nur funktionale Programmierung", "Nur Assembler"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Klassen, Objekte, Vererbung und Kapselung sind zentrale Konzepte."
  },
  {
    id: "q10_i_060",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine Klasse?",
    answers: ["Eine Vorlage (Bauplan) für Objekte mit Attributen und Methoden", "Nur ein Objekt", "Nur eine Funktion", "Nur eine Variable"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Aus Klassen werden Objekte erzeugt (Instanziierung)."
  },
  {
    id: "q10_i_061",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Objekt?",
    answers: ["Eine konkrete Instanz einer Klasse mit eigenen Werten", "Nur eine Klasse", "Nur eine Funktion", "Nur eine Variable"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Objekte haben Zustand (Attribute) und Verhalten (Methoden)."
  },
  {
    id: "q10_i_062",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Vererbung?",
    answers: ["Das Ableiten neuer Klassen von bestehenden Klassen unter Übernahme von Eigenschaften", "Nur das Kopieren von Code", "Nur das Überschreiben von Dateien", "Nur das Speichern"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Vererbung fördert Wiederverwendung und Hierarchien."
  },
  {
    id: "q10_i_063",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Kapselung?",
    answers: ["Das Verbergen interner Details einer Klasse und kontrollierter Zugriff über Methoden", "Nur das Verstecken von Dateien", "Nur das Verschlüsseln", "Nur das Komprimieren"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Kapselung schützt Datenintegrität."
  },
  {
    id: "q10_i_064",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Polymorphie?",
    answers: ["Die Fähigkeit, dass gleiche Methodenaufrufe unterschiedliche Verhaltensweisen auslösen", "Nur Vererbung", "Nur Kapselung", "Nur Abstraktion"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Polymorphie ermöglicht flexible und erweiterbare Systeme."
  },
  {
    id: "q10_i_065",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist eine API?",
    answers: ["Eine Schnittstelle, über die Programme miteinander kommunizieren", "Nur ein Programm", "Nur eine Datenbank", "Nur ein Betriebssystem"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "API steht für Application Programming Interface."
  },
  {
    id: "q10_i_066",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Versionskontrolle (z. B. Git)?",
    answers: ["Ein System zur Nachverfolgung und Verwaltung von Änderungen am Code", "Nur ein Editor", "Nur ein Compiler", "Nur ein Debugger"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Git ermöglicht Zusammenarbeit und Historie."
  },
  {
    id: "q10_i_067",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Repository?",
    answers: ["Ein Speicherort für den Code und dessen Versionshistorie", "Nur ein Ordner", "Nur eine Datei", "Nur ein Server"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Git-Repositories können lokal oder remote sein."
  },
  {
    id: "q10_i_068",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Open Source?",
    answers: ["Software, deren Quellcode öffentlich zugänglich und veränderbar ist", "Nur kostenlose Software", "Nur proprietäre Software", "Nur Cloud-Software"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Open Source fördert Transparenz und Zusammenarbeit."
  },
  {
    id: "q10_i_069",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Bug?",
    answers: ["Ein Fehler im Programmcode oder Verhalten", "Nur ein Feature", "Nur eine Warnung", "Nur ein Kommentar"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bugs werden durch Debugging behoben."
  },
  {
    id: "q10_i_070",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Testen in der Softwareentwicklung?",
    answers: ["Das systematische Prüfen, ob ein Programm die Anforderungen erfüllt", "Nur das Schreiben von Code", "Nur das Kompilieren", "Nur das Veröffentlichen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Tests erhöhen die Softwarequalität."
  },
  {
    id: "q10_i_071",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Modul?",
    answers: ["Ein eigenständiger, wiederverwendbarer Programmteil", "Nur eine Variable", "Nur eine Schleife", "Nur eine Datei"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Module fördern Struktur und Wiederverwendung."
  },
  {
    id: "q10_i_072",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die IDE?",
    answers: ["Eine integrierte Entwicklungsumgebung mit Editor, Compiler und Debugger", "Nur ein Texteditor", "Nur ein Browser", "Nur ein Betriebssystem"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: VS Code, PyCharm, Eclipse."
  },
  {
    id: "q10_i_073",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Scratch?",
    answers: ["Eine visuelle Programmiersprache für Einsteiger mit Bausteinen", "Nur eine Textsprache", "Nur eine Datenbank", "Nur ein Betriebssystem"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Scratch wird oft in der Schule eingesetzt."
  },
  {
    id: "q10_i_074",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Python?",
    answers: ["Eine weit verbreitete, lesbare Programmiersprache", "Nur eine Datenbank", "Nur ein Betriebssystem", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Python eignet sich gut für Anfänger und Datenanalyse."
  },
  {
    id: "q10_i_075",
    category: "k10_informatik",
    topic: "algorithmen",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist JavaScript?",
    answers: ["Eine Programmiersprache, die vor allem im Web eingesetzt wird", "Nur eine Datenbanksprache", "Nur ein Betriebssystem", "Nur ein Textformat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "JavaScript läuft in Browsern und auf Servern (Node.js)."
  },

  // ================================================================
  // 3. INFORMATIKSYSTEME & HARDWARE (30 Fragen)
  // ================================================================
  {
    id: "q10_i_076",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die Von-Neumann-Architektur?",
    answers: ["Ein Rechnermodell mit gemeinsamer Speicher für Programm und Daten", "Nur ein Netzwerkmodell", "Nur ein Datenbankmodell", "Nur ein Programmierparadigma"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die meisten heutigen Computer folgen diesem Prinzip."
  },
  {
    id: "q10_i_077",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die CPU?",
    answers: ["Die zentrale Verarbeitungseinheit, das „Gehirn“ des Computers", "Nur der Arbeitsspeicher", "Nur die Festplatte", "Nur die Grafikkarte"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "CPU steht für Central Processing Unit."
  },
  {
    id: "q10_i_078",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist RAM?",
    answers: ["Der flüchtige Arbeitsspeicher des Computers", "Nur der Festspeicher", "Nur der Prozessor", "Nur die Grafikkarte"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "RAM verliert Daten beim Ausschalten."
  },
  {
    id: "q10_i_079",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Festspeicher (SSD/HDD)?",
    answers: ["Ein nicht-flüchtiger Speicher für dauerhafte Daten", "Nur der Arbeitsspeicher", "Nur der Prozessor", "Nur der Cache"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "SSDs sind schneller als klassische Festplatten."
  },
  {
    id: "q10_i_080",
    category: "k10_informatik",
 topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Betriebssystem?",
    answers: ["Die Software, die Hardware verwaltet und Programme ausführt", "Nur ein Anwendungsprogramm", "Nur ein Treiber", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Windows, macOS, Linux, Android."
  },
  {
    id: "q10_i_081",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Treiber?",
    answers: ["Software, die die Kommunikation zwischen Betriebssystem und Hardware ermöglicht", "Nur ein Anwendungsprogramm", "Nur ein Virus", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ohne Treiber funktioniert Hardware oft nicht korrekt."
  },
  {
    id: "q10_i_082",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Netzwerk?",
    answers: ["Eine Verbindung mehrerer Computer zum Datenaustausch", "Nur ein einzelner Computer", "Nur eine Datei", "Nur ein Programm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Netzwerke können lokal (LAN) oder global (Internet) sein."
  },
  {
    id: "q10_i_083",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das Internet?",
    answers: ["Ein weltweites Netzwerk von Netzwerken", "Nur das World Wide Web", "Nur E-Mail", "Nur soziale Medien"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das WWW ist nur ein Dienst des Internets."
  },
  {
    id: "q10_i_084",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist das World Wide Web (WWW)?",
    answers: ["Ein System von miteinander verknüpften Hypertext-Dokumenten im Internet", "Nur das Internet", "Nur E-Mail", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das WWW basiert auf HTTP und HTML."
  },
  {
    id: "q10_i_085",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Browser?",
    answers: ["Ein Programm zum Anzeigen und Navigieren von Webseiten", "Nur ein Betriebssystem", "Nur ein Editor", "Nur ein Server"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Chrome, Firefox, Safari, Edge."
  },
  {
    id: "q10_i_086",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist HTML?",
    answers: ["Eine Auszeichnungssprache zur Strukturierung von Webseiten", "Nur eine Programmiersprache", "Nur ein Stylesheet", "Nur ein Datenbankformat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "HTML steht für HyperText Markup Language."
  },
  {
    id: "q10_i_087",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist CSS?",
    answers: ["Eine Sprache zur Gestaltung und Formatierung von Webseiten", "Nur eine Programmiersprache", "Nur eine Auszeichnungssprache", "Nur ein Datenbankformat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "CSS steht für Cascading Style Sheets."
  },
  {
    id: "q10_i_088",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Server?",
    answers: ["Ein Computer oder Programm, das Dienste für andere Computer bereitstellt", "Nur ein Client", "Nur ein Browser", "Nur ein Router"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Webserver liefern Webseiten aus."
  },
  {
    id: "q10_i_089",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Client?",
    answers: ["Ein Computer oder Programm, das Dienste von einem Server anfordert", "Nur ein Server", "Nur ein Router", "Nur ein Switch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Browser sind typische Clients."
  },
  {
    id: "q10_i_090",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist IP-Adresse?",
    answers: ["Eine eindeutige Adresse eines Geräts im Netzwerk", "Nur ein Domainname", "Nur ein Passwort", "Nur ein Port"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "IPv4 und IPv6 sind die gängigen Versionen."
  },
  {
    id: "q10_i_091",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist DNS?",
    answers: ["Ein System, das Domainnamen in IP-Adressen übersetzt", "Nur ein Protokoll", "Nur ein Browser", "Nur ein Server"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "DNS macht das Internet benutzerfreundlich."
  },
  {
    id: "q10_i_092",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist HTTP / HTTPS?",
    answers: ["Protokolle zur Übertragung von Webseiten (HTTPS ist verschlüsselt)", "Nur ein Dateiformat", "Nur eine Programmiersprache", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "HTTPS schützt die Verbindung durch Verschlüsselung."
  },
  {
    id: "q10_i_093",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Router?",
    answers: ["Ein Gerät, das Datenpakete zwischen Netzwerken weiterleitet", "Nur ein Switch", "Nur ein Modem", "Nur ein Server"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Router verbinden z. B. Heimnetz und Internet."
  },
  {
    id: "q10_i_094",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Switch?",
    answers: ["Ein Gerät, das Daten innerhalb eines lokalen Netzwerks verteilt", "Nur ein Router", "Nur ein Modem", "Nur ein Server"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Switches arbeiten auf der Data-Link-Schicht."
  },
  {
    id: "q10_i_095",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Firewall?",
    answers: ["Ein Sicherheitssystem, das unerwünschten Netzwerkverkehr filtert", "Nur ein Antivirus", "Nur ein Router", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Firewalls schützen vor unerlaubten Zugriffen."
  },
  {
    id: "q10_i_096",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Cloud Computing?",
    answers: ["Die Nutzung von IT-Ressourcen über das Internet statt lokal", "Nur lokaler Speicher", "Nur ein Betriebssystem", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Google Drive, AWS, Microsoft Azure."
  },
  {
    id: "q10_i_097",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Algorithmus in Hardware-Kontext (z. B. CPU)?",
    answers: ["Die festgelegte Abfolge von Schritten, die der Prozessor ausführt", "Nur Software", "Nur ein Programm", "Nur ein Dateiformat"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Auch Hardware folgt algorithmischen Abläufen."
  },
  {
    id: "q10_i_098",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Bus im Computer?",
    answers: ["Ein Kommunikationsweg für Daten zwischen Komponenten", "Nur ein Speicher", "Nur ein Prozessor", "Nur ein Netzwerk"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Es gibt Datenbus, Adressbus und Steuerbus."
  },
  {
    id: "q10_i_099",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Cache?",
    answers: ["Ein schneller Zwischenspeicher für häufig genutzte Daten", "Nur der Arbeitsspeicher", "Nur die Festplatte", "Nur der Prozessor"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Cache beschleunigt den Datenzugriff."
  },
  {
    id: "q10_i_100",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Peripheriegerät?",
    answers: ["Ein externes Gerät, das an den Computer angeschlossen wird", "Nur die CPU", "Nur der RAM", "Nur das Mainboard"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: Tastatur, Maus, Drucker, Monitor."
  },
  {
    id: "q10_i_101",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Mainboard / Motherboard?",
    answers: ["Die Hauptplatine, auf der die zentralen Komponenten verbunden sind", "Nur die CPU", "Nur der RAM", "Nur die Grafikkarte"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Mainboard verbindet alle Teile."
  },
  {
    id: "q10_i_102",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Betriebssystem-Kernel?",
    answers: ["Der zentrale Kern des Betriebssystems, der Hardware und Prozesse verwaltet", "Nur eine Anwendung", "Nur ein Treiber", "Nur ein Browser"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Kernel hat besondere Privilegien."
  },
  {
    id: "q10_i_103",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Virtualisierung?",
    answers: ["Das Ausführen mehrerer virtueller Systeme auf einer physischen Hardware", "Nur Cloud-Speicher", "Nur Kompression", "Nur Verschlüsselung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Virtuelle Maschinen teilen sich die Hardware."
  },
  {
    id: "q10_i_104",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein IoT-Gerät?",
    answers: ["Ein mit dem Internet verbundenes Alltagsgerät (Internet of Things)", "Nur ein Computer", "Nur ein Smartphone", "Nur ein Server"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: smarte Lampen, Thermostate, Wearables."
  },
  {
    id: "q10_i_105",
    category: "k10_informatik",
    topic: "systeme",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Protokoll in Netzwerken?",
    answers: ["Ein Satz von Regeln für die Kommunikation zwischen Geräten", "Nur ein Passwort", "Nur eine IP-Adresse", "Nur ein Port"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beispiele: TCP, IP, HTTP, SMTP."
  },

  // ================================================================
  // 4. KI, DATENSCHUTZ, GESELLSCHAFT (45 Fragen)
  // ================================================================
  {
    id: "q10_i_106",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist künstliche Intelligenz (KI)?",
    answers: ["Systeme, die Aufgaben lösen, die normalerweise menschliche Intelligenz erfordern", "Nur Roboter", "Nur Algorithmen", "Nur Datenbanken"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "KI umfasst Lernen, Planen und Problemlösen."
  },
  {
    id: "q10_i_107",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist maschinelles Lernen?",
    answers: ["Verfahren, bei denen Systeme aus Daten lernen, ohne explizit programmiert zu sein", "Nur klassische Programmierung", "Nur Datenbanken", "Nur Netzwerke"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Maschinelles Lernen ist ein Teilgebiet der KI."
  },
  {
    id: "q10_i_108",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein neuronales Netz?",
    answers: ["Ein Modell, das von biologischen Neuronen inspiriert ist und Muster lernt", "Nur ein Computernetzwerk", "Nur eine Datenbank", "Nur ein Algorithmus"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Tiefe neuronale Netze ermöglichen Deep Learning."
  },
  {
    id: "q10_i_109",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Chatbot?",
    answers: ["Ein Programm, das mit Menschen in natürlicher Sprache kommuniziert", "Nur ein Suchalgorithmus", "Nur ein Compiler", "Nur ein Browser"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Chatbots nutzen oft KI-Techniken."
  },
  {
    id: "q10_i_110",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Bias in KI-Systemen?",
    answers: ["Systematische Verzerrungen in den Ergebnissen durch unausgewogene Trainingsdaten", "Nur ein Fehler im Code", "Nur ein Hardwareproblem", "Nur eine langsame Ausführung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Bias kann Diskriminierung verstärken."
  },
  {
    id: "q10_i_111",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Datenschutz?",
    answers: ["Der Schutz personenbezogener Daten vor Missbrauch", "Nur die Verschlüsselung", "Nur die Kompression", "Nur die Speicherung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Datenschutz ist ein Grundrecht."
  },
  {
    id: "q10_i_112",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die DSGVO?",
    answers: ["Die Datenschutz-Grundverordnung der Europäischen Union", "Nur ein deutsches Gesetz", "Nur ein US-Gesetz", "Nur ein Unternehmenskodex"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die DSGVO regelt den Umgang mit personenbezogenen Daten."
  },
  {
    id: "q10_i_113",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was sind personenbezogene Daten?",
    answers: ["Daten, die sich auf eine identifizierte oder identifizierbare Person beziehen", "Nur anonyme Daten", "Nur öffentliche Daten", "Nur Unternehmensdaten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Name, Adresse, IP-Adresse können personenbezogen sein."
  },
  {
    id: "q10_i_114",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Einwilligung im Datenschutz?",
    answers: ["Die freiwillige, informierte Zustimmung zur Verarbeitung personenbezogener Daten", "Nur ein Vertrag", "Nur ein Gesetz", "Nur eine Pflicht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Einwilligung muss widerrufbar sein."
  },
  {
    id: "q10_i_115",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Tracking?",
    answers: ["Das Verfolgen des Nutzerverhaltens im Internet", "Nur das Speichern von Dateien", "Nur das Verschlüsseln", "Nur das Komprimieren"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Cookies und Fingerprinting ermöglichen Tracking."
  },
  {
    id: "q10_i_116",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Cookie?",
    answers: ["Eine kleine Datei, die Websites auf dem Gerät speichern, um Informationen zu behalten", "Nur ein Virus", "Nur ein Programm", "Nur ein Passwort"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Cookies können nützlich oder problematisch sein."
  },
  {
    id: "q10_i_117",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Phishing?",
    answers: ["Der Versuch, durch gefälschte Nachrichten an sensible Daten zu gelangen", "Nur Spam", "Nur Werbung", "Nur ein Virus"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Phishing nutzt oft gefälschte E-Mails oder Webseiten."
  },
  {
    id: "q10_i_118",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein Virus (Computervirus)?",
    answers: ["Schadsoftware, die sich selbst verbreitet und Schaden anrichtet", "Nur ein Programmfehler", "Nur Werbung", "Nur ein Cookie"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Viren benötigen meist ein Wirtsprogramm."
  },
  {
    id: "q10_i_119",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Ransomware?",
    answers: ["Schadsoftware, die Daten verschlüsselt und Lösegeld fordert", "Nur ein Virus", "Nur Spyware", "Nur Adware"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Backups und Vorsicht sind der beste Schutz."
  },
  {
    id: "q10_i_120",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ein starkes Passwort?",
    answers: ["Ein langes, komplexes und einzigartiges Passwort", "Nur ein kurzes Wort", "Nur der eigene Name", "Nur ein Geburtsdatum"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Passwortmanager und Zwei-Faktor-Authentifizierung helfen."
  },
  {
    id: "q10_i_121",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Zwei-Faktor-Authentifizierung (2FA)?",
    answers: ["Ein Sicherheitsverfahren mit zwei unabhängigen Nachweisen der Identität", "Nur ein Passwort", "Nur ein Fingerabdruck", "Nur eine PIN"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "2FA erhöht die Sicherheit erheblich."
  },
  {
    id: "q10_i_122",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Social Engineering?",
    answers: ["Das Ausnutzen menschlicher Schwächen, um an Informationen oder Zugang zu gelangen", "Nur technisches Hacking", "Nur Phishing", "Nur Malware"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Menschen sind oft das schwächste Glied."
  },
  {
    id: "q10_i_123",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist digitale Souveränität?",
    answers: ["Die Fähigkeit, digitale Technologien selbstbestimmt und sicher zu nutzen", "Nur Datenschutz", "Nur Open Source", "Nur Cloud-Nutzung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Digitale Souveränität betrifft Individuen und Staaten."
  },
  {
    id: "q10_i_124",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der digitale Fußabdruck?",
    answers: ["Die Spuren, die man durch digitale Aktivitäten hinterlässt", "Nur Cookies", "Nur Passwörter", "Nur IP-Adressen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Fußabdruck kann schwer löschbar sein."
  },
  {
    id: "q10_i_125",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Fake News?",
    answers: ["Absichtlich falsche oder irreführende Informationen, die als Nachrichten verbreitet werden", "Nur Meinungen", "Nur Satire", "Nur Werbung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Medienkompetenz hilft gegen Fake News."
  },
  {
    id: "q10_i_126",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Deepfake?",
    answers: ["Mit KI erzeugte oder manipulierte Medieninhalte, die real wirken", "Nur ein Video", "Nur ein Bild", "Nur ein Text"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Deepfakes können Desinformation verstärken."
  },
  {
    id: "q10_i_127",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist Algorithmus-Transparenz?",
    answers: ["Die Nachvollziehbarkeit, wie ein Algorithmus zu Entscheidungen kommt", "Nur Open Source", "Nur Dokumentation", "Nur Tests"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Transparenz ist wichtig für Vertrauen und Fairness."
  },
  {
    id: "q10_i_128",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist ethische KI?",
    answers: ["KI-Systeme, die fair, transparent und menschenzentriert entwickelt und eingesetzt werden", "Nur leistungsstarke KI", "Nur Open-Source-KI", "Nur kommerzielle KI"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Ethik in der KI ist ein wachsendes Forschungsfeld."
  },
  {
    id: "q10_i_129",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen starker und schwacher KI?",
    answers: ["Schwache KI: spezialisiert auf Aufgaben, starke KI: allgemeine Menschenähnliche Intelligenz", "Beide sind identisch", "Schwache KI ist immer stark", "Starke KI ist immer schwach"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Heutige Systeme sind schwache KI."
  },
  {
    id: "q10_i_130",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen überwachtem und unüberwachtem Lernen?",
    answers: ["Überwacht: mit gelabelten Daten, unüberwacht: ohne Labels", "Beide sind identisch", "Überwacht ist immer unüberwacht", "Unüberwacht ist immer überwacht"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind zentrale Lernparadigmen."
  },
  {
    id: "q10_i_131",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Datenschutz und Datensicherheit?",
    answers: ["Datenschutz: Schutz der Person, Datensicherheit: Schutz der Daten vor Verlust/Zugriff", "Beide sind identisch", "Datenschutz ist immer Sicherheit", "Sicherheit ist immer Datenschutz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide ergänzen sich."
  },
  {
    id: "q10_i_132",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Anonymisierung und Pseudonymisierung?",
    answers: ["Anonymisierung: nicht rückführbar, Pseudonymisierung: mit Schlüssel rückführbar", "Beide sind identisch", "Anonymisierung ist immer Pseudonymisierung", "Pseudonymisierung ist immer Anonymisierung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind Datenschutzmaßnahmen."
  },
  {
    id: "q10_i_133",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Open Source und proprietärer Software?",
    answers: ["Open Source: Quellcode offen, proprietär: geschlossen und lizenziert", "Beide sind identisch", "Open Source ist immer proprietär", "Proprietär ist immer Open Source"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Modelle haben Vor- und Nachteile."
  },
  {
    id: "q10_i_134",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Client und Server?",
    answers: ["Client fordert an, Server stellt bereit", "Beide sind identisch", "Client ist immer Server", "Server ist immer Client"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Client-Server-Modell ist grundlegend."
  },
  {
    id: "q10_i_135",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen LAN und WAN?",
    answers: ["LAN: lokal, WAN: über große Entfernungen", "Beide sind identisch", "LAN ist immer WAN", "WAN ist immer LAN"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Internet ist ein WAN."
  },
  {
    id: "q10_i_136",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Hardware und Software?",
    answers: ["Hardware: physische Komponenten, Software: Programme und Daten", "Beide sind identisch", "Hardware ist immer Software", "Software ist immer Hardware"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind notwendig für funktionierende Systeme."
  },
  {
    id: "q10_i_137",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Frontend und Backend?",
    answers: ["Frontend: Benutzeroberfläche, Backend: serverseitige Logik und Daten", "Beide sind identisch", "Frontend ist immer Backend", "Backend ist immer Frontend"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Webanwendungen trennen oft beide Schichten."
  },
  {
    id: "q10_i_138",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen synchroner und asynchroner Kommunikation?",
    answers: ["Synchron: gleichzeitig, asynchron: zeitversetzt", "Beide sind identisch", "Synchron ist immer asynchron", "Asynchron ist immer synchron"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "E-Mail ist asynchron, Chat oft synchron."
  },
  {
    id: "q10_i_139",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen zentraler und dezentraler Architektur?",
    answers: ["Zentral: eine zentrale Instanz, dezentral: verteilte Verantwortung", "Beide sind identisch", "Zentral ist immer dezentral", "Dezentral ist immer zentral"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Blockchain ist ein Beispiel für dezentral."
  },
  {
    id: "q10_i_140",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Authentifizierung und Autorisierung?",
    answers: ["Authentifizierung: Identität prüfen, Autorisierung: Rechte prüfen", "Beide sind identisch", "Authentifizierung ist immer Autorisierung", "Autorisierung ist immer Authentifizierung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Beide sind Sicherheitsmechanismen."
  },
  {
    id: "q10_i_141",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Verschlüsselung und Hashing?",
    answers: ["Verschlüsselung: umkehrbar, Hashing: praktisch nicht umkehrbar", "Beide sind identisch", "Verschlüsselung ist immer Hashing", "Hashing ist immer Verschlüsselung"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Passwörter werden gehasht, nicht verschlüsselt gespeichert."
  },
  {
    id: "q10_i_142",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen privater und öffentlicher Cloud?",
    answers: ["Privat: eigene Infrastruktur, öffentlich: geteilte Dienste eines Anbieters", "Beide sind identisch", "Privat ist immer öffentlich", "Öffentlich ist immer privat"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Hybride Modelle kombinieren beide."
  },
  {
    id: "q10_i_143",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Edge Computing und Cloud Computing?",
    answers: ["Edge: Verarbeitung nah am Gerät, Cloud: zentral in Rechenzentren", "Beide sind identisch", "Edge ist immer Cloud", "Cloud ist immer Edge"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Edge reduziert Latenz und Bandbreitenbedarf."
  },
  {
    id: "q10_i_144",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Supervised und Reinforcement Learning?",
    answers: ["Supervised: mit Labels, Reinforcement: Lernen durch Belohnung und Bestrafung", "Beide sind identisch", "Supervised ist immer Reinforcement", "Reinforcement ist immer Supervised"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Reinforcement Learning wird z. B. bei Spielen und Robotik genutzt."
  },
  {
    id: "q10_i_145",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Black-Box und erklärbarer KI?",
    answers: ["Black-Box: undurchsichtig, erklärbar: nachvollziehbare Entscheidungen", "Beide sind identisch", "Black-Box ist immer erklärbar", "Erklärbar ist immer Black-Box"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Erklärbarkeit ist wichtig für Vertrauen und Recht."
  },
  {
    id: "q10_i_146",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen Datensparsamkeit und Datenmaximierung?",
    answers: ["Datensparsamkeit: nur notwendige Daten, Maximierung: möglichst viele Daten", "Beide sind identisch", "Sparsamkeit ist immer Maximierung", "Maximierung ist immer Sparsamkeit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Datensparsamkeit ist ein DSGVO-Prinzip."
  },
  {
    id: "q10_i_147",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen IT-Sicherheit und Cybersicherheit?",
    answers: ["Cybersicherheit betont den Schutz vernetzter Systeme und des digitalen Raums", "Beide sind identisch", "IT-Sicherheit ist immer Cyber", "Cyber ist immer IT"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Die Begriffe überschneiden sich stark."
  },
  {
    id: "q10_i_148",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen digitaler Kompetenz und Medienkompetenz?",
    answers: ["Digitale Kompetenz: technische Fähigkeiten, Medienkompetenz: kritisches Nutzen von Medien", "Beide sind identisch", "Digitale ist immer Medien", "Medien ist immer digital"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide sind eng verwandt und ergänzen sich."
  },
  {
    id: "q10_i_149",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist der Unterschied zwischen ethischer und rechtlicher Verantwortung in der Informatik?",
    answers: ["Ethisch: moralische Prinzipien, rechtlich: gesetzliche Vorschriften", "Beide sind identisch", "Ethisch ist immer rechtlich", "Rechtlich ist immer ethisch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Beide Ebenen sind für Entwickler und Nutzer relevant."
  },
  {
    id: "q10_i_150",
    category: "k10_informatik",
    topic: "ki_gesellschaft",
    area: "schule",
    grade: 10,
    subject: "informatik",
    question: "Was ist die zentrale Aufgabe der Informatik in der Gesellschaft?",
    answers: ["Digitale Systeme verantwortungsvoll zu gestalten und kritisch zu hinterfragen", "Nur Programme zu schreiben", "Nur Hardware zu bauen", "Nur Daten zu sammeln"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Informatikbildung fördert Mündigkeit in der digitalen Welt."
  }
];
