const K10_ENGLISCH_QUESTIONS = [
  // ================================================================
  // 1. GRAMMAR – TENSES (25 Fragen)
  // ================================================================
  {
    id: "q10_e_001",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which tense is used for actions that started in the past and continue to the present?",
    answers: ["Present Perfect", "Simple Past", "Past Perfect", "Present Continuous"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Present Perfect (have/has + past participle) connects past and present."
  },
  {
    id: "q10_e_002",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence is correct?",
    answers: ["I have lived here for five years.", "I live here for five years.", "I am living here for five years.", "I lived here for five years."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Present Perfect with 'for' for duration up to now."
  },
  {
    id: "q10_e_003",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "When do we use the Past Perfect?",
    answers: ["For an action completed before another past action", "For habits in the present", "For future plans", "For general truths"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Past Perfect (had + past participle) shows the earlier of two past events."
  },
  {
    id: "q10_e_004",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which is the correct form of the Future with 'will'?",
    answers: ["She will help you tomorrow.", "She helps you tomorrow.", "She is help you tomorrow.", "She helped you tomorrow."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Will + infinitive for spontaneous decisions or predictions."
  },
  {
    id: "q10_e_005",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which tense is typical for planned future arrangements?",
    answers: ["Present Continuous", "Simple Present", "Past Perfect", "Present Perfect"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "I'm meeting him at 5 o'clock – fixed plan."
  },
  {
    id: "q10_e_006",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'By the time we arrived, the film ___.'",
    answers: ["had already started", "has already started", "already starts", "was already start"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Past Perfect for the earlier action."
  },
  {
    id: "q10_e_007",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which signal word often goes with the Present Perfect?",
    answers: ["already / yet / just / ever", "yesterday / last week", "tomorrow / next year", "while / when"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Typical Present Perfect markers."
  },
  {
    id: "q10_e_008",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence uses the correct tense for a finished past action?",
    answers: ["She finished her homework an hour ago.", "She has finished her homework an hour ago.", "She finishes her homework an hour ago.", "She is finishing her homework an hour ago."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Simple Past with a definite past time."
  },
  {
    id: "q10_e_009",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the Present Perfect Continuous used for?",
    answers: ["Actions that started in the past and are still continuing or have just stopped", "Completed actions with a result", "Habits in the past", "Future predictions"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "have/has been + -ing form."
  },
  {
    id: "q10_e_010",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'I ___ English for six years.'",
    answers: ["have been learning", "am learning", "learn", "learned"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Present Perfect Continuous for duration."
  },
  {
    id: "q10_e_011",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which form is used after 'while' for simultaneous past actions?",
    answers: ["Past Continuous", "Simple Past", "Present Perfect", "Future"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "While I was reading, she was cooking."
  },
  {
    id: "q10_e_012",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence is correct?",
    answers: ["If it rains, we will stay at home.", "If it will rain, we stay at home.", "If it rains, we stayed at home.", "If it rain, we will stay."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "First Conditional: If + Present, will + infinitive."
  },
  {
    id: "q10_e_013",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the structure of the Second Conditional?",
    answers: ["If + Past Simple, would + infinitive", "If + Present, will + infinitive", "If + Past Perfect, would have + past participle", "If + Present Perfect, will + infinitive"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Unreal or hypothetical present/future situations."
  },
  {
    id: "q10_e_014",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'If I ___ rich, I would travel the world.'",
    answers: ["were", "am", "was being", "will be"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Second Conditional – 'were' is common for all persons."
  },
  {
    id: "q10_e_015",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which tense is used in the if-clause of the Third Conditional?",
    answers: ["Past Perfect", "Simple Past", "Present Perfect", "Present Simple"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "If + Past Perfect, would have + past participle."
  },
  {
    id: "q10_e_016",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'If she had studied harder, she ___ the exam.'",
    answers: ["would have passed", "would pass", "will pass", "passed"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Third Conditional for unreal past."
  },
  {
    id: "q10_e_017",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence shows a habitual past action?",
    answers: ["When I was young, I used to play football every day.", "I am playing football every day.", "I have played football every day.", "I will play football every day."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Used to' expresses past habits."
  },
  {
    id: "q10_e_018",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the difference between 'will' and 'going to'?",
    answers: ["'Going to' is often for premeditated plans, 'will' for spontaneous decisions", "There is no difference", "'Will' is only for the past", "'Going to' is only for questions"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Both can express future, but usage differs."
  },
  {
    id: "q10_e_019",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which form is correct after 'since'?",
    answers: ["Present Perfect", "Simple Past", "Present Continuous", "Past Perfect"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "I have known her since 2018."
  },
  {
    id: "q10_e_020",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'Look at those clouds! It ___ rain.'",
    answers: ["is going to", "will", "rains", "rained"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Evidence in the present → going to."
  },
  {
    id: "q10_e_021",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which tense is used for general truths?",
    answers: ["Simple Present", "Present Continuous", "Present Perfect", "Past Perfect"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Water boils at 100 °C."
  },
  {
    id: "q10_e_022",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the Past Continuous used for?",
    answers: ["An action in progress at a specific time in the past", "A completed past action", "A future plan", "A general truth"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "I was reading at 8 o'clock."
  },
  {
    id: "q10_e_023",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'She ___ to London three times this year.'",
    answers: ["has been", "was", "is", "goes"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Present Perfect for experiences in an unfinished time period."
  },
  {
    id: "q10_e_024",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence is in the Future Perfect?",
    answers: ["By next year I will have finished school.", "I will finish school next year.", "I am finishing school next year.", "I finished school next year."],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "will have + past participle – completed before a future point."
  },
  {
    id: "q10_e_025",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'I have just finished' mean?",
    answers: ["The action was completed a very short time ago", "The action is still going on", "The action will happen soon", "The action happened long ago"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Just' with Present Perfect indicates a recent completion."
  },

  // ================================================================
  // 2. GRAMMAR – PASSIVE, RELATIVE CLAUSES, REPORTED SPEECH (25 Fragen)
  // ================================================================
  {
    id: "q10_e_026",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "How is the passive voice formed in the Simple Present?",
    answers: ["am/is/are + past participle", "have/has + past participle", "was/were + past participle", "will + past participle"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "The letter is written every day."
  },
  {
    id: "q10_e_027",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to passive: 'They built this house in 1990.'",
    answers: ["This house was built in 1990.", "This house is built in 1990.", "This house has been built in 1990.", "This house will be built in 1990."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Simple Past passive: was/were + past participle."
  },
  {
    id: "q10_e_028",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which relative pronoun is used for people?",
    answers: ["who / that", "which / that", "whose", "where"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Who refers to people, which to things."
  },
  {
    id: "q10_e_029",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'The book ___ I bought yesterday is interesting.'",
    answers: ["which / that", "who", "whose", "where"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Which/that for things."
  },
  {
    id: "q10_e_030",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a defining relative clause?",
    answers: ["A clause that is necessary to identify the noun", "A clause that only gives extra information", "A clause without a verb", "A main clause"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Defining clauses are essential and usually without commas."
  },
  {
    id: "q10_e_031",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to reported speech: 'I am tired,' she said.",
    answers: ["She said (that) she was tired.", "She said (that) she is tired.", "She said (that) I am tired.", "She said (that) she will be tired."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Present → Past in reported speech."
  },
  {
    id: "q10_e_032",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to reported speech: 'I will call you tomorrow,' he said.",
    answers: ["He said (that) he would call me the next day.", "He said (that) he will call me tomorrow.", "He said (that) he calls me tomorrow.", "He said (that) he called me tomorrow."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "will → would; tomorrow → the next day."
  },
  {
    id: "q10_e_033",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb form follows 'suggest'?",
    answers: ["suggest + -ing / suggest that + subject + should", "suggest + infinitive with to", "suggest + bare infinitive", "suggest + past participle"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "I suggest going / I suggest that we should go."
  },
  {
    id: "q10_e_034",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'The man ___ car was stolen is very angry.'",
    answers: ["whose", "who", "which", "that"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Whose expresses possession."
  },
  {
    id: "q10_e_035",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "How is the passive formed in the Present Perfect?",
    answers: ["have/has been + past participle", "have/has + past participle", "was/were + past participle", "is/are being + past participle"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "The work has been done."
  },
  {
    id: "q10_e_036",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to passive: 'Someone has stolen my bike.'",
    answers: ["My bike has been stolen.", "My bike was stolen.", "My bike is stolen.", "My bike will be stolen."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Present Perfect passive."
  },
  {
    id: "q10_e_037",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which relative pronoun can be omitted in defining clauses?",
    answers: ["who/which/that when it is the object", "who when it is the subject", "whose always", "where always"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "The book (that) I read was great."
  },
  {
    id: "q10_e_038",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to reported speech: 'Where do you live?' she asked me.",
    answers: ["She asked me where I lived.", "She asked me where do I live.", "She asked me where I live.", "She asked me where did I live."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Word order changes; tense shifts back."
  },
  {
    id: "q10_e_039",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the passive of 'They are repairing the road'?",
    answers: ["The road is being repaired.", "The road is repaired.", "The road has been repaired.", "The road was repaired."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Present Continuous passive: is/are being + past participle."
  },
  {
    id: "q10_e_040",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'This is the school ___ I went as a child.'",
    answers: ["where / that", "who", "whose", "which"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Where for places (or that/which in some cases)."
  },
  {
    id: "q10_e_041",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence is a non-defining relative clause?",
    answers: ["My brother, who lives in London, is a doctor.", "The man who lives next door is a doctor.", "The book that I bought is interesting.", "People who work hard succeed."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Non-defining clauses give extra information and use commas."
  },
  {
    id: "q10_e_042",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to reported speech: 'Don't open the window,' he said.",
    answers: ["He told me not to open the window.", "He said me not open the window.", "He told me don't open the window.", "He said not open the window."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Negative imperative → told + not to + infinitive."
  },
  {
    id: "q10_e_043",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What follows 'look forward to'?",
    answers: ["the -ing form", "the infinitive with to", "the bare infinitive", "the past participle"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "look forward to meeting you."
  },
  {
    id: "q10_e_044",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'She is interested ___ learning languages.'",
    answers: ["in", "on", "at", "for"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "interested in + -ing."
  },
  {
    id: "q10_e_045",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which structure is used after 'It's worth'?",
    answers: ["-ing form", "infinitive with to", "bare infinitive", "past participle"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "It's worth reading this book."
  },
  {
    id: "q10_e_046",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Change to passive: 'People speak English all over the world.'",
    answers: ["English is spoken all over the world.", "English was spoken all over the world.", "English has been spoken all over the world.", "English is being spoken all over the world."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Simple Present passive for general facts."
  },
  {
    id: "q10_e_047",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the correct reported form of 'Can you help me?'?",
    answers: ["He asked if I could help him.", "He asked can I help him.", "He asked if I can help him.", "He asked me help him."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "can → could; question word order changes."
  },
  {
    id: "q10_e_048",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which relative pronoun is used for possession?",
    answers: ["whose", "who", "which", "that"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Whose works for people and things."
  },
  {
    id: "q10_e_049",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'The film ___ we saw last night was boring.'",
    answers: ["which / that", "who", "whose", "where"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Object relative pronoun for things."
  },
  {
    id: "q10_e_050",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the passive of 'They will open the new museum next month'?",
    answers: ["The new museum will be opened next month.", "The new museum is opened next month.", "The new museum has been opened next month.", "The new museum was opened next month."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "will be + past participle."
  },

  // ================================================================
  // 3. VOCABULARY & TOPICS (identity, community, change, environment) (30 Fragen)
  // ================================================================
  {
    id: "q10_e_051",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'identity' mainly refer to?",
    answers: ["Who a person is and how they see themselves", "Only a passport number", "Only physical appearance", "Only nationality"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Identity includes personal, social and cultural aspects."
  },
  {
    id: "q10_e_052",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'a group of people living in the same place or sharing interests'?",
    answers: ["community", "competition", "condition", "conclusion"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Community is a key topic in year 10."
  },
  {
    id: "q10_e_053",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the opposite of 'include'?",
    answers: ["exclude", "invite", "involve", "increase"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Exclude means to leave out."
  },
  {
    id: "q10_e_054",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb means 'to make something continue'?",
    answers: ["maintain", "destroy", "ignore", "abandon"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Maintain relationships / maintain peace."
  },
  {
    id: "q10_e_055",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'sustainable' mean?",
    answers: ["Able to continue without damaging the environment", "Very expensive", "Only temporary", "Completely artificial"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Sustainable development is a key environmental term."
  },
  {
    id: "q10_e_056",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'the state of being equal'?",
    answers: ["equality", "quality", "quantity", "identity"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Equality between people / gender equality."
  },
  {
    id: "q10_e_057",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a 'stereotype'?",
    answers: ["An oversimplified and fixed idea about a group of people", "A scientific fact", "A personal opinion based on research", "A legal document"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Stereotypes can be harmful and inaccurate."
  },
  {
    id: "q10_e_058",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective means 'open to new ideas and opinions'?",
    answers: ["open-minded", "narrow-minded", "absent-minded", "single-minded"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Open-minded people accept different views."
  },
  {
    id: "q10_e_059",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'diversity' mean?",
    answers: ["Variety and difference within a group", "Complete sameness", "Only one culture", "Isolation"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Cultural diversity is often discussed in class 10."
  },
  {
    id: "q10_e_060",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb means 'to take part in something'?",
    answers: ["participate / get involved", "exclude", "ignore", "avoid"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Participate in a discussion / get involved in the community."
  },
  {
    id: "q10_e_061",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'climate change'?",
    answers: ["Long-term change in global temperatures and weather patterns", "Only daily weather", "A short storm", "A local temperature rise"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "A major topic connected to environment and the future."
  },
  {
    id: "q10_e_062",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'the right to vote'?",
    answers: ["suffrage / the right to vote", "silence", "suffering", "success"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Universal suffrage is an important historical and political term."
  },
  {
    id: "q10_e_063",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'empathy' mean?",
    answers: ["The ability to understand and share another person's feelings", "Complete indifference", "Strong dislike", "Only intellectual understanding"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Empathy is important in intercultural communication."
  },
  {
    id: "q10_e_064",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective describes something that can be used again?",
    answers: ["reusable / recyclable", "disposable", "single-use", "temporary"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Reusable bags help the environment."
  },
  {
    id: "q10_e_065",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a 'role model'?",
    answers: ["A person whose behaviour is copied by others", "A fashion model only", "A teacher only", "A fictional character only"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Young people often look for positive role models."
  },
  {
    id: "q10_e_066",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb means 'to make people feel that they belong'?",
    answers: ["include / integrate", "exclude", "isolate", "reject"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Inclusive communities integrate different people."
  },
  {
    id: "q10_e_067",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'prejudice' mean?",
    answers: ["An unfair opinion formed without enough knowledge", "A scientific theory", "A legal decision", "A personal preference based on facts"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Prejudice can lead to discrimination."
  },
  {
    id: "q10_e_068",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'the process of becoming part of a group'?",
    answers: ["integration", "isolation", "separation", "exclusion"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Social integration is a common topic."
  },
  {
    id: "q10_e_069",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'globalisation'?",
    answers: ["The process of increasing worldwide connection and interdependence", "Only local trade", "A return to national isolation", "A weather phenomenon"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Globalisation affects economy, culture and environment."
  },
  {
    id: "q10_e_070",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective means 'harmful to the environment'?",
    answers: ["polluting / environmentally damaging", "sustainable", "eco-friendly", "green"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Polluting industries damage the planet."
  },
  {
    id: "q10_e_071",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'volunteer' mean?",
    answers: ["A person who works without being paid", "A professional employee", "A paid expert", "A company manager"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Volunteers help in the community."
  },
  {
    id: "q10_e_072",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase means 'to express your opinion clearly'?",
    answers: ["to speak your mind / to voice your opinion", "to keep quiet", "to change the subject", "to ignore the topic"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Useful for discussions and opinion pieces."
  },
  {
    id: "q10_e_073",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'discrimination'?",
    answers: ["Unfair treatment of people based on group membership", "Fair and equal treatment", "A scientific method", "A type of friendship"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Discrimination is a central social issue."
  },
  {
    id: "q10_e_074",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'the ability to recover from difficulties'?",
    answers: ["resilience", "weakness", "dependence", "isolation"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Personal and community resilience."
  },
  {
    id: "q10_e_075",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'carbon footprint' refer to?",
    answers: ["The amount of greenhouse gases produced by an activity", "The size of a shoe", "A type of pollution filter", "A measurement of rain"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Reducing your carbon footprint helps the climate."
  },
  {
    id: "q10_e_076",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb means 'to make something available to everyone'?",
    answers: ["provide / give access to", "restrict", "hide", "deny"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Provide equal opportunities."
  },
  {
    id: "q10_e_077",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'peer pressure'?",
    answers: ["Influence from people of the same age group", "Pressure from parents only", "Pressure from teachers only", "A medical condition"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Peer pressure can be positive or negative."
  },
  {
    id: "q10_e_078",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective means 'able to be trusted'?",
    answers: ["reliable / trustworthy", "unreliable", "doubtful", "suspicious"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "A reliable friend / a trustworthy source."
  },
  {
    id: "q10_e_079",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'raise awareness' mean?",
    answers: ["To make people know more about an issue", "To ignore a problem", "To hide information", "To solve a problem immediately"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Campaigns raise awareness of social and environmental issues."
  },
  {
    id: "q10_e_080",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'the way people live and the values they share'?",
    answers: ["culture", "nature", "structure", "temperature"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Culture includes traditions, language and behaviour."
  },

  // ================================================================
  // 4. SKILLS – READING, WRITING, MEDIATION, DISCUSSION (30 Fragen)
  // ================================================================
  {
    id: "q10_e_081",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the main purpose of an opinion piece?",
    answers: ["To express and justify a personal view", "To only report facts without opinion", "To tell a fictional story", "To give step-by-step instructions"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Opinion pieces present arguments for a standpoint."
  },
  {
    id: "q10_e_082",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What should a good introduction of an opinion text do?",
    answers: ["Present the topic and the writer's position", "Only list arguments", "Only conclude", "Only give examples"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "The introduction leads into the topic and thesis."
  },
  {
    id: "q10_e_083",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'mediation' in the foreign language classroom?",
    answers: ["Transferring information from one language/context to another", "Only translating word for word", "Only speaking freely", "Only listening"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mediation is a key competence: summarise, explain, adapt."
  },
  {
    id: "q10_e_084",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which strategy helps when reading a difficult text?",
    answers: ["Skimming for main ideas and scanning for details", "Reading every word aloud only", "Ignoring unknown words completely", "Translating every single word first"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Skimming and scanning are efficient reading strategies."
  },
  {
    id: "q10_e_085",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a useful phrase to introduce a counter-argument?",
    answers: ["On the other hand / However / Critics argue that…", "In conclusion", "First of all", "For example"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "These phrases signal the opposite view."
  },
  {
    id: "q10_e_086",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What should you do in a panel discussion?",
    answers: ["Listen actively, take turns and support or challenge ideas politely", "Only speak and never listen", "Interrupt constantly", "Stay completely silent"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Good discussion skills include turn-taking and respect."
  },
  {
    id: "q10_e_087",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase is useful to summarise a text?",
    answers: ["In short / To sum up / The main point is…", "In my opinion", "I disagree", "For instance"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Summarising phrases help structure mediation and reviews."
  },
  {
    id: "q10_e_088",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the difference between formal and informal language?",
    answers: ["Formal language avoids slang and contractions; informal is more casual", "There is no difference", "Formal language uses only slang", "Informal language is only written"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Register depends on audience and situation."
  },
  {
    id: "q10_e_089",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a good way to structure an opinion essay?",
    answers: ["Introduction – arguments for/against – conclusion", "Only a long list of examples", "Only a conclusion", "Random paragraphs"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Clear structure makes the text coherent."
  },
  {
    id: "q10_e_090",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase can you use to agree partially?",
    answers: ["I see your point, but… / I agree to some extent…", "I completely disagree", "You are wrong", "I have no opinion"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Partial agreement is useful in discussions."
  },
  {
    id: "q10_e_091",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'skim' a text mean?",
    answers: ["Read quickly to get the general idea", "Read every word carefully", "Only look at the pictures", "Translate the whole text"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Skimming gives an overview."
  },
  {
    id: "q10_e_092",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'scan' a text mean?",
    answers: ["Look quickly for specific information", "Read slowly for detail", "Ignore the text", "Write a summary first"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Scanning finds particular details (dates, names, numbers)."
  },
  {
    id: "q10_e_093",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which linking word shows contrast?",
    answers: ["however / although / whereas", "therefore / so", "furthermore / moreover", "for example"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Contrast linkers are essential in argumentative texts."
  },
  {
    id: "q10_e_094",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the purpose of a conclusion in an opinion text?",
    answers: ["To summarise the main points and restate the opinion", "To introduce new arguments", "To only give examples", "To ask questions only"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "The conclusion rounds off the text."
  },
  {
    id: "q10_e_095",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase is useful when mediating a German text into English?",
    answers: ["The text says that… / According to the author…", "I invent the content", "I ignore difficult parts", "I only translate word for word"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mediation requires clear reference to the source."
  },
  {
    id: "q10_e_096",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What should you avoid in a formal email?",
    answers: ["Slang, contractions and overly emotional language", "Clear structure", "Polite forms", "A subject line"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Formal style requires appropriate register."
  },
  {
    id: "q10_e_097",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase helps to give an example?",
    answers: ["For instance / For example / Such as", "In contrast", "In conclusion", "On the other hand"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Examples support arguments."
  },
  {
    id: "q10_e_098",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is important when taking part in a discussion?",
    answers: ["Support your points with reasons and listen to others", "Only repeat your opinion", "Interrupt others", "Speak as fast as possible"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Good discussion = reasons + interaction."
  },
  {
    id: "q10_e_099",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which strategy helps with unknown words while reading?",
    answers: ["Use context clues and word formation", "Always stop and look up every word", "Skip the whole paragraph", "Guess randomly without context"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Context and morphology help comprehension."
  },
  {
    id: "q10_e_100",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a useful phrase to conclude a discussion contribution?",
    answers: ["So, to sum up my point… / That’s why I believe…", "I don’t know", "Whatever", "Let’s change the topic"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Clear closing makes the contribution stronger."
  },

  // ================================================================
  // 5. CULTURE & FURTHER GRAMMAR / VOCAB (50 Fragen – Erweiterung)
  // ================================================================
  {
    id: "q10_e_101",
    category: "k10_englisch",
    topic: "culture",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which country is often a reference culture besides the UK in class 10?",
    answers: ["New Zealand / USA / Australia (depending on materials)", "Only France", "Only Germany", "Only Japan"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Anglophone cultures beyond Britain are part of the curriculum."
  },
  {
    id: "q10_e_102",
    category: "k10_englisch",
    topic: "culture",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the capital of New Zealand?",
    answers: ["Wellington", "Auckland", "Sydney", "Christchurch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wellington is the capital; Auckland is the largest city."
  },
  {
    id: "q10_e_103",
    category: "k10_englisch",
    topic: "culture",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the official language of the UK?",
    answers: ["English (with regional varieties)", "Only French", "Only German", "Only Welsh"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "English is the main language; Welsh, Scottish Gaelic etc. also exist."
  },
  {
    id: "q10_e_104",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which form is correct after 'I would rather'?",
    answers: ["I would rather stay at home.", "I would rather to stay at home.", "I would rather staying at home.", "I would rather stayed at home."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "would rather + bare infinitive."
  },
  {
    id: "q10_e_105",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'She is used ___ getting up early.'",
    answers: ["to", "for", "with", "at"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "be used to + -ing / noun."
  },
  {
    id: "q10_e_106",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the difference between 'used to' and 'be used to'?",
    answers: ["'Used to' = past habit; 'be used to' = be accustomed to", "They mean the same", "'Used to' is only for the future", "'Be used to' is only for the past"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Different meanings and structures."
  },
  {
    id: "q10_e_107",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'It’s time we ___ home.'",
    answers: ["went", "go", "are going", "have gone"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "It's time + past tense (unreal)."
  },
  {
    id: "q10_e_108",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb is followed by the infinitive with 'to'?",
    answers: ["decide / hope / want / plan", "enjoy / finish / avoid / suggest", "make / let / help (sometimes)", "look forward to"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Many verbs of intention take to-infinitive."
  },
  {
    id: "q10_e_109",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb is usually followed by the -ing form?",
    answers: ["enjoy / finish / avoid / suggest / mind", "want / hope / decide / plan", "can / must / should", "will / shall"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Certain verbs require gerund."
  },
  {
    id: "q10_e_110",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'take action' mean?",
    answers: ["To do something in order to achieve a goal", "To take a photo", "To take a break", "To take a seat"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Take action against climate change."
  },
  {
    id: "q10_e_111",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase means 'to have a positive effect'?",
    answers: ["to make a difference", "to make a mistake", "to make a noise", "to make a mess"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Small actions can make a difference."
  },
  {
    id: "q10_e_112",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the meaning of 'challenge' as a noun?",
    answers: ["A difficult task that tests ability", "An easy task", "A type of food", "A holiday"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Facing challenges is part of personal growth."
  },
  {
    id: "q10_e_113",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective means 'connected with the present time'?",
    answers: ["current / contemporary", "ancient", "future", "outdated"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Current issues / contemporary culture."
  },
  {
    id: "q10_e_114",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'impact' mean?",
    answers: ["A strong effect or influence", "A light touch", "A type of sport", "A small change"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "The impact of technology on society."
  },
  {
    id: "q10_e_115",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which verb means 'to deal successfully with a problem'?",
    answers: ["cope with / manage", "ignore", "create", "worsen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Cope with stress / manage difficulties."
  },
  {
    id: "q10_e_116",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'This is the first time I ___ sushi.'",
    answers: ["have eaten", "ate", "am eating", "eat"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Present Perfect with 'the first time'."
  },
  {
    id: "q10_e_117",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence is correct?",
    answers: ["I wish I had more time.", "I wish I have more time.", "I wish I will have more time.", "I wish I am having more time."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "I wish + Past Simple for present unreal wishes."
  },
  {
    id: "q10_e_118",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'I wish I ___ harder for the exam.'",
    answers: ["had studied", "studied", "study", "will study"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "I wish + Past Perfect for past regrets."
  },
  {
    id: "q10_e_119",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is a defining relative clause essential for?",
    answers: ["Identifying which person or thing we mean", "Only giving extra information", "Replacing the main clause", "Making the sentence longer"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Without it the meaning is unclear."
  },
  {
    id: "q10_e_120",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence contains a non-defining relative clause?",
    answers: ["London, which is the capital of England, is a big city.", "The city which I visited was interesting.", "People who exercise stay healthy.", "The book that she wrote is popular."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Extra information, set off by commas."
  },
  {
    id: "q10_e_121",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the best way to start a formal letter?",
    answers: ["Dear Sir or Madam / Dear Mr Smith", "Hi there", "Hey", "Hello friend"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Formal openings are required in official correspondence."
  },
  {
    id: "q10_e_122",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "How do you end a formal letter if you don’t know the name?",
    answers: ["Yours faithfully", "Yours sincerely", "Best wishes", "Cheers"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Yours faithfully when the name is unknown."
  },
  {
    id: "q10_e_123",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'register' in language use?",
    answers: ["The level of formality appropriate to the situation", "Only vocabulary lists", "Only grammar rules", "Only pronunciation"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Choosing the right register is a key competence."
  },
  {
    id: "q10_e_124",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'a person who flees their country'?",
    answers: ["refugee", "tourist", "resident", "citizen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Refugees seek safety from danger or persecution."
  },
  {
    id: "q10_e_125",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'migration' mean?",
    answers: ["Movement of people from one place to another", "Only holiday travel", "Only animal movement", "A type of weather"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Migration can be voluntary or forced."
  },
  {
    id: "q10_e_126",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective means 'showing kindness and concern'?",
    answers: ["caring / compassionate", "indifferent", "cruel", "selfish"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "A caring community supports its members."
  },
  {
    id: "q10_e_127",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'digital literacy'?",
    answers: ["The ability to use digital tools critically and effectively", "Only typing speed", "Only playing games", "Only watching videos"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Digital literacy includes evaluation of online information."
  },
  {
    id: "q10_e_128",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase means 'to think carefully about something'?",
    answers: ["to reflect on / to consider", "to ignore", "to forget", "to rush"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Reflect on your experiences."
  },
  {
    id: "q10_e_129",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is important when writing a summary?",
    answers: ["Use your own words and keep the main points", "Copy whole sentences", "Add many personal opinions", "Make it longer than the original"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "A summary is concise and objective."
  },
  {
    id: "q10_e_130",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase introduces a result?",
    answers: ["As a result / Therefore / Consequently", "Although / However", "For example", "In addition"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Result linkers show cause-effect."
  },
  {
    id: "q10_e_131",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'She asked me ___ I had finished.'",
    answers: ["if / whether", "that", "what", "which"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Yes/no questions in reported speech use if/whether."
  },
  {
    id: "q10_e_132",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the passive of 'Someone is cleaning the windows'?",
    answers: ["The windows are being cleaned.", "The windows are cleaned.", "The windows have been cleaned.", "The windows were cleaned."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Present Continuous passive."
  },
  {
    id: "q10_e_133",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which relative clause needs commas?",
    answers: ["Non-defining relative clauses", "Defining relative clauses", "All relative clauses", "No relative clauses"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Extra information is set off by commas."
  },
  {
    id: "q10_e_134",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'empower' mean?",
    answers: ["To give someone the power or confidence to do something", "To take power away", "To ignore someone", "To criticise someone"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Education can empower people."
  },
  {
    id: "q10_e_135",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'the state of being free from danger'?",
    answers: ["safety / security", "risk", "threat", "danger"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Safety is a basic need."
  },
  {
    id: "q10_e_136",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is 'social media' mainly used for?",
    answers: ["Sharing information and connecting with others online", "Only writing books", "Only watching TV", "Only face-to-face meetings"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Social media is a central topic of digital communication."
  },
  {
    id: "q10_e_137",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the best attitude in intercultural encounters?",
    answers: ["Open-mindedness and respect for difference", "Assuming your culture is superior", "Avoiding all contact", "Ignoring differences"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Intercultural competence requires openness."
  },
  {
    id: "q10_e_138",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase is useful to ask for clarification?",
    answers: ["Could you explain that again? / What do you mean by…?", "I don’t care", "Whatever", "You are wrong"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Clarification keeps communication clear."
  },
  {
    id: "q10_e_139",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'By the end of this year I ___ my exams.'",
    answers: ["will have finished", "will finish", "finish", "have finished"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "Future Perfect – completed before a future time."
  },
  {
    id: "q10_e_140",
    category: "k10_englisch",
    topic: "grammar_tenses",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which sentence is in the Present Perfect Continuous?",
    answers: ["She has been working here for three years.", "She has worked here for three years.", "She is working here for three years.", "She worked here for three years."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "has/have been + -ing emphasises duration."
  },
  {
    id: "q10_e_141",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'advocate for' mean?",
    answers: ["To publicly support a cause", "To oppose a cause", "To ignore a cause", "To study a cause only"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Advocate for equal rights."
  },
  {
    id: "q10_e_142",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which word means 'a detailed examination'?",
    answers: ["analysis", "summary", "opinion", "story"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Text analysis is a core skill."
  },
  {
    id: "q10_e_143",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the goal of a panel discussion in class?",
    answers: ["To exchange views on a topic in a structured way", "To only read a text aloud", "To write a silent essay", "To take a vocabulary test"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Panel discussions practise speaking and argumentation."
  },
  {
    id: "q10_e_144",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which phrase is useful to disagree politely?",
    answers: ["I see what you mean, but I think… / I’m not sure I agree…", "You are completely wrong", "That’s stupid", "No way"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Polite disagreement keeps the discussion constructive."
  },
  {
    id: "q10_e_145",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What does 'opportunity' mean?",
    answers: ["A chance to do something positive", "A problem", "A restriction", "A failure"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Equal opportunities are an important social goal."
  },
  {
    id: "q10_e_146",
    category: "k10_englisch",
    topic: "vocabulary",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which adjective means 'lasting for a long time'?",
    answers: ["long-term / lasting", "short-term", "temporary", "brief"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Long-term solutions are needed for climate issues."
  },
  {
    id: "q10_e_147",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Complete: 'I prefer reading ___ watching TV.'",
    answers: ["to", "than", "as", "for"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "prefer A to B."
  },
  {
    id: "q10_e_148",
    category: "k10_englisch",
    topic: "grammar_structures",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which form is correct: 'She suggested ___ a break.'?",
    answers: ["taking", "to take", "take", "took"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "suggest + -ing."
  },
  {
    id: "q10_e_149",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "What is the main goal of mediation tasks?",
    answers: ["To make information accessible in another language or form", "To translate every word literally", "To write a free essay", "To only listen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mediation bridges languages and contexts."
  },
  {
    id: "q10_e_150",
    category: "k10_englisch",
    topic: "skills",
    area: "schule",
    grade: 10,
    subject: "englisch",
    question: "Which competence is especially trained in year 10 English?",
    answers: ["Expressing and justifying opinions in discussions and texts", "Only learning new vocabulary lists", "Only grammar drills without context", "Only reading aloud"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Opinion writing and discussion are central in Klasse 10."
  }
];
