// ================================================================
// KLASSE 5 - ERDKUNDE (100 Fragen)
// NRW-Lehrplan: Orientierung auf der Erde, Deutschland/Europa,
// NRW-Regionen, Klima und Landschaften
// ================================================================

const K5_ERDKUNDE_QUESTIONS = [

  // --- Orientierung auf der Erde (25 Fragen) ---
  {"id":"k5ek001","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt die gedachte Linie, die die Erde in Nord- und Südhalbkugel teilt?","answers":["Polarkreis (66,5° Nord)","Äquator (0° Breite)","Wendekreis des Krebses","Nullmeridian (0° Länge)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Der Äquator ist der längste Breitenkreis und teilt die Erde in die nördliche und südliche Hemisphäre."},
  {"id":"k5ek002","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie viele Kontinente gibt es im klassischen Modell?","answers":["Sechs Kontinente","Sieben Kontinente","Fünf Kontinente","Acht Kontinente"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Klassisch zählt man sieben Kontinente: Nordamerika, Südamerika, Europa, Afrika, Asien, Australien/Ozeanien, Antarktis."},
  {"id":"k5ek003","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Ozean liegt zwischen Europa und Nordamerika?","answers":["Pazifischer Ozean","Arktischer Ozean","Indischer Ozean","Atlantischer Ozean"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Der Atlantik trennt Europa und Afrika im Osten von Nord- und Südamerika im Westen."},
  {"id":"k5ek004","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Auf welchem Kontinent liegt Deutschland?","answers":["Europa","Afrika","Nordamerika","Asien"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Deutschland liegt in Mitteleuropa und grenzt an neun Nachbarstaaten."},
  {"id":"k5ek005","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt der größte Ozean der Erde?","answers":["Pazifischer Ozean (Pazifik)","Arktischer Ozean (Nordpolarmeer)","Atlantischer Ozean (Atlantik)","Indischer Ozean (Indik)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Der Pazifik ist mit etwa 166 Millionen km² der größte und tiefste Ozean der Erde."},
  {"id":"k5ek006","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was zeigt der Maßstab auf einer Landkarte an?","answers":["Wie stark die Wirklichkeit verkleinert dargestellt ist","In welcher Himmelsrichtung die Karte ausgerichtet ist","Wie viele Städte auf der Karte eingezeichnet sind","Welche Farben für Wälder und Gewässer verwendet werden"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Der Maßstab (z.B. 1:100.000) gibt an, wie viel Mal kleiner die Karte als die Wirklichkeit ist."},
  {"id":"k5ek007","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Himmelsrichtung zeigt eine Kompassnadel an?","answers":["Westen","Osten","Norden","Süden"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Die magnetische Kompassnadel richtet sich nach dem magnetischen Nordpol der Erde aus."},
  {"id":"k5ek008","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Woraus besteht das Gradnetz der Erde?","answers":["Aus Äquatorlinien und Flussläufen","Aus Breitengraden und Längengraden","Aus Staatsgrenzen und Zeitzonen","Aus Höhenlinien und Tiefenlinien"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Das Gradnetz aus Breitengraden (horizontal) und Längengraden (vertikal) dient der genauen Ortsbestimmung."},
  {"id":"k5ek009","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt der Nullmeridian und durch welchen Ort verläuft er?","answers":["Rom-Meridian, durch die Altstadt von Rom","Paris-Meridian, durch das Zentrum von Paris","Greenwich-Meridian, durch London (Greenwich)","Berlin-Meridian, durch Berlin-Mitte"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Der international anerkannte Nullmeridian verläuft durch die Sternwarte in Greenwich, einem Stadtteil von London."},
  {"id":"k5ek010","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wo geht die Sonne am Morgen auf?","answers":["Im Norden","Im Osten","Im Westen","Im Süden"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Die Erde dreht sich von West nach Ost, daher erscheint die Sonne morgens im Osten und wandert Richtung Westen."},
  {"id":"k5ek011","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was ist eine Legende auf einer Landkarte?","answers":["Die Liste aller Städte, die auf der Karte eingezeichnet sind","Die Erklärung aller verwendeten Zeichen und Farben","Die genaue Messung der Höhe über dem Meeresspiegel","Die Angabe der Himmelsrichtung durch einen Pfeil"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Die Legende (Zeichenerklärung) entschlüsselt Symbole, Farben und Signaturen der Karte."},
  {"id":"k5ek012","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welchen Kontinent durchquert der Äquator in seiner Mitte?","answers":["Europa","Antarktis","Afrika","Nordamerika"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Der Äquator verläuft quer durch Afrika (z.B. durch Gabun, Kongo, Kenia). Europa liegt vollständig nördlich des Äquators."},
  {"id":"k5ek013","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welche vier Haupthimmelsrichtungen wird die Windrose unterteilt?","answers":["Vorne, Hinten, Links, Rechts","Oben, Unten, Links, Rechts","Nordost, Südost, Südwest, Nordwest","Norden, Osten, Süden, Westen"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Die vier Haupthimmelsrichtungen: Nord (N), Ost (O), Süd (S), West (W). Dazu kommen Nebenhimmelsrichtungen."},
  {"id":"k5ek014","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie nennt man die Darstellung der Erde als Kugel?","answers":["Globus","Kompass","Planisphäre","Atlas"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Ein Globus ist ein verkleinertes, kugelförmiges Modell der Erde mit realistischem Abbild der Kontinente und Ozeane."},
  {"id":"k5ek015","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was liegt nördlicher: Deutschland oder Italien?","answers":["Beide Länder liegen auf exakt gleicher Höhe","Italien liegt nördlicher als ganz Deutschland","Der Unterschied ist nur minimal und nicht messbar","Deutschland liegt deutlich nördlicher als Italien"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Deutschland erstreckt sich etwa von 47° bis 55° Nord, Italien von 36° bis 47° Nord. Deutschland liegt weiter nördlich."},
  {"id":"k5ek016","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was ist ein Breitengrad?","answers":["Ein gedachter Kreis parallel zum Äquator","Eine Grenze zwischen zwei Zeitzonen","Eine senkrechte Linie vom Nord- zum Südpol","Eine Markierung für den Stand der Sonne"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Breitengrade verlaufen waagerecht um die Erde. Der Äquator ist Breitengrad 0°, die Pole liegen bei 90°."},
  {"id":"k5ek017","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Kontinent ist vollständig von Eis bedeckt?","answers":["Afrika (mit der Sahara-Wüste)","Europa (mit den skandinavischen Bergen)","Antarktis (Südpolargebiet)","Asien (mit dem Himalaya-Gebirge)"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Die Antarktis am Südpol ist ein Kontinent mit durchschnittlich 2.500 m dickem Eispanzer. Sie ist unbewohnt."},
  {"id":"k5ek018","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wo liegt der Pazifische Ozean im Vergleich zu Amerika?","answers":["Westlich von Nord- und Südamerika","Südlich des gesamten amerikanischen Kontinents","Östlich von Nord- und Südamerika","Nördlich des gesamten amerikanischen Kontinents"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Der Pazifik liegt westlich von Amerika und östlich von Asien und Australien."},
  {"id":"k5ek019","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Meer ist das größte Binnenmeer der Erde?","answers":["Mittelmeer (zwischen Europa und Afrika)","Ostsee (zwischen Skandinavien und Mitteleuropa)","Schwarzes Meer (östlich des Balkans)","Nordsee (vor der deutschen Küste)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Das Mittelmeer ist mit etwa 2,5 Millionen km² das größte Binnenmeer, umgeben von Europa, Afrika und Asien."},
  {"id":"k5ek020","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was bedeuten die blauen Linien auf einer physischen Landkarte?","answers":["Höhenlinien im alpinen Gebirgsraum","Gewässer wie Flüsse, Bäche und Seen","Grenzen zwischen zwei verschiedenen Staaten","Autobahnen und breite Bundesstraßen"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Blaue Farbe steht auf Karten für Gewässer: Flüsse, Seen, Kanäle und Meere."},
  {"id":"k5ek021","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welcher Himmelsrichtung liegt Deutschland von Frankreich aus gesehen?","answers":["Nördlich (Deutschland liegt nördlich von Frankreich)","Südlich (Deutschland liegt südlich von Frankreich)","Westlich (Deutschland liegt westlich von Frankreich)","Östlich (Deutschland liegt östlich von Frankreich)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Frankreich grenzt im Westen an Deutschland. Von Frankreich aus liegt Deutschland also im Osten."},
  {"id":"k5ek022","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was versteht man unter dem Begriff 'Topografie'?","answers":["Die Auflistung aller Länder auf einem Kontinent","Die Darstellung von Wetterdaten auf einer Karte","Die Beschreibung der Geländeformen und Höhenverhältnisse","Die Untersuchung von Bodenschätzen unter der Erde"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Topografie erfasst Geländemerkmale wie Berge, Täler, Ebenen und stellt sie in Karten detailgetreu dar."},
  {"id":"k5ek023","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Auf welcher Halbkugel liegt Deutschland vollständig?","answers":["Südhalbkugel (südlich des Äquators)","Nordhalbkugel (nördlich des Äquators)","Osthalbkugel (nur östlich des 180. Längengrades)","Westhalbkugel (westlich des Nullmeridians)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Deutschland liegt zwischen etwa 47° und 55° nördlicher Breite und damit vollständig auf der Nordhalbkugel."},
  {"id":"k5ek024","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Kontinent ist der kleinste der Erde?","answers":["Europa (der zweitkleinste Kontinent)","Antarktis (das eisbedeckte Südpolargebiet)","Südamerika (mit tropischen Regenwäldern)","Australien (auch Ozeanien genannt)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Australien ist der kleinste Kontinent mit etwa 8,6 Millionen km² Fläche."},
  {"id":"k5ek025","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was zeigt eine physische Karte hauptsächlich?","answers":["Das Streckennetz von Eisenbahnen und Autobahnen","Die Bevölkerungsdichte in verschiedenen Regionen","Die politischen Grenzen und Hauptstädte aller Länder","Die natürlichen Gegebenheiten wie Berge, Flüsse und Seen"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Die physische Karte stellt die Erdoberfläche mit Höhen, Gewässern und Landschaftsformen dar."},

  // --- Deutschland und seine Landschaften (25 Fragen) ---
  {"id":"k5ek026","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt die Hauptstadt von Deutschland?","answers":["München","Hamburg","Bonn","Berlin"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Berlin ist seit der Wiedervereinigung 1990 die Hauptstadt der Bundesrepublik Deutschland."},
  {"id":"k5ek027","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"An welche Meere grenzt Deutschland im Norden?","answers":["Atlantik und Nordpolarmeer","Nordsee und Ostsee","Schwarzes Meer und Kaspisches Meer","Mittelmeer und Adria"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Deutschlands Nordseeküste liegt im Nordwesten, die Ostseeküste im Nordosten. Beide sind Teil des Atlantiks."},
  {"id":"k5ek028","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt der höchste Berg Deutschlands?","answers":["Watzmann (2.713 Meter)","Brocken (1.141 Meter)","Feldberg (1.493 Meter)","Zugspitze (2.962 Meter)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Die Zugspitze liegt in den bayerischen Alpen nahe Garmisch-Partenkirchen und ist 2.962 m hoch."},
  {"id":"k5ek029","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Fluss ist der längste innerhalb Deutschlands?","answers":["Donau (auf deutschem Gebiet etwa 647 km)","Weser (auf deutschem Gebiet etwa 452 km)","Elbe (auf deutschem Gebiet etwa 727 km)","Rhein (auf deutschem Gebiet etwa 865 km)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Der Rhein fließt auf 865 km durch Deutschland. Die Donau ist insgesamt länger, aber kürzer auf deutschem Gebiet."},
  {"id":"k5ek030","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welchem Bundesland liegt die Stadt Köln?","answers":["Nordrhein-Westfalen","Rheinland-Pfalz","Niedersachsen","Hessen"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Köln ist eine der größten Städte in Nordrhein-Westfalen und liegt direkt am Rhein."},
  {"id":"k5ek031","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was sind die Alpen geografisch betrachtet?","answers":["Ein weitläufiges Tiefland zwischen Nord- und Ostsee","Ein großes Waldgebiet in der Mitte Deutschlands","Ein Hochgebirge im Süden Deutschlands und angrenzenden Ländern","Eine flache Küstenregion an der Nordsee"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Die Alpen sind das höchste Gebirge Europas und erstrecken sich von Frankreich bis Slowenien."},
  {"id":"k5ek032","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Landschaftsform prägt den Norden Deutschlands?","answers":["Hochgebirge (steile Gipfel und tiefe Täler)","Norddeutsches Tiefland (flache Landschaft)","Alpenvorland (hügelige Landschaft im Süden)","Mittelgebirge (abwechslungsreiche Höhenzüge)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Das Norddeutsche Tiefland erstreckt sich von der Nordseeküste bis zum Rand der Mittelgebirge."},
  {"id":"k5ek033","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie viele Bundesländer hat die Bundesrepublik Deutschland?","answers":["12 Bundesländer","16 Bundesländer","10 Bundesländer","20 Bundesländer"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Deutschland besteht aus 16 Bundesländern, darunter drei Stadtstaaten: Berlin, Hamburg und Bremen."},
  {"id":"k5ek034","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Mittelgebirge liegt in Nordrhein-Westfalen?","answers":["Bayerischer Wald (an der Grenze zu Tschechien)","Schwarzwald (im Südwesten Baden-Württembergs)","Erzgebirge (im Grenzgebiet zu Tschechien)","Sauerland (Teil des Rheinischen Schiefergebirges)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Das Sauerland liegt im Südosten von NRW und ist bekannt für seine bewaldeten Berge und Wintersportmöglichkeiten."},
  {"id":"k5ek035","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"An welchem Fluss liegt die Stadt Hamburg?","answers":["Donau","Elbe","Weser","Rhein"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Hamburg liegt an der Elbe und ist der größte deutsche Seehafen, etwa 100 km von der Nordsee entfernt."},
  {"id":"k5ek036","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was versteht man unter dem Begriff 'Bundesland'?","answers":["Ein Verbund mehrerer Staaten unter einer Regierung","Eine Stadt, die keinem Landkreis angehört","Ein Teilstaat mit eigener Regierung innerhalb Deutschlands","Eine Region ohne eigene politische Entscheidungsgewalt"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Deutschland ist ein Bundesstaat: 16 Bundesländer haben eigene Parlamente und Regierungen mit bestimmten Zuständigkeiten."},
  {"id":"k5ek037","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher See ist der größte vollständig in Deutschland liegende See?","answers":["Bodensee (Grenzsee zu Österreich und der Schweiz)","Müritz (in Mecklenburg-Vorpommern)","Chiemsee (in Oberbayern gelegen)","Starnberger See (südlich von München)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Die Müritz in der Mecklenburgischen Seenplatte ist mit etwa 117 km² der größte vollständig deutsche Binnensee."},
  {"id":"k5ek038","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Gebirge liegt im Südwesten Deutschlands?","answers":["Fichtelgebirge (im Nordosten Bayerns)","Harz (an der Grenze von Niedersachsen und Sachsen-Anhalt)","Schwarzwald (in Baden-Württemberg)","Thüringer Wald (im Bundesland Thüringen)"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Der Schwarzwald liegt in Baden-Württemberg und ist das höchste und größte zusammenhängende Mittelgebirge Deutschlands."},
  {"id":"k5ek039","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt der größte Hafen Deutschlands?","answers":["Rostocker Hafen","Wilhelmshavener Hafen","Bremer Hafen","Hamburger Hafen"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Der Hamburger Hafen ist der größte Seehafen Deutschlands und einer der größten Containerhäfen Europas."},
  {"id":"k5ek040","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Insel gehört zu Deutschland und liegt in der Nordsee?","answers":["Kreta (im östlichen Mittelmeer)","Mallorca (im westlichen Mittelmeer)","Rügen (vor der Küste Mecklenburg-Vorpommerns)","Sylt (vor der Küste Schleswig-Holsteins)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Sylt ist eine deutsche Nordseeinsel. Rügen liegt in der Ostsee. Mallorca und Kreta sind nicht deutsch."},
  {"id":"k5ek041","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welchem Bundesland liegt die Landeshauptstadt Düsseldorf?","answers":["Baden-Württemberg","Rheinland-Pfalz","Hessen","Nordrhein-Westfalen"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Düsseldorf ist die Landeshauptstadt von Nordrhein-Westfalen, dem bevölkerungsreichsten Bundesland."},
  {"id":"k5ek042","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was ist typisch für die Landschaft der Lüneburger Heide?","answers":["Weite Heideflächen mit Wacholderbüschen und Schafen","Flache Marschwiesen direkt an der Nordseeküste","Dichte Nadelwälder mit steilen Felsformationen","Weinberge entlang eines großen Flusstales"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Die Lüneburger Heide in Niedersachsen ist eine historische Kulturlandschaft mit Heidekraut und typischem Bewuchs."},
  {"id":"k5ek043","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Fluss fließt durch die Stadt Dresden?","answers":["Rhein","Elbe","Main","Donau"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Die Elbe durchfließt Dresden und prägt das Stadtbild mit den berühmten Elbwiesen."},
  {"id":"k5ek044","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches ist das flächenmäßig größte Bundesland Deutschlands?","answers":["Nordrhein-Westfalen (etwa 34.100 km²)","Niedersachsen (etwa 47.600 km²)","Baden-Württemberg (etwa 35.700 km²)","Bayern (etwa 70.500 km²)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Bayern ist mit Abstand das größte Bundesland, gefolgt von Niedersachsen und Baden-Württemberg."},
  {"id":"k5ek045","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was sind die Gezeiten an der Nordseeküste?","answers":["Sandverwehungen, die die Dünenlandschaft formen","Das regelmäßige Wechselspiel von Ebbe und Flut","Starke Wirbelstürme, die im Herbst auftreten","Die jahreszeitliche Erwärmung des Meerwassers"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Ebbe (sinkender Wasserspiegel) und Flut (steigender Wasserspiegel) entstehen durch die Anziehungskraft von Mond und Sonne."},
  {"id":"k5ek046","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Landeshauptstadt liegt am Rhein?","answers":["Hannover (Niedersachsen)","Düsseldorf (Nordrhein-Westfalen)","Potsdam (Brandenburg)","Schwerin (Mecklenburg-Vorpommern)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Düsseldorf liegt direkt am Rhein. Hannover liegt an der Leine, Potsdam an der Havel."},
  {"id":"k5ek047","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches deutsche Mittelgebirge liegt direkt an der Grenze zu Tschechien?","answers":["Erzgebirge (Sachsen und Tschechien)","Eifel (Nordrhein-Westfalen und Rheinland-Pfalz)","Schwarzwald (Baden-Württemberg)","Harz (Niedersachsen und Sachsen-Anhalt)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Das Erzgebirge erstreckt sich entlang der sächsisch-tschechischen Grenze und war historisch für Silberbergbau bekannt."},
  {"id":"k5ek048","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Stadt ist ein sogenannter Stadtstaat in Deutschland?","answers":["Dortmund (Stadt in NRW)","Hamburg (eigenes Bundesland)","Frankfurt (Stadt in Hessen)","Köln (Stadt in NRW)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Die drei Stadtstaaten Deutschlands sind Berlin, Hamburg und Bremen. Sie sind zugleich Stadt und Bundesland."},
  {"id":"k5ek049","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt das Gebiet entlang der deutschen Nordseeküste mit fruchtbarem Boden?","answers":["Heide (sandige, trockene Landschaft)","Alm (Bergwiese in den Alpen)","Marsch (durch Deiche geschütztes Schwemmland)","Geest (sandige, höher gelegene Flächen)"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Die Marsch entstand durch Ablagerungen des Meeres und ist nach Eindeichung sehr fruchtbares Ackerland."},
  {"id":"k5ek050","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie viele direkte Nachbarstaaten grenzen an Deutschland?","answers":["Zwölf Nachbarstaaten","Vier Nachbarstaaten","Sechs Nachbarstaaten","Neun Nachbarstaaten"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Deutschland hat neun Nachbarn: Dänemark, Polen, Tschechien, Österreich, Schweiz, Frankreich, Luxemburg, Belgien, Niederlande."},

  // --- Europa (15 Fragen) ---
  {"id":"k5ek051","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Meer trennt Europa von Afrika?","answers":["Schwarzes Meer","Nordsee","Mittelmeer","Ostsee"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Das Mittelmeer liegt zwischen Südeuropa und Nordafrika und ist über die Straße von Gibraltar mit dem Atlantik verbunden."},
  {"id":"k5ek052","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt die Hauptstadt von Frankreich?","answers":["Paris","London","Madrid","Rom"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Paris ist die Hauptstadt Frankreichs und eine der größten Städte Europas. London ist Hauptstadt des Vereinigten Königreichs."},
  {"id":"k5ek053","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"An welchem Fluss liegt die Stadt Paris?","answers":["Themse","Seine","Tiber","Donau"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Paris liegt an der Seine. Die Themse fließt durch London, der Tiber durch Rom, die Donau durch Wien und Budapest."},
  {"id":"k5ek054","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Gebirge bildet die natürliche Grenze zwischen Europa und Asien?","answers":["Karpaten (in Osteuropa)","Pyrenäen (zwischen Frankreich und Spanien)","Alpen (in Mitteleuropa)","Uralgebirge (in Russland)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Der Ural in Russland gilt als östliche Grenze Europas zu Asien, zusammen mit dem Uralfluss und dem Kaukasus."},
  {"id":"k5ek055","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Land ist kein direkter Nachbar Deutschlands?","answers":["Polen","Dänemark","Tschechien","Spanien"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Spanien liegt im Südwesten Europas und grenzt nicht an Deutschland. Polen, Tschechien und Dänemark sind direkte Nachbarn."},
  {"id":"k5ek056","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt die Hauptstadt von Österreich?","answers":["Bern","Wien","Prag","Budapest"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Wien ist die Hauptstadt Österreichs und liegt an der Donau. Bern ist die Hauptstadt der Schweiz."},
  {"id":"k5ek057","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Auf welcher Halbinsel liegt Spanien zusammen mit Portugal?","answers":["Apenninenhalbinsel","Skandinavische Halbinsel","Balkanhalbinsel","Iberische Halbinsel"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Die Iberische Halbinsel umfasst Spanien, Portugal und das kleine Andorra im Südwesten Europas."},
  {"id":"k5ek058","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Land wird auch 'Vereinigtes Königreich' genannt?","answers":["Niederlande (mit den Antillen)","Großbritannien (mit Nordirland)","Frankreich (mit Überseegebieten)","Deutschland (mit seinen Bundesländern)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Das Vereinigte Königreich (UK) besteht aus England, Schottland, Wales und Nordirland."},
  {"id":"k5ek059","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welchem Land liegt die Stadt Rom?","answers":["Italien (Hauptstadt Roms)","Spanien (Hauptstadt Madrids)","Frankreich (Hauptstadt Paris')","Griechenland (Hauptstadt Athens)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Rom ist die Hauptstadt Italiens. Die Stadt war das Zentrum des Römischen Reiches."},
  {"id":"k5ek060","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Durch welche Meerenge gelangt man vom Mittelmeer in den Atlantik?","answers":["Bosporus (zwischen Europa und Asien)","Straße von Sizilien (zwischen Italien und Tunesien)","Straße von Gibraltar (zwischen Spanien und Marokko)","Ärmelkanal (zwischen Frankreich und England)"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Die Straße von Gibraltar verbindet Mittelmeer und Atlantik. An der engsten Stelle ist sie nur etwa 14 km breit."},
  {"id":"k5ek061","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Sprache spricht man hauptsächlich in den Niederlanden?","answers":["Deutsch (in Deutschland)","Dänisch (in Dänemark)","Schwedisch (in Schweden)","Niederländisch"],"correct":3,"difficulty":"mittel","points":10,"explanation":"In den Niederlanden ist Niederländisch die Amtssprache. Dänisch spricht man in Dänemark."},
  {"id":"k5ek062","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Fluss fließt durch die Hauptstadt Wien?","answers":["Elbe","Rhein","Weichsel","Donau"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Die Donau durchfließt Wien und ist mit etwa 2.850 km der zweitlängste Fluss Europas (nach der Wolga)."},
  {"id":"k5ek063","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Land ist bekannt für seine Kanäle und Windmühlen?","answers":["Niederlande (mit Amsterdam)","Polen (mit Warschau)","Österreich (mit Wien)","Schweiz (mit Bern)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Die Niederlande sind berühmt für ihr ausgedehntes Kanalsystem und die traditionellen Windmühlen."},
  {"id":"k5ek064","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt das Hochgebirge in der Schweiz?","answers":["Alpen","Apennin","Pyrenäen","Karpaten"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Die Alpen durchziehen die Schweiz und sind das höchste Gebirge Europas. Pyrenäen liegen zwischen Frankreich und Spanien."},
  {"id":"k5ek065","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welchem Land liegt die Stadt Krakau?","answers":["Slowakei","Tschechien","Polen","Ungarn"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Krakau (Kraków) ist eine der ältesten und bedeutendsten Städte Polens im Süden des Landes."},

  // --- NRW-Regionen (10 Fragen) ---
  {"id":"k5ek066","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt die Landeshauptstadt von Nordrhein-Westfalen?","answers":["Münster","Köln","Düsseldorf","Bonn"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Düsseldorf ist Sitz des Landtags und der Landesregierung von NRW und damit die Landeshauptstadt."},
  {"id":"k5ek067","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher Fluss fließt mitten durch das Ruhrgebiet?","answers":["Lippe (fließt nördlich des Ruhrgebiets)","Ruhr (namensgebend für das Ruhrgebiet)","Rhein (durchfließt Köln und Düsseldorf)","Emscher (ehemaliger Abwasserfluss)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Die Ruhr durchfließt das Ruhrgebiet und gab der Region ihren Namen. Sie mündet bei Duisburg in den Rhein."},
  {"id":"k5ek068","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Region in NRW war früher durch Kohlebergbau geprägt?","answers":["Münsterland (flache Parklandschaft)","Eifel (Vulkangebiet im Südwesten)","Sauerland (Mittelgebirge im Süden)","Ruhrgebiet (Städte wie Essen, Dortmund, Bochum)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Das Ruhrgebiet war das größte Kohleabbaugebiet Europas. Heute ist es eine Dienstleistungs- und Kulturregion."},
  {"id":"k5ek069","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher bekannte Dom steht in Köln?","answers":["Essener Münster (frühgotische Kirche)","Aachener Dom (karolingischer Bau)","Münsteraner Dom (romanische Kirche)","Kölner Dom (gotische Kathedrale)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Der Kölner Dom ist eine der größten gotischen Kathedralen Europas und Wahrzeichen der Stadt Köln."},
  {"id":"k5ek070","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Mittelgebirge liegt im Süden von NRW?","answers":["Sauerland (Teil des Rheinischen Schiefergebirges)","Bergisches Land (östlich von Köln)","Eifel (im Südwesten von NRW)","Weserbergland (in Ostwestfalen)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Das Sauerland ist ein beliebtes Wander- und Wintersportgebiet mit Höhen bis über 800 Meter."},
  {"id":"k5ek071","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißt die älteste Stadt Nordrhein-Westfalens?","answers":["Aachen (römische Siedlung Aquae Granni)","Köln (römische Gründung Colonia)","Xanten (römische Gründung Colonia Ulpia Traiana)","Bonn (römische Gründung Bonna)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Köln wurde 50 n. Chr. von den Römern als Colonia Claudia Ara Agrippinensium gegründet und ist damit eine der ältesten Städte."},
  {"id":"k5ek072","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches bekannte Schloss liegt bei Bonn?","answers":["Schloss Drachenburg (auf dem Drachenfels)","Schloss Sanssouci (in Potsdam)","Schloss Neuschwanstein (in Bayern)","Schloss Heidelberg (in Baden-Württemberg)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Schloss Drachenburg liegt auf dem Drachenfels im Siebengebirge bei Bonn und ist ein beliebtes Ausflugsziel."},
  {"id":"k5ek073","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welcher See im Ruhrgebiet ist ein bekanntes Naherholungsgebiet?","answers":["Baldeneysee (in Essen an der Ruhr)","Chiemsee (in Oberbayern)","Müritz (in Mecklenburg)","Bodensee (im Dreiländereck)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Der Baldeneysee ist ein Stausee der Ruhr in Essen und ein beliebtes Ziel für Wassersport und Spaziergänge."},
  {"id":"k5ek074","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welcher Stadt in NRW befindet sich der größte Binnenhafen Europas?","answers":["Köln (Rheinhafen)","Duisburg (Duisport am Rhein)","Münster (Dortmund-Ems-Kanal)","Dortmund (Kanalhafen)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Duisburg besitzt mit 'Duisport' den größten Binnenhafen Europas am Zusammenfluss von Rhein und Ruhr."},
  {"id":"k5ek075","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Gebirge grenzt im Südwesten an das Sauerland?","answers":["Taunus (mit dem Feldberg)","Westerwald (mit Basaltkuppen)","Eifel (mit vulkanischen Maaren)","Bergisches Land (mit vielen Talsperren)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Das Bergische Land schließt sich westlich an das Sauerland an und ist bekannt für Wälder, Talsperren und Fachwerkhäuser."},

  // --- Klima, Wetter und Landschaften (15 Fragen) ---
  {"id":"k5ek076","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welcher Klimazone liegt Deutschland?","answers":["Polare Klimazone (extrem kalte Winter)","Subtropische Klimazone (sehr heiße Sommer)","Gemäßigte Klimazone (warme Sommer, milde Winter)","Tropische Klimazone (ganzjährig heiß und feucht)"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Deutschland liegt in der gemäßigten Klimazone mit vier Jahreszeiten und ganzjährigen Niederschlägen."},
  {"id":"k5ek077","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie entsteht Regen im Wasserkreislauf?","answers":["Wind treibt Meerwasser in großen Mengen ins Landesinnere","Wolken saugen das gesamte Wasser aus Seen und Flüssen auf","Die Sonne erhitzt die Erde, bis Wasser aus dem Boden tritt","Wasser verdunstet, steigt auf, kondensiert und fällt als Niederschlag"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Verdunstung → Aufstieg → Abkühlung → Kondensation → Wolkenbildung → Niederschlag. So schließt sich der Kreislauf."},
  {"id":"k5ek078","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Temperatur herrscht am Äquator im Vergleich zu den Polen?","answers":["An den Polen ist es genauso warm wie am Äquator","Die Temperaturen sind weltweit überall identisch","Am Äquator ist es deutlich wärmer als an den Polen","Am Äquator ist es kälter als an den Polen"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Die Sonneneinstrahlung ist am Äquator am stärksten. Zu den Polen hin wird sie flacher und die Temperatur sinkt."},
  {"id":"k5ek079","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was versteht man unter dem Begriff 'Klima'?","answers":["Den durchschnittlichen Wetterverlauf über einen langen Zeitraum","Den Niederschlag, der innerhalb einer Stunde fällt","Das aktuelle Wetter an einem bestimmten Tag","Die Temperatur, die genau in diesem Moment herrscht"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Klima ist die Statistik des Wetters über Jahrzehnte (mindestens 30 Jahre), Wetter ist der aktuelle Zustand."},
  {"id":"k5ek080","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Warum ist es an den Küsten im Winter meist milder als im Binnenland?","answers":["Der Wind vom Land erwärmt die gesamte Küstenregion","Das Salzwasser heizt die Luft über dem Meer aktiv auf","Das Meer speichert Wärme länger und gibt sie langsam ab","An der Küste scheint die Sonne auch im Winter sehr stark"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Wasser erwärmt sich langsamer und kühlt langsamer ab als Land – es wirkt als Wärmespeicher."},
  {"id":"k5ek081","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was zeigt eine Klimadiagramm-Darstellung?","answers":["Die Bevölkerungsdichte in verschiedenen Regionen","Den Verlauf von Flüssen von der Quelle bis zur Mündung","Temperatur und Niederschlag im Jahresverlauf","Die genaue Höhe eines Berges über dem Meeresspiegel"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Ein Klimadiagramm stellt monatliche Durchschnittstemperaturen (als Kurve) und Niederschläge (als Balken) dar."},
  {"id":"k5ek082","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welcher Jahreszeit fallen die Blätter von den Laubbäumen in Deutschland?","answers":["Winter (bei gefrorenem Boden)","Sommer (in den heißen Monaten)","Frühling (wenn es wärmer wird)","Herbst (Vorbereitung auf den Winter)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Im Herbst bereiten sich Laubbäume auf den Winter vor. Sie entziehen den Blättern Nährstoffe und werfen sie ab."},
  {"id":"k5ek083","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was versteht man unter 'Erosion' in der Landschaft?","answers":["Versteppung ehemals fruchtbarer Landschaften","Ablagerung von Sand an einer Flussmündung","Abtragung von Gestein und Boden durch Wasser, Wind oder Eis","Bildung neuer Gebirge durch Plattenkollision"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Erosion formt Landschaften: Flüsse graben Täler, Wind schleift Felsen, Gletscher hobeln Täler aus."},
  {"id":"k5ek084","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie entsteht eine Düne in der Wüste oder an der Küste?","answers":["Wasser spült Sand von weit entfernten Stränden an","Sonneneinstrahlung lässt den Boden wellenförmig aufquellen","Pflanzen wurzeln im Boden und heben den Sand an","Wind trägt Sandkörner heran und lagert sie zu Hügeln ab"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Wind transportiert Sandkörner. Sobald die Windgeschwindigkeit nachlässt, fallen sie zu Boden und häufen sich an."},
  {"id":"k5ek085","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche der folgenden Landschaften ist typisch für eine Küstenregion an der Nordsee?","answers":["Tundra (baumlose Kältesteppe)","Watt (Meeresboden, der bei Ebbe trockenfällt)","Alm (Grasfläche im Hochgebirge)","Steppe (trockene Graslandschaft)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Das Wattenmeer der Nordsee ist UNESCO-Weltnaturerbe. Bei Ebbe fällt der Meeresboden trocken."},
  {"id":"k5ek086","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was bestimmt maßgeblich die Temperaturen auf der Erde?","answers":["Die Anzahl der Städte in einer bestimmten Region","Die Größe der Wälder auf einem Kontinent","Die Tiefe der Meere an den Küsten","Die Sonneneinstrahlung und der Breitengrad"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Je näher am Äquator, desto mehr Sonnenenergie pro Fläche. Mit zunehmendem Breitengrad nimmt die Einstrahlung ab."},
  {"id":"k5ek087","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Warum regnet es an der Westseite von Gebirgen oft mehr als an der Ostseite?","answers":["An der Westseite gibt es grundsätzlich mehr Flüsse und Seen","Die Ostseite wird ständig von der Sonne beschienen","Der Wind weht Feuchtigkeit von der Ost- zur Westseite","Feuchte Luft steigt auf, kühlt ab und regnet an der Westseite ab"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Westwinde bringen feuchte Luft vom Meer. Beim Aufsteigen am Gebirge kondensiert die Feuchtigkeit (Steigungsregen). Ostseite = Regenschatten."},
  {"id":"k5ek088","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was ist ein Fjord?","answers":["Ein schmaler, tiefer Meeresarm, der durch Gletscher entstanden ist","Ein künstlich angelegter Kanal in den Niederlanden","Ein unterirdischer Wasserlauf in Karstgebieten","Ein breiter Sandstrand an der Nordseeküste"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Fjorde (z.B. in Norwegen) entstanden durch Gletscher, die tiefe Täler ins Gestein hobelten, die später vom Meer geflutet wurden."},
  {"id":"k5ek089","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Farbe zeigt auf einer Höhenkarte die tief liegenden Gebiete an?","answers":["Grün (Tiefland und Ebenen)","Braun (Hochgebirge und Gipfel)","Blau (Gewässer und Meere)","Weiß (Gletscher und Schneeflächen)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Auf physischen Karten: Grün = Tiefland (0-200 m), Gelb = Hügelland, Braun = Gebirge, Weiß = Hochgebirge."},
  {"id":"k5ek090","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Landschaftsform entsteht durch Vulkanausbrüche?","answers":["Dünenlandschaft (durch Wind geformt)","Flussdelta (an einer Flussmündung)","Vulkankegel oder Caldera (eingestürzter Vulkankrater)","Karstlandschaft (durch Kalklösung entstanden)"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Vulkane bauen durch ausgestoßenes Material Kegel auf. Nach Einsturz eines Kraters entsteht eine Caldera."},

  // --- Wirtschaft und Verkehr (10 Fragen) ---
  {"id":"k5ek091","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wofür ist das Ruhrgebiet in Deutschland heute besonders bekannt?","answers":["Ausschließlich Kohlebergbau und Schwerindustrie","Fischerei und maritime Wirtschaft","Alpine Landwirtschaft und Viehzucht","Kultur, Universitäten und Dienstleistungen (Strukturwandel)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Das Ruhrgebiet hat den Wandel von der Montanindustrie zur Wissens- und Dienstleistungsregion erfolgreich vollzogen."},
  {"id":"k5ek092","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welches Verkehrsmittel wird auf dem Rhein am häufigsten für Gütertransporte genutzt?","answers":["Hochgeschwindigkeitszug (ICE)","Lastkraftwagen (LKW)","Flugzeug (Frachtflieger)","Binnenschiff (Containerschiffe und Schubverbände)"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Der Rhein ist die verkehrsreichste Wasserstraße Europas. Massengüter wie Kohle, Erz und Container werden per Schiff transportiert."},
  {"id":"k5ek093","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wozu dienen Talsperren im Sauerland und Bergischen Land?","answers":["Kühlung von Kraftwerken in der Region","Fischzucht in großen industriellen Anlagen","Trinkwasserversorgung und Hochwasserschutz","Gewinnung von Salz aus tiefen Bohrlöchern"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Zahlreiche Talsperren (z.B. Möhnetalsperre, Biggetalsperre) dienen der Trinkwassergewinnung und regulieren Hochwasser."},
  {"id":"k5ek094","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"In welcher Region Deutschlands wird am meisten Wein angebaut?","answers":["Schleswig-Holstein (Nordseeküste)","Rheinland-Pfalz (Pfalz, Rheinhessen, Mosel)","Bayern (Alpenvorland)","Mecklenburg-Vorpommern (Ostseeküste)"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Rheinland-Pfalz ist das bedeutendste Weinanbaugebiet Deutschlands mit Regionen wie Mosel, Pfalz und Rheinhessen."},
  {"id":"k5ek095","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Was ist ein Containerhafen?","answers":["Ein Hafen, der nur von Fischerbooten genutzt wird","Ein Hafen, der ausschließlich flüssige Güter verladen kann","Ein Hafen, der speziell für genormte Frachtbehälter ausgelegt ist","Ein Hafen für Kreuzfahrtschiffe mit Passagieren"],"correct":2,"difficulty":"mittel","points":10,"explanation":"Container sind standardisierte Frachtboxen. Containerhäfen (z.B. Hamburg) schlagen diese mit speziellen Kränen um."},
  {"id":"k5ek096","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Rohstoffe wurden früher im Ruhrgebiet abgebaut?","answers":["Erdöl und flüssiges Erdgas","Uran und radioaktive Mineralien","Gold und wertvolle Edelsteine","Steinkohle (unter Tage) und Eisenerz"],"correct":3,"difficulty":"mittel","points":10,"explanation":"Das Ruhrgebiet verdankt seinen Aufstieg der Steinkohle. Die letzte Zeche schloss 2018 in Bottrop."},
  {"id":"k5ek097","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Wie heißen die wichtigsten deutschen Autohersteller-Standorte?","answers":["Wolfsburg (VW), München (BMW), Stuttgart (Mercedes)","Bremen (VW), Nürnberg (BMW), Dortmund (Mercedes)","Köln (VW), Frankfurt (BMW), Leipzig (Mercedes)","Hamburg (VW), Berlin (BMW), Dresden (Mercedes)"],"correct":0,"difficulty":"mittel","points":10,"explanation":"VW hat seinen Hauptsitz in Wolfsburg, BMW in München, Mercedes-Benz in Stuttgart. Alle drei sind in Süd-/Mitteldeutschland."},
  {"id":"k5ek098","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Womit beschäftigt sich die Wirtschaftsgeografie?","answers":["Mit der Vorhersage von Erdbeben und Vulkanausbrüchen","Mit der räumlichen Verteilung wirtschaftlicher Aktivitäten","Mit der Höhenmessung von Gebirgsketten","Mit der Geschichte alter ausgestorbener Kulturen"],"correct":1,"difficulty":"mittel","points":10,"explanation":"Wirtschaftsgeografie untersucht, wo und warum bestimmte Industrien, Landwirtschaft und Dienstleistungen angesiedelt sind."},
  {"id":"k5ek099","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Warum liegen viele Großstädte an Flüssen oder am Meer?","answers":["Weil Wasserwege Handel und Transport erleichtert haben","Weil Flüsse das ganze Jahr über Trinkwasser liefern","Weil Gebäude auf feuchtem Boden stabiler stehen","Weil die Menschen früher nur schwimmend reisen konnten"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Historisch waren Flüsse und Häfen wichtige Verkehrswege für Waren. Viele Städte entstanden an günstigen Handelsplätzen."},
  {"id":"k5ek100","category":"k5_erdkunde","area":"schule","grade":5,"subject":"erdkunde","question":"Welche Bedeutung hat der Dortmund-Ems-Kanal für NRW?","answers":["Er verbindet das Ruhrgebiet mit dem Nordseehafen Emden","Er versorgt das Sauerland mit Trinkwasser aus der Ems","Er leitet ausschließlich Hochwasser in den Rhein ab","Er dient nur der Freizeitschifffahrt ohne Güterverkehr"],"correct":0,"difficulty":"mittel","points":10,"explanation":"Der Dortmund-Ems-Kanal verbindet den Dortmund-Ems-Hafen mit Emden und ist eine wichtige Binnenwasserstraße für Güter."}

];

if (typeof window !== 'undefined') window.K5_ERDKUNDE_QUESTIONS = K5_ERDKUNDE_QUESTIONS;
if (typeof registerQuestions === 'function') registerQuestions('K5_ERDKUNDE_QUESTIONS', K5_ERDKUNDE_QUESTIONS);
