const K3_DEUTSCH_QUESTIONS = [
  // ================================================================
  // 1. WORTARTEN & ZEITFORMEN (25 Fragen)
  // ================================================================
  {
    id: "q3_d_001",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Wortart ist 'schnell' in 'Er läuft schnell'?",
    answers: ["Adjektiv", "Nomen", "Verb", "Pronomen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'schnell' beschreibt näher, wie er läuft – es ist ein Adjektiv."
  },
  {
    id: "q3_d_002",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie lautet die Mehrzahl von 'Kind'?",
    answers: ["Kinder", "Kinde", "Kindern", "Kinds"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Mehrzahl von Kind ist Kinder."
  },
  {
    id: "q3_d_003",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist ein Verb?",
    answers: ["Ein Tuwort wie 'laufen'", "Ein Namenwort wie 'Baum'", "Ein Wiewort wie 'schön'", "Ein Zahlwort wie 'drei'"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verben beschreiben Tätigkeiten: laufen, essen, lesen."
  },
  {
    id: "q3_d_004",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist ein Nomen (Namenwort)?",
    answers: ["Baum", "rennen", "schön", "schnell"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Baum ist ein Nomen und wird großgeschrieben."
  },
  {
    id: "q3_d_005",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie heißt die Vergangenheit (Präteritum) von 'gehen'?",
    answers: ["ging", "geht", "ist gegangen", "gehte"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Ging' ist das Präteritum von gehen."
  },
  {
    id: "q3_d_006",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches der drei Wörter ist ein Verb?",
    answers: ["laufen", "schön", "Hund", "gestern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Verben sind Tunwörter wie 'laufen'."
  },
  {
    id: "q3_d_007",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist die Einzahl von 'Tische'?",
    answers: ["Tisch", "Tisches", "Tischen", "Tischer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Einzahl ist Tisch, Mehrzahl ist Tische."
  },
  {
    id: "q3_d_008",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort ist das Adjektiv im Satz: 'Der flinke Hase rennt über das Feld'?",
    answers: ["flinke", "Der", "Hase", "rennt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'flinke' beschreibt, wie der Hase ist – es ist ein Adjektiv."
  },
  {
    id: "q3_d_009",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie lautet die Vergangenheitsform (Präteritum) von dem Verb 'schreiben'?",
    answers: ["schrieb", "geschrieben", "schreibte", "schreibt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Präteritum von schreiben heißt 'ich schrieb / er schrieb'."
  },
  {
    id: "q3_d_010",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie heißt die Vergangenheitsform (Präteritum) von 'sehen'?",
    answers: ["sah", "sieht", "gesehen", "sehte"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Präteritum von sehen heißt 'sah'."
  },
  {
    id: "q3_d_011",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie heißt die Vergangenheitsform (Präteritum) von 'kommen'?",
    answers: ["kam", "gekommen", "kömmte", "kommt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Präteritum lautet: er kam."
  },
  {
    id: "q3_d_012",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "In welcher Zeitform steht der Satz: 'Lisa liest ein spannendes Buch'?",
    answers: ["Präsens (Gegenwart)", "Präteritum (Vergangenheit)", "Perfekt", "Futur (Zukunft)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'liest' passiert genau jetzt in der Gegenwart (Präsens)."
  },
  {
    id: "q3_d_013",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "In welcher Zeitform steht der Satz: 'Gestern spielte Tim im Garten'?",
    answers: ["Präteritum (Vergangenheit)", "Präsens (Gegenwart)", "Futur (Zukunft)", "Infinitiv"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'spielte' drückt die schriftliche Vergangenheit (Präteritum) aus."
  },
  {
    id: "q3_d_014",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie bildet man das Perfekt (gesprochene Vergangenheit) von 'laufen'?",
    answers: ["ist gelaufen", "lief", "laufte", "hat gelauft"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Perfekt von laufen wird mit 'sein' gebildet: ist gelaufen."
  },
  {
    id: "q3_d_015",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort ist ein Pronomen (Fürwort)?",
    answers: ["ich", "Tisch", "blau", "schwimmen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Pronomen (ich, du, er, sie, es...) stehen stellvertretend für Nomen."
  },
  {
    id: "q3_d_016",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Pronomen (Fürwort) kann 'der Hund' im Satz ersetzen?",
    answers: ["er", "sie", "es", "wir"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Hund ist männlich -> er."
  },
  {
    id: "q3_d_017",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Pronomen kann 'die Kinder' im Satz ersetzen?",
    answers: ["sie", "er", "es", "du"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Kinder (Mehrzahl) = sie."
  },
  {
    id: "q3_d_018",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie lautet die Steigerung des Adjektivs 'groß'?",
    answers: ["groß, größer, am größten", "groß, großer, am großten", "groß, mehr groß, am meisten groß", "groß, am größten, größer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Steigerung heißt: groß -> größer -> am größten."
  },
  {
    id: "q3_d_019",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie lautet die Steigerung des Adjektivs 'gut'?",
    answers: ["gut, besser, am besten", "gut, guter, am gutesten", "gut, am besten, besser", "gut, feiner, am feinsten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'Gut' wird unregelmäßig gesteigert: gut -> besser -> am besten."
  },
  {
    id: "q3_d_020",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist die Grundform (Infinitiv) der Verbform 'du rennst'?",
    answers: ["rennen", "renne", "rennt", "gerannt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Grundform (Infinitiv) lautet 'rennen'."
  },
  {
    id: "q3_d_021",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches abstraktes Wort (Gefühl) ist ein Nomen?",
    answers: ["Freude", "froh", "freuen", "fröhlich"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "auch Gefühle wie 'die Freude' sind Nomen und werden großgeschrieben."
  },
  {
    id: "q3_d_022",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Aus welcher Wortart besteht das Wort 'traurig'?",
    answers: ["Adjektiv", "Nomen", "Verb", "Pronomen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'traurig' beschreibt eine Eigenschaft/Zustand (Wie-Wort / Adjektiv)."
  },
  {
    id: "q3_d_023",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Verb passt am besten zum Nomen 'die Uhr'?",
    answers: ["tickt", "bellt", "fliegt", "schwimmt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Uhr tickt."
  },
  {
    id: "q3_d_024",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie heißt die Vergangenheitsform (Präteritum) von 'fliegen'?",
    answers: ["flog", "fliegte", "geflogen", "fliegt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Präteritum von fliegen heißt 'flog'."
  },
  {
    id: "q3_d_025",
    category: "k3_deutsch",
    topic: "wortarten_zeitformen",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches dieser Wörter ist KEIN Verb?",
    answers: ["schön", "tanzen", "lachen", "schreiben"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'schön' ist ein Adjektiv. Die anderen drei Wörter sind Verben."
  },

  // ================================================================
  // 2. RECHTSCHREIBSTRATEGIEN & WORTBAUSTEINE (25 Fragen)
  // ================================================================
  {
    id: "q3_d_026",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie schreibt man das Wort richtig?",
    answers: ["Fahrrad", "Farrad", "Fahrat", "Fahrraht"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fahrrad kommt von 'fahren' und 'Rad' – daher doppeltes r."
  },
  {
    id: "q3_d_027",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wann schreibt man ein Wort groß?",
    answers: ["Bei Nomen und am Satzanfang", "Bei Verben und am Satzende", "Bei allen Wörtern über vier Buchstaben", "Bei Adjektiven und am Zeilenende"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nomen und der erste Buchstabe im Satz werden großgeschrieben."
  },
  {
    id: "q3_d_028",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie schreibt man die Mehrzahl von 'Baum'?",
    answers: ["Bäume", "Beume", "Beme", "Baume"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bäume ist die korrekte Schreibweise."
  },
  {
    id: "q3_d_029",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Vorsilbe macht aus dem Wort 'lesen' ein Wort für 'etwas falsch lesen'?",
    answers: ["ver-", "zer-", "aus-", "ent-"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Vorsilbe 'ver-' drückt oft ein Versehen aus (sich verlesen)."
  },
  {
    id: "q3_d_030",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wann nutzt man im Deutschen die Schreibweise mit 'ck' statt mit einfachem 'k'?",
    answers: ["Nach kurz gesprochenem Vokal", "Nach lang gesprochenem Vokal", "Immer am Ende eines Satzes", "Nur bei großgeschriebenen Nomen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach einem kurz gesprochenen Selbstlaut (Vokal) folgt 'ck' (z. B. Socke, Bäckerei)."
  },
  {
    id: "q3_d_031",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wann schreibt man 'tz' statt einfachem 'z'?",
    answers: ["Nach einem kurzen Vokal", "Nach einem langen Vokal", "Immer am Wortanfang", "Nur bei Verben"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Nach kurzem Selbstlaut steht 'tz' (Katze, Mütze)."
  },
  {
    id: "q3_d_032",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort schreibt man mit stummem Dehnungs-h?",
    answers: ["Zahn", "Sonne", "Kiste", "Wasser"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Das Dehnungs-h in 'Zahn' dehnt den Vokal 'a' lang."
  },
  {
    id: "q3_d_033",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort wird mit langem 'ie' geschrieben?",
    answers: ["Wiese", "Wisse", "Winter", "Wille"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein lang gesprochenes 'i' wird meist als 'ie' geschrieben (Wiese)."
  },
  {
    id: "q3_d_034",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches dieser Wörter schreibt man mit doppeltem Konsonanten?",
    answers: ["Sonne", "Sone", "Sahn", "Sonee"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kurzer Vokal 'o' -> doppelter Mitlaut 'nn' (Sonne)."
  },
  {
    id: "q3_d_035",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Aus welchem Wortstamm besteht die Wortfamilie 'Fahrrad, Fahrer, fahrbar'?",
    answers: ["fahr", "rad", "ren", "flug"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der gemeinsame Wortstamm aller dieser Wörter heißt 'fahr'."
  },
  {
    id: "q3_d_036",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Nachsilbe (Morphem) macht aus dem Adjektiv 'heiter' ein Nomen?",
    answers: ["-keit", "-ung", "-nis", "-schaft"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "heiter + -keit = die Heiterkeit."
  },
  {
    id: "q3_d_037",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Nachsilbe macht aus dem Nomen 'Freund' ein Adjektiv?",
    answers: ["-lich", "-ung", "-heit", "-nis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Freund + -lich = freundlich."
  },
  {
    id: "q3_d_038",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Vokal fehlt beim Wort 'Kön_g'?",
    answers: ["i", "e", "a", "u"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "König wird mit 'i' vor dem 'g' geschrieben."
  },
  {
    id: "q3_d_039",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Endbuchstabe ist richtig: 'Korb' oder 'Korp'? Verlängere zu 'Körbe'.",
    answers: ["b", "p", "g", "k"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Verlängerung 'Kör-be' zeigt deutlich das 'b'."
  },
  {
    id: "q3_d_040",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Endung ist bei 'Schran_k' richtig? Verlängere zu 'Schränke'.",
    answers: ["k", "g", "ck", "gk"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Schrän-ke zeigt, dass man das Wort mit 'k' schreibt."
  },
  {
    id: "q3_d_041",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie trennt man das Wort 'Sommer' richtig am Zeilenende?",
    answers: ["Som-mer", "So-mmer", "Somm-er", "S-ommer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Doppelte Konsonanten werden getrennt: Som-mer."
  },
  {
    id: "q3_d_042",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches dieser Wörter enthält eine Vorsilbe?",
    answers: ["ge-wonnen", "Garten", "Gabel", "Gurke"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'ge-' ist die Vorsilbe beim Partizip gewonnen."
  },
  {
    id: "q3_d_043",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches dieser Wörter steht im Wörterbuch an erster Stelle?",
    answers: ["Bär", "Biene", "Brot", "Butter"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "B-ä-r kommt nach dem Alphabet vor B-i, B-r und B-u."
  },
  {
    id: "q3_d_044",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort ist richtig geschrieben?",
    answers: ["Schiff", "Schif", "Schihf", "Schiffh"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Kurzer Vokal 'i' -> doppel-f: Schiff."
  },
  {
    id: "q3_d_045",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Schreibweise ist richtig: Bäcker oder Becker?",
    answers: ["Bäcker", "Becker", "Beker", "Bäker"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bäcker kommt vom Wortstamm 'backen' (a wird zu ä, ck nach kurzem Vokal)."
  },
  {
    id: "q3_d_046",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie lautet die Auslautprobe für das Wort 'Wald'?",
    answers: ["Wälder (mit 'd')", "Walde (mit 't')", "Waldig (mit 't')", "Walds (mit 'tz')"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Mehrzahl 'Wäl-der' lässt das 'd' deutlich hören."
  },
  {
    id: "q3_d_047",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Warum schreibt man 'Häuser' mit 'äu'?",
    answers: ["Weil die Einzahl 'Haus' mit 'au' geschrieben wird", "Weil 'äu' immer am Wortanfang steht", "Weil es ein Verb ist", "Weil man kein 'eu' kennt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ableitung: Aus dem 'au' in Haus wird in der Mehrzahl der Umlaut 'äu'."
  },
  {
    id: "q3_d_048",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches dieser Wörter schreibt man mit 'ss'?",
    answers: ["Fluss", "Fluß", "Flus", "Flush"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Nach kurzem Vokal schreibt man 'ss' (Fluss)."
  },
  {
    id: "q3_d_049",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort schreibt man mit 'ß' nach langem Vokal?",
    answers: ["Straße", "Strasse", "Strase", "Strasze"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Nach einem langen Vokal (a) steht ein 'ß' (Straße)."
  },
  {
    id: "q3_d_050",
    category: "k3_deutsch",
    topic: "rechtschreibung_bausteine",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort enthält den Nomen-Baustein '-heit'?",
    answers: ["Freiheit", "Freiung", "Freischaft", "Freikheit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Frei + -heit = Freiheit."
  },

  // ================================================================
  // 3. SATZGLIEDER (SUBJEKT & PRÄDIKAT) (25 Fragen)
  // ================================================================
  {
    id: "q3_d_051",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher dieser Sätze ist ein Aufforderungssatz (Befehlssatz)?",
    answers: ["Räum bitte sofort dein Zimmer auf!", "Kommst du heute zum Spielplatz?", "Wir gehen zusammen auf den Spielplatz.", "Wann fängt die Schule morgen an?"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Aufforderungssätze verlangen etwas und enden meist mit einem Ausrufezeichen (!)."
  },
  {
    id: "q3_d_052",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie fragt man nach dem Satzglied 'Subjekt' (Satzgegenstand)?",
    answers: ["Wer oder was?", "Was tut das Subjekt?", "Wann?", "Wo?"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Subjekt erfragt man immer mit: Wer oder was?"
  },
  {
    id: "q3_d_053",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie fragt man nach dem Satzglied 'Prädikat' (Satzaussage)?",
    answers: ["Was tut das Subjekt?", "Wer oder was?", "Wie ist etwas?", "Warum?"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Prädikat erfragt man mit: Was tut jemand / was geschieht?"
  },
  {
    id: "q3_d_054",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Subjekt im Satz: 'Der kleine Hund bellt laut'?",
    answers: ["Der kleine Hund", "bellt", "laut", "Hund bellt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wer oder was bellt laut? -> Der kleine Hund."
  },
  {
    id: "q3_d_055",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Prädikat im Satz: 'Die Kinder spielen im Park'?",
    answers: ["spielen", "Die Kinder", "im Park", "Park"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Was tun die Kinder? -> spielen."
  },
  {
    id: "q3_d_056",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Subjekt im Satz: 'Heute liest Oma ein Buch'?",
    answers: ["Oma", "Heute", "liest", "ein Buch"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wer liest ein Buch? -> Oma."
  },
  {
    id: "q3_d_057",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Prädikat im Satz: 'Der Vogel fliegt hoch am Himmel'?",
    answers: ["fliegt", "Der Vogel", "hoch", "am Himmel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Was tut der Vogel? -> fliegt."
  },
  {
    id: "q3_d_058",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Satzzeichen verwendet man bei Aufzählungen von Wörtern?",
    answers: ["Komma (,)", "Punkt (.)", "Fragezeichen (?)", "Ausrufezeichen (!)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Aufzählungen werden durch Kommas getrennt."
  },
  {
    id: "q3_d_059",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Satzzeichen gehört am Ende eines Befehlssatzes?",
    answers: ["Ausrufezeichen (!)", "Punkt (.)", "Fragezeichen (?)", "Komma (,)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Befehle und Ausrufe enden mit einem Ausrufezeichen (!)."
  },
  {
    id: "q3_d_060",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Satzzeichen fehlt an der Lücke: 'Auf dem Tisch liegen Stifte__ Hefte und Bücher.'?",
    answers: ["Komma (,)", "Punkt (.)", "Fragezeichen (?)", "Doppelpunkt (:)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Aufzählung (Stifte, Hefte und Bücher) gehört dort ein Komma hin."
  },
  {
    id: "q3_d_061",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Satz ist grammatikalisch vollständig und enthält Subjekt und Prädikat?",
    answers: ["Der Junge schläft.", "Der lange Weg.", "Gestern im Wald.", "Sehr schnell und bunt."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Der Junge schläft.' hat ein Subjekt (Der Junge) und ein Prädikat (schläft)."
  },
  {
    id: "q3_d_062",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Satzglied besteht immer aus dem Verb des Satzes?",
    answers: ["Prädikat", "Subjekt", "Objekt", "Ortsangabe"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Prädikat ist das Verb in einem Satz."
  },
  {
    id: "q3_d_063",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Subjekt im Satz: 'Jeden Morgen kräht der Hahn'?",
    answers: ["der Hahn", "Jeden Morgen", "kräht", "Morgen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wer oder was kräht? -> der Hahn."
  },
  {
    id: "q3_d_064",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Prädikat im Satz: 'Die Sonne scheint den ganzen Tag'?",
    answers: ["scheint", "Die Sonne", "den ganzen Tag", "Tag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Was tut die Sonne? -> scheint."
  },
  {
    id: "q3_d_065",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie nennt man die Probe, bei der man die Bausteine eines Satzes verschiebt?",
    answers: ["Umstellprobe / Verschiebeprobe", "Verlängerungsprobe", "Ersatzprobe", "Leseprobe"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Mit der Umstellprobe findet man heraus, welche Wörter zusammen ein Satzglied bilden."
  },
  {
    id: "q3_d_066",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Wörter bilden zusammen EIN Satzglied: 'In den Sommerferien reisen wir nach Italien.'?",
    answers: ["In den Sommerferien", "In den", "reisen wir", "nach Italien reisen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'In den Sommerferien' lässt sich nur als kompletter Block verschieben."
  },
  {
    id: "q3_d_067",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Wort bildet das Prädikat im Satz: 'Wir backen heute Plätzchen'?",
    answers: ["backen", "Wir", "heute", "Plätzchen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Verb 'backen' ist das Prädikat."
  },
  {
    id: "q3_d_068",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Subjekt im Satz: 'Gestern hat der Lehrer die Arbeiten verteilt'?",
    answers: ["der Lehrer", "Gestern", "hat verteilt", "die Arbeiten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Wer hat die Arbeiten verteilt? -> der Lehrer."
  },
  {
    id: "q3_d_069",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Satzzeichen steht vor der wörtlichen Rede direkt nach dem Begleitsatz 'Er rief:'?",
    answers: ["Doppelpunkt (:)", "Komma (,)", "Punkt (.)", "Semikolon (;)"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Nach dem Begleitsatz steht ein Doppelpunkt (:)."
  },
  {
    id: "q3_d_070",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie kennzeichnet man die gesprochenen Worte in der wörtlichen Rede?",
    answers: ["Mit Anführungszeichen („ ... “)", "Mit Fragezeichen", "Mit Ausrufezeichen", "Mit Klammern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Wörtliche Rede steht in Anführungszeichen („...“)."
  },
  {
    id: "q3_d_071",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Satz zeigt die RICHTIGE Zeichensetzung bei wörtlicher Rede?",
    answers: ["Sie rief: „Komm schnell!“", "Sie rief Komm schnell!", "Sie rief: Komm schnell.", "Sie rief, „Komm schnell“."],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Begleitsatz + Doppelpunkt + Anführungszeichen unten + Satzzeichen + Anführungszeichen oben."
  },
  {
    id: "q3_d_072",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie nennt man einen Satz, der eine Information erfragt?",
    answers: ["Fragesatz", "Aussagesatz", "Aufforderungssatz", "Ausrufesatz"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Fragesatz erfragt Informationen und endet mit einem Fragezeichen (?)."
  },
  {
    id: "q3_d_073",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist das Prädikat im Satz: 'Die Katzen schlafen friedlich'?",
    answers: ["schlafen", "Die Katzen", "friedlich", "Katzen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Was tun die Katzen? -> schlafen."
  },
  {
    id: "q3_d_074",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Aus wie vielen Satzgliedern besteht der Satz: 'Der Hund / schläft / im Garten.'?",
    answers: ["3 Satzglieder", "2 Satzglieder", "4 Satzglieder", "1 Satzglied"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "1. Der Hund (Subjekt), 2. schläft (Prädikat), 3. im Garten (Ortsangabe)."
  },
  {
    id: "q3_d_075",
    category: "k3_deutsch",
    topic: "satzglieder",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Satz steht in einer richtigen Satzglied-Reihenfolge?",
    answers: ["Morgen fahren wir in den Zoo.", "Wir morgen fahren in den Zoo.", "In den Zoo morgen fahren wir.", "Fahren in den Zoo morgen wir."],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Morgen fahren wir in den Zoo.' bildet eine grammatikalisch korrekte Satzstruktur."
  },

  // ================================================================
  // 4. TEXTE, MÄRCHEN & LESEVERSTÄNDNIS (25 Fragen)
  // ================================================================
  {
    id: "q3_d_076",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was ist die Hauptaufgabe einer Überschrift bei einem Sachtext?",
    answers: ["Den Inhalt kurz zusammenfassen oder neugierig machen", "Den Text möglichst lang machen", "Rechtschreibfehler verstecken", "Das Ende zu verraten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Überschrift zeigt dem Leser sofort, wovon der Text handelt."
  },
  {
    id: "q3_d_077",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie nennt man einen Text, der echte Fakten und Informationen über ein Thema (z. B. Tiere) liefert?",
    answers: ["Sachtext", "Märchen", "Gedicht", "Fabel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Sachtexte informieren sachlich über echte Themen."
  },
  {
    id: "q3_d_078",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Womit beginnen klassische Märchen der Brüder Grimm sehr häufig?",
    answers: ["„Es war einmal...“", "„Gestern passierte folgendes...“", "„Ende gut, alles gut...“", "„Sehr geehrte Damen und Herren...“"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Fast alle bekannten deutschen Märchen beginnen mit 'Es war einmal...'."
  },
  {
    id: "q3_d_079",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches dieser Merkmale passt typischerweise zu einem Märchen?",
    answers: ["Zauberei und fabelhafte Wesen (z. B. Hexen, Zwerge)", "Echte Flugpläne von Flugzeugen", "Kochrezepte", "Nachrichten aus der Zeitung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Märchen enthalten magische Elemente und Zauberei."
  },
  {
    id: "q3_d_080",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was bedeutet das Sprichwort: „Lügen haben kurze Beine“?",
    answers: ["Lügen fliegen schnell auf und kommen ans Licht", "Wer lügt, kann nicht schnell rennen", "Kleine Menschen lügen oft", "Lügen macht lange Beine"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Es bedeutet, dass die Wahrheit schnell herauskommt."
  },
  {
    id: "q3_d_081",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was bedeutet das Sprichwort: „Übung macht den Meister“?",
    answers: ["Wer viel übt, wird immer besser", "Nur Meister dürfen üben", "Man braucht nie wieder zu lernen", "Üben ist reine Zeitverschwendung"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Durch Ausdauer und Training lernt man eine Fähigkeit gut."
  },
  {
    id: "q3_d_082",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was versteht man unter 'Sinnabschnitten' in einem längeren Text?",
    answers: ["Absätze, die zusammengehörige Gedanken ordnen", "Sätze mit vielen Ausrufezeichen", "Lustige Witze im Text", "Seitenzahlen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Sinnabschnitte unterteilen einen Text übersichtlich in inhaltliche Blöcke."
  },
  {
    id: "q3_d_083",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wozu dient das Inhaltsverzeichnis am Anfang eines Buches?",
    answers: ["Um Kapitel und Seitenzahlen schnell zu finden", "Um Bilder auszumalen", "Um Rechtschreibfehler zu korrigieren", "Um das Buch zu verschließen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Inhaltsverzeichnis zeigt alle Themen und auf welcher Seite sie stehen."
  },
  {
    id: "q3_d_084",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Text ist eine Bastelanleitung?",
    answers: ["Eine Schritt-für-Schritt-Erklärung zum Selbermachen", "Eine erfundene Detektivgeschichte", "Ein Liebesgedicht", "Ein Zeitungsartikel über das Wetter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Anleitungen erklären Schritt für Schritt, wie man etwas baut oder bastelt."
  },
  {
    id: "q3_d_085",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welcher Texttyp erklärt Zutaten und Zubereitung eines Gerichts?",
    answers: ["Rezept", "Gedicht", "Märchen", "Steckbrief"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Koch- oder Backrezept nennt Zutaten und Schritte zum Kochen."
  },
  {
    id: "q3_d_086",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Märchen handelt von zwei Geschwistern im Lebkuchenhaus einer Hexe?",
    answers: ["Hänsel und Gretel", "Rotkäppchen", "Schneewittchen", "Aschenputtel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Hänsel und Gretel finden das Lebkuchenhaus im Wald."
  },
  {
    id: "q3_d_087",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Märchen handelt von einem Mädchen mit sehr langen Haaren in einem Turm?",
    answers: ["Rapunzel", "Dornröschen", "Frau Holle", "Der Froschkönig"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Rapunzel lässt ihr langes Haar vom Turm herunter."
  },
  {
    id: "q3_d_088",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Märchen handelt von einer Prinzessin, die sich an einer Spindel sticht und 100 Jahre schläft?",
    answers: ["Dornröschen", "Schneewittchen", "Rumpelstilzchen", "Sterntaler"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Dornröschen schläft 100 Jahre hinter einer Rosenhecke."
  },
  {
    id: "q3_d_089",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was liest man am Ende einer Fabel (Tiergeschichte) meist heraus?",
    answers: ["Eine Lehre oder Moral für das menschliche Zusammenleben", "Einen Einkaufszettel", "Eine Telefonnummer", "Ein Rechenbeispiel"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Fabeln belehren den Leser durch das Verhalten von sprechenden Tieren."
  },
  {
    id: "q3_d_090",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Eigenschaft wird in Fabeln dem Fuchs sehr oft zugeschrieben?",
    answers: ["Schlauheit und List", "Dummheit", "Müdigkeit", "Ängstlichkeit"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Reineke Fuchs gilt in Fabeln stets als schlau und listig."
  },
  {
    id: "q3_d_091",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was bedeutet das Sprichwort: „In der Not erkennt man seine Freunde“?",
    answers: ["Wahre Freunde helfen einem auch in schwierigen Situationen", "In der Not vergisst man Namen", "Freunde treffen sich nur im Urlaub", "Man hat keine Freunde"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Echte Freunde erweisen sich besonders in schweren Zeiten als verlässlich."
  },
  {
    id: "q3_d_092",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wozu dienen W-Fragen (Wer, Wo, Wann, Was) beim Lesen eines Textes?",
    answers: ["Um die wichtigsten Kerninformationen schnell zu verstehen", "Um das Buch auswendig zu lernen", "Um neue Wörter zu erfinden", "Um das Lesen zu verhindern"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "W-Fragen helfen, den Inhalt eines Textes gezielt zu erschließen."
  },
  {
    id: "q3_d_093",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie nennt man ein Buch, in dem man Wörter nach dem Alphabet nachschlagen kann?",
    answers: ["Wörterbuch / Duden", "Atlas", "Fotoalbum", "Tagebuch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Im Wörterbuch schlägt man die richtige Schreibweise nach."
  },
  {
    id: "q3_d_094",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie nennt man kurze informative Aufstellungen über eine Person oder ein Tier mit den wichtigsten Fakten?",
    answers: ["Steckbrief", "Märchen", "Gedicht", "Krimi"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Steckbrief fasst Stichpunkte wie Name, Größe, Nahrung übersichtlich zusammen."
  },
  {
    id: "q3_d_095",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was bedeutet der Begriff 'Strophe' bei einem Gedicht?",
    answers: ["Ein zusammenhängender Abschnitt aus mehreren Verszeilen", "Eine Überschrift", "Die letzte Seite eines Buches", "Der Name des Dichters"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mehrere Zeilen (Verse) bilden in einem Gedicht eine Strophe."
  },
  {
    id: "q3_d_096",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Wie nennt man die einzelnen Zeilen in einem Gedicht?",
    answers: ["Verse", "Sinnabschnitte", "Kapitel", "Paragraphen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Zeilen in Gedichten nennt man Verse."
  },
  {
    id: "q3_d_097",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welches Reimschema liegt vor bei: Haus – Maus / Sonne – Wonne?",
    answers: ["Paarreim (aabb)", "Kreuzreim (abab)", "Umarmender Reim (abba)", "Kein Reim"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Raimen sich zwei aufeinanderfolgende Zeilen paarweise, spricht man vom Paarreim."
  },
  {
    id: "q3_d_098",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Welche Zeichen helfen in Sachtexten, wichtige Stichpunkte übersichtlich aufzulisten?",
    answers: ["Spiegelstriche / Aufzählungspunkte", "Fragezeichen", "Ausrufezeichen", "Anführungszeichen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Spiegelstriche gliedern Stichpunkte übersichtlich."
  },
  {
    id: "q3_d_099",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was sind 'Schlüsselwörter' beim Lesen eines Sachtextes?",
    answers: ["Die wichtigsten Begriffe, die den Kern des Inhalts tragen", "Die schwersten Wörter im Duden", "Die Wörter am Satzanfang", "Nur Zahlen und Daten"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Schlüsselwörter enthalten die Hauptinformationen eines Textes."
  },
  {
    id: "q3_d_100",
    category: "k3_deutsch",
    topic: "leseverstaendnis_k3",
    area: "schule",
    grade: 3,
    subject: "deutsch",
    question: "Was versteht man unter 'überfliegendem Lesen'?",
    answers: ["Einen Text zügig durchlesen, um sich einen ersten Überblick zu verschaffen", "Lautes Vorlesen im Stehen", "Rückwärtslesen von Wörtern", "Ein Buch mit der Lupe betrachten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Überfliegendes Lesen verschafft schnell eine Vorstellung vom Gesamtthema."
  }
];