const K3_MATHE_QUESTIONS = [
  // ================================================================
  // 1. TAUSENDERRAUM & ORIENTIERUNG (25 Fragen)
  // ================================================================
  {
    id: "q3_m_001",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie heißt die Zahl, die aus 4 Hundertern, 2 Zehnern und 7 Einern besteht?",
    answers: ["427", "472", "247", "724"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4 Hunderter (400) + 2 Zehner (20) + 7 Einer (7) = 427."
  },
  {
    id: "q3_m_002",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist der Vorgänger der Zahl 500?",
    answers: ["499", "501", "490", "400"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Direkt vor der 500 steht die 499."
  },
  {
    id: "q3_m_003",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist der Nachfolger der Zahl 799?",
    answers: ["800", "798", "801", "790"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Auf 799 folgt beim Zählen die 800."
  },
  {
    id: "q3_m_004",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie lauten die Nachbarhunderter von 340?",
    answers: ["300 und 400", "330 und 350", "200 und 400", "300 und 500"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Hunderter davor ist 300, der Hunderter danach 400."
  },
  {
    id: "q3_m_005",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viel ist 100 - 30?",
    answers: ["70", "80", "90", "60"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 100 dreißig weggenommen bleiben 70."
  },
  {
    id: "q3_m_006",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Ergänze zum Tausender: 600 + __ = 1000",
    answers: ["400", "500", "300", "600"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "6 Hunderter + 4 Hunderter = 10 Hunderter (1000)."
  },
  {
    id: "q3_m_007",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Ergänze zum Tausender: 850 + __ = 1000",
    answers: ["150", "250", "100", "200"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "850 + 50 = 900, und noch 100 dazu = 1000. Zusammen 150."
  },
  {
    id: "q3_m_008",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche Zahl hat 7 Hunderter, 0 Zehner und 5 Einer?",
    answers: ["705", "750", "507", "75"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 Hunderter + 0 Zehner + 5 Einer = 705."
  },
  {
    id: "q3_m_009",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Zähle in 50er-Schritten: 150, 200, 250, __",
    answers: ["300", "260", "350", "280"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Immer +50: Auf 250 folgt die 300."
  },
  {
    id: "q3_m_010",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welches Zeichen passt: 608 __ 680?",
    answers: ["<", ">", "=", "+"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "608 ist kleiner als 680 (608 < 680)."
  },
  {
    id: "q3_m_011",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche Zahl liegt genau in der Mitte zwischen 400 und 500?",
    answers: ["450", "440", "460", "425"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Mitte von 400 und 500 ist 450."
  },
  {
    id: "q3_m_012",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie schreibt man 'siebenhundertdreiundfünfzig' als Zahl?",
    answers: ["753", "735", "573", "357"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 Hunderter, 5 Zehner und 3 Einer = 753."
  },
  {
    id: "q3_m_013",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Aus wie vielen Zehnern besteht ein Hunderter?",
    answers: ["10 Zehner", "100 Zehner", "5 Zehner", "20 Zehner"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 mal 10 = 100. Ein Hunderter hat 10 Zehner."
  },
  {
    id: "q3_m_014",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Aus wie vielen Hundertern besteht die Zahl 1000?",
    answers: ["10 Hunderter", "100 Hunderter", "5 Hunderter", "1 Hunderter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 Hunderter ergeben zusammen 1000."
  },
  {
    id: "q3_m_015",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie lauten die Nachbarzehner der Zahl 524?",
    answers: ["520 und 530", "500 und 600", "523 und 525", "510 und 530"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der Zehner vor 524 ist 520, der Zehner danach 530."
  },
  {
    id: "q3_m_016",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie lauten die Nachbarzehner der Zahl 893?",
    answers: ["890 und 900", "800 und 900", "880 und 900", "892 und 894"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Der reine Zehner davor ist 890, danach kommt 900."
  },
  {
    id: "q3_m_017",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welches ist der nächste reine Hunderter beim Aufwärtszählen nach der 612?",
    answers: ["700", "600", "620", "800"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der nächste volle Hunderter nach 612 ist 700."
  },
  {
    id: "q3_m_018",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche Zahl ist um 100 kleiner als 1000?",
    answers: ["900", "990", "800", "9000"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1000 - 100 = 900."
  },
  {
    id: "q3_m_019",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche Zahl ist um 50 größer als 450?",
    answers: ["500", "400", "550", "460"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "450 + 50 = 500."
  },
  {
    id: "q3_m_020",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche dieser Zahlen ist am größten: 309, 390, 903, 930?",
    answers: ["930", "903", "390", "309"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "930 hat die meisten Hunderter und Zehner."
  },
  {
    id: "q3_m_021",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche dieser Zahlen ist am kleinsten: 102, 120, 201, 210?",
    answers: ["102", "120", "201", "210"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "102 hat nur 1 Hunderter, 0 Zehner und 2 Einer."
  },
  {
    id: "q3_m_022",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist die kleinste dreistellige Zahl?",
    answers: ["100", "101", "99", "111"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "100 ist die erste dreistellige Zahl."
  },
  {
    id: "q3_m_023",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist die größte dreistellige Zahl?",
    answers: ["999", "1000", "990", "900"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "999 ist die höchste dreistellige Zahl vor der 1000."
  },
  {
    id: "q3_m_024",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welches Zeichen passt: 999 __ 1000?",
    answers: ["<", ">", "=", "+"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "999 ist kleiner als 1000 (999 < 1000)."
  },
  {
    id: "q3_m_025",
    category: "k3_mathe",
    topic: "tausenderraum",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Einer stecken in einem Hunderter?",
    answers: ["100 Einer", "10 Einer", "1000 Einer", "50 Einer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Hunderter besteht aus 100 Einern."
  },

  // ================================================================
  // 2. SCHRIFTLICHE & HALBSCHRIFTLICHE ADDITION & SUBTRAKTION (25 Fragen)
  // ================================================================
  {
    id: "q3_m_026",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 45 + 38?",
    answers: ["83", "73", "93", "103"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "45 + 30 = 75, plus 8 = 83."
  },
  {
    id: "q3_m_027",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ergibt die Addition 340 + 280 im Tausenderraum?",
    answers: ["620", "520", "640", "580"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "340 + 200 = 540; 540 + 80 = 620."
  },
  {
    id: "q3_m_028",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 250 + 350?",
    answers: ["600", "500", "550", "650"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "200 + 300 = 500, und 50 + 50 = 100 -> zusammen 600."
  },
  {
    id: "q3_m_029",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 720 - 150?",
    answers: ["570", "580", "630", "550"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "720 - 100 = 620, minus 50 = 570."
  },
  {
    id: "q3_m_030",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne schriftlich: 234 + 153",
    answers: ["387", "377", "397", "287"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4+3=7 (Einer), 3+5=8 (Zehner), 2+1=3 (Hunderter) -> 387."
  },
  {
    id: "q3_m_031",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne schriftlich mit Übertrag: 468 + 275",
    answers: ["743", "643", "733", "753"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "8+5=13 (3 an, 1 Übertrag), 6+7+1=14 (4 an, 1 Übertrag), 4+2+1=7 -> 743."
  },
  {
    id: "q3_m_032",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne schriftlich: 589 - 243",
    answers: ["346", "342", "246", "356"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "9-3=6, 8-4=4, 5-2=3 -> 346."
  },
  {
    id: "q3_m_033",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne schriftlich mit Entbündelung/Übertrag: 612 - 345",
    answers: ["267", "367", "277", "347"],
    correct: 0,
    difficulty: "schwer",
    points: 5,
    explanation: "612 minus 345 ergibt genau 267."
  },
  {
    id: "q3_m_034",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was bedeutet der 'Übertrag' bei der schriftlichen Addition?",
    answers: ["Dass ein Ergebnis ab 10 an den nächsten Stellenwert weitergegeben wird", "Dass man eine Zahl abziehen muss", "Dass man die Aufgabe vertauscht", "Dass das Ergebnis falsch ist"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Erreicht die Summe einer Spalte 10 oder mehr, wandert der Zehner als Übertrag nach links."
  },
  {
    id: "q3_m_035",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 500 - 120?",
    answers: ["380", "390", "420", "350"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "500 - 100 = 400, minus 20 = 380."
  },
  {
    id: "q3_m_036",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 180 + 240?",
    answers: ["420", "410", "430", "320"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "180 + 200 = 380, plus 40 = 420."
  },
  {
    id: "q3_m_037",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 900 - 450?",
    answers: ["450", "500", "400", "550"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Hälfte von 900 ist 450."
  },
  {
    id: "q3_m_038",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 630 + 70?",
    answers: ["700", "690", "710", "600"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "30 + 70 = 100 -> 600 + 100 = 700."
  },
  {
    id: "q3_m_039",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 1000 - 250?",
    answers: ["750", "850", "650", "700"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1000 - 200 = 800, minus 50 = 750."
  },
  {
    id: "q3_m_040",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 410 + 190?",
    answers: ["600", "500", "610", "590"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "10 + 90 = 100, plus 400 + 100 = 600."
  },
  {
    id: "q3_m_041",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Probe der Subtraktion: 800 - 300 = 500. Wie lautet die Umkehraufgabe?",
    answers: ["500 + 300 = 800", "800 + 300 = 1100", "500 - 300 = 200", "300 + 300 = 600"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit der Umkehraufgabe (Addition) überprüft man eine Minusaufgabe."
  },
  {
    id: "q3_m_042",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Schriftlich addieren mit drei Zahlen: 125 + 342 + 211 =",
    answers: ["678", "668", "688", "578"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Einer: 5+2+1=8, Zehner: 2+4+1=7, Hunderter: 1+3+2=6 -> 678."
  },
  {
    id: "q3_m_043",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 350 - 80?",
    answers: ["270", "280", "260", "330"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "350 - 50 = 300, minus 30 = 270."
  },
  {
    id: "q3_m_044",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 480 + 60?",
    answers: ["540", "530", "550", "440"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "480 + 20 = 500, plus 40 = 540."
  },
  {
    id: "q3_m_045",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welcher Überschlag passt am besten zu 398 + 203?",
    answers: ["400 + 200 = 600", "300 + 200 = 500", "400 + 300 = 700", "350 + 250 = 600"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "398 ist nah an 400, 203 ist nah an 200 -> Überschlag 400 + 200 = 600."
  },
  {
    id: "q3_m_046",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welcher Überschlag passt am besten zu 891 - 304?",
    answers: ["900 - 300 = 600", "800 - 300 = 500", "900 - 400 = 500", "850 - 300 = 550"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "891 ist etwa 900, 304 ist etwa 300 -> 900 - 300 = 600."
  },
  {
    id: "q3_m_047",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche Zahl fehlt: 150 + __ = 400?",
    answers: ["250", "300", "200", "150"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "400 - 150 = 250."
  },
  {
    id: "q3_m_048",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welche Zahl fehlt: 600 - __ = 220?",
    answers: ["380", "320", "480", "280"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "600 - 220 = 380."
  },
  {
    id: "q3_m_049",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Tauschaufgabe: Wenn 230 + 470 = 700 ist, was ist dann 470 + 230?",
    answers: ["700", "600", "800", "240"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Bei der Addition darf man die Summandentauschen, das Ergebnis bleibt 700."
  },
  {
    id: "q3_m_050",
    category: "k3_mathe",
    topic: "schriftliche_addition_subtraktion",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 840 - 390?",
    answers: ["450", "460", "550", "440"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "840 - 400 = 440, plus 10 (da 10 zu viel abgezogen) = 450."
  },

  // ================================================================
  // 3. MULTIPLIKATION & DIVISION (25 Fragen)
  // ================================================================
  {
    id: "q3_m_051",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 6 × 7?",
    answers: ["42", "36", "48", "54"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Einmaleins: 6 × 7 = 42."
  },
  {
    id: "q3_m_052",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 100 : 4?",
    answers: ["25", "20", "30", "35"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4 × 25 = 100, also ist 100 : 4 = 25."
  },
  {
    id: "q3_m_053",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 4 × 5?",
    answers: ["20", "25", "15", "30"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4 mal 5 ergibt 20."
  },
  {
    id: "q3_m_054",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist die Hälfte von 14?",
    answers: ["7", "8", "6", "9"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "14 geteilt durch 2 ergibt 7."
  },
  {
    id: "q3_m_055",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist das Ergebnis mit Rest bei der geteilt-Aufgabe 23 : 5?",
    answers: ["4 Rest 3", "4 Rest 1", "5 Rest 2", "3 Rest 8"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4 × 5 = 20. Bis zur 23 bleiben genau 3 Rest."
  },
  {
    id: "q3_m_056",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 8 × 7?",
    answers: ["56", "54", "64", "48"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "8 × 7 = 56."
  },
  {
    id: "q3_m_057",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 9 × 6?",
    answers: ["54", "56", "63", "45"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "9 × 6 = 54."
  },
  {
    id: "q3_m_058",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 7 × 7?",
    answers: ["49", "42", "56", "48"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "7 mal 7 ist 49."
  },
  {
    id: "q3_m_059",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 8 × 8?",
    answers: ["64", "56", "72", "68"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "8 mal 8 ergibt 64."
  },
  {
    id: "q3_m_060",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Quadrataufgabe: Was ist 9 × 9?",
    answers: ["81", "72", "90", "89"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "9 mal 9 = 81."
  },
  {
    id: "q3_m_061",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne halbschriftlich: 4 × 12 =",
    answers: ["48", "44", "52", "46"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "4 × 10 = 40 und 4 × 2 = 8 -> 40 + 8 = 48."
  },
  {
    id: "q3_m_062",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne halbschriftlich: 3 × 24 =",
    answers: ["72", "62", "74", "82"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "3 × 20 = 60 und 3 × 4 = 12 -> 60 + 12 = 72."
  },
  {
    id: "q3_m_063",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechne halbschriftlich: 5 × 16 =",
    answers: ["80", "75", "85", "90"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "5 × 10 = 50 und 5 × 6 = 30 -> 50 + 30 = 80."
  },
  {
    id: "q3_m_064",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 30 : 6?",
    answers: ["5", "6", "4", "7"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "5 × 6 = 30."
  },
  {
    id: "q3_m_065",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 48 : 8?",
    answers: ["6", "7", "5", "8"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "6 × 8 = 48."
  },
  {
    id: "q3_m_066",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 63 : 7?",
    answers: ["9", "8", "7", "6"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "9 × 7 = 63."
  },
  {
    id: "q3_m_067",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist 72 : 9?",
    answers: ["8", "7", "9", "6"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "8 × 9 = 72."
  },
  {
    id: "q3_m_068",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Division mit Rest: Was ist 17 : 3?",
    answers: ["5 Rest 2", "5 Rest 1", "4 Rest 3", "6 Rest 0"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "5 × 3 = 15. Von 15 bis 17 fehlen noch 2 Rest."
  },
  {
    id: "q3_m_069",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Division mit Rest: Was ist 29 : 4?",
    answers: ["7 Rest 1", "6 Rest 5", "7 Rest 2", "8 Rest 1"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "7 × 4 = 28. Bleibt genau 1 Rest."
  },
  {
    id: "q3_m_070",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Division mit Rest: Was ist 38 : 6?",
    answers: ["6 Rest 2", "6 Rest 1", "5 Rest 3", "7 Rest 2"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "6 × 6 = 36. Es bleiben 2 Rest."
  },
  {
    id: "q3_m_071",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechnen mit Zehnerzahlen: Was ist 3 × 40?",
    answers: ["120", "140", "100", "1200"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "3 × 4 = 12 -> mit Null anhängen: 120."
  },
  {
    id: "q3_m_072",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechnen mit Zehnerzahlen: Was ist 6 × 50?",
    answers: ["300", "250", "350", "3000"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "6 × 5 = 30 -> Null anhängen: 300."
  },
  {
    id: "q3_m_073",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechnen mit Zehnerzahlen: Was ist 200 : 4?",
    answers: ["50", "40", "60", "20"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "20 : 4 = 5 -> Null anhängen: 50."
  },
  {
    id: "q3_m_074",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Rechnen mit Zehnerzahlen: Was ist 360 : 6?",
    answers: ["60", "50", "70", "600"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "36 : 6 = 6 -> Null anhängen: 60."
  },
  {
    id: "q3_m_075",
    category: "k3_mathe",
    topic: "multiplikation_division_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was ist die Umkehraufgabe von 56 : 8 = 7?",
    answers: ["7 × 8 = 56", "56 - 8 = 48", "8 + 7 = 15", "56 × 8 = 448"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Umkehraufgabe der Division ist die Multiplikation (7 × 8 = 56)."
  },

  // ================================================================
  // 4. GRÖSSEN, MESSEN & GEOMETRIE (25 Fragen)
  // ================================================================
  {
    id: "q3_m_076",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Ecken hat ein Rechteck?",
    answers: ["4", "3", "5", "6"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Rechteck hat vier Ecken und vier Seiten."
  },
  {
    id: "q3_m_077",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Zentimeter sind 1 Meter?",
    answers: ["100", "10", "1000", "1090"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Meter sind genau 100 Zentimeter."
  },
  {
    id: "q3_m_078",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Zentimeter sind 2 m?",
    answers: ["200 cm", "20 cm", "2000 cm", "100 cm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 m = 100 cm, also 2 m = 200 cm."
  },
  {
    id: "q3_m_079",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Ecken hat ein Dreieck?",
    answers: ["3", "4", "5", "6"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Dreieck hat genau 3 Ecken."
  },
  {
    id: "q3_m_080",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welcher geometrische Körper hat 6 rechteckige Flächen, 8 Ecken und 12 Kanten?",
    answers: ["Quader", "Zylinder", "Kugel", "Pyramide"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Der Quader hat 6 Begrenzungsflächen, 8 Ecken und 12 Kanten."
  },
  {
    id: "q3_m_081",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Millimeter (mm) stecken in genau 5 Zentimetern (cm)?",
    answers: ["50 mm", "5 mm", "500 mm", "10 mm"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 cm entspricht 10 mm. Folglich sind 5 cm = 50 mm."
  },
  {
    id: "q3_m_082",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Meter (m) entsprechen genau 1 Kilometer (km)?",
    answers: ["1000 m", "100 m", "10 m", "500 m"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Wort 'Kilo' bedeutet 1000: 1 km = 1000 Meter."
  },
  {
    id: "q3_m_083",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Gramm (g) wiegt 1 Kilogramm (kg)?",
    answers: ["1000 g", "100 g", "500 g", "10 g"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 kg wiegt genau 1000 Gramm."
  },
  {
    id: "q3_m_084",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Milliliter (ml) sind 1 Liter (l)?",
    answers: ["1000 ml", "100 ml", "500 ml", "10 ml"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 Liter besteht aus 1000 Millilitern."
  },
  {
    id: "q3_m_085",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welches Messgerät nutzt man zur Messung des Gewichts von Äpfeln?",
    answers: ["Waage", "Lineal", "Uhr", "Thermometer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Gewichte (in Gramm oder Kilogramm) misst man mit einer Waage."
  },
  {
    id: "q3_m_086",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welches Gefäß fasst typischerweise etwa 1 Liter Flüssigkeit?",
    answers: ["Eine Milchtüte", "Ein Teelöffel", "Ein Badesee", "Einfache Mülltonne"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine gewöhnliche Packung Milch oder Saft fasst genau 1 Liter."
  },
  {
    id: "q3_m_087",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Kanten hat ein Würfel?",
    answers: ["12 Kanten", "8 Kanten", "6 Kanten", "10 Kanten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Würfel besitzt 12 gleich lange Kanten."
  },
  {
    id: "q3_m_088",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele quadratische Flächen hat ein Spielwürfel?",
    answers: ["6 Flächen", "4 Flächen", "8 Flächen", "12 Flächen"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Würfel hat 6 quadratische Außenseiten."
  },
  {
    id: "q3_m_089",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was versteht man unter einem 'Würfelnetz'?",
    answers: ["Eine flache Figur aus 6 zusammenhängenden Quadraten, die man zum Würfel falten kann", "Ein Fischernetz aus Metall", "Eine Zeichnung eines Kaskadendreiecks", "Ein Ballnetz"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Kappt man die Kanten eines Würfels auf und legt ihn flach hin, entsteht ein Würfelnetz."
  },
  {
    id: "q3_m_090",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Sekunden hat eine Minute?",
    answers: ["60 Sekunden", "100 Sekunden", "30 Sekunden", "12 Sekunden"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Minute besteht aus genau 60 Sekunden."
  },
  {
    id: "q3_m_091",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Minuten dauert eine reguläre Schulstunde gewöhnlich?",
    answers: ["45 Minuten", "60 Minuten", "30 Minuten", "90 Minuten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Schulstunde dauert in der Regel 45 Minuten."
  },
  {
    id: "q3_m_092",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Paul geht um 14:15 Uhr los und kommt um 14:45 Uhr an. Wie lange war er unterwegs?",
    answers: ["30 Minuten", "15 Minuten", "45 Minuten", "1 Stunde"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Von 14:15 Uhr bis 14:45 Uhr vergehen genau 30 Minuten."
  },
  {
    id: "q3_m_093",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Meter fehlen bei 750 Meter noch bis zu 1 Kilometer?",
    answers: ["250 m", "350 m", "150 m", "500 m"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 km = 1000 m. 1000 m - 750 m = 250 m."
  },
  {
    id: "q3_m_094",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Gramm fehlen bei 600 Gramm noch bis zu 1 Kilogramm?",
    answers: ["400 g", "300 g", "500 g", "200 g"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "1 kg = 1000 g. 1000 g - 600 g = 400 g."
  },
  {
    id: "q3_m_095",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wofür steht die Längenabkürzung 'km'?",
    answers: ["Kilometer", "Kilo-Metermaß", "Kleinmeter", "Kreismeter"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'km' ist die offizielle Abkürzung für Kilometer."
  },
  {
    id: "q3_m_096",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wofür steht die Gewichtsabkürzung 'kg'?",
    answers: ["Kilogramm", "Kleingramm", "Kreisgewicht", "Kilo-Grammometer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'kg' steht für Kilogramm."
  },
  {
    id: "q3_m_097",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Was zeichnet eine achsensymmetrische Figur aus?",
    answers: ["Man kann sie an einer Spiegelachse deckungsgleich falten oder spiegeln", "Sie ist immer rund", "Sie hat keine Ecken", "Sie besteht nur aus Strichen"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "Achsensymmetrische Figuren besitzen mindestens eine Symmetrieachse."
  },
  {
    id: "q3_m_098",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Welches Arbeitsmittel nutzt man im Geometrieunterricht besonders zum Zeichnen von rechten Winkeln und geraden Linien?",
    answers: ["Geodreieck / Lineal", "Zirkel", "Schere", "Klebestift"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Mit dem Geodreieck zeichnet und misst man Winkel und Linien."
  },
  {
    id: "q3_m_099",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Ecken hat ein Zylinder (z. B. eine Konservendose)?",
    answers: ["0 Ecken", "2 Ecken", "4 Ecken", "8 Ecken"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Ein Zylinder hat runde Grund- und Deckflächen und besitzt keine spitzen Ecken."
  },
  {
    id: "q3_m_100",
    category: "k3_mathe",
    topic: "groessen_geometrie_k3",
    area: "schule",
    grade: 3,
    subject: "mathe",
    question: "Wie viele Kanten und Ecken hat eine perfekte Kugel?",
    answers: ["0 Ecken und 0 Kanten", "1 Ecke und 1 Kante", "2 Ecken und 0 Kanten", "4 Ecken und 4 Kanten"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Eine Kugel hat eine durchgehend gebogene Oberfläche, aber weder Ecken noch Kanten."
  }
];