const K3_ENGLISCH_QUESTIONS = [
  // ================================================================
  // 1. FAMILY, FRIENDS & FEELINGS (25 Fragen)
  // ================================================================
  {
    id: "q3_e_001",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Hund' auf Englisch?",
    answers: ["cat", "dog", "fish", "bird"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "Hund heißt auf Englisch 'dog'."
  },
  {
    id: "q3_e_002",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie sagt man 'Guten Morgen' auf Englisch?",
    answers: ["Good evening", "Good morning", "Goodbye", "Good night"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'Good morning' bedeutet Guten Morgen."
  },
  {
    id: "q3_e_003",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie geht es weiter: one, two, __?",
    answers: ["five", "four", "three", "seven"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Die Zahlenfolge lautet: one (1), two (2), three (3)."
  },
  {
    id: "q3_e_004",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Katze' auf Englisch?",
    answers: ["cat", "fish", "dog", "bird"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'cat' ist die englische Übersetzung für Katze."
  },
  {
    id: "q3_e_005",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'big'?",
    answers: ["klein", "neu", "groß", "alt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'big' bedeutet groß."
  },
  {
    id: "q3_e_006",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie sagt man 'Hallo' auf Englisch?",
    answers: ["Goodbye", "Good night", "Good evening", "Hello"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Hello' oder 'Hi' bedeutet Hallo."
  },
  {
    id: "q3_e_007",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welches Tier verbirgt sich hinter dem englischen Wort 'rabbit'?",
    answers: ["Katze im Alltag", "Hund zur Auswahl", "Vogel im Alltag", "Kaninchen / Hase"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'rabbit' heißt Kaninchen."
  },
  {
    id: "q3_e_008",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'mother'?",
    answers: ["Bruder", "Vater", "Schwester", "Mutter"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'mother' (oder 'mum') heißt Mutter."
  },
  {
    id: "q3_e_009",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'father'?",
    answers: ["Vater", "Bruder", "Mutter", "Onkel"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'father' (oder 'dad') heißt Vater."
  },
  {
    id: "q3_e_010",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Schwester' auf Englisch?",
    answers: ["sister", "aunt", "mother", "brother"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'sister' ist die englische Bezeichnung für Schwester."
  },
  {
    id: "q3_e_011",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Bruder' auf Englisch?",
    answers: ["brother", "uncle", "father", "sister"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'brother' bedeutet Bruder."
  },
  {
    id: "q3_e_012",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Gefühl 'happy'?",
    answers: ["wütend in der Praxis", "traurig in der Praxis", "glücklich / fröhlich", "müde in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'happy' heißt glücklich."
  },
  {
    id: "q3_e_013",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Gefühl 'sad'?",
    answers: ["glücklich", "müde", "hungrig", "traurig"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'sad' heißt traurig."
  },
  {
    id: "q3_e_014",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'tired' im Satz 'I am tired'?",
    answers: ["hungrig", "durstig", "müde", "böse"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'tired' heißt müde."
  },
  {
    id: "q3_e_015",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Freund' oder 'Freundin' auf Englisch?",
    answers: ["family", "baby", "teacher", "friend"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'friend' heißt Freund/Freundin."
  },
  {
    id: "q3_e_016",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was ist das Gegenteil von 'big'?",
    answers: ["small", "tall", "long", "old"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "Das Gegenteil von big (groß) ist small (klein)."
  },
  {
    id: "q3_e_017",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Großmutter / Oma' auf Englisch?",
    answers: ["sister in der Praxis", "grandmother / grandma", "mother in der Praxis", "grandfather im Alltag"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'grandmother' (kurz: grandma) ist die Oma."
  },
  {
    id: "q3_e_018",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Großvater / Opa' auf Englisch?",
    answers: ["father in der Praxis", "grandmother im Alltag", "grandfather / grandpa", "brother in der Praxis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'grandfather' (kurz: grandpa) heißt Opa."
  },
  {
    id: "q3_e_019",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie frage ich jemanden 'Wie heißt du?' auf Englisch?",
    answers: ["How are you?", "How old are you?", "What is your name?", "Where are you?"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'What is your name?' fragt nach dem Namen."
  },
  {
    id: "q3_e_020",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie frage ich jemanden 'Wie geht es dir?' auf Englisch?",
    answers: ["How old are you?", "What is your name?", "Where do you live?", "How are you?"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'How are you?' heißt 'Wie geht es dir?'."
  },
  {
    id: "q3_e_021",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'hungry'?",
    answers: ["müde", "traurig", "hungrig", "durstig"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'hungry' bedeutet hungrig."
  },
  {
    id: "q3_e_022",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'thirsty'?",
    answers: ["wütend", "durstig", "hungrig", "ängstlich"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'thirsty' bedeutet durstig."
  },
  {
    id: "q3_e_023",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie sagt man 'Auf Wiedersehen' auf Englisch?",
    answers: ["Goodbye", "Hello", "Good morning", "Please"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Goodbye' (oder 'Bye-bye') heißt Auf Wiedersehen."
  },
  {
    id: "q3_e_024",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt das Wort 'boy' auf Deutsch?",
    answers: ["Mann", "Junge", "Mädchen", "Kind"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'boy' heißt Junge."
  },
  {
    id: "q3_e_025",
    category: "k3_englisch",
    topic: "family_feelings",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt das Wort 'girl' auf Deutsch?",
    answers: ["Frau", "Junge", "Mädchen", "Kind"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'girl' bedeutet Mädchen."
  },

  // ================================================================
  // 2. WEATHER, MONTHS & SEASONS (25 Fragen)
  // ================================================================
  {
    id: "q3_e_026",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Montag' auf Englisch?",
    answers: ["Monday", "Friday", "Tuesday", "Sunday"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Monday' ist der Montag."
  },
  {
    id: "q3_e_027",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Sonntag' auf Englisch?",
    answers: ["Thursday", "Monday", "Saturday", "Sunday"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Sunday' ist der Sonntag."
  },
  {
    id: "q3_e_028",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Freitag' auf Englisch?",
    answers: ["Sunday", "Tuesday", "Wednesday", "Friday"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'Friday' ist der Freitag."
  },
  {
    id: "q3_e_029",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'sun'?",
    answers: ["Regen", "Mond", "Sonne", "Wolke"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'sun' heißt Sonne."
  },
  {
    id: "q3_e_030",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'rain'?",
    answers: ["Regen", "Sonne", "Schnee", "Wind"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'rain' heißt Regen."
  },
  {
    id: "q3_e_031",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'snow'?",
    answers: ["Nebel", "Hagel", "Schnee", "Eis"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'snow' bedeutet Schnee."
  },
  {
    id: "q3_e_032",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'sunny' im Satz 'It is sunny today'?",
    answers: ["regnerisch", "sonnig", "kalt", "windig"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'sunny' bedeutet sonnig."
  },
  {
    id: "q3_e_033",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'rainy'?",
    answers: ["regnerisch", "heiß", "sonnig", "schneebedeckt"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'rainy' bedeutet regnerisch."
  },
  {
    id: "q3_e_034",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'windy'?",
    answers: ["wolkig", "windig", "kalt", "warm"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'windy' bedeutet windig."
  },
  {
    id: "q3_e_035",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welche Jahreszeit heißt auf Englisch 'summer'?",
    answers: ["Herbst", "Frühling", "Sommer", "Winter"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'summer' ist der Sommer."
  },
  {
    id: "q3_e_036",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welche Jahreszeit heißt auf Englisch 'winter'?",
    answers: ["Winter", "Frühling", "Herbst", "Sommer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'winter' ist der Winter."
  },
  {
    id: "q3_e_037",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welche Jahreszeit heißt auf Englisch 'spring'?",
    answers: ["Frühling", "Herbst", "Winter", "Sommer"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'spring' ist der Frühling."
  },
  {
    id: "q3_e_038",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welche Jahreszeit heißt auf Englisch 'autumn' (oder 'fall')?",
    answers: ["Winter", "Herbst", "Frühling", "Sommer"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'autumn' ist der Herbst."
  },
  {
    id: "q3_e_039",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'cold'?",
    answers: ["heiß", "warm", "kalt", "nass"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'cold' bedeutet kalt."
  },
  {
    id: "q3_e_040",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'hot'?",
    answers: ["trocken", "kalt", "kühl", "heiß"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'hot' bedeutet sehr warm oder heiß."
  },
  {
    id: "q3_e_041",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welcher Monat heißt auf Englisch 'January'?",
    answers: ["Juli", "Janus", "Juni", "Januar"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'January' ist der Januar."
  },
  {
    id: "q3_e_042",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welcher Monat heißt auf Englisch 'December'?",
    answers: ["November", "Oktober", "Dezember", "September"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'December' ist der Dezember."
  },
  {
    id: "q3_e_043",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Samstag' auf Englisch?",
    answers: ["Saturday", "Sunday", "Thursday", "Tuesday"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Saturday' ist der Samstag."
  },
  {
    id: "q3_e_044",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Dienstag' auf Englisch?",
    answers: ["Tuesday", "Thursday", "Tuesdayday", "Wednesday"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'Tuesday' ist der Dienstag."
  },
  {
    id: "q3_e_045",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Mittwoch' auf Englisch?",
    answers: ["Wednesday", "Friday", "Thursday", "Tuesday"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'Wednesday' ist der Mittwoch."
  },
  {
    id: "q3_e_046",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt der Wochentag 'Donnerstag' auf Englisch?",
    answers: ["Thursday", "Sunday", "Tuesday", "Friday"],
    correct: 0,
    difficulty: "mittel",
    points: 5,
    explanation: "'Thursday' ist der Donnerstag."
  },
  {
    id: "q3_e_047",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'cloudy'?",
    answers: ["stürmisch", "sonnig im Alltag", "regnerisch", "bewölkt / wolkig"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'cloudy' heißt wolkig oder bewölkt (cloud = Wolke)."
  },
  {
    id: "q3_e_048",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie fragt man nach dem Wetter: 'Wie ist das Wetter heute?' auf Englisch?",
    answers: ["How is the sun? in der Praxis", "What's the weather like today?", "What day is today? zur Auswahl", "Where is the rain? zur Auswahl"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "'What's the weather like today?' fragt nach dem Wetter."
  },
  {
    id: "q3_e_049",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welcher Monat heißt auf Englisch 'May'?",
    answers: ["Mond", "Mitte", "Mai", "März"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'May' ist der Mai."
  },
  {
    id: "q3_e_050",
    category: "k3_englisch",
    topic: "weather_seasons",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welcher Monat heißt auf Englisch 'October'?",
    answers: ["September", "August", "November", "Oktober"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'October' ist der Oktober."
  },

  // ================================================================
  // 3. FOOD, DRINKS & CLOTHES (25 Fragen)
  // ================================================================
  {
    id: "q3_e_051",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'red'?",
    answers: ["grün", "gelb", "rot", "blau"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'red' heißt rot."
  },
  {
    id: "q3_e_052",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie heißt die Farbe 'rot' auf Englisch?",
    answers: ["green", "red", "black", "blue"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'red' bedeutet rot."
  },
  {
    id: "q3_e_053",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt das Kleidungsstück 'Hose' auf Englisch?",
    answers: ["trousers", "shoes", "shirt", "jacket"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'trousers' bedeutet Hose."
  },
  {
    id: "q3_e_054",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie übersetzt man 'Ich mag Äpfel' ins Englische?",
    answers: ["I see apples", "I eat apples", "I like apples", "I have apples"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'I like apples' bedeutet 'Ich mag Äpfel'."
  },
  {
    id: "q3_e_055",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welche Farbe entsteht, wenn man 'yellow' und 'blue' mischt?",
    answers: ["red", "orange", "green", "purple"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "Gelb (yellow) und Blau (blue) ergeben Grün (green)."
  },
  {
    id: "q3_e_056",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Apfel' auf Englisch?",
    answers: ["apple", "banana", "pear", "orange"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'apple' heißt Apfel."
  },
  {
    id: "q3_e_057",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'milk'?",
    answers: ["Tee", "Saft", "Milch", "Wasser"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'milk' heißt Milch."
  },
  {
    id: "q3_e_058",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'water'?",
    answers: ["Limonade", "Milch", "Wasser", "Wein"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'water' bedeutet Wasser."
  },
  {
    id: "q3_e_059",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'bread'?",
    answers: ["Kuchen", "Brot", "Käse", "Butter"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'bread' heißt Brot."
  },
  {
    id: "q3_e_060",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das englische Wort 'cheese'?",
    answers: ["Fleisch", "Schokolade", "Käse", "Ei"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'cheese' heißt Käse."
  },
  {
    id: "q3_e_061",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Schuhe' auf Englisch?",
    answers: ["socks", "shoes", "hat", "boots"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'shoes' bedeutet Schuhe."
  },
  {
    id: "q3_e_062",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Socken' auf Englisch?",
    answers: ["socks", "skirt", "trousers", "shoes"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'socks' bedeutet Socken."
  },
  {
    id: "q3_e_063",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Jacke / Mantel' auf Englisch?",
    answers: ["jacket / coat", "dress", "shirt", "cap im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'jacket' heißt Jacke, 'coat' Mantel."
  },
  {
    id: "q3_e_064",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'T-shirt'?",
    answers: ["T-Shirt / Hemd", "Mütze", "Schuh", "Hose im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'T-shirt' ist das T-Shirt."
  },
  {
    id: "q3_e_065",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'blue'?",
    answers: ["schwarz", "gelb", "blau", "braun"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'blue' heißt blau."
  },
  {
    id: "q3_e_066",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'yellow'?",
    answers: ["grün", "rot", "gelb", "weiß"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'yellow' bedeutet gelb."
  },
  {
    id: "q3_e_067",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'green'?",
    answers: ["rosa", "grau", "grün", "orange"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'green' heißt grün."
  },
  {
    id: "q3_e_068",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'black'?",
    answers: ["blau", "lila", "schwarz", "weiß"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'black' heißt schwarz."
  },
  {
    id: "q3_e_069",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Farbe 'white'?",
    answers: ["braun", "weiß", "rot", "gelb"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'white' heißt weiß."
  },
  {
    id: "q3_e_070",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Hut / Mütze' auf Englisch?",
    answers: ["gloves", "belt", "hat / cap", "skirt"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'hat' heißt Hut, 'cap' Kappe/Mütze."
  },
  {
    id: "q3_e_071",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Kleid' auf Englisch?",
    answers: ["shirt", "jeans", "skirt", "dress"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'dress' bedeutet Kleid."
  },
  {
    id: "q3_e_072",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Rock' (Kleidung) auf Englisch?",
    answers: ["shorts", "shirt", "skirt", "coat"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'skirt' ist der Rock."
  },
  {
    id: "q3_e_073",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'juice' im Wort 'apple juice'?",
    answers: ["Soße", "Kuchen", "Suppe", "Saft"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'juice' heißt Saft (apple juice = Apfelsaft)."
  },
  {
    id: "q3_e_074",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Eis' (zum Essen) auf Englisch?",
    answers: ["ice cream", "candy", "cookie", "cake"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'ice cream' heißt Speiseeis."
  },
  {
    id: "q3_e_075",
    category: "k3_englisch",
    topic: "food_clothes",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Wie sagt man höflich 'Danke' auf Englisch?",
    answers: ["Thank you", "Sorry", "Welcome", "Please"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'Thank you' (oder 'Thanks') heißt Danke."
  },

  // ================================================================
  // 4. HOME, ROOMS & TOWN (25 Fragen)
  // ================================================================
  {
    id: "q3_e_076",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'school'?",
    answers: ["Schule", "Straße", "Schrank", "Stuhl"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'school' heißt Schule."
  },
  {
    id: "q3_e_077",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Haus' auf Englisch?",
    answers: ["house", "home", "room", "door"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'house' ist das Haus."
  },
  {
    id: "q3_e_078",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'room'?",
    answers: ["Dach", "Garten", "Wand", "Zimmer / Raum"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'room' bedeutet Zimmer."
  },
  {
    id: "q3_e_079",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welches Zimmer im Haus ist die 'kitchen'?",
    answers: ["Wohnzimmer", "Küche", "Schlafzimmer", "Badezimmer"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'kitchen' heißt Küche."
  },
  {
    id: "q3_e_080",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welches Zimmer im Haus ist das 'bedroom'?",
    answers: ["Kinderzimmer", "Badezimmer", "Küche", "Schlafzimmer"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'bedroom' ist das Schlafzimmer (bed = Bett)."
  },
  {
    id: "q3_e_081",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Welches Zimmer ist das 'bathroom'?",
    answers: ["Wohnzimmer", "Küche", "Badezimmer", "Flur"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'bathroom' ist das Badezimmer."
  },
  {
    id: "q3_e_082",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Garten' auf Englisch?",
    answers: ["park", "garden", "street", "yard"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'garden' heißt Garten."
  },
  {
    id: "q3_e_083",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'table'?",
    answers: ["Tafel", "Teppich", "Tisch", "Stuhl"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'table' heißt Tisch."
  },
  {
    id: "q3_e_084",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'chair'?",
    answers: ["Stuhl", "Sofa", "Schrank", "Tisch"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'chair' bedeutet Stuhl."
  },
  {
    id: "q3_e_085",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'bed'?",
    answers: ["Buch", "Bett", "Bank", "Bad"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'bed' heißt Bett."
  },
  {
    id: "q3_e_086",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Tür' auf Englisch?",
    answers: ["wall", "window", "door", "floor"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'door' ist die Tür."
  },
  {
    id: "q3_e_087",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Fenster' auf Englisch?",
    answers: ["window", "wall", "door", "roof"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'window' heißt Fenster."
  },
  {
    id: "q3_e_088",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'book'?",
    answers: ["Tasche", "Stift", "Heft", "Buch"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'book' heißt Buch."
  },
  {
    id: "q3_e_089",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'pencil'?",
    answers: ["Kugelschreiber", "Lineal", "Bleistift", "Schere"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'pencil' ist der Bleistift."
  },
  {
    id: "q3_e_090",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'school bag'?",
    answers: ["Schultasche / Rucksack", "Schulbuch in der Praxis", "Schulbank in der Praxis", "Schultüte in der Praxis"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'school bag' ist die Schultasche."
  },
  {
    id: "q3_e_091",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Stadt' auf Englisch?",
    answers: ["street", "village", "town / city", "park"],
    correct: 2,
    difficulty: "leicht",
    points: 5,
    explanation: "'town' (oder 'city') heißt Stadt."
  },
  {
    id: "q3_e_092",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Straße' auf Englisch?",
    answers: ["path", "bridge", "road", "street"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'street' (oder 'road') bedeutet Straße."
  },
  {
    id: "q3_e_093",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'car'?",
    answers: ["Fahrrad", "Bus", "Zug", "Auto"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'car' heißt Auto."
  },
  {
    id: "q3_e_094",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'bus'?",
    answers: ["Bus", "Flugzeug", "Bahn", "Schiff"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'bus' ist der Bus."
  },
  {
    id: "q3_e_095",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Fahrrad' auf Englisch?",
    answers: ["bike / bicycle", "train", "plane", "car im Alltag"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'bike' (oder 'bicycle') heißt Fahrrad."
  },
  {
    id: "q3_e_096",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet das Wort 'park'?",
    answers: ["Spielplatz", "Park / Grünanlage", "Wiese zur Auswahl", "Wald in der Praxis"],
    correct: 1,
    difficulty: "leicht",
    points: 5,
    explanation: "'park' ist der Park."
  },
  {
    id: "q3_e_097",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was heißt 'Geschäft / Laden' auf Englisch?",
    answers: ["bank", "school", "house", "shop"],
    correct: 3,
    difficulty: "leicht",
    points: 5,
    explanation: "'shop' heißt Geschäft oder Laden."
  },
  {
    id: "q3_e_098",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet 'playground'?",
    answers: ["Spielplatz", "Fußballplatz", "Pausenhof", "Turnhalle"],
    correct: 0,
    difficulty: "leicht",
    points: 5,
    explanation: "'playground' heißt Spielplatz (play = spielen, ground = Boden/Platz)."
  },
  {
    id: "q3_e_099",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Präposition 'on' im Satz 'The book is on the table'?",
    answers: ["in", "auf", "unter", "neben"],
    correct: 1,
    difficulty: "mittel",
    points: 5,
    explanation: "'on' heißt auf."
  },
  {
    id: "q3_e_100",
    category: "k3_englisch",
    topic: "home_town",
    area: "schule",
    grade: 3,
    subject: "englisch",
    question: "Was bedeutet die Präposition 'under' im Satz 'The cat is under the bed'?",
    answers: [" hinter", "auf", "vor", "unter"],
    correct: 3,
    difficulty: "mittel",
    points: 5,
    explanation: "'under' heißt unter."
  },

  // ================================================================
// 5. ERSTE SÄTZE & SATZVERSTÄNDNIS (30 neue Fragen)
// ================================================================

{
  id: "q3_e_101",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Welcher Satz ist RICHTIG?",
  answers: [
      "Am I a girl.",
      "I am a girl.",
      "I is a girl.",
      "I be a girl."
    ],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig heißt es: 'I am a girl.' (Ich bin ein Mädchen.)"
},
{
  id: "q3_e_102",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Welcher Satz ist RICHTIG?",
  answers: [
      "You be my friend.",
      "You is my friend.",
      "You are my friend.",
      "Are you my friend."
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig heißt es: 'You are my friend.' (Du bist mein Freund.)"
},
{
  id: "q3_e_103",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Welcher Satz ist RICHTIG?",
  answers: [
      "He has a dog.",
      "Has he a dog.",
      "He is a dog.",
      "He have a dog."
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig heißt es: 'He has a dog.' (Er hat einen Hund.)"
},
{
  id: "q3_e_104",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Welcher Satz ist RICHTIG?",
  answers: [
      "She is apples.",
      "She like apples.",
      "Likes she apples.",
      "She likes apples."
    ],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig heißt es: 'She likes apples.' (Sie mag Äpfel.)"
},
{
  id: "q3_e_105",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Welcher Satz ist RICHTIG?",
  answers: [
      "We are football.",
      "We plays football.",
      "Play we football.",
      "We play football."
    ],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig heißt es: 'We play football.' (Wir spielen Fußball.)"
},
{
  id: "q3_e_106",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was heißt 'Ich habe einen Bruder.' auf Englisch?",
  answers: [
      "I am a brother.",
      "I have a brother.",
      "Have I a brother.",
      "I has a brother."
    ],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'I have a brother.' (Ich habe einen Bruder.)"
},
{
  id: "q3_e_107",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was heißt 'Sie mag Schokolade.' auf Englisch?",
  answers: [
      "She is chocolate.",
      "She likes chocolate.",
      "Likes she chocolate.",
      "She like chocolate."
    ],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'She likes chocolate.' (Sie mag Schokolade.)"
},
{
  id: "q3_e_108",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was heißt 'Wir sind im Park.' auf Englisch?",
  answers: [
      "Are we in the park.",
      "We are in the park.",
      "We is in the park.",
      "We be in the park."
    ],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'We are in the park.' (Wir sind im Park.)"
},
{
  id: "q3_e_109",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was heißt 'Er spielt Klavier.' auf Englisch?",
  answers: [
      "Plays he the piano.",
      "He is the piano.",
      "He plays the piano.",
      "He play the piano."
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'He plays the piano.' (Er spielt Klavier.)"
},
{
  id: "q3_e_110",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Wie fragt man auf Englisch 'Wie alt bist du?'?",
  answers: [
      "How are you old?",
      "How old are you?",
      "What old are you?",
      "How is your age?"
    ],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "Richtig: 'How old are you?' (Wie alt bist du?)"
},
{
  id: "q3_e_111",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Wie fragt man auf Englisch 'Wo wohnst du?'?",
  answers: [
      "How do you live?",
      "What do you live?",
      "Where are you live?",
      "Where do you live?"
    ],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'Where do you live?' (Wo wohnst du?)"
},
{
  id: "q3_e_112",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Wie fragt man auf Englisch 'Magst du Pizza?'?",
  answers: [
      "Do you likes pizza?",
      "Like you pizza?",
      "Do you like pizza?",
      "Are you like pizza?"
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'Do you like pizza?' (Magst du Pizza?)"
},
{
  id: "q3_e_113",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Ich kann schwimmen.'?",
  answers: [
      "Can I swim.",
      "I can swim.",
      "I swim can.",
      "I can to swim."
    ],
  correct: 1,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'I can swim.' (Ich kann schwimmen.)"
},
{
  id: "q3_e_114",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Sie hat blaue Augen.'?",
  answers: [
      "She has blue eyes.",
      "Has she blue eyes.",
      "She is blue eyes.",
      "She have blue eyes."
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'She has blue eyes.' (Sie hat blaue Augen.)"
},
{
  id: "q3_e_115",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Wir gehen zur Schule.'?",
  answers: [
      "We go to school.",
      "Go we to school.",
      "We are go to school.",
      "We goes to school."
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'We go to school.' (Wir gehen zur Schule.)"
},
{
  id: "q3_e_116",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'I like to read books.'?",
  answers: [
      "Ich mag Bücher lesen.",
      "Ich sehe Bücher.",
      "Ich lese gerne Bücher.",
      "Ich kaufe Bücher."
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "'I like to read books.' bedeutet: Ich lese gerne Bücher."
},
{
  id: "q3_e_117",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'My father is a teacher.'?",
  answers: [
      "Mein Vater ist Lehrer.",
      "Meine Mutter ist Lehrerin.",
      "Mein Bruder ist Lehrer.",
      "Mein Vater ist Arzt."
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "'My father is a teacher.' bedeutet: Mein Vater ist Lehrer."
},
{
  id: "q3_e_118",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'It is raining outside.'?",
  answers: [
      "Die Sonne scheint.",
      "Es schneit draußen.",
      "Es ist windig.",
      "Es regnet draußen."
    ],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "'It is raining outside.' bedeutet: Es regnet draußen."
},
{
  id: "q3_e_119",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'The cat is under the table.'?",
  answers: [
      "Die Katze ist auf dem Tisch.",
      "Die Katze ist neben dem Tisch.",
      "Die Katze ist unter dem Tisch.",
      "Die Katze ist hinter dem Tisch."
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "'under' bedeutet 'unter' – die Katze ist unter dem Tisch."
},
{
  id: "q3_e_120",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'The book is on the shelf.'?",
  answers: [
      "Das Buch ist neben dem Regal.",
      "Das Buch ist im Regal.",
      "Das Buch ist auf dem Regal.",
      "Das Buch ist unter dem Regal."
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "'on' bedeutet 'auf' – das Buch ist auf dem Regal."
},
{
  id: "q3_e_121",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Das Wetter ist heute schön.'?",
  answers: [
      "The weather is nice today.",
      "Today is nice the weather.",
      "The weather is bad today.",
      "Weather is nice today."
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'The weather is nice today.' (Das Wetter ist heute schön.)"
},
{
  id: "q3_e_122",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Ich habe Hunger.'?",
  answers: [
      "I have hungry.",
      "I am hungry.",
      "Hungry I am.",
      "I am hunger."
    ],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "Richtig: 'I am hungry.' (Ich habe Hunger.)"
},
{
  id: "q3_e_123",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Ich habe Durst.'?",
  answers: [
      "Thirsty I am.",
      "I am thirsty.",
      "I am thirst.",
      "I have thirsty."
    ],
  correct: 1,
  difficulty: "leicht",
  points: 5,
  explanation: "Richtig: 'I am thirsty.' (Ich habe Durst.)"
},
{
  id: "q3_e_124",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Kannst du mir helfen?'?",
  answers: [
      "Help you me?",
      "Can you helps me?",
      "Can you help me?",
      "Do you can help me?"
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'Can you help me?' (Kannst du mir helfen?)"
},
{
  id: "q3_e_125",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'I am going to the cinema.'?",
  answers: [
      "Ich gehe nach Hause.",
      "Ich gehe ins Schwimmbad.",
      "Ich gehe zur Schule.",
      "Ich gehe ins Kino."
    ],
  correct: 3,
  difficulty: "mittel",
  points: 5,
  explanation: "'I am going to the cinema.' bedeutet: Ich gehe ins Kino."
},
{
  id: "q3_e_126",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'My sister is younger than me.'?",
  answers: [
      "Meine Schwester ist kleiner als ich.",
      "Meine Schwester ist jünger als ich.",
      "Meine Schwester ist älter als ich.",
      "Meine Schwester ist größer als ich."
    ],
  correct: 1,
  difficulty: "schwer",
  points: 5,
  explanation: "'younger' bedeutet jünger – meine Schwester ist jünger als ich."
},
{
  id: "q3_e_127",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'I get up at 7 o'clock.'?",
  answers: [
      "Ich gehe um 7 Uhr ins Bett.",
      "Ich esse um 7 Uhr.",
      "Ich stehe um 7 Uhr auf.",
      "Ich komme um 7 Uhr."
    ],
  correct: 2,
  difficulty: "mittel",
  points: 5,
  explanation: "'I get up at 7 o'clock.' bedeutet: Ich stehe um 7 Uhr auf."
},
{
  id: "q3_e_128",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Was ist deine Lieblingsfarbe?'?",
  answers: [
      "What is your favourite colour?",
      "How is your colour? im Alltag",
      "What is your best colour?",
      "Which colour do you like?"
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "Richtig: 'What is your favourite colour?' (Was ist deine Lieblingsfarbe?)"
},
{
  id: "q3_e_129",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was bedeutet der Satz 'Let's go to the park!'?",
  answers: [
      "Lass uns in den Park gehen!",
      "Lass uns nach Hause gehen!",
      "Lass uns essen gehen!",
      "Lass uns schwimmen gehen!"
    ],
  correct: 0,
  difficulty: "mittel",
  points: 5,
  explanation: "'Let's go to the park!' bedeutet: Lass uns in den Park gehen!"
},
{
  id: "q3_e_130",
  category: "k3_englisch",
  topic: "sentences",
  area: "schule",
  grade: 3,
  subject: "englisch",
  question: "Was ist die englische Übersetzung für 'Darf ich bitte zur Toilette gehen?'?",
  answers: [
      "I go to toilet? in der Praxis",
      "May I go to the toilet, please?",
      "May I to the toilet? im Alltag",
      "Can I go to toilet? zur Auswahl"
    ],
  correct: 1,
  difficulty: "schwer",
  points: 5,
  explanation: "Richtig: 'May I go to the toilet, please?' (Darf ich bitte zur Toilette gehen?)"
}
,
  // ERWEITERUNG (+30)
,
  { id: "q3_e_101", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "What is „apple“ in German?", answers: ["Birne", "Banane", "Apfel", "Orange"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "apple = Apfel." },
  { id: "q3_e_102", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "„House“ heißt …", answers: ["Maus", "Hose", "Haus", "Hut"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "house = Haus." },
  { id: "q3_e_103", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "How do you say „Wasser“?", answers: ["fire", "water", "bread", "milk"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "water = Wasser." },
  { id: "q3_e_104", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "„Big“ means …", answers: ["klein", "groß", "alt", "jung"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "big = groß." },
  { id: "q3_e_105", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "Opposite of „hot“?", answers: ["warm", "cold", "new", "fast"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "cold = kalt." },
  { id: "q3_e_106", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "I ___ a student. (be)", answers: ["is", "are", "am", "be"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "I am." },
  { id: "q3_e_107", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "She ___ to school. (go)", answers: ["go", "goes", "going", "gone"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "She goes." },
  { id: "q3_e_108", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "Plural of „child“?", answers: ["childs", "children", "childes", "child"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "children." },
  { id: "q3_e_109", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "a / an: ___ apple", answers: ["a", "an", "the", "some"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "an apple (Vokal)." },
  { id: "q3_e_110", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "This is ___ book.", answers: ["I", "me", "my", "mine"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "my book." },
  { id: "q3_e_111", category: "k3_englisch", topic: "numbers", area: "schule", grade: 3, subject: "englisch",
    question: "What is 12 in words?", answers: ["twenty", "eleven", "twelve", "thirteen"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "twelve." },
  { id: "q3_e_112", category: "k3_englisch", topic: "numbers", area: "schule", grade: 3, subject: "englisch",
    question: "„Twenty“ ist …", answers: ["12", "22", "20", "2"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "twenty = 20." },
  { id: "q3_e_113", category: "k3_englisch", topic: "school", area: "schule", grade: 3, subject: "englisch",
    question: "„Teacher“ means …", answers: ["Schüler", "Lehrer", "Buch", "Klasse"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "teacher = Lehrer/in." },
  { id: "q3_e_114", category: "k3_englisch", topic: "school", area: "schule", grade: 3, subject: "englisch",
    question: "I write with a …", answers: ["chair", "pen", "door", "window"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "pen = Stift." },
  { id: "q3_e_115", category: "k3_englisch", topic: "school", area: "schule", grade: 3, subject: "englisch",
    question: "„Classroom“ heißt …", answers: ["Pausenhof", "Klassenraum", "Turnhalle", "Büro"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "classroom = Klassenraum." },
  { id: "q3_e_116", category: "k3_englisch", topic: "everyday", area: "schule", grade: 3, subject: "englisch",
    question: "Good night means …", answers: ["Guten Morgen", "Gute Nacht", "Guten Tag", "Tschüss"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Gute Nacht." },
  { id: "q3_e_117", category: "k3_englisch", topic: "everyday", area: "schule", grade: 3, subject: "englisch",
    question: "How old are you? asks for …", answers: ["Name", "Alter", "Farbe", "Adresse"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "das Alter." },
  { id: "q3_e_118", category: "k3_englisch", topic: "everyday", area: "schule", grade: 3, subject: "englisch",
    question: "„Please“ and „thank you“ are …", answers: ["Zahlen", "Farben", "Höflichkeit", "Tiere"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "Höflichkeitswörter." },
  { id: "q3_e_119", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "„Dog“ and „cat“ are …", answers: ["food", "animals", "colours", "numbers"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "animals." },
  { id: "q3_e_120", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "The sun is …", answers: ["blue", "yellow", "often yellow/bright", "green"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "often seen as yellow." },
  { id: "q3_e_121", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "They ___ happy.", answers: ["is", "am", "are", "be"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "They are." },
  { id: "q3_e_122", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "He ___ football. (play)", answers: ["play", "plays", "playing", "played"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "He plays." },
  { id: "q3_e_123", category: "k3_englisch", topic: "numbers", area: "schule", grade: 3, subject: "englisch",
    question: "Half of twenty is …", answers: ["five", "fifteen", "ten", "twelve"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "ten." },
  { id: "q3_e_124", category: "k3_englisch", topic: "school", area: "schule", grade: 3, subject: "englisch",
    question: "Open your … please.", answers: ["shoe", "book", "apple", "dog"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "book." },
  { id: "q3_e_125", category: "k3_englisch", topic: "everyday", area: "schule", grade: 3, subject: "englisch",
    question: "See you tomorrow means …", answers: ["Bis gestern", "Bis morgen", "Guten Appetit", "Entschuldigung"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "Bis morgen." },
  { id: "q3_e_126", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "„Bread“ heißt …", answers: ["Butter", "Brot", "Käse", "Milch"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "bread = Brot." },
  { id: "q3_e_127", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "„Friend“ means …", answers: ["Feind", "Fremder", "Freund", "Vater"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "friend = Freund." },
  { id: "q3_e_128", category: "k3_englisch", topic: "grammar", area: "schule", grade: 3, subject: "englisch",
    question: "We ___ from Germany. (be)", answers: ["is", "am", "are", "be"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "We are." },
  { id: "q3_e_129", category: "k3_englisch", topic: "everyday", area: "schule", grade: 3, subject: "englisch",
    question: "Excuse me is used to …", answers: ["danken", "grüßen nachts", "höflich unterbrechen/ansprechen", "zählen"], correct: 2, difficulty: "leicht", points: 5,
    explanation: "höflich ansprechen." },
  { id: "q3_e_130", category: "k3_englisch", topic: "vocab", area: "schule", grade: 3, subject: "englisch",
    question: "„Green“ is a …", answers: ["number", "colour", "animal", "day"], correct: 1, difficulty: "leicht", points: 5,
    explanation: "colour." }
];
