// ============================================================
//  EduPlay Hub – Fragen-Verzeichnis (automatisch erzeugt)
//
//  Sagt dem Loader, welche Datei welche Kategorien liefert,
//  damit beim Start nichts geladen wird, das niemand ansieht.
//
//  NEUE FRAGEN-DATEI HINZUGEFUEGT? Diese Datei neu erzeugen
//  lassen oder den Eintrag von Hand ergaenzen – sonst findet
//  der Loader die Kategorie nicht.
//
//  datei = Pfad · name = globale Variable · kat = Kategorien
//  n = Anzahl Fragen (nur zur Anzeige)
// ============================================================

window.FRAGEN_VERZEICHNIS = [
  { datei: "fragen/fun/kinder_anime.js", name: "KINDER_ANIME_QUESTIONS", n: 100, kat: ["kinder_anime_cartoons"] },
  { datei: "fragen/fun/kinder_maerchen.js", name: "KINDER_MAERCHEN_QUESTIONS", n: 100, kat: ["kinder_maerchen_disney"] },
  { datei: "fragen/fun/kinder_tiere_natur.js", name: "KINDER_TIERE_NATUR_QUESTIONS", n: 100, kat: ["kinder_tiere_natur"] },
  { datei: "fragen/fun/kinder_wissen.js", name: "KINDER_WISSEN_QUESTIONS", n: 100, kat: ["kinder_erstes_wissen"] },
  { datei: "fragen/fun/spass_allgemein.js", name: "SPASS_ALLGEMEIN_QUESTIONS", n: 247, kat: ["spass_allgemein"] },
  { datei: "fragen/fun/spass_beruf_humor.js", name: "SPASS_BERUF_HUMOR_QUESTIONS", n: 34, kat: ["spass_beruf_humor"] },
  { datei: "fragen/fun/spass_erfindungen.js", name: "SPASS_ERFINDUNGEN_QUESTIONS", n: 101, kat: ["spass_erfindungen"] },
  { datei: "fragen/fun/spass_essen.js", name: "SPASS_ESSEN_QUESTIONS", n: 103, kat: ["spass_essen"] },
  { datei: "fragen/fun/spass_hauptstaedte.js", name: "SPASS_HAUPTSTAEDTE_QUESTIONS", n: 60, kat: ["spass_hauptstaedte_europa","spass_hauptstaedte_welt"] },
  { datei: "fragen/fun/spass_hauptstaedte_europa.js", name: "SPASS_HAUPTSTAEDTE_EUROPA_QUESTIONS", n: 5, kat: ["spass_hauptstaedte_europa"] },
  { datei: "fragen/fun/spass_humor.js", name: "SPASS_HUMOR_QUESTIONS", n: 119, kat: ["spass_humor"] },
  { datei: "fragen/fun/spass_kleine.js", name: "SPASS_KLEINE_QUESTIONS", n: 99, kat: ["spass_kleine"] },
  { datei: "fragen/fun/spass_laender.js", name: "SPASS_LAENDER_QUESTIONS", n: 113, kat: ["spass_laender"] },
  { datei: "fragen/fun/spass_musik.js", name: "SPASS_MUSIK_QUESTIONS", n: 113, kat: ["spass_musik"] },
  { datei: "fragen/fun/spass_musik_wer_singt.json", name: "SPASS_MUSIK_WER_SINGT_QUESTIONS", n: 105, kat: ["musik_wer_singt"] },
  { datei: "fragen/fun/spass_nice_to_know.js", name: "SPASS_NICE_TO_KNOW_QUESTIONS", n: 132, kat: ["schaetzen_nice_to_know","spass_nice_to_know"] },
  { datei: "fragen/fun/spass_raetsel.js", name: "SPASS_RAETSEL_QUESTIONS", n: 111, kat: ["spass_raetsel"] },
  { datei: "fragen/fun/spass_schaetzfragen.js", name: "SPASS_SCHAETZFRAGEN_QUESTIONS", n: 127, kat: ["schaetzen_mensch_koerper","schaetzen_ungewoehnlich_welt"] },
  { datei: "fragen/fun/spass_sport_film.js", name: "SPASS_SPORT_FILM_QUESTIONS", n: 149, kat: ["spass_sport_film"] },
  { datei: "fragen/fun/spass_gaming.json", name: "SPASS_GAMING_QUESTIONS", n: 101, kat: ["gaming_popkultur"] },
  { datei: "fragen/fun/spass_geografie.json", name: "SPASS_GEOGRAFIE_QUESTIONS", n: 105, kat: ["geografie_geschichte"] },
  { datei: "fragen/fun/spass_sport_animationl.json", name: "SPASS_ANIMATION_QUESTIONS", n: 40, kat: ["kinder_anime_cartoons","animation_zeichentrick"] },
  { datei: "fragen/fun/spass_sport_beruehmtheiten.json", name: "SPASS_BERUEHMTHEITEN_QUESTIONS", n: 75, kat: ["beruehmtheiten"] },
  { datei: "fragen/fun/spass_sport_film_serien.json", name: "SPASS_FILM_SERIEN_QUESTIONS", n: 152, kat: ["film_serien","werbung_marken","musik_hits","natur_wissenschaft"] },
  { datei: "fragen/fun/spass_sport_fussball.json", name: "SPASS_FUSSBALL_QUESTIONS", n: 75, kat: ["fussball_sport"] },
  { datei: "fragen/fun/spass_sport_technik.json", name: "SPASS_TECHNIK_QUESTIONS", n: 65, kat: ["technik_gadgets"] },
  { datei: "fragen/fun/spass_sport_zitate.json", name: "SPASS_ZITATE_QUESTIONS", n: 106, kat: ["film_serien_zitate"] },
  { datei: "fragen/fun/spass_tiere.js", name: "SPASS_TIERE_QUESTIONS", n: 101, kat: ["spass_tiere"] },
  { datei: "fragen/fun/spass_ungewoehnliches.js", name: "SPASS_UNGEWOEHNLICHES_QUESTIONS", n: 132, kat: ["schaetzen_ungewoehnlich_welt","spass_welt"] },
  { datei: "fragen/fun/spass_wuerdest_du.js", name: "SPASS_WUERDEST_DU_QUESTIONS", n: 139, kat: ["spass_wuerdest_du"] },
  { datei: "fragen/klasse1/questions_k1_deutsch.js", name: "K1_DEUTSCH_QUESTIONS", n: 100, kat: ["k1_deutsch"] },
  { datei: "fragen/klasse1/questions_k1_mathe.js", name: "K1_MATHE_QUESTIONS", n: 110, kat: ["k1_mathe"] },
  { datei: "fragen/klasse1/questions_k1_sachunterricht.js", name: "K1_SACHUNTERRICHT_QUESTIONS", n: 100, kat: ["k1_sachunterricht"] },
  { datei: "fragen/klasse2/questions_k2_deutsch.js", name: "K2_DEUTSCH_QUESTIONS", n: 100, kat: ["k2_deutsch"] },
  { datei: "fragen/klasse2/questions_k2_englisch.js", name: "K2_ENGLISCH_QUESTIONS", n: 60, kat: ["k2_englisch"] },
  { datei: "fragen/klasse2/questions_k2_mathe.js", name: "K2_MATHE_QUESTIONS", n: 100, kat: ["k2_mathe"] },
  { datei: "fragen/klasse2/questions_k2_sachunterricht.js", name: "K2_SACHUNTERRICHT_QUESTIONS", n: 100, kat: ["k2_sachunterricht"] },
  { datei: "fragen/klasse3/questions_k3_deutsch.js", name: "K3_DEUTSCH_QUESTIONS", n: 100, kat: ["k3_deutsch"] },
  { datei: "fragen/klasse3/questions_k3_englisch.js", name: "K3_ENGLISCH_QUESTIONS", n: 130, kat: ["k3_englisch"] },
  { datei: "fragen/klasse3/questions_k3_mathe.js", name: "K3_MATHE_QUESTIONS", n: 100, kat: ["k3_mathe"] },
  { datei: "fragen/klasse3/questions_k3_sachunterricht.js", name: "K3_SACHUNTERRICHT_QUESTIONS", n: 106, kat: ["k2_sachunterricht","k3_sachunterricht"] },
  { datei: "fragen/klasse4/questions_k4_deutsch.js", name: "K4_DEUTSCH_QUESTIONS", n: 100, kat: ["k4_deutsch"] },
  { datei: "fragen/klasse4/questions_k4_englisch.js", name: "K4_ENGLISCH_QUESTIONS", n: 100, kat: ["k4_englisch"] },
  { datei: "fragen/klasse4/questions_k4_mathe.js", name: "K4_MATHE_QUESTIONS", n: 100, kat: ["k4_mathe"] },
  { datei: "fragen/klasse4/questions_k4_sachunterricht.js", name: "K4_SACHUNTERRICHT_QUESTIONS", n: 89, kat: ["k4_sachunterricht"] },
  { datei: "fragen/klasse5/questions_k5_biologie.js", name: "K5_BIOLOGIE_QUESTIONS", n: 100, kat: ["k5_biologie"] },
  { datei: "fragen/klasse5/questions_k5_deutsch.js", name: "K5_DEUTSCH_QUESTIONS", n: 100, kat: ["k5_deutsch"] },
  { datei: "fragen/klasse5/questions_k5_englisch.js", name: "K5_ENGLISCH_QUESTIONS", n: 100, kat: ["k5_englisch"] },
  { datei: "fragen/klasse5/questions_k5_erdkunde.js", name: "K5_ERDKUNDE_QUESTIONS", n: 100, kat: ["k5_erdkunde"] },
  { datei: "fragen/klasse5/questions_k5_mathe.js", name: "K5_MATHE_QUESTIONS", n: 100, kat: ["k5_mathe"] },
  { datei: "fragen/klasse5/questions_k5_politik.js", name: "K5_POLITIK_QUESTIONS", n: 100, kat: ["k5_politik"] },
  { datei: "fragen/klasse6/questions_k6_biologie.js", name: "K6_BIOLOGIE_QUESTIONS", n: 100, kat: ["k6_biologie"] },
  { datei: "fragen/klasse6/questions_k6_deutsch.js", name: "K6_DEUTSCH_QUESTIONS", n: 100, kat: ["k6_deutsch"] },
  { datei: "fragen/klasse6/questions_k6_englisch.js", name: "K6_ENGLISCH_QUESTIONS", n: 200, kat: ["k6_englisch"] },
  { datei: "fragen/klasse6/questions_k6_erdkunde.js", name: "K6_ERDKUNDE_QUESTIONS", n: 100, kat: ["k6_erdkunde"] },
  { datei: "fragen/klasse6/questions_k6_geschichte.js", name: "K6_GESCHICHTE_QUESTIONS", n: 100, kat: ["k6_geschichte"] },
  { datei: "fragen/klasse6/questions_k6_mathe.js", name: "K6_MATHE_QUESTIONS", n: 200, kat: ["k6_mathe"] },
  { datei: "fragen/klasse6/questions_k6_musik.js", name: "K6_MUSIK_KUNST_QUESTIONS", n: 100, kat: ["k6_musik_kunst"] },
  { datei: "fragen/klasse6/questions_k6_physik.js", name: "K6_PHYSIK_QUESTIONS", n: 100, kat: ["k6_physik"] },
  { datei: "fragen/klasse6/questions_k6_politik.js", name: "K6_POLITIK_QUESTIONS", n: 100, kat: ["k6_politik"] },
  { datei: "fragen/klasse6/questions_k6_religion.js", name: "K6_PHILOSOPHIE_RELIGION_QUESTIONS", n: 100, kat: ["k6_religion"] },
  { datei: "fragen/klasse7/questions_k7_biologie.js", name: "K7_BIOLOGIE_QUESTIONS", n: 101, kat: ["k7_biologie"] },
  { datei: "fragen/klasse7/questions_k7_chemie.js", name: "K7_CHEMIE_QUESTIONS", n: 100, kat: ["k7_chemie"] },
  { datei: "fragen/klasse7/questions_k7_deutsch.js", name: "K7_DEUTSCH_QUESTIONS", n: 200, kat: ["k7_deutsch"] },
  { datei: "fragen/klasse7/questions_k7_englisch.js", name: "K7_ENGLISCH_QUESTIONS", n: 100, kat: ["k7_englisch"] },
  { datei: "fragen/klasse7/questions_k7_erdkunde.js", name: "K7_ERDKUNDE_QUESTIONS", n: 100, kat: ["k7_erdkunde"] },
  { datei: "fragen/klasse7/questions_k7_franzoesischk.js", name: "K7_FRANZOESISCH_QUESTIONS", n: 100, kat: ["k7_franzoesisch"] },
  { datei: "fragen/klasse7/questions_k7_geschichte.js", name: "K7_GESCHICHTE_QUESTIONS", n: 100, kat: ["k7_geschichte"] },
  { datei: "fragen/klasse7/questions_k7_mathe.js", name: "K7_MATHEMATIK_QUESTIONS", n: 200, kat: ["k7_mathe"] },
  { datei: "fragen/klasse7/questions_k7_physik.js", name: "K7_PHYSIK_QUESTIONS", n: 200, kat: ["k7_physik"] },
  { datei: "fragen/klasse7/questions_k7_politik.js", name: "K7_POLITIK_QUESTIONS", n: 100, kat: ["k7_politik"] },
  { datei: "fragen/klasse7/questions_k7_religion.js", name: "K7_RELIGION_PHILOSOPHIE_QUESTIONS", n: 100, kat: ["k7_religion"] },
  { datei: "fragen/klasse8/questions_k8_biologie.js", name: "questions_k8_biologie", n: 100, kat: ["k8_biologie"] },
  { datei: "fragen/klasse8/questions_k8_chemie.js", name: "questions_k8_chemie", n: 100, kat: ["k8_chemie"] },
  { datei: "fragen/klasse8/questions_k8_deutsch.js", name: "questions_k8_deutsch", n: 100, kat: ["k8_deutsch"] },
  { datei: "fragen/klasse8/questions_k8_englisch.js", name: "questions_k8_englisch", n: 100, kat: ["k8_englisch"] },
  { datei: "fragen/klasse8/questions_k8_erdkunde.js", name: "questions_k8_erdkunde", n: 100, kat: ["k8_erdkunde"] },
  { datei: "fragen/klasse8/questions_k8_franzoesisch.js", name: "questions_k8_franzoesisch", n: 100, kat: ["k8_franzoesisch"] },
  { datei: "fragen/klasse8/questions_k8_geschichte.js", name: "questions_k8_geschichte", n: 100, kat: ["k8_geschichte"] },
  { datei: "fragen/klasse8/questions_k8_informatik.js", name: "questions_k8_informatik", n: 100, kat: ["k8_informatik"] },
  { datei: "fragen/klasse8/questions_k8_mathe.js", name: "questions_k8_mathematik", n: 100, kat: ["k8_mathe"] },
  { datei: "fragen/klasse8/questions_k8_physik.js", name: "questions_k8_physik", n: 100, kat: ["k8_physik"] },
  { datei: "fragen/klasse8/questions_k8_politik.js", name: "questions_k8_politik", n: 100, kat: ["k8_politik"] },
  { datei: "fragen/klasse8/questions_k8_religion.js", name: "questions_k8_religion", n: 100, kat: ["k8_religion"] },
  { datei: "fragen/klasse9/questions_k9_biologie.js", name: "K9_BIOLOGIE_QUESTIONS", n: 100, kat: ["k9_biologie"] },
  { datei: "fragen/klasse9/questions_k9_chemie.js", name: "K9_CHEMIE_QUESTIONS", n: 100, kat: ["k9_chemie"] },
  { datei: "fragen/klasse9/questions_k9_deutsch.js", name: "K9_DEUTSCH_QUESTIONS", n: 200, kat: ["k9_deutsch"] },
  { datei: "fragen/klasse9/questions_k9_englisch.js", name: "K9_ENGLISCH_QUESTIONS", n: 100, kat: ["k9_englisch"] },
  { datei: "fragen/klasse9/questions_k9_erdkunde.js", name: "K9_ERDKUNDE_QUESTIONS", n: 100, kat: ["k9_erdkunde"] },
  { datei: "fragen/klasse9/questions_k9_franzoesisch.js", name: "K9_FRANZOESISCH_QUESTIONS", n: 100, kat: ["k9_franzoesisch"] },
  { datei: "fragen/klasse9/questions_k9_geschichte.js", name: "K9_GESCHICHTE_QUESTIONS", n: 100, kat: ["k9_geschichte"] },
  { datei: "fragen/klasse9/questions_k9_informatik.js", name: "K9_INFORMATIK_QUESTIONS", n: 100, kat: ["k9_informatik"] },
  { datei: "fragen/klasse9/questions_k9_mathematik.js", name: "K9_MATHEMATIK_QUESTIONS", n: 155, kat: ["k9_mathe"] },
  { datei: "fragen/klasse9/questions_k9_physik.js", name: "K9_PHYSIK_QUESTIONS", n: 100, kat: ["k9_physik"] },
  { datei: "fragen/klasse9/questions_k9_politik.js", name: "K9_POLITIK_QUESTIONS", n: 100, kat: ["k9_politik"] },
  { datei: "fragen/klasse9/questions_k9_religion.js", name: "K9_RELIGION_QUESTIONS", n: 100, kat: ["k9_religion"] },
  { datei: "fragen/klassse10/questions_k10_biologie.js", name: "K10_BIOLOGIE_QUESTIONS", n: 150, kat: ["k10_biologie"] },
  { datei: "fragen/klassse10/questions_k10_chemie.js", name: "K10_CHEMIE_QUESTIONS", n: 150, kat: ["k10_chemie"] },
  { datei: "fragen/klassse10/questions_k10_deutsch.js", name: "K10_DEUTSCH_QUESTIONS", n: 100, kat: ["k10_deutsch"] },
  { datei: "fragen/klassse10/questions_k10_englisch.js", name: "K10_ENGLISCH_QUESTIONS", n: 150, kat: ["k10_englisch"] },
  { datei: "fragen/klassse10/questions_k10_erdkunde.js", name: "K10_ERDKUNDE_QUESTIONS", n: 150, kat: ["k10_erdkunde"] },
  { datei: "fragen/klassse10/questions_k10_franzoesisch.js", name: "K10_FRANZOESISCH_QUESTIONS", n: 150, kat: ["k10_franzoesisch"] },
  { datei: "fragen/klassse10/questions_k10_geschichte.js", name: "K10_GESCHICHTE_QUESTIONS", n: 150, kat: ["k10_geschichte"] },
  { datei: "fragen/klassse10/questions_k10_informatik.js", name: "K10_INFORMATIK_QUESTIONS", n: 150, kat: ["k10_informatik"] },
  { datei: "fragen/klassse10/questions_k10_mathematik.js", name: "K10_MATHEMATIK_QUESTIONS", n: 150, kat: ["k10_mathe"] },
  { datei: "fragen/klassse10/questions_k10_physik.js", name: "K10_PHYSIK_QUESTIONS", n: 150, kat: ["k10_physik"] },
  { datei: "fragen/klassse10/questions_k10_politik.js", name: "K10_POLITIK_QUESTIONS", n: 150, kat: ["k10_politik"] },
  { datei: "fragen/klassse10/questions_k10_religion_ethik.js", name: "K10_RELIGION_ETHIK_QUESTIONS", n: 150, kat: ["k10_religion"] },
];
