// ============================================================
// EduPlay Hub – Themen-Wortlisten (Kinder)
// Großgeschrieben, ohne ß, Einzelwörter
// ============================================================

const GERMAN_WORDS_KIDS_THEMES = {
    gemischt: null, // → volle GERMAN_WORDS_KIDS

    tiere: [
        "HUND", "KATZE", "MAUS", "PFERD", "KUH", "SCHAF", "ZIEGE", "SCHWEIN", "HUHN", "ENTE",
        "GANS", "HASE", "KANINCHEN", "HAMSTER", "MEERSCHWEIN", "FISCH", "VOGEL", "ADLER", "EULE", "SPATZ",
        "AMSEL", "RABE", "TAUBE", "SCHWAN", "STORCH", "FROSCH", "KRÖTE", "SCHLANGE", "ECHSE", "KROKODIL",
        "ELEFANT", "LÖWE", "TIGER", "BÄR", "WOLF", "FUCHS", "HIRSCH", "REH", "WILD", "AFFEN",
        "AFFE", "GORILLA", "ZEBRA", "GIRAFFE", "NILPFERD", "NASHORN", "KAMEEL", "PFERD", "PONY", "ESEL",
        "HUNDCHEN", "WELPE", "KÄTZCHEN", "KÜKEN", "LAMM", "KALB", "FOHLEN", "BIENE", "WESPE", "AMEISE",
        "KÄFER", "SCHMETTERLING", "SPINNE", "WURM", "SCHNECKE", "QUALLE", "DELFIN", "WAL", "HAI", "ROBBE",
        "PINGUIN", "EISBÄR", "PAPAGEI", "KANARIEN", "WELLI", "GOLDHAMSTER", "ZEBRAFISCH", "MAULWURF", "IGEL", "FLEDERMAUS",
        "BIBER", "OTTER", "EICHHÖRNCHEN", "MARDER", "DACHS", "LUCHS", "PUMA", "PANTHER", "GEPARD", "KÄNGURU",
        "KOALA", "FAULTIER", "FLAMINGO", "PFAN", "TRUTHAHN", "PUTER", "ERPEL", "KORMORAN", "PELIKAN", "STRAUSS"
    ],

    schule: [
        "SCHULE", "KLASSE", "LEHRER", "LEHRERIN", "SCHÜLER", "MAPPE", "HEFT", "STIFT", "BLEISTIFT", "KUGELSCHREIBER",
        "RADIERER", "LINEAL", "ZIRKEL", "SCHERE", "KLEBER", "FARBE", "MALSTIFT", "KREIDE", "TAFEL", "WANDTAFEL",
        "PAUSE", "PAUSEHOF", "KLINGEL", "STUNDE", "UNTERRICHT", "HAUSAUFGABE", "TEST", "ARBEIT", "NOTE", "ZEUGNIS",
        "BUCH", "LESEBUCH", "RECHENBUCH", "ATLAS", "GLOBE", "LANDKARTE", "RUCKSACK", "TURNBEUTEL", "BROTDOSE", "TRINKFLASCHE",
        "BANK", "STUHL", "TISCH", "GARDEROBE", "FLUR", "TURNHALLE", "SPORTHALLE", "BIBLIOTHEK", "SEKRETARIAT", "DIREKTOR",
        "RECHNEN", "LESEN", "SCHREIBEN", "MALEN", "SINGEN", "TURNEN", "WERKEN", "BASTELN", "PROJEKT", "AUSFLUG",
        "WANDERTAG", "SCHULFEST", "ZEUGNISTAG", "FERIEN", "SOMMERFERIEN", "WEIHNACHTEN", "OSTERN", "KLASSENFAHRT", "SCHULBUS", "FAHRRAD",
        "FREUND", "FREUNDIN", "KLASSENKAMERAD", "NACHBAR", "PARTNER", "GRUPPE", "TEAM", "SPIEL", "RÄTSEL", "QUIZ",
        "ABC", "ALPHABET", "ZAHL", "RECHENAUFGABE", "TEXT", "SATZ", "WORT", "SILBE", "BUCHSTABE", "DIKTAT",
        "AUFSATZ", "GESCHICHTE", "MÄRCHEN", "GEDICHT", "LIED", "MUSIK", "FLÖTE", "TROMMEL", "CHOR", "ORCHESTER"
    ],

    essen: [
        "APFEL", "BIRNE", "BANANE", "ORANGE", "MANDARINE", "ZITRONE", "ERDBEERE", "HIMBEERE", "BLAUBEERE", "KIRSCHE",
        "PFLAUME", "TRAUBE", "MELONE", "ANANAS", "MANGO", "KIWI", "PFIRSICH", "APRIKOSE", "BROT", "BRÖTCHEN",
        "TOAST", "BREZEL", "KUCHEN", "KEKS", "KUCHENSTÜCK", "TORTE", "EIS", "JOGHURT", "QUARK", "MILCH",
        "KÄSE", "BUTTER", "MARMELADE", "HONIG", "NUSS", "MANDEL", "HASELNUSS", "WALNUSS", "SUPPE", "EINTOPF",
        "NUDELN", "SPAGHETTI", "REIS", "KARTOFFEL", "POMMES", "BREI", "MÜSLI", "CORNFLAKES", "EI", "OMELETT",
        "WURST", "SCHINKEN", "FLEISCH", "HÄHNCHEN", "FISCH", "SALAT", "GURKE", "TOMATE", "PAPRIKA", "KAROTTE",
        "MOHRE", "ERBSE", "BOHNE", "MAIS", "SPINAT", "KOHL", "BROKKOLI", "BLUMENKOHL", "ZWIEBEL", "KNOBLAUCH",
        "SAFT", "WASSER", "TEE", "KAKAO", "LIMONADE", "SCHORLE", "SMOOTHIE", "SUPPE", "SOSE", "KETCHUP",
        "MAJONÄSE", "SENF", "PIZZA", "BURGER", "HOTDOG", "SANDWICH", "WRAP", "PFANNKUCHEN", "WAFFEL", "CRÊPE",
        "SCHOKOLADE", "BONBON", "LITSCHI", "GUMMIBÄRCHEN", "POPCORN", "CHIPS", "BREZELSTANGE", "LAUGEN", "CROISSANT", "DONUT"
    ],

    sport: [
        "BALL", "FUSSBALL", "TOR", "TORWART", "STURM", "ABWEHR", "MITTELFELD", "SCHIEDSRICHTER", "PFEIFE", "GELBKARTE",
        "ROTKARTE", "ECKBALL", "ELFMETER", "ABSEIT", "TRAINING", "TRAINER", "MANNSCHAFT", "TEAM", "SPIELER", "KAPITÄN",
        "LAUFEN", "SPRINTEN", "JOGGEN", "HÜPFEN", "SPRINGEN", "WEITSPRUNG", "HOCHSPRUNG", "TURNEN", "TURNHALLE", "MATTE",
        "RECK", "BARREN", "PFERD", "BODEN", "KASTEN", "BANK", "SEIL", "SPRINGSEIL", "REIFEN", "KEGEL",
        "SCHWIMMEN", "BECKEN", "BAHN", "STARTBLOCK", "KRAULEN", "RÜCKEN", "BRUST", "DELFIN", "TAUCHEN", "WASSERBALL",
        "RAD", "FAHRRAD", "RENNRAD", "HELM", "PEDAL", "LENKER", "KETTE", "SKATEBOARD", "ROLLER", "INLINER",
        "EIS", "SCHLITTSCHUH", "EISHOCKEY", "SCHLÄGER", "PUCK", "SKI", "SNOWBOARD", "RODELN", "SCHLITTEN", "LANGLAUF",
        "TENNIS", "TISCHTENNIS", "BADMINTON", "VOLLEYBALL", "BASKETBALL", "HANDBALL", "HOCKEY", "GOLF", "BASEBALL", "RUGBY",
        "KAMPFSPORT", "JUDO", "KARATE", "BOXEN", "FECHTEN", "BOGEN", "PFEIL", "WURFSCHEIBE", "SPEER", "KUGEL",
        "MEDAILLE", "POKAL", "SIEG", "PLATZ", "REKORD", "START", "ZIEL", "RUNDE", "WETTKAMPF", "OLYMPIA"
    ],

    natur: [
        "BAUM", "AST", "BLATT", "WURZEL", "RINDE", "WALD", "WIESE", "FELD", "ACKER", "BERG",
        "HÜGEL", "TAL", "FLUSS", "BACH", "SEE", "TEICH", "MEER", "STRAND", "SAND", "STEIN",
        "FELS", "HÖHLE", "WOLKE", "REGEN", "SCHNEE", "HAGEL", "NEBEL", "SONNE", "MOND", "STERN",
        "HIMMEL", "WIND", "STURM", "GEWITTER", "BLITZ", "DONNER", "REGENBOGEN", "TAU", "REIF", "FROST",
        "BLUME", "ROSE", "TULPE", "GÄNSEBLÜMCHEN", "SONNENBLUME", "GRAS", "MOOS", "FARN", "PILZ", "BEERE",
        "EICHEL", "KIEFER", "TANNE", "BUCHE", "EICHE", "BIRKE", "WEIDE", "STRAUCH", "HECKE", "GARTEN",
        "PARK", "PFAD", "WEG", "BRÜCKE", "INSEL", "HALBINSEL", "KÜSTE", "BUCHT", "HAFEN", "LEUCHTTURM",
        "VULKAN", "LAVA", "ERDE", "BODEN", "LEHM", "TON", "KIES", "KIESEL", "MUSCHEL", "SCHNECKE",
        "INSEKT", "VOGEL", "TIER", "PFLANZE", "SAAT", "SAME", "KNÖSPE", "BLÜTE", "FRUCHT", "ERNTE",
        "FRÜHLING", "SOMMER", "HERBST", "WINTER", "JAHRESZEIT", "TAG", "NACHT", "MORGEN", "ABEND", "DÄMMERUNG"
    ],

    zuhause: [
        "HAUS", "WOHNUNG", "ZIMMER", "KÜCHE", "BAD", "WC", "FLUR", "DIELE", "KELLER", "DACHBODEN",
        "DACH", "FENSTER", "TÜR", "SCHLÜSSEL", "KLINGEL", "TREPPE", "AUFZUG", "BALKON", "TERRASSE", "GARTEN",
        "TISCH", "STUHL", "SOFA", "SESSEL", "BETT", "SCHRANK", "REGAL", "KOMMODE", "NACHTTISCH", "SPIEGEL",
        "LAMPE", "LICHT", "KERZE", "TEPPICH", "VORHANG", "GARDINE", "KISSEN", "DECKE", "LAKEN", "MATRATZE",
        "HERD", "BACKOFEN", "MIKROWELLE", "KÜHLSCHRANK", "SPÜLE", "SPÜLMASCHINE", "TOASTER", "WASSERKOCHER", "MIXER", "TOPF",
        "PFANNE", "TELLER", "TASSE", "BECHER", "GLAS", "MESSER", "GABEL", "LÖFFEL", "SCHÜSSEL", "BRETT",
        "WASCHMASCHINE", "TROCKNER", "BÜGELEISEN", "STAUBSAUGER", "BESEN", "WISCHER", "EIMER", "MÜLLEIMER", "MÜLL", "RECYCLING",
        "FERNSEHER", "RADIO", "COMPUTER", "TABLET", "TELEFON", "HANDY", "LAUTSPRECHER", "UHR", "WECKER", "KALENDER",
        "BILD", "FOTO", "POSTER", "PFLANZE", "BLUMENTOPF", "AQUARIUM", "KÄFIG", "SPIELZEUG", "PUPPE", "BALL",
        "FAMILIE", "MUTTER", "VATER", "SCHWESTER", "BRUDER", "OMA", "OPA", "KIND", "BABY", "HAUSTIER"
    ],

    fahrzeuge: [
        "AUTO", "PKW", "BUS", "LASTWAGEN", "LKW", "TRANSPORTER", "VAN", "TAXI", "POLIZEI", "FEUERWEHR",
        "KRANKENWAGEN", "RETTUNG", "MOTORRAD", "ROLLER", "MOPED", "FAHRRAD", "RENNRAD", "MOUNTAINBIKE", "TRETROLLER", "SKATEBOARD",
        "ZUG", "BAHN", "SBAHN", "UBAHN", "STRASSENBAHN", "TRAM", "LOK", "WAGGON", "BAHNHOF", "GLEIS",
        "FLUGZEUG", "FLIEGER", "HUBSCHRAUBER", "DROHNE", "BALLON", "ZEPPELIN", "RAKETE", "RAUMSCHIFF", "SATELLIT", "FLUGHAFEN",
        "SCHIFF", "BOOT", "SEGELBOOT", "MOTORBOOT", "FÄHRE", "KREUZFAHRTSCHIFF", "UBOOT", "KANU", "KAJAK", "FLOSS",
        "TRAKTOR", "MÄHDRESCHER", "BAGGER", "KRAN", "WALZE", "RADLADER", "GABELSTAPLER", "BULLE", "PLANIER", "KIPPER",
        "RENNWAGEN", "FORMEL", "GOKART", "QUAD", "SNOWMOBIL", "SCHLITTEN", "KUTSCHE", "WAGEN", "KARREN", "ANHÄNGER",
        "REIFEN", "RAD", "LENKER", "PEDAL", "BREMSE", "MOTOR", "AUSPUFF", "SCHEINWERFER", "HUPE", "SITZ",
        "HELM", "GURT", "KINDERSITZ", "NAVIGATION", "KARTE", "STRASSE", "AUTOBAHN", "KREUZUNG", "AMPEL", "ZEBRASTREIFEN",
        "PARKPLATZ", "GARAGE", "TANKSTELLE", "WERKSTATT", "REIFENWECHSEL", "TÜV", "KENNZEICHEN", "NUMMERNSCHILD", "FÜHRERSCHEIN", "TICKET"
    ]
};

// Deduplizieren & normalisieren
Object.keys(GERMAN_WORDS_KIDS_THEMES).forEach(key => {
    const arr = GERMAN_WORDS_KIDS_THEMES[key];
    if (!arr) return;
    const seen = new Set();
    GERMAN_WORDS_KIDS_THEMES[key] = arr
        .map(w => String(w).toUpperCase().normalize("NFC").trim())
        .filter(w => w && !w.includes("ß") && !w.includes("ẞ") && !seen.has(w) && (seen.add(w), true));
});

const KIDS_THEME_LABELS = {
    gemischt: "🎲 Gemischt",
    tiere: "🐾 Tiere",
    schule: "📚 Schule",
    essen: "🍎 Essen",
    sport: "⚽ Sport",
    natur: "🌿 Natur",
    zuhause: "🏠 Zuhause",
    fahrzeuge: "🚗 Fahrzeuge"
};

if (typeof window !== "undefined") {
    window.GERMAN_WORDS_KIDS_THEMES = GERMAN_WORDS_KIDS_THEMES;
    window.KIDS_THEME_LABELS = KIDS_THEME_LABELS;
}
